# Project Alpha: RL Bot v63p

## 📋 TODO & Roadmap
- **Data Policy:** Should we apply `handle_zeros_as_nan` globally to all matrices?
- **Feature Scaling:** Finalize the `get_agent_view` dual-view scaling logic.
- **Performance:** Move heavy logic (`analyze_4d_regime`) into `core` modular library.

<details>
<summary><b>📜 Version History (v59 - v63)</b></summary>

### v63
- Added **Metric Registry** (Strong-typed, dual-view).
- Fixed **Index Poisoning** bug (Dates in Ticker column).
- Unified **Perception** and **Execution** in Audit packs.
- Added 4 New Pillars: Return Autocorr, Range Position, OBV Divergence, Convexity.

### v62
- Fixed **Object Reference Mutation** bug in `compute_alpha_ensemble`.
- Added `PostBuildVerifier`, `DeepDiveDebugger`, and `ForensicExporter`.

### v61
- Verified all metrics with Excel parity.
- Refactored `AlphaEngine` into Orchestrator pattern.

### v60
- Converted notebook code to modular system.
- Added Volatility Regime plots.

### v59
- Implemented **Result Pattern** for error handling.
- Switched to logarithmic returns globally.
</details>

## I. Initialization & Environment

In [1]:
# 1. Setup & Path
%load_ext autoreload
%autoreload 2

import sys
import os
import gc
import pandas as pd
import numpy as np
import multiprocessing
import random
import re
import time
from pathlib import Path
from dataclasses import dataclass
from typing import Literal, Optional
from types import SimpleNamespace
from IPython.display import display, clear_output
from tqdm.notebook import tqdm
import plotly.io as pio

def add_project_root_to_path():
    current = Path.cwd()
    for path in [current] + list(current.parents):
        if path.name == "notebooks_RLVR":
            sys.path.insert(0, str(path))
            return path
        candidate = path / "notebooks_RLVR"
        if candidate.exists():
            sys.path.insert(0, str(candidate))
            return candidate
    raise RuntimeError("Could not find notebooks_RLVR directory")

add_project_root_to_path()

# 2. Display Settings
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.precision", 4)

# 3. Project Imports
from core.analyzer import create_walk_forward_analyzer, run_headless_simulation
from core.auditor import SystemAuditor as SA
from core.builder import ParallelFeatureBuilder, FeatureCubeStitcher
from core.contracts import FilterPack, EngineInput, MarketObservation
from core.engine import AlphaEngine, AlphaCache
from core.environment import DiscoveryEnv
from core.features import generate_features
from core.logic import AlphaLogic
from core.paths import OUTPUT_DIR
from core.quant import QuantUtils, TickerEngine
from core.settings import GLOBAL_SETTINGS
from core.utils import SystemUtils as SU
from strategy.registry import STRATEGY_REGISTRY

# 4. Load Environment Paths
DATA_DIR = SU.load_env_from_root("DATA_DIR")
DATA_PATH_OHLCV = SU.load_env_from_root("DATA_PATH_OHLCV")
DATA_PATH_INDICES = SU.load_env_from_root("DATA_PATH_INDICES")
print(f"✓ Paths Initialized.\nDATA Dir: {DATA_DIR}\nOHLCV: {DATA_PATH_OHLCV}\nIndices: {DATA_PATH_INDICES}")

NOTEBOOKS_RLVR_ROOT: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR

OUTPUT_DIR: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output

✓ Paths Initialized.
DATA Dir: c:\Users\ping\Files_win10\python\py311\stocks\data\
OHLCV: c:\Users\ping\Files_win10\python\py311\stocks\data\df_OHLCV_stocks_etfs.parquet
Indices: c:\Users\ping\Files_win10\python\py311\stocks\data\df_indices.parquet

## II. Data Pipeline

In [2]:
# === RELOADING FROM PARQUET ===
features_df = pd.read_parquet("output/features_df.parquet")
macro_df = pd.read_parquet("output/macro_df.parquet")
df_close_wide = pd.read_parquet("output/df_close_wide.parquet")
df_atrp_wide = pd.read_parquet("output/df_atrp_wide.parquet")
df_trp_wide = pd.read_parquet("output/df_trp_wide.parquet")

df_indices = pd.read_parquet(DATA_PATH_INDICES, engine="pyarrow")
df_ohlcv = pd.read_parquet(DATA_PATH_OHLCV, engine="pyarrow")
df_fed = pd.read_parquet(
    OUTPUT_DIR / "High_Yield_Spread_T10Y2Y_Spread.parquet", engine="pyarrow"
)

In [3]:
print("⏳ Loading DataFrames... takes ~6 minutes")
df_indices = pd.read_parquet(DATA_PATH_INDICES, engine="pyarrow")
df_ohlcv = pd.read_parquet(DATA_PATH_OHLCV, engine="pyarrow")
df_fed = pd.read_parquet(
    OUTPUT_DIR / "High_Yield_Spread_T10Y2Y_Spread.parquet", engine="pyarrow"
)

print("⚡ Generating Features...")
features_df, macro_df = generate_features(
    df_ohlcv=df_ohlcv,
    df_indices=df_indices,
    df_fed=df_fed,
    benchmark_ticker=GLOBAL_SETTINGS["benchmark_ticker"],
)

print("🚀 Unstacking Wide Matrices...")
df_close_wide = df_ohlcv["Adj Close"].unstack(level=0)
df_atrp_wide = features_df["ATRP"].unstack(level=0).reindex_like(df_close_wide)
df_trp_wide = features_df["TRP"].unstack(level=0).reindex_like(df_close_wide)

if GLOBAL_SETTINGS["handle_zeros_as_nan"]:
    df_close_wide = df_close_wide.replace(0, np.nan)

df_close_wide = df_close_wide.ffill(limit=GLOBAL_SETTINGS["max_data_gap_ffill"])
df_close_wide = df_close_wide.fillna(GLOBAL_SETTINGS["nan_price_replacement"])

print(
    f"✅ Pipeline Complete. Tickers: {len(df_close_wide.columns)}, Days: {len(df_close_wide)}"
)

⏳ Loading DataFrames... takes ~6 minutes
⚡ Generating Features...
⚡ Generating Decoupled Features (Benchmark: SPY)...
🚀 Unstacking Wide Matrices...
✅ Pipeline Complete. Tickers: 1578, Days: 16194

In [4]:
# === SAVE TO PERSISTENCE SANDBOX ===
features_df.to_parquet("output/features_df.parquet", index=True)
macro_df.to_parquet("output/macro_df.parquet", index=True)
df_close_wide.to_parquet("output/df_close_wide.parquet", index=True)
df_atrp_wide.to_parquet("output/df_atrp_wide.parquet", index=True)
df_trp_wide.to_parquet("output/df_trp_wide.parquet", index=True)

## III. The Analysis Suite

In [5]:
# SINGLE SOURCE OF TRUTH
engine = AlphaEngine(
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    macro_df=macro_df,
    df_close_wide=df_close_wide,
    df_atrp_wide=df_atrp_wide,
    df_trp_wide=df_trp_wide,
)
print("🎯 Master AlphaEngine Ready.")

🎯 Master AlphaEngine Ready.

In [6]:
# Configuration for Interactive UI
_inputs = EngineInput(
    mode="Ranking",
    decision_date=pd.Timestamp("2026-04-16"),
    lookback_period=10,
    holding_period=5,
    metric="Log Price Gain",
    benchmark_ticker=GLOBAL_SETTINGS["benchmark_ticker"],
    rank_start=1,
    rank_end=3,
    debug=False,
)

analyzer1, _ = create_walk_forward_analyzer(engine, _inputs, universe_subset=None)
analyzer1.show()

DEBUG: 941 stocks passed filters on 2026-04-16

VBox(children=(HTML(value='<b>1. Timeline Configuration:</b> (Past <--- Decision ---> Future)'), HBox(children…

In [ ]:
print("--- CASCADE FILTER, TICKERS PASSED FIRST FILTER ---")
# Get decision date from last run
decision_date_last_run = FilterPack(decision_date=analyzer1.last_run.decision_date)

# 1. LAUNCH STAGE 2 (Cascade)
# universe_subset=analyzer1.last_run.tickers means "Scan the whole market"
analyzer2, stage2_pack = create_walk_forward_analyzer(
    engine,
    universe_subset=analyzer1.last_run.tickers,
    # universe_subset=None,
    filter_pack=decision_date_last_run,
)

print("🚀 Ready for Stage 2: Run Simulation for 2nd filter.")
analyzer2.show()

--- CASCADE FILTER, TICKERS PASSED FIRST FILTER ---
🚀 Ready for Stage 2: Run Simulation for 2nd filter.

VBox(children=(HTML(value='<b>1. Timeline Configuration:</b> (Past <--- Decision ---> Future)'), HBox(children…

In [8]:
# Configuration for Interactive UI
_inputs = EngineInput(
    mode="Ranking",
    decision_date=pd.Timestamp("2026-04-16"),
    lookback_period=10,
    holding_period=5,
    metric="Log Price Gain",
    benchmark_ticker=GLOBAL_SETTINGS["benchmark_ticker"],
    rank_start=1,
    rank_end=3,
    debug=True,
)

print("--- 🤖 RL AGENT HEADLESS VIEW ---")
metrics_df = run_headless_simulation(engine, _inputs)
display(metrics_df)
print(f"\nTarget Reward Signal: {metrics_df.loc['Group Gain', 'Holding']:.6f}")

--- 🤖 RL AGENT HEADLESS VIEW ---
DEBUG: 941 stocks passed filters on 2026-04-16
----------------------------------------------------------------------
Timeline: [2026-04-01] -> Decision: 2026-04-16 -> Entry: 2026-04-17 -> End: 2026-04-24
Selected Tickers (3):
SOXL, CRDO, NBIS
----------------------------------------------------------------------

                            Full  Lookback  Holding
Metric
Group Gain                0.6818    0.5047   0.1557
Benchmark Gain            0.0858    0.0684   0.0053
== Gain Delta             0.5960    0.4363   0.1504
Group Sharpe             23.1077   24.1712  38.7616
Benchmark Sharpe         10.9495   14.0962   2.3401
== Sharpe Delta          12.1582   10.0750  36.4215
Group Sharpe (ATRP)       0.6272    0.6934   0.5230
Benchmark Sharpe (ATRP)   0.3892    0.4683   0.0879
== Sharpe (ATRP) Delta    0.2380    0.2251   0.4351
Group Sharpe (TRP)        0.5379    0.6064   0.4259
Benchmark Sharpe (TRP)    0.4575    0.5606   0.1070
== Sharpe (TRP) Delta     0.0804    0.0457   0.3190

Target Reward Signal: 0.155737

In [9]:
##################################
##################################
##################################

In [23]:
result = SU.visualize_analyzer_structure(analyzer=analyzer2)

====================================================================
🔍 HIGH-TRANSPARENCY AUDIT MAP
====================================================================
[  0] 📦 audit_pack (EngineOutput)
[  1]   📈 portfolio_series (shape=(49,))
[  2]   📈 benchmark_series (shape=(49,))
[  3]   🧮 normalized_plot_data (shape=(49, 50))
[  4]   📂 tickers (len=50)
[  5]     📄 index_0 (str)
[  6]     📄 index_1 (str)
[  7]     📄 index_2 (str)
[  8]     📄 index_3 (str)
[  9]     📄 index_4 (str)
[ 10]     📄 index_5 (str)
[ 11]     📄 index_6 (str)
[ 12]     📄 index_7 (str)
[ 13]     📄 index_8 (str)
[ 14]     📄 index_9 (str)
[ 15]     📄 index_10 (str)
[ 16]     📄 index_11 (str)
[ 17]     📄 index_12 (str)
[ 18]     📄 index_13 (str)
[ 19]     📄 index_14 (str)
[ 20]     📄 index_15 (str)
[ 21]     📄 index_16 (str)
[ 22]     📄 index_17 (str)
[ 23]     📄 index_18 (str)
[ 24]     📄 index_19 (str)
[ 25]     📄 index_20 (str)
[ 26]     📄 index_21 (str)
[ 27]     📄 index_22 (str)
[ 28]     📄 index_23 (str)
[ 29]     📄 index_24 (str)
[ 30]     📄 index_25 (str)
[ 31]     📄 index_26 (str)
[ 32]     📄 index_27 (str)
[ 33]     📄 index_28 (str)
[ 34]     📄 index_29 (str)
[ 35]     📄 index_30 (str)
[ 36]     📄 index_31 (str)
[ 37]     📄 index_32 (str)
[ 38]     📄 index_33 (str)
[ 39]     📄 index_34 (str)
[ 40]     📄 index_35 (str)
[ 41]     📄 index_36 (str)
[ 42]     📄 index_37 (str)
[ 43]     📄 index_38 (str)
[ 44]     📄 index_39 (str)
[ 45]     📄 index_40 (str)
[ 46]     📄 index_41 (str)
[ 47]     📄 index_42 (str)
[ 48]     📄 index_43 (str)
[ 49]     📄 index_44 (str)
[ 50]     📄 index_45 (str)
[ 51]     📄 index_46 (str)
[ 52]     📄 index_47 (str)
[ 53]     📄 index_48 (str)
[ 54]     📄 index_49 (str)
[ 55]   📈 initial_weights (shape=(50,))
[ 56]   📂 perf_metrics (len=24)
[ 57]     🔢 full_p_gain (float)
[ 58]     🔢 full_p_sharpe (float)
[ 59]     🔢 full_p_sharpe_atrp (float)
[ 60]     🔢 full_p_sharpe_trp (float)
[ 61]     🔢 lookback_p_gain (float)
[ 62]     🔢 lookback_p_sharpe (float)
[ 63]     🔢 lookback_p_sharpe_atrp (float)
[ 64]     🔢 lookback_p_sharpe_trp (float)
[ 65]     🔢 holding_p_gain (float)
[ 66]     🔢 holding_p_sharpe (float)
[ 67]     🔢 holding_p_sharpe_atrp (float)
[ 68]     🔢 holding_p_sharpe_trp (float)
[ 69]     🔢 full_b_gain (float)
[ 70]     🔢 full_b_sharpe (float)
[ 71]     🔢 full_b_sharpe_atrp (float)
[ 72]     🔢 full_b_sharpe_trp (float)
[ 73]     🔢 lookback_b_gain (float)
[ 74]     🔢 lookback_b_sharpe (float)
[ 75]     🔢 lookback_b_sharpe_atrp (float)
[ 76]     🔢 lookback_b_sharpe_trp (float)
[ 77]     🔢 holding_b_gain (float)
[ 78]     🔢 holding_b_sharpe (float)
[ 79]     🔢 holding_b_sharpe_atrp (float)
[ 80]     🔢 holding_b_sharpe_trp (float)
[ 81]   🧮 results_df (shape=(50, 2))
[ 82]   📅 start_date (Timestamp)
[ 83]   📅 decision_date (Timestamp)
[ 84]   📅 buy_date (Timestamp)
[ 85]   📅 holding_end_date (Timestamp)
[ 86]   📈 portfolio_atrp_series (shape=(49,))
[ 87]   📈 benchmark_atrp_series (shape=(49,))
[ 88]   📈 portfolio_trp_series (shape=(49,))
[ 89]   📈 benchmark_trp_series (shape=(49,))
[ 90]   📄 error_msg (NoneType)
[ 91]   📂 debug_data (len=9)
[ 92]     📂 audit_liquidity (len=3)
[ 93]       📄 mode (str)
[ 94]       🔢 tickers_passed (int)
[ 95]       🔢 forced_list (bool)
[ 96]     🧮 full_universe_ranking (shape=(100, 16))
[ 97]     📂 meta (len=4)
[ 98]       🔢 dropped_count (int)
[ 99]       📂 dropped_tickers (len=0)
[100]       🔢 clean_count (int)
[101]       📄 selection_range (str)
[102]     📦 inputs_snapshot (EngineInput)
[103]       📄 mode (str)
[104]       📅 decision_date (Timestamp)
[105]       🔢 lookback_period (int)
[106]       🔢 holding_period (int)
[107]       📄 metric (str)
[108]       📄 benchmark_ticker (str)
[109]       🔢 rank_start (int)
[110]       🔢 rank_end (int)
[111]       📂 quality_thresholds (len=4)
[112]         🔢 min_median_dollar_volume (int)
[113]         🔢 min_liquidity_percentile (float)
[114]         🔢 max_stale_pct (float)
[115]         🔢 max_same_vol_count (int)
[116]       📂 manual_tickers (len=0)
[117]       🔢 debug (bool)
[118]       📂 universe_subset (len=100)
[119]         📄 index_0 (str)
[120]         📄 index_1 (str)
[121]         📄 index_2 (str)
[122]         📄 index_3 (str)
[123]         📄 index_4 (str)
[124]         📄 index_5 (str)
[125]         📄 index_6 (str)
[126]         📄 index_7 (str)
[127]         📄 index_8 (str)
[128]         📄 index_9 (str)
[129]         📄 index_10 (str)
[130]         📄 index_11 (str)
[131]         📄 index_12 (str)
[132]         📄 index_13 (str)
[133]         📄 index_14 (str)
[134]         📄 index_15 (str)
[135]         📄 index_16 (str)
[136]         📄 index_17 (str)
[137]         📄 index_18 (str)
[138]         📄 index_19 (str)
[139]         📄 index_20 (str)
[140]         📄 index_21 (str)
[141]         📄 index_22 (str)
[142]         📄 index_23 (str)
[143]         📄 index_24 (str)
[144]         📄 index_25 (str)
[145]         📄 index_26 (str)
[146]         📄 index_27 (str)
[147]         📄 index_28 (str)
[148]         📄 index_29 (str)
[149]         📄 index_30 (str)
[150]         📄 index_31 (str)
[151]         📄 index_32 (str)
[152]         📄 index_33 (str)
[153]         📄 index_34 (str)
[154]         📄 index_35 (str)
[155]         📄 index_36 (str)
[156]         📄 index_37 (str)
[157]         📄 index_38 (str)
[158]         📄 index_39 (str)
[159]         📄 index_40 (str)
[160]         📄 index_41 (str)
[161]         📄 index_42 (str)
[162]         📄 index_43 (str)
[163]         📄 index_44 (str)
[164]         📄 index_45 (str)
[165]         📄 index_46 (str)
[166]         📄 index_47 (str)
[167]         📄 index_48 (str)
[168]         📄 index_49 (str)
[169]         📄 index_50 (str)
[170]         📄 index_51 (str)
[171]         📄 index_52 (str)
[172]         📄 index_53 (str)
[173]         📄 index_54 (str)
[174]         📄 index_55 (str)
[175]         📄 index_56 (str)
[176]         📄 index_57 (str)
[177]         📄 index_58 (str)
[178]         📄 index_59 (str)
[179]         📄 index_60 (str)
[180]         📄 index_61 (str)
[181]         📄 index_62 (str)
[182]         📄 index_63 (str)
[183]         📄 index_64 (str)
[184]         📄 index_65 (str)
[185]         📄 index_66 (str)
[186]         📄 index_67 (str)
[187]         📄 index_68 (str)
[188]         📄 index_69 (str)
[189]         📄 index_70 (str)
[190]         📄 index_71 (str)
[191]         📄 index_72 (str)
[192]         📄 index_73 (str)
[193]         📄 index_74 (str)
[194]         📄 index_75 (str)
[195]         📄 index_76 (str)
[196]         📄 index_77 (str)
[197]         📄 index_78 (str)
[198]         📄 index_79 (str)
[199]         📄 index_80 (str)
[200]         📄 index_81 (str)
[201]         📄 index_82 (str)
[202]         📄 index_83 (str)
[203]         📄 index_84 (str)
[204]         📄 index_85 (str)
[205]         📄 index_86 (str)
[206]         📄 index_87 (str)
[207]         📄 index_88 (str)
[208]         📄 index_89 (str)
[209]         📄 index_90 (str)
[210]         📄 index_91 (str)
[211]         📄 index_92 (str)
[212]         📄 index_93 (str)
[213]         📄 index_94 (str)
[214]         📄 index_95 (str)
[215]         📄 index_96 (str)
[216]         📄 index_97 (str)
[217]         📄 index_98 (str)
[218]         📄 index_99 (str)
[219]     🧮 alpha_perception (shape=(943, 11))
[220]     📂 verification (len=2)
[221]       📂 p (len=4)
                  ╰── val --> [See ID 1]
[222]         📈 ret (shape=(49,))
                  ╰── atrp --> [See ID 86]
                  ╰── trp --> [See ID 88]
[223]       📂 b (len=4)
                  ╰── val --> [See ID 2]
[224]         📈 ret (shape=(49,))
                  ╰── atrp --> [See ID 87]
                  ╰── trp --> [See ID 89]
[225]     📂 portfolio_raw_components (len=4)
[226]       🧮 prices (shape=(49, 50))
[227]       🧮 atrp (shape=(49, 50))
[228]       🧮 trp (shape=(49, 50))
[229]       🧮 ohlcv_raw (shape=(2450, 5))
[230]     📂 benchmark_raw_components (len=4)
[231]       🧮 prices (shape=(49, 1))
[232]       🧮 atrp (shape=(49, 1))
[233]       🧮 trp (shape=(49, 1))
[234]       🧮 ohlcv_raw (shape=(49, 5))
              ╰── selection_audit --> [See ID 96]
[235]   🧮 macro_df (shape=(16194, 11))
[236]   📄 alpha_perception (NoneType)

In [24]:
target_tickers = SU.peek(4, result)

 ============================================================
 📍 INDEX: [4]
 🏷️  NAME:  tickers
 📂 PATH:  audit_pack -> tickers
 ============================================================

['INTC',
 'USO',
 'SOXL',
 'TSEM',
 'SNDK',
 'NOK',
 'STM',
 'RVMD',
 'STX',
 'CIEN',
 'WDC',
 'BE',
 'APA',
 'ONTO',
 'PBR',
 'TTMI',
 'MPWR',
 'CVE',
 'ASX',
 'SOXX',
 'BP',
 'MU',
 'FIX',
 'SMH',
 'KLAC',
 'SU',
 'STLD',
 'LSCC',
 'LITE',
 'HAL',
 'EWT',
 'TER',
 'SATS',
 'GOOGL',
 'GOOG',
 'UTHR',
 'FTI',
 'ROST',
 'JBHT',
 'MKSI',
 'CMI',
 'CAT',
 'KEYS',
 'ADI',
 'JAZZ',
 'TD',
 'BG',
 'RY',
 'LRCX',
 'XBI']

In [12]:
SU.export_audit_to_excel(
    audit_pack=analyzer1.last_run, filename="Audit_Verification_Report.xlsx"
)

📂 [EXCEL AUDIT] Building full transparency report: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\Audit_Verification_Report.xlsx
✨ Audit Report Complete: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\Audit_Verification_Report.xlsx

WindowsPath('C:/Users/ping/Files_win10/python/py311/stocks/notebooks_RLVR/output/Audit_Verification_Report.xlsx')

In [13]:
##################################
##################################
##################################

In [14]:
import pathlib

# Set display width to prevent line wrapping
pd.set_option("display.width", 2000)

# Show all columns instead of truncated view
pd.set_option("display.max_columns", None)


def load_latest_finviz_parquet(data_dir: str) -> pd.DataFrame:
    path = pathlib.Path(data_dir)
    pattern = "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_df_finviz_merged_stocks_etfs.parquet"

    files = list(path.glob(pattern))

    if not files:
        print(f"DEBUG: No files matching pattern found in {path.absolute()}")
        return None

    latest_path = max(files, key=lambda x: x.name)
    print(f"DEBUG: Loading file: {latest_path.name}")

    try:
        return pd.read_parquet(latest_path)
    except Exception as e:
        print(f"DEBUG: Failed to read {latest_path.name}. Error: {e}")
        return None


# Usage
df_finviz = load_latest_finviz_parquet(DATA_DIR)
print(f"df_finviz:\n{df_finviz}")

DEBUG: Loading file: 2026-05-06_df_finviz_merged_stocks_etfs.parquet
df_finviz:
       No.                                            Company               Index                  Sector                        Industry Country Exchange                                               Info  MktCap AUM, M  Rank  Market Cap, M    P/E  Fwd P/E   PEG    P/S    P/B    P/C  P/FCF  Book/sh  Cash/sh  Dividend %  Dividend TTM Dividend Ex Date  Payout Ratio %    EPS  EPS next Q  EPS this Y %  EPS next Y %  EPS past 5Y %  EPS next 5Y %  Sales past 5Y %  Sales Q/Q %  EPS Q/Q %  EPS YoY TTM %  Sales YoY TTM %  Sales, M  Income, M  EPS Surprise %  Revenue Surprise %  Outstanding, M  Float, M  Float %  Insider Own %  Insider Trans %  Inst Own %  Inst Trans %  Short Float %  Short Ratio  Short Interest, M  ROA %   ROE %  ROIC %  Curr R  Quick R  LTDebt/Eq  Debt/Eq  Gross M %  Oper M %  Profit M %  Perf 3D %  Perf Week %  Perf Month %  Perf Quart %  Perf Half %  Perf Year %  Perf YTD %  Beta    ATR  ATR/Price %  Volatility W %  Volatility M %  SMA20 %  SMA50 %  SMA200 %  50D High %  50D Low %  52W High %  52W Low %        52W Range  All-Time High %  All-Time Low %    RSI  Earnings    IPO Date Optionable Shortable  Employees  Change from Open %  Gap %  Recom  Avg Volume, M  Rel Volume     Volume  Target Price  Prev Close    Open    High     Low   Price  Change %                            Single Category         Asset Type  Expense %  Holdings  AUM, M  Flows 1M, M  Flows% 1M  Flows 3M, M  Flows% 3M  Flows YTD, M  Flows% YTD  Return% 1Y  Return% 3Y  Return% 5Y                                               Tags  Sharpe 3d  Sortino 3d  Omega 3d  Sharpe 5d  Sortino 5d  Omega 5d  Sharpe 10d  Sortino 10d  Omega 10d  Sharpe 15d  Sortino 15d  Omega 15d  Sharpe 30d  Sortino 30d  Omega 30d  Sharpe 60d  Sortino 60d  Omega 60d  Sharpe 120d  Sortino 120d  Omega 120d  Sharpe 250d  Sortino 250d  Omega 250d
NVDA     1                                        NVIDIA Corp  DJIA, NDX, S&P 500              Technology                  Semiconductors     USA     NASD                         Technology, Semiconductors      5050270.0     1      5050270.0  42.40      NaN  0.47  23.39  32.11  80.73  60.36     6.47     2.57        0.02          0.04        3/11/2026            0.82   4.90        1.74           NaN           NaN            NaN            NaN              NaN        73.21      96.65          66.12            65.47  215940.0   120070.0            5.52                3.03         24300.0   23370.0    96.17           3.81            -0.29       68.43          0.14           1.21         1.65             283.34  75.42  101.49   71.75    3.91     3.24       0.06     0.07      71.07     60.38       55.60     4.7266        -0.68         16.69         19.31         0.46        83.05       11.44  2.25   6.58       3.1660            3.88            2.99     3.67    10.71     12.78       -4.15      26.52       -4.15      87.53  110.82 - 216.82            -4.15       623389.97  60.81  May 20/a   1/22/1999        Yes       Yes    42000.0                3.93   1.77   1.29       171.9000        1.08  185827317        269.82      196.50  199.97  208.26  198.61  207.83      5.77                                                                      NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -     7.8610     52.4621    5.6737     5.2106     28.3038    3.6134      2.2362       4.2837     1.4492      2.0044       3.7115     1.4061      3.3568       6.1130     1.7687      1.2057       1.8057     1.2179       0.4795        0.7078      1.0806       1.7427        2.7323      1.3307
GOOG     2                                       Alphabet Inc        NDX, S&P 500  Communication Services  Internet Content & Information     USA     NASD  Communication Services, Internet Content & Inf...      4815920.0     2      4815920.0  30.91      NaN  1.65  11.38  10.00  37.97  74.75    39.51    10.41        0.22          0.84         6/8/2026            7.68  12.78        2.87           NaN           NaN            NaN            NaN              NaN        22.34      70.31          46.22            17.77  423170.0   160210.0           90.44                2.74          5460.0    5070.0    92.85          58.19            -0.03       27.08          0.65           0.82         2.04              41.39  27.17   38.88   28.04    1.92     1.92       0.19     0.22      60.43     33.63       37.86     3.1105        13.77         30.01         18.54        39.08       139.19       25.92  1.26   9.72       2.4599            2.84            2.30    13.88    24.00     39.00        1.59      45.52        1.59     164.33  149.49 - 388.96             1.59         1525.34  82.83  Apr 29/a   3/27/2014        Yes       Yes   190820.0                1.50   1.31   1.37        20.3100        1.10   22241157        422.86      384.27  389.30  396.38  387.10  395.14      2.83                                                                      NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -    28.0182   9473.0093  844.9227     8.4983     28.2862    4.5637      8.6682      85.0440    13.1087      7.0118      34.6003     5.3693      6.9306      20.4712     3.9433      2.7603       5.9125     1.6734       2.2411        4.2659      1.4897       3.3280        6.6610      1.7982
GOOGL    3                                       Alphabet Inc        NDX, S&P 500  Communication Services  Internet Content & Information     USA     NASD  Communication Services, Internet Content & Inf...      4799310.0     3      4799310.0  31.14      NaN  1.66  11.34  10.07  37.84  74.49    39.51    10.52        0.22          0.84         6/8/2026            7.68  12.78        2.88           NaN           NaN            NaN            NaN              NaN        22.34      70.31          46.22            17.77  423170.0   160210.0           90.52                2.73          5820.0    5800.0    99.65          52.10            -0.04       38.52          0.65           1.35         2.51              78.07  27.17   38.88   28.04    1.92     1.92       0.19     0.22      60.43     33.63       37.86     3.2021        13.75         30.31         19.52        40.29       143.85       27.17  1.27   9.94       2.4972            2.72            2.32    13.93    24.33     40.06        1.33      46.28        1.33     169.24  147.84 - 392.82             1.33        16475.85  83.47  Apr 29/a   8/19/2004        Yes       Yes   190820.0                0.91   1.55   1.36        31.1100        1.00   31097267        423.24      388.43  394.47  399.85  392.76  398.04      2.47                                                                      NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -    37.9403   9473.0093  844.9227     9.8776     41.1342    6.1824      9.0471     129.7867    20.9942      6.9876      34.9009     5.5958      6.8710      19.7857     3.8478      2.7956       5.8812     1.6809       2.2778        4.3150      1.5015       3.3216        6.6234      1.7971
AAPL     4                                          Apple Inc  DJIA, NDX, S&P 500              Technology            Consumer Electronics     USA     NASD                   Technology, Consumer Electronics      4222760.0     4      4222760.0  34.78      NaN  2.47   9.35  39.60  61.64  32.69     7.26     4.66        0.38          1.04        5/11/2026           13.66   8.27        1.87           NaN           NaN            NaN            NaN              NaN        16.60      22.04          28.91            12.76  451440.0   122580.0            3.30                1.58         14670.0   14660.0    99.97           0.12            -0.57       66.03          0.35           0.92         3.05             134.42  34.91  141.47   67.76    1.07     1.02       0.70     0.80      47.86     32.64       27.15     2.6308         6.42         13.42          3.99         6.86        44.83        5.76  1.06   6.67       2.3199            2.72            2.05     6.40     9.68     12.20        0.10      17.11       -0.38      48.78  193.25 - 288.62            -0.38       451846.01  69.41  Apr 30/a  12/12/1980        Yes       Yes   166000.0                1.94  -0.75   1.89        44.1000        1.30   57493987        305.80      284.18  282.05  288.03  281.07  287.51      1.17                                                                      NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -    28.7204   9473.0093  844.9227    11.7209     38.5862    5.8614      5.4002      13.3578     2.3945      5.6930      11.5536     2.4315      4.3833       8.5290     2.0238      0.7803       1.1261     1.1385       0.4133        0.6078      1.0746       1.5926        2.6441      1.3309
MSFT     5                                     Microsoft Corp  DJIA, NDX, S&P 500              Technology       Software - Infrastructure     USA     NASD              Technology, Software - Infrastructure      3075070.0     5      3075070.0  24.66      NaN  1.14   9.66   7.42  39.29  42.17    55.78    10.54        0.89          3.48        5/21/2026           24.34  16.79        4.25           NaN           NaN            NaN            NaN              NaN        18.30      23.32          29.64            17.87  318270.0   125220.0            5.18                1.77          7430.0    7310.0    98.46           1.53            -0.02       75.20          0.38           1.14         2.39              83.41  19.93   34.01   24.02    1.28     1.27       0.26     0.30      68.31     46.80       39.34    -0.1158        -2.47         11.19         -0.06       -19.94        -4.47      -14.40  1.09  11.07       2.6742            2.68            2.51     0.59     4.15    -11.27       -4.55      16.19      -25.47      16.19  356.28 - 555.45           -25.47       519436.97  54.07  Apr 29/a   3/13/1986        Yes       Yes   228000.0                1.61  -0.96   1.22        34.9500        0.86   30174359        558.68      411.38  407.42  418.42  405.11  413.96      0.63                                                                      NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -     0.5172      1.0844    1.0966     5.9714     19.3775    2.8900     -0.4369      -0.5665     0.9241     -0.8626      -1.0729     0.8648      3.0565       4.9547     1.6737      0.0503       0.0726     1.0085      -1.4609       -1.7907      0.7698      -0.2606       -0.3367      0.9533
...    ...                                                ...                 ...                     ...                             ...     ...      ...                                                ...            ...   ...            ...    ...      ...   ...    ...    ...    ...    ...      ...      ...         ...           ...              ...             ...    ...         ...           ...           ...            ...            ...              ...          ...        ...            ...              ...       ...        ...             ...                 ...             ...       ...      ...            ...              ...         ...           ...            ...          ...                ...    ...     ...     ...     ...      ...        ...      ...        ...       ...         ...        ...          ...           ...           ...          ...          ...         ...   ...    ...          ...             ...             ...      ...      ...       ...         ...        ...         ...        ...              ...              ...             ...    ...       ...         ...        ...       ...        ...                 ...    ...    ...            ...         ...        ...           ...         ...     ...     ...     ...     ...       ...                                        ...                ...        ...       ...     ...          ...        ...          ...        ...           ...         ...         ...         ...         ...                                                ...        ...         ...       ...        ...         ...       ...         ...          ...        ...         ...          ...        ...         ...          ...        ...         ...          ...        ...          ...           ...         ...          ...           ...         ...
EMLC   393      VanEck J.P. Morgan EM Local Currency Bond ETF                   -               Financial            Exchange Traded Fund     USA     NYSE  Financial, Exchange Traded Fund, Bonds - Treas...         4830.0  1554            NaN    NaN      NaN   NaN    NaN    NaN    NaN    NaN      NaN      NaN        6.07          1.55         5/1/2026             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN       NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         1.21               5.89    NaN     NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     0.8261         0.87          1.87         -2.44         1.02         4.70       -0.74  0.38   0.18       0.7023            0.48            0.47    -0.39     0.25      0.02       -3.76       3.35       -3.76       5.93    24.19 - 26.63           -54.17           15.17  51.13         -   7/23/2010        Yes       Yes        NaN                0.35   0.71    NaN         4.8500        1.03    5010891           NaN       25.36   25.54   25.64   25.54   25.63      1.06              Bonds - Treasury & Government              Bonds       0.30     516.0  4830.0          NaN       0.24          NaN       0.84        730.40       17.82       10.35        6.69        1.50      Emerging, fixed-income, currency-bonds, bonds    22.0071   9473.0093  844.9227     4.3258      9.8850    2.1922      0.6289       0.9958     1.1088     -1.5374      -2.1435     0.7817      2.1891       4.1154     1.4747     -0.9504      -1.2926     0.8491       0.3655        0.5108      1.0683       1.1272        1.6271      1.2192
UPRO   395           ProShares UltraPro S&P 500 ETF 3x Shares                   -               Financial            Exchange Traded Fund     USA     NYSE  Financial, Exchange Traded Fund, Equity - Leve...         4780.0  1555            NaN    NaN      NaN   NaN    NaN    NaN    NaN    NaN      NaN      NaN        0.73          1.01        3/25/2026             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN       NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.22               0.93    NaN     NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     5.3722         9.30         36.14         17.86        15.69        99.19       18.61  3.02   3.99       2.9060            2.59            2.51    10.86    22.05     23.06        3.57      55.77        3.57     102.28   67.88 - 132.57             3.57        13441.93  75.20         -   6/25/2009        Yes       Yes        NaN                2.29   1.80    NaN         4.3100        0.80    3429389           NaN      131.85  134.22  137.75  134.08  137.30      4.13               Equity - Leveraged / Inverse  Equities (Stocks)       0.89     521.0  4780.0          NaN      -9.47          NaN      -8.46       -550.58      -10.33       85.14       50.30       21.09                      U.S., equity, SP500, leverage    39.9828   9473.0093  844.9227    10.9793     43.2659    6.4510      9.4552      28.4280     4.7386      7.0467      17.8022     2.9643      5.8219      11.6415     2.7436      1.5011       2.3462     1.2794       0.9185        1.3501      1.1640       1.8914        2.9030      1.3801
REET   396                            iShares Global REIT ETF                   -               Financial            Exchange Traded Fund     USA     NYSE  Financial, Exchange Traded Fund, Global or ExU...         4770.0  1556            NaN    NaN      NaN   NaN    NaN    NaN    NaN    NaN      NaN      NaN        3.33          0.92        3/17/2026             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN       NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.27               0.63    NaN     NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     1.1368         2.80          7.48          6.40         9.31        12.85       10.54  0.96   0.34       1.2328            1.07            1.08     2.10     4.54      7.54        0.29      11.77        0.29      15.01    23.98 - 27.50           -10.40           76.57  64.62         -   7/10/2014        Yes       Yes        NaN                0.36   1.10    NaN         2.3100        1.27    2932523           NaN       27.18   27.48   27.66   27.44   27.58      1.47  Global or ExUS Equities - Industry Sector  Equities (Stocks)       0.14     357.0  4770.0          NaN      -0.42          NaN       1.07         97.34        2.08       14.77        9.01        3.33                 Global, equity, real-estate, REITs    24.4262   9473.0093  844.9227     3.5426      7.7837    1.8220      3.0738       6.4397     1.6539      1.9644       3.3369     1.3581      5.4922      10.7190     2.4072      0.9349       1.3283     1.1688       1.4231        2.0714      1.2703       1.0795        1.5349      1.1952

In [26]:
tickers_in_df_finviz = [x for x in target_tickers if x not in ["USO", "SATS"]]
df_finviz.loc[tickers_in_df_finviz]

# df_finviz.loc[target_tickers]

       No.                                   Company          Index                  Sector                                  Industry         Country Exchange                                               Info  MktCap AUM, M  Rank  Market Cap, M     P/E  Fwd P/E   PEG    P/S     P/B      P/C   P/FCF  Book/sh  Cash/sh  Dividend %  Dividend TTM Dividend Ex Date  Payout Ratio %    EPS  EPS next Q  EPS this Y %  EPS next Y %  EPS past 5Y %  EPS next 5Y %  Sales past 5Y %  Sales Q/Q %  EPS Q/Q %  EPS YoY TTM %  Sales YoY TTM %   Sales, M  Income, M  EPS Surprise %  Revenue Surprise %  Outstanding, M  Float, M  Float %  Insider Own %  Insider Trans %  Inst Own %  Inst Trans %  Short Float %  Short Ratio  Short Interest, M  ROA %    ROE %  ROIC %  Curr R  Quick R  LTDebt/Eq  Debt/Eq  Gross M %  Oper M %  Profit M %  Perf 3D %  Perf Week %  Perf Month %  Perf Quart %  Perf Half %  Perf Year %  Perf YTD %  Beta    ATR  ATR/Price %  Volatility W %  Volatility M %  SMA20 %  SMA50 %  SMA200 %  50D High %  50D Low %  52W High %  52W Low %         52W Range  All-Time High %  All-Time Low %    RSI  Earnings    IPO Date Optionable Shortable  Employees  Change from Open %  Gap %  Recom  Avg Volume, M  Rel Volume     Volume  Target Price  Prev Close     Open     High      Low    Price  Change %                             Single Category         Asset Type  Expense %  Holdings   AUM, M  Flows 1M, M  Flows% 1M  Flows 3M, M  Flows% 3M  Flows YTD, M  Flows% YTD  Return% 1Y  Return% 3Y  Return% 5Y                                    Tags  Sharpe 3d  Sortino 3d  Omega 3d  Sharpe 5d  Sortino 5d   Omega 5d  Sharpe 10d  Sortino 10d  Omega 10d  Sharpe 15d  Sortino 15d  Omega 15d  Sharpe 30d  Sortino 30d  Omega 30d  Sharpe 60d  Sortino 60d  Omega 60d  Sharpe 120d  Sortino 120d  Omega 120d  Sharpe 250d  Sortino 250d  Omega 250d
INTC    21                                Intel Corp   NDX, S&P 500              Technology                            Semiconductors             USA     NASD                         Technology, Semiconductors       567990.0    25       567990.0     NaN      NaN  1.08  10.56    5.10    17.32     NaN    22.18     6.52        0.04           NaN         8/7/2024             NaN  -0.63        0.21           NaN           NaN            NaN            NaN              NaN         7.18    -288.04          86.07             1.36   53760.00   -3170.00         1426.32                9.33         5020.00   4250.00    84.56          15.49            -0.01       59.44          5.96           3.40         1.36             144.27  -1.60    -3.01   -2.06    2.31     1.85       0.39     0.40      35.90      2.47       -5.90    13.4411        19.27        113.59        132.53       186.10       466.75      206.26  2.19   5.67       5.0173            6.87            6.04    43.33    90.67    172.99        2.29     178.14        2.29     495.89    18.97 - 110.48             2.29        33027.44  85.92  Apr 23/a    5/3/1973        Yes       Yes    85100.0                1.88   2.57   2.62       106.3600        1.46  155236591         85.33      108.15   110.93   113.50   106.58   113.01      4.49                                                                       NaN       NaN      NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                       -    23.1624   9473.0093  844.9227    10.9491     38.8216     5.8911     11.6895      76.4468    12.9584      8.0488      39.1345     6.2259      8.1008      26.6053     4.6259      4.8472      11.8925     2.4540       3.2269        6.1180      1.8016       2.7307        5.2023      1.6632
SOXL   137  Direxion Daily Semiconductor Bull 3X ETF              -               Financial                      Exchange Traded Fund             USA     NYSE  Financial, Exchange Traded Fund, Equity - Leve...        18530.0   782            NaN     NaN      NaN   NaN    NaN     NaN      NaN     NaN      NaN      NaN        0.05          0.08        9/23/2025             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN        NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.14              11.88    NaN      NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN    27.1856        40.59        193.28        211.81       241.40      1212.10      294.60  5.55  10.29       6.2044            9.13            7.48    52.87   117.54    229.29       12.62     319.66       12.62    1268.40    12.12 - 147.26            12.62        53202.71  82.14         -   3/11/2010        Yes       Yes        NaN                5.01   9.56    NaN        84.1400        0.75   63254599           NaN      144.16   157.94   166.00   149.06   165.85     15.05                Equity - Leveraged / Inverse  Equities (Stocks)       0.75      43.0  18530.0          NaN     -29.88          NaN     -29.42     -12950.00      -41.14      988.47      117.84       30.39  U.S., equity, semiconductors, leverage   155.5311   9473.0093  844.9227    13.7274    102.8002    13.9516      8.2890      18.6239     3.4582     10.5148      23.7469     4.9092      7.8425      14.9837     3.3927      4.0457       6.5861     1.9127       3.0618        4.7721      1.6435       3.0292        4.8462      1.6713
TSEM   534                   Tower Semiconductor Ltd              -              Technology                            Semiconductors          Israel     NASD                         Technology, Semiconductors        24240.0   641        24240.0  111.85      NaN  1.03  15.48    8.36    21.04     NaN    25.94    10.31         NaN           NaN                -            0.00   1.94        0.56           NaN           NaN            NaN            NaN              NaN        13.69      43.76           5.23             9.05    1570.00     220.47           14.37                0.10          112.53    104.85    93.18           6.18             0.00       73.20          1.69           4.21         1.53               4.41   6.89     7.91    7.22    6.48     5.51       0.05     0.06      23.23     12.40       14.08    -0.5229         8.88         13.63         78.82       156.92       504.77       84.70  0.85  14.65       6.7552            7.08            6.72     2.55    23.81     93.47       -5.29     100.01       -5.29     512.19    35.42 - 228.99           -66.02        16323.84  58.75  May 13/b  10/26/1994        Yes       Yes        NaN               -6.79   3.17   1.83         2.8800        0.79    2284142        177.60      225.53   232.67   232.67   214.01   216.87     -3.84                                                                       NaN       NaN      NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                       -     1.2849      2.9020    1.2585    -1.8828     -3.2386     0.7335      3.0028       6.7395     1.6992      0.5153       0.9510     1.0880      1.9018       3.3133     1.3717      2.8168       5.3505     1.6458       2.4467        4.0855      1.5228       3.1520        5.8196      1.7530
SNDK    64                              Sandisk Corp   NDX, S&P 500              Technology                         Computer Hardware             USA     NASD                      Technology, Computer Hardware       208800.0    71       208800.0   49.01      NaN   NaN  15.84   15.15    55.90   46.82    93.09    25.22         NaN           NaN                -             NaN  28.77       32.82           NaN           NaN            NaN            NaN              NaN       251.03     272.72         395.16            82.76   13180.00    4510.00           60.09               26.06          148.00    139.17    94.03           6.02            -0.05       78.62         -8.91           7.01         0.54               9.75  30.01    39.30   32.29    4.78     3.62       0.01     0.02      56.04     41.58       34.19    18.7852        32.49         98.37        141.21       581.12      4067.84      493.98  4.83  80.03       5.6760            8.17            6.69    37.27    75.10    278.28       -0.63     172.72       -0.63    4155.90   33.13 - 1418.88            -0.63         4956.41  81.22  Apr 30/a   2/13/2025        Yes       Yes    11000.0               -1.76   2.05   1.65        18.1600        1.12   20281116       1498.27     1406.32  1435.21  1439.70  1337.56  1409.98      0.26                                                                       NaN       NaN      NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                       -    11.6931   9473.0093  844.9227    21.1748  45277.4681  5705.4248     14.3353      36.0441     7.8117      9.3956      23.6931     4.4469      7.0023      14.1069     2.9973      4.8630       8.8728     2.1013       3.6228        6.1460      1.8384       4.2936        8.1153      2.1409
NOK    228                            Nokia Corp ADR              -              Technology                   Communication Equipment         Finland     NYSE                Technology, Communication Equipment        73770.0   261        73770.0   82.28      NaN  1.92   3.18    3.02    10.98   45.07     4.36     1.20        1.34          0.21        4/28/2026             NaN   0.16        0.06           NaN           NaN            NaN            NaN              NaN        13.95     253.04           9.07            12.83   23200.00     898.25           33.18               -1.18         5590.00   5590.00   100.00           0.00              NaN       14.02          7.46           1.22         0.94              68.24   2.10     3.84    3.21    1.57     1.32       0.15     0.16      43.47      8.78        3.87    -0.8271         5.86         49.04         93.97        84.48       162.23      103.86  1.12   0.63       4.7763            5.65            5.30    18.59    40.81     98.21       -5.65      81.18       -5.65     229.75      4.00 - 13.98           -77.96          968.76  77.27  Apr 23/b    7/1/1994        Yes       Yes        NaN                0.08  -1.79   2.28        72.8700        1.65  120101196         11.11       13.42    13.18    13.54    13.01    13.19     -1.71                                                                       NaN       NaN      NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                       -     1.1249      2.5003    1.2227     3.6414      8.1451     1.7364     12.4924      62.8021     9.5173      7.7431      18.3932     3.5578      6.8962      17.1860     3.2646      5.3164      11.1754     2.3781       3.0400        5.0997      1.6849       2.3250        4.3553      1.5814
STM    313                       ST Microelectronics              -              Technology                            Semiconductors     Switzerland     NYSE                         Technology, Semiconductors        51510.0   360        51510.0  376.79      NaN  0.31   4.15    2.90    11.27  320.71    19.99     5.14        0.63          0.36        3/24/2026          164.16   0.15        0.25           NaN           NaN            NaN            NaN              NaN        23.20     -32.33         -86.68             0.79   12410.00     144.84          -25.16                1.22          888.79    888.79   100.00           0.00              NaN       10.29          2.04           1.25         1.11              11.07   0.58     0.82    0.72    3.31     2.34       0.13     0.14      33.84      3.54        1.17     3.9462        10.02         62.42         97.58       137.50       156.98      123.40  1.89   2.05       3.5375            4.11            3.35    21.45    48.04     92.38        0.49      90.78        0.49     174.51     21.11 - 57.67           -21.56         1507.86  87.32  Apr 23/b   12/8/1994        Yes       Yes    49157.0                1.56  -0.21   2.10         9.9500        1.20   11981026         56.33       57.18    57.06    58.01    55.56    57.95      1.35                                                                       NaN       NaN      NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                       -    23.8207   9473.0093  844.9227    10.0386     35.1538     5.4290     10.9651      43.9172     6.9270     11.2825      75.6653    12.3638      9.1257      35.4599     6.2944      4.6502       9.6899     2.2900       3.9993        8.0374      2.0334       2.0924        3.3097      1.4699
RVMD   436                  Revolution Medicines Inc              -              Healthcare                             Biotechnology             USA     NASD                          Healthcare, Biotechnology        32120.0   518        32120.0     NaN      NaN   NaN    NaN   18.24    15.85     NaN     8.28     9.53         NaN           NaN                -             NaN  -5.92       -1.83           NaN           NaN            NaN            NaN              NaN          NaN     -65.69         -65.84          -100.00       0.00   -1130.00          -24.75             -100.00          197.00    185.15    93.98          12.91            -1.83       83.15          0.64           7.23         4.63              13.39 -45.15   -58.07  -55.40    7.14     7.14       0.25     0.26        NaN       NaN         NaN     8.3094         7.48         56.89         56.53       154.63       303.50       89.67  1.41   7.49       4.9580            4.88            5.17     8.70    32.14     93.71       -2.97      65.07       -2.97     344.32    34.00 - 155.70            -2.97          972.94  66.39  May 06/a   2/13/2020        Yes       Yes      883.0                2.96  -0.33   1.00         2.8900        0.74    2127000        174.30      147.21   146.72   151.43   145.29   151.07      2.62                                                                       NaN       NaN      NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                       -     7.7186     49.4189    5.4026     4.8851     11.9119     2.3205      4.8770      12.6067     2.3141      0.5664       1.0045     1.0984      3.6091      16.2001     2.8455      2.3748       8.9841     2.0036       2.3654        6.3199      1.9441       2.1735        5.1733      1.7150
STX     80           Seagate Technology Holdings Plc   NDX, S&P 500              Technology                         Computer Hardware             USA     NASD                      Technology, Computer Hardware       176340.0    88       176340.0   74.65      NaN  0.45  16.02  161.17   153.74   73.11     4.88     5.12        0.37          2.92        6/24/2026           42.25  10.54        5.05           NaN           NaN            NaN            NaN              NaN        44.07     107.51          55.56            28.92   11010.00    2380.00           16.65                5.10          224.41    223.35    99.53           0.39           -21.16       84.05         -4.18           3.78         2.17               8.44  28.90  1787.97   48.78    1.33     0.85       3.45     3.82      41.54     29.46       21.60     8.1837        22.25         67.78         87.86       196.15       737.51      185.57  2.01  37.45       4.7621            5.76            5.23    30.87    63.22    149.52       -0.71     129.95       -0.71     755.55    91.92 - 792.01            -0.71        26289.93  87.03  Apr 28/a  12/11/2002        Yes       Yes    30000.0                2.29  -0.28   1.64         3.9000        1.42    5517775        800.41      771.01   768.84   787.35   752.80   786.42      2.00                                                                       NaN       NaN      NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                       -    29.7892   9473.0093  844.9227    21.6772  45277.4681  5705.4248     12.5989      55.9682    10.7617     12.7273      53.1867     9.8159      9.0261      18.9281     4.3142      4.7264       8.6129     2.0521       3.2935        5.8091      1.7076       3.6944        6.9180      1.9060
CIEN   198                                CIENA Corp        S&P 500              Technology                   Communication Equipment             USA     NYSE                Technology, Communication Equipment        81560.0   226        81560.0  366.29      NaN  0.98  15.92   29.22    62.75  109.88    19.74     9.19         NaN           NaN                -            0.00   1.57        1.46           NaN           NaN            NaN            NaN              NaN        26.75    1618.00         193.36            26.54    5120.00     229.05           15.76                2.01          141.45    139.23    98.43           1.53           -10.11      100.64         -7.15           3.37         1.39               4.69   4.00     8.20    5.26    2.81     2.14       0.56     0.57      39.48      8.19        4.47     7.7528        21.33         28.78        127.53       204.28       693.82      146.63  1.25  31.70       5.4959            5.82            6.02    13.85    34.50    136.28        2.63     107.19        2.63     716.21    70.67 - 562.00           -45.43        11482.13  71.26  Mar 05/b    2/7/1997        Yes       Yes     9080.0                2.45   3.35   2.00         3.3700        0.66    2235661        418.73      544.75   563.00   583.78   550.06   576.79      5.88                                                                       NaN       NaN      NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                       -    16.6576   9473.0093  844.9227    14.7631  45277.4681  5705.4248      4.3229       9.0422     2.2999      4.5486       9.4792     2.4059      3.3021       5.3258     1.7319      4.0248       6.2811     1.9321       3.1998        4.9127      1.7033       3.5221        5.8355      1.9218

In [16]:
print(df_finviz.loc[target_tickers])

      No.                                   Company Index      Sector                   Industry         Country Exchange                                               Info  MktCap AUM, M  Rank  Market Cap, M     P/E  Fwd P/E   PEG    P/S    P/B    P/C   P/FCF  Book/sh  Cash/sh  Dividend %  Dividend TTM Dividend Ex Date  Payout Ratio %   EPS  EPS next Q  EPS this Y %  EPS next Y %  EPS past 5Y %  EPS next 5Y %  Sales past 5Y %  Sales Q/Q %  EPS Q/Q %  EPS YoY TTM %  Sales YoY TTM %  Sales, M  Income, M  EPS Surprise %  Revenue Surprise %  Outstanding, M  Float, M  Float %  Insider Own %  Insider Trans %  Inst Own %  Inst Trans %  Short Float %  Short Ratio  Short Interest, M  ROA %  ROE %  ROIC %  Curr R  Quick R  LTDebt/Eq  Debt/Eq  Gross M %  Oper M %  Profit M %  Perf 3D %  Perf Week %  Perf Month %  Perf Quart %  Perf Half %  Perf Year %  Perf YTD %  Beta    ATR  ATR/Price %  Volatility W %  Volatility M %  SMA20 %  SMA50 %  SMA200 %  50D High %  50D Low %  52W High %  52W Low %       52W Range  All-Time High %  All-Time Low %    RSI  Earnings   IPO Date Optionable Shortable  Employees  Change from Open %  Gap %  Recom  Avg Volume, M  Rel Volume    Volume  Target Price  Prev Close    Open    High     Low   Price  Change %               Single Category         Asset Type  Expense %  Holdings   AUM, M  Flows 1M, M  Flows% 1M  Flows 3M, M  Flows% 3M  Flows YTD, M  Flows% YTD  Return% 1Y  Return% 3Y  Return% 5Y                                    Tags  Sharpe 3d  Sortino 3d  Omega 3d  Sharpe 5d  Sortino 5d  Omega 5d  Sharpe 10d  Sortino 10d  Omega 10d  Sharpe 15d  Sortino 15d  Omega 15d  Sharpe 30d  Sortino 30d  Omega 30d  Sharpe 60d  Sortino 60d  Omega 60d  Sharpe 120d  Sortino 120d  Omega 120d  Sharpe 250d  Sortino 250d  Omega 250d
SOXL  137  Direxion Daily Semiconductor Bull 3X ETF     -   Financial       Exchange Traded Fund             USA     NYSE  Financial, Exchange Traded Fund, Equity - Leve...        18530.0   782            NaN     NaN      NaN   NaN    NaN    NaN    NaN     NaN      NaN      NaN        0.05          0.08        9/23/2025             NaN   NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN       NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.14              11.88    NaN    NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN    27.1856        40.59        193.28        211.81       241.40      1212.10      294.60  5.55  10.29       6.2044            9.13            7.48    52.87   117.54    229.29       12.62     319.66       12.62    1268.40  12.12 - 147.26            12.62        53202.71  82.14         -  3/11/2010        Yes       Yes        NaN                5.01   9.56    NaN          84.14        0.75  63254599           NaN      144.16  157.94  166.00  149.06  165.85     15.05  Equity - Leveraged / Inverse  Equities (Stocks)       0.75      43.0  18530.0          NaN     -29.88          NaN     -29.42      -12950.0      -41.14      988.47      117.84       30.39  U.S., equity, semiconductors, leverage   155.5311   9473.0093  844.9227    13.7274    102.8002   13.9516      8.2890      18.6239     3.4582     10.5148      23.7469     4.9092      7.8425      14.9837     3.3927      4.0457       6.5861     1.9127       3.0618        4.7721      1.6435       3.0292        4.8462      1.6713
CRDO  403        Credo Technology Group Holding Ltd   RUT  Technology             Semiconductors  Cayman Islands     NASD                         Technology, Semiconductors        36570.0   478        36570.0  109.97      NaN  0.34  34.24  19.76  28.10  128.92    10.04     7.06         NaN           NaN                -             0.0  1.80        1.02           NaN           NaN            NaN            NaN              NaN       201.49     408.64        6897.08           226.12    1070.0     339.76           17.38                0.21          184.22    165.65    89.92          10.19            -6.50       76.02          3.73           5.58         1.27               9.24  24.65  27.54   18.25   10.82     9.56       0.01     0.01      67.83     30.32       31.81     7.5442        12.81         85.68        104.53         9.77       315.96       37.81  3.17  12.65       6.3795            7.50            7.79    16.99    50.57     43.35       -0.76     129.28       -7.25     334.37  45.65 - 213.80            -7.25         2655.94  68.13  Mar 02/a  1/27/2022        Yes       Yes      622.0                0.34   2.09   1.16           7.27        0.83   6024753        212.16      193.57  197.61  198.58  184.20  198.29      2.44                                                         NaN       NaN      NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                       -    21.9632   9473.0093  844.9227    12.2548     45.4069    6.7207      2.3697       3.7139     1.4191      5.1389       8.8135     2.1357      6.0317      12.3499     2.5649      2.1445       3.4513     1.4034       0.8976        1.3984      1.1573       2.0146        3.2238      1.3907
NBIS  327                           Nebius Group NV     -  Technology  Software - Infrastructure     Netherlands     NASD              Technology, Software - Infrastructure        49110.0   378        49110.0  382.75      NaN   NaN  91.92  10.70  13.35     NaN    18.23    14.61         NaN           NaN                -             0.0  0.51       -0.77           NaN           NaN            NaN            NaN              NaN       500.79     -70.26         373.88           354.32     534.2     101.60            5.74               -7.92          219.47    201.25    91.70          20.05            -0.27       39.93          1.04          21.68         2.67              43.63   0.25   0.50    1.07    3.08     6.57       1.05     1.06      -7.66   -113.33       19.02    26.2800        38.18         66.18        136.79        61.94       679.11      133.07  3.83  12.87       6.5970           10.25            8.27    24.86    54.13     93.58        8.41     133.56        8.41     739.10  23.25 - 179.96             8.41         1862.66  74.18  May 13/b  5/24/2011        Yes       Yes        NaN                8.52   2.19   1.76          16.32        1.17  19163820        176.85      175.92  179.77  195.99  175.11  195.09     10.90                                                         NaN       NaN      NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                       -    10.6240    396.8786   36.3568    22.5070    968.2151  122.9836      5.4010      13.5235     2.4411      3.2840       7.5017     1.8078      5.0635      10.2513     2.2216      3.5995       6.5324     1.7996       2.0035        3.3476      1.3783       2.3428        4.6347      1.5272

In [17]:
def cleanup_ui():
    clear_output(wait=True)
    pio.renderers.default = None
    gc.collect()
    print("🧹 Memory Cleared.")


def active_engine_audit():
    gc.collect()
    engines = [obj for obj in gc.get_objects() if type(obj).__name__ == "AlphaEngine"]
    print(f"Active AlphaEngine Instances: {len(engines)}")


active_engine_audit()

Active AlphaEngine Instances: 1

In [18]:
# print(features_df.info())
# display(features_df.head())
# display(df_indices.tail())

In [19]:
################################
################################
################################
################################

In [20]:
SU.peek(0, result)

 ============================================================
 📍 INDEX: [0]
 🏷️  NAME:  audit_pack
 📂 PATH:  audit_pack
 ============================================================

EngineOutput(portfolio_series=Date
2026-04-01    1.0000
2026-04-02    1.0448
2026-04-06    1.0736
2026-04-07    1.1157
2026-04-08    1.2222
2026-04-09    1.2799
2026-04-10    1.3768
2026-04-13    1.4861
2026-04-14    1.6280
2026-04-15    1.6786
2026-04-16    1.6565
2026-04-17    1.6761
2026-04-20    1.7388
2026-04-21    1.7746
2026-04-22    1.8428
2026-04-23    1.8776
2026-04-24    1.9774
dtype: float64, benchmark_series=Date
2026-04-01    1.0000
2026-04-02    1.0009
2026-04-06    1.0056
2026-04-07    1.0061
2026-04-08    1.0317
2026-04-09    1.0377
2026-04-10    1.0370
2026-04-13    1.0471
2026-04-14    1.0599
2026-04-15    1.0682
2026-04-16    1.0708
2026-04-17    1.0838
2026-04-20    1.0816
2026-04-21    1.0745
2026-04-22    1.0854
2026-04-23    1.0812
2026-04-24    1.0896
dtype: float64, normalized_plot_data=Ticker        SOXL    CRDO    NBIS
Date
2026-04-01  1.0000  1.0000  1.0000
2026-04-02  1.0094  1.0577  1.0674
2026-04-06  1.0488  1.0682  1.1039
2026-04-07  1.0821  1.1133  1.1515
2026-04-08  1.2916  1.1490  1.2261
2026-04-09  1.3773  1.1252  1.3372
2026-04-10  1.4617  1.2468  1.4220
2026-04-13  1.5415  1.4008  1.5160
2026-04-14  1.6324  1.6631  1.5884
2026-04-15  1.6449  1.7551  1.6358
2026-04-16  1.6910  1.6569  1.6218
2026-04-17  1.8117  1.6753  1.5413
2026-04-20  1.8358  1.8195  1.5612
2026-04-21  1.8770  1.9112  1.5356
2026-04-22  2.0214  1.9755  1.5315
2026-04-23  2.1579  1.9343  1.5408
2026-04-24  2.4554  2.0334  1.4435, tickers=['SOXL', 'CRDO', 'NBIS'], initial_weights=SOXL    0.3333
CRDO    0.3333
NBIS    0.3333
dtype: float64, perf_metrics={'full_p_gain': 0.6817877455655165, 'full_p_sharpe': 23.107695909016513, 'full_p_sharpe_atrp': 0.627152382982204, 'full_p_sharpe_trp': 0.5379225630058191, 'lookback_p_gain': 0.5047361606600764, 'lookback_p_sharpe': 24.171188169091653, 'lookback_p_sharpe_atrp': 0.6933520751573404, 'lookback_p_sharpe_trp': 0.6063818627830315, 'holding_p_gain': 0.1557372663005199, 'holding_p_sharpe': 38.76157962199495, 'holding_p_sharpe_atrp': 0.5229937086357112, 'holding_p_sharpe_trp': 0.42591769143115193, 'full_b_gain': 0.08579734445868653, 'full_b_sharpe': 10.949522306673591, 'full_b_sharpe_atrp': 0.38916841187622164, 'full_b_sharpe_trp': 0.45751426966529196, 'lookback_b_gain': 0.06844737547915633, 'lookback_b_sharpe': 14.096177166249744, 'lookback_b_sharpe_atrp': 0.46825337733519884, 'lookback_b_sharpe_trp': 0.5606475436482259, 'holding_b_gain': 0.005336791499196458, 'holding_b_sharpe': 2.3401295978502965, 'holding_b_sharpe_atrp': 0.08793310536654401, 'holding_b_sharpe_trp': 0.10696619502502655}, results_df=        Rank  Strategy Value
Ticker
SOXL       1          0.5253
CRDO       2          0.5049
NBIS       3          0.4835, start_date=Timestamp('2026-04-01 00:00:00'), decision_date=Timestamp('2026-04-16 00:00:00'), buy_date=Timestamp('2026-04-17 00:00:00'), holding_end_date=Timestamp('2026-04-24 00:00:00'), portfolio_atrp_series=Date
2026-04-01    0.0953
2026-04-02    0.0933
2026-04-06    0.0881
2026-04-07    0.0834
2026-04-08    0.0786
2026-04-09    0.0748
2026-04-10    0.0718
2026-04-13    0.0689
2026-04-14    0.0659
2026-04-15    0.0639
2026-04-16    0.0653
2026-04-17    0.0650
2026-04-20    0.0626
2026-04-21    0.0605
2026-04-22    0.0588
2026-04-23    0.0596
2026-04-24    0.0605
dtype: float64, benchmark_atrp_series=Date
2026-04-01    0.0159
2026-04-02    0.0162
2026-04-06    0.0154
2026-04-07    0.0152
2026-04-08    0.0157
2026-04-09    0.0152
2026-04-10    0.0145
2026-04-13    0.0144
2026-04-14    0.0141
2026-04-15    0.0136
2026-04-16    0.0130
2026-04-17    0.0130
2026-04-20    0.0125
2026-04-21    0.0126
2026-04-22    0.0123
2026-04-23    0.0125
2026-04-24    0.0121
dtype: float64, portfolio_trp_series=Date
2026-04-01    0.0777
2026-04-02    0.1204
2026-04-06    0.0532
2026-04-07    0.0647
2026-04-08    0.1105
2026-04-09    0.0721
2026-04-10    0.1010
2026-04-13    0.0995
2026-04-14    0.1054
2026-04-15    0.0633
2026-04-16    0.0721
2026-04-17    0.0717
2026-04-20    0.0613
2026-04-21    0.0506
2026-04-22    0.0652
2026-04-23    0.0844
2026-04-24    0.1117
dtype: float64, benchmark_trp_series=Date
2026-04-01    0.0125
2026-04-02    0.0200
2026-04-06    0.0064
2026-04-07    0.0130
2026-04-08    0.0264
2026-04-09    0.0109
2026-04-10    0.0053
2026-04-13    0.0142
2026-04-14    0.0122
2026-04-15    0.0087
2026-04-16    0.0061
2026-04-17    0.0151
2026-04-20    0.0056
2026-04-21    0.0123
2026-04-22    0.0104
2026-04-23    0.0142
2026-04-24    0.0084
dtype: float64, error_msg=None, debug_data={'audit_liquidity': {'date': Timestamp('2026-04-16 00:00:00'), 'total_tickers_available': 1578, 'percentile_setting': 0.4, 'final_cutoff_usd': 102252047.09944001, 'tickers_passed': 941, 'universe_snapshot':            ATR    ATRP     TRP      RSI  Mom_21  Consistency   IR_63  Beta_63   DD_21  AutoCorr_15  Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5  Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount  Passed_Final
Ticker
A       3.1930  0.0270  0.0293  54.3418  0.0512          0.4 -0.2499   0.8866 -0.0178      -0.1328 -0.0127        0.7072     0.0074     0.0957    -0.0003              0.0        2.2616e+08                  0.0          True
AA      3.3635  0.0478  0.0378  58.2595  0.0763          0.4  0.0488   1.0655 -0.0396       0.2481  0.0004        0.7437    -0.0114    -0.0405    -0.0117              0.0        2.2739e+08                  0.0          True
AAL     0.5632  0.0459  0.0432  61.6207  0.1298          0.6 -0.1121   2.0561  0.0000      -0.0966  0.0082        0.8826     0.0242     0.7186     0.0132              0.0        7.3124e+08                  0.0          True
AAON    4.6710  0.0511  0.0317  56.5042  0.1521          0.6  0.0292   1.6886 -0.0248       0.0824 -0.0121        0.7558    -0.0047    -0.2545    -0.0219              0.0        7.7810e+07                  0.0         False
AAPL    5.8970  0.0224  0.0224  57.4298  0.0361          0.2  0.0005   0.9787 -0.0114      -0.3195 -0.0114        0.8263     0.0050    -0.3292     0.0055              0.0        1.0939e+10                  0.0          True
...        ...     ...     ...      ...     ...          ...     ...      ...     ...          ...     ...           ...        ...        ...        ...              ...               ...                  ...           ...
ZM      3.5157  0.0406  0.0510  59.8709  0.1407          0.4  0.0293   1.0152 -0.0264      -0.5145 -0.0264        0.7558     0.0252     0.1565     0.0287              0.0        2.2758e+08                  0.0          True
ZS      8.1369  0.0606  0.0520  44.3727 -0.1389          0.8 -0.1764   0.8997 -0.1389       0.1586  0.0253        0.4168     0.0325     1.1566     0.0555              0.0        4.4275e+08                  0.0          True
ZTO     0.6392  0.0253  0.0221  62.2596  0.0832          0.8  0.0966   0.1060  0.0000       0.0624  0.0088        0.8685     0.0042     0.4669    -0.0014              0.0        3.4584e+07                  0.0         False
ZTS     3.0579  0.0258  0.0250  49.1555 -0.0217          0.4 -0.0737   0.8548 -0.0171      -0.2915 -0.0142        0.6263     0.0026     0.0612     0.0002              0.0        4.6773e+08                  0.0          True
ZWS     1.4070  0.0303  0.0370  48.2899  0.0283          0.2 -0.0065   1.0202 -0.0625       0.0966 -0.0186        0.5059    -0.0098    -0.5339    -0.0200              0.0        3.6239e+07                  0.0         False

[1578 rows x 19 columns]}, 'full_universe_ranking':         Strategy_Score  Raw_Price_Start  Raw_Price_End  Raw_TRP_Mean  Raw_ATRP_Mean  Raw_Mom_21  Raw_IR_63  Raw_Consistency  Raw_RSI  Raw_DD_21  Raw_Range_Pos_20  Raw_Slope_P_5  Raw_Slope_V_5  Raw_Convexity  Raw_AutoCorr_15  Was_Dropped
Ticker
A               0.0319          114.540        118.250        0.0275         0.0273      0.0512    -0.2499              0.4  54.3418    -0.0178            0.7072         0.0074         0.0957        -0.0003          -0.1328        False
AA             -0.0232           72.060         70.410        0.0393         0.0512      0.0763     0.0488              0.4  58.2595    -0.0396            0.7437        -0.0114        -0.0405        -0.0117           0.2481        False
AAL             0.0975           11.130         12.270        0.0505         0.0491      0.1298    -0.1121              0.6  61.6207     0.0000            0.8826         0.0242         0.7186         0.0132          -0.0966        False
AAPL            0.0299          255.630        263.400        0.0241         0.0227      0.0361     0.0005              0.2  57.4298    -0.0114            0.8263         0.0050        -0.3292         0.0055          -0.3195        False
ABBV           -0.0200          213.211        208.990        0.0257         0.0272     -0.0411    -0.0554              0.4  46.4258    -0.0311            0.4824         0.0044        -0.0562         0.0085           0.1622        False
...                ...              ...            ...           ...            ...         ...        ...              ...      ...        ...               ...            ...            ...            ...              ...          ...
ZBH             0.0404           91.030         94.780        0.0224         0.0235      0.0272     0.0497              0.8  58.7640    -0.0180            0.7519         0.0023         0.3469        -0.0075          -0.1092        False
ZBRA            0.1171          207.280        233.040        0.0351         0.0390      0.1147    -0.0728              0.8  64.6796     0.0000            0.9795         0.0111         1.1141         0.0048          -0.2102        False
ZM              0.0715           80.700         86.680        0.0469         0.0364      0.1407     0.0293              0.4  59.8709    -0.0264            0.7558         0.0252         0.1565         0.0287          -0.5145        False
ZS             -0.0173          136.670        134.330        0.0617         0.0629     -0.1389    -0.1764              0.8  44.3727    -0.1389            0.4168         0.0325         1.1566         0.0555           0.1586        False
ZTS             0.0148          116.782        118.524        0.0235         0.0265     -0.0217    -0.0737              0.4  49.1555    -0.0171            0.6263         0.0026         0.0612         0.0002          -0.2915        False

[941 rows x 16 columns], 'meta': {'dropped_count': 0, 'dropped_tickers': [], 'clean_count': 941, 'selection_range': '1-3'}, 'inputs_snapshot': EngineInput(mode='Ranking', decision_date=Timestamp('2026-04-16 00:00:00'), lookback_period=10, holding_period=5, metric='Log Price Gain', benchmark_ticker='SPY', rank_start=1, rank_end=3, quality_thresholds={'min_median_dollar_volume': 1000000, 'min_liquidity_percentile': 0.4, 'max_stale_pct': 0.05, 'max_same_vol_count': 10}, manual_tickers=[], debug=True, universe_subset=None), 'alpha_perception':         Log Price Gain (Z)  Sharpe (TRP) (S)  Momentum (21d) (S)  Info Ratio (63d) (S)  Oversold (-RSI) (S)  Dip Buyer (-dd_21) (S)  Range Position (20d) (S)  Return Autocorr (15d) (S)  Low Volatility (-ATRP) (Z)  OBV Divergence (5d) (Z)  Convexity (Z)
Ticker
A                  -0.2587            0.1199              0.0512               -0.2499              -0.2171                  0.0178                    0.7072                    -0.1328                      0.3723                  -0.3245        -0.2221
AA                 -0.9423           -0.0559              0.0763                0.0488              -0.4130                  0.0396                    0.7437                     0.2481                     -1.0641                   1.0498        -0.9916
AAL                 0.5564            0.2032              0.1298               -0.1121              -0.5810                 -0.0000                    0.8826                    -0.0966                     -0.9374                  -0.1049         0.6860
AAPL               -0.2828            0.1283              0.0361                0.0005              -0.3715                  0.0114                    0.8263                    -0.3195                      0.6505                  -1.3257         0.1706
ABBV               -0.9030           -0.0732             -0.0411               -0.0554               0.1787                  0.0311                    0.4824                     0.1622                      0.3765                  -0.4849         0.3725
...                    ...               ...                 ...                   ...                  ...                     ...                       ...                        ...                         ...                      ...            ...
ZBH                -0.1533            0.1836              0.0272                0.0497              -0.4382                  0.0180                    0.7519                    -0.1092                      0.6026                   0.8769        -0.7123
ZBRA                0.8002            0.3403              0.1147               -0.0728              -0.7340                 -0.0000                    0.9795                    -0.2102                     -0.3300                   2.2628         0.1236
ZM                  0.2332            0.1665              0.1407                0.0293              -0.4935                  0.0264                    0.7558                    -0.5145                     -0.1761                  -1.8273         1.7354
ZS                 -0.8691           -0.0093             -0.1389               -0.1764               0.2814                  0.1389                    0.4168                     0.1586                     -1.7688                   0.3786         3.5451
ZTS                -0.4707            0.0667             -0.0217               -0.0737               0.0422                  0.0171                    0.6263                    -0.2915                      0.4232                   0.0306        -0.1884

[941 rows x 11 columns], 'verification': {'p': {'val': Date
2026-04-01    1.0000
2026-04-02    1.0448
2026-04-06    1.0736
2026-04-07    1.1157
2026-04-08    1.2222
2026-04-09    1.2799
2026-04-10    1.3768
2026-04-13    1.4861
2026-04-14    1.6280
2026-04-15    1.6786
2026-04-16    1.6565
2026-04-17    1.6761
2026-04-20    1.7388
2026-04-21    1.7746
2026-04-22    1.8428
2026-04-23    1.8776
2026-04-24    1.9774
dtype: float64, 'ret': Date
2026-04-01       NaN
2026-04-02    0.0448
2026-04-06    0.0276
2026-04-07    0.0392
2026-04-08    0.0955
2026-04-09    0.0472
2026-04-10    0.0757
2026-04-13    0.0794
2026-04-14    0.0955
2026-04-15    0.0311
2026-04-16   -0.0131
2026-04-17    0.0118
2026-04-20    0.0374
2026-04-21    0.0205
2026-04-22    0.0385
2026-04-23    0.0189
2026-04-24    0.0531
dtype: float64, 'atrp': Date
2026-04-01    0.0953
2026-04-02    0.0933
2026-04-06    0.0881
2026-04-07    0.0834
2026-04-08    0.0786
2026-04-09    0.0748
2026-04-10    0.0718
2026-04-13    0.0689
2026-04-14    0.0659
2026-04-15    0.0639
2026-04-16    0.0653
2026-04-17    0.0650
2026-04-20    0.0626
2026-04-21    0.0605
2026-04-22    0.0588
2026-04-23    0.0596
2026-04-24    0.0605
dtype: float64, 'trp': Date
2026-04-01    0.0777
2026-04-02    0.1204
2026-04-06    0.0532
2026-04-07    0.0647
2026-04-08    0.1105
2026-04-09    0.0721
2026-04-10    0.1010
2026-04-13    0.0995
2026-04-14    0.1054
2026-04-15    0.0633
2026-04-16    0.0721
2026-04-17    0.0717
2026-04-20    0.0613
2026-04-21    0.0506
2026-04-22    0.0652
2026-04-23    0.0844
2026-04-24    0.1117
dtype: float64}, 'b': {'val': Date
2026-04-01    1.0000
2026-04-02    1.0009
2026-04-06    1.0056
2026-04-07    1.0061
2026-04-08    1.0317
2026-04-09    1.0377
2026-04-10    1.0370
2026-04-13    1.0471
2026-04-14    1.0599
2026-04-15    1.0682
2026-04-16    1.0708
2026-04-17    1.0838
2026-04-20    1.0816
2026-04-21    1.0745
2026-04-22    1.0854
2026-04-23    1.0812
2026-04-24    1.0896
dtype: float64, 'ret': Date
2026-04-01       NaN
2026-04-02    0.0009
2026-04-06    0.0047
2026-04-07    0.0004
2026-04-08    0.0255
2026-04-09    0.0058
2026-04-10   -0.0007
2026-04-13    0.0098
2026-04-14    0.0122
2026-04-15    0.0079
2026-04-16    0.0025
2026-04-17    0.0121
2026-04-20   -0.0020
2026-04-21   -0.0065
2026-04-22    0.0101
2026-04-23   -0.0039
2026-04-24    0.0077
dtype: float64, 'atrp': Date
2026-04-01    0.0159
2026-04-02    0.0162
2026-04-06    0.0154
2026-04-07    0.0152
2026-04-08    0.0157
2026-04-09    0.0152
2026-04-10    0.0145
2026-04-13    0.0144
2026-04-14    0.0141
2026-04-15    0.0136
2026-04-16    0.0130
2026-04-17    0.0130
2026-04-20    0.0125
2026-04-21    0.0126
2026-04-22    0.0123
2026-04-23    0.0125
2026-04-24    0.0121
dtype: float64, 'trp': Date
2026-04-01    0.0125
2026-04-02    0.0200
2026-04-06    0.0064
2026-04-07    0.0130
2026-04-08    0.0264
2026-04-09    0.0109
2026-04-10    0.0053
2026-04-13    0.0142
2026-04-14    0.0122
2026-04-15    0.0087
2026-04-16    0.0061
2026-04-17    0.0151
2026-04-20    0.0056
2026-04-21    0.0123
2026-04-22    0.0104
2026-04-23    0.0142
2026-04-24    0.0084
dtype: float64}}, 'portfolio_raw_components': {'prices': Ticker        SOXL    CRDO    NBIS
Date
2026-04-01   52.26   95.92  101.95
2026-04-02   52.75  101.45  108.82
2026-04-06   54.81  102.46  112.54
2026-04-07   56.55  106.79  117.40
2026-04-08   67.50  110.21  125.00
2026-04-09   71.98  107.93  136.33
2026-04-10   76.39  119.59  144.97
2026-04-13   80.56  134.36  154.56
2026-04-14   85.31  159.52  161.94
2026-04-15   85.96  168.35  166.77
2026-04-16   88.37  158.93  165.34
2026-04-17   94.68  160.69  157.14
2026-04-20   95.94  174.53  159.16
2026-04-21   98.09  183.32  156.55
2026-04-22  105.64  189.49  156.14
2026-04-23  112.77  185.54  157.08
2026-04-24  128.32  195.04  147.16, 'atrp': Ticker        SOXL    CRDO    NBIS
Date
2026-04-01  0.1105  0.0872  0.0884
2026-04-02  0.1111  0.0845  0.0852
2026-04-06  0.1030  0.0813  0.0806
2026-04-07  0.0984  0.0761  0.0764
2026-04-08  0.0886  0.0737  0.0725
2026-04-09  0.0819  0.0742  0.0680
2026-04-10  0.0776  0.0708  0.0668
2026-04-13  0.0732  0.0671  0.0661
2026-04-14  0.0684  0.0656  0.0637
2026-04-15  0.0682  0.0618  0.0618
2026-04-16  0.0665  0.0675  0.0616
2026-04-17  0.0624  0.0678  0.0650
2026-04-20  0.0609  0.0638  0.0631
2026-04-21  0.0586  0.0603  0.0631
2026-04-22  0.0560  0.0574  0.0643
2026-04-23  0.0557  0.0599  0.0647
2026-04-24  0.0551  0.0578  0.0736, 'trp': Ticker        SOXL    CRDO    NBIS
Date
2026-04-01  0.1183  0.0510  0.0640
2026-04-02  0.1331  0.1113  0.1173
2026-04-06  0.0520  0.0508  0.0568
2026-04-07  0.0790  0.0504  0.0649
2026-04-08  0.1693  0.0739  0.0828
2026-04-09  0.0664  0.0600  0.0880
2026-04-10  0.0827  0.1202  0.1030
2026-04-13  0.0681  0.1212  0.1113
2026-04-14  0.0587  0.1838  0.0713
2026-04-15  0.0724  0.0561  0.0618
2026-04-16  0.0688  0.0950  0.0521
2026-04-17  0.0674  0.0803  0.0675
2026-04-20  0.0511  0.0826  0.0484
2026-04-21  0.0472  0.0542  0.0501
2026-04-22  0.0757  0.0450  0.0774
2026-04-23  0.0987  0.0761  0.0747
2026-04-24  0.1352  0.0689  0.1321, 'ohlcv_raw':                    Adj Open  Adj High  Adj Low  Adj Close     Volume
Ticker Date
SOXL   2026-04-01    50.040    54.090   49.620      52.26  121955600
       2026-04-02    46.060    53.070   46.050      52.75  104471700
       2026-04-06    53.750    55.600   52.880      54.81   68780400
       2026-04-07    54.320    56.600   52.130      56.55  107326500
       2026-04-08    66.330    67.980   63.560      67.50  111697300
       2026-04-09    68.120    72.280   68.120      71.98   79331600
       2026-04-10    74.300    78.300   74.300      76.39   78863600
       2026-04-13    75.590    80.740   75.250      80.56   64504600
       2026-04-14    83.270    85.570   80.710      85.31   61657000
       2026-04-15    84.660    85.980   79.760      85.96   68425400
       2026-04-16    85.010    89.390   83.310      88.37   63777500
       2026-04-17    93.200    94.750   90.660      94.68   67081400

EngineOutput(portfolio_series=Date
2026-04-01    1.0000
2026-04-02    1.0448
2026-04-06    1.0736
2026-04-07    1.1157
2026-04-08    1.2222
2026-04-09    1.2799
2026-04-10    1.3768
2026-04-13    1.4861
2026-04-14    1.6280
2026-04-15    1.6786
2026-04-16    1.6565
2026-04-17    1.6761
2026-04-20    1.7388
2026-04-21    1.7746
2026-04-22    1.8428
2026-04-23    1.8776
2026-04-24    1.9774
dtype: float64, benchmark_series=Date
2026-04-01    1.0000
2026-04-02    1.0009
2026-04-06    1.0056
2026-04-07    1.0061
2026-04-08    1.0317
2026-04-09    1.0377
2026-04-10    1.0370
2026-04-13    1.0471
2026-04-14    1.0599
2026-04-15    1.0682
2026-04-16    1.0708
2026-04-17    1.0838
2026-04-20    1.0816
2026-04-21    1.0745
2026-04-22    1.0854
2026-04-23    1.0812
2026-04-24    1.0896
dtype: float64, normalized_plot_data=Ticker        SOXL    CRDO    NBIS
Date
2026-04-01  1.0000  1.0000  1.0000
2026-04-02  1.0094  1.0577  1.0674
2026-04-06  1.0488  1.0682  1.1039
2026-04-07  1.0821  1.1133  1.1515
2026-04-08  1.2916  1.1490  1.2261
2026-04-09  1.3773  1.1252  1.3372
2026-04-10  1.4617  1.2468  1.4220
2026-04-13  1.5415  1.4008  1.5160
2026-04-14  1.6324  1.6631  1.5884
2026-04-15  1.6449  1.7551  1.6358
2026-04-16  1.6910  1.6569  1.6218
2026-04-17  1.8117  1.6753  1.5413
2026-04-20  1.8358  1.8195  1.5612
2026-04-21  1.8770  1.9112  1.5356
2026-04-22  2.0214  1.9755  1.5315
2026-04-23  2.1579  1.9343  1.5408
2026-04-24  2.4554  2.0334  1.4435, tickers=['SOXL', 'CRDO', 'NBIS'], initial_weights=SOXL    0.3333
CRDO    0.3333
NBIS    0.3333
dtype: float64, perf_metrics={'full_p_gain': 0.6817877455655165, 'full_p_sharpe': 23.107695909016513, 'full_p_sharpe_atrp': 0.627152382982204, 'full_p_sharpe_trp': 0.5379225630058191, 'lookback_p_gain': 0.5047361606600764, 'lookback_p_sharpe': 24.171188169091653, 'lookback_p_sharpe_atrp': 0.6933520751573404, 'lookback_p_sharpe_trp': 0.6063818627830315, 'holding_p_gain': 0.1557372663005199, 'holding_p_sharpe': 38.76157962199495, 'holding_p_sharpe_atrp': 0.5229937086357112, 'holding_p_sharpe_trp': 0.42591769143115193, 'full_b_gain': 0.08579734445868653, 'full_b_sharpe': 10.949522306673591, 'full_b_sharpe_atrp': 0.38916841187622164, 'full_b_sharpe_trp': 0.45751426966529196, 'lookback_b_gain': 0.06844737547915633, 'lookback_b_sharpe': 14.096177166249744, 'lookback_b_sharpe_atrp': 0.46825337733519884, 'lookback_b_sharpe_trp': 0.5606475436482259, 'holding_b_gain': 0.005336791499196458, 'holding_b_sharpe': 2.3401295978502965, 'holding_b_sharpe_atrp': 0.08793310536654401, 'holding_b_sharpe_trp': 0.10696619502502655}, results_df=        Rank  Strategy Value
Ticker
SOXL       1          0.5253
CRDO       2          0.5049
NBIS       3          0.4835, start_date=Timestamp('2026-04-01 00:00:00'), decision_date=Timestamp('2026-04-16 00:00:00'), buy_date=Timestamp('2026-04-17 00:00:00'), holding_end_date=Timestamp('2026-04-24 00:00:00'), portfolio_atrp_series=Date
2026-04-01    0.0953
2026-04-02    0.0933
2026-04-06    0.0881
2026-04-07    0.0834
2026-04-08    0.0786
2026-04-09    0.0748
2026-04-10    0.0718
2026-04-13    0.0689
2026-04-14    0.0659
2026-04-15    0.0639
2026-04-16    0.0653
2026-04-17    0.0650
2026-04-20    0.0626
2026-04-21    0.0605
2026-04-22    0.0588
2026-04-23    0.0596
2026-04-24    0.0605
dtype: float64, benchmark_atrp_series=Date
2026-04-01    0.0159
2026-04-02    0.0162
2026-04-06    0.0154
2026-04-07    0.0152
2026-04-08    0.0157
2026-04-09    0.0152
2026-04-10    0.0145
2026-04-13    0.0144
2026-04-14    0.0141
2026-04-15    0.0136
2026-04-16    0.0130
2026-04-17    0.0130
2026-04-20    0.0125
2026-04-21    0.0126
2026-04-22    0.0123
2026-04-23    0.0125
2026-04-24    0.0121
dtype: float64, portfolio_trp_series=Date
2026-04-01    0.0777
2026-04-02    0.1204
2026-04-06    0.0532
2026-04-07    0.0647
2026-04-08    0.1105
2026-04-09    0.0721
2026-04-10    0.1010
2026-04-13    0.0995
2026-04-14    0.1054
2026-04-15    0.0633
2026-04-16    0.0721
2026-04-17    0.0717
2026-04-20    0.0613
2026-04-21    0.0506
2026-04-22    0.0652
2026-04-23    0.0844
2026-04-24    0.1117
dtype: float64, benchmark_trp_series=Date
2026-04-01    0.0125
2026-04-02    0.0200
2026-04-06    0.0064
2026-04-07    0.0130
2026-04-08    0.0264
2026-04-09    0.0109
2026-04-10    0.0053
2026-04-13    0.0142
2026-04-14    0.0122
2026-04-15    0.0087
2026-04-16    0.0061
2026-04-17    0.0151
2026-04-20    0.0056
2026-04-21    0.0123
2026-04-22    0.0104
2026-04-23    0.0142
2026-04-24    0.0084
dtype: float64, error_msg=None, debug_data={'audit_liquidity': {'date': Timestamp('2026-04-16 00:00:00'), 'total_tickers_available': 1578, 'percentile_setting': 0.4, 'final_cutoff_usd': 102252047.09944001, 'tickers_passed': 941, 'universe_snapshot':            ATR    ATRP     TRP      RSI  Mom_21  Consistency   IR_63  Beta_63   DD_21  AutoCorr_15  Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5  Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount  Passed_Final
Ticker
A       3.1930  0.0270  0.0293  54.3418  0.0512          0.4 -0.2499   0.8866 -0.0178      -0.1328 -0.0127        0.7072     0.0074     0.0957    -0.0003              0.0        2.2616e+08                  0.0          True
AA      3.3635  0.0478  0.0378  58.2595  0.0763          0.4  0.0488   1.0655 -0.0396       0.2481  0.0004        0.7437    -0.0114    -0.0405    -0.0117              0.0        2.2739e+08                  0.0          True
AAL     0.5632  0.0459  0.0432  61.6207  0.1298          0.6 -0.1121   2.0561  0.0000      -0.0966  0.0082        0.8826     0.0242     0.7186     0.0132              0.0        7.3124e+08                  0.0          True
AAON    4.6710  0.0511  0.0317  56.5042  0.1521          0.6  0.0292   1.6886 -0.0248       0.0824 -0.0121        0.7558    -0.0047    -0.2545    -0.0219              0.0        7.7810e+07                  0.0         False
AAPL    5.8970  0.0224  0.0224  57.4298  0.0361          0.2  0.0005   0.9787 -0.0114      -0.3195 -0.0114        0.8263     0.0050    -0.3292     0.0055              0.0        1.0939e+10                  0.0          True
...        ...     ...     ...      ...     ...          ...     ...      ...     ...          ...     ...           ...        ...        ...        ...              ...               ...                  ...           ...
ZM      3.5157  0.0406  0.0510  59.8709  0.1407          0.4  0.0293   1.0152 -0.0264      -0.5145 -0.0264        0.7558     0.0252     0.1565     0.0287              0.0        2.2758e+08                  0.0          True
ZS      8.1369  0.0606  0.0520  44.3727 -0.1389          0.8 -0.1764   0.8997 -0.1389       0.1586  0.0253        0.4168     0.0325     1.1566     0.0555              0.0        4.4275e+08                  0.0          True
ZTO     0.6392  0.0253  0.0221  62.2596  0.0832          0.8  0.0966   0.1060  0.0000       0.0624  0.0088        0.8685     0.0042     0.4669    -0.0014              0.0        3.4584e+07                  0.0         False
ZTS     3.0579  0.0258  0.0250  49.1555 -0.0217          0.4 -0.0737   0.8548 -0.0171      -0.2915 -0.0142        0.6263     0.0026     0.0612     0.0002              0.0        4.6773e+08                  0.0          True
ZWS     1.4070  0.0303  0.0370  48.2899  0.0283          0.2 -0.0065   1.0202 -0.0625       0.0966 -0.0186        0.5059    -0.0098    -0.5339    -0.0200              0.0        3.6239e+07                  0.0         False

[1578 rows x 19 columns]}, 'full_universe_ranking':         Strategy_Score  Raw_Price_Start  Raw_Price_End  Raw_TRP_Mean  Raw_ATRP_Mean  Raw_Mom_21  Raw_IR_63  Raw_Consistency  Raw_RSI  Raw_DD_21  Raw_Range_Pos_20  Raw_Slope_P_5  Raw_Slope_V_5  Raw_Convexity  Raw_AutoCorr_15  Was_Dropped
Ticker
A               0.0319          114.540        118.250        0.0275         0.0273      0.0512    -0.2499              0.4  54.3418    -0.0178            0.7072         0.0074         0.0957        -0.0003          -0.1328        False
AA             -0.0232           72.060         70.410        0.0393         0.0512      0.0763     0.0488              0.4  58.2595    -0.0396            0.7437        -0.0114        -0.0405        -0.0117           0.2481        False
AAL             0.0975           11.130         12.270        0.0505         0.0491      0.1298    -0.1121              0.6  61.6207     0.0000            0.8826         0.0242         0.7186         0.0132          -0.0966        False
AAPL            0.0299          255.630        263.400        0.0241         0.0227      0.0361     0.0005              0.2  57.4298    -0.0114            0.8263         0.0050        -0.3292         0.0055          -0.3195        False
ABBV           -0.0200          213.211        208.990        0.0257         0.0272     -0.0411    -0.0554              0.4  46.4258    -0.0311            0.4824         0.0044        -0.0562         0.0085           0.1622        False
...                ...              ...            ...           ...            ...         ...        ...              ...      ...        ...               ...            ...            ...            ...              ...          ...
ZBH             0.0404           91.030         94.780        0.0224         0.0235      0.0272     0.0497              0.8  58.7640    -0.0180            0.7519         0.0023         0.3469        -0.0075          -0.1092        False
ZBRA            0.1171          207.280        233.040        0.0351         0.0390      0.1147    -0.0728              0.8  64.6796     0.0000            0.9795         0.0111         1.1141         0.0048          -0.2102        False
ZM              0.0715           80.700         86.680        0.0469         0.0364      0.1407     0.0293              0.4  59.8709    -0.0264            0.7558         0.0252         0.1565         0.0287          -0.5145        False
ZS             -0.0173          136.670        134.330        0.0617         0.0629     -0.1389    -0.1764              0.8  44.3727    -0.1389            0.4168         0.0325         1.1566         0.0555           0.1586        False
ZTS             0.0148          116.782        118.524        0.0235         0.0265     -0.0217    -0.0737              0.4  49.1555    -0.0171            0.6263         0.0026         0.0612         0.0002          -0.2915        False

[941 rows x 16 columns], 'meta': {'dropped_count': 0, 'dropped_tickers': [], 'clean_count': 941, 'selection_range': '1-3'}, 'inputs_snapshot': EngineInput(mode='Ranking', decision_date=Timestamp('2026-04-16 00:00:00'), lookback_period=10, holding_period=5, metric='Log Price Gain', benchmark_ticker='SPY', rank_start=1, rank_end=3, quality_thresholds={'min_median_dollar_volume': 1000000, 'min_liquidity_percentile': 0.4, 'max_stale_pct': 0.05, 'max_same_vol_count': 10}, manual_tickers=[], debug=True, universe_subset=None), 'alpha_perception':         Log Price Gain (Z)  Sharpe (TRP) (S)  Momentum (21d) (S)  Info Ratio (63d) (S)  Oversold (-RSI) (S)  Dip Buyer (-dd_21) (S)  Range Position (20d) (S)  Return Autocorr (15d) (S)  Low Volatility (-ATRP) (Z)  OBV Divergence (5d) (Z)  Convexity (Z)
Ticker
A                  -0.2587            0.1199              0.0512               -0.2499              -0.2171                  0.0178                    0.7072                    -0.1328                      0.3723                  -0.3245        -0.2221
AA                 -0.9423           -0.0559              0.0763                0.0488              -0.4130                  0.0396                    0.7437                     0.2481                     -1.0641                   1.0498        -0.9916
AAL                 0.5564            0.2032              0.1298               -0.1121              -0.5810                 -0.0000                    0.8826                    -0.0966                     -0.9374                  -0.1049         0.6860
AAPL               -0.2828            0.1283              0.0361                0.0005              -0.3715                  0.0114                    0.8263                    -0.3195                      0.6505                  -1.3257         0.1706
ABBV               -0.9030           -0.0732             -0.0411               -0.0554               0.1787                  0.0311                    0.4824                     0.1622                      0.3765                  -0.4849         0.3725
...                    ...               ...                 ...                   ...                  ...                     ...                       ...                        ...                         ...                      ...            ...
ZBH                -0.1533            0.1836              0.0272                0.0497              -0.4382                  0.0180                    0.7519                    -0.1092                      0.6026                   0.8769        -0.7123
ZBRA                0.8002            0.3403              0.1147               -0.0728              -0.7340                 -0.0000                    0.9795                    -0.2102                     -0.3300                   2.2628         0.1236
ZM                  0.2332            0.1665              0.1407                0.0293              -0.4935                  0.0264                    0.7558                    -0.5145                     -0.1761                  -1.8273         1.7354
ZS                 -0.8691           -0.0093             -0.1389               -0.1764               0.2814                  0.1389                    0.4168                     0.1586                     -1.7688                   0.3786         3.5451
ZTS                -0.4707            0.0667             -0.0217               -0.0737               0.0422                  0.0171                    0.6263                    -0.2915                      0.4232                   0.0306        -0.1884

[941 rows x 11 columns], 'verification': {'p': {'val': Date
2026-04-01    1.0000
2026-04-02    1.0448
2026-04-06    1.0736
2026-04-07    1.1157
2026-04-08    1.2222
2026-04-09    1.2799
2026-04-10    1.3768
2026-04-13    1.4861
2026-04-14    1.6280
2026-04-15    1.6786
2026-04-16    1.6565
2026-04-17    1.6761
2026-04-20    1.7388
2026-04-21    1.7746
2026-04-22    1.8428
2026-04-23    1.8776
2026-04-24    1.9774
dtype: float64, 'ret': Date
2026-04-01       NaN
2026-04-02    0.0448
2026-04-06    0.0276
2026-04-07    0.0392
2026-04-08    0.0955
2026-04-09    0.0472
2026-04-10    0.0757
2026-04-13    0.0794
2026-04-14    0.0955
2026-04-15    0.0311
2026-04-16   -0.0131
2026-04-17    0.0118
2026-04-20    0.0374
2026-04-21    0.0205
2026-04-22    0.0385
2026-04-23    0.0189
2026-04-24    0.0531
dtype: float64, 'atrp': Date
2026-04-01    0.0953
2026-04-02    0.0933
2026-04-06    0.0881
2026-04-07    0.0834
2026-04-08    0.0786
2026-04-09    0.0748
2026-04-10    0.0718
2026-04-13    0.0689
2026-04-14    0.0659
2026-04-15    0.0639
2026-04-16    0.0653
2026-04-17    0.0650
2026-04-20    0.0626
2026-04-21    0.0605
2026-04-22    0.0588
2026-04-23    0.0596
2026-04-24    0.0605
dtype: float64, 'trp': Date
2026-04-01    0.0777
2026-04-02    0.1204
2026-04-06    0.0532
2026-04-07    0.0647
2026-04-08    0.1105
2026-04-09    0.0721
2026-04-10    0.1010
2026-04-13    0.0995
2026-04-14    0.1054
2026-04-15    0.0633
2026-04-16    0.0721
2026-04-17    0.0717
2026-04-20    0.0613
2026-04-21    0.0506
2026-04-22    0.0652
2026-04-23    0.0844
2026-04-24    0.1117
dtype: float64}, 'b': {'val': Date
2026-04-01    1.0000
2026-04-02    1.0009
2026-04-06    1.0056
2026-04-07    1.0061
2026-04-08    1.0317
2026-04-09    1.0377
2026-04-10    1.0370
2026-04-13    1.0471
2026-04-14    1.0599
2026-04-15    1.0682
2026-04-16    1.0708
2026-04-17    1.0838
2026-04-20    1.0816
2026-04-21    1.0745
2026-04-22    1.0854
2026-04-23    1.0812
2026-04-24    1.0896
dtype: float64, 'ret': Date
2026-04-01       NaN
2026-04-02    0.0009
2026-04-06    0.0047
2026-04-07    0.0004
2026-04-08    0.0255
2026-04-09    0.0058
2026-04-10   -0.0007
2026-04-13    0.0098
2026-04-14    0.0122
2026-04-15    0.0079
2026-04-16    0.0025
2026-04-17    0.0121
2026-04-20   -0.0020
2026-04-21   -0.0065
2026-04-22    0.0101
2026-04-23   -0.0039
2026-04-24    0.0077
dtype: float64, 'atrp': Date
2026-04-01    0.0159
2026-04-02    0.0162
2026-04-06    0.0154
2026-04-07    0.0152
2026-04-08    0.0157
2026-04-09    0.0152
2026-04-10    0.0145
2026-04-13    0.0144
2026-04-14    0.0141
2026-04-15    0.0136
2026-04-16    0.0130
2026-04-17    0.0130
2026-04-20    0.0125
2026-04-21    0.0126
2026-04-22    0.0123
2026-04-23    0.0125
2026-04-24    0.0121
dtype: float64, 'trp': Date
2026-04-01    0.0125
2026-04-02    0.0200
2026-04-06    0.0064
2026-04-07    0.0130
2026-04-08    0.0264
2026-04-09    0.0109
2026-04-10    0.0053
2026-04-13    0.0142
2026-04-14    0.0122
2026-04-15    0.0087
2026-04-16    0.0061
2026-04-17    0.0151
2026-04-20    0.0056
2026-04-21    0.0123
2026-04-22    0.0104
2026-04-23    0.0142
2026-04-24    0.0084
dtype: float64}}, 'portfolio_raw_components': {'prices': Ticker        SOXL    CRDO    NBIS
Date
2026-04-01   52.26   95.92  101.95
2026-04-02   52.75  101.45  108.82
2026-04-06   54.81  102.46  112.54
2026-04-07   56.55  106.79  117.40
2026-04-08   67.50  110.21  125.00
2026-04-09   71.98  107.93  136.33
2026-04-10   76.39  119.59  144.97
2026-04-13   80.56  134.36  154.56
2026-04-14   85.31  159.52  161.94
2026-04-15   85.96  168.35  166.77
2026-04-16   88.37  158.93  165.34
2026-04-17   94.68  160.69  157.14
2026-04-20   95.94  174.53  159.16
2026-04-21   98.09  183.32  156.55
2026-04-22  105.64  189.49  156.14
2026-04-23  112.77  185.54  157.08
2026-04-24  128.32  195.04  147.16, 'atrp': Ticker        SOXL    CRDO    NBIS
Date
2026-04-01  0.1105  0.0872  0.0884
2026-04-02  0.1111  0.0845  0.0852
2026-04-06  0.1030  0.0813  0.0806
2026-04-07  0.0984  0.0761  0.0764
2026-04-08  0.0886  0.0737  0.0725
2026-04-09  0.0819  0.0742  0.0680
2026-04-10  0.0776  0.0708  0.0668
2026-04-13  0.0732  0.0671  0.0661
2026-04-14  0.0684  0.0656  0.0637
2026-04-15  0.0682  0.0618  0.0618
2026-04-16  0.0665  0.0675  0.0616
2026-04-17  0.0624  0.0678  0.0650
2026-04-20  0.0609  0.0638  0.0631
2026-04-21  0.0586  0.0603  0.0631
2026-04-22  0.0560  0.0574  0.0643
2026-04-23  0.0557  0.0599  0.0647
2026-04-24  0.0551  0.0578  0.0736, 'trp': Ticker        SOXL    CRDO    NBIS
Date
2026-04-01  0.1183  0.0510  0.0640
2026-04-02  0.1331  0.1113  0.1173
2026-04-06  0.0520  0.0508  0.0568
2026-04-07  0.0790  0.0504  0.0649
2026-04-08  0.1693  0.0739  0.0828
2026-04-09  0.0664  0.0600  0.0880
2026-04-10  0.0827  0.1202  0.1030
2026-04-13  0.0681  0.1212  0.1113
2026-04-14  0.0587  0.1838  0.0713
2026-04-15  0.0724  0.0561  0.0618
2026-04-16  0.0688  0.0950  0.0521
2026-04-17  0.0674  0.0803  0.0675
2026-04-20  0.0511  0.0826  0.0484
2026-04-21  0.0472  0.0542  0.0501
2026-04-22  0.0757  0.0450  0.0774
2026-04-23  0.0987  0.0761  0.0747
2026-04-24  0.1352  0.0689  0.1321, 'ohlcv_raw':                    Adj Open  Adj High  Adj Low  Adj Close     Volume
Ticker Date
SOXL   2026-04-01    50.040    54.090   49.620      52.26  121955600
       2026-04-02    46.060    53.070   46.050      52.75  104471700
       2026-04-06    53.750    55.600   52.880      54.81   68780400
       2026-04-07    54.320    56.600   52.130      56.55  107326500
       2026-04-08    66.330    67.980   63.560      67.50  111697300
       2026-04-09    68.120    72.280   68.120      71.98   79331600
       2026-04-10    74.300    78.300   74.300      76.39   78863600
       2026-04-13    75.590    80.740   75.250      80.56   64504600
       2026-04-14    83.270    85.570   80.710      85.31   61657000
       2026-04-15    84.660    85.980   79.760      85.96   68425400
       2026-04-16    85.010    89.390   83.310      88.37   63777500
       2026-04-17    93.200    94.750   90.660      94.68   67081400

In [21]:
features_df.loc["TSLA"]

                ATR    ATRP     TRP      RSI  Mom_21  Consistency   IR_63  Beta_63   DD_21  AutoCorr_15  Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5  Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount
Date
2010-06-29      NaN  0.0000  0.0000  50.0000     NaN          NaN     NaN   1.0000  0.0000       0.0000     NaN           NaN        NaN        NaN     0.0000              NaN               NaN                  NaN
2010-06-30   0.4747  0.2988  0.2988   0.0000     NaN          NaN     NaN   1.0000  0.0000       0.0000 -0.0025           NaN        NaN        NaN     0.0000              NaN               NaN                  NaN
2010-07-01   0.4677  0.3194  0.2573   0.0000     NaN          NaN     NaN   1.0000  0.0000       0.0000 -0.0785           NaN        NaN        NaN     0.0000              NaN               NaN                  NaN
2010-07-02   0.4552  0.3556  0.2286   0.0000     NaN          NaN     NaN   1.0000  0.0000       0.0000 -0.1257           NaN        NaN        NaN     0.0000              NaN               NaN                  NaN
2010-07-06   0.4425  0.4120  0.2588   0.0000     NaN          0.0     NaN   1.0000  0.0000       0.0000 -0.1609           NaN    -0.1004    -0.6060     0.0000              NaN               NaN                  NaN
...             ...     ...     ...      ...     ...          ...     ...      ...     ...          ...     ...           ...        ...        ...        ...              ...               ...                  ...
2026-04-30  14.2693  0.0374  0.0434  51.8141  0.0266          0.6 -0.0898   1.6384 -0.0474       0.0782  0.0237        0.6162     0.0013    -0.0814     0.0060              0.0        2.8642e+10                  0.0
2026-05-01  14.6087  0.0374  0.0487  56.1443  0.0251          0.6 -0.1041   1.6728 -0.0245       0.1042  0.0241        0.7438     0.0078     0.0769     0.0084              0.0        2.8534e+10                  0.0
2026-05-04  14.2680  0.0364  0.0251  56.9111  0.0885          0.6 -0.0774   1.6831 -0.0202       0.0968  0.0043        0.7672     0.0133     0.5663     0.0121              0.0        2.8534e+10                  0.0
2026-05-05  14.1860  0.0364  0.0337  54.9873  0.1036          0.6 -0.0981   1.6853 -0.0281       0.0982 -0.0080        0.7236     0.0115     0.5531     0.0037              0.0        2.8462e+10                  0.0
2026-05-06  14.4342  0.0362  0.0443  59.3938  0.1502          0.8 -0.0631   1.6637 -0.0047      -0.1886  0.0240        0.8535     0.0084     0.3830    -0.0049              0.0        2.8462e+10                  0.0

[3988 rows x 18 columns]