v61 
- **Verified all metric calculation with Excel** 
- Updated core.analyzer
- Replaced the `Result` pattern with exceptions and flattened the logic
- Refactored the `AlphaEngine` into a streamlined Orchestrator pattern
-  **Strict Date Logic:** No more "Time Travel" bugs.
-  **Dataclass Contracts:** No more "Magic String" typos or blind dictionaries.
-  **Exception Flow:** The `run` method is now a clean, readable story instead of a maze of `if/else` checks.
-  **Performance Workers:** Math is separated from orchestration.
- Ret_1d, explicitly turns division-by-zero results (`inf`) into `NaN`, and replace [np.inf, -np.inf] with np.nan

v60  
- Converted code from notebook to modular system.
- Fixed divide by zero warning from calculate_gain
- Added subtitle to subplots
- Added Volatility Regime plot

v59  
- Removed "nest" of if-statements in **AlphaEngine.run**
- Use **Result Pattern** to handle errors
- Change verify_analyzer_short and verify_analyzer_long gain calculation from simple return to logarithmic return
- Change calculate_gain from simple return to logarithmic return
- Remove bfill from calculate_gain to prevent backfill with future data
- Verify macro_df calculation

v57, v58  
added marco subplotsThe macro regime framework is now fully documented with:
- Trend (SMA200 deviation) → Where we are in the cycle  
- Trend Velocity (Z) → How fast we're moving relative to normal
- VIX-Z → Market fear/complacency levels

v56  

- De-coupled features_df and macro_df
- generate_features and audit_feature_engineering_integrity use GLOBAL_SETTINGS

v55  
Added
- audit_feature_engineering_integrity (check calculation in features_df)  

These are the metrics in plot  
- --- 1. LEGACY / SANITY CHECKS ---
- "Price Gain": lambda obs: QuantUtils.calculate_gain(obs["lookback_close"]),
- "Sharpe": lambda obs: QuantUtils.calculate_sharpe(obs["lookback_returns"]),
- "Sharpe (ATRP)": lambda obs: QuantUtils.calculate_sharpe_vol(
        obs["lookback_returns"], obs["atrp"]
    ),
- "Sharpe (TRP)": lambda obs: QuantUtils.calculate_sharpe_vol(
        obs["lookback_returns"], obs["trp"]
    ),
- --- 2. NEW QUANT METRICS ---
- "Momentum (21d)": lambda obs: obs["mom_21"],
- "Information Ratio (IR)": lambda obs: obs["ir_63"],  # Kept this one
- "Consistency (WinRate)": lambda obs: obs["consistency"],
- "Oversold (RSI)": lambda obs: -obs["rsi"],
- "Dip Buyer (Drawdown)": lambda obs: -obs["dd_21"],
- "Low Volatility": lambda obs: -obs["atrp"],

v54
-  **Replaced plot_walk_forward_analyzer with create_walk_forward_analyzer**

v53  
Looking at this registry with a quant lens, the list is **comprehensive but bloated**—we have **momentum measured five times under different names** (roc₁, roc₃, roc₅, roc₁₀, roc₂₁ and their negative twins “Pullback”).  
That’s **10 slots** telling us almost the same story at slightly different lags; in a rank-based engine they will **crowd the signal space** and inflate turnover without adding IC.

Duplicate / redundant cluster  
- Momentum 1 D ↔ Pullback 1 D (perfect mirror)  
- Same for 3 D, 5 D, 10 D, 21 D.  
**Keep one side only**—momentum is enough; the portfolio constructor can always **reverse the rank** if it wants “oversold”.

Close cousins that can be merged  
- “Sharpe” vs “Sharpe (ATRP)” – both are return / vol; keep **ATRP version** because it is regime-aware and smoother.  
- “RVol” vs “Vol_Regime” – both capture vol expansion; keep the **longer-memory one** (Vol_Regime) and drop the intraday snapshot.

Gaps that matter to a quant  
1. **Consistency sensor**: nowhere do we ask “how often did the ticker close higher than it opened?” – add **5-day win-rate** or **up-day hit-ratio**.  
2. **Risk-adjusted intraday strength**: no **Sharpe(on-balance volume)** or **volume-momentum efficiency**; OBV_Score is raw, not risk-scaled.  
3. **Benchmark-relative consistency**: “Alpha (RelStrength)” is cumulative; add **rolling information ratio vs SPY** to catch *sustained* alpha, not one gap.  
4. **Tail flag**: no **skew** or **max-drawdown** metric; a single 20 % gap stock can poison the book.  
5. **Macro regime overlay**: no **beta-to-SPY** or **correlation-break** sensor; mid-2022 macro swings showed that low-beta names behaved like a different asset class.

Recommended minimal clean set (≤ 12 metrics)

1. Sharpe(ATRP) – strategic anchor  
2. Momentum 21 D – slow trend  
3. Momentum 5 D – fast trend  
4. 5-day win-rate – consistency  
5. RSI(Trend) – strength confirmation  
6. OBV_Score – volume conviction  
7. Vol_Regime – vol expansion filter  
8. Alpha(RelStrength) 63-day IR – benchmark consistency  
9. Max 21-day drawdown – tail guard  
10. Beta-to-SPY – macro regime tag  

Drop everything else; the freed-up slots reduce collinearity, cut turnover, and leave head-room for **interaction terms** (e.g. momentum × consistency) that actually add orthogonal signal.



Below is a single, fully-vectorised block that adds the **five gap metrics** to your existing MultiIndex OHLCV frame.  
It never loops over tickers; everything is done with `groupby(level=0).rolling(...)` so it runs in C-speed and keeps the same index.

```python
import pandas as pd
import numpy as np

# ----------  CONFIG  -------------------------------------------------
LKB_RET   = 21          # look-back for return-based metrics
LKB_CONS  = 5           # consistency window (days)
LKB_IR    = 63          # IR window
LKB_BETA  = 63          # beta window
LKB_TAIL  = 21          # max-drawdown window
BENCH     = 'SPY'       # ticker that exists in your universe
# ---------------------------------------------------------------------

# 1.  DAILY RETURNS ----------------------------------------------------
df['ret'] = df.groupby(level=0)['Adj Close'].pct_change()

# 2.  CONSISTENCY SENSOR  (5-day win-rate) -----------------------------
df['up']  = df['ret'].gt(0).astype(int)
df['consistency_5d'] = (df.groupby(level=0)['up']
                          .rolling(LKB_CONS).mean()
                          .reset_index(level=0, drop=True))

# 3.  BENCHMARK-RELATIVE CONSISTENCY  (63-day IR vs SPY) ---------------
# need benchmark return
bench_ret = df.xs(BENCH, level=0)['ret'].rename('bench_ret')
df = df.join(bench_ret, how='left')          # broadcast to all tickers

df['active'] = df['ret'] - df['bench_ret']
g = df.groupby(level=0)
active_mean  = g['active'].rolling(LKB_IR).mean()
active_std   = g['active'].rolling(LKB_IR).std()
df['IR_63d'] = active_mean / active_std      # Information Ratio

# 4.  TAIL FLAG  (21-day max drawdown) ---------------------------------
roll_max = g['Adj Close'].rolling(LKB_TAIL).max()
dd = (df['Adj Close'] - roll_max) / roll_max
df['max_dd_21d'] = dd.groupby(level=0).rolling(LKB_TAIL).min()

# 5.  MACRO REGIME OVERLAY  (beta to SPY) ------------------------------
cov  = g['ret'].rolling(LKB_BETA).cov(df['bench_ret'])
var  = df['bench_ret'].groupby(level=0).rolling(LKB_BETA).var()
df['beta_SPY'] = cov / var

# 6.  RISK-ADJUSTED INTRADAY STRENGTH  (OBV Sharpe) --------------------
# OBV
df['close_chg'] = df.groupby(level=0)['Adj Close'].diff()
df['vol_dir']   = np.where(df['close_chg'] > 0,  df['Volume'],
                   np.where(df['close_chg'] < 0, -df['Volume'], 0))
df['obv'] = df.groupby(level=0)['vol_dir'].cumsum()

# OBV return & vol
df['obv_ret'] = df.groupby(level=0)['obv'].pct_change()
obv_mean = g['obv_ret'].rolling(LKB_RET).mean()
obv_std  = g['obv_ret'].rolling(LKB_RET).std()
df['OBV_Sharpe_21d'] = obv_mean / obv_std

# drop helper columns --------------------------------------------------
df.drop(columns=['up','bench_ret','active','close_chg','vol_dir'], inplace=True)
```

After the block you have five new columns:

- `consistency_5d`      – 5-day win-rate (0-1)  
- `IR_63d`              – 63-day Information Ratio vs SPY  
- `max_dd_21d`          – 21-day maximum drawdown (≤ 0)  
- `beta_SPY`            – rolling beta to SPY  
- `OBV_Sharpe_21d`      – OBV risk-adjusted momentum  

All are aligned to the original MultiIndex and ready to be ranked or z-scored inside your Alpha Engine.

v52  
- **Cascase Filter results `AGREED` with bot_v54i.ipynb**
- **Cascade Filter works with df_ohlcv_subset**
- **verify_engine_results_short_form**
- **verify_engine_results_long_form**
-  **The Temporal Alignment Fix:** We synchronized the "Reward" (Returns) and "Risk" (Volatility) by implementing the $N-1$ denominator logic. This ensures that Day 1's volatility no longer dilutes your Sharpe scores.
-  **The Event-Driven Re-normalization:** We verified that the Engine correctly resets capital and weights at the start of the Holding period, giving you an accurate "Fresh Start" performance metric.
-  **The Double-Blind Verification:** We proved that the Engine's True Range (TRP) math is flawless by recreating it from raw High/Low/Close data and achieving an 8-decimal match.
-  **Mathematical Fortification:** We centralized all logic into a polymorphic `QuantUtils` kernel that handles both single-portfolio reports and whole-universe rankings with built-in numerical safety.
-  **Volatility Evolution:** We successfully added `TRP` (True Range Percent) and the `Sharpe (TRP)` metric, giving you a raw, high-frequency alternative to the smoothed ATR.
-  **Data Integrity:** We implemented the "Momentum Collapse" tripwire (`verify_ranking_integrity`) to ensure that your risk-adjusted rankings never accidentally devolve into simple price momentum.
-  **The "Audit Pack" Architecture:** We collapsed fragmented results into a single, atomic container, ensuring that your inputs, results, and debug data are always perfectly synchronized.
-  **Total Transparency:** We replaced scattered CSV files with a unified **Excel Audit Report**, allowing for 1-to-1 manual verification of every calculation in the system.

v51

UNDO v50, Calculate Sharpe(ATR) using mean over lookback period.  

Comment out ``# --- PINPOINT START: ATRP SWITCH ---`` in function ``_select_tickers`` can switch between ``Averaged ATRP over lookback period`` and ``Current ATRP``  
    # --- PINPOINT START: ATRP SWITCH ---  
    # To switch between Old (Averaged ATRP) and New (Current ATRP):  
    # 1. Comment out the logic you DON'T want.  
    # 2. Uncomment the logic you DO want.

v50

Ticker selection based on atrp_value_for_obs based on decision day, was based on average over lookback period.

v48  
### Summary of what you just accomplished:
1.  **Strict Math:** `QuantUtils` now contains an `assert` that prevents any dev (or AI) from filling the first day with 0.0.
2.  **Semantic Protection:** Variables are now named `returns_WITH_BOUNDARY_NAN`, signaling to the AI that the Null value is part of its identity.
3.  **Complete SOLID Separation:** The Engine CONDUCTS the simulation, while `QuantUtils` CALCULATES the results. They no longer share logic.

**1. Data Flow of `plot_walk_forward_analyzer`**
The function acts as a **UI wrapper** around the `AlphaEngine` class. The flow is:
1.  **Input:** User selects parameters (Dates, Lookback, Strategy).
2.  **State Construction:** `AlphaEngine` slices the historical data (`df_ohlcv`, `df_atrp`) up to the `decision_date`.
3.  **Policy Execution (Hardcoded):** The engine applies the logic (e.g., `METRIC_REGISTRY['Sharpe']`) to rank stocks based *only* on the Lookback window.
4.  **Environment Step:** It simulates a "Buy" at `decision_date + 1` and calculates the returns over the `holding_period`.
5.  **Reward Generation:** It outputs performance metrics (`holding_p_gain`, `holding_p_sharpe`).

In [1]:
# 1. Enable Autoreload
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

def add_project_root_to_path():
    """Find notebooks_RLVR and add to sys.path."""
    current = Path.cwd()

    # Search upward for notebooks_RLVR folder
    for path in [current] + list(current.parents):
        if path.name == "notebooks_RLVR":
            sys.path.insert(0, str(path))
            print(f"✓ Added to path: {path}")
            return path
        # Also check if notebooks_RLVR exists as child (for running from stocks/)
        candidate = path / "notebooks_RLVR"
        if candidate.exists():
            sys.path.insert(0, str(candidate))
            print(f"✓ Added to path: {candidate}")
            return candidate

    raise RuntimeError("Could not find notebooks_RLVR directory")


# Run once at notebook start
add_project_root_to_path()


# 2. Force reload cached modules (run this to refresh code changes)
# import importlib

modules_to_reload = [
    "core.analyzer",
    "core.auditor",
    "core.contracts",    
    "core.engine",
    "core.features",
    "core.paths",
    "core.performance",
    "core.quant",
    "core.result",
    "core.settings",
    "core.utils",
    "strategy.registry",
]

for mod in modules_to_reload:
    if mod in sys.modules:
        del sys.modules[mod]


# 3. Standard imports
import pandas as pd
# import os
import numpy as np

from IPython.display import display
# from dataclasses import fields, asdict, is_dataclass
# from typing import List, Union, Tuple 


# 4. Fresh imports (these will re-import from disk due to cache clearing above)

from core.analyzer import create_walk_forward_analyzer
from core.auditor import SystemAuditor as SA
from core.contracts import FilterPack
from core.engine import AlphaEngine
from core.features import generate_features
from core.paths import OUTPUT_DIR
# from core.performance import PerformanceCalculator
# from core.quant import QuantUtils
# from core.result import TaskResult
from core.settings import GLOBAL_SETTINGS
from core.utils import SystemUtils as SU
# from strategy.registry import METRIC_REGISTRY


# 5. Pandas display settings
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", 50)
pd.set_option("display.precision", 4)


# # 6. Instantiate engine (customize DataFrames as needed)
# master_engine = AlphaEngine(
#     df_ohlcv=df_ohlcv,
#     features_df=features_df,
#     macro_df=macro_df,
#     df_close_wide=df_close_wide,
#     df_atrp_wide=df_atrp_wide,
#     df_trp_wide=df_trp_wide,
# )

✓ Added to path: c:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR
NOTEBOOKS_RLVR_ROOT: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR

OUTPUT_DIR: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output

In [2]:
from dotenv import load_dotenv
import os
from pathlib import Path


def load_env_from_root(env_var_name):
    """
    Load specified environment variable from .env file in root directory

    Parameters:
    -----------
    env_var_name : str
        Name of the environment variable to retrieve (e.g., 'DATA_PATH_OHLCV', 'API_KEY')

    Returns:
    --------
    str : Value of the requested environment variable

    Example:
    --------
    DATA_PATH_OHLCV = load_env_from_root('DATA_PATH_OHLCV')
    API_KEY = load_env_from_root('API_KEY')
    """
    # Start from current file or current working directory
    try:
        start_path = Path(__file__).resolve().parent
    except NameError:
        # If __file__ not defined (e.g., Jupyter), use current working directory
        start_path = Path.cwd()

    # Search upwards for the .env directory
    current = start_path
    for _ in range(10):  # Limit search depth
        env_path = current / ".env" / "my_api_key.env"
        if env_path.exists():
            load_dotenv(env_path, override=True)
            value = os.getenv(env_var_name)
            if value is None:
                raise KeyError(f"Variable '{env_var_name}' not found in {env_path}")
            return value

        # Go up one level
        parent = current.parent
        if parent == current:  # Reached root
            break
        current = parent

    raise FileNotFoundError(
        f"Could not find .env/my_api_key.env when searching for '{env_var_name}'"
    )


#

In [3]:
DATA_PATH_OHLCV = load_env_from_root("DATA_PATH_OHLCV")
DATA_PATH_INDICES = load_env_from_root("DATA_PATH_INDICES")
print(f"DATA_PATH_OHLCV: {DATA_PATH_OHLCV}")
print(f"DATA_PATH_INDICES: {DATA_PATH_INDICES}")

DATA_PATH_OHLCV: c:\Users\ping\Files_win10\python\py311\stocks\data\df_OHLCV_stocks_etfs.parquet
DATA_PATH_INDICES: c:\Users\ping\Files_win10\python\py311\stocks\data\df_indices.parquet

In [4]:
df_indices = pd.read_parquet(DATA_PATH_INDICES, engine="pyarrow")
print(f"df_indices:|n{df_indices}")

df_indices:|n                   Adj Open  Adj High  Adj Low  Adj Close  Volume
Ticker Date
^BSESN 1997-07-01   4263.11   4301.77  4247.66    4300.86       0
       1997-07-02   4302.96   4395.31  4295.40    4333.90       0
       1997-07-03   4335.79   4393.29  4299.97    4323.46       0
       1997-07-04   4332.70   4347.59  4300.58    4323.82       0
       1997-07-07   4326.81   4391.01  4289.49    4291.45       0
...                     ...       ...      ...        ...     ...
^VIX3M 2026-03-12     26.27     26.99    25.80      26.95       0
       2026-03-13     25.92     27.34    25.51      27.28       0
       2026-03-16     25.98     25.98    24.67      24.92       0
       2026-03-17     24.26     24.58    23.87      24.33       0
       2026-03-18     25.00     26.57    24.82      26.56       0

[136268 rows x 5 columns]

In [5]:
_indices = df_indices.index.get_level_values(0).unique().tolist()
display(_indices)
df_indices.info()

['^BSESN',
 '^DJI',
 '^FCHI',
 '^FTSE',
 '^GDAXI',
 '^GSPC',
 '^HSI',
 '^IXIC',
 '^N225',
 '^NYA',
 '^STOXX50E',
 '^VIX',
 '^VIX3M']

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 136268 entries, ('^BSESN', Timestamp('1997-07-01 00:00:00')) to ('^VIX3M', Timestamp('2026-03-18 00:00:00'))
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Adj Open   136268 non-null  float64
 1   Adj High   136268 non-null  float64
 2   Adj Low    136268 non-null  float64
 3   Adj Close  136268 non-null  float64
 4   Volume     136268 non-null  int64
dtypes: float64(4), int64(1)
memory usage: 6.2+ MB

In [6]:
print(f"Takes about 1.5 minutes")
df_ohlcv = pd.read_parquet(DATA_PATH_OHLCV, engine="pyarrow")

Takes about 1.5 minutes

In [7]:
print(f"df_ohlcv.head():\n {df_ohlcv.head()}\n")
df_ohlcv.info()

df_ohlcv.head():
                    Adj Open  Adj High  Adj Low  Adj Close    Volume
Ticker Date
A      1999-11-18   27.1966   29.8864  23.9091    26.3000  74849954
       1999-11-19   25.6649   25.7023  23.7970    24.1333  18230872
       1999-11-22   24.6936   26.3000  23.9465    26.3000   7871810
       1999-11-23   25.4034   26.0759  23.9091    23.9091   7151080
       1999-11-24   23.9838   25.0672  23.9091    24.5442   5795948

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9504947 entries, ('A', Timestamp('1999-11-18 00:00:00')) to ('ZWS', Timestamp('2026-03-18 00:00:00'))
Data columns (total 5 columns):
 #   Column     Dtype
---  ------     -----
 0   Adj Open   float64
 1   Adj High   float64
 2   Adj Low    float64
 3   Adj Close  float64
 4   Volume     int64
dtypes: float64(4), int64(1)
memory usage: 399.5+ MB

In [8]:
print(f"Takes about 2.5 minutes to generate_features")

features_df, macro_df = generate_features(
    df_ohlcv=df_ohlcv,
    df_indices=df_indices,
    benchmark_ticker=GLOBAL_SETTINGS["benchmark_ticker"],
)

Takes about 2.5 minutes to generate_features
⚡ Generating Decoupled Features (Benchmark: SPY)...

In [9]:
print(f"features_df.info():\n{features_df.info()}\n")
print(f"features_df.index.names:\n{features_df.index.names}\n")
print(f"macro_df.info():\n{macro_df.info()}\n")
print(f"macro_df.index.names:\n{macro_df.index.names}\n")

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 9504947 entries, ('A', Timestamp('1999-11-18 00:00:00')) to ('ZWS', Timestamp('2026-03-18 00:00:00'))
Data columns (total 13 columns):
 #   Column               Dtype
---  ------               -----
 0   ATR                  float64
 1   ATRP                 float64
 2   TRP                  float64
 3   RSI                  float64
 4   Mom_21               float64
 5   Consistency          float64
 6   IR_63                float64
 7   Beta_63              float64
 8   DD_21                float64
 9   Ret_1d               float64
 10  RollingStalePct      float64
 11  RollMedDollarVol     float64
 12  RollingSameVolCount  float64
dtypes: float64(13)
memory usage: 979.7+ MB
features_df.info():
None

features_df.index.names:
['Ticker', 'Date']

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 16160 entries, 1962-01-02 to 2026-03-18
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Mkt_Ret            16160 non-null  float64
 1   Macro_Trend        16160 non-null  float64
 2   Macro_Trend_Vel    16160 non-null  float64
 3   Macro_Trend_Vel_Z  16160 non-null  float64
 4   Macro_Trend_Mom    16160 non-null  float64
 5   Macro_Vix_Z        16160 non-null  float64
 6   Macro_Vix_Ratio    16160 non-null  float64
dtypes: float64(7)
memory usage: 1.5 MB
macro_df.info():
None

macro_df.index.names:
['Date']

In [10]:
# Pre-flight Automated Audit Suite
checks = [
    SA.verify_math_integrity(),
    SA.verify_ranking_integrity(),
    SA.verify_vol_alignment_integrity(),
    SA.verify_feature_engineering_integrity(),
]

for check in checks:
    icon = "✅" if check.ok else "🔥"
    print(f"{icon} {check.msg}")
    if not check.ok:
        print("🛑 Critical Failure. System Halted.")
        break

print("=" * 85)
# Separate verify_marco_engine output from intertwine with other outputs

checks = [
    SA.verify_macro_engine(
        df_ohlcv=df_ohlcv,
        df_indices=df_indices,
        original_macro_df=macro_df,
        settings=GLOBAL_SETTINGS,
    ),
]

for check in checks:
    icon = "✅" if check.ok else "🔥"
    print(f"{icon} {check.msg}")
    if not check.ok:
        print("🛑 Critical Failure. System Halted.")
        break

--- 🛡️ Starting Feature Engineering Audit ---
⚡ Generating Decoupled Features (Benchmark: SPY)...
Audit Values:
[ nan 25.  17.5]
✅ FEATURE INTEGRITY PASSED: Wilder's ATR logic is strictly enforced.
✅ Mathematical boundaries strictly enforced.
✅ Ranking integrity strictly enforced.
✅ Reward and Risk are strictly synchronized.
✅ Wilder's ATR logic is strictly enforced.
=====================================================================================
--- Macro Verification (Benchmark: SPY) ---

Comparing verification vs original (Clip Threshold: 4.0):
✅ Mkt_Ret              | PASS (Max Diff: 0.00e+00)
✅ Macro_Trend          | PASS (Max Diff: 0.00e+00)
✅ Macro_Trend_Vel      | PASS (Max Diff: 0.00e+00)
✅ Macro_Trend_Vel_Z    | PASS (Max Diff: 0.00e+00)
✅ Macro_Trend_Mom      | PASS (Max Diff: 0.00e+00)
✅ Macro_Vix_Z          | PASS (Max Diff: 0.00e+00)
✅ Macro_Vix_Ratio      | PASS (Max Diff: 0.00e+00)
✅ Macro Integrity Verified

In [11]:
print(
    "🚀 Generating Wide Matrices for Instant Backtesting... (takes about 1 minute to run)"
)

# 1. Price Matrix
df_close_wide = df_ohlcv["Adj Close"].unstack(level=0)

# 2. Volatility Matrices (Unstack and Align)
# Using features_df (the first item from the tuple)
print("   - Unstacking ATRP...")
df_atrp_wide = features_df["ATRP"].unstack(level=0).reindex_like(df_close_wide)

print("   - Unstacking TRP...")
df_trp_wide = features_df["TRP"].unstack(level=0).reindex_like(df_close_wide)

# 3. Handle Data Gaps (Sanitize the Wide Matrices)
if GLOBAL_SETTINGS["handle_zeros_as_nan"]:
    df_close_wide = df_close_wide.replace(0, np.nan)

# Forward fill up to the limit, then fill remaining with the "Disaster Detection" value
df_close_wide = df_close_wide.ffill(limit=GLOBAL_SETTINGS["max_data_gap_ffill"])
df_close_wide = df_close_wide.fillna(GLOBAL_SETTINGS["nan_price_replacement"])

print(
    f"✅ Pre-computation Complete. Tickers: {len(df_close_wide.columns)}, Days: {len(df_close_wide)}"
)
print("   Ready: df_close_wide, df_atrp_wide, df_trp_wide, and macro_df.")

🚀 Generating Wide Matrices for Instant Backtesting... (takes about 1 minute to run)
   - Unstacking ATRP...
   - Unstacking TRP...
✅ Pre-computation Complete. Tickers: 1582, Days: 16160
   Ready: df_close_wide, df_atrp_wide, df_trp_wide, and macro_df.

In [12]:
# 6. Instantiate engine (customize DataFrames as needed)
master_engine = AlphaEngine(
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    macro_df=macro_df,
    df_close_wide=df_close_wide,
    df_atrp_wide=df_atrp_wide,
    df_trp_wide=df_trp_wide,
)

In [ ]:
# universe_subset=None means "Scan the whole market"
analyzer1, stage1_pack = create_walk_forward_analyzer(
    master_engine, universe_subset=None
)

print("🚀 Ready for Stage 1: Run Simulation for first filter.")
analyzer1.show()

🚀 Ready for Stage 1: Run Simulation for first filter.
DEBUG: 937 stocks passed filters on 2025-12-10

VBox(children=(HTML(value='<b>1. Timeline Configuration:</b> (Past <--- Decision ---> Future)'), HBox(children…

In [ ]:
# Get decision date from last run
decision_date_last_run = FilterPack(decision_date=analyzer1.last_run.decision_date)

# 1. LAUNCH STAGE 2 (Cascade)
# universe_subset=analyzer1.last_run.tickers means "Scan the whole market"
analyzer2, stage1_pack = create_walk_forward_analyzer(
    master_engine,
    universe_subset=analyzer1.last_run.tickers,
    # universe_subset=None,
    filter_pack=decision_date_last_run,
)

print("🚀 Ready for Stage 2: Run Simulation for 2nd filter.")
analyzer2.show()

🚀 Ready for Stage 2: Run Simulation for 2nd filter.

VBox(children=(HTML(value='<b>1. Timeline Configuration:</b> (Past <--- Decision ---> Future)'), HBox(children…

In [15]:
###############################
###############################

In [43]:
my_analyzer = analyzer1

my_res = SU.visualize_analyzer_structure(my_analyzer)

====================================================================
🔍 HIGH-TRANSPARENCY AUDIT MAP
====================================================================
[  0] 📦 audit_pack (EngineOutput)
[  1]   📈 portfolio_series (shape=(28,))
[  2]   📈 benchmark_series (shape=(28,))
[  3]   🧮 normalized_plot_data (shape=(28, 10))
[  4]   📂 tickers (len=10)
[  5]     📄 index_0 (str)
[  6]     📄 index_1 (str)
[  7]     📄 index_2 (str)
[  8]     📄 index_3 (str)
[  9]     📄 index_4 (str)
[ 10]     📄 index_5 (str)
[ 11]     📄 index_6 (str)
[ 12]     📄 index_7 (str)
[ 13]     📄 index_8 (str)
[ 14]     📄 index_9 (str)
[ 15]   📈 initial_weights (shape=(10,))
[ 16]   📂 perf_metrics (len=24)
[ 17]     🔢 full_p_gain (float)
[ 18]     🔢 full_p_sharpe (float)
[ 19]     🔢 full_p_sharpe_atrp (float)
[ 20]     🔢 full_p_sharpe_trp (float)
[ 21]     🔢 lookback_p_gain (float)
[ 22]     🔢 lookback_p_sharpe (float)
[ 23]     🔢 lookback_p_sharpe_atrp (float)
[ 24]     🔢 lookback_p_sharpe_trp (float)
[ 25]     🔢 holding_p_gain (float)
[ 26]     🔢 holding_p_sharpe (float)
[ 27]     🔢 holding_p_sharpe_atrp (float)
[ 28]     🔢 holding_p_sharpe_trp (float)
[ 29]     🔢 full_b_gain (float)
[ 30]     🔢 full_b_sharpe (float)
[ 31]     🔢 full_b_sharpe_atrp (float)
[ 32]     🔢 full_b_sharpe_trp (float)
[ 33]     🔢 lookback_b_gain (float)
[ 34]     🔢 lookback_b_sharpe (float)
[ 35]     🔢 lookback_b_sharpe_atrp (float)
[ 36]     🔢 lookback_b_sharpe_trp (float)
[ 37]     🔢 holding_b_gain (float)
[ 38]     🔢 holding_b_sharpe (float)
[ 39]     🔢 holding_b_sharpe_atrp (float)
[ 40]     🔢 holding_b_sharpe_trp (float)
[ 41]   🧮 results_df (shape=(10, 2))
[ 42]   📅 start_date (Timestamp)
[ 43]   📅 decision_date (Timestamp)
[ 44]   📅 buy_date (Timestamp)
[ 45]   📅 holding_end_date (Timestamp)
[ 46]   📈 portfolio_atrp_series (shape=(28,))
[ 47]   📈 benchmark_atrp_series (shape=(28,))
[ 48]   📈 portfolio_trp_series (shape=(28,))
[ 49]   📈 benchmark_trp_series (shape=(28,))
[ 50]   📄 error_msg (NoneType)
[ 51]   📂 debug_data (len=8)
[ 52]     📂 audit_liquidity (len=6)
                ╰── date --> [See ID 43]
[ 53]       🔢 total_tickers_available (int)
[ 54]       🔢 percentile_setting (float)
[ 55]       🔢 final_cutoff_usd (shape=())
[ 56]       📄 tickers_passed (shape=())
[ 57]       🧮 universe_snapshot (shape=(1552, 14))
[ 58]     🧮 full_universe_ranking (shape=(924, 4))
[ 59]     📂 meta (len=4)
[ 60]       🔢 dropped_count (int)
[ 61]       📂 dropped_tickers (len=0)
[ 62]       🔢 clean_count (int)
[ 63]       📄 selection_range (str)
[ 64]     📦 inputs_snapshot (EngineInput)
[ 65]       📄 mode (str)
[ 66]       📅 start_date (Timestamp)
[ 67]       🔢 lookback_period (int)
[ 68]       🔢 holding_period (int)
[ 69]       📄 metric (str)
[ 70]       📄 benchmark_ticker (str)
[ 71]       🔢 rank_start (int)
[ 72]       🔢 rank_end (int)
[ 73]       📂 quality_thresholds (len=4)
[ 74]         🔢 min_median_dollar_volume (int)
[ 75]         🔢 min_liquidity_percentile (float)
[ 76]         🔢 max_stale_pct (float)
[ 77]         🔢 max_same_vol_count (int)
[ 78]       📂 manual_tickers (len=1)
[ 79]         📄 index_0 (str)
[ 80]       🔢 debug (bool)
[ 81]       📄 universe_subset (NoneType)
[ 82]     📂 verification (len=2)
[ 83]       📂 p (len=4)
                  ╰── val --> [See ID 1]
[ 84]         📈 ret (shape=(28,))
                  ╰── atrp --> [See ID 46]
                  ╰── trp --> [See ID 48]
[ 85]       📂 b (len=4)
                  ╰── val --> [See ID 2]
[ 86]         📈 ret (shape=(28,))
                  ╰── atrp --> [See ID 47]
                  ╰── trp --> [See ID 49]
[ 87]     📂 portfolio_raw_components (len=4)
[ 88]       🧮 prices (shape=(28, 10))
[ 89]       🧮 atrp (shape=(28, 10))
[ 90]       🧮 trp (shape=(28, 10))
[ 91]       🧮 ohlcv_raw (shape=(280, 5))
[ 92]     📂 benchmark_raw_components (len=4)
[ 93]       🧮 prices (shape=(28, 1))
[ 94]       🧮 atrp (shape=(28, 1))
[ 95]       🧮 trp (shape=(28, 1))
[ 96]       🧮 ohlcv_raw (shape=(28, 5))
              ╰── selection_audit --> [See ID 58]
[ 97]   🧮 macro_df (shape=(16160, 7))

In [44]:
SU.peek(3, my_res)

 ============================================================
 📍 INDEX: [3]
 🏷️  NAME:  normalized_plot_data
 📂 PATH:  audit_pack -> normalized_plot_data
 ============================================================

Ticker         SHV    JAAA    SGOV     BIL    USFR    TFLO    MINT    AVGO    PULS    TEVA
Date
2024-12-02  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
2024-12-03  1.0003  1.0016  1.0001  1.0002  0.9998  1.0002  1.0002  1.0098  1.0002  1.0529
2024-12-04  1.0003  1.0014  1.0003  1.0003  1.0002  1.0000  1.0004  1.0243  1.0004  1.0691
2024-12-05  1.0005  1.0010  1.0004  1.0004  1.0004  1.0004  1.0005  1.0238  1.0004  1.0703
2024-12-06  1.0010  1.0012  1.0009  1.0009  1.0006  1.0008  1.0009  1.0782  1.0010  1.0408
2024-12-09  1.0012  1.0020  1.0010  1.0010  1.0008  1.0010  1.0011  1.0747  1.0012  1.0571
2024-12-10  1.0012  1.0022  1.0012  1.0012  1.0008  1.0010  1.0012  1.0318  1.0012  1.0420
2024-12-11  1.0014  1.0022  1.0012  1.0013  1.0010  1.0010  1.0014  1.1002  1.0014  1.0480
2024-12-12  1.0015  1.0020  1.0013  1.0015  1.0014  1.0014  1.0015  1.0850  1.0014  1.0096
2024-12-13  1.0017  1.0026  1.0018  1.0019  1.0016  1.0018  1.0016  1.3501  1.0014  0.9910
2024-12-16  1.0020  1.0036  1.0019  1.0020  1.0018  1.0018  1.0020  1.5014  1.0018  0.9916
2024-12-17  1.0020  1.0030  1.0019  1.0021  1.0020  1.0022  1.0020  1.4427  1.0022  1.2541
2024-12-18  1.0021  1.0022  1.0021  1.0021  1.0020  1.0021  1.0020  1.3430  1.0018  1.2733
2024-12-19  1.0024  1.0022  1.0023  1.0022  1.0024  1.0023  1.0019  1.3112  1.0020  1.2799
2024-12-20  1.0027  1.0030  1.0025  1.0027  1.0028  1.0029  1.0024  1.3260  1.0026  1.3267
2024-12-23  1.0028  1.0038  1.0027  1.0027  1.0030  1.0027  1.0025  1.3991  1.0026  1.3339
2024-12-24  1.0031  1.0040  1.0030  1.0029  1.0030  1.0033  1.0027  1.4433  1.0030  1.3465
2024-12-26  1.0032  1.0046  1.0031  1.0031  1.0034  1.0031  1.0029  1.4775  1.0028  1.3586
2024-12-27  1.0035  1.0054  1.0034  1.0035  1.0036  1.0035  1.0032  1.4558  1.0034  1.3676
2024-12-30  1.0038  1.0056  1.0034  1.0035  1.0036  1.0039  1.0035  1.4186  1.0038  1.3405
2024-12-31  1.0039  1.0056  1.0037  1.0038  1.0042  1.0041  1.0040  1.3961  1.0040  1.3237
2025-01-02  1.0041  1.0064  1.0039  1.0040  1.0044  1.0043  1.0038  1.3969  1.0042  1.2793
2025-01-03  1.0043  1.0062  1.0042  1.0041  1.0046  1.0045  1.0043  1.4004  1.0046  1.2757
2025-01-06  1.0045  1.0068  1.0042  1.0042  1.0048  1.0047  1.0045  1.4236  1.0049  1.2655
2025-01-07  1.0047  1.0066  1.0044  1.0044  1.0050  1.0049  1.0044  1.3768  1.0049  1.2973
2025-01-08  1.0047  1.0064  1.0046  1.0046  1.0052  1.0051  1.0048  1.3808  1.0053  1.2907
2025-01-10  1.0050  1.0072  1.0050  1.0050  1.0058  1.0053  1.0049  1.3507  1.0053  1.2577
2025-01-13  1.0052  1.0078  1.0052  1.0051  1.0060  1.0059  1.0051  1.3566  1.0055  1.2276

Ticker         SHV    JAAA    SGOV     BIL    USFR    TFLO    MINT    AVGO    PULS    TEVA
Date
2024-12-02  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000
2024-12-03  1.0003  1.0016  1.0001  1.0002  0.9998  1.0002  1.0002  1.0098  1.0002  1.0529
2024-12-04  1.0003  1.0014  1.0003  1.0003  1.0002  1.0000  1.0004  1.0243  1.0004  1.0691
2024-12-05  1.0005  1.0010  1.0004  1.0004  1.0004  1.0004  1.0005  1.0238  1.0004  1.0703
2024-12-06  1.0010  1.0012  1.0009  1.0009  1.0006  1.0008  1.0009  1.0782  1.0010  1.0408
2024-12-09  1.0012  1.0020  1.0010  1.0010  1.0008  1.0010  1.0011  1.0747  1.0012  1.0571
2024-12-10  1.0012  1.0022  1.0012  1.0012  1.0008  1.0010  1.0012  1.0318  1.0012  1.0420
2024-12-11  1.0014  1.0022  1.0012  1.0013  1.0010  1.0010  1.0014  1.1002  1.0014  1.0480
2024-12-12  1.0015  1.0020  1.0013  1.0015  1.0014  1.0014  1.0015  1.0850  1.0014  1.0096
2024-12-13  1.0017  1.0026  1.0018  1.0019  1.0016  1.0018  1.0016  1.3501  1.0014  0.9910
2024-12-16  1.0020  1.0036  1.0019  1.0020  1.0018  1.0018  1.0020  1.5014  1.0018  0.9916
2024-12-17  1.0020  1.0030  1.0019  1.0021  1.0020  1.0022  1.0020  1.4427  1.0022  1.2541
2024-12-18  1.0021  1.0022  1.0021  1.0021  1.0020  1.0021  1.0020  1.3430  1.0018  1.2733
2024-12-19  1.0024  1.0022  1.0023  1.0022  1.0024  1.0023  1.0019  1.3112  1.0020  1.2799
2024-12-20  1.0027  1.0030  1.0025  1.0027  1.0028  1.0029  1.0024  1.3260  1.0026  1.3267
2024-12-23  1.0028  1.0038  1.0027  1.0027  1.0030  1.0027  1.0025  1.3991  1.0026  1.3339
2024-12-24  1.0031  1.0040  1.0030  1.0029  1.0030  1.0033  1.0027  1.4433  1.0030  1.3465
2024-12-26  1.0032  1.0046  1.0031  1.0031  1.0034  1.0031  1.0029  1.4775  1.0028  1.3586
2024-12-27  1.0035  1.0054  1.0034  1.0035  1.0036  1.0035  1.0032  1.4558  1.0034  1.3676
2024-12-30  1.0038  1.0056  1.0034  1.0035  1.0036  1.0039  1.0035  1.4186  1.0038  1.3405
2024-12-31  1.0039  1.0056  1.0037  1.0038  1.0042  1.0041  1.0040  1.3961  1.0040  1.3237
2025-01-02  1.0041  1.0064  1.0039  1.0040  1.0044  1.0043  1.0038  1.3969  1.0042  1.2793
2025-01-03  1.0043  1.0062  1.0042  1.0041  1.0046  1.0045  1.0043  1.4004  1.0046  1.2757
2025-01-06  1.0045  1.0068  1.0042  1.0042  1.0048  1.0047  1.0045  1.4236  1.0049  1.2655
2025-01-07  1.0047  1.0066  1.0044  1.0044  1.0050  1.0049  1.0044  1.3768  1.0049  1.2973
2025-01-08  1.0047  1.0064  1.0046  1.0046  1.0052  1.0051  1.0048  1.3808  1.0053  1.2907
2025-01-10  1.0050  1.0072  1.0050  1.0050  1.0058  1.0053  1.0049  1.3507  1.0053  1.2577
2025-01-13  1.0052  1.0078  1.0052  1.0051  1.0060  1.0059  1.0051  1.3566  1.0055  1.2276

In [45]:
analyzer1.last_run.tickers
analyzer1.last_run.start_date
analyzer1.last_run.holding_end_date

Timestamp('2025-01-13 00:00:00')

In [46]:
# 3. Post-flight Reconciliation
audit = SA.verify_analyzer_short(my_analyzer)
if not audit.ok:
    print(f"🚨 ALERT: {audit.msg}")
    # You could trigger a notification or log the failure here

===============================================================================================
***********************************************************************************************
🕵️  STARTING SHORT-FORM AUDIT: Sharpe (ATRP) @ 2025-01-02
⚠️  ASSUMPTION: Verification logic is independent, but trusts Engine source DataFrames
    (engine.features_df, engine.df_close, and debug['portfolio_raw_components'])
***********************************************************************************************
===============================================================================================
🕵️  AUDIT: Sharpe (ATRP) @ 2025-01-02
===============================================================================================
LAYER 1: SURVIVAL  | Universe: 1552 -> Survivors: 924 | ✅ PASS
LAYER 2: SELECTION | Strategy: Sharpe (ATRP) | Selection Match: ✅ PASS
LAYER 3: PERFORMANCE (Holding Period: 5 days)
Metric               | Engine       | Manual       | Status
-----------------------------------------------------------------------------------------------
Gain                 |    -0.006031 |    -0.006031 | ✅ PASS
Sharpe               |    -9.178441 |    -9.178441 | ✅ PASS
Sharpe (ATRP)        |    -0.147304 |    -0.147304 | ✅ PASS
Sharpe (TRP)         |    -0.167143 |    -0.167143 | ✅ PASS
===============================================================================================

In [47]:
audit = SA.verify_analyzer_long(my_analyzer, n_tickers=5)

=====================================================================================
🛡️  STARTING NUCLEAR AUDIT | 2025-01-02 | Sharpe (ATRP)
*************************************************************************************
⚠️  ASSUMPTION: Verification logic is independent, but trusts Engine source DataFrames
    (engine.features_df, engine.df_close, and debug['portfolio_raw_components'])
*************************************************************************************
=====================================================================================
📝 1. PERFORMANCE RECONCILIATION

Period                     Full Holding Lookback
Entity    Metric
Benchmark Gain           ✅ PASS  ✅ PASS   ✅ PASS
          Sharpe         ✅ PASS  ✅ PASS   ✅ PASS
          Sharpe (ATRP)  ✅ PASS  ✅ PASS   ✅ PASS
          Sharpe (TRP)   ✅ PASS  ✅ PASS   ✅ PASS
Group     Gain           ✅ PASS  ✅ PASS   ✅ PASS
          Sharpe         ✅ PASS  ✅ PASS   ✅ PASS
          Sharpe (ATRP)  ✅ PASS  ✅ PASS   ✅ PASS
          Sharpe (TRP)   ✅ PASS  ✅ PASS   ✅ PASS

=====================================================================================
📝 2. SURVIVAL AUDIT
   Survival Integrity: ✅ PASS (Engine: 924 vs Auditor: 924)

=====================================================================================
📝 3. UNIVERSAL SELECTION AUDIT | Strategy: Sharpe (ATRP)
   Scope: Evaluated 924 candidates (Full Universe).
   Result: 924 PASSED | 0 FAILED
   All scores match registry math. Sharpe (ATRP) results of the first 5 tickers

=====================================================================================

In [48]:
# Takes 4 seconds to run, checks selected tickers from analyzer1
SA.audit_feature_engineering_integrity(my_analyzer, mode="last_run")

===============================================================================================
🕵️  NUCLEAR FEATURE AUDIT | Mode: LAST_RUN | Tickers: 10
===============================================================================================
STEP 1: BOUNDARY INTEGRITY   | MultiIndex Isolation Check | ✅ PASS
STEP 2: SHADOW CALCULATIONS  | Re-computing metrics... DONE (0.45s)

Metric               | Max Delta    | Correlation  | Status
-------------------------------------------------------------------------------------
Ret_1d               |   0.0000e+00 |     1.000000 | ✅ PASS
ATR                  |   0.0000e+00 |     1.000000 | ✅ PASS
ATRP                 |   0.0000e+00 |     1.000000 | ✅ PASS
TRP                  |   0.0000e+00 |     1.000000 | ✅ PASS
RSI                  |   0.0000e+00 |     1.000000 | ✅ PASS
Mom_21               |   0.0000e+00 |     1.000000 | ✅ PASS
Consistency          |   0.0000e+00 |     1.000000 | ✅ PASS
DD_21                |   0.0000e+00 |     1.000000 | ✅ PASS
RollingStalePct      |   0.0000e+00 |     1.000000 | ✅ PASS
RollMedDollarVol     |   0.0000e+00 |     1.000000 | ✅ PASS
RollingSameVolCount  |   0.0000e+00 |     1.000000 | ✅ PASS
Macro_Vix_Signals    | N/A          | N/A          | ✅ LIVE
===============================================================================================

### Audit Every Tickers in features_df, Takes 3 minutes

In [ ]:
# # Takes 3 minutes to run, checks every tickers ~1580 tickers
# SA.audit_feature_engineering_integrity(my_analyzer, mode="system")

===============================================================================================
🕵️  NUCLEAR FEATURE AUDIT | Mode: SYSTEM | Tickers: 1582
===============================================================================================
STEP 1: BOUNDARY INTEGRITY   | MultiIndex Isolation Check | ✅ PASS
STEP 2: SHADOW CALCULATIONS  | Re-computing metrics... DONE (72.76s)

Metric               | Max Delta    | Correlation  | Status
-------------------------------------------------------------------------------------
Ret_1d               |   0.0000e+00 |     1.000000 | ✅ PASS
ATR                  |   0.0000e+00 |     1.000000 | ✅ PASS
ATRP                 |   0.0000e+00 |          nan | ✅ PASS
TRP                  |   0.0000e+00 |          nan | ✅ PASS
RSI                  |   0.0000e+00 |     1.000000 | ✅ PASS
Mom_21               |   0.0000e+00 |          nan | ✅ PASS
Consistency          |   0.0000e+00 |     1.000000 | ✅ PASS
DD_21                |   0.0000e+00 |     1.000000 | ✅ PASS
RollingStalePct      |   0.0000e+00 |     1.000000 | ✅ PASS
RollMedDollarVol     |   0.0000e+00 |     1.000000 | ✅ PASS
RollingSameVolCount  |   0.0000e+00 |     1.000000 | ✅ PASS
Macro_Vix_Signals    | N/A          | N/A          | ✅ LIVE
===============================================================================================

### Export Ticker's OHLCV and Features

In [56]:
f_name_excel = OUTPUT_DIR / "Audit_Verification_Report.xlsx"

SU.export_audit_to_excel(audit_pack=my_analyzer.last_run, filename=f_name_excel)

📂 [EXCEL AUDIT] Building full transparency report: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\Audit_Verification_Report.xlsx
✨ Audit Report Complete: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\Audit_Verification_Report.xlsx

WindowsPath('C:/Users/ping/Files_win10/python/py311/stocks/notebooks_RLVR/output/Audit_Verification_Report.xlsx')

In [57]:
f_name_csv = OUTPUT_DIR / "all_tickers_data_stacked.csv"

# Single call replaces your 3 cells
file_path = SU.export_last_run_tickers_data_to_csv(
    analyzer=my_analyzer,
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    filename=f_name_csv,
)

Creating combined dictionary for 11 ticker(s)
Date range: 2024-12-02 00:00:00 to 2025-01-13 00:00:00
============================================================
Data retrieved for 11 ticker(s) from 2024-12-02 00:00:00 to 2025-01-13 00:00:00
Total rows: 308
Date range in data: 2024-12-02 00:00:00 to 2025-01-13 00:00:00
  BIL: 28 rows
  SGOV: 28 rows
  SHV: 28 rows
  USFR: 28 rows
  TFLO: 28 rows
  MINT: 28 rows
  PULS: 28 rows
  AVGO: 28 rows
  TEVA: 28 rows
  JAAA: 28 rows
  SPY: 28 rows
Features data retrieved for 11 ticker(s) from 2024-12-02 00:00:00 to 2025-01-13 00:00:00
Total rows: 308
Date range in data: 2024-12-02 00:00:00 to 2025-01-13 00:00:00
Available features: ATR, ATRP, TRP, RSI, Mom_21, Consistency, IR_63, Beta_63, DD_21, Ret_1d, RollingStalePct, RollMedDollarVol, RollingSameVolCount
  BIL: 28 rows
  SGOV: 28 rows
  SHV: 28 rows
  USFR: 28 rows
  TFLO: 28 rows
  MINT: 28 rows
  PULS: 28 rows
  AVGO: 28 rows
  TEVA: 28 rows
  JAAA: 28 rows
  SPY: 28 rows

Processing BIL...
  ✓ Successfully combined data
  OHLCV shape: (28, 5)
  Features shape: (28, 13)
  Combined shape: (28, 18)
  Date range: 2024-12-02 00:00:00 to 2025-01-13 00:00:00

Processing SGOV...
  ✓ Successfully combined data
  OHLCV shape: (28, 5)
  Features shape: (28, 13)
  Combined shape: (28, 18)
  Date range: 2024-12-02 00:00:00 to 2025-01-13 00:00:00

Processing SHV...
  ✓ Successfully combined data
  OHLCV shape: (28, 5)
  Features shape: (28, 13)
  Combined shape: (28, 18)
  Date range: 2024-12-02 00:00:00 to 2025-01-13 00:00:00

Processing USFR...
  ✓ Successfully combined data
  OHLCV shape: (28, 5)
  Features shape: (28, 13)
  Combined shape: (28, 18)
  Date range: 2024-12-02 00:00:00 to 2025-01-13 00:00:00

Processing TFLO...
  ✓ Successfully combined data
  OHLCV shape: (28, 5)
  Features shape: (28, 13)
  Combined shape: (28, 18)
  Date range: 2024-12-02 00:00:00 to 2025-01-13 00:00:00

Processing MINT...
  ✓ Successfully combined data
  OHLCV shape: (28, 5)
  Features shape: (28, 13)
  Combined shape: (28, 18)
  Date range: 2024-12-02 00:00:00 to 2025-01-13 00:00:00

Processing PULS...
  ✓ Successfully combined data
  OHLCV shape: (28, 5)
  Features shape: (28, 13)
  Combined shape: (28, 18)
  Date range: 2024-12-02 00:00:00 to 2025-01-13 00:00:00

Processing AVGO...
  ✓ Successfully combined data
  OHLCV shape: (28, 5)
  Features shape: (28, 13)
  Combined shape: (28, 18)
  Date range: 2024-12-02 00:00:00 to 2025-01-13 00:00:00

Processing TEVA...
  ✓ Successfully combined data
  OHLCV shape: (28, 5)
  Features shape: (28, 13)
  Combined shape: (28, 18)
  Date range: 2024-12-02 00:00:00 to 2025-01-13 00:00:00

Processing JAAA...
  ✓ Successfully combined data
  OHLCV shape: (28, 5)
  Features shape: (28, 13)
  Combined shape: (28, 18)
  Date range: 2024-12-02 00:00:00 to 2025-01-13 00:00:00

Processing SPY...
  ✓ Successfully combined data
  OHLCV shape: (28, 5)
  Features shape: (28, 13)
  Combined shape: (28, 18)
  Date range: 2024-12-02 00:00:00 to 2025-01-13 00:00:00

============================================================
SUMMARY
============================================================
Total tickers processed: 11
Tickers with combined data: 11

Ticker details:
  BIL: (28, 18) - 2024-12-02 00:00:00 to 2025-01-13 00:00:00
    Columns: 18
  SGOV: (28, 18) - 2024-12-02 00:00:00 to 2025-01-13 00:00:00
    Columns: 18
  SHV: (28, 18) - 2024-12-02 00:00:00 to 2025-01-13 00:00:00
    Columns: 18
  USFR: (28, 18) - 2024-12-02 00:00:00 to 2025-01-13 00:00:00
    Columns: 18
  TFLO: (28, 18) - 2024-12-02 00:00:00 to 2025-01-13 00:00:00
    Columns: 18
  MINT: (28, 18) - 2024-12-02 00:00:00 to 2025-01-13 00:00:00
    Columns: 18
  PULS: (28, 18) - 2024-12-02 00:00:00 to 2025-01-13 00:00:00
    Columns: 18
  AVGO: (28, 18) - 2024-12-02 00:00:00 to 2025-01-13 00:00:00
    Columns: 18
  TEVA: (28, 18) - 2024-12-02 00:00:00 to 2025-01-13 00:00:00
    Columns: 18
  JAAA: (28, 18) - 2024-12-02 00:00:00 to 2025-01-13 00:00:00
    Columns: 18
  SPY: (28, 18) - 2024-12-02 00:00:00 to 2025-01-13 00:00:00
    Columns: 18
BIL:
              Adj Open    Adj High     Adj Low   Adj Close    Volume        ATR       ATRP        TRP         RSI     Mom_21  Consistency       IR_63     Beta_63      DD_21     Ret_1d  RollingStalePct   RollMedDollarVol  RollingSameVolCount
Date
2024-12-02 86.92040000 86.92040000 86.91090000 86.92040000  13652981 0.02154013 0.00024781 0.00027266 98.25138690 0.00398149   0.80000000 -0.18137394 -0.00457511 0.00000000 0.00027274       0.00000000 553933185.61520004           0.00000000
2024-12-03 86.92990000 86.93940000 86.92990000 86.93940000   5970462 0.02135869 0.00024567 0.00021854 98.39075293 0.00377312   0.80000000 -0.18699034 -0.00468944 0.00000000 0.00021859       0.00000000 553084743.45235014           0.00000000
2024-12-04 86.95840000 86.95840000 86.94890000 86.94890000   6275537 0.02119021 0.00024371 0.00021852 98.45697326 0.00366379   1.00000000 -0.20587524 -0.00489618 0.00000000 0.00010927       0.00000000 552412975.71105003           0.00000000
2024-12-05 86.96790000 86.96790000 86.95840000 86.95840000   6187982 0.02103377 0.00024188 0.00021850 98.52245121 0.00377345   1.00000000 -0.25459236 -0.00301415 0.00000000 0.00010926       0.00000000 551265572.37450004           0.00000000
2024-12-06 86.99640000 86.99640000 86.98690000 86.99640000   6005295 0.02224564 0.00025571 0.00043680 98.75079983 0.00399190   1.00000000 -0.23561562 -0.00247717 0.00000000 0.00043699       0.00000000 550062508.86380005           0.00000000
2024-12-09 87.00590000 87.01540000 87.00590000 87.00590000   9253349 0.02201381 0.00025302 0.00021838 98.80070077 0.00399146   1.00000000 -0.21205271 -0.00238890 0.00000000 0.00010920       0.00000000 550062508.86380005           0.00000000
2024-12-10 87.01540000 87.02490000 87.01540000 87.02490000   5682963 0.02179854 0.00025049 0.00021833 98.89571177 0.00366290   1.00000000 -0.18190287 -0.00189561 0.00000000 0.00021838       0.00000000 550062508.86380005           0.00000000
2024-12-11 87.02490000 87.03440000 87.02490000 87.03440000   6151887 0.02092007 0.00024037 0.00010915 98.94089129 0.00388245   1.00000000 -0.18055927 -0.00188238 0.00000000 0.00010916       0.00000000 550062508.86380005           0.00000000
2024-12-12 87.04390000 87.05350000 87.04390000 87.05350000   5019881 0.02079007 0.00023882 0.00021941 99.02707641 0.00399274   1.00000000 -0.15572804 -0.00245774 0.00000000 0.00021945       0.00000000 547875718.45525002           0.00000000
2024-12-13 87.08190000 87.08190000 87.07240000 87.08190000   6600186 0.02133363 0.00024498 0.00032613 99.13923807 0.00410141   1.00000000 -0.15142698 -0.00253214 0.00000000 0.00032624       0.00000000 547875718.45525002           0.00000000
2024-12-16 87.09140000 87.09140000 87.08190000 87.09140000   7115622 0.02048837 0.00023525 0.00010908 99.17355965 0.00421095   1.00000000 -0.16032741 -0.00262959 0.00000000 0.00010909       0.00000000 547875718.45525002           0.00000000
2024-12-17 87.10090000 87.10090000 87.09140000 87.10090000   6132419 0.01970349 0.00022621 0.00010907 99.20758642 0.00399172   1.00000000 -0.15757142 -0.00242216 0.00000000 0.00010908       0.00000000 545942581.78839993           0.00000000
2024-12-18 87.10090000 87.11040000 87.10090000 87.10090000   9753318 0.01897467 0.00021785 0.00010907 99.20758642 0.00388179   0.80000000 -0.04238996 -0.00051332 0.00000000 0.00000000       0.00000000 545942581.78839993           0.00000000
2024-12-19 87.12290000 87.12290000 87.11330000 87.11330000  14541706 0.01919076 0.00022030 0.00025254 99.25407757 0.00369617   0.80000000 -0.04607747 -0.00033747 0.00000000 0.00014236       0.00000000 545942581.78839993           0.00000000
2024-12-20 87.14200000 87.15150000 87.14200000 87.15150000  13298421 0.02054857 0.00023578 0.00043832 99.37561200 0.00402640   0.80000000 -0.06449179  0.00054472 0.00000000 0.00043851       0.00000000 545942581.78839993           0.00000000
2024-12-23 87.15150000 87.16110000 87.15150000 87.15150000   6887932 0.01976653 0.00022681 0.00011015 99.37561200 0.00391769   0.60000000 -0.07100319  0.00032080 0.00000000 0.00000000       0.00000000 547875718.45525002           0.00000000
2024-12-24 87.17060000 87.18020000 87.17060000 87.17060000   4344360 0.02040463 0.00023408 0.00032924 99.42951232 0.00380931   0.60000000 -0.09746776  0.00045921 0.00000000 0.00021916       0.00000000 545942581.78839993           0.00000000
2024-12-26 87.18970000 87.18970000 87.18010000 87.18970000   6488875 0.02031144 0.00023296 0.00021906 99.47803684 0.00391943   0.80000000 -0.08911885  0.00060095 0.00000000 0.00021911       0.00000000 547875718.45525002           0.00000000
2024-12-27 87.22790000 87.22790000 87.21830000 87.22790000   6438049 0.02158920 0.00024750 0.00043793 99.55885533 0.00435928   0.80000000 -0.06901481 -0.00009244 0.00000000 0.00043813       0.00000000 550062508.86380005           0.00000000
2024-12-30 87.22790000 87.23740000 87.22790000 87.22790000   9421129 0.02072568 0.00023760 0.00010891 99.55885533 0.00403095   0.60000000 -0.03740588  0.00053032 0.00000000 0.00000000       0.00000000 551265572.37450004           0.00000000
2024-12-31 87.25650000 87.25650000 87.24690000 87.24690000   7651570 0.02128813 0.00024400 0.00032781 99.59502608 0.00403007   0.80000000 -0.04846969  0.00061885 0.00000000 0.00021782       0.00000000 552412975.71105003           0.00000000
2025-01-02 87.26600000 87.26600000 87.25650000 87.26600000  11272640 0.02113184 0.00024215 0.00021887 99.62804280 0.00397605   0.80000000 -0.04241723  0.00058695 0.00000000 0.00021892       0.00000000 552412975.71105003           0.00000000
2025-01-03 87.29470000 87.29470000 87.27560000 87.27560000   8213688 0.02167242 0.00024832 0.00032884 99.64376336 0.00386706   0.80000000 -0.07017492  0.00037502 0.00000000 0.00011001       0.00000000 552412975.71105003           0.00000000
2025-01-06 87.28510000 87.29470000 87.28510000 87.28510000   8202370 0.02148868 0.00024619 0.00021882 99.65911721 0.00386664   0.80000000 -0.06417765  0.00020715 0.00000000 0.00010885       0.00000000 553084743.45235014           0.00000000
2025-01-07 87.30420000 87.31370000 87.29470000 87.30420000   7290344 0.02199663 0.00025195 0.00032759 99.68821305 0.00397661   1.00000000 -0.05931918  0.00018027 0.00000000 0.00021882       0.00000000 553933185.61520004           0.00000000
2025-01-08 87.32330000 87.32330000 87.31370000 87.32330000   6993042 0.02178973 0.00024953 0.00021873 99.71445993 0.00375763   1.00000000 -0.04356528  0.00060023 0.00000000 0.00021878       0.00000000 554770033.41719997           0.00000000
2025-01-10 87.36150000 87.36150000 87.35190000 87.35190000  10597029 0.02296189 0.00026287 0.00043731 99.74858878 0.00397674   1.00000000  0.00104364  0.00015257 0.00000000 0.00032752       0.00000000 555419629.34675002           0.00000000
2025-01-13 87.36150000 87.37100000 87.36150000 87.36150000   8230978 0.02268604 0.00025968 0.00021863 99.75900138 0.00386786   1.00000000 -0.00536591  0.00009090 0.00000000 0.00010990       0.00000000 555419629.34675002           0.00000000

SGOV:
              Adj Open    Adj High     Adj Low   Adj Close    Volume        ATR       ATRP        TRP         RSI     Mom_21  Consistency       IR_63     Beta_63      DD_21     Ret_1d  RollingStalePct   RollMedDollarVol  RollingSameVolCount
Date
2024-12-02 95.39120000 95.39590000 95.38640000 95.38640000  12065143 0.02525260 0.00026474 0.00027887 98.71663710 0.00411810   1.00000000 -0.18116354 -0.00282011 0.00000000 0.00017930       0.00000000 376061931.32630002           0.00000000
2024-12-03 95.40550000 95.40550000 95.39600000 95.39600000   6030677 0.02481313 0.00026011 0.00020022 98.76530332 0.00366976   1.00000000 -0.18703406 -0.00290224 0.00000000 0.00010064       0.00000000 376061931.32630002           0.00000000
2024-12-04 95.41500000 95.42450000 95.40550000 95.41500000   5627868 0.02507648 0.00026281 0.00029870 98.85763488 0.00376933   1.00000000 -0.20624831 -0.00274371 0.00000000 0.00019917       0.00000000 376610065.40555000           0.00000000
2024-12-05 95.42450000 95.43400000 95.42450000 95.42450000   5121990 0.02464244 0.00025824 0.00019911 98.90185346 0.00366866   1.00000000 -0.25456164 -0.00156839 0.00000000 0.00009957       0.00000000 378204677.59254998           0.00000000
2024-12-06 95.47200000 95.47200000 95.46250000 95.47200000   5026178 0.02627513 0.00027521 0.00049753 99.09125974 0.00416826   1.00000000 -0.23557523 -0.00131501 0.00000000 0.00049778       0.00000000 379685406.32330000           0.00000000
2024-12-09 95.47200000 95.48150000 95.47200000 95.48150000   5826327 0.02507690 0.00026264 0.00009950 99.12380947 0.00406858   1.00000000 -0.21173604 -0.00108630 0.00000000 0.00009951       0.00000000 381344109.58790004           0.00000000
2024-12-10 95.49100000 95.50050000 95.49100000 95.50050000   5567289 0.02464284 0.00025804 0.00019895 99.18656407 0.00376805   1.00000000 -0.18160272 -0.00051564 0.00000000 0.00019899       0.00000000 383603300.41645002           0.00000000
2024-12-11 95.51000000 95.51000000 95.50050000 95.50050000   5106424 0.02356121 0.00024671 0.00009948 99.18656407 0.00386829   0.80000000 -0.18045312 -0.00072563 0.00000000 0.00000000       0.00000000 384820577.86745000           0.00000000
2024-12-12 95.51960000 95.51960000 95.51000000 95.51000000   4944144 0.02324255 0.00024335 0.00019998 99.21900079 0.00386790   0.80000000 -0.15603284 -0.00109956 0.00000000 0.00009948       0.00000000 385857257.56379998           0.00000000
2024-12-13 95.54810000 95.55760000 95.54810000 95.55760000   4913117 0.02498237 0.00026144 0.00049813 99.35729221 0.00406849   0.80000000 -0.15125839 -0.00126060 0.00000000 0.00049838       0.00000000 385857257.56379998           0.00000000
2024-12-16 95.56710000 95.56710000 95.55760000 95.56710000   5888486 0.02387648 0.00024984 0.00009941 99.38085560 0.00416831   0.80000000 -0.15992656 -0.00140936 0.00000000 0.00009942       0.00000000 385857257.56379998           0.00000000
2024-12-17 95.57660000 95.57660000 95.56710000 95.56710000   6098409 0.02284959 0.00023909 0.00009941 99.38085560 0.00366843   0.60000000 -0.15766813 -0.00087303 0.00000000 0.00000000       0.00000000 386764188.68299997           0.00000000
2024-12-18 95.58810000 95.58810000 95.57860000 95.58810000  12077802 0.02271748 0.00023766 0.00021969 99.43405018 0.00378988   0.80000000 -0.04173267 -0.00109081 0.00000000 0.00021974       0.00000000 386764188.68299997           0.00000000
2024-12-19 95.59760000 95.61190000 95.59760000 95.60720000   8717310 0.02279480 0.00023842 0.00024894 99.47798017 0.00389031   0.80000000 -0.04520883 -0.00095724 0.00000000 0.00019982       0.00000000 386764188.68299997           0.00000000
2024-12-20 95.63100000 95.63580000 95.62630000 95.62630000   9324527 0.02320946 0.00024271 0.00029908 99.51825084 0.00389058   0.80000000 -0.06446541 -0.00092361 0.00000000 0.00019978       0.00000000 386764188.68299997           0.00000000
2024-12-23 95.64540000 95.64540000 95.63580000 95.64540000   7368858 0.02291593 0.00023959 0.00019970 99.55520367 0.00409109   0.80000000 -0.07055561 -0.00084023 0.00000000 0.00019974       0.00000000 386764188.68299997           0.00000000
2024-12-24 95.67400000 95.67400000 95.66440000 95.67400000   4876911 0.02332193 0.00024376 0.00029893 99.60416552 0.00409197   1.00000000 -0.09638710 -0.00064642 0.00000000 0.00029902       0.00000000 387468066.76789999           0.00000000
2024-12-26 95.68350000 95.68350000 95.67400000 95.68350000   5212006 0.02233465 0.00023342 0.00009929 99.61916166 0.00409157   1.00000000 -0.08849217 -0.00055670 0.00000000 0.00009930       0.00000000 389350426.88450003           0.00000000
2024-12-27 95.70260000 95.71220000 95.70260000 95.71220000   6871664 0.02278932 0.00023810 0.00029986 99.66095149 0.00419357   1.00000000 -0.06887739 -0.00075502 0.00000000 0.00029995       0.00000000 391420800.85930002           0.00000000
2024-12-30 95.72170000 95.72170000 95.71220000 95.71220000   6860766 0.02184008 0.00022818 0.00009926 99.66095149 0.00399449   0.80000000 -0.03707917 -0.00000967 0.00000000 0.00000000       0.00000000 391893915.75125003           0.00000000
2024-12-31 95.75030000 95.75990000 95.74080000 95.74080000   7723864 0.02368722 0.00024741 0.00049822 99.69910999 0.00389538   0.80000000 -0.04832586  0.00039283 0.00000000 0.00029881       0.00000000 392485063.58144999           0.00000000
2025-01-02 95.75990000 95.75990000 95.75030000 95.75990000   7893403 0.02335956 0.00024394 0.00019946 99.72164129 0.00391565   0.80000000 -0.04209366  0.00037436 0.00000000 0.00019950       0.00000000 392485063.58144999           0.00000000
2025-01-03 95.79810000 95.79810000 95.78850000 95.78850000   7051995 0.02441959 0.00025493 0.00039880 99.75163229 0.00411443   0.80000000 -0.06927752  0.00063708 0.00000000 0.00029866       0.00000000 392485063.58144999           0.00000000
2025-01-06 95.79810000 95.80760000 95.78850000 95.78850000   7270153 0.02403962 0.00025097 0.00019940 99.75163229 0.00391448   0.60000000 -0.06381492 -0.00004178 0.00000000 0.00000000       0.00000000 393459581.44939995           0.00000000
2025-01-07 95.81720000 95.81720000 95.80760000 95.80760000   7116959 0.02437250 0.00025439 0.00029956 99.77076205 0.00401469   0.80000000 -0.05875132 -0.00029234 0.00000000 0.00019940       0.00000000 394166852.80089998           0.00000000
2025-01-08 95.81710000 95.82670000 95.81710000 95.82670000   6392910 0.02399590 0.00025041 0.00019932 99.78832018 0.00371523   0.80000000 -0.04322752 -0.00010466 0.00000000 0.00019936       0.00000000 394716443.50629997           0.00000000
2025-01-10 95.86490000 95.87440000 95.85530000 95.86490000   8010235 0.02568905 0.00026797 0.00049758 99.81829600 0.00401544   0.80000000  0.00130795 -0.00091427 0.00000000 0.00039864       0.00000000 395032944.63890004           0.00000000
2025-01-13 95.87920000 95.88390000 95.87440000 95.88390000   8013064 0.02521126 0.00026294 0.00019816 99.83110687 0.00401464   0.80000000 -0.00509955 -0.00090667 0.00000000 0.00019820       0.00000000 395179249.62049997           0.00000000

SHV:
               Adj Open     Adj High      Adj Low    Adj Close   Volume        ATR       ATRP        TRP         RSI     Mom_21  Consistency       IR_63     Beta_63      DD_21     Ret_1d  RollingStalePct   RollMedDollarVol  RollingSameVolCount
Date
2024-12-02 104.67800000 104.67800000 104.66800000 104.67800000  4386505 0.02699573 0.00025789 0.00014330 98.48419418 0.00384553   1.00000000 -0.18217138 -0.00096943 0.00000000 0.00014332       0.00000000 275454793.55849999           0.00000000
2024-12-03 104.69700000 104.70600000 104.68700000 104.70600000  1828929 0.02706746 0.00025851 0.00026742 98.63150650 0.00368091   1.00000000 -0.18809042 -0.00090424 0.00000000 0.00026749       0.00000000 273388152.13349998           0.00000000
2024-12-04 104.71600000 104.72500000 104.70600000 104.70600000  3901897 0.02649121 0.00025301 0.00018146 98.63150650 0.00349815   0.80000000 -0.20743846 -0.00116957 0.00000000 0.00000000       0.00000000 273388152.13349998           0.00000000
2024-12-05 104.73500000 104.73500000 104.72500000 104.73500000  2123459 0.02667041 0.00025465 0.00027689 98.77455952 0.00377608   0.80000000 -0.25568554  0.00036734 0.00000000 0.00027697       0.00000000 269857570.95599997           0.00000000
2024-12-06 104.77300000 104.78200000 104.77300000 104.78200000  2476159 0.02812253 0.00026839 0.00044855 98.96364103 0.00422653   0.80000000 -0.23664597  0.00100689 0.00000000 0.00044875       0.00000000 267731259.88499999           0.00000000
2024-12-09 104.79200000 104.80100000 104.78200000 104.80100000  2700529 0.02747092 0.00026212 0.00018130 99.02887480 0.00413916   0.80000000 -0.21286595  0.00082786 0.00000000 0.00018133       0.00000000 269857570.95599997           0.00000000

In [58]:
SU.create_combined_dict(
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    tickers=my_analyzer.last_run.tickers,
    date_start=my_analyzer.last_run.start_date,
    date_end=analyzer1.last_run.holding_end_date,
    verbose=False,
)

{'BIL':             Adj Open  Adj High  Adj Low  Adj Close    Volume     ATR    ATRP     TRP      RSI  Mom_21  Consistency   IR_63     Beta_63  DD_21  Ret_1d  RollingStalePct  RollMedDollarVol  RollingSameVolCount
 Date
 2024-12-02   86.9204   86.9204  86.9109    86.9204  13652981  0.0215  0.0002  0.0003  98.2514  0.0040          0.8 -0.1814 -4.5751e-03    0.0  0.0003              0.0        5.5393e+08                  0.0
 2024-12-03   86.9299   86.9394  86.9299    86.9394   5970462  0.0214  0.0002  0.0002  98.3908  0.0038          0.8 -0.1870 -4.6894e-03    0.0  0.0002              0.0        5.5308e+08                  0.0
 2024-12-04   86.9584   86.9584  86.9489    86.9489   6275537  0.0212  0.0002  0.0002  98.4570  0.0037          1.0 -0.2059 -4.8962e-03    0.0  0.0001              0.0        5.5241e+08                  0.0
 2024-12-05   86.9679   86.9679  86.9584    86.9584   6187982  0.0210  0.0002  0.0002  98.5225  0.0038          1.0 -0.2546 -3.0141e-03    0.0  0.0001              0.0        5.5127e+08                  0.0
 2024-12-06   86.9964   86.9964  86.9869    86.9964   6005295  0.0222  0.0003  0.0004  98.7508  0.0040          1.0 -0.2356 -2.4772e-03    0.0  0.0004              0.0        5.5006e+08                  0.0
 2024-12-09   87.0059   87.0154  87.0059    87.0059   9253349  0.0220  0.0003  0.0002  98.8007  0.0040          1.0 -0.2121 -2.3889e-03    0.0  0.0001              0.0        5.5006e+08                  0.0
 2024-12-10   87.0154   87.0249  87.0154    87.0249   5682963  0.0218  0.0003  0.0002  98.8957  0.0037          1.0 -0.1819 -1.8956e-03    0.0  0.0002              0.0        5.5006e+08                  0.0
 2024-12-11   87.0249   87.0344  87.0249    87.0344   6151887  0.0209  0.0002  0.0001  98.9409  0.0039          1.0 -0.1806 -1.8824e-03    0.0  0.0001              0.0        5.5006e+08                  0.0
 2024-12-12   87.0439   87.0535  87.0439    87.0535   5019881  0.0208  0.0002  0.0002  99.0271  0.0040          1.0 -0.1557 -2.4577e-03    0.0  0.0002              0.0        5.4788e+08                  0.0
 2024-12-13   87.0819   87.0819  87.0724    87.0819   6600186  0.0213  0.0002  0.0003  99.1392  0.0041          1.0 -0.1514 -2.5321e-03    0.0  0.0003              0.0        5.4788e+08                  0.0
 2024-12-16   87.0914   87.0914  87.0819    87.0914   7115622  0.0205  0.0002  0.0001  99.1736  0.0042          1.0 -0.1603 -2.6296e-03    0.0  0.0001              0.0        5.4788e+08                  0.0
 2024-12-17   87.1009   87.1009  87.0914    87.1009   6132419  0.0197  0.0002  0.0001  99.2076  0.0040          1.0 -0.1576 -2.4222e-03    0.0  0.0001              0.0        5.4594e+08                  0.0
 2024-12-18   87.1009   87.1104  87.1009    87.1009   9753318  0.0190  0.0002  0.0001  99.2076  0.0039          0.8 -0.0424 -5.1332e-04    0.0  0.0000              0.0        5.4594e+08                  0.0
 2024-12-19   87.1229   87.1229  87.1133    87.1133  14541706  0.0192  0.0002  0.0003  99.2541  0.0037          0.8 -0.0461 -3.3747e-04    0.0  0.0001              0.0        5.4594e+08                  0.0
 2024-12-20   87.1420   87.1515  87.1420    87.1515  13298421  0.0205  0.0002  0.0004  99.3756  0.0040          0.8 -0.0645  5.4472e-04    0.0  0.0004              0.0        5.4594e+08                  0.0
 2024-12-23   87.1515   87.1611  87.1515    87.1515   6887932  0.0198  0.0002  0.0001  99.3756  0.0039          0.6 -0.0710  3.2080e-04    0.0  0.0000              0.0        5.4788e+08                  0.0
 2024-12-24   87.1706   87.1802  87.1706    87.1706   4344360  0.0204  0.0002  0.0003  99.4295  0.0038          0.6 -0.0975  4.5921e-04    0.0  0.0002              0.0        5.4594e+08                  0.0
 2024-12-26   87.1897   87.1897  87.1801    87.1897   6488875  0.0203  0.0002  0.0002  99.4780  0.0039          0.8 -0.0891  6.0095e-04    0.0  0.0002              0.0        5.4788e+08                  0.0
 2024-12-27   87.2279   87.2279  87.2183    87.2279   6438049  0.0216  0.0002  0.0004  99.5589  0.0044          0.8 -0.0690 -9.2440e-05    0.0  0.0004              0.0        5.5006e+08                  0.0
 2024-12-30   87.2279   87.2374  87.2279    87.2279   9421129  0.0207  0.0002  0.0001  99.5589  0.0040          0.6 -0.0374  5.3032e-04    0.0  0.0000              0.0        5.5127e+08                  0.0
 2024-12-31   87.2565   87.2565  87.2469    87.2469   7651570  0.0213  0.0002  0.0003  99.5950  0.0040          0.8 -0.0485  6.1885e-04    0.0  0.0002              0.0        5.5241e+08                  0.0
 2025-01-02   87.2660   87.2660  87.2565    87.2660  11272640  0.0211  0.0002  0.0002  99.6280  0.0040          0.8 -0.0424  5.8695e-04    0.0  0.0002              0.0        5.5241e+08                  0.0
 2025-01-03   87.2947   87.2947  87.2756    87.2756   8213688  0.0217  0.0002  0.0003  99.6438  0.0039          0.8 -0.0702  3.7502e-04    0.0  0.0001              0.0        5.5241e+08                  0.0
 2025-01-06   87.2851   87.2947  87.2851    87.2851   8202370  0.0215  0.0002  0.0002  99.6591  0.0039          0.8 -0.0642  2.0715e-04    0.0  0.0001              0.0        5.5308e+08                  0.0
 2025-01-07   87.3042   87.3137  87.2947    87.3042   7290344  0.0220  0.0003  0.0003  99.6882  0.0040          1.0 -0.0593  1.8027e-04    0.0  0.0002              0.0        5.5393e+08                  0.0
 2025-01-08   87.3233   87.3233  87.3137    87.3233   6993042  0.0218  0.0002  0.0002  99.7145  0.0038          1.0 -0.0436  6.0023e-04    0.0  0.0002              0.0        5.5477e+08                  0.0
 2025-01-10   87.3615   87.3615  87.3519    87.3519  10597029  0.0230  0.0003  0.0004  99.7486  0.0040          1.0  0.0010  1.5257e-04    0.0  0.0003              0.0        5.5542e+08                  0.0
 2025-01-13   87.3615   87.3710  87.3615    87.3615   8230978  0.0227  0.0003  0.0002  99.7590  0.0039          1.0 -0.0054  9.0904e-05    0.0  0.0001              0.0        5.5542e+08                  0.0,
 'SGOV':             Adj Open  Adj High  Adj Low  Adj Close    Volume     ATR    ATRP         TRP      RSI  Mom_21  Consistency   IR_63     Beta_63  DD_21      Ret_1d  RollingStalePct  RollMedDollarVol  RollingSameVolCount
 Date
 2024-12-02   95.3912   95.3959  95.3864    95.3864  12065143  0.0253  0.0003  2.7887e-04  98.7166  0.0041          1.0 -0.1812 -2.8201e-03    0.0  1.7930e-04              0.0        3.7606e+08                  0.0
 2024-12-03   95.4055   95.4055  95.3960    95.3960   6030677  0.0248  0.0003  2.0022e-04  98.7653  0.0037          1.0 -0.1870 -2.9022e-03    0.0  1.0064e-04              0.0        3.7606e+08                  0.0
 2024-12-04   95.4150   95.4245  95.4055    95.4150   5627868  0.0251  0.0003  2.9870e-04  98.8576  0.0038          1.0 -0.2062 -2.7437e-03    0.0  1.9917e-04              0.0        3.7661e+08                  0.0
 2024-12-05   95.4245   95.4340  95.4245    95.4245   5121990  0.0246  0.0003  1.9911e-04  98.9019  0.0037          1.0 -0.2546 -1.5684e-03    0.0  9.9565e-05              0.0        3.7820e+08                  0.0
 2024-12-06   95.4720   95.4720  95.4625    95.4720   5026178  0.0263  0.0003  4.9753e-04  99.0913  0.0042          1.0 -0.2356 -1.3150e-03    0.0  4.9778e-04              0.0        3.7969e+08                  0.0
 2024-12-09   95.4720   95.4815  95.4720    95.4815   5826327  0.0251  0.0003  9.9496e-05  99.1238  0.0041          1.0 -0.2117 -1.0863e-03    0.0  9.9506e-05              0.0        3.8134e+08                  0.0
 2024-12-10   95.4910   95.5005  95.4910    95.5005   5567289  0.0246  0.0003  1.9895e-04  99.1866  0.0038          1.0 -0.1816 -5.1564e-04    0.0  1.9899e-04              0.0        3.8360e+08                  0.0
 2024-12-11   95.5100   95.5100  95.5005    95.5005   5106424  0.0236  0.0002  9.9476e-05  99.1866  0.0039          0.8 -0.1805 -7.2563e-04    0.0  0.0000e+00              0.0        3.8482e+08                  0.0
 2024-12-12   95.5196   95.5196  95.5100    95.5100   4944144  0.0232  0.0002  1.9998e-04  99.2190  0.0039          0.8 -0.1560 -1.0996e-03    0.0  9.9476e-05              0.0        3.8586e+08                  0.0
 2024-12-13   95.5481   95.5576  95.5481    95.5576   4913117  0.0250  0.0003  4.9813e-04  99.3573  0.0041          0.8 -0.1513 -1.2606e-03    0.0  4.9838e-04              0.0        3.8586e+08                  0.0
 2024-12-16   95.5671   95.5671  95.5576    95.5671   5888486  0.0239  0.0002  9.9407e-05  99.3809  0.0042          0.8 -0.1599 -1.4094e-03    0.0  9.9416e-05              0.0        3.8586e+08                  0.0
 2024-12-17   95.5766   95.5766  95.5671    95.5671   6098409  0.0228  0.0002  9.9407e-05  99.3809  0.0037          0.6 -0.1577 -8.7303e-04    0.0  0.0000e+00              0.0        3.8676e+08                  0.0
 2024-12-18   95.5881   95.5881  95.5786    95.5881  12077802  0.0227  0.0002  2.1969e-04  99.4341  0.0038          0.8 -0.0417 -1.0908e-03    0.0  2.1974e-04              0.0        3.8676e+08                  0.0
 2024-12-19   95.5976   95.6119  95.5976    95.6072   8717310  0.0228  0.0002  2.4894e-04  99.4780  0.0039          0.8 -0.0452 -9.5724e-04    0.0  1.9982e-04              0.0        3.8676e+08                  0.0
 2024-12-20   95.6310   95.6358  95.6263    95.6263   9324527  0.0232  0.0002  2.9908e-04  99.5183  0.0039          0.8 -0.0645 -9.2361e-04    0.0  1.9978e-04              0.0        3.8676e+08                  0.0
 2024-12-23   95.6454   95.6454  95.6358    95.6454   7368858  0.0229  0.0002  1.9970e-04  99.5552  0.0041          0.8 -0.0706 -8.4023e-04    0.0  1.9974e-04              0.0        3.8676e+08                  0.0
 2024-12-24   95.6740   95.6740  95.6644    95.6740   4876911  0.0233  0.0002  2.9893e-04  99.6042  0.0041          1.0 -0.0964 -6.4642e-04    0.0  2.9902e-04              0.0        3.8747e+08                  0.0
 2024-12-26   95.6835   95.6835  95.6740    95.6835   5212006  0.0223  0.0002  9.9286e-05  99.6192  0.0041          1.0 -0.0885 -5.5670e-04    0.0  9.9296e-05              0.0        3.8935e+08                  0.0
 2024-12-27   95.7026   95.7122  95.7026    95.7122   6871664  0.0228  0.0002  2.9986e-04  99.6610  0.0042          1.0 -0.0689 -7.5502e-04    0.0  2.9995e-04              0.0        3.9142e+08                  0.0
 2024-12-30   95.7217   95.7217  95.7122    95.7122   6860766  0.0218  0.0002  9.9256e-05  99.6610  0.0040          0.8 -0.0371 -9.6741e-06    0.0  0.0000e+00              0.0        3.9189e+08                  0.0
 2024-12-31   95.7503   95.7599  95.7408    95.7408   7723864  0.0237  0.0002  4.9822e-04  99.6991  0.0039          0.8 -0.0483  3.9283e-04    0.0  2.9881e-04              0.0        3.9249e+08                  0.0
 2025-01-02   95.7599   95.7599  95.7503    95.7599   7893403  0.0234  0.0002  1.9946e-04  99.7216  0.0039          0.8 -0.0421  3.7436e-04    0.0  1.9950e-04              0.0        3.9249e+08                  0.0
 2025-01-03   95.7981   95.7981  95.7885    95.7885   7051995  0.0244  0.0003  3.9880e-04  99.7516  0.0041          0.8 -0.0693  6.3708e-04    0.0  2.9866e-04              0.0        3.9249e+08                  0.0
 2025-01-06   95.7981   95.8076  95.7885    95.7885   7270153  0.0240  0.0003  1.9940e-04  99.7516  0.0039          0.6 -0.0638 -4.1778e-05    0.0  0.0000e+00              0.0        3.9346e+08                  0.0
 2025-01-07   95.8172   95.8172  95.8076    95.8076   7116959  0.0244  0.0003  2.9956e-04  99.7708  0.0040          0.8 -0.0588 -2.9234e-04    0.0  1.9940e-04              0.0        3.9417e+08                  0.0
 2025-01-08   95.8171   95.8267  95.8171    95.8267   6392910  0.0240  0.0003  1.9932e-04  99.7883  0.0037          0.8 -0.0432 -1.0466e-04    0.0  1.9936e-04              0.0        3.9472e+08                  0.0
 2025-01-10   95.8649   95.8744  95.8553    95.8649   8010235  0.0257  0.0003  4.9758e-04  99.8183  0.0040          0.8  0.0013 -9.1427e-04    0.0  3.9864e-04              0.0        3.9503e+08                  0.0
 2025-01-13   95.8792   95.8839  95.8744    95.8839   8013064  0.0252  0.0003  1.9816e-04  99.8311  0.0040          0.8 -0.0051 -9.0667e-04    0.0  1.9820e-04              0.0        3.9518e+08                  0.0,
 'SHV':             Adj Open  Adj High  Adj Low  Adj Close   Volume     ATR    ATRP         TRP      RSI  Mom_21  Consistency   IR_63  Beta_63  DD_21      Ret_1d  RollingStalePct  RollMedDollarVol  RollingSameVolCount
 Date
 2024-12-02   104.678   104.678  104.668    104.678  4386505  0.0270  0.0003  1.4330e-04  98.4842  0.0038          1.0 -0.1822  -0.0010    0.0  1.4332e-04              0.0        2.7545e+08                  0.0
 2024-12-03   104.697   104.706  104.687    104.706  1828929  0.0271  0.0003  2.6742e-04  98.6315  0.0037          1.0 -0.1881  -0.0009    0.0  2.6749e-04              0.0        2.7339e+08                  0.0
 2024-12-04   104.716   104.725  104.706    104.706  3901897  0.0265  0.0003  1.8146e-04  98.6315  0.0035          0.8 -0.2074  -0.0012    0.0  0.0000e+00              0.0        2.7339e+08                  0.0
 2024-12-05   104.735   104.735  104.725    104.735  2123459  0.0267  0.0003  2.7689e-04  98.7746  0.0038          0.8 -0.2557   0.0004    0.0  2.7697e-04              0.0        2.6986e+08                  0.0
 2024-12-06   104.773   104.782  104.773    104.782  2476159  0.0281  0.0003  4.4855e-04  98.9636  0.0042          0.8 -0.2366   0.0010    0.0  4.4875e-04              0.0        2.6773e+08                  0.0
 2024-12-09   104.792   104.801  104.782    104.801  2700529  0.0275  0.0003  1.8130e-04  99.0289  0.0041          0.8 -0.2129   0.0008    0.0  1.8133e-04              0.0        2.6986e+08                  0.0
 2024-12-10   104.811   104.811  104.801    104.801  1722267  0.0262  0.0003  9.5419e-05  99.0289  0.0036          0.6 -0.1830   0.0021    0.0  0.0000e+00              0.0        2.6986e+08                  0.0
 2024-12-11   104.820   104.830  104.811    104.820  2352983  0.0264  0.0003  2.7666e-04  99.0949  0.0039          0.8 -0.1817   0.0021    0.0  1.8130e-04              0.0        2.6986e+08                  0.0
 2024-12-12   104.830   104.839  104.830    104.830  1645899  0.0259  0.0002  1.8125e-04  99.1286  0.0039          0.8 -0.1571   0.0017    0.0  9.5402e-05              0.0        2.6986e+08                  0.0
 2024-12-13   104.877   104.877  104.858    104.858  1739097  0.0274  0.0003  4.4823e-04  99.2163  0.0040          0.8 -0.1533   0.0017    0.0  2.6710e-04              0.0        2.6986e+08                  0.0
 2024-12-16   104.877   104.887  104.877    104.887  2354666  0.0275  0.0003  2.7649e-04  99.2954  0.0041          0.8 -0.1618   0.0017    0.0  2.7656e-04              0.0        2.6773e+08                  0.0
 2024-12-17   104.906   104.906  104.887    104.887  2529070  0.0269  0.0003  1.8115e-04  99.2954  0.0040          0.8 -0.1597   0.0024    0.0  0.0000e+00              0.0        2.6699e+08                  0.0
 2024-12-18   104.894   104.913  104.894    104.903  3102605  0.0268  0.0003  2.4785e-04  99.3382  0.0039          0.8 -0.0433   0.0020    0.0  1.5255e-04              0.0        2.6773e+08                  0.0
 2024-12-19   104.922   104.932  104.913    104.932  3478669  0.0270  0.0003  2.7637e-04  99.4083  0.0040          0.8 -0.0468   0.0022    0.0  2.7645e-04              0.0        2.6773e+08                  0.0
 2024-12-20   104.970   104.970  104.951    104.960  2720254  0.0278  0.0003  3.6204e-04  99.4670  0.0041          0.8 -0.0657   0.0024    0.0  2.6684e-04              0.0        2.6773e+08                  0.0
 2024-12-23   104.980   104.980  104.960    104.970  5799284  0.0272  0.0003  1.9053e-04  99.4866  0.0042          0.8 -0.0720   0.0023    0.0  9.5274e-05              0.0        2.6773e+08                  0.0
 2024-12-24   105.008   105.008  104.989    104.999  1920032  0.0280  0.0003  3.6191e-04  99.5394  0.0041          1.0 -0.0983   0.0026    0.0  2.7627e-04              0.0        2.6773e+08                  0.0
 2024-12-26   105.008   105.018  104.999    105.018  2072490  0.0274  0.0003  1.8092e-04  99.5706  0.0041          1.0 -0.0902   0.0027    0.0  1.8095e-04              0.0        2.6773e+08                  0.0
 2024-12-27   105.046   105.056  105.037    105.046  3195338  0.0281  0.0003  3.6175e-04  99.6123  0.0043          1.0 -0.0705   0.0024    0.0  2.6662e-04              0.0        2.6986e+08                  0.0
 2024-12-30   105.065   105.075  105.056    105.075  3477621  0.0282  0.0003  2.7599e-04  99.6502  0.0044          1.0 -0.0380   0.0022    0.0  2.7607e-04              0.0        2.7339e+08                  0.0
 2024-12-31   105.084   105.094  105.075    105.084  3773422  0.0275  0.0003  1.8081e-04  99.6612  0.0040          1.0 -0.0493   0.0024    0.0  8.5653e-05              0.0        2.7545e+08                  0.0
 2025-01-02   105.104   105.104  105.094    105.104  2595249  0.0270  0.0003  1.9029e-04  99.6850  0.0041          1.0 -0.0431   0.0024    0.0  1.9032e-04              0.0        2.7405e+08                  0.0
 2025-01-03   105.142   105.142  105.132    105.132  2247581  0.0278  0.0003  3.6145e-04  99.7152  0.0041          1.0 -0.0702   0.0024    0.0  2.6640e-04              0.0        2.7405e+08                  0.0
 2025-01-06   105.142   105.151  105.142    105.151  2736496  0.0271  0.0003  1.8069e-04  99.7339  0.0042          1.0 -0.0643   0.0021    0.0  1.8073e-04              0.0        2.7545e+08                  0.0
 2025-01-07   105.151   105.170  105.151    105.170  2559518  0.0266  0.0003  1.8066e-04  99.7514  0.0042          1.0 -0.0588   0.0014    0.0  1.8069e-04              0.0        2.7545e+08                  0.0
 2025-01-08   105.161   105.170  105.161    105.170  4537180  0.0253  0.0002  8.5576e-05  99.7514  0.0037          0.8 -0.0440   0.0012    0.0  0.0000e+00              0.0        2.7567e+08                  0.0
 2025-01-10   105.209   105.209  105.199    105.199  9021342  0.0263  0.0002  3.7073e-04  99.7774  0.0038          0.8  0.0006   0.0009    0.0  2.7574e-04              0.0        2.7750e+08                  0.0
 2025-01-13   105.218   105.218  105.209    105.218  9426220  0.0258  0.0002  1.8058e-04  99.7926  0.0040          0.8 -0.0057   0.0008    0.0  1.8061e-04              0.0        2.7937e+08                  0.0,
 'USFR':             Adj Open  Adj High  Adj Low  Adj Close    Volume     ATR    ATRP     TRP      RSI  Mom_21  Consistency   IR_63  Beta_63   DD_21  Ret_1d  RollingStalePct  RollMedDollarVol  RollingSameVolCount
 Date
 2024-12-02   47.7797   47.7892  47.7797    47.7892   5536507  0.0138  0.0003  0.0002  97.4618  0.0048          1.0 -0.1799  -0.0019  0.0000  0.0002              0.0        1.9199e+08                  0.0
 2024-12-03   47.7892   47.7987  47.7797    47.7797   2794203  0.0141  0.0003  0.0004  91.3268  0.0042          0.8 -0.1866  -0.0018 -0.0002 -0.0002              0.0        1.9179e+08                  0.0
 2024-12-04   47.7987   47.7987  47.7892    47.7987   2634291  0.0145  0.0003  0.0004  92.3623  0.0044          0.8 -0.2043  -0.0020  0.0000  0.0004              0.0        1.9161e+08                  0.0
 2024-12-05   47.7987   47.8082  47.7987    47.8082   2898110  0.0141  0.0003  0.0002  92.8237  0.0044          0.8 -0.2530   0.0003  0.0000  0.0002              0.0        1.9144e+08                  0.0
 2024-12-06   47.8177   47.8177  47.8082    47.8177   4751578  0.0138  0.0003  0.0002  93.2620  0.0048          0.8 -0.2342   0.0017  0.0000  0.0002              0.0        1.9144e+08                  0.0
 2024-12-09   47.8177   47.8272  47.8177    47.8272   4670832  0.0135  0.0003  0.0002  93.6778  0.0046          0.8 -0.2105   0.0015  0.0000  0.0002              0.0        1.9144e+08                  0.0

In [59]:
_tic = "NVDA"
_start_date = "2025-03-12"
_end_date = "2026-03-12"
# print(features_df.loc[_tic][_start_date:_end_date])
print(features_df.loc[_tic].tail(10))
# features_df.loc[_tic][_start_date:_end_date][["Ret_1d", "Consistency"]]

               ATR    ATRP     TRP      RSI  Mom_21  Consistency   IR_63  Beta_63   DD_21  Ret_1d  RollingStalePct  RollMedDollarVol  RollingSameVolCount
Date
2026-03-05  6.3715  0.0348  0.0337  47.6618  0.0166          0.6  0.0185   2.1244 -0.0625  0.0016              0.0        3.0610e+10                  0.0
2026-03-06  6.3822  0.0359  0.0367  42.4160  0.0208          0.6  0.0156   2.1571 -0.0907 -0.0301              0.0        3.0610e+10                  0.0
2026-03-09  6.4513  0.0353  0.0402  47.8271  0.0627          0.6  0.0139   2.1744 -0.0660  0.0272              0.0        3.0610e+10                  0.0
2026-03-10  6.3069  0.0341  0.0240  50.0459 -0.0035          0.8  0.0316   2.1737 -0.0552  0.0116              0.0        3.0610e+10                  0.0
2026-03-11  6.0828  0.0327  0.0170  51.3799 -0.0210          0.8  0.0212   2.1921 -0.0487  0.0069              0.0        3.0548e+10                  0.0
2026-03-12  5.9541  0.0325  0.0234  48.2240 -0.0286          0.6  0.0229   2.1141 -0.0635 -0.0155              0.0        3.0283e+10                  0.0
2026-03-13  5.9681  0.0331  0.0341  45.2320 -0.0515          0.6  0.0255   2.1677 -0.0782 -0.0158              0.0        3.0021e+10                  0.0
2026-03-16  6.1582  0.0336  0.0471  48.7510 -0.0198          0.6  0.0471   2.1643 -0.0630  0.0165              0.0        3.0021e+10                  0.0
2026-03-17  5.9840  0.0329  0.0204  47.3286 -0.0048          0.4  0.0586   2.1178 -0.0696 -0.0070              0.0        3.0021e+10                  0.0
2026-03-18  5.7745  0.0320  0.0169  45.6281 -0.0247          0.2  0.0557   2.0429 -0.0775 -0.0084              0.0        2.9967e+10                  0.0

In [60]:
# analyzer1.last_run.tickers
# analyzer1.last_run.start_date
# analyzer1.last_run.holding_end_date
_tic = analyzer1.last_run.tickers[0]
_start_date = analyzer1.last_run.start_date
_end_date = analyzer1.last_run.holding_end_date

In [61]:
result = SU.create_combined_dict(
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    tickers=[_tic],
    date_start=_start_date,
    date_end=_end_date,
    verbose=False,
)
print(f"ticker: {_tic}\n")
print(result[_tic])

ticker: BIL

            Adj Open  Adj High  Adj Low  Adj Close    Volume     ATR    ATRP     TRP      RSI  Mom_21  Consistency   IR_63     Beta_63  DD_21  Ret_1d  RollingStalePct  RollMedDollarVol  RollingSameVolCount
Date
2024-12-02   86.9204   86.9204  86.9109    86.9204  13652981  0.0215  0.0002  0.0003  98.2514  0.0040          0.8 -0.1814 -4.5751e-03    0.0  0.0003              0.0        5.5393e+08                  0.0
2024-12-03   86.9299   86.9394  86.9299    86.9394   5970462  0.0214  0.0002  0.0002  98.3908  0.0038          0.8 -0.1870 -4.6894e-03    0.0  0.0002              0.0        5.5308e+08                  0.0
2024-12-04   86.9584   86.9584  86.9489    86.9489   6275537  0.0212  0.0002  0.0002  98.4570  0.0037          1.0 -0.2059 -4.8962e-03    0.0  0.0001              0.0        5.5241e+08                  0.0
2024-12-05   86.9679   86.9679  86.9584    86.9584   6187982  0.0210  0.0002  0.0002  98.5225  0.0038          1.0 -0.2546 -3.0141e-03    0.0  0.0001              0.0        5.5127e+08                  0.0
2024-12-06   86.9964   86.9964  86.9869    86.9964   6005295  0.0222  0.0003  0.0004  98.7508  0.0040          1.0 -0.2356 -2.4772e-03    0.0  0.0004              0.0        5.5006e+08                  0.0
2024-12-09   87.0059   87.0154  87.0059    87.0059   9253349  0.0220  0.0003  0.0002  98.8007  0.0040          1.0 -0.2121 -2.3889e-03    0.0  0.0001              0.0        5.5006e+08                  0.0
2024-12-10   87.0154   87.0249  87.0154    87.0249   5682963  0.0218  0.0003  0.0002  98.8957  0.0037          1.0 -0.1819 -1.8956e-03    0.0  0.0002              0.0        5.5006e+08                  0.0
2024-12-11   87.0249   87.0344  87.0249    87.0344   6151887  0.0209  0.0002  0.0001  98.9409  0.0039          1.0 -0.1806 -1.8824e-03    0.0  0.0001              0.0        5.5006e+08                  0.0
2024-12-12   87.0439   87.0535  87.0439    87.0535   5019881  0.0208  0.0002  0.0002  99.0271  0.0040          1.0 -0.1557 -2.4577e-03    0.0  0.0002              0.0        5.4788e+08                  0.0
2024-12-13   87.0819   87.0819  87.0724    87.0819   6600186  0.0213  0.0002  0.0003  99.1392  0.0041          1.0 -0.1514 -2.5321e-03    0.0  0.0003              0.0        5.4788e+08                  0.0
2024-12-16   87.0914   87.0914  87.0819    87.0914   7115622  0.0205  0.0002  0.0001  99.1736  0.0042          1.0 -0.1603 -2.6296e-03    0.0  0.0001              0.0        5.4788e+08                  0.0
2024-12-17   87.1009   87.1009  87.0914    87.1009   6132419  0.0197  0.0002  0.0001  99.2076  0.0040          1.0 -0.1576 -2.4222e-03    0.0  0.0001              0.0        5.4594e+08                  0.0
2024-12-18   87.1009   87.1104  87.1009    87.1009   9753318  0.0190  0.0002  0.0001  99.2076  0.0039          0.8 -0.0424 -5.1332e-04    0.0  0.0000              0.0        5.4594e+08                  0.0
2024-12-19   87.1229   87.1229  87.1133    87.1133  14541706  0.0192  0.0002  0.0003  99.2541  0.0037          0.8 -0.0461 -3.3747e-04    0.0  0.0001              0.0        5.4594e+08                  0.0
2024-12-20   87.1420   87.1515  87.1420    87.1515  13298421  0.0205  0.0002  0.0004  99.3756  0.0040          0.8 -0.0645  5.4472e-04    0.0  0.0004              0.0        5.4594e+08                  0.0
2024-12-23   87.1515   87.1611  87.1515    87.1515   6887932  0.0198  0.0002  0.0001  99.3756  0.0039          0.6 -0.0710  3.2080e-04    0.0  0.0000              0.0        5.4788e+08                  0.0
2024-12-24   87.1706   87.1802  87.1706    87.1706   4344360  0.0204  0.0002  0.0003  99.4295  0.0038          0.6 -0.0975  4.5921e-04    0.0  0.0002              0.0        5.4594e+08                  0.0
2024-12-26   87.1897   87.1897  87.1801    87.1897   6488875  0.0203  0.0002  0.0002  99.4780  0.0039          0.8 -0.0891  6.0095e-04    0.0  0.0002              0.0        5.4788e+08                  0.0
2024-12-27   87.2279   87.2279  87.2183    87.2279   6438049  0.0216  0.0002  0.0004  99.5589  0.0044          0.8 -0.0690 -9.2440e-05    0.0  0.0004              0.0        5.5006e+08                  0.0
2024-12-30   87.2279   87.2374  87.2279    87.2279   9421129  0.0207  0.0002  0.0001  99.5589  0.0040          0.6 -0.0374  5.3032e-04    0.0  0.0000              0.0        5.5127e+08                  0.0
2024-12-31   87.2565   87.2565  87.2469    87.2469   7651570  0.0213  0.0002  0.0003  99.5950  0.0040          0.8 -0.0485  6.1885e-04    0.0  0.0002              0.0        5.5241e+08                  0.0
2025-01-02   87.2660   87.2660  87.2565    87.2660  11272640  0.0211  0.0002  0.0002  99.6280  0.0040          0.8 -0.0424  5.8695e-04    0.0  0.0002              0.0        5.5241e+08                  0.0
2025-01-03   87.2947   87.2947  87.2756    87.2756   8213688  0.0217  0.0002  0.0003  99.6438  0.0039          0.8 -0.0702  3.7502e-04    0.0  0.0001              0.0        5.5241e+08                  0.0
2025-01-06   87.2851   87.2947  87.2851    87.2851   8202370  0.0215  0.0002  0.0002  99.6591  0.0039          0.8 -0.0642  2.0715e-04    0.0  0.0001              0.0        5.5308e+08                  0.0
2025-01-07   87.3042   87.3137  87.2947    87.3042   7290344  0.0220  0.0003  0.0003  99.6882  0.0040          1.0 -0.0593  1.8027e-04    0.0  0.0002              0.0        5.5393e+08                  0.0
2025-01-08   87.3233   87.3233  87.3137    87.3233   6993042  0.0218  0.0002  0.0002  99.7145  0.0038          1.0 -0.0436  6.0023e-04    0.0  0.0002              0.0        5.5477e+08                  0.0
2025-01-10   87.3615   87.3615  87.3519    87.3519  10597029  0.0230  0.0003  0.0004  99.7486  0.0040          1.0  0.0010  1.5257e-04    0.0  0.0003              0.0        5.5542e+08                  0.0
2025-01-13   87.3615   87.3710  87.3615    87.3615   8230978  0.0227  0.0003  0.0002  99.7590  0.0039          1.0 -0.0054  9.0904e-05    0.0  0.0001              0.0        5.5542e+08                  0.0