v61 
- **Verified all metric calculation with Excel** 
- Updated core.analyzer
- Replaced the `Result` pattern with exceptions and flattened the logic
- Refactored the `AlphaEngine` into a streamlined Orchestrator pattern
-  **Strict Date Logic:** No more "Time Travel" bugs.
-  **Dataclass Contracts:** No more "Magic String" typos or blind dictionaries.
-  **Exception Flow:** The `run` method is now a clean, readable story instead of a maze of `if/else` checks.
-  **Performance Workers:** Math is separated from orchestration.
- Ret_1d, explicitly turns division-by-zero results (`inf`) into `NaN`, and replace [np.inf, -np.inf] with np.nan

v60  
- Converted code from notebook to modular system.
- Fixed divide by zero warning from calculate_gain
- Added subtitle to subplots
- Added Volatility Regime plot

v59  
- Removed "nest" of if-statements in **AlphaEngine.run**
- Use **Result Pattern** to handle errors
- Change verify_analyzer_short and verify_analyzer_long gain calculation from simple return to logarithmic return
- Change calculate_gain from simple return to logarithmic return
- Remove bfill from calculate_gain to prevent backfill with future data
- Verify macro_df calculation

v57, v58  
added marco subplotsThe macro regime framework is now fully documented with:
- Trend (SMA200 deviation) → Where we are in the cycle  
- Trend Velocity (Z) → How fast we're moving relative to normal
- VIX-Z → Market fear/complacency levels

v56  

- De-coupled features_df and macro_df
- generate_features and audit_feature_engineering_integrity use GLOBAL_SETTINGS

v55  
Added
- audit_feature_engineering_integrity (check calculation in features_df)  

These are the metrics in plot  
- --- 1. LEGACY / SANITY CHECKS ---
- "Price Gain": lambda obs: QuantUtils.calculate_gain(obs["lookback_close"]),
- "Sharpe": lambda obs: QuantUtils.calculate_sharpe(obs["lookback_returns"]),
- "Sharpe (ATRP)": lambda obs: QuantUtils.calculate_sharpe_vol(
        obs["lookback_returns"], obs["atrp"]
    ),
- "Sharpe (TRP)": lambda obs: QuantUtils.calculate_sharpe_vol(
        obs["lookback_returns"], obs["trp"]
    ),
- --- 2. NEW QUANT METRICS ---
- "Momentum (21d)": lambda obs: obs["mom_21"],
- "Information Ratio (IR)": lambda obs: obs["ir_63"],  # Kept this one
- "Consistency (WinRate)": lambda obs: obs["consistency"],
- "Oversold (RSI)": lambda obs: -obs["rsi"],
- "Dip Buyer (Drawdown)": lambda obs: -obs["dd_21"],
- "Low Volatility": lambda obs: -obs["atrp"],

v54
-  **Replaced plot_walk_forward_analyzer with create_walk_forward_analyzer**

v53  
Looking at this registry with a quant lens, the list is **comprehensive but bloated**—we have **momentum measured five times under different names** (roc₁, roc₃, roc₅, roc₁₀, roc₂₁ and their negative twins “Pullback”).  
That’s **10 slots** telling us almost the same story at slightly different lags; in a rank-based engine they will **crowd the signal space** and inflate turnover without adding IC.

Duplicate / redundant cluster  
- Momentum 1 D ↔ Pullback 1 D (perfect mirror)  
- Same for 3 D, 5 D, 10 D, 21 D.  
**Keep one side only**—momentum is enough; the portfolio constructor can always **reverse the rank** if it wants “oversold”.

Close cousins that can be merged  
- “Sharpe” vs “Sharpe (ATRP)” – both are return / vol; keep **ATRP version** because it is regime-aware and smoother.  
- “RVol” vs “Vol_Regime” – both capture vol expansion; keep the **longer-memory one** (Vol_Regime) and drop the intraday snapshot.

Gaps that matter to a quant  
1. **Consistency sensor**: nowhere do we ask “how often did the ticker close higher than it opened?” – add **5-day win-rate** or **up-day hit-ratio**.  
2. **Risk-adjusted intraday strength**: no **Sharpe(on-balance volume)** or **volume-momentum efficiency**; OBV_Score is raw, not risk-scaled.  
3. **Benchmark-relative consistency**: “Alpha (RelStrength)” is cumulative; add **rolling information ratio vs SPY** to catch *sustained* alpha, not one gap.  
4. **Tail flag**: no **skew** or **max-drawdown** metric; a single 20 % gap stock can poison the book.  
5. **Macro regime overlay**: no **beta-to-SPY** or **correlation-break** sensor; mid-2022 macro swings showed that low-beta names behaved like a different asset class.

Recommended minimal clean set (≤ 12 metrics)

1. Sharpe(ATRP) – strategic anchor  
2. Momentum 21 D – slow trend  
3. Momentum 5 D – fast trend  
4. 5-day win-rate – consistency  
5. RSI(Trend) – strength confirmation  
6. OBV_Score – volume conviction  
7. Vol_Regime – vol expansion filter  
8. Alpha(RelStrength) 63-day IR – benchmark consistency  
9. Max 21-day drawdown – tail guard  
10. Beta-to-SPY – macro regime tag  

Drop everything else; the freed-up slots reduce collinearity, cut turnover, and leave head-room for **interaction terms** (e.g. momentum × consistency) that actually add orthogonal signal.



Below is a single, fully-vectorised block that adds the **five gap metrics** to your existing MultiIndex OHLCV frame.  
It never loops over tickers; everything is done with `groupby(level=0).rolling(...)` so it runs in C-speed and keeps the same index.

```python
import pandas as pd
import numpy as np

# ----------  CONFIG  -------------------------------------------------
LKB_RET   = 21          # look-back for return-based metrics
LKB_CONS  = 5           # consistency window (days)
LKB_IR    = 63          # IR window
LKB_BETA  = 63          # beta window
LKB_TAIL  = 21          # max-drawdown window
BENCH     = 'SPY'       # ticker that exists in your universe
# ---------------------------------------------------------------------

# 1.  DAILY RETURNS ----------------------------------------------------
df['ret'] = df.groupby(level=0)['Adj Close'].pct_change()

# 2.  CONSISTENCY SENSOR  (5-day win-rate) -----------------------------
df['up']  = df['ret'].gt(0).astype(int)
df['consistency_5d'] = (df.groupby(level=0)['up']
                          .rolling(LKB_CONS).mean()
                          .reset_index(level=0, drop=True))

# 3.  BENCHMARK-RELATIVE CONSISTENCY  (63-day IR vs SPY) ---------------
# need benchmark return
bench_ret = df.xs(BENCH, level=0)['ret'].rename('bench_ret')
df = df.join(bench_ret, how='left')          # broadcast to all tickers

df['active'] = df['ret'] - df['bench_ret']
g = df.groupby(level=0)
active_mean  = g['active'].rolling(LKB_IR).mean()
active_std   = g['active'].rolling(LKB_IR).std()
df['IR_63d'] = active_mean / active_std      # Information Ratio

# 4.  TAIL FLAG  (21-day max drawdown) ---------------------------------
roll_max = g['Adj Close'].rolling(LKB_TAIL).max()
dd = (df['Adj Close'] - roll_max) / roll_max
df['max_dd_21d'] = dd.groupby(level=0).rolling(LKB_TAIL).min()

# 5.  MACRO REGIME OVERLAY  (beta to SPY) ------------------------------
cov  = g['ret'].rolling(LKB_BETA).cov(df['bench_ret'])
var  = df['bench_ret'].groupby(level=0).rolling(LKB_BETA).var()
df['beta_SPY'] = cov / var

# 6.  RISK-ADJUSTED INTRADAY STRENGTH  (OBV Sharpe) --------------------
# OBV
df['close_chg'] = df.groupby(level=0)['Adj Close'].diff()
df['vol_dir']   = np.where(df['close_chg'] > 0,  df['Volume'],
                   np.where(df['close_chg'] < 0, -df['Volume'], 0))
df['obv'] = df.groupby(level=0)['vol_dir'].cumsum()

# OBV return & vol
df['obv_ret'] = df.groupby(level=0)['obv'].pct_change()
obv_mean = g['obv_ret'].rolling(LKB_RET).mean()
obv_std  = g['obv_ret'].rolling(LKB_RET).std()
df['OBV_Sharpe_21d'] = obv_mean / obv_std

# drop helper columns --------------------------------------------------
df.drop(columns=['up','bench_ret','active','close_chg','vol_dir'], inplace=True)
```

After the block you have five new columns:

- `consistency_5d`      – 5-day win-rate (0-1)  
- `IR_63d`              – 63-day Information Ratio vs SPY  
- `max_dd_21d`          – 21-day maximum drawdown (≤ 0)  
- `beta_SPY`            – rolling beta to SPY  
- `OBV_Sharpe_21d`      – OBV risk-adjusted momentum  

All are aligned to the original MultiIndex and ready to be ranked or z-scored inside your Alpha Engine.

v52  
- **Cascase Filter results `AGREED` with bot_v54i.ipynb**
- **Cascade Filter works with df_ohlcv_subset**
- **verify_engine_results_short_form**
- **verify_engine_results_long_form**
-  **The Temporal Alignment Fix:** We synchronized the "Reward" (Returns) and "Risk" (Volatility) by implementing the $N-1$ denominator logic. This ensures that Day 1's volatility no longer dilutes your Sharpe scores.
-  **The Event-Driven Re-normalization:** We verified that the Engine correctly resets capital and weights at the start of the Holding period, giving you an accurate "Fresh Start" performance metric.
-  **The Double-Blind Verification:** We proved that the Engine's True Range (TRP) math is flawless by recreating it from raw High/Low/Close data and achieving an 8-decimal match.
-  **Mathematical Fortification:** We centralized all logic into a polymorphic `QuantUtils` kernel that handles both single-portfolio reports and whole-universe rankings with built-in numerical safety.
-  **Volatility Evolution:** We successfully added `TRP` (True Range Percent) and the `Sharpe (TRP)` metric, giving you a raw, high-frequency alternative to the smoothed ATR.
-  **Data Integrity:** We implemented the "Momentum Collapse" tripwire (`verify_ranking_integrity`) to ensure that your risk-adjusted rankings never accidentally devolve into simple price momentum.
-  **The "Audit Pack" Architecture:** We collapsed fragmented results into a single, atomic container, ensuring that your inputs, results, and debug data are always perfectly synchronized.
-  **Total Transparency:** We replaced scattered CSV files with a unified **Excel Audit Report**, allowing for 1-to-1 manual verification of every calculation in the system.

v51

UNDO v50, Calculate Sharpe(ATR) using mean over lookback period.  

Comment out ``# --- PINPOINT START: ATRP SWITCH ---`` in function ``_select_tickers`` can switch between ``Averaged ATRP over lookback period`` and ``Current ATRP``  
    # --- PINPOINT START: ATRP SWITCH ---  
    # To switch between Old (Averaged ATRP) and New (Current ATRP):  
    # 1. Comment out the logic you DON'T want.  
    # 2. Uncomment the logic you DO want.

v50

Ticker selection based on atrp_value_for_obs based on decision day, was based on average over lookback period.

v48  
### Summary of what you just accomplished:
1.  **Strict Math:** `QuantUtils` now contains an `assert` that prevents any dev (or AI) from filling the first day with 0.0.
2.  **Semantic Protection:** Variables are now named `returns_WITH_BOUNDARY_NAN`, signaling to the AI that the Null value is part of its identity.
3.  **Complete SOLID Separation:** The Engine CONDUCTS the simulation, while `QuantUtils` CALCULATES the results. They no longer share logic.

**1. Data Flow of `plot_walk_forward_analyzer`**
The function acts as a **UI wrapper** around the `AlphaEngine` class. The flow is:
1.  **Input:** User selects parameters (Dates, Lookback, Strategy).
2.  **State Construction:** `AlphaEngine` slices the historical data (`df_ohlcv`, `df_atrp`) up to the `decision_date`.
3.  **Policy Execution (Hardcoded):** The engine applies the logic (e.g., `METRIC_REGISTRY['Sharpe']`) to rank stocks based *only* on the Lookback window.
4.  **Environment Step:** It simulates a "Buy" at `decision_date + 1` and calculates the returns over the `holding_period`.
5.  **Reward Generation:** It outputs performance metrics (`holding_p_gain`, `holding_p_sharpe`).

In [33]:
# 1. Enable Autoreload
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

def add_project_root_to_path():
    """Find notebooks_RLVR and add to sys.path."""
    current = Path.cwd()

    # Search upward for notebooks_RLVR folder
    for path in [current] + list(current.parents):
        if path.name == "notebooks_RLVR":
            sys.path.insert(0, str(path))
            print(f"✓ Added to path: {path}")
            return path
        # Also check if notebooks_RLVR exists as child (for running from stocks/)
        candidate = path / "notebooks_RLVR"
        if candidate.exists():
            sys.path.insert(0, str(candidate))
            print(f"✓ Added to path: {candidate}")
            return candidate

    raise RuntimeError("Could not find notebooks_RLVR directory")


# Run once at notebook start
add_project_root_to_path()


# 2. Force reload cached modules (run this to refresh code changes)
# import importlib

modules_to_reload = [
    "core.analyzer",
    "core.auditor",
    "core.contracts",    
    "core.engine",
    "core.features",
    "core.paths",
    "core.performance",
    "core.quant",
    "core.result",
    "core.settings",
    "core.utils",
    "strategy.registry",
]

for mod in modules_to_reload:
    if mod in sys.modules:
        del sys.modules[mod]


# 3. Standard imports
import pandas as pd
# import os
import numpy as np

from IPython.display import display
# from dataclasses import fields, asdict, is_dataclass
# from typing import List, Union, Tuple 


# 4. Fresh imports (these will re-import from disk due to cache clearing above)

from core.analyzer import create_walk_forward_analyzer, run_headless_simulation
from core.auditor import SystemAuditor as SA
from core.contracts import FilterPack
from core.engine import AlphaEngine
from core.features import generate_features
from core.paths import OUTPUT_DIR
# from core.performance import PerformanceCalculator
# from core.quant import QuantUtils
from core.result import HeadlessReporter
from core.settings import GLOBAL_SETTINGS
from core.utils import SystemUtils as SU
# from strategy.registry import METRIC_REGISTRY


# 5. Pandas display settings
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", 50)
pd.set_option("display.precision", 4)


# # 6. Instantiate engine (customize DataFrames as needed)
# old_master_engine = AlphaEngine(
#     df_ohlcv=df_ohlcv,
#     features_df=features_df,
#     macro_df=macro_df,
#     df_close_wide=df_close_wide,
#     df_atrp_wide=df_atrp_wide,
#     df_trp_wide=df_trp_wide,
# )

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
✓ Added to path: c:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR
NOTEBOOKS_RLVR_ROOT: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR

OUTPUT_DIR: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output

In [4]:
from dotenv import load_dotenv
import os
from pathlib import Path


def load_env_from_root(env_var_name):
    """
    Load specified environment variable from .env file in root directory

    Parameters:
    -----------
    env_var_name : str
        Name of the environment variable to retrieve (e.g., 'DATA_PATH_OHLCV', 'API_KEY')

    Returns:
    --------
    str : Value of the requested environment variable

    Example:
    --------
    DATA_PATH_OHLCV = load_env_from_root('DATA_PATH_OHLCV')
    API_KEY = load_env_from_root('API_KEY')
    """
    # Start from current file or current working directory
    try:
        start_path = Path(__file__).resolve().parent
    except NameError:
        # If __file__ not defined (e.g., Jupyter), use current working directory
        start_path = Path.cwd()

    # Search upwards for the .env directory
    current = start_path
    for _ in range(10):  # Limit search depth
        env_path = current / ".env" / "my_api_key.env"
        if env_path.exists():
            load_dotenv(env_path, override=True)
            value = os.getenv(env_var_name)
            if value is None:
                raise KeyError(f"Variable '{env_var_name}' not found in {env_path}")
            return value

        # Go up one level
        parent = current.parent
        if parent == current:  # Reached root
            break
        current = parent

    raise FileNotFoundError(
        f"Could not find .env/my_api_key.env when searching for '{env_var_name}'"
    )


#

In [5]:
DATA_PATH_OHLCV = load_env_from_root("DATA_PATH_OHLCV")
DATA_PATH_INDICES = load_env_from_root("DATA_PATH_INDICES")
print(f"DATA_PATH_OHLCV: {DATA_PATH_OHLCV}")
print(f"DATA_PATH_INDICES: {DATA_PATH_INDICES}")

DATA_PATH_OHLCV: c:\Users\ping\Files_win10\python\py311\stocks\data\df_OHLCV_stocks_etfs.parquet
DATA_PATH_INDICES: c:\Users\ping\Files_win10\python\py311\stocks\data\df_indices.parquet

In [6]:
df_indices = pd.read_parquet(DATA_PATH_INDICES, engine="pyarrow")
print(f"df_indices:|n{df_indices}")

df_indices:|n                   Adj Open  Adj High  Adj Low  Adj Close  Volume
Ticker Date
^BSESN 1997-07-01   4263.11   4301.77  4247.66    4300.86       0
       1997-07-02   4302.96   4395.31  4295.40    4333.90       0
       1997-07-03   4335.79   4393.29  4299.97    4323.46       0
       1997-07-04   4332.70   4347.59  4300.58    4323.82       0
       1997-07-07   4326.81   4391.01  4289.49    4291.45       0
...                     ...       ...      ...        ...     ...
^VIX3M 2026-03-16     25.98     25.98    24.67      24.92       0
       2026-03-17     24.26     24.58    23.87      24.33       0
       2026-03-18     25.00     26.57    24.82      26.56       0
       2026-03-19     27.96     28.03    25.19      25.54       0
       2026-03-20     26.07     28.61    25.91      27.43       0

[136293 rows x 5 columns]

In [ ]:
_indices = df_indices.index.get_level_values(0).unique().tolist()
display(_indices)
df_indices.info()

In [7]:
print(f"Takes about 1.5 minutes")
df_ohlcv = pd.read_parquet(DATA_PATH_OHLCV, engine="pyarrow")

Takes about 1.5 minutes

In [ ]:
print(f"df_ohlcv.head():\n {df_ohlcv.head()}\n")
df_ohlcv.info()

In [8]:
print(f"Takes about 2.5 minutes to generate_features")

features_df, macro_df = generate_features(
    df_ohlcv=df_ohlcv,
    df_indices=df_indices,
    benchmark_ticker=GLOBAL_SETTINGS["benchmark_ticker"],
)

Takes about 2.5 minutes to generate_features
⚡ Generating Decoupled Features (Benchmark: SPY)...

In [ ]:
print(f"features_df.info():\n{features_df.info()}\n")
print(f"features_df.index.names:\n{features_df.index.names}\n")
print(f"macro_df.info():\n{macro_df.info()}\n")
print(f"macro_df.index.names:\n{macro_df.index.names}\n")

In [ ]:
# Pre-flight Automated Audit Suite
checks = [
    SA.verify_math_integrity(),
    SA.verify_ranking_integrity(),
    SA.verify_vol_alignment_integrity(),
    SA.verify_feature_engineering_integrity(),
]

for check in checks:
    icon = "✅" if check.ok else "🔥"
    print(f"{icon} {check.msg}")
    if not check.ok:
        print("🛑 Critical Failure. System Halted.")
        break

print("=" * 85)
# Separate verify_marco_engine output from intertwine with other outputs

checks = [
    SA.verify_macro_engine(
        df_ohlcv=df_ohlcv,
        df_indices=df_indices,
        original_macro_df=macro_df,
        settings=GLOBAL_SETTINGS,
    ),
]

for check in checks:
    icon = "✅" if check.ok else "🔥"
    print(f"{icon} {check.msg}")
    if not check.ok:
        print("🛑 Critical Failure. System Halted.")
        break

In [9]:
print(
    "🚀 Generating Wide Matrices for Instant Backtesting... (takes about 1 minute to run)"
)

# 1. Price Matrix
df_close_wide = df_ohlcv["Adj Close"].unstack(level=0)

# 2. Volatility Matrices (Unstack and Align)
# Using features_df (the first item from the tuple)
print("   - Unstacking ATRP...")
df_atrp_wide = features_df["ATRP"].unstack(level=0).reindex_like(df_close_wide)

print("   - Unstacking TRP...")
df_trp_wide = features_df["TRP"].unstack(level=0).reindex_like(df_close_wide)

# 3. Handle Data Gaps (Sanitize the Wide Matrices)
if GLOBAL_SETTINGS["handle_zeros_as_nan"]:
    df_close_wide = df_close_wide.replace(0, np.nan)

# Forward fill up to the limit, then fill remaining with the "Disaster Detection" value
df_close_wide = df_close_wide.ffill(limit=GLOBAL_SETTINGS["max_data_gap_ffill"])
df_close_wide = df_close_wide.fillna(GLOBAL_SETTINGS["nan_price_replacement"])

print(
    f"✅ Pre-computation Complete. Tickers: {len(df_close_wide.columns)}, Days: {len(df_close_wide)}"
)
print("   Ready: df_close_wide, df_atrp_wide, df_trp_wide, and macro_df.")

🚀 Generating Wide Matrices for Instant Backtesting... (takes about 1 minute to run)
   - Unstacking ATRP...
   - Unstacking TRP...
✅ Pre-computation Complete. Tickers: 1582, Days: 16162
   Ready: df_close_wide, df_atrp_wide, df_trp_wide, and macro_df.

In [10]:
# 6. Instantiate engine (customize DataFrames as needed)
old_master_engine = AlphaEngine(
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    macro_df=macro_df,
    df_close_wide=df_close_wide,
    df_atrp_wide=df_atrp_wide,
    df_trp_wide=df_trp_wide,
)

In [ ]:
# universe_subset=None means "Scan the whole market"
analyzer1, stage1_pack = create_walk_forward_analyzer(
    old_master_engine, universe_subset=None
)

print("🚀 Ready for Stage 1: Run Simulation for first filter.")
analyzer1.show()

🚀 Ready for Stage 1: Run Simulation for first filter.
DEBUG: 937 stocks passed filters on 2025-12-10

VBox(children=(HTML(value='<b>1. Timeline Configuration:</b> (Past <--- Decision ---> Future)'), HBox(children…

In [ ]:
# Get decision date from last run
decision_date_last_run = FilterPack(decision_date=analyzer1.last_run.decision_date)

# 1. LAUNCH STAGE 2 (Cascade)
# universe_subset=analyzer1.last_run.tickers means "Scan the whole market"
analyzer2, stage1_pack = create_walk_forward_analyzer(
    old_master_engine,
    universe_subset=analyzer1.last_run.tickers,
    # universe_subset=None,
    filter_pack=decision_date_last_run,
)

print("🚀 Ready for Stage 2: Run Simulation for 2nd filter.")
analyzer2.show()

In [ ]:
###############################
###############################

In [12]:
my_analyzer = analyzer1

my_res = SU.visualize_analyzer_structure(my_analyzer)

====================================================================
🔍 HIGH-TRANSPARENCY AUDIT MAP
====================================================================
[  0] 📦 audit_pack (EngineOutput)
[  1]   📈 portfolio_series (shape=(28,))
[  2]   📈 benchmark_series (shape=(28,))
[  3]   🧮 normalized_plot_data (shape=(28, 2))
[  4]   📂 tickers (len=2)
[  5]     📄 index_0 (str)
[  6]     📄 index_1 (str)
[  7]   📈 initial_weights (shape=(2,))
[  8]   📂 perf_metrics (len=24)
[  9]     🔢 full_p_gain (float)
[ 10]     🔢 full_p_sharpe (float)
[ 11]     🔢 full_p_sharpe_atrp (float)
[ 12]     🔢 full_p_sharpe_trp (float)
[ 13]     🔢 lookback_p_gain (float)
[ 14]     🔢 lookback_p_sharpe (float)
[ 15]     🔢 lookback_p_sharpe_atrp (float)
[ 16]     🔢 lookback_p_sharpe_trp (float)
[ 17]     🔢 holding_p_gain (float)
[ 18]     🔢 holding_p_sharpe (float)
[ 19]     🔢 holding_p_sharpe_atrp (float)
[ 20]     🔢 holding_p_sharpe_trp (float)
[ 21]     🔢 full_b_gain (float)
[ 22]     🔢 full_b_sharpe (float)
[ 23]     🔢 full_b_sharpe_atrp (float)
[ 24]     🔢 full_b_sharpe_trp (float)
[ 25]     🔢 lookback_b_gain (float)
[ 26]     🔢 lookback_b_sharpe (float)
[ 27]     🔢 lookback_b_sharpe_atrp (float)
[ 28]     🔢 lookback_b_sharpe_trp (float)
[ 29]     🔢 holding_b_gain (float)
[ 30]     🔢 holding_b_sharpe (float)
[ 31]     🔢 holding_b_sharpe_atrp (float)
[ 32]     🔢 holding_b_sharpe_trp (float)
[ 33]   🧮 results_df (shape=(2, 2))
[ 34]   📅 start_date (Timestamp)
[ 35]   📅 decision_date (Timestamp)
[ 36]   📅 buy_date (Timestamp)
[ 37]   📅 holding_end_date (Timestamp)
[ 38]   📈 portfolio_atrp_series (shape=(28,))
[ 39]   📈 benchmark_atrp_series (shape=(28,))
[ 40]   📈 portfolio_trp_series (shape=(28,))
[ 41]   📈 benchmark_trp_series (shape=(28,))
[ 42]   📄 error_msg (NoneType)
[ 43]   📂 debug_data (len=8)
[ 44]     📂 audit_liquidity (len=6)
                ╰── date --> [See ID 35]
[ 45]       🔢 total_tickers_available (int)
[ 46]       🔢 percentile_setting (float)
[ 47]       🔢 final_cutoff_usd (shape=())
[ 48]       📄 tickers_passed (shape=())
[ 49]       🧮 universe_snapshot (shape=(1580, 14))
[ 50]     🧮 full_universe_ranking (shape=(937, 4))
[ 51]     📂 meta (len=4)
[ 52]       🔢 dropped_count (int)
[ 53]       📂 dropped_tickers (len=0)
[ 54]       🔢 clean_count (int)
[ 55]       📄 selection_range (str)
[ 56]     📦 inputs_snapshot (EngineInput)
[ 57]       📄 mode (str)
[ 58]       📅 start_date (Timestamp)
[ 59]       🔢 lookback_period (int)
[ 60]       🔢 holding_period (int)
[ 61]       📄 metric (str)
[ 62]       📄 benchmark_ticker (str)
[ 63]       🔢 rank_start (int)
[ 64]       🔢 rank_end (int)
[ 65]       📂 quality_thresholds (len=4)
[ 66]         🔢 min_median_dollar_volume (int)
[ 67]         🔢 min_liquidity_percentile (float)
[ 68]         🔢 max_stale_pct (float)
[ 69]         🔢 max_same_vol_count (int)
[ 70]       📂 manual_tickers (len=0)
[ 71]       🔢 debug (bool)
[ 72]       📄 universe_subset (NoneType)
[ 73]     📂 verification (len=2)
[ 74]       📂 p (len=4)
                  ╰── val --> [See ID 1]
[ 75]         📈 ret (shape=(28,))
                  ╰── atrp --> [See ID 38]
                  ╰── trp --> [See ID 40]
[ 76]       📂 b (len=4)
                  ╰── val --> [See ID 2]
[ 77]         📈 ret (shape=(28,))
                  ╰── atrp --> [See ID 39]
                  ╰── trp --> [See ID 41]
[ 78]     📂 portfolio_raw_components (len=4)
[ 79]       🧮 prices (shape=(28, 2))
[ 80]       🧮 atrp (shape=(28, 2))
[ 81]       🧮 trp (shape=(28, 2))
[ 82]       🧮 ohlcv_raw (shape=(56, 5))
[ 83]     📂 benchmark_raw_components (len=4)
[ 84]       🧮 prices (shape=(28, 1))
[ 85]       🧮 atrp (shape=(28, 1))
[ 86]       🧮 trp (shape=(28, 1))
[ 87]       🧮 ohlcv_raw (shape=(28, 5))
              ╰── selection_audit --> [See ID 50]
[ 88]   🧮 macro_df (shape=(16162, 7))

In [13]:
SU.peek(3, my_res)

 ============================================================
 📍 INDEX: [3]
 🏷️  NAME:  normalized_plot_data
 📂 PATH:  audit_pack -> normalized_plot_data
 ============================================================

Ticker        ONON      TD
Date
2025-11-10  1.0000  1.0000
2025-11-11  1.0063  1.0057
2025-11-12  1.1874  1.0197
2025-11-13  1.2128  1.0026
2025-11-14  1.2128  1.0026
2025-11-17  1.1842  1.0038
2025-11-18  1.2203  1.0138
2025-11-19  1.2386  1.0055
2025-11-20  1.1848  1.0022
2025-11-21  1.1808  1.0112
2025-11-24  1.1668  1.0192
2025-11-25  1.1945  1.0144
2025-11-26  1.2354  1.0283
2025-11-28  1.2583  1.0344
2025-12-01  1.2780  1.0291
2025-12-02  1.2915  1.0420
2025-12-03  1.3464  1.0398
2025-12-04  1.3304  1.0609
2025-12-05  1.3770  1.0885
2025-12-08  1.3450  1.0861
2025-12-09  1.3533  1.0986
2025-12-10  1.3936  1.1247
2025-12-11  1.4159  1.1317
2025-12-12  1.3947  1.1267
2025-12-15  1.3670  1.1343
2025-12-16  1.3813  1.1295
2025-12-17  1.3759  1.1234
2025-12-18  1.3862  1.1403

Ticker        ONON      TD
Date
2025-11-10  1.0000  1.0000
2025-11-11  1.0063  1.0057
2025-11-12  1.1874  1.0197
2025-11-13  1.2128  1.0026
2025-11-14  1.2128  1.0026
2025-11-17  1.1842  1.0038
2025-11-18  1.2203  1.0138
2025-11-19  1.2386  1.0055
2025-11-20  1.1848  1.0022
2025-11-21  1.1808  1.0112
2025-11-24  1.1668  1.0192
2025-11-25  1.1945  1.0144
2025-11-26  1.2354  1.0283
2025-11-28  1.2583  1.0344
2025-12-01  1.2780  1.0291
2025-12-02  1.2915  1.0420
2025-12-03  1.3464  1.0398
2025-12-04  1.3304  1.0609
2025-12-05  1.3770  1.0885
2025-12-08  1.3450  1.0861
2025-12-09  1.3533  1.0986
2025-12-10  1.3936  1.1247
2025-12-11  1.4159  1.1317
2025-12-12  1.3947  1.1267
2025-12-15  1.3670  1.1343
2025-12-16  1.3813  1.1295
2025-12-17  1.3759  1.1234
2025-12-18  1.3862  1.1403

In [14]:
analyzer1.last_run.tickers
analyzer1.last_run.start_date
analyzer1.last_run.holding_end_date

Timestamp('2025-12-18 00:00:00')

In [15]:
# 3. Post-flight Reconciliation
audit = SA.verify_analyzer_short(my_analyzer)
if not audit.ok:
    print(f"🚨 ALERT: {audit.msg}")
    # You could trigger a notification or log the failure here

===============================================================================================
***********************************************************************************************
🕵️  STARTING SHORT-FORM AUDIT: Sharpe (ATRP) @ 2025-12-10
⚠️  ASSUMPTION: Verification logic is independent, but trusts Engine source DataFrames
    (engine.features_df, engine.df_close, and debug['portfolio_raw_components'])
***********************************************************************************************
===============================================================================================
🕵️  AUDIT: Sharpe (ATRP) @ 2025-12-10
===============================================================================================
LAYER 1: SURVIVAL  | Universe: 1580 -> Survivors: 937 | ✅ PASS
LAYER 2: SELECTION | Strategy: Sharpe (ATRP) | Selection Match: ✅ PASS
LAYER 3: PERFORMANCE (Holding Period: 5 days)
Metric               | Engine       | Manual       | Status
-----------------------------------------------------------------------------------------------
Gain                 |    -0.006771 |    -0.006771 | ✅ PASS
Sharpe               |    -2.486459 |    -2.486459 | ✅ PASS
Sharpe (ATRP)        |    -0.051518 |    -0.051518 | ✅ PASS
Sharpe (TRP)         |    -0.060649 |    -0.060649 | ✅ PASS
===============================================================================================

In [16]:
audit = SA.verify_analyzer_long(my_analyzer, n_tickers=5)

=====================================================================================
🛡️  STARTING NUCLEAR AUDIT | 2025-12-10 | Sharpe (ATRP)
*************************************************************************************
⚠️  ASSUMPTION: Verification logic is independent, but trusts Engine source DataFrames
    (engine.features_df, engine.df_close, and debug['portfolio_raw_components'])
*************************************************************************************
=====================================================================================
📝 1. PERFORMANCE RECONCILIATION

Period                     Full Holding Lookback
Entity    Metric
Benchmark Gain           ✅ PASS  ✅ PASS   ✅ PASS
          Sharpe         ✅ PASS  ✅ PASS   ✅ PASS
          Sharpe (ATRP)  ✅ PASS  ✅ PASS   ✅ PASS
          Sharpe (TRP)   ✅ PASS  ✅ PASS   ✅ PASS
Group     Gain           ✅ PASS  ✅ PASS   ✅ PASS
          Sharpe         ✅ PASS  ✅ PASS   ✅ PASS
          Sharpe (ATRP)  ✅ PASS  ✅ PASS   ✅ PASS
          Sharpe (TRP)   ✅ PASS  ✅ PASS   ✅ PASS

=====================================================================================
📝 2. SURVIVAL AUDIT
   Survival Integrity: ✅ PASS (Engine: 937 vs Auditor: 937)

=====================================================================================
📝 3. UNIVERSAL SELECTION AUDIT | Strategy: Sharpe (ATRP)
   Scope: Evaluated 937 candidates (Full Universe).
   Result: 937 PASSED | 0 FAILED
   All scores match registry math. Sharpe (ATRP) results of the first 5 tickers

=====================================================================================

In [17]:
# Takes 4 seconds to run, checks selected tickers from analyzer1
SA.audit_feature_engineering_integrity(my_analyzer, mode="last_run")

===============================================================================================
🕵️  NUCLEAR FEATURE AUDIT | Mode: LAST_RUN | Tickers: 2
===============================================================================================
STEP 1: BOUNDARY INTEGRITY   | MultiIndex Isolation Check | ✅ PASS
STEP 2: SHADOW CALCULATIONS  | Re-computing metrics... DONE (0.18s)

Metric               | Max Delta    | Correlation  | Status
-------------------------------------------------------------------------------------
Ret_1d               |   0.0000e+00 |     1.000000 | ✅ PASS
ATR                  |   0.0000e+00 |     1.000000 | ✅ PASS
ATRP                 |   0.0000e+00 |     1.000000 | ✅ PASS
TRP                  |   0.0000e+00 |     1.000000 | ✅ PASS
RSI                  |   0.0000e+00 |     1.000000 | ✅ PASS
Mom_21               |   0.0000e+00 |     1.000000 | ✅ PASS
Consistency          |   0.0000e+00 |     1.000000 | ✅ PASS
DD_21                |   0.0000e+00 |     1.000000 | ✅ PASS
RollingStalePct      |   0.0000e+00 |     1.000000 | ✅ PASS
RollMedDollarVol     |   0.0000e+00 |     1.000000 | ✅ PASS
RollingSameVolCount  |   0.0000e+00 |     1.000000 | ✅ PASS
Macro_Vix_Signals    | N/A          | N/A          | ✅ LIVE
===============================================================================================

### Audit Every Tickers in features_df, Takes 3 minutes

In [18]:
# # Takes 3 minutes to run, checks every tickers ~1580 tickers
# SA.audit_feature_engineering_integrity(my_analyzer, mode="system")

### Export Ticker's OHLCV and Features

In [19]:
f_name_excel = OUTPUT_DIR / "Audit_Verification_Report.xlsx"

SU.export_audit_to_excel(audit_pack=my_analyzer.last_run, filename=f_name_excel)

📂 [EXCEL AUDIT] Building full transparency report: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\Audit_Verification_Report.xlsx
✨ Audit Report Complete: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\Audit_Verification_Report.xlsx

WindowsPath('C:/Users/ping/Files_win10/python/py311/stocks/notebooks_RLVR/output/Audit_Verification_Report.xlsx')

In [20]:
f_name_csv = OUTPUT_DIR / "all_tickers_data_stacked.csv"

# Single call replaces your 3 cells
file_path = SU.export_last_run_tickers_data_to_csv(
    analyzer=my_analyzer,
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    filename=f_name_csv,
)

Creating combined dictionary for 3 ticker(s)
Date range: 2025-11-10 00:00:00 to 2025-12-18 00:00:00
============================================================
Data retrieved for 3 ticker(s) from 2025-11-10 00:00:00 to 2025-12-18 00:00:00
Total rows: 84
Date range in data: 2025-11-10 00:00:00 to 2025-12-18 00:00:00
  TD: 28 rows
  ONON: 28 rows
  SPY: 28 rows
Features data retrieved for 3 ticker(s) from 2025-11-10 00:00:00 to 2025-12-18 00:00:00
Total rows: 84
Date range in data: 2025-11-10 00:00:00 to 2025-12-18 00:00:00
Available features: ATR, ATRP, TRP, RSI, Mom_21, Consistency, IR_63, Beta_63, DD_21, Ret_1d, RollingStalePct, RollMedDollarVol, RollingSameVolCount
  TD: 28 rows
  ONON: 28 rows
  SPY: 28 rows

Processing TD...
  ✓ Successfully combined data
  OHLCV shape: (28, 5)
  Features shape: (28, 13)
  Combined shape: (28, 18)
  Date range: 2025-11-10 00:00:00 to 2025-12-18 00:00:00

Processing ONON...
  ✓ Successfully combined data
  OHLCV shape: (28, 5)
  Features shape: (28, 13)
  Combined shape: (28, 18)
  Date range: 2025-11-10 00:00:00 to 2025-12-18 00:00:00

Processing SPY...
  ✓ Successfully combined data
  OHLCV shape: (28, 5)
  Features shape: (28, 13)
  Combined shape: (28, 18)
  Date range: 2025-11-10 00:00:00 to 2025-12-18 00:00:00

============================================================
SUMMARY
============================================================
Total tickers processed: 3
Tickers with combined data: 3

Ticker details:
  TD: (28, 18) - 2025-11-10 00:00:00 to 2025-12-18 00:00:00
    Columns: 18
  ONON: (28, 18) - 2025-11-10 00:00:00 to 2025-12-18 00:00:00
    Columns: 18
  SPY: (28, 18) - 2025-11-10 00:00:00 to 2025-12-18 00:00:00
    Columns: 18
TD:
              Adj Open    Adj High     Adj Low   Adj Close   Volume        ATR       ATRP        TRP         RSI     Mom_21  Consistency      IR_63    Beta_63       DD_21      Ret_1d  RollingStalePct   RollMedDollarVol  RollingSameVolCount
Date
2025-11-10 81.17000000 81.28000000 80.51000000 81.14000000  1537700 1.11764928 0.01377433 0.00948977 55.12213694 0.03600613   0.60000000 0.06568396 0.56846189 -0.01910058  0.00296663       0.00000000 112856493.73324999           0.00000000
2025-11-11 81.25000000 81.99000000 81.25000000 81.60000000  2429300 1.09853148 0.01346240 0.01041667 57.94840670 0.03461392   0.80000000 0.05048714 0.55816633 -0.01353965  0.00566921       0.00000000 112856493.73324999           0.00000000
2025-11-12 81.80000000 82.93000000 81.80000000 82.74000000  1724400 1.11506494 0.01347673 0.01607445 63.99935482 0.04219675   0.80000000 0.06935423 0.55618794  0.00000000  0.01397059       0.00000000 112972429.22825001           0.00000000
2025-11-13 82.74000000 82.94000000 81.05000000 81.35000000  1740900 1.17041745 0.01438743 0.02323294 53.82868853 0.01194178   0.80000000 0.07595168 0.59620031 -0.01679961 -0.01679961       0.00000000 113368228.17210001           0.00000000
2025-11-14 81.14000000 81.48000000 80.23000000 81.35000000  2446900 1.17610192 0.01445731 0.01536570 53.82868853 0.03340955   0.60000000 0.07792022 0.59578863 -0.01679961  0.00000000       0.00000000 113527830.00000000           0.00000000
2025-11-17 81.27000000 82.11000000 81.07000000 81.45000000  2006900 1.16638035 0.01432020 0.01276857 54.43288737 0.02853896   0.60000000 0.09727792 0.56776336 -0.01559101  0.00122926       0.00000000 114501442.50000000           0.00000000
2025-11-18 81.12000000 82.47000000 80.53000000 82.26000000  1636400 1.22163890 0.01485095 0.02358376 59.10147025 0.02992363   0.60000000 0.11062919 0.53778396 -0.00580131  0.00994475       0.00000000 115047627.91620001           0.00000000
2025-11-19 82.08000000 82.22000000 81.30000000 81.59000000  1428000 1.20295040 0.01474385 0.01176615 54.15863912 0.01530612   0.40000000 0.08747429 0.52662347 -0.01389896 -0.00814491       0.00000000 115143410.41619998           0.00000000
2025-11-20 82.01000000 82.43000000 80.97000000 81.32000000  1489000 1.22131109 0.01501858 0.01795376 52.26177893 0.00581323   0.40000000 0.11194714 0.50824929 -0.01716219 -0.00330923       0.00000000 115158664.99999999           0.00000000
2025-11-21 81.73000000 82.18000000 81.03000000 82.05000000  1628700 1.21621744 0.01482288 0.01401584 56.67956025 0.01421508   0.60000000 0.11638334 0.50480473 -0.00833938  0.00897688       0.00000000 115233002.00000000           0.00000000
2025-11-24 81.98000000 82.89000000 81.82000000 82.70000000  2046300 1.20577334 0.01458009 0.01293833 60.21043532 0.02098765   0.60000000 0.08444802 0.48505039 -0.00048344  0.00792200       0.00000000 115403808.00000000           0.00000000
2025-11-25 82.50000000 83.02000000 81.94000000 82.31000000  2191800 1.19678953 0.01454003 0.01312113 57.19807551 0.00833027   0.40000000 0.04914782 0.45687518 -0.00519700 -0.00471584       0.00000000 115562541.61080000           0.00000000
2025-11-26 82.69000000 83.57000000 82.44000000 83.44000000  2492100 1.20130456 0.01439723 0.01510067 62.97766973 0.00870406   0.60000000 0.15171075 0.50548727  0.00000000  0.01372859       0.00000000 115692425.61080001           0.00000000
2025-11-28 83.55000000 84.06000000 83.37000000 83.93000000   654200 1.16478281 0.01387803 0.00822114 65.17372562 0.02629005   0.80000000 0.10137058 0.56757096  0.00000000  0.00587248       0.00000000 115562541.61080000           0.00000000
2025-12-01 83.95000000 84.23000000 83.02000000 83.50000000  2457800 1.16801261 0.01398817 0.01449102 61.71416040 0.01941155   0.60000000 0.10167877 0.56154985 -0.00512332 -0.00512332       0.00000000 115562541.61080000           0.00000000
2025-12-02 83.82000000 84.55000000 83.00000000 84.55000000  4317300 1.19529742 0.01413717 0.01833235 66.40384919 0.02946548   0.60000000 0.12371830 0.56382682  0.00000000  0.01257485       0.00000000 115692425.61080001           0.00000000
2025-12-03 84.65000000 85.11000000 84.16000000 84.37000000  2112000 1.17777618 0.01395966 0.01125993 64.93541212 0.02978152   0.60000000 0.13463940 0.57658997 -0.00212892 -0.00212892       0.00000000 115933874.72640002           0.00000000
2025-12-04 84.67000000 86.34000000 83.58000000 86.08000000  3954900 1.29079216 0.01499526 0.03206320 71.40480390 0.06878570   0.60000000 0.16769112 0.57211691  0.00000000  0.02026787       0.00000000 116121301.81389999           0.00000000
2025-12-05 86.85000000 88.45000000 86.77000000 88.32000000  4420500 1.36787844 0.01548775 0.02683424 77.31033960 0.09496653   0.60000000 0.20038956 0.57804936  0.00000000  0.02602230       0.00000000 116121301.81389999           0.00000000
2025-12-08 88.41000000 88.79000000 88.06000000 88.13000000  3922300 1.32231569 0.01500415 0.00828322 75.87888549 0.09573542   0.60000000 0.19141397 0.57886563 -0.00215127 -0.00215127       0.00000000 116121301.81389999           0.00000000
2025-12-09 88.26000000 89.24000000 88.19000000 89.14000000  2627200 1.30715029 0.01466401 0.01245232 78.19060878 0.10185414   0.60000000 0.20424650 0.57248944  0.00000000  0.01146034       0.00000000 116121301.81389999           0.00000000
2025-12-10 89.46000000 91.52000000 89.44000000 91.26000000  2848500 1.38378241 0.01516308 0.02607933 82.07407274 0.12472270   0.80000000 0.22214856 0.58936441  0.00000000  0.02378281       0.00000000 116121301.81389999           0.00000000
2025-12-11 91.50000000 91.85000000 90.82000000 91.83000000  2345400 1.35851224 0.01479377 0.01121638 82.95298930 0.12536765   0.80000000 0.22916443 0.58962109  0.00000000  0.00624589       0.00000000 116121301.81389999           0.00000000
2025-12-12 91.95000000 92.11000000 90.91000000 91.42000000  1734800 1.34718993 0.01473627 0.01312623 79.91768257 0.10490694   0.60000000 0.22981266 0.58401263 -0.00446477 -0.00446477       0.00000000 116121301.81389999           0.00000000
2025-12-15 91.71000000 92.24000000 91.47000000 92.04000000  1542200 1.30953351 0.01422787 0.00890917 81.04706133 0.13140750   0.80000000 0.23599346 0.58179195  0.00000000  0.00678189       0.00000000 116121301.81389999           0.00000000
2025-12-16 91.91000000 92.23000000 91.64000000 91.65000000  1259200 1.25813826 0.01372764 0.00643753 78.07277348 0.12661340   0.60000000 0.21993269 0.58858573 -0.00423729 -0.00423729       0.00000000 116121301.81389999           0.00000000
2025-12-17 91.79000000 91.85000000 90.37000000 91.15000000  1880300 1.27398553 0.01397680 0.01623697 74.30773162 0.11909147   0.40000000 0.23868422 0.59771072 -0.00966971 -0.00545554       0.00000000 116325847.08750001           0.00000000
2025-12-18 91.76000000 93.08000000 91.50000000 92.52000000  1957300 1.32084370 0.01427630 0.02086035 77.50830400 0.12472648   0.40000000 0.25519033 0.61577951  0.00000000  0.01503017       0.00000000 117022129.23260000           0.00000000

ONON:
              Adj Open    Adj High     Adj Low   Adj Close    Volume        ATR       ATRP        TRP         RSI      Mom_21  Consistency       IR_63    Beta_63       DD_21      Ret_1d  RollingStalePct   RollMedDollarVol  RollingSameVolCount
Date
2025-11-10 35.81000000 35.89000000 34.40500000 34.96000000  10173300 1.52237620 0.04354623 0.04247712 26.02145594 -0.16483516   0.00000000 -0.27908438 1.09783248 -0.19130234 -0.00114286       0.00000000 216938212.50000000           0.00000000
2025-11-11 35.82000000 35.97000000 34.86500000 35.18000000  12342600 1.49256362 0.04242648 0.03140989 27.68077625 -0.18128927   0.20000000 -0.25427862 1.12684198 -0.18621328  0.00629291       0.00000000 216938212.50000000           0.00000000
2025-11-12 43.84000000 44.87000000 41.01000000 41.51000000  48483000 2.07809479 0.05006251 0.23343773 57.33400706 -0.01588431   0.40000000 -0.04973118 1.07697623 -0.03978718  0.17993178       0.00000000 216938212.50000000           0.00000000
2025-11-13 42.29000000 44.73000000 41.45500000 42.40000000  19693200 2.16358802 0.05102802 0.07724057 59.82809450  0.02316602   0.60000000 -0.04421671 0.88806182 -0.01919963  0.02144062       0.00000000 216938212.50000000           0.00000000
2025-11-14 42.40000000 44.14000000 42.01000000 42.40000000  13488300 2.16118887 0.05097144 0.05023585 59.82809450  0.01000476   0.60000000 -0.04288148 0.88730781 -0.01919963  0.00000000       0.00000000 216938212.50000000           0.00000000
2025-11-17 42.00000000 42.89500000 41.08000000 41.40000000   7372700 2.13646109 0.05160534 0.04384058 55.59330642 -0.01004304   0.60000000 -0.05079108 0.93300658 -0.04233171 -0.02358491       0.00000000 216938212.50000000           0.00000000
2025-11-18 41.68000000 42.70500000 41.23500000 42.66000000   6769600 2.08885673 0.04896523 0.03445851 59.48466436  0.02869544   0.60000000 -0.03414333 0.83608262 -0.01318529  0.03043478       0.00000000 217790518.50000000           0.00000000
2025-11-19 42.72000000 43.46000000 42.18000000 43.30000000   5979900 2.03108125 0.04690719 0.02956120 61.33790672  0.00908879   0.60000000 -0.02310738 0.83347066  0.00000000  0.01500234       0.00000000 219063807.00000000           0.00000000
2025-11-20 42.97000000 43.56800000 41.33000000 41.42000000   8101400 2.04586116 0.04939307 0.05403187 53.58415761 -0.02010882   0.40000000 -0.05223524 0.82753316 -0.04341801 -0.04341801       0.00000000 221924930.00000000           0.00000000
2025-11-21 41.57000000 42.07000000 40.45000000 41.28000000   6728200 2.01544251 0.04882370 0.03924419 53.04639140 -0.04510756   0.40000000 -0.05069821 0.77844874 -0.04665127 -0.00338001       0.00000000 223774361.00000000           0.00000000
2025-11-24 41.05000000 41.60000000 40.63000000 40.79000000   5129900 1.94076804 0.04757951 0.02378034 51.11290812 -0.02182254   0.40000000 -0.05728689 0.70518490 -0.05796767 -0.01187016       0.00000000 223774361.00000000           0.00000000
2025-11-25 40.75000000 42.85000000 40.26000000 41.76000000   6251700 1.98714175 0.04758481 0.06202107 54.63774895 -0.01066098   0.40000000 -0.04874787 0.74843975 -0.03556582  0.02378034       0.00000000 223774361.00000000           0.00000000
2025-11-26 41.97000000 43.44000000 41.51000000 43.19000000   4833600 1.98306020 0.04591480 0.04468627 59.29704430  0.04906485   0.40000000 -0.02641037 0.80787157 -0.00254042  0.03424330       0.00000000 221924930.00000000           0.00000000
2025-11-28 43.34000000 44.24000000 43.28000000 43.99000000   3016900 1.91641304 0.04356474 0.02386906 61.66904038  0.11962331   0.60000000 -0.02839499 0.85601609  0.00000000  0.01852281       0.00000000 219063807.00000000           0.00000000
2025-12-01 43.52000000 45.38000000 43.17000000 44.68000000   9109500 1.93738354 0.04336131 0.04946285 63.63732386  0.20010744   0.80000000 -0.01862086 0.82682855  0.00000000  0.01568538       0.00000000 221924930.00000000           0.00000000
2025-12-02 45.00000000 46.05000000 44.87000000 45.15000000   5838100 1.89685614 0.04201232 0.03034330 64.95730844  0.21534320   1.00000000 -0.01165703 0.83367442  0.00000000  0.01051925       0.00000000 223774361.00000000           0.00000000
2025-12-03 45.34000000 47.58000000 45.15000000 47.07000000   6646800 1.93493785 0.04110767 0.05162524 69.78293160  0.29100384   1.00000000 -0.00184971 0.81844408  0.00000000  0.04252492       0.00000000 224161446.00000000           0.00000000
2025-12-04 47.28000000 47.87000000 46.30000000 46.51000000   3588700 1.90887086 0.04104216 0.03375618 66.88967779  0.28480663   0.80000000 -0.00384271 0.80942366 -0.01189717 -0.01189717       0.00000000 224161446.00000000           0.00000000
2025-12-05 46.57000000 48.16000000 46.57000000 48.14000000   5855100 1.89038008 0.03926839 0.03427503 70.69788486  0.33425721   0.80000000  0.01720038 0.82194206  0.00000000  0.03504623       0.00000000 224476113.50000000           0.00000000
2025-12-08 47.84000000 47.89900000 45.83000000 47.02000000   5629500 1.92035293 0.04084119 0.04912803 65.15283369  0.32413405   0.60000000  0.01718612 0.85295358 -0.02326548 -0.02326548       0.00000000 226434529.50000000           0.00000000
2025-12-09 47.10000000 47.75000000 46.54000000 47.31000000   2880200 1.86961344 0.03951836 0.02557599 65.89865586  0.35171429   0.60000000  0.03962239 0.87175515 -0.01724138  0.00616759       0.00000000 226434529.50000000           0.00000000
2025-12-10 47.70000000 49.52000000 47.59500000 48.72000000   6914600 1.89392676 0.03887370 0.04536125 69.33514190  0.39359268   0.60000000  0.04989471 0.90444775  0.00000000  0.02980342       0.00000000 228318080.00000000           0.00000000
2025-12-11 48.20000000 49.57500000 47.80100000 49.50000000   5540300 1.88536057 0.03808809 0.03583838 71.07183902  0.40704946   0.80000000  0.06121591 0.90607376  0.00000000  0.01600985       0.00000000 228318080.00000000           0.00000000
2025-12-12 49.48000000 50.02000000 48.57000000 48.76000000   3672100 1.85426338 0.03802837 0.02973749 67.18431725  0.17465671   0.60000000  0.06438122 0.94332781 -0.01494949 -0.01494949       0.00000000 228318080.00000000           0.00000000
2025-12-15 48.83000000 48.90000000 47.23000000 47.79000000   5054600 1.84110171 0.03852483 0.03494455 62.36854859  0.12712264   0.60000000  0.05034511 0.95861818 -0.03454545 -0.01989336       0.00000000 228562637.00000000           0.00000000
2025-12-16 48.00000000 49.54000000 47.94000000 48.29000000   4705600 1.83459445 0.03799119 0.03623939 63.80862567  0.13891509   0.60000000  0.04690193 0.95747313 -0.02444444  0.01046244       0.00000000 228562637.00000000           0.00000000
2025-12-17 48.21000000 48.61500000 47.73000000 48.10000000   3374900 1.76676627 0.03673111 0.01839917 62.82476428  0.16183575   0.40000000  0.03982487 0.91956357 -0.02828283 -0.00393456       0.00000000 228562637.00000000           0.00000000
2025-12-18 48.51000000 49.78000000 48.27000000 48.46000000   4135600 1.76056868 0.03633035 0.03466777 63.95870031  0.13595874   0.40000000  0.03960100 0.91877460 -0.02101010  0.00748441       0.00000000 228562637.00000000           0.00000000

SPY:
               Adj Open     Adj High      Adj Low    Adj Close     Volume        ATR       ATRP        TRP         RSI      Mom_21  Consistency      IR_63    Beta_63       DD_21      Ret_1d  RollingStalePct     RollMedDollarVol  RollingSameVolCount
Date
2025-11-10 673.40600000 678.31800000 671.20800000 677.58200000   76274749 7.52756617 0.01110945 0.01645115 57.80394450  0.04352071   0.60000000 0.00000000 1.00000000 -0.00865548  0.01560470       0.00000000 39997929136.84100342           0.00000000
2025-11-11 676.10000000 679.70000000 674.88700000 679.13300000   59289082 7.33366859 0.01079857 0.00708698 58.93538713  0.03010378   0.80000000 0.00000000 1.00000000 -0.00638627  0.00228902       0.00000000 40052461674.36350250           0.00000000
2025-11-12 680.91300000 681.08200000 677.09500000 679.51100000   62667302 7.09462083 0.01044077 0.00586745 59.22236434  0.03193714   0.80000000 0.00000000 1.00000000 -0.00583323  0.00055659       0.00000000 40144396732.18600464           0.00000000
2025-11-13 676.64700000 677.00500000 666.72400000 668.23500000  104046879 7.50121935 0.01122542 0.01913548 48.36429751  0.01032803   0.80000000 0.00000000 1.00000000 -0.02233072 -0.01659429       0.00000000 40246325233.69650269           0.00000000
2025-11-14 661.61300000 671.83500000 659.51500000 668.12600000   97398147 7.84541796 0.01174242 0.01843964 48.27216357  0.01708936   0.60000000 0.00000000 1.00000000 -0.02249019 -0.00016312       0.00000000 40318360299.15550232           0.00000000
2025-11-17 665.90800000 669.89600000 658.42100000 661.90100000   90971156 8.10467382 0.01224454 0.01733643 43.20957850  0.00192695   0.40000000 0.00000000 1.00000000 -0.03159775 -0.00931710       0.00000000 40460784009.71849823           0.00000000
2025-11-18 658.35100000 661.35400000 652.14700000 656.34300000  115119282 8.22248284 0.01252772 0.01486113 39.25140649 -0.01671313   0.20000000 0.00000000 1.00000000 -0.03972945 -0.00839703       0.00000000 40579610790.84249878           0.00000000
2025-11-19 657.03900000 663.56200000 655.02000000 658.87800000   95242238 8.24530549 0.01251416 0.01296446 41.86706468 -0.01290059   0.20000000 0.00000000 1.00000000 -0.03602059  0.00386231       0.00000000 40579610790.84249878           0.00000000
2025-11-20 669.10000000 671.73500000 648.19900000 648.83600000  166234678 9.33749796 0.01439115 0.03627419 35.37013183 -0.02286531   0.20000000 0.00000000 1.00000000 -0.05071266 -0.01524106       0.00000000 40666676972.36549377           0.00000000
2025-11-21 651.34100000 660.78700000 647.16500000 655.29900000  124662004 9.64353382 0.01471623 0.02078746 41.64640847 -0.01895032   0.40000000 0.00000000 1.00000000 -0.04125689  0.00996091       0.00000000 40768281216.02600098           0.00000000
2025-11-24 658.93800000 666.26600000 657.84400000 664.94400000   80895913 9.73806711 0.01464494 0.01649312 49.52420462 -0.01258063   0.60000000 0.00000000 1.00000000 -0.02714565  0.01471847       0.00000000 40830623217.19699860           0.00000000
2025-11-25 664.84400000 672.38200000 660.71800000 671.19800000   81538749 9.87563375 0.01471344 0.01737788 53.87266795 -0.01491429   0.80000000 0.00000000 1.00000000 -0.01799566  0.00940530       0.00000000 40854046084.34149933           0.00000000
2025-11-26 673.79300000 677.84000000 672.88900000 675.83200000   72288877 9.64465991 0.01427079 0.00982789 56.83968526 -0.01074110   0.80000000 0.00000000 1.00000000 -0.01121583  0.00690407       0.00000000 40910959473.83700562           0.00000000
2025-11-28 677.00500000 679.79900000 676.64700000 679.52100000   49492213 9.23911277 0.01359651 0.00583794 59.09533613 -0.00581860   1.00000000 0.00000000 1.00000000  0.00000000  0.00545846       0.00000000 40910959473.83700562           0.00000000
2025-12-01 674.96700000 679.12300000 674.89700000 676.41800000   61549682 8.90946186 0.01317153 0.00683601 56.42411503  0.00064647   0.80000000 0.00000000 1.00000000 -0.00456645 -0.00456645       0.00000000 41031561447.38400269           0.00000000
2025-12-02 678.05900000 679.94800000 675.48400000 677.67100000   63312257 8.59192887 0.01267861 0.00658727 57.26416060 -0.00077706   0.80000000 0.00000000 1.00000000 -0.00272251  0.00185240       0.00000000 41141648499.44550323           0.00000000

In [21]:
SU.create_combined_dict(
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    tickers=my_analyzer.last_run.tickers,
    date_start=my_analyzer.last_run.start_date,
    date_end=analyzer1.last_run.holding_end_date,
    verbose=False,
)

{'TD':             Adj Open  Adj High  Adj Low  Adj Close   Volume     ATR    ATRP     TRP      RSI  Mom_21  Consistency   IR_63  Beta_63   DD_21  Ret_1d  RollingStalePct  RollMedDollarVol  RollingSameVolCount
 Date
 2025-11-10     81.17     81.28    80.51      81.14  1537700  1.1176  0.0138  0.0095  55.1221  0.0360          0.6  0.0657   0.5685 -0.0191  0.0030              0.0        1.1286e+08                  0.0
 2025-11-11     81.25     81.99    81.25      81.60  2429300  1.0985  0.0135  0.0104  57.9484  0.0346          0.8  0.0505   0.5582 -0.0135  0.0057              0.0        1.1286e+08                  0.0
 2025-11-12     81.80     82.93    81.80      82.74  1724400  1.1151  0.0135  0.0161  63.9994  0.0422          0.8  0.0694   0.5562  0.0000  0.0140              0.0        1.1297e+08                  0.0
 2025-11-13     82.74     82.94    81.05      81.35  1740900  1.1704  0.0144  0.0232  53.8287  0.0119          0.8  0.0760   0.5962 -0.0168 -0.0168              0.0        1.1337e+08                  0.0
 2025-11-14     81.14     81.48    80.23      81.35  2446900  1.1761  0.0145  0.0154  53.8287  0.0334          0.6  0.0779   0.5958 -0.0168  0.0000              0.0        1.1353e+08                  0.0
 2025-11-17     81.27     82.11    81.07      81.45  2006900  1.1664  0.0143  0.0128  54.4329  0.0285          0.6  0.0973   0.5678 -0.0156  0.0012              0.0        1.1450e+08                  0.0
 2025-11-18     81.12     82.47    80.53      82.26  1636400  1.2216  0.0149  0.0236  59.1015  0.0299          0.6  0.1106   0.5378 -0.0058  0.0099              0.0        1.1505e+08                  0.0
 2025-11-19     82.08     82.22    81.30      81.59  1428000  1.2030  0.0147  0.0118  54.1586  0.0153          0.4  0.0875   0.5266 -0.0139 -0.0081              0.0        1.1514e+08                  0.0
 2025-11-20     82.01     82.43    80.97      81.32  1489000  1.2213  0.0150  0.0180  52.2618  0.0058          0.4  0.1119   0.5082 -0.0172 -0.0033              0.0        1.1516e+08                  0.0
 2025-11-21     81.73     82.18    81.03      82.05  1628700  1.2162  0.0148  0.0140  56.6796  0.0142          0.6  0.1164   0.5048 -0.0083  0.0090              0.0        1.1523e+08                  0.0
 2025-11-24     81.98     82.89    81.82      82.70  2046300  1.2058  0.0146  0.0129  60.2104  0.0210          0.6  0.0844   0.4851 -0.0005  0.0079              0.0        1.1540e+08                  0.0
 2025-11-25     82.50     83.02    81.94      82.31  2191800  1.1968  0.0145  0.0131  57.1981  0.0083          0.4  0.0491   0.4569 -0.0052 -0.0047              0.0        1.1556e+08                  0.0
 2025-11-26     82.69     83.57    82.44      83.44  2492100  1.2013  0.0144  0.0151  62.9777  0.0087          0.6  0.1517   0.5055  0.0000  0.0137              0.0        1.1569e+08                  0.0
 2025-11-28     83.55     84.06    83.37      83.93   654200  1.1648  0.0139  0.0082  65.1737  0.0263          0.8  0.1014   0.5676  0.0000  0.0059              0.0        1.1556e+08                  0.0
 2025-12-01     83.95     84.23    83.02      83.50  2457800  1.1680  0.0140  0.0145  61.7142  0.0194          0.6  0.1017   0.5615 -0.0051 -0.0051              0.0        1.1556e+08                  0.0
 2025-12-02     83.82     84.55    83.00      84.55  4317300  1.1953  0.0141  0.0183  66.4038  0.0295          0.6  0.1237   0.5638  0.0000  0.0126              0.0        1.1569e+08                  0.0
 2025-12-03     84.65     85.11    84.16      84.37  2112000  1.1778  0.0140  0.0113  64.9354  0.0298          0.6  0.1346   0.5766 -0.0021 -0.0021              0.0        1.1593e+08                  0.0
 2025-12-04     84.67     86.34    83.58      86.08  3954900  1.2908  0.0150  0.0321  71.4048  0.0688          0.6  0.1677   0.5721  0.0000  0.0203              0.0        1.1612e+08                  0.0
 2025-12-05     86.85     88.45    86.77      88.32  4420500  1.3679  0.0155  0.0268  77.3103  0.0950          0.6  0.2004   0.5780  0.0000  0.0260              0.0        1.1612e+08                  0.0
 2025-12-08     88.41     88.79    88.06      88.13  3922300  1.3223  0.0150  0.0083  75.8789  0.0957          0.6  0.1914   0.5789 -0.0022 -0.0022              0.0        1.1612e+08                  0.0
 2025-12-09     88.26     89.24    88.19      89.14  2627200  1.3072  0.0147  0.0125  78.1906  0.1019          0.6  0.2042   0.5725  0.0000  0.0115              0.0        1.1612e+08                  0.0
 2025-12-10     89.46     91.52    89.44      91.26  2848500  1.3838  0.0152  0.0261  82.0741  0.1247          0.8  0.2221   0.5894  0.0000  0.0238              0.0        1.1612e+08                  0.0
 2025-12-11     91.50     91.85    90.82      91.83  2345400  1.3585  0.0148  0.0112  82.9530  0.1254          0.8  0.2292   0.5896  0.0000  0.0062              0.0        1.1612e+08                  0.0
 2025-12-12     91.95     92.11    90.91      91.42  1734800  1.3472  0.0147  0.0131  79.9177  0.1049          0.6  0.2298   0.5840 -0.0045 -0.0045              0.0        1.1612e+08                  0.0
 2025-12-15     91.71     92.24    91.47      92.04  1542200  1.3095  0.0142  0.0089  81.0471  0.1314          0.8  0.2360   0.5818  0.0000  0.0068              0.0        1.1612e+08                  0.0
 2025-12-16     91.91     92.23    91.64      91.65  1259200  1.2581  0.0137  0.0064  78.0728  0.1266          0.6  0.2199   0.5886 -0.0042 -0.0042              0.0        1.1612e+08                  0.0
 2025-12-17     91.79     91.85    90.37      91.15  1880300  1.2740  0.0140  0.0162  74.3077  0.1191          0.4  0.2387   0.5977 -0.0097 -0.0055              0.0        1.1633e+08                  0.0
 2025-12-18     91.76     93.08    91.50      92.52  1957300  1.3208  0.0143  0.0209  77.5083  0.1247          0.4  0.2552   0.6158  0.0000  0.0150              0.0        1.1702e+08                  0.0,
 'ONON':             Adj Open  Adj High  Adj Low  Adj Close    Volume     ATR    ATRP     TRP      RSI  Mom_21  Consistency   IR_63  Beta_63   DD_21  Ret_1d  RollingStalePct  RollMedDollarVol  RollingSameVolCount
 Date
 2025-11-10     35.81    35.890   34.405      34.96  10173300  1.5224  0.0435  0.0425  26.0215 -0.1648          0.0 -0.2791   1.0978 -0.1913 -0.0011              0.0        2.1694e+08                  0.0
 2025-11-11     35.82    35.970   34.865      35.18  12342600  1.4926  0.0424  0.0314  27.6808 -0.1813          0.2 -0.2543   1.1268 -0.1862  0.0063              0.0        2.1694e+08                  0.0
 2025-11-12     43.84    44.870   41.010      41.51  48483000  2.0781  0.0501  0.2334  57.3340 -0.0159          0.4 -0.0497   1.0770 -0.0398  0.1799              0.0        2.1694e+08                  0.0
 2025-11-13     42.29    44.730   41.455      42.40  19693200  2.1636  0.0510  0.0772  59.8281  0.0232          0.6 -0.0442   0.8881 -0.0192  0.0214              0.0        2.1694e+08                  0.0
 2025-11-14     42.40    44.140   42.010      42.40  13488300  2.1612  0.0510  0.0502  59.8281  0.0100          0.6 -0.0429   0.8873 -0.0192  0.0000              0.0        2.1694e+08                  0.0
 2025-11-17     42.00    42.895   41.080      41.40   7372700  2.1365  0.0516  0.0438  55.5933 -0.0100          0.6 -0.0508   0.9330 -0.0423 -0.0236              0.0        2.1694e+08                  0.0
 2025-11-18     41.68    42.705   41.235      42.66   6769600  2.0889  0.0490  0.0345  59.4847  0.0287          0.6 -0.0341   0.8361 -0.0132  0.0304              0.0        2.1779e+08                  0.0
 2025-11-19     42.72    43.460   42.180      43.30   5979900  2.0311  0.0469  0.0296  61.3379  0.0091          0.6 -0.0231   0.8335  0.0000  0.0150              0.0        2.1906e+08                  0.0
 2025-11-20     42.97    43.568   41.330      41.42   8101400  2.0459  0.0494  0.0540  53.5842 -0.0201          0.4 -0.0522   0.8275 -0.0434 -0.0434              0.0        2.2192e+08                  0.0
 2025-11-21     41.57    42.070   40.450      41.28   6728200  2.0154  0.0488  0.0392  53.0464 -0.0451          0.4 -0.0507   0.7784 -0.0467 -0.0034              0.0        2.2377e+08                  0.0
 2025-11-24     41.05    41.600   40.630      40.79   5129900  1.9408  0.0476  0.0238  51.1129 -0.0218          0.4 -0.0573   0.7052 -0.0580 -0.0119              0.0        2.2377e+08                  0.0
 2025-11-25     40.75    42.850   40.260      41.76   6251700  1.9871  0.0476  0.0620  54.6377 -0.0107          0.4 -0.0487   0.7484 -0.0356  0.0238              0.0        2.2377e+08                  0.0
 2025-11-26     41.97    43.440   41.510      43.19   4833600  1.9831  0.0459  0.0447  59.2970  0.0491          0.4 -0.0264   0.8079 -0.0025  0.0342              0.0        2.2192e+08                  0.0
 2025-11-28     43.34    44.240   43.280      43.99   3016900  1.9164  0.0436  0.0239  61.6690  0.1196          0.6 -0.0284   0.8560  0.0000  0.0185              0.0        2.1906e+08                  0.0
 2025-12-01     43.52    45.380   43.170      44.68   9109500  1.9374  0.0434  0.0495  63.6373  0.2001          0.8 -0.0186   0.8268  0.0000  0.0157              0.0        2.2192e+08                  0.0
 2025-12-02     45.00    46.050   44.870      45.15   5838100  1.8969  0.0420  0.0303  64.9573  0.2153          1.0 -0.0117   0.8337  0.0000  0.0105              0.0        2.2377e+08                  0.0
 2025-12-03     45.34    47.580   45.150      47.07   6646800  1.9349  0.0411  0.0516  69.7829  0.2910          1.0 -0.0018   0.8184  0.0000  0.0425              0.0        2.2416e+08                  0.0
 2025-12-04     47.28    47.870   46.300      46.51   3588700  1.9089  0.0410  0.0338  66.8897  0.2848          0.8 -0.0038   0.8094 -0.0119 -0.0119              0.0        2.2416e+08                  0.0
 2025-12-05     46.57    48.160   46.570      48.14   5855100  1.8904  0.0393  0.0343  70.6979  0.3343          0.8  0.0172   0.8219  0.0000  0.0350              0.0        2.2448e+08                  0.0
 2025-12-08     47.84    47.899   45.830      47.02   5629500  1.9204  0.0408  0.0491  65.1528  0.3241          0.6  0.0172   0.8530 -0.0233 -0.0233              0.0        2.2643e+08                  0.0
 2025-12-09     47.10    47.750   46.540      47.31   2880200  1.8696  0.0395  0.0256  65.8987  0.3517          0.6  0.0396   0.8718 -0.0172  0.0062              0.0        2.2643e+08                  0.0
 2025-12-10     47.70    49.520   47.595      48.72   6914600  1.8939  0.0389  0.0454  69.3351  0.3936          0.6  0.0499   0.9044  0.0000  0.0298              0.0        2.2832e+08                  0.0
 2025-12-11     48.20    49.575   47.801      49.50   5540300  1.8854  0.0381  0.0358  71.0718  0.4070          0.8  0.0612   0.9061  0.0000  0.0160              0.0        2.2832e+08                  0.0
 2025-12-12     49.48    50.020   48.570      48.76   3672100  1.8543  0.0380  0.0297  67.1843  0.1747          0.6  0.0644   0.9433 -0.0149 -0.0149              0.0        2.2832e+08                  0.0
 2025-12-15     48.83    48.900   47.230      47.79   5054600  1.8411  0.0385  0.0349  62.3685  0.1271          0.6  0.0503   0.9586 -0.0345 -0.0199              0.0        2.2856e+08                  0.0
 2025-12-16     48.00    49.540   47.940      48.29   4705600  1.8346  0.0380  0.0362  63.8086  0.1389          0.6  0.0469   0.9575 -0.0244  0.0105              0.0        2.2856e+08                  0.0
 2025-12-17     48.21    48.615   47.730      48.10   3374900  1.7668  0.0367  0.0184  62.8248  0.1618          0.4  0.0398   0.9196 -0.0283 -0.0039              0.0        2.2856e+08                  0.0
 2025-12-18     48.51    49.780   48.270      48.46   4135600  1.7606  0.0363  0.0347  63.9587  0.1360          0.4  0.0396   0.9188 -0.0210  0.0075              0.0        2.2856e+08                  0.0}

In [22]:
_tic = "NVDA"
_start_date = "2025-03-12"
_end_date = "2026-03-12"
# print(features_df.loc[_tic][_start_date:_end_date])
print(features_df.loc[_tic].tail(10))
# features_df.loc[_tic][_start_date:_end_date][["Ret_1d", "Consistency"]]

               ATR    ATRP     TRP      RSI  Mom_21  Consistency   IR_63  Beta_63   DD_21  Ret_1d  RollingStalePct  RollMedDollarVol  RollingSameVolCount
Date
2026-03-09  6.4513  0.0353  0.0402  47.8271  0.0627          0.6  0.0139   2.1743 -0.0660  0.0272              0.0        3.0610e+10                  0.0
2026-03-10  6.3069  0.0341  0.0240  50.0459 -0.0035          0.8  0.0316   2.1737 -0.0552  0.0116              0.0        3.0610e+10                  0.0
2026-03-11  6.0828  0.0327  0.0170  51.3799 -0.0210          0.8  0.0212   2.1921 -0.0487  0.0069              0.0        3.0548e+10                  0.0
2026-03-12  5.9541  0.0325  0.0234  48.2240 -0.0286          0.6  0.0229   2.1141 -0.0635 -0.0155              0.0        3.0283e+10                  0.0
2026-03-13  5.9681  0.0331  0.0341  45.2320 -0.0515          0.6  0.0255   2.1677 -0.0782 -0.0158              0.0        3.0021e+10                  0.0
2026-03-16  6.1582  0.0336  0.0471  48.7510 -0.0198          0.6  0.0471   2.1643 -0.0630  0.0165              0.0        3.0021e+10                  0.0
2026-03-17  5.9840  0.0329  0.0204  47.3286 -0.0048          0.4  0.0586   2.1178 -0.0696 -0.0070              0.0        3.0021e+10                  0.0
2026-03-18  5.7745  0.0320  0.0169  45.6281 -0.0247          0.2  0.0557   2.0429 -0.0775 -0.0084              0.0        2.9967e+10                  0.0
2026-03-19  5.6913  0.0319  0.0258  43.5993 -0.0501          0.2  0.0391   2.0552 -0.0869 -0.0102              0.0        2.9967e+10                  0.0
2026-03-20  5.7733  0.0334  0.0396  37.8302 -0.0808          0.2  0.0474   2.0231 -0.1168 -0.0328              0.0        2.9967e+10                  0.0

In [23]:
# analyzer1.last_run.tickers
# analyzer1.last_run.start_date
# analyzer1.last_run.holding_end_date
_tic = analyzer1.last_run.tickers[0]
_start_date = analyzer1.last_run.start_date
_end_date = analyzer1.last_run.holding_end_date

In [24]:
result = SU.create_combined_dict(
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    tickers=[_tic],
    date_start=_start_date,
    date_end=_end_date,
    verbose=False,
)
print(f"ticker: {_tic}\n")
print(result[_tic])

ticker: TD

            Adj Open  Adj High  Adj Low  Adj Close   Volume     ATR    ATRP     TRP      RSI  Mom_21  Consistency   IR_63  Beta_63   DD_21  Ret_1d  RollingStalePct  RollMedDollarVol  RollingSameVolCount
Date
2025-11-10     81.17     81.28    80.51      81.14  1537700  1.1176  0.0138  0.0095  55.1221  0.0360          0.6  0.0657   0.5685 -0.0191  0.0030              0.0        1.1286e+08                  0.0
2025-11-11     81.25     81.99    81.25      81.60  2429300  1.0985  0.0135  0.0104  57.9484  0.0346          0.8  0.0505   0.5582 -0.0135  0.0057              0.0        1.1286e+08                  0.0
2025-11-12     81.80     82.93    81.80      82.74  1724400  1.1151  0.0135  0.0161  63.9994  0.0422          0.8  0.0694   0.5562  0.0000  0.0140              0.0        1.1297e+08                  0.0
2025-11-13     82.74     82.94    81.05      81.35  1740900  1.1704  0.0144  0.0232  53.8287  0.0119          0.8  0.0760   0.5962 -0.0168 -0.0168              0.0        1.1337e+08                  0.0
2025-11-14     81.14     81.48    80.23      81.35  2446900  1.1761  0.0145  0.0154  53.8287  0.0334          0.6  0.0779   0.5958 -0.0168  0.0000              0.0        1.1353e+08                  0.0
2025-11-17     81.27     82.11    81.07      81.45  2006900  1.1664  0.0143  0.0128  54.4329  0.0285          0.6  0.0973   0.5678 -0.0156  0.0012              0.0        1.1450e+08                  0.0
2025-11-18     81.12     82.47    80.53      82.26  1636400  1.2216  0.0149  0.0236  59.1015  0.0299          0.6  0.1106   0.5378 -0.0058  0.0099              0.0        1.1505e+08                  0.0
2025-11-19     82.08     82.22    81.30      81.59  1428000  1.2030  0.0147  0.0118  54.1586  0.0153          0.4  0.0875   0.5266 -0.0139 -0.0081              0.0        1.1514e+08                  0.0
2025-11-20     82.01     82.43    80.97      81.32  1489000  1.2213  0.0150  0.0180  52.2618  0.0058          0.4  0.1119   0.5082 -0.0172 -0.0033              0.0        1.1516e+08                  0.0
2025-11-21     81.73     82.18    81.03      82.05  1628700  1.2162  0.0148  0.0140  56.6796  0.0142          0.6  0.1164   0.5048 -0.0083  0.0090              0.0        1.1523e+08                  0.0
2025-11-24     81.98     82.89    81.82      82.70  2046300  1.2058  0.0146  0.0129  60.2104  0.0210          0.6  0.0844   0.4851 -0.0005  0.0079              0.0        1.1540e+08                  0.0
2025-11-25     82.50     83.02    81.94      82.31  2191800  1.1968  0.0145  0.0131  57.1981  0.0083          0.4  0.0491   0.4569 -0.0052 -0.0047              0.0        1.1556e+08                  0.0
2025-11-26     82.69     83.57    82.44      83.44  2492100  1.2013  0.0144  0.0151  62.9777  0.0087          0.6  0.1517   0.5055  0.0000  0.0137              0.0        1.1569e+08                  0.0
2025-11-28     83.55     84.06    83.37      83.93   654200  1.1648  0.0139  0.0082  65.1737  0.0263          0.8  0.1014   0.5676  0.0000  0.0059              0.0        1.1556e+08                  0.0
2025-12-01     83.95     84.23    83.02      83.50  2457800  1.1680  0.0140  0.0145  61.7142  0.0194          0.6  0.1017   0.5615 -0.0051 -0.0051              0.0        1.1556e+08                  0.0
2025-12-02     83.82     84.55    83.00      84.55  4317300  1.1953  0.0141  0.0183  66.4038  0.0295          0.6  0.1237   0.5638  0.0000  0.0126              0.0        1.1569e+08                  0.0
2025-12-03     84.65     85.11    84.16      84.37  2112000  1.1778  0.0140  0.0113  64.9354  0.0298          0.6  0.1346   0.5766 -0.0021 -0.0021              0.0        1.1593e+08                  0.0
2025-12-04     84.67     86.34    83.58      86.08  3954900  1.2908  0.0150  0.0321  71.4048  0.0688          0.6  0.1677   0.5721  0.0000  0.0203              0.0        1.1612e+08                  0.0
2025-12-05     86.85     88.45    86.77      88.32  4420500  1.3679  0.0155  0.0268  77.3103  0.0950          0.6  0.2004   0.5780  0.0000  0.0260              0.0        1.1612e+08                  0.0
2025-12-08     88.41     88.79    88.06      88.13  3922300  1.3223  0.0150  0.0083  75.8789  0.0957          0.6  0.1914   0.5789 -0.0022 -0.0022              0.0        1.1612e+08                  0.0
2025-12-09     88.26     89.24    88.19      89.14  2627200  1.3072  0.0147  0.0125  78.1906  0.1019          0.6  0.2042   0.5725  0.0000  0.0115              0.0        1.1612e+08                  0.0
2025-12-10     89.46     91.52    89.44      91.26  2848500  1.3838  0.0152  0.0261  82.0741  0.1247          0.8  0.2221   0.5894  0.0000  0.0238              0.0        1.1612e+08                  0.0
2025-12-11     91.50     91.85    90.82      91.83  2345400  1.3585  0.0148  0.0112  82.9530  0.1254          0.8  0.2292   0.5896  0.0000  0.0062              0.0        1.1612e+08                  0.0
2025-12-12     91.95     92.11    90.91      91.42  1734800  1.3472  0.0147  0.0131  79.9177  0.1049          0.6  0.2298   0.5840 -0.0045 -0.0045              0.0        1.1612e+08                  0.0
2025-12-15     91.71     92.24    91.47      92.04  1542200  1.3095  0.0142  0.0089  81.0471  0.1314          0.8  0.2360   0.5818  0.0000  0.0068              0.0        1.1612e+08                  0.0
2025-12-16     91.91     92.23    91.64      91.65  1259200  1.2581  0.0137  0.0064  78.0728  0.1266          0.6  0.2199   0.5886 -0.0042 -0.0042              0.0        1.1612e+08                  0.0
2025-12-17     91.79     91.85    90.37      91.15  1880300  1.2740  0.0140  0.0162  74.3077  0.1191          0.4  0.2387   0.5977 -0.0097 -0.0055              0.0        1.1633e+08                  0.0
2025-12-18     91.76     93.08    91.50      92.52  1957300  1.3208  0.0143  0.0209  77.5083  0.1247          0.4  0.2552   0.6158  0.0000  0.0150              0.0        1.1702e+08                  0.0

In [ ]:
#######################
#######################

In [ ]:
# import pandas as pd
# from typing import Dict, Any
# from core.contracts import EngineOutput, EngineInput


# class HeadlessReporter:
#     """
#     Expert Logic: Extracts metrics and timeline metadata from EngineOutput.
#     Maintains transparency and trust without needing Plotly.
#     """

#     @staticmethod
#     def get_metadata(res: EngineOutput) -> Dict[str, Any]:
#         """Extracts the timeline and ticker list as structured data."""
#         return {
#             "start": res.start_date.date(),
#             "decision": res.decision_date.date(),
#             "entry": res.buy_date.date(),
#             "end": res.holding_end_date.date(),
#             "tickers": res.tickers,
#             "ticker_count": len(res.tickers),
#         }

#     @staticmethod
#     def get_metrics_table(res: EngineOutput) -> pd.DataFrame:
#         """The existing table logic—keeps the math verified."""
#         m = res.perf_metrics
#         rows = []
#         metric_types = [
#             ("Gain", "gain"),
#             ("Sharpe", "sharpe"),
#             ("Sharpe (ATRP)", "sharpe_atrp"),
#             ("Sharpe (TRP)", "sharpe_trp"),
#         ]

#         for label, key in metric_types:
#             p_row = {
#                 "Metric": f"Group {label}",
#                 "Full": m.get(f"full_p_{key}"),
#                 "Lookback": m.get(f"lookback_p_{key}"),
#                 "Holding": m.get(f"holding_p_{key}"),
#             }
#             b_row = {
#                 "Metric": f"Benchmark {label}",
#                 "Full": m.get(f"full_b_{key}"),
#                 "Lookback": m.get(f"lookback_b_{key}"),
#                 "Holding": m.get(f"holding_b_{key}"),
#             }

#             d_row = {"Metric": f"== {label} Delta"}
#             for col in ["Full", "Lookback", "Holding"]:
#                 p_val, b_val = p_row[col] or 0.0, b_row[col] or 0.0
#                 d_row[col] = p_val - b_val
#             rows.extend([p_row, b_row, d_row])

#         return pd.DataFrame(rows).set_index("Metric")


# def run_headless_simulation(engine, inputs: EngineInput) -> pd.DataFrame:
#     """
#     Orchestrator: Prints the Audit Timeline and Returns the Metrics DataFrame.
#     """
#     result = engine.run(inputs)
#     if result.error_msg:
#         print(f"🚨 Engine Error: {result.error_msg}")
#         return pd.DataFrame()

#     # 1. Extract and Print Metadata (Matches the Screenshot Audit)
#     meta = HeadlessReporter.get_metadata(result)

#     print("-" * 70)
#     print(
#         f"Timeline: [{meta['start']}] -> Decision: {meta['decision']} -> "
#         f"Entry: {meta['entry']} -> End: {meta['end']}"
#     )

#     ticker_str = ", ".join(meta["tickers"])
#     print(f"Selected Tickers ({meta['ticker_count']}):\n{ticker_str}")
#     print("-" * 70)

#     # 2. Return Table
#     return HeadlessReporter.get_metrics_table(result)


#

In [ ]:
# 1. Define the Action (Inputs)
my_input = EngineInput(
    mode="Ranking",
    start_date=pd.Timestamp("2025-12-10"),  # Decision Date from your screenshot
    lookback_period=21,
    holding_period=5,
    metric="Sharpe (ATRP)",
    benchmark_ticker="SPY",
    rank_start=11,
    rank_end=12,  # Choosing top 2 tickers as seen in your image (TD, ONON)
    debug=True,
)

# 2. Run the Headless Engine
metrics_df = run_headless_simulation(old_master_engine, my_input)

# 3. Verify Result
print("--- HEADLESS METRICS REPORT ---")
display(metrics_df)

# TEST: Gain in Holding Period (The Reward for RL)
reward = metrics_df.loc["Group Gain", "Holding"]
print(f"\nTarget Reward Signal: {reward:.4f}")

DEBUG: 937 stocks passed filters on 2025-12-10
----------------------------------------------------------------------
Timeline: [2025-11-10] -> Decision: 2025-12-10 -> Entry: 2025-12-11 -> End: 2025-12-18
Selected Tickers (2):
TD, ONON
----------------------------------------------------------------------
--- HEADLESS METRICS REPORT ---

                           Full  Lookback  Holding
Metric
Group Gain               0.2337    0.2304  -0.0068
Benchmark Gain          -0.0073    0.0090  -0.0186
== Gain Delta            0.2410    0.2215   0.0118
Group Sharpe             6.4330    7.4510  -2.4865
Benchmark Sharpe        -0.4945    0.9141  -7.6352
== Sharpe Delta          6.9275    6.5369   5.1487
Group Sharpe (ATRP)      0.2936    0.3612  -0.0515
Benchmark Sharpe (ATRP) -0.0200    0.0367  -0.3363
== Sharpe (ATRP) Delta   0.3136    0.3245   0.2847
Group Sharpe (TRP)       0.2746    0.3217  -0.0606
Benchmark Sharpe (TRP)  -0.0199    0.0372  -0.3035
== Sharpe (TRP) Delta    0.2945    0.2845   0.2428

Target Reward Signal: -0.0068