## I. Initialization & Environment

In [1]:
# 1. Setup & Path
%load_ext autoreload
%autoreload 2

import sys
import gc
import pandas as pd
import numpy as np
from pathlib import Path
from IPython.display import display, clear_output
import plotly.io as pio

def add_project_root_to_path():
    current = Path.cwd()
    for path in [current] + list(current.parents):
        if path.name == "notebooks_RLVR_v2":
            sys.path.insert(0, str(path))
            return path
        candidate = path / "notebooks_RLVR_v2"
        if candidate.exists():
            sys.path.insert(0, str(candidate))
            return candidate
    raise RuntimeError("Could not find notebooks_RLVR_v2 directory")

add_project_root_to_path()

# 2. Display Settings
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.precision", 4)

# 3. Project Imports
from core.analyzer import create_walk_forward_analyzer, run_headless_simulation
from core.kernel import FilterPack, EngineInput, MarketObservation, QuantUtils, TickerEngine
from core.config import GLOBAL_SETTINGS, OUTPUT_DIR
from core.environment import ParallelFeatureBuilder, FeatureCubeStitcher, DiscoveryEnv, AlphaLogic
from core.engine import AlphaEngine, AlphaCache
from core.features import generate_features
from core.utils import SystemUtils as SU
from strategy.registry import STRATEGY_REGISTRY

# 4. Load Environment Paths
DATA_DIR = SU.load_env_from_root("DATA_DIR")
DATA_PATH_OHLCV = SU.load_env_from_root("DATA_PATH_OHLCV")
DATA_PATH_INDICES = SU.load_env_from_root("DATA_PATH_INDICES")
print(f"✓ Paths Initialized.\nDATA Dir: {DATA_DIR}\nOHLCV: {DATA_PATH_OHLCV}\nIndices: {DATA_PATH_INDICES}")

NOTEBOOKS_RLVR_ROOT: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR

OUTPUT_DIR: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output

✓ Paths Initialized.
DATA Dir: c:\Users\ping\Files_win10\python\py311\stocks\data\
OHLCV: c:\Users\ping\Files_win10\python\py311\stocks\data\df_OHLCV_stocks_etfs.parquet
Indices: c:\Users\ping\Files_win10\python\py311\stocks\data\df_indices.parquet

## II. Data Pipeline

In [2]:
# # === RELOADING FROM PARQUET ===
# features_df = pd.read_parquet("output/features_df.parquet")
# macro_df = pd.read_parquet("output/macro_df.parquet")
# df_close_wide = pd.read_parquet("output/df_close_wide.parquet")
# df_atrp_wide = pd.read_parquet("output/df_atrp_wide.parquet")
# df_trp_wide = pd.read_parquet("output/df_trp_wide.parquet")

# df_indices = pd.read_parquet(DATA_PATH_INDICES, engine="pyarrow")
# df_ohlcv = pd.read_parquet(DATA_PATH_OHLCV, engine="pyarrow")
# df_fed = pd.read_parquet(
#     OUTPUT_DIR / "High_Yield_Spread_T10Y2Y_Spread.parquet", engine="pyarrow"
# )

In [3]:
print("⏳ Loading DataFrames... takes ~6 minutes")
df_indices = pd.read_parquet(DATA_PATH_INDICES, engine="pyarrow")
df_ohlcv = pd.read_parquet(DATA_PATH_OHLCV, engine="pyarrow")
df_fed = pd.read_parquet(
    OUTPUT_DIR / "High_Yield_Spread_T10Y2Y_Spread.parquet", engine="pyarrow"
)

print("⚡ Generating Features...")
features_df, macro_df = generate_features(
    df_ohlcv=df_ohlcv,
    df_indices=df_indices,
    df_fed=df_fed,
    benchmark_ticker=GLOBAL_SETTINGS["benchmark_ticker"],
)

print("🚀 Unstacking Wide Matrices...")
df_close_wide = df_ohlcv["Adj Close"].unstack(level=0)
df_atrp_wide = features_df["ATRP"].unstack(level=0).reindex_like(df_close_wide)
df_trp_wide = features_df["TRP"].unstack(level=0).reindex_like(df_close_wide)

if GLOBAL_SETTINGS["handle_zeros_as_nan"]:
    df_close_wide = df_close_wide.replace(0, np.nan)

df_close_wide = df_close_wide.ffill(limit=GLOBAL_SETTINGS["max_data_gap_ffill"])
df_close_wide = df_close_wide.fillna(GLOBAL_SETTINGS["nan_price_replacement"])

print(
    f"✅ Pipeline Complete. Tickers: {len(df_close_wide.columns)}, Days: {len(df_close_wide)}"
)

⏳ Loading DataFrames... takes ~6 minutes
⚡ Generating Features...
⚡ Generating Decoupled Features (Benchmark: SPY)...
🚀 Unstacking Wide Matrices...
✅ Pipeline Complete. Tickers: 1578, Days: 16192

In [4]:
# === PERSISTENCE SANDBOX ===
features_df.to_parquet("output/features_df.parquet", index=True)
macro_df.to_parquet("output/macro_df.parquet", index=True)
df_close_wide.to_parquet("output/df_close_wide.parquet", index=True)
df_atrp_wide.to_parquet("output/df_atrp_wide.parquet", index=True)
df_trp_wide.to_parquet("output/df_trp_wide.parquet", index=True)

## III. The Analysis Suite

In [5]:
# SINGLE SOURCE OF TRUTH
engine = AlphaEngine(
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    macro_df=macro_df,
    df_close_wide=df_close_wide,
    df_atrp_wide=df_atrp_wide,
    df_trp_wide=df_trp_wide,
)
print("🎯 Master AlphaEngine Ready.")

🎯 Master AlphaEngine Ready.

In [6]:
# Configuration for Interactive UI
_inputs = EngineInput(
    mode="Ranking",
    decision_date=pd.Timestamp("2026-04-16"),
    lookback_period=10,
    holding_period=5,
    metric="Log Price Gain",
    benchmark_ticker=GLOBAL_SETTINGS["benchmark_ticker"],
    rank_start=1,
    rank_end=3,
    debug=False,
)

analyzer1, _ = create_walk_forward_analyzer(engine, _inputs, universe_subset=None)
analyzer1.show()

DEBUG: 941 stocks passed filters on 2026-04-16

VBox(children=(HTML(value='<b>1. Timeline Configuration:</b> (Past <--- Decision ---> Future)'), HBox(children…

In [7]:
print("--- CASCADE FILTER, TICKERS PASSED FIRST FILTER ---")
# Get decision date from last run
decision_date_last_run = FilterPack(decision_date=analyzer1.last_run.decision_date)

# 1. LAUNCH STAGE 2 (Cascade)
# universe_subset=analyzer1.last_run.tickers means "Scan the whole market"
analyzer2, stage2_pack = create_walk_forward_analyzer(
    engine,
    universe_subset=analyzer1.last_run.tickers,
    # universe_subset=None,
    filter_pack=decision_date_last_run,
)

print("🚀 Ready for Stage 2: Run Simulation for 2nd filter.")
analyzer2.show()

--- CASCADE FILTER, TICKERS PASSED FIRST FILTER ---
🚀 Ready for Stage 2: Run Simulation for 2nd filter.

VBox(children=(HTML(value='<b>1. Timeline Configuration:</b> (Past <--- Decision ---> Future)'), HBox(children…

In [8]:
# Configuration for Interactive UI
_inputs = EngineInput(
    mode="Ranking",
    decision_date=pd.Timestamp("2026-04-16"),
    lookback_period=10,
    holding_period=5,
    metric="Log Price Gain",
    benchmark_ticker=GLOBAL_SETTINGS["benchmark_ticker"],
    rank_start=1,
    rank_end=3,
    debug=True,
)

print("--- 🤖 RL AGENT HEADLESS VIEW ---")
metrics_df = run_headless_simulation(engine, _inputs)
display(metrics_df)
print(f"\nTarget Reward Signal: {metrics_df.loc['Group Gain', 'Holding']:.6f}")

--- 🤖 RL AGENT HEADLESS VIEW ---
DEBUG: 941 stocks passed filters on 2026-04-16
----------------------------------------------------------------------
Timeline: [2026-04-01] -> Decision: 2026-04-16 -> Entry: 2026-04-17 -> End: 2026-04-24
Selected Tickers (3):
SOXL, CRDO, NBIS
----------------------------------------------------------------------

                            Full  Lookback  Holding
Metric
Group Gain                0.6818    0.5047   0.1557
Benchmark Gain            0.0858    0.0684   0.0053
== Gain Delta             0.5960    0.4363   0.1504
Group Sharpe             23.1077   24.1712  38.7616
Benchmark Sharpe         10.9495   14.0962   2.3401
== Sharpe Delta          12.1582   10.0750  36.4215
Group Sharpe (ATRP)       0.6272    0.6934   0.5230
Benchmark Sharpe (ATRP)   0.3892    0.4683   0.0879
== Sharpe (ATRP) Delta    0.2380    0.2251   0.4351
Group Sharpe (TRP)        0.5379    0.6064   0.4259
Benchmark Sharpe (TRP)    0.4575    0.5606   0.1070
== Sharpe (TRP) Delta     0.0804    0.0457   0.3190

Target Reward Signal: 0.155737

In [9]:
##################################
##################################
##################################

In [10]:
result = SU.visualize_analyzer_structure(analyzer=analyzer1)

====================================================================
🔍 HIGH-TRANSPARENCY AUDIT MAP
====================================================================
[  0] 📦 audit_pack (EngineOutput)
[  1]   📈 portfolio_series (shape=(17,))
[  2]   📈 benchmark_series (shape=(17,))
[  3]   🧮 normalized_plot_data (shape=(17, 3))
[  4]   📂 tickers (len=3)
[  5]     📄 index_0 (str)
[  6]     📄 index_1 (str)
[  7]     📄 index_2 (str)
[  8]   📈 initial_weights (shape=(3,))
[  9]   📂 perf_metrics (len=24)
[ 10]     🔢 full_p_gain (float)
[ 11]     🔢 full_p_sharpe (float)
[ 12]     🔢 full_p_sharpe_atrp (float)
[ 13]     🔢 full_p_sharpe_trp (float)
[ 14]     🔢 lookback_p_gain (float)
[ 15]     🔢 lookback_p_sharpe (float)
[ 16]     🔢 lookback_p_sharpe_atrp (float)
[ 17]     🔢 lookback_p_sharpe_trp (float)
[ 18]     🔢 holding_p_gain (float)
[ 19]     🔢 holding_p_sharpe (float)
[ 20]     🔢 holding_p_sharpe_atrp (float)
[ 21]     🔢 holding_p_sharpe_trp (float)
[ 22]     🔢 full_b_gain (float)
[ 23]     🔢 full_b_sharpe (float)
[ 24]     🔢 full_b_sharpe_atrp (float)
[ 25]     🔢 full_b_sharpe_trp (float)
[ 26]     🔢 lookback_b_gain (float)
[ 27]     🔢 lookback_b_sharpe (float)
[ 28]     🔢 lookback_b_sharpe_atrp (float)
[ 29]     🔢 lookback_b_sharpe_trp (float)
[ 30]     🔢 holding_b_gain (float)
[ 31]     🔢 holding_b_sharpe (float)
[ 32]     🔢 holding_b_sharpe_atrp (float)
[ 33]     🔢 holding_b_sharpe_trp (float)
[ 34]   🧮 results_df (shape=(3, 2))
[ 35]   📅 start_date (Timestamp)
[ 36]   📅 decision_date (Timestamp)
[ 37]   📅 buy_date (Timestamp)
[ 38]   📅 holding_end_date (Timestamp)
[ 39]   📈 portfolio_atrp_series (shape=(17,))
[ 40]   📈 benchmark_atrp_series (shape=(17,))
[ 41]   📈 portfolio_trp_series (shape=(17,))
[ 42]   📈 benchmark_trp_series (shape=(17,))
[ 43]   📄 error_msg (NoneType)
[ 44]   📂 debug_data (len=9)
[ 45]     📂 audit_liquidity (len=6)
                ╰── date --> [See ID 36]
[ 46]       🔢 total_tickers_available (int)
[ 47]       🔢 percentile_setting (float)
[ 48]       🔢 final_cutoff_usd (shape=())
[ 49]       📄 tickers_passed (shape=())
[ 50]       🧮 universe_snapshot (shape=(1578, 19))
[ 51]     🧮 full_universe_ranking (shape=(941, 16))
[ 52]     📂 meta (len=4)
[ 53]       🔢 dropped_count (int)
[ 54]       📂 dropped_tickers (len=0)
[ 55]       🔢 clean_count (int)
[ 56]       📄 selection_range (str)
[ 57]     📦 inputs_snapshot (EngineInput)
[ 58]       📄 mode (str)
[ 59]       📅 decision_date (Timestamp)
[ 60]       🔢 lookback_period (int)
[ 61]       🔢 holding_period (int)
[ 62]       📄 metric (str)
[ 63]       📄 benchmark_ticker (str)
[ 64]       🔢 rank_start (int)
[ 65]       🔢 rank_end (int)
[ 66]       📂 quality_thresholds (len=4)
[ 67]         🔢 min_median_dollar_volume (int)
[ 68]         🔢 min_liquidity_percentile (float)
[ 69]         🔢 max_stale_pct (float)
[ 70]         🔢 max_same_vol_count (int)
[ 71]       📂 manual_tickers (len=0)
[ 72]       🔢 debug (bool)
[ 73]       📄 universe_subset (NoneType)
[ 74]     🧮 alpha_perception (shape=(941, 11))
[ 75]     📂 verification (len=2)
[ 76]       📂 p (len=4)
                  ╰── val --> [See ID 1]
[ 77]         📈 ret (shape=(17,))
                  ╰── atrp --> [See ID 39]
                  ╰── trp --> [See ID 41]
[ 78]       📂 b (len=4)
                  ╰── val --> [See ID 2]
[ 79]         📈 ret (shape=(17,))
                  ╰── atrp --> [See ID 40]
                  ╰── trp --> [See ID 42]
[ 80]     📂 portfolio_raw_components (len=4)
[ 81]       🧮 prices (shape=(17, 3))
[ 82]       🧮 atrp (shape=(17, 3))
[ 83]       🧮 trp (shape=(17, 3))
[ 84]       🧮 ohlcv_raw (shape=(51, 5))
[ 85]     📂 benchmark_raw_components (len=4)
[ 86]       🧮 prices (shape=(17, 1))
[ 87]       🧮 atrp (shape=(17, 1))
[ 88]       🧮 trp (shape=(17, 1))
[ 89]       🧮 ohlcv_raw (shape=(17, 5))
              ╰── selection_audit --> [See ID 51]
[ 90]   🧮 macro_df (shape=(16192, 11))
[ 91]   📄 alpha_perception (NoneType)

In [11]:
target_tickers = SU.peek(4, result)

 ============================================================
 📍 INDEX: [4]
 🏷️  NAME:  tickers
 📂 PATH:  audit_pack -> tickers
 ============================================================

['SOXL', 'CRDO', 'NBIS']

In [12]:
SU.export_audit_to_excel(
    audit_pack=analyzer1.last_run, filename="Audit_Verification_Report.xlsx"
)

📂 [EXCEL AUDIT] Building full transparency report: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\Audit_Verification_Report.xlsx
✨ Audit Report Complete: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\Audit_Verification_Report.xlsx

WindowsPath('C:/Users/ping/Files_win10/python/py311/stocks/notebooks_RLVR/output/Audit_Verification_Report.xlsx')

In [13]:
##################################
##################################
##################################

In [14]:
import pathlib

# Set display width to prevent line wrapping
pd.set_option("display.width", 2000)

# Show all columns instead of truncated view
pd.set_option("display.max_columns", None)


def load_latest_finviz_parquet(data_dir: str) -> pd.DataFrame:
    path = pathlib.Path(data_dir)
    pattern = "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_df_finviz_merged_stocks_etfs.parquet"

    files = list(path.glob(pattern))

    if not files:
        print(f"DEBUG: No files matching pattern found in {path.absolute()}")
        return None

    latest_path = max(files, key=lambda x: x.name)
    print(f"DEBUG: Loading file: {latest_path.name}")

    try:
        return pd.read_parquet(latest_path)
    except Exception as e:
        print(f"DEBUG: Failed to read {latest_path.name}. Error: {e}")
        return None


# Usage
df_finviz = load_latest_finviz_parquet(DATA_DIR)
print(f"df_finviz:\n{df_finviz}")

DEBUG: Loading file: 2026-05-04_df_finviz_merged_stocks_etfs.parquet
df_finviz:
       No.                                            Company               Index                  Sector                        Industry Country Exchange                                               Info  MktCap AUM, M  Rank  Market Cap, M    P/E  Fwd P/E   PEG    P/S    P/B    P/C  P/FCF  Book/sh  Cash/sh  Dividend %  Dividend TTM Dividend Ex Date  Payout Ratio %    EPS  EPS next Q  EPS this Y %  EPS next Y %  EPS past 5Y %  EPS next 5Y %  Sales past 5Y %  Sales Q/Q %  EPS Q/Q %  EPS YoY TTM %  Sales YoY TTM %  Sales, M  Income, M  EPS Surprise %  Revenue Surprise %  Outstanding, M  Float, M  Float %  Insider Own %  Insider Trans %  Inst Own %  Inst Trans %  Short Float %  Short Ratio  Short Interest, M  ROA %   ROE %  ROIC %  Curr R  Quick R  LTDebt/Eq  Debt/Eq  Gross M %  Oper M %  Profit M %  Perf 3D %  Perf Week %  Perf Month %  Perf Quart %  Perf Half %  Perf Year %  Perf YTD %  Beta    ATR  ATR/Price %  Volatility W %  Volatility M %  SMA20 %  SMA50 %  SMA200 %  50D High %  50D Low %  52W High %  52W Low %        52W Range  All-Time High %  All-Time Low %    RSI  Earnings    IPO Date Optionable Shortable  Employees  Change from Open %  Gap %  Recom  Avg Volume, M  Rel Volume     Volume  Target Price  Prev Close    Open    High     Low   Price  Change %                Single Category         Asset Type  Expense %  Holdings  AUM, M  Flows 1M, M  Flows% 1M  Flows 3M, M  Flows% 3M  Flows YTD, M  Flows% YTD  Return% 1Y  Return% 3Y  Return% 5Y                                               Tags  Sharpe 3d  Sortino 3d  Omega 3d  Sharpe 5d  Sortino 5d   Omega 5d  Sharpe 10d  Sortino 10d  Omega 10d  Sharpe 15d  Sortino 15d  Omega 15d  Sharpe 30d  Sortino 30d  Omega 30d  Sharpe 60d  Sortino 60d  Omega 60d  Sharpe 120d  Sortino 120d  Omega 120d  Sharpe 250d  Sortino 250d  Omega 250d
NVDA     1                                        NVIDIA Corp  DJIA, NDX, S&P 500              Technology                  Semiconductors     USA     NASD                         Technology, Semiconductors      4823060.0     1      4823060.0  40.49      NaN  0.45  22.34  30.67  77.10  57.64     6.47     2.57        0.02          0.04        3/11/2026            0.82   4.90        1.74           NaN           NaN            NaN            NaN              NaN        73.21      96.65          66.12            65.47  215940.0   120070.0            5.52                3.03         24300.0   23370.0    96.17           3.81            -0.30       68.43          0.14           1.21         1.62             283.34  75.42  101.49   71.75    3.91     3.24       0.06     0.07      71.07     60.38       55.60    -5.1470        -8.37         11.89          6.93        -2.17        73.34        6.42  2.25   6.33       3.1892            3.60            2.84     0.11     5.95      7.88       -8.46      20.83       -8.46      79.10  110.82 - 216.82            -8.46       595339.96  53.01  May 20/a   1/22/1999        Yes       Yes    42000.0               -0.51   0.53   1.29       175.0800        0.71  124164197        269.82      198.45  199.50  201.73  194.74  198.48      0.02                                                          NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -   -11.2544    -11.2397    0.0000   -13.5879    -11.1591     0.0000     -0.3170      -0.4994     0.9489      0.5476       0.8598     1.0986      2.9332       4.9660     1.6428      0.8884       1.2745     1.1543       0.0423        0.0603      1.0068       1.7191        2.6703      1.3247
GOOGL    2                                       Alphabet Inc        NDX, S&P 500  Communication Services  Internet Content & Information     USA     NASD  Communication Services, Internet Content & Inf...      4629980.0     2      4629980.0  29.98      NaN  1.65  10.94   9.70  36.50  71.86    39.51    10.50        0.22          0.84         6/8/2026            7.68  12.78        2.87           NaN           NaN            NaN            NaN              NaN        22.34      70.31          46.22            17.77  423170.0   160210.0           90.52                2.73          5820.0    5800.0    99.64          52.10            -0.04       38.51          0.65           1.35         2.37              78.07  27.17   38.88   28.04    1.92     1.92       0.19     0.22      60.43     33.63       37.86     9.5188         9.39         29.58         11.51        36.16       133.65       22.44  1.27   9.84       2.5675            2.94            2.34    12.33    20.95     35.84       -0.91      40.84       -0.91     159.23  147.84 - 386.76            -0.91        15859.94  80.05  Apr 29/a   8/19/2004        Yes       Yes   190820.0               -0.68   0.05   1.36        32.9300        0.79   26082547        420.90      385.69  385.88  387.38  379.79  383.25     -0.63                                                          NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -    -5.6272     -7.4963    0.3322     7.4936    116.7949    15.7148      7.8987     112.8086    16.1455      5.8107      28.7010     4.5101      4.9675      11.7512     2.6204      2.1688       4.4459     1.5007       1.9422        3.6324      1.4164       2.9072        5.3509      1.6793
GOOG     3                                       Alphabet Inc        NDX, S&P 500  Communication Services  Internet Content & Information     USA     NASD  Communication Services, Internet Content & Inf...      4615930.0     3      4615930.0  29.70      NaN  1.64  10.91   9.61  36.39  71.64    39.51    10.43        0.23          0.84         6/8/2026            7.68  12.78        2.86           NaN           NaN            NaN            NaN              NaN        22.34      70.31          46.22            17.77  423170.0   160210.0           90.44                2.74          5460.0    5070.0    92.85          58.19            -0.03       27.09          0.65           0.82         1.94              41.39  27.17   38.88   28.04    1.92     1.92       0.19     0.22      60.43     33.63       37.86     9.3087         8.93         28.93         10.07        34.67       128.96       20.98  1.26   9.56       2.5182            2.87            2.29    12.00    20.32     34.49       -0.98      39.81       -0.98     153.96  149.49 - 383.39            -0.98         1461.58  79.08  Apr 29/a   3/27/2014        Yes       Yes   190820.0               -0.73  -0.20   1.37        21.3100        0.85   18209374        420.48      383.22  382.45  384.18  376.77  379.64     -0.93                                                          NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -    -5.5784     -7.4529    0.3360     7.1699     77.0973    10.0668      7.6029      75.2883    11.6405      5.6643      27.1486     4.1214      5.1314      12.8051     2.7394      2.0891       4.3376     1.4809       1.8943        3.5547      1.4027       2.8832        5.2754      1.6729
AAPL     4                                          Apple Inc  DJIA, NDX, S&P 500              Technology            Consumer Electronics     USA     NASD                   Technology, Consumer Electronics      4064180.0     4      4064180.0  33.49      NaN  2.40   9.00  38.13  59.33  31.46     7.26     4.67        0.39          1.04        5/11/2026           13.66   8.27        1.87           NaN           NaN            NaN            NaN              NaN        16.60      22.04          28.91            12.76  451440.0   122580.0            3.30                1.58         14670.0   14660.0    99.97           0.12            -0.57       66.02          0.35           0.92         2.94             134.42  34.91  141.47   67.76    1.07     1.02       0.70     0.80      47.86     32.64       27.15     2.4651         3.45          8.17          2.53         2.00        34.81        1.83  1.06   6.54       2.3625            2.28            2.10     3.58     5.88      8.34       -3.62      12.76       -4.08      43.25  193.25 - 288.62            -4.08       435057.75  61.76  Apr 30/a  12/12/1980        Yes       Yes   166000.0               -1.03  -0.16   1.89        45.6500        1.00   45472125        305.33      280.14  279.70  280.63  274.86  276.83     -1.18                                                          NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -     5.1443     18.9928    2.6920     4.6670     14.5588     2.5796      4.2471      10.4131     2.0871      4.1792       8.3585     1.9257      3.3644       6.2896     1.7550     -0.0911      -0.1275     0.9848       0.1975        0.2881      1.0350       1.4118        2.3242      1.2888
MSFT     5                                     Microsoft Corp  DJIA, NDX, S&P 500              Technology       Software - Infrastructure     USA     NASD              Technology, Software - Infrastructure      3072550.0     5      3072550.0  24.63      NaN  1.15   9.65   7.42  39.25  42.14    55.78    10.54        0.89          3.48        5/21/2026           24.34  16.79        4.23           NaN           NaN            NaN            NaN              NaN        18.30      23.32          29.64            17.87  318270.0   125220.0            5.18                1.77          7430.0    7310.0    98.46           1.53            -0.05       74.71          0.38           1.14         2.29              83.41  19.93   34.01   24.02    1.28     1.27       0.26     0.30      68.31     46.80       39.34    -2.5538        -2.64         10.75         -2.30       -21.33        -4.98      -14.47  1.09  11.12       2.6885            2.33            2.39     1.47     4.33    -11.53       -4.63      16.09      -25.53      16.09  356.28 - 555.45           -25.53       519010.26  53.99  Apr 29/a   3/13/1986        Yes       Yes   228000.0                0.53  -0.72   1.23        36.4000        0.77   27966590        554.32      414.44  411.44  420.78  410.80  413.62     -0.20                                                          NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -     8.6045     73.7177    7.5673    -6.2865     -7.0943     0.3057     -1.8187      -2.2474     0.7379      2.5116       3.8091     1.5034      2.0833       3.2520     1.4119      0.4961       0.7347     1.0867      -1.3944       -1.7105      0.7788      -0.2162       -0.2795      0.9611
...    ...                                                ...                 ...                     ...                             ...     ...      ...                                                ...            ...   ...            ...    ...      ...   ...    ...    ...    ...    ...      ...      ...         ...           ...              ...             ...    ...         ...           ...           ...            ...            ...              ...          ...        ...            ...              ...       ...        ...             ...                 ...             ...       ...      ...            ...              ...         ...           ...            ...          ...                ...    ...     ...     ...     ...      ...        ...      ...        ...       ...         ...        ...          ...           ...           ...          ...          ...         ...   ...    ...          ...             ...             ...      ...      ...       ...         ...        ...         ...        ...              ...              ...             ...    ...       ...         ...        ...       ...        ...                 ...    ...    ...            ...         ...        ...           ...         ...     ...     ...     ...     ...       ...                            ...                ...        ...       ...     ...          ...        ...          ...        ...           ...         ...         ...         ...         ...                                                ...        ...         ...       ...        ...         ...        ...         ...          ...        ...         ...          ...        ...         ...          ...        ...         ...          ...        ...          ...           ...         ...          ...           ...         ...
SJNK   395  State Street SPDR Bloomberg Short Term High Yi...                   -               Financial            Exchange Traded Fund     USA     NYSE  Financial, Exchange Traded Fund, Bonds - Corpo...         4770.0  1555            NaN    NaN      NaN   NaN    NaN    NaN    NaN    NaN      NaN      NaN        7.05          1.76         5/1/2026             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN       NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.92               4.03    NaN     NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     0.0500        -0.87          0.28         -1.19        -1.81         0.28       -1.26  0.29   0.09       0.3600            0.26            0.29    -0.56    -0.24     -1.24       -1.38       1.13       -2.53       1.13    24.72 - 25.65           -19.82           16.71  43.02         -   3/15/2012        Yes       Yes        NaN               -0.24  -0.04    NaN         4.3800        0.89    3884556           NaN       25.07   25.06   25.07   24.98   25.00     -0.28              Bonds - Corporate              Bonds       0.40    1150.0  4770.0          NaN       0.98          NaN      -9.26       -418.87       -8.07        8.24        8.48        4.95  U.S., fixed-income, corporate-bonds, bonds, hi...   -11.5260    -11.3725    0.0000    -3.1418     -4.5933     0.5888     -2.7091      -3.6028     0.6472     -1.9760      -2.8475     0.7268      1.8597       3.0602     1.3549     -0.3852      -0.5419     0.9381       0.1159        0.1659      1.0203       1.0566        1.6240      1.2037
RSPT   396        Invesco S&P 500 Equal Weight Technology ETF                   -               Financial            Exchange Traded Fund     USA     NYSE  Financial, Exchange Traded Fund, US Equities -...         4740.0  1556            NaN    NaN      NaN   NaN    NaN    NaN    NaN    NaN      NaN      NaN        0.31          0.17        3/23/2026             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN       NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.81               0.33    NaN     NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     3.7495         3.30         17.48         13.99        17.86        53.94       19.78  1.29   1.02       1.8712            1.57            1.56     6.71    13.17     19.76        0.36      26.18        0.36      57.04    34.71 - 54.32             0.36         2413.14  72.29         -   11/7/2006        Yes       Yes        NaN               -0.16   0.63    NaN         0.4075        1.22     496427           NaN       54.26   54.60   54.91   54.20   54.51      0.46  US Equities - Industry Sector  Equities (Stocks)       0.40      74.0  4740.0          NaN      -0.55          NaN       0.74         24.04        0.51       57.90       29.03       14.20  U.S., equity, technology, I.T., equal-weight, ...    23.2973   5125.6923  457.6330    32.4809  26782.2759  3375.2496      5.2712       9.3813     2.1240      9.2362      17.3270     3.5893      5.4059       9.8569     2.3054      2.6387       4.1173     1.4951       1.4424        2.1173      1.2493       2.0587        3.1247      1.3964
ISTB   397                 iShares Core 1-5 Year USD Bond ETF                   -               Financial            Exchange Traded Fund     USA     NASD  Financial, Exchange Traded Fund, Bonds - Broad...         4730.0  1557            NaN    NaN      NaN   NaN    NaN    NaN    NaN    NaN      NaN      NaN        4.24          2.04         5/1/2026             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN       NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.20               0.09    NaN     NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     0.0245        -0.64         -0.25         -0.94        -1.29         0.02       -1.07  0.11   0.10       0.2073            0.14            0.14    -0.49    -0.62     -0.98       -1.67       0.02       -1.67       0.35    48.06 - 49.05            -6.31            6.99  36.36         -  10/22/2012        Yes       Yes        NaN               -0.10  -0.02    NaN         0.4481        1.29     576933           NaN       48.29   48.28   48.28   48.17   48.23     -0.12           Bonds - Broad Market              Bonds       0.06    7035.0  4730.0          NaN       0.20          NaN       0.41         73.13        1.57        4.02        4.74        1.92                          U.S., fixed-income, bonds    -9.8724    -10.5054    0.0641    -6.9470     -7.6187     0.2903     -5.4131      -5.9895     0.4064     -4.5963      -5.4991     0.4767     -0.1930      -0.2594     0.9712     -2.0492      -2.5198     0.7274      -0.9973       -1.2804      0.8518       0.1151        0.1626      1.0190

In [15]:
df_finviz.loc[target_tickers]

      No.                                   Company Index      Sector                   Industry         Country Exchange                                               Info  MktCap AUM, M  Rank  Market Cap, M     P/E  Fwd P/E   PEG    P/S    P/B    P/C   P/FCF  Book/sh  Cash/sh  Dividend %  Dividend TTM Dividend Ex Date  Payout Ratio %   EPS  EPS next Q  EPS this Y %  EPS next Y %  EPS past 5Y %  EPS next 5Y %  Sales past 5Y %  Sales Q/Q %  EPS Q/Q %  EPS YoY TTM %  Sales YoY TTM %  Sales, M  Income, M  EPS Surprise %  Revenue Surprise %  Outstanding, M  Float, M  Float %  Insider Own %  Insider Trans %  Inst Own %  Inst Trans %  Short Float %  Short Ratio  Short Interest, M  ROA %  ROE %  ROIC %  Curr R  Quick R  LTDebt/Eq  Debt/Eq  Gross M %  Oper M %  Profit M %  Perf 3D %  Perf Week %  Perf Month %  Perf Quart %  Perf Half %  Perf Year %  Perf YTD %  Beta    ATR  ATR/Price %  Volatility W %  Volatility M %  SMA20 %  SMA50 %  SMA200 %  50D High %  50D Low %  52W High %  52W Low %       52W Range  All-Time High %  All-Time Low %    RSI  Earnings   IPO Date Optionable Shortable  Employees  Change from Open %  Gap %  Recom  Avg Volume, M  Rel Volume    Volume  Target Price  Prev Close    Open    High     Low   Price  Change %               Single Category         Asset Type  Expense %  Holdings   AUM, M  Flows 1M, M  Flows% 1M  Flows 3M, M  Flows% 3M  Flows YTD, M  Flows% YTD  Return% 1Y  Return% 3Y  Return% 5Y                                    Tags  Sharpe 3d  Sortino 3d  Omega 3d  Sharpe 5d  Sortino 5d  Omega 5d  Sharpe 10d  Sortino 10d  Omega 10d  Sharpe 15d  Sortino 15d  Omega 15d  Sharpe 30d  Sortino 30d  Omega 30d  Sharpe 60d  Sortino 60d  Omega 60d  Sharpe 120d  Sortino 120d  Omega 120d  Sharpe 250d  Sortino 250d  Omega 250d
SOXL  143  Direxion Daily Semiconductor Bull 3X ETF     -   Financial       Exchange Traded Fund             USA     NYSE  Financial, Exchange Traded Fund, Equity - Leve...        17060.0   802            NaN     NaN      NaN   NaN    NaN    NaN    NaN     NaN      NaN      NaN        0.06          0.08        9/23/2025             NaN   NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN       NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.14              11.88    NaN    NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     8.1207         3.37        141.80         95.63       169.15       859.74      203.47  5.56   8.61       6.7503            8.19            7.13    28.58    75.38    159.83       -2.92     222.75       -2.92     952.39  12.12 - 131.38            -2.92        40893.43  72.24         -  3/11/2010        Yes       Yes        NaN               -3.57   1.43    NaN          86.52        0.53  45976254           NaN      130.40  132.27  133.67  123.80  127.55     -2.19  Equity - Leveraged / Inverse  Equities (Stocks)       0.75      43.0  17060.0          NaN     -32.97          NaN     -28.12      -12580.0      -42.44      976.07       115.1       26.07  U.S., equity, semiconductors, leverage     1.0952      2.4271    1.2162    13.2622     56.8146    8.1580      6.6342      12.6527     2.6700      7.8969      15.1350     3.4915      6.8690      12.3534     2.9727      3.2814       5.0905     1.6996       2.5382        3.8318      1.5078       2.8702        4.5154      1.6255
CRDO  426        Credo Technology Group Holding Ltd   RUT  Technology             Semiconductors  Cayman Islands     NASD                         Technology, Semiconductors        33210.0   505        33210.0   99.86      NaN  0.31  31.09  17.94  25.52  117.07    10.04     7.06         NaN           NaN                -             0.0  1.80        1.02           NaN           NaN            NaN            NaN              NaN       201.49     408.64        6897.08           226.12    1070.0     339.76           17.38                0.21          184.22    165.65    89.92          10.19            -6.37       76.08          3.73           5.58         1.23               9.24  24.65  27.54   18.25   10.82     9.56       0.01     0.01      67.83     30.32       31.81     2.4407        -0.24         77.49         50.10         8.07       273.10       25.14  3.17  11.96       6.6422            7.09            7.49    12.01    39.85     31.13       -9.50     108.20      -15.78     294.44  45.65 - 213.80           -15.78         2402.57  62.33  Mar 02/a  1/27/2022        Yes       Yes      622.0               -3.72   1.43   1.16           7.51        0.48   3623868        212.16      184.38  187.02  188.20  178.88  180.06     -2.34                                                         NaN       NaN      NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                       -     4.8466     17.0583    2.5197     7.5982     26.2272    3.5143     -0.2326      -0.3322     0.9657      2.8823       4.6059     1.5213      5.0519      10.0702     2.2004      2.5178       4.1634     1.4867       0.5366        0.8237      1.0914       1.9902        3.1802      1.3854
NBIS  344                           Nebius Group NV     -  Technology  Software - Infrastructure     Netherlands     NASD              Technology, Software - Infrastructure        44410.0   401        44410.0  346.13      NaN   NaN  83.13   9.68  12.07     NaN    18.23    14.61         NaN           NaN                -             0.0  0.51       -0.77           NaN           NaN            NaN            NaN              NaN       500.79     -70.26         373.88           354.32     534.2     101.60            5.74               -7.92          219.47    201.25    91.70          20.05            -0.26       39.84          1.04          21.68         2.71              43.63   0.25   0.50    1.07    3.08     6.57       1.05     1.06      -7.66   -113.33       19.02    24.9522        21.70         62.12        100.11        42.07       594.57      110.76  3.86  12.33       6.9890            9.26            8.00    17.76    43.18     77.40        4.57     111.21        4.57     658.80  23.25 - 168.71             4.57         1674.83  68.89  May 13/b  5/24/2011        Yes       Yes        NaN               10.12   3.70   1.76          16.07        1.54  24701895        176.85      154.49  160.21  179.40  159.70  176.42     14.20                                                         NaN       NaN      NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                       -   119.6595   5125.6923  457.6330    14.9741    105.1732   14.2506      3.3693       7.7818     1.8303      1.9942       4.1631     1.4389      4.3769       8.5285     2.0226      3.4689       6.2330     1.7574       1.4562        2.3629      1.2605       2.3631        4.6701      1.5316

In [16]:
print(df_finviz.loc[target_tickers])

      No.                                   Company Index      Sector                   Industry         Country Exchange                                               Info  MktCap AUM, M  Rank  Market Cap, M     P/E  Fwd P/E   PEG    P/S    P/B    P/C   P/FCF  Book/sh  Cash/sh  Dividend %  Dividend TTM Dividend Ex Date  Payout Ratio %   EPS  EPS next Q  EPS this Y %  EPS next Y %  EPS past 5Y %  EPS next 5Y %  Sales past 5Y %  Sales Q/Q %  EPS Q/Q %  EPS YoY TTM %  Sales YoY TTM %  Sales, M  Income, M  EPS Surprise %  Revenue Surprise %  Outstanding, M  Float, M  Float %  Insider Own %  Insider Trans %  Inst Own %  Inst Trans %  Short Float %  Short Ratio  Short Interest, M  ROA %  ROE %  ROIC %  Curr R  Quick R  LTDebt/Eq  Debt/Eq  Gross M %  Oper M %  Profit M %  Perf 3D %  Perf Week %  Perf Month %  Perf Quart %  Perf Half %  Perf Year %  Perf YTD %  Beta    ATR  ATR/Price %  Volatility W %  Volatility M %  SMA20 %  SMA50 %  SMA200 %  50D High %  50D Low %  52W High %  52W Low %       52W Range  All-Time High %  All-Time Low %    RSI  Earnings   IPO Date Optionable Shortable  Employees  Change from Open %  Gap %  Recom  Avg Volume, M  Rel Volume    Volume  Target Price  Prev Close    Open    High     Low   Price  Change %               Single Category         Asset Type  Expense %  Holdings   AUM, M  Flows 1M, M  Flows% 1M  Flows 3M, M  Flows% 3M  Flows YTD, M  Flows% YTD  Return% 1Y  Return% 3Y  Return% 5Y                                    Tags  Sharpe 3d  Sortino 3d  Omega 3d  Sharpe 5d  Sortino 5d  Omega 5d  Sharpe 10d  Sortino 10d  Omega 10d  Sharpe 15d  Sortino 15d  Omega 15d  Sharpe 30d  Sortino 30d  Omega 30d  Sharpe 60d  Sortino 60d  Omega 60d  Sharpe 120d  Sortino 120d  Omega 120d  Sharpe 250d  Sortino 250d  Omega 250d
SOXL  143  Direxion Daily Semiconductor Bull 3X ETF     -   Financial       Exchange Traded Fund             USA     NYSE  Financial, Exchange Traded Fund, Equity - Leve...        17060.0   802            NaN     NaN      NaN   NaN    NaN    NaN    NaN     NaN      NaN      NaN        0.06          0.08        9/23/2025             NaN   NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN       NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.14              11.88    NaN    NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     8.1207         3.37        141.80         95.63       169.15       859.74      203.47  5.56   8.61       6.7503            8.19            7.13    28.58    75.38    159.83       -2.92     222.75       -2.92     952.39  12.12 - 131.38            -2.92        40893.43  72.24         -  3/11/2010        Yes       Yes        NaN               -3.57   1.43    NaN          86.52        0.53  45976254           NaN      130.40  132.27  133.67  123.80  127.55     -2.19  Equity - Leveraged / Inverse  Equities (Stocks)       0.75      43.0  17060.0          NaN     -32.97          NaN     -28.12      -12580.0      -42.44      976.07       115.1       26.07  U.S., equity, semiconductors, leverage     1.0952      2.4271    1.2162    13.2622     56.8146    8.1580      6.6342      12.6527     2.6700      7.8969      15.1350     3.4915      6.8690      12.3534     2.9727      3.2814       5.0905     1.6996       2.5382        3.8318      1.5078       2.8702        4.5154      1.6255
CRDO  426        Credo Technology Group Holding Ltd   RUT  Technology             Semiconductors  Cayman Islands     NASD                         Technology, Semiconductors        33210.0   505        33210.0   99.86      NaN  0.31  31.09  17.94  25.52  117.07    10.04     7.06         NaN           NaN                -             0.0  1.80        1.02           NaN           NaN            NaN            NaN              NaN       201.49     408.64        6897.08           226.12    1070.0     339.76           17.38                0.21          184.22    165.65    89.92          10.19            -6.37       76.08          3.73           5.58         1.23               9.24  24.65  27.54   18.25   10.82     9.56       0.01     0.01      67.83     30.32       31.81     2.4407        -0.24         77.49         50.10         8.07       273.10       25.14  3.17  11.96       6.6422            7.09            7.49    12.01    39.85     31.13       -9.50     108.20      -15.78     294.44  45.65 - 213.80           -15.78         2402.57  62.33  Mar 02/a  1/27/2022        Yes       Yes      622.0               -3.72   1.43   1.16           7.51        0.48   3623868        212.16      184.38  187.02  188.20  178.88  180.06     -2.34                                                         NaN       NaN      NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                       -     4.8466     17.0583    2.5197     7.5982     26.2272    3.5143     -0.2326      -0.3322     0.9657      2.8823       4.6059     1.5213      5.0519      10.0702     2.2004      2.5178       4.1634     1.4867       0.5366        0.8237      1.0914       1.9902        3.1802      1.3854
NBIS  344                           Nebius Group NV     -  Technology  Software - Infrastructure     Netherlands     NASD              Technology, Software - Infrastructure        44410.0   401        44410.0  346.13      NaN   NaN  83.13   9.68  12.07     NaN    18.23    14.61         NaN           NaN                -             0.0  0.51       -0.77           NaN           NaN            NaN            NaN              NaN       500.79     -70.26         373.88           354.32     534.2     101.60            5.74               -7.92          219.47    201.25    91.70          20.05            -0.26       39.84          1.04          21.68         2.71              43.63   0.25   0.50    1.07    3.08     6.57       1.05     1.06      -7.66   -113.33       19.02    24.9522        21.70         62.12        100.11        42.07       594.57      110.76  3.86  12.33       6.9890            9.26            8.00    17.76    43.18     77.40        4.57     111.21        4.57     658.80  23.25 - 168.71             4.57         1674.83  68.89  May 13/b  5/24/2011        Yes       Yes        NaN               10.12   3.70   1.76          16.07        1.54  24701895        176.85      154.49  160.21  179.40  159.70  176.42     14.20                                                         NaN       NaN      NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                       -   119.6595   5125.6923  457.6330    14.9741    105.1732   14.2506      3.3693       7.7818     1.8303      1.9942       4.1631     1.4389      4.3769       8.5285     2.0226      3.4689       6.2330     1.7574       1.4562        2.3629      1.2605       2.3631        4.6701      1.5316

In [17]:
def cleanup_ui():
    clear_output(wait=True)
    pio.renderers.default = None
    gc.collect()
    print("🧹 Memory Cleared.")


def active_engine_audit():
    gc.collect()
    engines = [obj for obj in gc.get_objects() if type(obj).__name__ == "AlphaEngine"]
    print(f"Active AlphaEngine Instances: {len(engines)}")


active_engine_audit()

Active AlphaEngine Instances: 1

In [18]:
# print(features_df.info())
# display(features_df.head())
# display(df_indices.tail())

In [19]:
################################
################################
################################
################################

In [20]:
SU.peek(0, result)

 ============================================================
 📍 INDEX: [0]
 🏷️  NAME:  audit_pack
 📂 PATH:  audit_pack
 ============================================================

EngineOutput(portfolio_series=Date
2026-04-01    1.0000
2026-04-02    1.0448
2026-04-06    1.0736
2026-04-07    1.1157
2026-04-08    1.2222
2026-04-09    1.2799
2026-04-10    1.3768
2026-04-13    1.4861
2026-04-14    1.6280
2026-04-15    1.6786
2026-04-16    1.6565
2026-04-17    1.6761
2026-04-20    1.7388
2026-04-21    1.7746
2026-04-22    1.8428
2026-04-23    1.8776
2026-04-24    1.9774
dtype: float64, benchmark_series=Date
2026-04-01    1.0000
2026-04-02    1.0009
2026-04-06    1.0056
2026-04-07    1.0061
2026-04-08    1.0317
2026-04-09    1.0377
2026-04-10    1.0370
2026-04-13    1.0471
2026-04-14    1.0599
2026-04-15    1.0682
2026-04-16    1.0708
2026-04-17    1.0838
2026-04-20    1.0816
2026-04-21    1.0745
2026-04-22    1.0854
2026-04-23    1.0812
2026-04-24    1.0896
dtype: float64, normalized_plot_data=Ticker        NBIS    SOXL    CRDO
Date
2026-04-01  1.0000  1.0000  1.0000
2026-04-02  1.0674  1.0094  1.0577
2026-04-06  1.1039  1.0488  1.0682
2026-04-07  1.1515  1.0821  1.1133
2026-04-08  1.2261  1.2916  1.1490
2026-04-09  1.3372  1.3773  1.1252
2026-04-10  1.4220  1.4617  1.2468
2026-04-13  1.5160  1.5415  1.4008
2026-04-14  1.5884  1.6324  1.6631
2026-04-15  1.6358  1.6449  1.7551
2026-04-16  1.6218  1.6910  1.6569
2026-04-17  1.5413  1.8117  1.6753
2026-04-20  1.5612  1.8358  1.8195
2026-04-21  1.5356  1.8770  1.9112
2026-04-22  1.5315  2.0214  1.9755
2026-04-23  1.5408  2.1579  1.9343
2026-04-24  1.4435  2.4554  2.0334, tickers=['SOXL', 'CRDO', 'NBIS'], initial_weights=SOXL    0.3333
CRDO    0.3333
NBIS    0.3333
dtype: float64, perf_metrics={'full_p_gain': 0.6817877455655165, 'full_p_sharpe': 23.107695909016513, 'full_p_sharpe_atrp': 0.627152382982204, 'full_p_sharpe_trp': 0.5379225630058191, 'lookback_p_gain': 0.5047361606600764, 'lookback_p_sharpe': 24.171188169091653, 'lookback_p_sharpe_atrp': 0.6933520751573402, 'lookback_p_sharpe_trp': 0.6063818627830315, 'holding_p_gain': 0.1557372663005199, 'holding_p_sharpe': 38.76157962199495, 'holding_p_sharpe_atrp': 0.522993708635711, 'holding_p_sharpe_trp': 0.42591769143115193, 'full_b_gain': 0.08579734445868653, 'full_b_sharpe': 10.949522306673591, 'full_b_sharpe_atrp': 0.3891684118772243, 'full_b_sharpe_trp': 0.45751426966529196, 'lookback_b_gain': 0.06844737547915633, 'lookback_b_sharpe': 14.096177166249744, 'lookback_b_sharpe_atrp': 0.4682533773365875, 'lookback_b_sharpe_trp': 0.5606475436482259, 'holding_b_gain': 0.005336791499196458, 'holding_b_sharpe': 2.3401295978502965, 'holding_b_sharpe_atrp': 0.08793310536669856, 'holding_b_sharpe_trp': 0.10696619502502655}, results_df=        Rank  Strategy Value
Ticker
SOXL       1          0.5253
CRDO       2          0.5049
NBIS       3          0.4835, start_date=Timestamp('2026-04-01 00:00:00'), decision_date=Timestamp('2026-04-16 00:00:00'), buy_date=Timestamp('2026-04-17 00:00:00'), holding_end_date=Timestamp('2026-04-24 00:00:00'), portfolio_atrp_series=Date
2026-04-01    0.0953
2026-04-02    0.0933
2026-04-06    0.0881
2026-04-07    0.0834
2026-04-08    0.0786
2026-04-09    0.0748
2026-04-10    0.0718
2026-04-13    0.0689
2026-04-14    0.0659
2026-04-15    0.0639
2026-04-16    0.0653
2026-04-17    0.0650
2026-04-20    0.0626
2026-04-21    0.0605
2026-04-22    0.0588
2026-04-23    0.0596
2026-04-24    0.0605
dtype: float64, benchmark_atrp_series=Date
2026-04-01    0.0159
2026-04-02    0.0162
2026-04-06    0.0154
2026-04-07    0.0152
2026-04-08    0.0157
2026-04-09    0.0152
2026-04-10    0.0145
2026-04-13    0.0144
2026-04-14    0.0141
2026-04-15    0.0136
2026-04-16    0.0130
2026-04-17    0.0130
2026-04-20    0.0125
2026-04-21    0.0126
2026-04-22    0.0123
2026-04-23    0.0125
2026-04-24    0.0121
dtype: float64, portfolio_trp_series=Date
2026-04-01    0.0777
2026-04-02    0.1204
2026-04-06    0.0532
2026-04-07    0.0647
2026-04-08    0.1105
2026-04-09    0.0721
2026-04-10    0.1010
2026-04-13    0.0995
2026-04-14    0.1054
2026-04-15    0.0633
2026-04-16    0.0721
2026-04-17    0.0717
2026-04-20    0.0613
2026-04-21    0.0506
2026-04-22    0.0652
2026-04-23    0.0844
2026-04-24    0.1117
dtype: float64, benchmark_trp_series=Date
2026-04-01    0.0125
2026-04-02    0.0200
2026-04-06    0.0064
2026-04-07    0.0130
2026-04-08    0.0264
2026-04-09    0.0109
2026-04-10    0.0053
2026-04-13    0.0142
2026-04-14    0.0122
2026-04-15    0.0087
2026-04-16    0.0061
2026-04-17    0.0151
2026-04-20    0.0056
2026-04-21    0.0123
2026-04-22    0.0104
2026-04-23    0.0142
2026-04-24    0.0084
dtype: float64, error_msg=None, debug_data={'audit_liquidity': {'date': Timestamp('2026-04-16 00:00:00'), 'total_tickers_available': 1578, 'percentile_setting': 0.4, 'final_cutoff_usd': 102252047.09944001, 'tickers_passed': 941, 'universe_snapshot':            ATR    ATRP     TRP      RSI  Mom_21  Consistency   IR_63  Beta_63   DD_21  AutoCorr_15  Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5  Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount  Passed_Final
Ticker
A       3.1930  0.0270  0.0293  54.3418  0.0512          0.4 -0.2499   0.8866 -0.0178      -0.1328 -0.0127        0.7072     0.0074     0.0957    -0.0003              0.0        2.2616e+08                  0.0          True
AA      3.3635  0.0478  0.0378  58.2595  0.0763          0.4  0.0488   1.0655 -0.0396       0.2481  0.0004        0.7437    -0.0114    -0.0405    -0.0117              0.0        2.2739e+08                  0.0          True
AAL     0.5632  0.0459  0.0432  61.6207  0.1298          0.6 -0.1121   2.0561  0.0000      -0.0966  0.0082        0.8826     0.0242     0.7186     0.0132              0.0        7.3124e+08                  0.0          True
AAON    4.6710  0.0511  0.0317  56.5042  0.1521          0.6  0.0292   1.6886 -0.0248       0.0824 -0.0121        0.7558    -0.0047    -0.2545    -0.0219              0.0        7.7810e+07                  0.0         False
AAPL    5.8970  0.0224  0.0224  57.4298  0.0361          0.2  0.0005   0.9787 -0.0114      -0.3195 -0.0114        0.8263     0.0050    -0.3292     0.0055              0.0        1.0939e+10                  0.0          True
...        ...     ...     ...      ...     ...          ...     ...      ...     ...          ...     ...           ...        ...        ...        ...              ...               ...                  ...           ...
ZM      3.5157  0.0406  0.0510  59.8709  0.1407          0.4  0.0293   1.0152 -0.0264      -0.5145 -0.0264        0.7558     0.0252     0.1565     0.0287              0.0        2.2758e+08                  0.0          True
ZS      8.1369  0.0606  0.0520  44.3727 -0.1389          0.8 -0.1764   0.8997 -0.1389       0.1586  0.0253        0.4168     0.0325     1.1566     0.0555              0.0        4.4275e+08                  0.0          True
ZTO     0.6392  0.0253  0.0221  62.2596  0.0832          0.8  0.0966   0.1060  0.0000       0.0624  0.0088        0.8685     0.0042     0.4669    -0.0014              0.0        3.4584e+07                  0.0         False
ZTS     3.0579  0.0258  0.0250  49.1555 -0.0217          0.4 -0.0737   0.8548 -0.0171      -0.2915 -0.0142        0.6263     0.0026     0.0612     0.0002              0.0        4.6773e+08                  0.0          True
ZWS     1.4070  0.0303  0.0370  48.2899  0.0283          0.2 -0.0065   1.0202 -0.0625       0.0966 -0.0186        0.5059    -0.0098    -0.5339    -0.0200              0.0        3.6239e+07                  0.0         False

[1578 rows x 19 columns]}, 'full_universe_ranking':         Strategy_Score  Raw_Price_Start  Raw_Price_End  Raw_TRP_Mean  Raw_ATRP_Mean  Raw_Mom_21  Raw_IR_63  Raw_Consistency  Raw_RSI  Raw_DD_21  Raw_Range_Pos_20  Raw_Slope_P_5  Raw_Slope_V_5  Raw_Convexity  Raw_AutoCorr_15  Was_Dropped
Ticker
A               0.0319          114.540        118.250        0.0275         0.0273      0.0512    -0.2499              0.4  54.3418    -0.0178            0.7072         0.0074         0.0957        -0.0003          -0.1328        False
AA             -0.0232           72.060         70.410        0.0393         0.0512      0.0763     0.0488              0.4  58.2595    -0.0396            0.7437        -0.0114        -0.0405        -0.0117           0.2481        False
AAL             0.0975           11.130         12.270        0.0505         0.0491      0.1298    -0.1121              0.6  61.6207     0.0000            0.8826         0.0242         0.7186         0.0132          -0.0966        False
AAPL            0.0299          255.630        263.400        0.0241         0.0227      0.0361     0.0005              0.2  57.4298    -0.0114            0.8263         0.0050        -0.3292         0.0055          -0.3195        False
ABBV           -0.0200          213.211        208.990        0.0257         0.0272     -0.0411    -0.0554              0.4  46.4258    -0.0311            0.4824         0.0044        -0.0562         0.0085           0.1622        False
...                ...              ...            ...           ...            ...         ...        ...              ...      ...        ...               ...            ...            ...            ...              ...          ...
ZBH             0.0404           91.030         94.780        0.0224         0.0235      0.0272     0.0497              0.8  58.7640    -0.0180            0.7519         0.0023         0.3469        -0.0075          -0.1092        False
ZBRA            0.1171          207.280        233.040        0.0351         0.0390      0.1147    -0.0728              0.8  64.6796     0.0000            0.9795         0.0111         1.1141         0.0048          -0.2102        False
ZM              0.0715           80.700         86.680        0.0469         0.0364      0.1407     0.0293              0.4  59.8709    -0.0264            0.7558         0.0252         0.1565         0.0287          -0.5145        False
ZS             -0.0173          136.670        134.330        0.0617         0.0629     -0.1389    -0.1764              0.8  44.3727    -0.1389            0.4168         0.0325         1.1566         0.0555           0.1586        False
ZTS             0.0148          116.782        118.524        0.0235         0.0265     -0.0217    -0.0737              0.4  49.1555    -0.0171            0.6263         0.0026         0.0612         0.0002          -0.2915        False

[941 rows x 16 columns], 'meta': {'dropped_count': 0, 'dropped_tickers': [], 'clean_count': 941, 'selection_range': '1-3'}, 'inputs_snapshot': EngineInput(mode='Ranking', decision_date=Timestamp('2026-04-16 00:00:00'), lookback_period=10, holding_period=5, metric='Log Price Gain', benchmark_ticker='SPY', rank_start=1, rank_end=3, quality_thresholds={'min_median_dollar_volume': 1000000, 'min_liquidity_percentile': 0.4, 'max_stale_pct': 0.05, 'max_same_vol_count': 10}, manual_tickers=[], debug=True, universe_subset=None), 'alpha_perception':         Log Price Gain (Z)  Sharpe (TRP) (S)  Momentum (21d) (S)  Info Ratio (63d) (S)  Oversold (-RSI) (S)  Dip Buyer (-dd_21) (S)  Range Position (20d) (S)  Return Autocorr (15d) (S)  Low Volatility (-ATRP) (Z)  OBV Divergence (5d) (Z)  Convexity (Z)
Ticker
A                  -0.2587            0.1199              0.0512               -0.2499              -0.2171                  0.0178                    0.7072                    -0.1328                      0.3723                  -0.3246        -0.2221
AA                 -0.9423           -0.0559              0.0763                0.0488              -0.4130                  0.0396                    0.7437                     0.2481                     -1.0641                   1.0498        -0.9916
AAL                 0.5564            0.2032              0.1298               -0.1121              -0.5810                 -0.0000                    0.8826                    -0.0966                     -0.9374                  -0.1050         0.6860
AAPL               -0.2828            0.1283              0.0361                0.0005              -0.3715                  0.0114                    0.8263                    -0.3195                      0.6505                  -1.3257         0.1706
ABBV               -0.9030           -0.0732             -0.0411               -0.0554               0.1787                  0.0311                    0.4824                     0.1622                      0.3765                  -0.4849         0.3725
...                    ...               ...                 ...                   ...                  ...                     ...                       ...                        ...                         ...                      ...            ...
ZBH                -0.1533            0.1836              0.0272                0.0497              -0.4382                  0.0180                    0.7519                    -0.1092                      0.6026                   0.8769        -0.7123
ZBRA                0.8002            0.3403              0.1147               -0.0728              -0.7340                 -0.0000                    0.9795                    -0.2102                     -0.3300                   2.2627         0.1236
ZM                  0.2332            0.1665              0.1407                0.0293              -0.4935                  0.0264                    0.7558                    -0.5145                     -0.1761                  -1.8274         1.7354
ZS                 -0.8691           -0.0093             -0.1389               -0.1764               0.2814                  0.1389                    0.4168                     0.1586                     -1.7688                   0.3785         3.5451
ZTS                -0.4707            0.0667             -0.0217               -0.0737               0.0422                  0.0171                    0.6263                    -0.2915                      0.4232                   0.0306        -0.1884

[941 rows x 11 columns], 'verification': {'p': {'val': Date
2026-04-01    1.0000
2026-04-02    1.0448
2026-04-06    1.0736
2026-04-07    1.1157
2026-04-08    1.2222
2026-04-09    1.2799
2026-04-10    1.3768
2026-04-13    1.4861
2026-04-14    1.6280
2026-04-15    1.6786
2026-04-16    1.6565
2026-04-17    1.6761
2026-04-20    1.7388
2026-04-21    1.7746
2026-04-22    1.8428
2026-04-23    1.8776
2026-04-24    1.9774
dtype: float64, 'ret': Date
2026-04-01       NaN
2026-04-02    0.0448
2026-04-06    0.0276
2026-04-07    0.0392
2026-04-08    0.0955
2026-04-09    0.0472
2026-04-10    0.0757
2026-04-13    0.0794
2026-04-14    0.0955
2026-04-15    0.0311
2026-04-16   -0.0131
2026-04-17    0.0118
2026-04-20    0.0374
2026-04-21    0.0205
2026-04-22    0.0385
2026-04-23    0.0189
2026-04-24    0.0531
dtype: float64, 'atrp': Date
2026-04-01    0.0953
2026-04-02    0.0933
2026-04-06    0.0881
2026-04-07    0.0834
2026-04-08    0.0786
2026-04-09    0.0748
2026-04-10    0.0718
2026-04-13    0.0689
2026-04-14    0.0659
2026-04-15    0.0639
2026-04-16    0.0653
2026-04-17    0.0650
2026-04-20    0.0626
2026-04-21    0.0605
2026-04-22    0.0588
2026-04-23    0.0596
2026-04-24    0.0605
dtype: float64, 'trp': Date
2026-04-01    0.0777
2026-04-02    0.1204
2026-04-06    0.0532
2026-04-07    0.0647
2026-04-08    0.1105
2026-04-09    0.0721
2026-04-10    0.1010
2026-04-13    0.0995
2026-04-14    0.1054
2026-04-15    0.0633
2026-04-16    0.0721
2026-04-17    0.0717
2026-04-20    0.0613
2026-04-21    0.0506
2026-04-22    0.0652
2026-04-23    0.0844
2026-04-24    0.1117
dtype: float64}, 'b': {'val': Date
2026-04-01    1.0000
2026-04-02    1.0009
2026-04-06    1.0056
2026-04-07    1.0061
2026-04-08    1.0317
2026-04-09    1.0377
2026-04-10    1.0370
2026-04-13    1.0471
2026-04-14    1.0599
2026-04-15    1.0682
2026-04-16    1.0708
2026-04-17    1.0838
2026-04-20    1.0816
2026-04-21    1.0745
2026-04-22    1.0854
2026-04-23    1.0812
2026-04-24    1.0896
dtype: float64, 'ret': Date
2026-04-01       NaN
2026-04-02    0.0009
2026-04-06    0.0047
2026-04-07    0.0004
2026-04-08    0.0255
2026-04-09    0.0058
2026-04-10   -0.0007
2026-04-13    0.0098
2026-04-14    0.0122
2026-04-15    0.0079
2026-04-16    0.0025
2026-04-17    0.0121
2026-04-20   -0.0020
2026-04-21   -0.0065
2026-04-22    0.0101
2026-04-23   -0.0039
2026-04-24    0.0077
dtype: float64, 'atrp': Date
2026-04-01    0.0159
2026-04-02    0.0162
2026-04-06    0.0154
2026-04-07    0.0152
2026-04-08    0.0157
2026-04-09    0.0152
2026-04-10    0.0145
2026-04-13    0.0144
2026-04-14    0.0141
2026-04-15    0.0136
2026-04-16    0.0130
2026-04-17    0.0130
2026-04-20    0.0125
2026-04-21    0.0126
2026-04-22    0.0123
2026-04-23    0.0125
2026-04-24    0.0121
dtype: float64, 'trp': Date
2026-04-01    0.0125
2026-04-02    0.0200
2026-04-06    0.0064
2026-04-07    0.0130
2026-04-08    0.0264
2026-04-09    0.0109
2026-04-10    0.0053
2026-04-13    0.0142
2026-04-14    0.0122
2026-04-15    0.0087
2026-04-16    0.0061
2026-04-17    0.0151
2026-04-20    0.0056
2026-04-21    0.0123
2026-04-22    0.0104
2026-04-23    0.0142
2026-04-24    0.0084
dtype: float64}}, 'portfolio_raw_components': {'prices': Ticker        SOXL    CRDO    NBIS
Date
2026-04-01   52.26   95.92  101.95
2026-04-02   52.75  101.45  108.82
2026-04-06   54.81  102.46  112.54
2026-04-07   56.55  106.79  117.40
2026-04-08   67.50  110.21  125.00
2026-04-09   71.98  107.93  136.33
2026-04-10   76.39  119.59  144.97
2026-04-13   80.56  134.36  154.56
2026-04-14   85.31  159.52  161.94
2026-04-15   85.96  168.35  166.77
2026-04-16   88.37  158.93  165.34
2026-04-17   94.68  160.69  157.14
2026-04-20   95.94  174.53  159.16
2026-04-21   98.09  183.32  156.55
2026-04-22  105.64  189.49  156.14
2026-04-23  112.77  185.54  157.08
2026-04-24  128.32  195.04  147.16, 'atrp': Ticker        SOXL    CRDO    NBIS
Date
2026-04-01  0.1105  0.0872  0.0884
2026-04-02  0.1111  0.0845  0.0852
2026-04-06  0.1030  0.0813  0.0806
2026-04-07  0.0984  0.0761  0.0764
2026-04-08  0.0886  0.0737  0.0725
2026-04-09  0.0819  0.0742  0.0680
2026-04-10  0.0776  0.0708  0.0668
2026-04-13  0.0732  0.0671  0.0661
2026-04-14  0.0684  0.0656  0.0637
2026-04-15  0.0682  0.0618  0.0618
2026-04-16  0.0665  0.0675  0.0616
2026-04-17  0.0624  0.0678  0.0650
2026-04-20  0.0609  0.0638  0.0631
2026-04-21  0.0586  0.0603  0.0631
2026-04-22  0.0560  0.0574  0.0643
2026-04-23  0.0557  0.0599  0.0647
2026-04-24  0.0551  0.0578  0.0736, 'trp': Ticker        SOXL    CRDO    NBIS
Date
2026-04-01  0.1183  0.0510  0.0640
2026-04-02  0.1331  0.1113  0.1173
2026-04-06  0.0520  0.0508  0.0568
2026-04-07  0.0790  0.0504  0.0649
2026-04-08  0.1693  0.0739  0.0828
2026-04-09  0.0664  0.0600  0.0880
2026-04-10  0.0827  0.1202  0.1030
2026-04-13  0.0681  0.1212  0.1113
2026-04-14  0.0587  0.1838  0.0713
2026-04-15  0.0724  0.0561  0.0618
2026-04-16  0.0688  0.0950  0.0521
2026-04-17  0.0674  0.0803  0.0675
2026-04-20  0.0511  0.0826  0.0484
2026-04-21  0.0472  0.0542  0.0501
2026-04-22  0.0757  0.0450  0.0774
2026-04-23  0.0987  0.0761  0.0747
2026-04-24  0.1352  0.0689  0.1321, 'ohlcv_raw':                    Adj Open  Adj High  Adj Low  Adj Close     Volume
Ticker Date
SOXL   2026-04-01    50.040    54.090   49.620      52.26  121955600
       2026-04-02    46.060    53.070   46.050      52.75  104471700
       2026-04-06    53.750    55.600   52.880      54.81   68780400
       2026-04-07    54.320    56.600   52.130      56.55  107326500
       2026-04-08    66.330    67.980   63.560      67.50  111697300
       2026-04-09    68.120    72.280   68.120      71.98   79331600
       2026-04-10    74.300    78.300   74.300      76.39   78863600
       2026-04-13    75.590    80.740   75.250      80.56   64504600
       2026-04-14    83.270    85.570   80.710      85.31   61657000
       2026-04-15    84.660    85.980   79.760      85.96   68425400
       2026-04-16    85.010    89.390   83.310      88.37   63777500
       2026-04-17    93.200    94.750   90.660      94.68   67081400

EngineOutput(portfolio_series=Date
2026-04-01    1.0000
2026-04-02    1.0448
2026-04-06    1.0736
2026-04-07    1.1157
2026-04-08    1.2222
2026-04-09    1.2799
2026-04-10    1.3768
2026-04-13    1.4861
2026-04-14    1.6280
2026-04-15    1.6786
2026-04-16    1.6565
2026-04-17    1.6761
2026-04-20    1.7388
2026-04-21    1.7746
2026-04-22    1.8428
2026-04-23    1.8776
2026-04-24    1.9774
dtype: float64, benchmark_series=Date
2026-04-01    1.0000
2026-04-02    1.0009
2026-04-06    1.0056
2026-04-07    1.0061
2026-04-08    1.0317
2026-04-09    1.0377
2026-04-10    1.0370
2026-04-13    1.0471
2026-04-14    1.0599
2026-04-15    1.0682
2026-04-16    1.0708
2026-04-17    1.0838
2026-04-20    1.0816
2026-04-21    1.0745
2026-04-22    1.0854
2026-04-23    1.0812
2026-04-24    1.0896
dtype: float64, normalized_plot_data=Ticker        NBIS    SOXL    CRDO
Date
2026-04-01  1.0000  1.0000  1.0000
2026-04-02  1.0674  1.0094  1.0577
2026-04-06  1.1039  1.0488  1.0682
2026-04-07  1.1515  1.0821  1.1133
2026-04-08  1.2261  1.2916  1.1490
2026-04-09  1.3372  1.3773  1.1252
2026-04-10  1.4220  1.4617  1.2468
2026-04-13  1.5160  1.5415  1.4008
2026-04-14  1.5884  1.6324  1.6631
2026-04-15  1.6358  1.6449  1.7551
2026-04-16  1.6218  1.6910  1.6569
2026-04-17  1.5413  1.8117  1.6753
2026-04-20  1.5612  1.8358  1.8195
2026-04-21  1.5356  1.8770  1.9112
2026-04-22  1.5315  2.0214  1.9755
2026-04-23  1.5408  2.1579  1.9343
2026-04-24  1.4435  2.4554  2.0334, tickers=['SOXL', 'CRDO', 'NBIS'], initial_weights=SOXL    0.3333
CRDO    0.3333
NBIS    0.3333
dtype: float64, perf_metrics={'full_p_gain': 0.6817877455655165, 'full_p_sharpe': 23.107695909016513, 'full_p_sharpe_atrp': 0.627152382982204, 'full_p_sharpe_trp': 0.5379225630058191, 'lookback_p_gain': 0.5047361606600764, 'lookback_p_sharpe': 24.171188169091653, 'lookback_p_sharpe_atrp': 0.6933520751573402, 'lookback_p_sharpe_trp': 0.6063818627830315, 'holding_p_gain': 0.1557372663005199, 'holding_p_sharpe': 38.76157962199495, 'holding_p_sharpe_atrp': 0.522993708635711, 'holding_p_sharpe_trp': 0.42591769143115193, 'full_b_gain': 0.08579734445868653, 'full_b_sharpe': 10.949522306673591, 'full_b_sharpe_atrp': 0.3891684118772243, 'full_b_sharpe_trp': 0.45751426966529196, 'lookback_b_gain': 0.06844737547915633, 'lookback_b_sharpe': 14.096177166249744, 'lookback_b_sharpe_atrp': 0.4682533773365875, 'lookback_b_sharpe_trp': 0.5606475436482259, 'holding_b_gain': 0.005336791499196458, 'holding_b_sharpe': 2.3401295978502965, 'holding_b_sharpe_atrp': 0.08793310536669856, 'holding_b_sharpe_trp': 0.10696619502502655}, results_df=        Rank  Strategy Value
Ticker
SOXL       1          0.5253
CRDO       2          0.5049
NBIS       3          0.4835, start_date=Timestamp('2026-04-01 00:00:00'), decision_date=Timestamp('2026-04-16 00:00:00'), buy_date=Timestamp('2026-04-17 00:00:00'), holding_end_date=Timestamp('2026-04-24 00:00:00'), portfolio_atrp_series=Date
2026-04-01    0.0953
2026-04-02    0.0933
2026-04-06    0.0881
2026-04-07    0.0834
2026-04-08    0.0786
2026-04-09    0.0748
2026-04-10    0.0718
2026-04-13    0.0689
2026-04-14    0.0659
2026-04-15    0.0639
2026-04-16    0.0653
2026-04-17    0.0650
2026-04-20    0.0626
2026-04-21    0.0605
2026-04-22    0.0588
2026-04-23    0.0596
2026-04-24    0.0605
dtype: float64, benchmark_atrp_series=Date
2026-04-01    0.0159
2026-04-02    0.0162
2026-04-06    0.0154
2026-04-07    0.0152
2026-04-08    0.0157
2026-04-09    0.0152
2026-04-10    0.0145
2026-04-13    0.0144
2026-04-14    0.0141
2026-04-15    0.0136
2026-04-16    0.0130
2026-04-17    0.0130
2026-04-20    0.0125
2026-04-21    0.0126
2026-04-22    0.0123
2026-04-23    0.0125
2026-04-24    0.0121
dtype: float64, portfolio_trp_series=Date
2026-04-01    0.0777
2026-04-02    0.1204
2026-04-06    0.0532
2026-04-07    0.0647
2026-04-08    0.1105
2026-04-09    0.0721
2026-04-10    0.1010
2026-04-13    0.0995
2026-04-14    0.1054
2026-04-15    0.0633
2026-04-16    0.0721
2026-04-17    0.0717
2026-04-20    0.0613
2026-04-21    0.0506
2026-04-22    0.0652
2026-04-23    0.0844
2026-04-24    0.1117
dtype: float64, benchmark_trp_series=Date
2026-04-01    0.0125
2026-04-02    0.0200
2026-04-06    0.0064
2026-04-07    0.0130
2026-04-08    0.0264
2026-04-09    0.0109
2026-04-10    0.0053
2026-04-13    0.0142
2026-04-14    0.0122
2026-04-15    0.0087
2026-04-16    0.0061
2026-04-17    0.0151
2026-04-20    0.0056
2026-04-21    0.0123
2026-04-22    0.0104
2026-04-23    0.0142
2026-04-24    0.0084
dtype: float64, error_msg=None, debug_data={'audit_liquidity': {'date': Timestamp('2026-04-16 00:00:00'), 'total_tickers_available': 1578, 'percentile_setting': 0.4, 'final_cutoff_usd': 102252047.09944001, 'tickers_passed': 941, 'universe_snapshot':            ATR    ATRP     TRP      RSI  Mom_21  Consistency   IR_63  Beta_63   DD_21  AutoCorr_15  Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5  Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount  Passed_Final
Ticker
A       3.1930  0.0270  0.0293  54.3418  0.0512          0.4 -0.2499   0.8866 -0.0178      -0.1328 -0.0127        0.7072     0.0074     0.0957    -0.0003              0.0        2.2616e+08                  0.0          True
AA      3.3635  0.0478  0.0378  58.2595  0.0763          0.4  0.0488   1.0655 -0.0396       0.2481  0.0004        0.7437    -0.0114    -0.0405    -0.0117              0.0        2.2739e+08                  0.0          True
AAL     0.5632  0.0459  0.0432  61.6207  0.1298          0.6 -0.1121   2.0561  0.0000      -0.0966  0.0082        0.8826     0.0242     0.7186     0.0132              0.0        7.3124e+08                  0.0          True
AAON    4.6710  0.0511  0.0317  56.5042  0.1521          0.6  0.0292   1.6886 -0.0248       0.0824 -0.0121        0.7558    -0.0047    -0.2545    -0.0219              0.0        7.7810e+07                  0.0         False
AAPL    5.8970  0.0224  0.0224  57.4298  0.0361          0.2  0.0005   0.9787 -0.0114      -0.3195 -0.0114        0.8263     0.0050    -0.3292     0.0055              0.0        1.0939e+10                  0.0          True
...        ...     ...     ...      ...     ...          ...     ...      ...     ...          ...     ...           ...        ...        ...        ...              ...               ...                  ...           ...
ZM      3.5157  0.0406  0.0510  59.8709  0.1407          0.4  0.0293   1.0152 -0.0264      -0.5145 -0.0264        0.7558     0.0252     0.1565     0.0287              0.0        2.2758e+08                  0.0          True
ZS      8.1369  0.0606  0.0520  44.3727 -0.1389          0.8 -0.1764   0.8997 -0.1389       0.1586  0.0253        0.4168     0.0325     1.1566     0.0555              0.0        4.4275e+08                  0.0          True
ZTO     0.6392  0.0253  0.0221  62.2596  0.0832          0.8  0.0966   0.1060  0.0000       0.0624  0.0088        0.8685     0.0042     0.4669    -0.0014              0.0        3.4584e+07                  0.0         False
ZTS     3.0579  0.0258  0.0250  49.1555 -0.0217          0.4 -0.0737   0.8548 -0.0171      -0.2915 -0.0142        0.6263     0.0026     0.0612     0.0002              0.0        4.6773e+08                  0.0          True
ZWS     1.4070  0.0303  0.0370  48.2899  0.0283          0.2 -0.0065   1.0202 -0.0625       0.0966 -0.0186        0.5059    -0.0098    -0.5339    -0.0200              0.0        3.6239e+07                  0.0         False

[1578 rows x 19 columns]}, 'full_universe_ranking':         Strategy_Score  Raw_Price_Start  Raw_Price_End  Raw_TRP_Mean  Raw_ATRP_Mean  Raw_Mom_21  Raw_IR_63  Raw_Consistency  Raw_RSI  Raw_DD_21  Raw_Range_Pos_20  Raw_Slope_P_5  Raw_Slope_V_5  Raw_Convexity  Raw_AutoCorr_15  Was_Dropped
Ticker
A               0.0319          114.540        118.250        0.0275         0.0273      0.0512    -0.2499              0.4  54.3418    -0.0178            0.7072         0.0074         0.0957        -0.0003          -0.1328        False
AA             -0.0232           72.060         70.410        0.0393         0.0512      0.0763     0.0488              0.4  58.2595    -0.0396            0.7437        -0.0114        -0.0405        -0.0117           0.2481        False
AAL             0.0975           11.130         12.270        0.0505         0.0491      0.1298    -0.1121              0.6  61.6207     0.0000            0.8826         0.0242         0.7186         0.0132          -0.0966        False
AAPL            0.0299          255.630        263.400        0.0241         0.0227      0.0361     0.0005              0.2  57.4298    -0.0114            0.8263         0.0050        -0.3292         0.0055          -0.3195        False
ABBV           -0.0200          213.211        208.990        0.0257         0.0272     -0.0411    -0.0554              0.4  46.4258    -0.0311            0.4824         0.0044        -0.0562         0.0085           0.1622        False
...                ...              ...            ...           ...            ...         ...        ...              ...      ...        ...               ...            ...            ...            ...              ...          ...
ZBH             0.0404           91.030         94.780        0.0224         0.0235      0.0272     0.0497              0.8  58.7640    -0.0180            0.7519         0.0023         0.3469        -0.0075          -0.1092        False
ZBRA            0.1171          207.280        233.040        0.0351         0.0390      0.1147    -0.0728              0.8  64.6796     0.0000            0.9795         0.0111         1.1141         0.0048          -0.2102        False
ZM              0.0715           80.700         86.680        0.0469         0.0364      0.1407     0.0293              0.4  59.8709    -0.0264            0.7558         0.0252         0.1565         0.0287          -0.5145        False
ZS             -0.0173          136.670        134.330        0.0617         0.0629     -0.1389    -0.1764              0.8  44.3727    -0.1389            0.4168         0.0325         1.1566         0.0555           0.1586        False
ZTS             0.0148          116.782        118.524        0.0235         0.0265     -0.0217    -0.0737              0.4  49.1555    -0.0171            0.6263         0.0026         0.0612         0.0002          -0.2915        False

[941 rows x 16 columns], 'meta': {'dropped_count': 0, 'dropped_tickers': [], 'clean_count': 941, 'selection_range': '1-3'}, 'inputs_snapshot': EngineInput(mode='Ranking', decision_date=Timestamp('2026-04-16 00:00:00'), lookback_period=10, holding_period=5, metric='Log Price Gain', benchmark_ticker='SPY', rank_start=1, rank_end=3, quality_thresholds={'min_median_dollar_volume': 1000000, 'min_liquidity_percentile': 0.4, 'max_stale_pct': 0.05, 'max_same_vol_count': 10}, manual_tickers=[], debug=True, universe_subset=None), 'alpha_perception':         Log Price Gain (Z)  Sharpe (TRP) (S)  Momentum (21d) (S)  Info Ratio (63d) (S)  Oversold (-RSI) (S)  Dip Buyer (-dd_21) (S)  Range Position (20d) (S)  Return Autocorr (15d) (S)  Low Volatility (-ATRP) (Z)  OBV Divergence (5d) (Z)  Convexity (Z)
Ticker
A                  -0.2587            0.1199              0.0512               -0.2499              -0.2171                  0.0178                    0.7072                    -0.1328                      0.3723                  -0.3246        -0.2221
AA                 -0.9423           -0.0559              0.0763                0.0488              -0.4130                  0.0396                    0.7437                     0.2481                     -1.0641                   1.0498        -0.9916
AAL                 0.5564            0.2032              0.1298               -0.1121              -0.5810                 -0.0000                    0.8826                    -0.0966                     -0.9374                  -0.1050         0.6860
AAPL               -0.2828            0.1283              0.0361                0.0005              -0.3715                  0.0114                    0.8263                    -0.3195                      0.6505                  -1.3257         0.1706
ABBV               -0.9030           -0.0732             -0.0411               -0.0554               0.1787                  0.0311                    0.4824                     0.1622                      0.3765                  -0.4849         0.3725
...                    ...               ...                 ...                   ...                  ...                     ...                       ...                        ...                         ...                      ...            ...
ZBH                -0.1533            0.1836              0.0272                0.0497              -0.4382                  0.0180                    0.7519                    -0.1092                      0.6026                   0.8769        -0.7123
ZBRA                0.8002            0.3403              0.1147               -0.0728              -0.7340                 -0.0000                    0.9795                    -0.2102                     -0.3300                   2.2627         0.1236
ZM                  0.2332            0.1665              0.1407                0.0293              -0.4935                  0.0264                    0.7558                    -0.5145                     -0.1761                  -1.8274         1.7354
ZS                 -0.8691           -0.0093             -0.1389               -0.1764               0.2814                  0.1389                    0.4168                     0.1586                     -1.7688                   0.3785         3.5451
ZTS                -0.4707            0.0667             -0.0217               -0.0737               0.0422                  0.0171                    0.6263                    -0.2915                      0.4232                   0.0306        -0.1884

[941 rows x 11 columns], 'verification': {'p': {'val': Date
2026-04-01    1.0000
2026-04-02    1.0448
2026-04-06    1.0736
2026-04-07    1.1157
2026-04-08    1.2222
2026-04-09    1.2799
2026-04-10    1.3768
2026-04-13    1.4861
2026-04-14    1.6280
2026-04-15    1.6786
2026-04-16    1.6565
2026-04-17    1.6761
2026-04-20    1.7388
2026-04-21    1.7746
2026-04-22    1.8428
2026-04-23    1.8776
2026-04-24    1.9774
dtype: float64, 'ret': Date
2026-04-01       NaN
2026-04-02    0.0448
2026-04-06    0.0276
2026-04-07    0.0392
2026-04-08    0.0955
2026-04-09    0.0472
2026-04-10    0.0757
2026-04-13    0.0794
2026-04-14    0.0955
2026-04-15    0.0311
2026-04-16   -0.0131
2026-04-17    0.0118
2026-04-20    0.0374
2026-04-21    0.0205
2026-04-22    0.0385
2026-04-23    0.0189
2026-04-24    0.0531
dtype: float64, 'atrp': Date
2026-04-01    0.0953
2026-04-02    0.0933
2026-04-06    0.0881
2026-04-07    0.0834
2026-04-08    0.0786
2026-04-09    0.0748
2026-04-10    0.0718
2026-04-13    0.0689
2026-04-14    0.0659
2026-04-15    0.0639
2026-04-16    0.0653
2026-04-17    0.0650
2026-04-20    0.0626
2026-04-21    0.0605
2026-04-22    0.0588
2026-04-23    0.0596
2026-04-24    0.0605
dtype: float64, 'trp': Date
2026-04-01    0.0777
2026-04-02    0.1204
2026-04-06    0.0532
2026-04-07    0.0647
2026-04-08    0.1105
2026-04-09    0.0721
2026-04-10    0.1010
2026-04-13    0.0995
2026-04-14    0.1054
2026-04-15    0.0633
2026-04-16    0.0721
2026-04-17    0.0717
2026-04-20    0.0613
2026-04-21    0.0506
2026-04-22    0.0652
2026-04-23    0.0844
2026-04-24    0.1117
dtype: float64}, 'b': {'val': Date
2026-04-01    1.0000
2026-04-02    1.0009
2026-04-06    1.0056
2026-04-07    1.0061
2026-04-08    1.0317
2026-04-09    1.0377
2026-04-10    1.0370
2026-04-13    1.0471
2026-04-14    1.0599
2026-04-15    1.0682
2026-04-16    1.0708
2026-04-17    1.0838
2026-04-20    1.0816
2026-04-21    1.0745
2026-04-22    1.0854
2026-04-23    1.0812
2026-04-24    1.0896
dtype: float64, 'ret': Date
2026-04-01       NaN
2026-04-02    0.0009
2026-04-06    0.0047
2026-04-07    0.0004
2026-04-08    0.0255
2026-04-09    0.0058
2026-04-10   -0.0007
2026-04-13    0.0098
2026-04-14    0.0122
2026-04-15    0.0079
2026-04-16    0.0025
2026-04-17    0.0121
2026-04-20   -0.0020
2026-04-21   -0.0065
2026-04-22    0.0101
2026-04-23   -0.0039
2026-04-24    0.0077
dtype: float64, 'atrp': Date
2026-04-01    0.0159
2026-04-02    0.0162
2026-04-06    0.0154
2026-04-07    0.0152
2026-04-08    0.0157
2026-04-09    0.0152
2026-04-10    0.0145
2026-04-13    0.0144
2026-04-14    0.0141
2026-04-15    0.0136
2026-04-16    0.0130
2026-04-17    0.0130
2026-04-20    0.0125
2026-04-21    0.0126
2026-04-22    0.0123
2026-04-23    0.0125
2026-04-24    0.0121
dtype: float64, 'trp': Date
2026-04-01    0.0125
2026-04-02    0.0200
2026-04-06    0.0064
2026-04-07    0.0130
2026-04-08    0.0264
2026-04-09    0.0109
2026-04-10    0.0053
2026-04-13    0.0142
2026-04-14    0.0122
2026-04-15    0.0087
2026-04-16    0.0061
2026-04-17    0.0151
2026-04-20    0.0056
2026-04-21    0.0123
2026-04-22    0.0104
2026-04-23    0.0142
2026-04-24    0.0084
dtype: float64}}, 'portfolio_raw_components': {'prices': Ticker        SOXL    CRDO    NBIS
Date
2026-04-01   52.26   95.92  101.95
2026-04-02   52.75  101.45  108.82
2026-04-06   54.81  102.46  112.54
2026-04-07   56.55  106.79  117.40
2026-04-08   67.50  110.21  125.00
2026-04-09   71.98  107.93  136.33
2026-04-10   76.39  119.59  144.97
2026-04-13   80.56  134.36  154.56
2026-04-14   85.31  159.52  161.94
2026-04-15   85.96  168.35  166.77
2026-04-16   88.37  158.93  165.34
2026-04-17   94.68  160.69  157.14
2026-04-20   95.94  174.53  159.16
2026-04-21   98.09  183.32  156.55
2026-04-22  105.64  189.49  156.14
2026-04-23  112.77  185.54  157.08
2026-04-24  128.32  195.04  147.16, 'atrp': Ticker        SOXL    CRDO    NBIS
Date
2026-04-01  0.1105  0.0872  0.0884
2026-04-02  0.1111  0.0845  0.0852
2026-04-06  0.1030  0.0813  0.0806
2026-04-07  0.0984  0.0761  0.0764
2026-04-08  0.0886  0.0737  0.0725
2026-04-09  0.0819  0.0742  0.0680
2026-04-10  0.0776  0.0708  0.0668
2026-04-13  0.0732  0.0671  0.0661
2026-04-14  0.0684  0.0656  0.0637
2026-04-15  0.0682  0.0618  0.0618
2026-04-16  0.0665  0.0675  0.0616
2026-04-17  0.0624  0.0678  0.0650
2026-04-20  0.0609  0.0638  0.0631
2026-04-21  0.0586  0.0603  0.0631
2026-04-22  0.0560  0.0574  0.0643
2026-04-23  0.0557  0.0599  0.0647
2026-04-24  0.0551  0.0578  0.0736, 'trp': Ticker        SOXL    CRDO    NBIS
Date
2026-04-01  0.1183  0.0510  0.0640
2026-04-02  0.1331  0.1113  0.1173
2026-04-06  0.0520  0.0508  0.0568
2026-04-07  0.0790  0.0504  0.0649
2026-04-08  0.1693  0.0739  0.0828
2026-04-09  0.0664  0.0600  0.0880
2026-04-10  0.0827  0.1202  0.1030
2026-04-13  0.0681  0.1212  0.1113
2026-04-14  0.0587  0.1838  0.0713
2026-04-15  0.0724  0.0561  0.0618
2026-04-16  0.0688  0.0950  0.0521
2026-04-17  0.0674  0.0803  0.0675
2026-04-20  0.0511  0.0826  0.0484
2026-04-21  0.0472  0.0542  0.0501
2026-04-22  0.0757  0.0450  0.0774
2026-04-23  0.0987  0.0761  0.0747
2026-04-24  0.1352  0.0689  0.1321, 'ohlcv_raw':                    Adj Open  Adj High  Adj Low  Adj Close     Volume
Ticker Date
SOXL   2026-04-01    50.040    54.090   49.620      52.26  121955600
       2026-04-02    46.060    53.070   46.050      52.75  104471700
       2026-04-06    53.750    55.600   52.880      54.81   68780400
       2026-04-07    54.320    56.600   52.130      56.55  107326500
       2026-04-08    66.330    67.980   63.560      67.50  111697300
       2026-04-09    68.120    72.280   68.120      71.98   79331600
       2026-04-10    74.300    78.300   74.300      76.39   78863600
       2026-04-13    75.590    80.740   75.250      80.56   64504600
       2026-04-14    83.270    85.570   80.710      85.31   61657000
       2026-04-15    84.660    85.980   79.760      85.96   68425400
       2026-04-16    85.010    89.390   83.310      88.37   63777500
       2026-04-17    93.200    94.750   90.660      94.68   67081400

In [21]:
features_df.loc["TSLA"]

                ATR    ATRP     TRP      RSI  Mom_21  Consistency   IR_63  Beta_63   DD_21  AutoCorr_15  Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5  Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount
Date
2010-06-29      NaN  0.0000  0.0000  50.0000     NaN          NaN     NaN   1.0000  0.0000       0.0000     NaN           NaN        NaN        NaN     0.0000              NaN               NaN                  NaN
2010-06-30   0.4747  0.2988  0.2988   0.0000     NaN          NaN     NaN   1.0000  0.0000       0.0000 -0.0025           NaN        NaN        NaN     0.0000              NaN               NaN                  NaN
2010-07-01   0.4677  0.3194  0.2573   0.0000     NaN          NaN     NaN   1.0000  0.0000       0.0000 -0.0785           NaN        NaN        NaN     0.0000              NaN               NaN                  NaN
2010-07-02   0.4552  0.3556  0.2286   0.0000     NaN          NaN     NaN   1.0000  0.0000       0.0000 -0.1257           NaN        NaN        NaN     0.0000              NaN               NaN                  NaN
2010-07-06   0.4425  0.4120  0.2588   0.0000     NaN          0.0     NaN   1.0000  0.0000       0.0000 -0.1609           NaN    -0.1004    -0.6060     0.0000              NaN               NaN                  NaN
...             ...     ...     ...      ...     ...          ...     ...      ...     ...          ...     ...           ...        ...        ...        ...              ...               ...                  ...
2026-04-28  14.6863  0.0391  0.0259  48.7541  0.0392          0.6 -0.1180   1.6338 -0.0614       0.1197 -0.0070        0.5383    -0.0047     0.1559     0.0071              0.0        2.8875e+10                  0.0
2026-04-29  14.0916  0.0378  0.0171  47.1592  0.0493          0.4 -0.1258   1.6349 -0.0694       0.1039 -0.0086        0.4936    -0.0006     0.1315     0.0064              0.0        2.8776e+10                  0.0
2026-04-30  14.2693  0.0374  0.0434  51.8141  0.0266          0.6 -0.0898   1.6384 -0.0474       0.0782  0.0237        0.6162     0.0013    -0.0814     0.0060              0.0        2.8642e+10                  0.0
2026-05-01  14.6087  0.0374  0.0487  56.1443  0.0251          0.6 -0.1041   1.6728 -0.0245       0.1042  0.0241        0.7438     0.0078     0.0765     0.0084              0.0        2.8534e+10                  0.0
2026-05-04  14.2680  0.0364  0.0251  56.9111  0.0885          0.6 -0.0774   1.6831 -0.0202       0.0968  0.0043        0.7672     0.0133     0.5648     0.0121              0.0        2.8534e+10                  0.0

[3986 rows x 18 columns]