 # Section 1: Setup, Unified Paths & Global Settings

 This cell loads essential utilities, configures global Pandas display parameters,

 silences silent-downcasting warnings, and dynamically maps project directories.

In [ ]:
%load_ext autoreload
%autoreload 2

import ast
from pathlib import Path

import numpy as np
import pandas as pd

from core.contracts import EngineInput, FilterPack
from core.paths import (
    GLOBAL_DATA_DIR,
    GLOBAL_PROCESSED_DIR,
    LOCAL_DATA_DIR,
    NOTEBOOKS_RLVR_ROOT,
    OUTPUT_DIR,
    PROJECT_ROOT,
)
from core.settings import TradingConfig
from core.utils import SystemUtils as SU
from data_pipeline import generate_features
from walk_forward import (
    AlphaEngine,
    create_walk_forward_analyzer,
    run_headless_simulation,
)

# 1. Global Configuration Options
config = TradingConfig()

# 2. Silence downcasting warnings & configure wide DataFrame display options
pd.set_option("future.no_silent_downcasting", True)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", 3000)

# 3. Path Selection Toggle (Set USE_LOCAL_DATA = False to switch to GLOBAL_DATA_DIR)
USE_LOCAL_DATA = True

data_dir = LOCAL_DATA_DIR if USE_LOCAL_DATA else GLOBAL_DATA_DIR
processed_dir = GLOBAL_PROCESSED_DIR
output_dir = OUTPUT_DIR

print(
    f"Paths Resolved:\n"
    f" - Project Root:         {PROJECT_ROOT}\n"
    f" - Notebooks RLVR Root:  {NOTEBOOKS_RLVR_ROOT}\n"
    f" - Global Data Dir:      {GLOBAL_DATA_DIR}\n"
    f" - Global Processed Dir: {GLOBAL_PROCESSED_DIR}\n"
    f" - Local Data Dir:       {LOCAL_DATA_DIR}\n"
    f" - Output Dir:           {OUTPUT_DIR}\n\n"
    f" - Active Data Dir:      {data_dir} ({'LOCAL' if USE_LOCAL_DATA else 'GLOBAL'})\n"
)

# Define Raw File Paths using selected data_dir
source_type = "LOCAL_DATA_DIR" if USE_LOCAL_DATA else "GLOBAL_DATA_DIR"
print(f"\nLoading files from {source_type}: {data_dir}")

ohlcv_filename = "df_ohlcv.parquet" if USE_LOCAL_DATA else "df_OHLCV_stocks_etfs.parquet"
fed_filename = "df_fed.parquet" if USE_LOCAL_DATA else "High_Yield_Spread_T10Y2Y_Spread.parquet"

df_ohlcv_path = data_dir / ohlcv_filename
df_fed_path = data_dir / fed_filename
df_indices_path = data_dir / "df_indices.parquet"

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Paths Resolved:
 - Project Root:         C:\Users\ping\Files_win10\python\py311\stocks
 - Notebooks RLVR Root:  C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2
 - Global Data Dir:      C:\Users\ping\Files_win10\python\py311\stocks\data
 - Global Processed Dir: C:\Users\ping\Files_win10\python\py311\stocks\data\processed
 - Local Data Dir:       C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\data
 - Output Dir:           C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\output

 - Active Data Dir:      C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\data (LOCAL)


Loading files from LOCAL_DATA_DIR: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\data

 # Section 2: Ingest Raw and Processed Datasets

 Safely loads raw inputs and previously stored processed matrices with existence verifications.

In [67]:
# # Define Raw File Paths
# df_ohlcv_path = data_dir / "df_OHLCV_stocks_etfs.parquet"
# df_fed_path = data_dir / "High_Yield_Spread_T10Y2Y_Spread.csv"
# df_indices_path = data_dir / "df_indices.parquet"

# Load Raw Files
if df_ohlcv_path.exists():
    df_ohlcv = pd.read_parquet(df_ohlcv_path)
    print("[OK] Successfully loaded df_ohlcv!")
else:
    print(f"[ERROR] File not found: {df_ohlcv_path}")

if df_fed_path.exists():
    # df_fed = pd.read_csv(df_fed_path)
    df_fed = pd.read_parquet(df_fed_path)
    print("[OK] Successfully loaded df_fed!")
else:
    print(f"[ERROR] File not found: {df_fed_path}")

if df_indices_path.exists():
    df_indices = pd.read_parquet(df_indices_path)
    print("[OK] Successfully loaded df_indices!")
else:
    print(f"[ERROR] File not found: {df_indices_path}")

[OK] Successfully loaded df_ohlcv!
[OK] Successfully loaded df_fed!
[OK] Successfully loaded df_indices!

In [68]:
# Define Processed File Paths
features_df_path = data_dir / "features_df.parquet"
macro_df_path = data_dir / "macro_df.parquet"
# features_df_path = current_dir / "data" / "features_df.parquet"
# macro_df_path = current_dir / "data" / "macro_df.parquet"
# df_close_wide_path = processed_dir / "df_close_wide.parquet"
# df_atrp_wide_path = processed_dir / "df_atrp_wide.parquet"
# df_trp_wide_path = processed_dir / "df_trp_wide.parquet"

# Load Processed Files
if features_df_path.exists():
    features_df = pd.read_parquet(features_df_path)
    print(f"[OK] Loaded features_df  | Shape: {features_df.shape}")
else:
    print(f"[ERROR] File not found: {features_df_path}")

if macro_df_path.exists():
    macro_df = pd.read_parquet(macro_df_path)
    print(f"[OK] Loaded macro_df     | Shape: {macro_df.shape}")
else:
    print(f"[ERROR] File not found: {macro_df_path}")

# if df_close_wide_path.exists():
#     df_close_wide = pd.read_parquet(df_close_wide_path)
#     print(f"[OK] Loaded df_close_wide| Shape: {df_close_wide.shape}")
# else:
#     print(f"[ERROR] File not found: {df_close_wide_path}")

# if df_atrp_wide_path.exists():
#     df_atrp_wide = pd.read_parquet(df_atrp_wide_path)
#     print(f"[OK] Loaded df_atrp_wide | Shape: {df_atrp_wide.shape}")
# else:
#     print(f"[ERROR] File not found: {df_atrp_wide_path}")

# if df_trp_wide_path.exists():
#     df_trp_wide = pd.read_parquet(df_trp_wide_path)
#     print(f"[OK] Loaded df_trp_wide  | Shape: {df_trp_wide.shape}")
# else:
#     print(f"[ERROR] File not found: {df_trp_wide_path}")

[ERROR] File not found: C:\Users\ping\Files_win10\python\py311\stocks\data\features_df.parquet
[ERROR] File not found: C:\Users\ping\Files_win10\python\py311\stocks\data\macro_df.parquet

In [69]:
print("🚀 Unstacking Wide Matrices...")

# 1. Unstack directly.
# (Since df_ohlcv is already a perfect grid of master_dates x tickers,
# unstacking automatically creates perfectly aligned wide dataframes).
df_close_wide = df_ohlcv["Adj Close"].unstack(level=0)
df_atrp_wide = features_df["ATRP"].unstack(level=0)
df_trp_wide = features_df["TRP"].unstack(level=0)

print("Applying terminal NaN replacements for model inputs...")

# 2. Terminal Fills ONLY.
# Note: 0-to-NaN conversion and bounded ffills were ALREADY applied upstream to df_ohlcv.
# Applying ffill here would incorrectly double your max_data_gap_ffill limit!
df_close_wide = df_close_wide.fillna(config.nan_price_replacement)
df_atrp_wide = df_atrp_wide.fillna(0.0)
df_trp_wide = df_trp_wide.fillna(0.0)

print("All wide dataframes unstacked and prepared for downstream modeling.")
print(
    f"[OK] Pipeline Complete. Tickers: {len(df_close_wide.columns)}, Days: {len(df_close_wide)}"
)

🚀 Unstacking Wide Matrices...
Applying terminal NaN replacements for model inputs...
All wide dataframes unstacked and prepared for downstream modeling.
[OK] Pipeline Complete. Tickers: 1576, Days: 8423

In [70]:
# # Define Processed File Paths
# features_df_path = processed_dir / "features_df.parquet"
# macro_df_path = processed_dir / "macro_df.parquet"
# df_close_wide_path = processed_dir / "df_close_wide.parquet"
# df_atrp_wide_path = processed_dir / "df_atrp_wide.parquet"
# df_trp_wide_path = processed_dir / "df_trp_wide.parquet"

# # Load Processed Files
# if features_df_path.exists():
#     features_df = pd.read_parquet(features_df_path)
#     print(f"[OK] Loaded features_df  | Shape: {features_df.shape}")
# else:
#     print(f"[ERROR] File not found: {features_df_path}")

# if macro_df_path.exists():
#     macro_df = pd.read_parquet(macro_df_path)
#     print(f"[OK] Loaded macro_df     | Shape: {macro_df.shape}")
# else:
#     print(f"[ERROR] File not found: {macro_df_path}")

# if df_close_wide_path.exists():
#     df_close_wide = pd.read_parquet(df_close_wide_path)
#     print(f"[OK] Loaded df_close_wide| Shape: {df_close_wide.shape}")
# else:
#     print(f"[ERROR] File not found: {df_close_wide_path}")

# if df_atrp_wide_path.exists():
#     df_atrp_wide = pd.read_parquet(df_atrp_wide_path)
#     print(f"[OK] Loaded df_atrp_wide | Shape: {df_atrp_wide.shape}")
# else:
#     print(f"[ERROR] File not found: {df_atrp_wide_path}")

# if df_trp_wide_path.exists():
#     df_trp_wide = pd.read_parquet(df_trp_wide_path)
#     print(f"[OK] Loaded df_trp_wide  | Shape: {df_trp_wide.shape}")
# else:
#     print(f"[ERROR] File not found: {df_trp_wide_path}")

 # Section 3: In-Memory Structural Previews

 Outputs head and tail previews of the core dataframes.

In [71]:
print("\n" + "=" * 50)
print("DATAFRAME STRUCTURAL PREVIEWS (HEAD & TAIL)")
print("=" * 50)

# 1. Preview wide matrix prices
if "df_close_wide" in locals():
    print("\n=== df_close_wide (Prices) ===")
    print("--- HEAD (First 3 Rows) ---")
    display(df_close_wide.head(3))
    print("\n--- TAIL (Last 3 Rows) ---")
    display(df_close_wide.tail(3))

# 2. Preview multi-index features
if "features_df" in locals():
    print("\n=== features_df (Multi-Index Features) ===")
    print("--- HEAD (First 3 Rows) ---")
    display(features_df.head(3))
    print("\n--- TAIL (Last 3 Rows) ---")
    display(features_df.tail(3))

# 3. Preview macro data
if "macro_df" in locals():
    print("\n=== macro_df (Macro Data) ===")
    print("--- HEAD (First 3 Rows) ---")
    display(macro_df.head(3))
    print("\n--- TAIL (Last 3 Rows) ---")
    display(macro_df.tail(3))

==================================================
DATAFRAME STRUCTURAL PREVIEWS (HEAD & TAIL)
==================================================

=== df_close_wide (Prices) ===
--- HEAD (First 3 Rows) ---

Ticker,091160.KS,2330.TW,A,AA,AAL,AAON,AAPL,ABBV,ABEV,ABNB,ABT,ABVX,ACGL,ACI,ACM,ACN,ACWI,ACWX,ADBE,ADC,ADI,ADM,ADP,ADSK,ADT,AEE,AEG,AEIS,AEM,AEP,AER,AES,AFG,AFL,AFRM,AG,AGCO,AGG,AGI,AGNC,AHR,AIG,AIQ,AIRR,AIT,AIZ,AJG,AKAM,AKRE,ALAB,ALB,ALC,ALGN,ALL,ALLE,ALLY,ALNY,ALSN,ALV,AM,AMAT,AMCR,AMD,AME,AMG,AMGN,AMH,AMKR,AMLP,AMP,AMRZ,AMT,AMTM,AMX,AMZN,AN,ANET,AON,AOS,APA,APD,APG,APH,APLD,APO,APP,APPF,APTV,AR,ARCC,ARE,ARES,ARGX,ARKK,ARM,ARMK,ARWR,AS,ASML,ASND,ASR,ASTS,ASX,ATI,ATO,ATR,AU,AUR,AVAV,AVB,AVDE,AVDV,AVEM,AVGO,AVLV,AVTR,AVUS,AVUV,AVY,AWI,AWK,AXIA,AXON,AXP,AXS,AXSM,AXTA,AYI,AZN,AZO,B,BA,BABA,BAC,BAH,BAI,BALL,BAM,BAP,BAX,BBAX,BBCA,BBD,BBEU,BBIN,BBIO,BBJP,BBUS,BBVA,BBY,BCE,BCH,BCS,BDX,BE,BEKE,BEN,BEP,BEPC,BETA,BF-A,BF-B,BG,BHP,BIDU,BIIB,BIL,BILI,BINC,BIO,BIP,BIRK,BIV,BJ,BK,BKLC,BKLN,BKNG,BKR,BLD,BLDR,BLK,BLSH,BLV,BMNR,BMO,BMRN,BMY,BN,BND,BNDX,BNO,BNS,BNT,BNTX,BOKF,BOND,BOXX,BP,BPOP,BR,BRK-A,BRK-B,BRKR,BRO,BROS,BRX,BSAC,BSBR,BSCQ,BSCR,BSOL,BSV,BSX,BSY,BTC,BTI,BUD,BUFR,BURL,BVN,BWA,BWXT,BX,BXP,BYD,BZ,C,CACI,CAE,CAG,CAH,CAI,CARR,CART,CASY,CAT,CB,CBOE,CBRE,CBSH,CCEP,CCI,CCJ,CCK,CCL,CDE,CDNS,CDP,CDW,CEF,CEG,CELH,CF,CFG,CFR,CG,CGBL,CGCP,CGDV,CGGO,CGGR,CGMU,CGUS,CGXU,CHD,CHDN,CHKP,CHRW,CHT,CHTR,CHWY,CHYM,CI,CIB,CIBR,CIEN,CIFR,CIGI,CINF,CL,CLF,CLH,CLS,CLX,CM,CMC,CMCSA,CME,CMG,CMI,CMS,CNA,CNC,CNH,CNI,CNM,CNP,CNQ,COF,COHR,COIN,COKE,COLB,COO,COP,COPX,COR,CORT,COST,COWZ,CP,CPAY,CPB,CPNG,CPRT,CPT,CQP,CR,CRBG,CRCL,CRDO,CRH,CRK,CRL,CRM,CRS,CRWD,CRWV,CSCO,CSGP,CSL,CSX,CTAS,CTRE,CTSH,CTVA,CUBE,CVE,CVNA,CVS,CVX,CW,CWB,CWEN,CX,CYTK,D,DAL,DASH,DB,DBEF,DBX,DCI,DD,DDOG,DDS,DE,DECK,DELL,DEO,DFAC,DFAE,DFAI,DFAS,DFAT,DFAU,DFAX,DFCF,DFEM,DFIC,DFIS,DFIV,DFLV,DFSD,DFSV,DFUS,DFUV,DG,DGRO,DGRW,DGX,DHI,DHR,DIA,DIHP,DINO,DIS,DIVO,DKNG,DKS,DLN,DLR,DLTR,DOC,DOCS,DOCU,DON,DOV,DOW,DOX,DPZ,DRI,DRS,DSGX,DSI,DT,DTE,DTM,DUHP,DUK,DUOL,DVA,DVN,DVY,DXCM,DXJ,DY,DYNF,E,EA,EAGG,EBAY,EC,ECL,ED,EDU,EDV,EEM,EFA,EFAV,EFG,EFV,EFX,EG,EGO,EGP,EHC,EIX,EL,ELAN,ELS,ELV,EMA,EMB,EMBJ,EME,EMLC,EMN,EMR,EMXC,ENB,ENSG,ENTG,EOG,EPAM,EPD,EQH,EQIX,EQNR,EQR,EQT,EQX,ERIC,ERIE,ES,ESAB,ESGD,ESGE,ESGU,ESGV,ESLT,ESS,ESTC,ET,ETHA,ETHB,ETN,ETR,EUFN,EVR,EVRG,EVTR,EW,EWBC,EWJ,EWT,EWY,EWZ,EXC,EXE,EXEL,EXLS,EXP,EXPD,EXPE,EXR,EZU,F,FAF,FANG,FAST,FBCG,FBND,FBTC,FCFS,FCNCA,FCX,FDL,FDN,FDS,FDVV,FDX,FE,FELC,FELG,FENI,FER,FERG,FEZ,FFIV,FHN,FICO,FIG,FIGR,FIS,FISV,FITB,FIVE,FIX,FLEX,FLOT,FLR,FLS,FLUT,FMDE,FMS,FMX,FN,FND,FNDA,FNDE,FNDF,FNDX,FNF,FNV,FOX,FOXA,FPE,FR,FRHC,FRMI,FROG,FRT,FSEC,FSLR,FSS,FSV,FTAI,FTCS,FTEC,FTI,FTNT,FTS,FTSM,FTV,FUTU,FVD,FWONA,FWONK,FXI,G,GAP,GBIL,GBTC,GD,GDDY,GDS,GDX,GDXJ,GE,GEHC,GEN,GEV,GFI,GFL,GFS,GGAL,GGG,GH,GIB,GIL,GILD,GIS,GL,GLBE,GLD,GLDM,GLPI,GLW,GM,GMAB,GME,GMED,GNRC,GOOG,GOOGL,GOVT,GPC,GPN,GRAB,GRID,GRMN,GS,GSAT,GSIE,GSK,GSLC,GTLB,GTLS,GUNR,GWRE,GWW,H,HAL,HALO,HAS,HBAN,HBM,HCA,HD,HDB,HDV,HEFA,HEI,HEI-A,HESM,HIG,HII,HIMS,HL,HLI,HLN,HLNE,HLT,HMC,HMY,HON,HOOD,HPE,HPQ,HQY,HRL,HSBC,HSIC,HST,HSY,HTHT,HUBB,HUBS,HUM,HWM,HYG,IAG,IAGG,IAU,IAUM,IBB,IBIT,IBKR,IBM,IBN,IBP,ICE,ICL,ICLR,ICSH,IDA,IDCC,IDEV,IDV,IDXX,IEF,IEFA,IEI,IEMG,IESC,IEUR,IEX,IFF,IGF,IGIB,IGM,IGSB,IGV,IHG,IHI,IJH,IJJ,IJK,IJR,IJS,IJT,ILMN,IMO,INCY,INDA,INFY,ING,INGR,INSM,INTC,INTU,INVH,IONQ,IONS,IOO,IOT,IP,IQLT,IQV,IR,IREN,IRM,ISRG,ISTB,IT,ITA,ITOT,ITT,ITUB,ITW,IUSB,IUSG,IUSV,IVE,IVV,IVW,IVZ,IWB,IWD,IWF,IWM,IWN,IWO,IWP,IWR,IWS,IWV,IWY,IX,IXJ,IXN,IXUS,IYF,IYR,IYW,J,JAAA,JAVA,JAZZ,JBHT,JBL,JBND,JBS,JBTM,JCI,JCPB,JD,JEF,JEPI,JEPQ,JGLO,JGRO,JHG,JHMM,JHX,JIRE,JKHY,JLL,JMBS,JMST,JMTG,JMUB,JNJ,JNK,JOBY,JPIE,JPM,JPST,JQUA,JXN,KB,KBWB,KDP,KEP,KEY,KEYS,KGC,KHC,KIM,KKR,KLAC,KLAR,KMB,KMI,KNSL,KNX,KO,KR,KRE,KRMN,KRYS,KSPI,KT,KTOS,KVUE,KVYO,KWEB,KYMR,L,LAD,LAMR,LBRDA,LBRDK,LDOS,LECO,LEN,LEVI,LFUS,LH,LHX,LI,LII,LIN,LINE,LITE,LKQ,LLY,LLYVA,LLYVK,LMBS,LMT,LNC,LNG,LNT,LOGI,LOW,LPLA,LQD,LRCX,LSCC,LTM,LULU,LUMN,LUV,LVS,LW,LYB,LYFT,LYG,LYV,MA,MAA,MAGS,MANH,MAR,MAS,MBB,MBLY,MCD,MCHI,MCHP,MCK,MCO,MDB,MDGL,MDLZ,MDT,MDY,MEDP,MELI,MET,META,MFC,MFG,MGA,MGC,MGK,MGM,MGV,MHK,MICC,MIDD,MINT,MKC,MKL,MKSI,MKTX,MLI,MLM,MMM,MMYT,MNDY,MNST,MO,MOAT,MOD,MOG-A,MOH,MORN,MOS,MP,MPC,MPLX,MPWR,MRK,MRNA,MRVL,MS,MSCI,MSFT,MSI,MSTR,MT,MTB,MTCH,MTD,MTSI,MTUM,MTZ,MU,MUB,MUFG,MUSA,NBIS,NBIX,NCLH,NDAQ,NDSN,NEE,NEM,NET,NEU,NFG,NFLX,NGG,NI,NICE,NIO,NKE,NLY,NMR,NNN,NOBL,NOC,NOK,NOW,NRG,NSC,NTAP,NTES,NTNX,NTR,NTRA,NTRS,NTSK,NU,NUE,NUVL,NVDA,NVDL,NVMI,NVO,NVR,NVS,NVT,NWG,NWS,NWSA,NXPI,NXT,NYT,O,OBDC,OC,ODFL,OEF,OGE,OHI,OKE,OKLO,OKTA,OLLI,OMC,OMF,OMFL,ON,ONB,ONC,ONEQ,ONON,ONTO,OPEN,OR,ORA,ORCL,ORI,ORLY,OSK,OTEX,OTF,OTIS,OVV,OWL,OXY,PAA,PAAA,PAAS,PAC,PAG,PAGP,PANW,PATH,PAVE,PAYC,PAYX,PB,PBA,PBR,PBR-A,PBUS,PCAR,PCG,PCOR,PCTY,PDBC,PDD,PDI,PEG,PEGA,PEN,PEP,PFE,PFF,PFG,PFGC,PFSI,PG,PGR,PH,PHG,PHM,PHYS,PINS,PJT,PKG,PKX,PLD,PLNT,PLTR,PM,PNC,PNFP,PNR,PNW,PODD,POOL,PPA,PPC,PPG,PPL,PR,PRAX,PRF,PRI,PRIM,PRU,PSA,PSKY,PSLV,PSN,PSNY,PSO,PSX,PTC,PUK,PULS,PVAL,PWR,PYLD,PYPL,Q,QBTS,QCOM,QGEN,QLD,QQQ,QQQI,QQQM,QRVO,QS,QSR,QUAL,QXO,QYLD,R,RACE,RBA,RBC,RBLX,RBRK,RCI,RCL,RDDT,RDVY,RDY,RECS,REET,REG,REGN,RELX,REXR,RF,RGA,RGC,RGEN,RGLD,RGTI,RIO,RIVN,RJF,RKLB,RKT,RL,RMBS,RMD,RNA,RNR,ROIV,ROK,ROKU,ROL,ROP,ROST,RPM,RPRX,RRC,RRR,RRX,RS,RSG,RSP,RSPT,RTO,RTX,RVMD,RVTY,RWL,RY,RYAAY,RYAN,RYTM,SAIA,SAIL,SAN,SANM,SAP,SARO,SATS,SBAC,SBIL,SBS,SBSW,SBUX,SCCO,SCHA,SCHB,SCHC,SCHD,SCHE,SCHF,SCHG,SCHH,SCHI,SCHK,SCHM,SCHO,SCHP,SCHR,SCHV,SCHW,SCHX,SCHZ,SCI,SCZ,SDVY,SDY,SE,SEIC,SF,SFD,SFM,SGI,SGOL,SGOV,SHEL,SHG,SHLD,SHOP,SHV,SHW,SHY,SHYG,SIL,SIRI,SITM,SIVR,SJM,SJNK,SKM,SLB,SLF,SLV,SLYV,SMBS,SMCI,SMFG,SMH,SMMT,SMTC,SN,SNA,SNAP,SNDK,SNN,SNOW,SNPS,SNX,SNY,SO,SOFI,SOLS,SOLV,SONY,SOXL,SOXX,SPAB,SPDW,SPEM,SPG,SPGI,SPHQ,SPHY,SPIB,SPLV,SPMB,SPMD,SPMO,SPOT,SPSB,SPSM,SPTI,SPTL,SPTM,SPTS,SPXC,SPXL,SPY,SPYD,SPYG,SPYI,SPYM,SPYV,SQM,SRAD,SRE,SRLN,SSB,SSD,SSNC,SSO,STAG,STE,STEP,STIP,STLA,STLD,STM,STN,STRC,STRL,STT,STWD,STX,STZ,SU,SUB,SUI,SUN,SUZ,SW,SWK,SWKS,SYF,SYK,SYM,SYY,T,TAK,TAP,TBIL,TCAF,TCOM,TD,TDG,TDY,TEAM,TECH,TECK,TECL,TEL,TEM,TER,TEVA,TFC,TFII,TFLO,TFPM,TGT,THC,THG,THRO,TIGO,TIMB,TIP,TJX,TKO,TLH,TLK,TLN,TLT,TM,TME,TMF,TMO,TMUS,TOL,TOST,TOTL,TPG,TPL,TPR,TQQQ,TRGP,TRI,TRMB,TROW,TRP,TRU,TRV,TS,TSCO,TSEM,TSLA,TSLL,TSM,TSN,TT,TTAN,TTC,TTD,TTE,TTEK,TTMI,TTWO,TU,TW,TWLO,TX,TXN,TXRH,TXT,TYL,U,UAL,UBER,UBS,UDR,UEC,UGI,UHAL,UHAL-B,UHS,UI,UL,ULS,ULTA,UMBF,UMC,UNH,UNM,UNP,UPRO,UPS,URA,URBN,URI,URTH,USB,USFD,USFR,USHY,USIG,USMV,USO,UTHR,UWMC,V,VALE,VB,VBIL,VBK,VBR,VCIT,VCLT,VCR,VCRB,VCSH,VDC,VDE,VEA,VEEV,VEU,VFC,VFH,VFLO,VFS,VG,VGIT,VGK,VGLT,VGSH,VGT,VHT,VICI,VIG,VIGI,VIK,VIPS,VIS,VIV,VLO,VLTO,VLUE,VLY,VMBS,VMC,VMI,VNO,VNOM,VNQ,VO,VOD,VOE,VONE,VONG,VONV,VOO,VOOG,VOOV,VOT,VOX,VOYA,VPL,VPU,VRSK,VRSN,VRT,VRTX,VSGX,VSS,VST,VT,VTEB,VTI,VTIP,VTR,VTRS,VTV,VTWO,VUG,VUSB,VV,VWO,VWOB,VXF,VXUS,VYM,VYMI,VZ,W,WAB,WAL,WAT,WAY,WBD,WBS,WCC,WCN,WDAY,WDC,WDS,WEC,WELL,WES,WF,WFC,WING,WIT,WLK,WM,WMB,WMG,WMS,WMT,WPC,WPM,WRB,WSM,WSO,WST,WTFC,WTRG,WTS,WTW,WWD,WY,WYNN,XAR,XBI,XEL,XLB,XLC,XLE,XLF,XLG,XLI,XLK,XLP,XLRE,XLU,XLV,XLY,XMHQ,XMMO,XOM,XP,XPEV,XPO,XYL,XYZ,YMM,YPF,YUM,YUMC,Z,ZBH,ZBRA,ZG,ZION,ZM,ZS,ZTO,ZTS,ZWS
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1993-01-29,0.0,0.0,0.0,13.9677,0.0,0.092891,0.428864,0.0,0.0,0.0,2.72499,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.48386,0.0,1.67574,5.67017,5.41987,5.44036,0.0,0.0,1.35284,0.0,2.81755,7.02831,0.0,2.69888,4.79254,1.22879,0.0,0.0,2.93619,0.0,0.0,0.0,0.0,141.739,0.0,0.0,2.12624,0.0,2.65303,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.790327,0.0,9.3750,1.77024,0.0,5.20272,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.03113,0.0,8.45907,1.11303,5.88715,9.49480,0.0,0.104842,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.38597,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.01364,0.0,0.0,0.0,0.0,3.65924,0.0,0.0,0.0,0.0,0.0,17.5625,9.37895,10.1275,0.0,5.52810,0.0,0.0,1.30822,0.0,0.0,3.74441,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.553122,0.805017,0.669824,0.0,1.89315,4.45098,0.0,0.0,1.97849,0.0,0.0,0.0,0.940882,1.37029,0.0,1.51992,0.0,1.16667,0.0,0.0,0.0,5.91667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.03735,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.21984,0.111068,0.0,0.0,0.0,0.0,0.0,0.0,4.27965,0.0,0.0,2.52377,17.7525,0.0,12100.0,0.0,0.0,0.462668,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.62500,0.0,0.0,1.11472,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.7726,2.125,0.0,3.86489,2.95933,0.0,0.0,0.0,3.26763,3.19972,0.0,0.0,0.0,3.26006,1.16145,0.0,0.0,31.3108,4.97755,113.765,4.91667,1.44444,0.0,3.48926,0.0,0.0,0.0,0.0,3.55842,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.57801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.61893,0.0,0.0,0.0,0.0,0.0,5.89722,3.47767,2.42875,7.500,0.0,4.53726,0.0,1.29304,1.37461,0.0,0.0,4.71098,6.80908,11.4799,0.0,0.0,0.0,0.0,3.47977,0.0,0.0,0.175781,0.0,1.09292,1.91769,0.411457,3.57188,0.0,0.0,0.0,6.24563,0.0,0.756976,0.0,7.57118,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.24341,15.4088,0.0,0.0,5.70061,0.0,0.0,0.788099,0.0,3.67769,1.08847,1.73437,0.0,0.0,0.0,0.0,0.0,0.0,6.10808,5.29791,3.46938,0.0,0.0,0.0,0.0,4.34712,0.0,0.0,0.0,0.0,0.0,1.56222,10.7536,0.0,29.3613,3.9320,0.0,0.0,9.98765,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.02267,0.669945,0.0,0.0,0.579932,10.8684,0.0,0.0,0.0,0.0,0.0,0.0,1.50789,0.0,0.0,0.0,4.28568,0.0,0.0,0.0,0.0,133.133,0.0,0.0,0.0,6.15942,0.0,0.0,7.10355,0.0,0.0,4.70578,0.0,0.0,0.0,2.00000,0.0,0.0,6.15634,0.0,0.0,0.0,3.02842,6.67228,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.79563,0.0,0.0,2.05265,16.4746,6.65620,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.67317,0.0,0.436971,0.0,0.0,2.52060,0.0,0.0,0.0,0.0,0.0,0.0,2.59615,0.0,2.01712,0.0,8.09764,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.17752,4.18448,0.0,0.0,6.21119,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.60938,0.0,0.0,0.0,0.0,0.789884,0.0,0.0,0.0,2.55076,0.0,0.0,0.211138,0.0,0.0,0.0,1.92178,45.9297,0.0,0.0,0.0,0.0,0.0,9.06271,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.63071,2.20341,0.0,0.0,0.0,1.46914,4.11667,0.0,0.0,0.0,0.0,0.0,3.36902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.97640,0.0,0.0,9.45214,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.63735,0.0,0.0,4.92802,0.0,0.0,0.0,0.0,15.9714,0.0,0.472157,0.0,3.22076,0.0,0.0,0.0,0.332456,0.0,0.0,0.0,0.369968,4.84843,7.80272,0.0,0.0,0.0,0.0,5.73891,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.04787,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.91981,0.0,0.0,0.0,0.0,0.0,17.1467,0.0,3.93581,0.0,7.04398,3.46442,0.0,0.0,6.07571,0.0,0.0,0.0,0.357786,0.0,0.0,0.0,0.0,0.0,7.53046,0.0,0.0,0.0,0.0,3.31056,0.0,6.74793,0.0,0.0,1.63850,0.0,1.45983,0.0,0.0,1.17706,5.66629,0.0,0.680056,0.0,5.30174,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.74255,0.0,0.0,0.0,0.0,0.0,0.0,7.11431,6.37631,0.0,0.0,2.10938,0.0,0.0,0.0,0.0,0.0,0.0,3.19083,15.6327,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.50297,0.0,0.0,0.0,0.0,0.0,0.0,1.86444,0.0,0.0,0.0,7.125,0.0,0.0,10.11050,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.37445,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.21016,0.0,0.0,0.0,4.41634,0.0,0.0,0.0,0.0,5.49616,0.0,0.0,2.61495,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.975010,0.0,0.0,0.0,0.0,0.0,4.89504,0.0,0.0,0.0,5.16085,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.00222,0.0,2.09356,0.0,1.33645,0.0,0.163982,0.0,9.60387,0.0,0.0,0.0,4.63472,1.52443,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.22988,0.0,0.0,0.0,0.0,0.0,0.0,2.55451,0.0,8.49981,32.8059,3.74015,0.0,0.0,4.74974,0.0,0.0,0.0,5.81171,0.0,0.0,0.0,7.34560,6.81200,0.0,3.59263,0.0,1.15364,0.0,0.0,0.466617,4.64583,0.0,0.0,3.18462,3.25433,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.90513,0.0,0.0,6.08922,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.28668,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.06216,0.0,0.0,6.31018,0.0,9.66667,0.0,0.276141,0.0,3.06058,34.00,0.0,0.0,0.310920,0.0,7.85433,0.0,0.0,0.044271,0.883170,0.0,12.1446,1.67480,0.0,0.0,14.0349,0.0,0.0,0.0,0.0,6.31232,0.0,0.0,0.0,0.0,1.64390,20.3562,0.0,0.0,6.35600,0.332061,0.0,0.0,0.0,1.44444,2.12990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.40396,1.46280,18.6027,0.0,29.2481,4.59737,0.0,0.0,1.38385,0.0,0.0,1.82641,0.0,0.0,1.31519,0.0,6.91080,0.0,0.0,0.0,9.71066,0.0,0.0,0.0,0.0,0.0,5.46970,0.0,0.0,4.78460,0.0,0.0,0.0,0.0,0.272840,0.7500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.29134,0.0,0.0,0.0,0.831271,0.0,1.74167,1.80938,0.851506,0.0,0.0,0.0,2.52403,0.0,0.0,0.0,4.60210,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.637156,1.20803,0.0,0.958494,0.0,0.0,0.0,0.0,0.0,3.13945,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.932757,0.0,0.0,0.0,0.0,0.0,1.23446,12.7667,0.0,0.0,0.0,0.0,0.0,3.33474,0.0,0.0,8.72851,1.72014,0.0,0.0,0.0,0.0,5.47008,1.36794,5.47680,1.49227,3.07299,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.2667,0.0,2.73135,5.07008,0.0,0.0,0.0,3.16222,6.89507,2.53988,0.0,0.0,0.0,0.0,0.0,0.0,2.56797,0.0,0.0,0.0,0.0,0.0,0.0,18.2812,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.552933,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.6712,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.8771,0.0,0.0,4.39702,0.0,0.0,9.5,2.43818,0.0,1.91854,0.0,1.37570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.68129,0.0,0.898971,2.50699,0.509596,4.05544,0.0,2.43691,0.0,5.55434,0.0,0.0,0.0,0.0,0.0,1.81711,0.0,7.02484,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.546728,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.443776,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.688168,0.0,0.0,5.79233,0.0,0.0,0.0,0.0,0.885740,0.662404,0.0,0.0,0.0,0.0,0.0,4.57794,0.0,0.0,0.0,0.0,3.07443,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.81311,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.335938,0.0,9.06443,0.0,0.0,0.0,0.0,8.43750,0.0,0.0,2.46075,0.0,0.0,0.0,2.57137,0.0,0.0,0.0,0.0,0.0,0.0,3.80905,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.64064,0.0,24.1133,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.30071,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.500,6.17301,0.0,0.0,1.87463,0.018108,0.0,0.0,0.0,0.0,0.0,8.27532,0.847805,0.0,3.51120,0.0,2.94244,1.70106,0.0,4.01956,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.899292,0.0,0.0,0.0,0.0,3.33410,2.12868,3.19400,0.0,0.0,0.0,3.34081,27.0037,0.0,0.0,0.0,0.0,0.0,0.550969,0.0,0.0,0.0,0.0,0.0,12.5294,0.0,0.0,12.0141,0.0,3.43805,0.0,0.0,0.0,0.271023,0.0,0.0,0.0,0.0,1.58333,1.33334,1.75225,0.0,8.11253,0.0,0.0,0.0,0.0,0.0,0.0,9.84190,4.02810,0.0,0.720857,0.0,2.40587,0.524813,0.0,0.0,0.0,0.0,0.0,0.0,1.92310,0.0,7.17971,4.875,0.0,0.0,0.0,0.0,2.14082,0.0,1.23857,0.0,0.0,1.68322,0.0,3.54838,0.0,0.0,8.49153,0.0,3.07566,12.5245,4.91883,0.0,0.0,0.0,0.0,0.0,0.0,1.35112,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.64710,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.61264,0.0,0.0,1.54130,0.0,9.45915,6.5213,1.90709,0.0,0.0,0.0,1.08027,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.67965,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.92067,0.0,0.0,0.0,0.0,0.0,0.0,4.05146,0.0,0.0,0.0,2.71816,0.0,3.79901,2.72652,0.0,0.0,2.29825,0.0,0.0,0.0,7.45530,1.60773,0.0,0.0,3.29893,0.0,0.0,1.01619,0.463131,1.71328,3.50595,0.0,0.892969,15.2336,0.0,0.0,5.15705,0.0,0.0,0.0,5.00386,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.19581,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.38889,0.0,5.71381,0.0,0.0,0.0,0.0,0.0

--- TAIL (Last 3 Rows) ---

Ticker,091160.KS,2330.TW,A,AA,AAL,AAON,AAPL,ABBV,ABEV,ABNB,ABT,ABVX,ACGL,ACI,ACM,ACN,ACWI,ACWX,ADBE,ADC,ADI,ADM,ADP,ADSK,ADT,AEE,AEG,AEIS,AEM,AEP,AER,AES,AFG,AFL,AFRM,AG,AGCO,AGG,AGI,AGNC,AHR,AIG,AIQ,AIRR,AIT,AIZ,AJG,AKAM,AKRE,ALAB,ALB,ALC,ALGN,ALL,ALLE,ALLY,ALNY,ALSN,ALV,AM,AMAT,AMCR,AMD,AME,AMG,AMGN,AMH,AMKR,AMLP,AMP,AMRZ,AMT,AMTM,AMX,AMZN,AN,ANET,AON,AOS,APA,APD,APG,APH,APLD,APO,APP,APPF,APTV,AR,ARCC,ARE,ARES,ARGX,ARKK,ARM,ARMK,ARWR,AS,ASML,ASND,ASR,ASTS,ASX,ATI,ATO,ATR,AU,AUR,AVAV,AVB,AVDE,AVDV,AVEM,AVGO,AVLV,AVTR,AVUS,AVUV,AVY,AWI,AWK,AXIA,AXON,AXP,AXS,AXSM,AXTA,AYI,AZN,AZO,B,BA,BABA,BAC,BAH,BAI,BALL,BAM,BAP,BAX,BBAX,BBCA,BBD,BBEU,BBIN,BBIO,BBJP,BBUS,BBVA,BBY,BCE,BCH,BCS,BDX,BE,BEKE,BEN,BEP,BEPC,BETA,BF-A,BF-B,BG,BHP,BIDU,BIIB,BIL,BILI,BINC,BIO,BIP,BIRK,BIV,BJ,BK,BKLC,BKLN,BKNG,BKR,BLD,BLDR,BLK,BLSH,BLV,BMNR,BMO,BMRN,BMY,BN,BND,BNDX,BNO,BNS,BNT,BNTX,BOKF,BOND,BOXX,BP,BPOP,BR,BRK-A,BRK-B,BRKR,BRO,BROS,BRX,BSAC,BSBR,BSCQ,BSCR,BSOL,BSV,BSX,BSY,BTC,BTI,BUD,BUFR,BURL,BVN,BWA,BWXT,BX,BXP,BYD,BZ,C,CACI,CAE,CAG,CAH,CAI,CARR,CART,CASY,CAT,CB,CBOE,CBRE,CBSH,CCEP,CCI,CCJ,CCK,CCL,CDE,CDNS,CDP,CDW,CEF,CEG,CELH,CF,CFG,CFR,CG,CGBL,CGCP,CGDV,CGGO,CGGR,CGMU,CGUS,CGXU,CHD,CHDN,CHKP,CHRW,CHT,CHTR,CHWY,CHYM,CI,CIB,CIBR,CIEN,CIFR,CIGI,CINF,CL,CLF,CLH,CLS,CLX,CM,CMC,CMCSA,CME,CMG,CMI,CMS,CNA,CNC,CNH,CNI,CNM,CNP,CNQ,COF,COHR,COIN,COKE,COLB,COO,COP,COPX,COR,CORT,COST,COWZ,CP,CPAY,CPB,CPNG,CPRT,CPT,CQP,CR,CRBG,CRCL,CRDO,CRH,CRK,CRL,CRM,CRS,CRWD,CRWV,CSCO,CSGP,CSL,CSX,CTAS,CTRE,CTSH,CTVA,CUBE,CVE,CVNA,CVS,CVX,CW,CWB,CWEN,CX,CYTK,D,DAL,DASH,DB,DBEF,DBX,DCI,DD,DDOG,DDS,DE,DECK,DELL,DEO,DFAC,DFAE,DFAI,DFAS,DFAT,DFAU,DFAX,DFCF,DFEM,DFIC,DFIS,DFIV,DFLV,DFSD,DFSV,DFUS,DFUV,DG,DGRO,DGRW,DGX,DHI,DHR,DIA,DIHP,DINO,DIS,DIVO,DKNG,DKS,DLN,DLR,DLTR,DOC,DOCS,DOCU,DON,DOV,DOW,DOX,DPZ,DRI,DRS,DSGX,DSI,DT,DTE,DTM,DUHP,DUK,DUOL,DVA,DVN,DVY,DXCM,DXJ,DY,DYNF,E,EA,EAGG,EBAY,EC,ECL,ED,EDU,EDV,EEM,EFA,EFAV,EFG,EFV,EFX,EG,EGO,EGP,EHC,EIX,EL,ELAN,ELS,ELV,EMA,EMB,EMBJ,EME,EMLC,EMN,EMR,EMXC,ENB,ENSG,ENTG,EOG,EPAM,EPD,EQH,EQIX,EQNR,EQR,EQT,EQX,ERIC,ERIE,ES,ESAB,ESGD,ESGE,ESGU,ESGV,ESLT,ESS,ESTC,ET,ETHA,ETHB,ETN,ETR,EUFN,EVR,EVRG,EVTR,EW,EWBC,EWJ,EWT,EWY,EWZ,EXC,EXE,EXEL,EXLS,EXP,EXPD,EXPE,EXR,EZU,F,FAF,FANG,FAST,FBCG,FBND,FBTC,FCFS,FCNCA,FCX,FDL,FDN,FDS,FDVV,FDX,FE,FELC,FELG,FENI,FER,FERG,FEZ,FFIV,FHN,FICO,FIG,FIGR,FIS,FISV,FITB,FIVE,FIX,FLEX,FLOT,FLR,FLS,FLUT,FMDE,FMS,FMX,FN,FND,FNDA,FNDE,FNDF,FNDX,FNF,FNV,FOX,FOXA,FPE,FR,FRHC,FRMI,FROG,FRT,FSEC,FSLR,FSS,FSV,FTAI,FTCS,FTEC,FTI,FTNT,FTS,FTSM,FTV,FUTU,FVD,FWONA,FWONK,FXI,G,GAP,GBIL,GBTC,GD,GDDY,GDS,GDX,GDXJ,GE,GEHC,GEN,GEV,GFI,GFL,GFS,GGAL,GGG,GH,GIB,GIL,GILD,GIS,GL,GLBE,GLD,GLDM,GLPI,GLW,GM,GMAB,GME,GMED,GNRC,GOOG,GOOGL,GOVT,GPC,GPN,GRAB,GRID,GRMN,GS,GSAT,GSIE,GSK,GSLC,GTLB,GTLS,GUNR,GWRE,GWW,H,HAL,HALO,HAS,HBAN,HBM,HCA,HD,HDB,HDV,HEFA,HEI,HEI-A,HESM,HIG,HII,HIMS,HL,HLI,HLN,HLNE,HLT,HMC,HMY,HON,HOOD,HPE,HPQ,HQY,HRL,HSBC,HSIC,HST,HSY,HTHT,HUBB,HUBS,HUM,HWM,HYG,IAG,IAGG,IAU,IAUM,IBB,IBIT,IBKR,IBM,IBN,IBP,ICE,ICL,ICLR,ICSH,IDA,IDCC,IDEV,IDV,IDXX,IEF,IEFA,IEI,IEMG,IESC,IEUR,IEX,IFF,IGF,IGIB,IGM,IGSB,IGV,IHG,IHI,IJH,IJJ,IJK,IJR,IJS,IJT,ILMN,IMO,INCY,INDA,INFY,ING,INGR,INSM,INTC,INTU,INVH,IONQ,IONS,IOO,IOT,IP,IQLT,IQV,IR,IREN,IRM,ISRG,ISTB,IT,ITA,ITOT,ITT,ITUB,ITW,IUSB,IUSG,IUSV,IVE,IVV,IVW,IVZ,IWB,IWD,IWF,IWM,IWN,IWO,IWP,IWR,IWS,IWV,IWY,IX,IXJ,IXN,IXUS,IYF,IYR,IYW,J,JAAA,JAVA,JAZZ,JBHT,JBL,JBND,JBS,JBTM,JCI,JCPB,JD,JEF,JEPI,JEPQ,JGLO,JGRO,JHG,JHMM,JHX,JIRE,JKHY,JLL,JMBS,JMST,JMTG,JMUB,JNJ,JNK,JOBY,JPIE,JPM,JPST,JQUA,JXN,KB,KBWB,KDP,KEP,KEY,KEYS,KGC,KHC,KIM,KKR,KLAC,KLAR,KMB,KMI,KNSL,KNX,KO,KR,KRE,KRMN,KRYS,KSPI,KT,KTOS,KVUE,KVYO,KWEB,KYMR,L,LAD,LAMR,LBRDA,LBRDK,LDOS,LECO,LEN,LEVI,LFUS,LH,LHX,LI,LII,LIN,LINE,LITE,LKQ,LLY,LLYVA,LLYVK,LMBS,LMT,LNC,LNG,LNT,LOGI,LOW,LPLA,LQD,LRCX,LSCC,LTM,LULU,LUMN,LUV,LVS,LW,LYB,LYFT,LYG,LYV,MA,MAA,MAGS,MANH,MAR,MAS,MBB,MBLY,MCD,MCHI,MCHP,MCK,MCO,MDB,MDGL,MDLZ,MDT,MDY,MEDP,MELI,MET,META,MFC,MFG,MGA,MGC,MGK,MGM,MGV,MHK,MICC,MIDD,MINT,MKC,MKL,MKSI,MKTX,MLI,MLM,MMM,MMYT,MNDY,MNST,MO,MOAT,MOD,MOG-A,MOH,MORN,MOS,MP,MPC,MPLX,MPWR,MRK,MRNA,MRVL,MS,MSCI,MSFT,MSI,MSTR,MT,MTB,MTCH,MTD,MTSI,MTUM,MTZ,MU,MUB,MUFG,MUSA,NBIS,NBIX,NCLH,NDAQ,NDSN,NEE,NEM,NET,NEU,NFG,NFLX,NGG,NI,NICE,NIO,NKE,NLY,NMR,NNN,NOBL,NOC,NOK,NOW,NRG,NSC,NTAP,NTES,NTNX,NTR,NTRA,NTRS,NTSK,NU,NUE,NUVL,NVDA,NVDL,NVMI,NVO,NVR,NVS,NVT,NWG,NWS,NWSA,NXPI,NXT,NYT,O,OBDC,OC,ODFL,OEF,OGE,OHI,OKE,OKLO,OKTA,OLLI,OMC,OMF,OMFL,ON,ONB,ONC,ONEQ,ONON,ONTO,OPEN,OR,ORA,ORCL,ORI,ORLY,OSK,OTEX,OTF,OTIS,OVV,OWL,OXY,PAA,PAAA,PAAS,PAC,PAG,PAGP,PANW,PATH,PAVE,PAYC,PAYX,PB,PBA,PBR,PBR-A,PBUS,PCAR,PCG,PCOR,PCTY,PDBC,PDD,PDI,PEG,PEGA,PEN,PEP,PFE,PFF,PFG,PFGC,PFSI,PG,PGR,PH,PHG,PHM,PHYS,PINS,PJT,PKG,PKX,PLD,PLNT,PLTR,PM,PNC,PNFP,PNR,PNW,PODD,POOL,PPA,PPC,PPG,PPL,PR,PRAX,PRF,PRI,PRIM,PRU,PSA,PSKY,PSLV,PSN,PSNY,PSO,PSX,PTC,PUK,PULS,PVAL,PWR,PYLD,PYPL,Q,QBTS,QCOM,QGEN,QLD,QQQ,QQQI,QQQM,QRVO,QS,QSR,QUAL,QXO,QYLD,R,RACE,RBA,RBC,RBLX,RBRK,RCI,RCL,RDDT,RDVY,RDY,RECS,REET,REG,REGN,RELX,REXR,RF,RGA,RGC,RGEN,RGLD,RGTI,RIO,RIVN,RJF,RKLB,RKT,RL,RMBS,RMD,RNA,RNR,ROIV,ROK,ROKU,ROL,ROP,ROST,RPM,RPRX,RRC,RRR,RRX,RS,RSG,RSP,RSPT,RTO,RTX,RVMD,RVTY,RWL,RY,RYAAY,RYAN,RYTM,SAIA,SAIL,SAN,SANM,SAP,SARO,SATS,SBAC,SBIL,SBS,SBSW,SBUX,SCCO,SCHA,SCHB,SCHC,SCHD,SCHE,SCHF,SCHG,SCHH,SCHI,SCHK,SCHM,SCHO,SCHP,SCHR,SCHV,SCHW,SCHX,SCHZ,SCI,SCZ,SDVY,SDY,SE,SEIC,SF,SFD,SFM,SGI,SGOL,SGOV,SHEL,SHG,SHLD,SHOP,SHV,SHW,SHY,SHYG,SIL,SIRI,SITM,SIVR,SJM,SJNK,SKM,SLB,SLF,SLV,SLYV,SMBS,SMCI,SMFG,SMH,SMMT,SMTC,SN,SNA,SNAP,SNDK,SNN,SNOW,SNPS,SNX,SNY,SO,SOFI,SOLS,SOLV,SONY,SOXL,SOXX,SPAB,SPDW,SPEM,SPG,SPGI,SPHQ,SPHY,SPIB,SPLV,SPMB,SPMD,SPMO,SPOT,SPSB,SPSM,SPTI,SPTL,SPTM,SPTS,SPXC,SPXL,SPY,SPYD,SPYG,SPYI,SPYM,SPYV,SQM,SRAD,SRE,SRLN,SSB,SSD,SSNC,SSO,STAG,STE,STEP,STIP,STLA,STLD,STM,STN,STRC,STRL,STT,STWD,STX,STZ,SU,SUB,SUI,SUN,SUZ,SW,SWK,SWKS,SYF,SYK,SYM,SYY,T,TAK,TAP,TBIL,TCAF,TCOM,TD,TDG,TDY,TEAM,TECH,TECK,TECL,TEL,TEM,TER,TEVA,TFC,TFII,TFLO,TFPM,TGT,THC,THG,THRO,TIGO,TIMB,TIP,TJX,TKO,TLH,TLK,TLN,TLT,TM,TME,TMF,TMO,TMUS,TOL,TOST,TOTL,TPG,TPL,TPR,TQQQ,TRGP,TRI,TRMB,TROW,TRP,TRU,TRV,TS,TSCO,TSEM,TSLA,TSLL,TSM,TSN,TT,TTAN,TTC,TTD,TTE,TTEK,TTMI,TTWO,TU,TW,TWLO,TX,TXN,TXRH,TXT,TYL,U,UAL,UBER,UBS,UDR,UEC,UGI,UHAL,UHAL-B,UHS,UI,UL,ULS,ULTA,UMBF,UMC,UNH,UNM,UNP,UPRO,UPS,URA,URBN,URI,URTH,USB,USFD,USFR,USHY,USIG,USMV,USO,UTHR,UWMC,V,VALE,VB,VBIL,VBK,VBR,VCIT,VCLT,VCR,VCRB,VCSH,VDC,VDE,VEA,VEEV,VEU,VFC,VFH,VFLO,VFS,VG,VGIT,VGK,VGLT,VGSH,VGT,VHT,VICI,VIG,VIGI,VIK,VIPS,VIS,VIV,VLO,VLTO,VLUE,VLY,VMBS,VMC,VMI,VNO,VNOM,VNQ,VO,VOD,VOE,VONE,VONG,VONV,VOO,VOOG,VOOV,VOT,VOX,VOYA,VPL,VPU,VRSK,VRSN,VRT,VRTX,VSGX,VSS,VST,VT,VTEB,VTI,VTIP,VTR,VTRS,VTV,VTWO,VUG,VUSB,VV,VWO,VWOB,VXF,VXUS,VYM,VYMI,VZ,W,WAB,WAL,WAT,WAY,WBD,WBS,WCC,WCN,WDAY,WDC,WDS,WEC,WELL,WES,WF,WFC,WING,WIT,WLK,WM,WMB,WMG,WMS,WMT,WPC,WPM,WRB,WSM,WSO,WST,WTFC,WTRG,WTS,WTW,WWD,WY,WYNN,XAR,XBI,XEL,XLB,XLC,XLE,XLF,XLG,XLI,XLK,XLP,XLRE,XLU,XLV,XLY,XMHQ,XMMO,XOM,XP,XPEV,XPO,XYL,XYZ,YMM,YPF,YUM,YUMC,Z,ZBH,ZBRA,ZG,ZION,ZM,ZS,ZTO,ZTS,ZWS
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-07-15,146100.0,2440.0,134.71,48.58,15.63,113.11,327.50,244.11,3.03,148.38,89.27,136.94,98.54,14.56,68.88,137.02,157.52,75.43,224.56,77.64,390.96,82.3,247.47,208.98,6.77,111.38,9.08,301.88,142.23,132.50,147.79,14.81,137.88,121.01,81.71,16.84,114.89,98.14,29.02,11.32,54.19,76.78,61.12,123.23,327.65,273.92,247.77,120.01,55.35,350.62,124.74,68.50,181.26,239.48,135.82,46.34,279.14,114.29,122.78,22.42,579.43,43.40,529.14,233.52,379.59,358.32,33.51,67.64,53.20,527.28,50.75,168.63,20.76,26.11,254.96,203.54,171.92,355.15,60.31,34.27,293.69,41.20,157.04,29.03,121.83,452.73,175.40,58.96,33.58,18.92,48.70,124.79,862.93,79.60,277.01,57.05,71.820,35.61,1815.27,268.57,283.46,66.31,40.72,193.59,174.98,129.11,79.14,6.02,141.22,190.29,90.61,104.92,92.00,394.28,91.69,11.20,128.51,124.67,156.79,155.90,129.21,9.92,541.12,358.44,110.71,237.53,32.43,334.323,168.37,2970.57,35.91,218.12,117.69,61.59,63.94,45.43,60.80,49.02,398.20,22.15,62.47,102.61,3.62,77.895,78.66,82.66,75.48,136.04,25.54,85.37,21.60,40.87,28.35,154.88,239.38,17.03,33.63,32.52,34.94,18.53,25.47,25.07,115.72,85.48,111.48,197.24,91.52,18.28,52.20,295.73,38.73,42.86,76.13,90.24,0.00,144.70,20.47,182.80,57.25,0.0,76.05,1093.40,25.13,67.39,15.79,183.65,58.95,58.72,44.47,72.82,48.03,47.59,90.29,44.59,91.99,139.33,91.43,117.45,41.33,171.01,147.39,733180.0,488.35,58.66,66.86,63.86,31.36,33.72,5.35,19.555,19.645,10.50,77.71,43.04,31.54,28.72,58.73,79.91,36.81,345.24,30.71,64.01,176.91,127.05,68.94,87.64,14.90,134.89,471.83,24.52,14.09,224.94,17.46,68.74,47.61,808.49,914.30,337.44,277.11,141.41,58.16,104.49,79.47,90.98,111.55,26.59,15.91,371.50,36.74,130.86,40.04,258.115,30.21,117.82,71.12,158.57,46.11,37.57,22.19,49.30,40.23,46.69,27.36,44.69,34.13,97.14,84.66,132.39,197.50,41.55,131.24,21.21,22.09,297.81,81.55,93.09,418.46,19.87,100.68,172.43,91.47,9.85,303.37,334.77,96.95,120.76,67.41,23.49,245.18,34.63,666.13,74.02,49.98,66.61,10.57,124.00,44.66,42.72,42.73,208.89,299.38,167.21,177.01,32.57,70.60,111.46,77.26,296.57,89.57,916.54,64.0,90.47,363.16,21.89,17.42,27.28,111.87,62.18,218.84,31.87,65.69,226.74,103.96,13.07,228.22,167.00,577.10,206.77,77.12,111.77,28.49,344.10,49.43,192.37,40.10,43.18,84.45,40.46,27.36,70.59,105.91,181.60,751.64,103.59,34.45,13.07,82.62,70.97,85.96,190.16,36.56,54.78,30.35,89.27,134.86,264.46,536.56,589.48,106.53,412.68,82.21,44.60,38.63,41.80,81.18,70.03,52.15,36.80,42.01,39.08,37.79,35.72,56.15,39.92,47.71,39.21,82.51,54.89,121.28,76.64,96.74,201.77,151.55,200.79,525.801,34.135,83.93,97.15,46.48,25.25,208.89,97.98,176.07,127.03,21.74,22.26,51.16,56.86,212.26,29.70,51.56,310.87,196.06,43.82,71.33,142.38,45.17,146.95,145.29,41.54,124.34,131.22,231.61,42.93,159.62,72.73,176.71,428.77,68.08,48.96,207.27,47.03,112.76,15.98,270.25,110.31,49.91,61.79,65.57,104.65,90.17,122.22,79.03,171.61,364.13,29.44,213.11,109.88,76.68,82.31,25.54,63.78,390.33,54.15,95.73,64.90,769.72,25.54,67.85,136.25,95.26,56.15,167.38,138.69,136.457,85.93,37.52,49.46,1022.60,35.87,68.26,49.25,9.35,10.07,210.19,73.79,87.17,103.69,52.51,165.80,134.00,731.26,292.79,62.24,19.91,14.52,24.74,412.86,114.24,40.48,353.65,85.42,50.535,87.27,132.41,93.50,102.49,171.64,35.88,45.74,87.63,55.55,27.58,206.53,177.70,267.11,144.64,68.76,14.18,69.57,189.76,45.36,62.08,45.28,56.54,215.23,2070.62,60.97,50.03,277.26,251.19,62.29,313.42,48.64,42.70,44.09,40.40,64.15,230.52,68.41,421.47,24.94,1205.79,23.50,30.93,41.10,50.36,57.94,193.03,1736.70,128.72,50.97,50.77,68.89,110.00,40.53,24.06,128.77,486.65,56.40,37.56,40.67,53.27,31.48,50.13,202.55,50.39,55.99,17.95,65.89,157.68,6.25,91.28,122.24,43.71,223.82,117.78,146.80,213.80,96.18,278.17,72.27,164.51,57.50,59.820,60.52,99.37,48.84,91.51,100.00,34.28,30.07,20.28,100.01,50.34,365.63,91.27,33.39,74.00,96.55,360.35,63.20,26.45,1055.28,32.99,38.92,61.41,52.67,73.50,162.96,65.90,52.45,131.70,37.22,181.51,38.98,372.35,80.24,44.03,174.41,77.64,29.08,22.26,78.56,226.58,370.21,370.92,22.61,121.00,78.22,3.82,182.63,241.76,1152.07,80.53,46.43,51.45,143.58,32.830,209.9,50.96,140.54,1371.44,191.00,35.25,75.82,80.51,18.12,21.98,378.85,341.44,26.19,27.65,46.36,351.59,253.20,39.29,134.50,277.79,37.17,15.46,142.90,9.75,85.79,328.48,27.89,15.15,222.84,115.54,47.39,23.75,95.07,25.15,100.46,87.16,23.80,170.27,42.67,479.92,215.33,407.78,279.24,79.81,14.99,49.96,76.28,40.41,189.90,36.81,97.41,211.20,29.40,228.59,139.84,5.10,172.08,50.49,149.32,270.21,89.99,42.84,557.02,93.78,97.54,116.98,79.68,625.91,75.56,223.57,75.31,67.01,52.72,159.28,52.22,93.94,159.87,49.86,75.63,147.16,113.48,146.16,136.23,174.00,187.15,120.42,115.09,48.72,11.04,33.31,99.17,109.81,102.99,279.70,29.82,37.51,54.73,140.70,36.43,36.74,49.79,206.81,79.14,38.28,123.52,388.97,48.10,133.76,236.42,165.44,194.16,8.45,271.41,45.77,189.38,111.60,230.25,758.39,138.56,30.30,412.74,247.28,123.58,295.77,221.29,382.53,140.33,109.51,165.33,429.48,289.53,40.59,97.93,137.78,94.92,134.50,103.83,248.45,129.66,50.55,80.51,239.32,276.28,319.18,53.08,12.10,134.54,142.76,46.555,29.28,57.13,56.62,60.12,72.19,96.09,0.0,73.77,26.30,82.96,148.47,327.91,44.83,50.92,50.29,50.28,247.02,96.07,7.76,45.93,346.91,50.48,72.00,124.27,121.61,98.44,30.28,11.46,23.53,322.71,23.66,25.45,25.09,100.95,224.50,19.58,106.53,32.20,319.61,73.57,82.45,56.56,75.78,48.78,350.24,89.41,17.34,49.68,18.70,17.63,27.00,114.12,112.52,331.37,160.29,30.82,30.83,108.21,253.21,85.29,23.88,415.43,271.99,286.82,12.73,548.67,514.15,43.99,752.00,24.92,1156.63,97.66,101.420,49.800,514.46,40.96,255.83,74.55,99.91,209.66,329.12,107.58,335.43,132.46,54.87,117.42,6.45,49.25,44.79,45.55,58.00,16.23,6.06,178.44,535.21,131.77,69.02,156.58,369.05,78.04,93.83,9.43,264.95,54.15,86.26,796.35,504.46,333.04,550.25,58.72,80.47,689.49,529.23,1843.19,92.2,681.31,43.07,10.66,66.29,277.01,89.46,46.84,161.89,111.51,18.68,133.94,100.59,50.92,1922.77,353.80,115.63,57.51,569.32,160.53,55.23,80.71,97.57,70.52,106.15,231.96,396.19,233.36,169.25,23.04,49.46,299.18,56.41,1352.66,123.61,68.28,206.26,228.55,621.77,395.63,407.18,97.47,67.63,248.53,40.11,1316.55,293.02,312.67,357.71,904.28,106.76,22.77,593.66,199.51,172.05,19.73,91.36,287.77,89.10,95.21,273.04,753.80,79.99,73.68,82.91,45.71,101.53,5.03,42.77,23.16,10.04,47.42,55.98,525.22,11.25,104.73,137.90,328.54,162.10,129.76,54.59,68.33,277.37,191.13,13.25,13.88,236.87,123.96,212.50,33.37,472.48,50.56,6497.57,150.80,159.46,17.92,31.66,27.98,279.01,109.13,75.22,63.26,11.10,143.56,225.23,373.90,48.75,47.95,91.03,45.69,150.86,65.46,80.93,60.58,69.16,92.54,26.38,311.26,103.40,37.46,304.73,4.75,28.80,109.70,132.49,40.31,82.73,145.54,22.75,10.38,72.20,56.05,9.69,53.77,23.35,51.36,43.57,227.80,200.40,25.10,354.02,11.95,56.64,144.73,110.00,72.49,50.33,17.86,16.01,75.69,123.15,17.51,43.58,123.05,17.17,85.74,16.36,79.88,31.28,316.73,135.40,24.82,30.62,112.96,110.41,84.98,148.05,205.22,952.95,27.02,125.39,30.57,23.68,168.56,227.86,51.89,143.42,52.24,133.76,180.88,254.15,99.81,64.33,107.07,159.28,202.37,171.88,28.42,115.31,35.71,19.59,318.42,54.55,305.26,90.67,115.04,314.68,9.25,18.53,56.62,15.04,16.52,196.16,123.61,29.08,49.62,51.86,648.84,26.35,55.52,140.23,18.27,177.98,41.24,91.61,717.74,55.87,295.56,83.44,6.430,74.18,219.80,15.32,18.30,264.48,375.74,111.32,590.14,57.07,80.38,33.86,292.17,198.03,80.16,12.77,44.56,27.94,79.99,664.45,33.51,35.09,31.48,234.23,5.125,148.06,193.02,15.25,93.62,17.800,170.30,76.20,14.60,374.08,102.89,198.57,12.30,307.73,34.89,461.92,143.32,43.76,348.51,225.81,103.04,56.31,36.05,65.51,213.31,391.91,217.34,212.97,60.80,29.78,195.89,184.44,111.28,130.28,217.87,66.63,40.66,109.69,417.05,15.13,13.82,207.33,155.91,27.54,0.00,187.09,100.22,5.92,8.54,105.11,181.54,34.52,29.16,48.65,32.34,36.34,27.48,34.90,24.01,22.45,36.39,35.38,24.10,26.21,24.55,33.93,102.79,29.74,22.96,77.98,83.76,43.04,152.51,111.36,98.17,78.75,24.76,73.30,73.27,38.63,100.54,84.64,71.42,60.26,123.55,110.21,332.29,82.00,42.28,75.01,30.65,612.38,54.88,109.02,24.94,32.26,47.55,81.25,52.21,108.66,25.220,26.89,26.50,590.77,15.07,135.22,150.05,403.70,4.76,1615.00,30.80,271.87,425.28,249.587,43.68,94.60,17.87,61.03,78.37,20.71,165.55,555.27,25.32,50.16,51.61,222.01,444.48,86.10,23.36,33.28,75.47,22.14,66.28,150.00,485.38,29.94,56.84,28.23,25.66,91.58,28.97,217.59,278.71,754.81,48.62,119.97,53.740,88.84,61.69,71.52,15.10,92.78,40.33,101.15,189.61,68.59,68.66,39.92,211.46,44.78,101.36,5.90,235.56,67.75,68.68,87.78,668.82,186.59,16.66,828.30,131.64,60.64,106.22,118.39,70.98,8.19,43.59,87.96,57.51,74.04,316.44,42.64,80.73,21.43,16.45,39.61,49.93,41.81,42.87,124.8,1232.18,624.15,91.77,71.48,57.95,197.13,201.34,57.25,342.12,31.56,52.80,146.23,50.57,27.40,138.29,192.34,206.90,43.11,94.70,22.36,108.07,150.97,185.70,98.47,14.14,400.12,84.24,176.92,8.86,33.05,535.29,187.62,153.19,30.39,39.155,44.49,413.44,140.26,74.44,278.16,95.51,51.92,118.58,69.08,77.60,329.19,56.92,30.17,251.00,394.46,12.220,419.48,57.47,480.20,78.35,93.99,19.37,80.34,31.33,143.62,243.80,10.48,100.68,211.54,44.94,301.19,189.86,88.75,303.52,31.27,120.97,72.67,55.07,39.319,10.11,36.22,69.34,60.85,148.02,542.54,61.45,87.75,466.14,145.31,24.92,418.52,89.00,288.36,145.87,112.94,40.90,72.95,1047.28,204.75,63.01,97.05,50.44,36.915,50.75,96.09,121.38,531.79,2.03,355.14,14.67,297.01,75.58,350.45,242.52,81.93,73.48,396.01,76.560,78.73,226.34,159.42,70.82,193.67,83.13,17.24,138.45,47.50,3.09,12.91,58.67,89.12,53.97,58.12,116.50,299.01,26.31,237.36,95.57,98.19,14.23,347.35,13.93,292.66,91.00,191.25,14.84,46.50,289.11,544.38,39.85,43.32,97.86,80.45,15.08,201.12,341.40,127.19,108.52,693.80,83.33,222.42,298.79,194.72,98.49,111.59,195.62,191.94,270.52,304.57,477.08,81.14,154.25,160.23,157.29,50.21,372.42,49.63,92.29,16.68,217.49,119.58,87.76,49.70,347.65,59.48,66.60,240.29,84.99,160.10,101.39,42.83,91.67,259.71,81.79,374.92,22.69,27.27,76.58,336.70,170.12,141.82,513.84,20.88,112.97,233.29,45.37,63.33,87.51,145.70,1.84,77.05,232.80,74.38,28.31,151.26,112.53,72.10,108.53,69.88,222.098,383.94,359.00,162.62,37.93,349.21,285.12,401.99,23.91,97.05,266.32,156.22,79.25,50.50,113.38,56.50,56.56,62.20,180.06,181.58,83.47,44.56,45.22,158.29,117.00,112.67,160.68,144.51,16.87,13.78,204.82,121.43,81.81,9.20,50.26,152.57,43.17,33.845,90.14,255.17,33.74,71.55,92.60,148.19,24.55,74.53,47.63

=== features_df (Multi-Index Features) ===
--- HEAD (First 3 Rows) ---

                             ATR      ATRP       TRP  RSI  Mom_21  Consistency  IR_63  Beta_63  DD_21  AutoCorr_15    Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5  Slope_P_5_Z  Slope_V_5_Z  Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount
Ticker    Date
091160.KS 2007-01-29    0.000000  0.000000  0.000000  0.0     0.0          0.0    0.0      1.0    0.0          0.0  0.000000           0.0        0.0        0.0          0.0          0.0        0.0              0.0               0.0                  0.0
          2007-01-30  142.780000  0.017081  0.017081 -1.0     0.0          0.0    0.0      1.0    0.0          0.0 -0.006568           0.0        0.0        0.0          0.0          0.0        0.0              0.0               0.0                  0.0
          2007-01-31  143.766429  0.017439  0.018994 -1.0     0.0          0.0    0.0      1.0    0.0          0.0 -0.013774           0.0        0.0        0.0          0.0          0.0        0.0              0.0               0.0                  0.0

--- TAIL (Last 3 Rows) ---

                        ATR      ATRP       TRP       RSI    Mom_21  Consistency     IR_63   Beta_63     DD_21  AutoCorr_15    Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5  Slope_P_5_Z  Slope_V_5_Z  Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount
Ticker Date
ZWS    2026-07-15  1.236545  0.025961  0.017636 -0.082696 -0.015706          0.6 -0.083843  1.101098 -0.071359    -0.121936  0.002526      0.204263   0.003982   0.255324     0.453519     0.541443   0.005059              0.0      4.021030e+07                  0.0
       2026-07-16  1.261078  0.026066  0.032658  0.003042 -0.009216          0.8 -0.030634  1.139130 -0.056736     0.103883  0.015746      0.337478   0.005785   0.433177     0.628594     0.827152   0.002432              0.0      4.021030e+07                  0.0
       2026-07-17  1.247429  0.026135  0.022418 -0.065991 -0.037119          0.6 -0.016506  1.149861 -0.069409    -0.208103 -0.013435      0.222025   0.005195   0.354094     0.546427     0.668873   0.001214              0.0      4.045033e+07                  0.0

=== macro_df (Macro Data) ===
--- HEAD (First 3 Rows) ---

             Mkt_Ret  Mkt_Ret_Z  Macro_Trend  Macro_Trend_Z  High_Yield_Spread_Z  Yield_Curve_10Y2Y_Z  Macro_Trend_Vel_Z  Macro_Trend_Mom  Macro_Vix_Z  Macro_Vix_Ratio  Mkt_Vol_63d_Z
Date
1997-01-02  0.000000        0.0          0.0            0.0                  0.0                  0.0                0.0              0.0          0.0              1.0            0.0
1997-01-03  0.014353        0.0          0.0            0.0                  0.0                  0.0                0.0              0.0          0.0              1.0            0.0
1997-01-06 -0.008739        0.0          0.0            0.0                  0.0                  0.0                0.0              0.0          0.0              1.0            0.0

--- TAIL (Last 3 Rows) ---

             Mkt_Ret  Mkt_Ret_Z  Macro_Trend  Macro_Trend_Z  High_Yield_Spread_Z  Yield_Curve_10Y2Y_Z  Macro_Trend_Vel_Z  Macro_Trend_Mom  Macro_Vix_Z  Macro_Vix_Ratio  Mkt_Vol_63d_Z
Date
2026-07-15  0.003964   0.314838     0.089911       0.210533            -1.272054            -1.469186           0.351333         0.351333    -1.298617         0.828662       0.353342
2026-07-16 -0.005419  -0.810075     0.083267       0.003627            -1.261809            -1.456801          -1.243963        -1.243963    -0.543182         0.857949       0.361127
2026-07-17 -0.009897  -1.316496     0.071888      -0.347941            -1.251313            -1.443830          -1.528960        -1.528960     0.864151         0.913827       0.463496

 # Section 4: Engine Initialization & Stage 1 Analysis

In [72]:
# Instantiate Master Engine
engine = AlphaEngine(
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    macro_df=macro_df,
    df_close_wide=df_close_wide,
    df_atrp_wide=df_atrp_wide,
    df_trp_wide=df_trp_wide,
)
print("Master AlphaEngine Ready.")

Master AlphaEngine Ready.

In [73]:
df_ohlcv.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8308398 entries, ('091160.KS', Timestamp('2007-01-29 00:00:00')) to ('ZWS', Timestamp('2026-07-17 00:00:00'))
Data columns (total 5 columns):
 #   Column     Dtype
---  ------     -----
 0   Adj Open   float64
 1   Adj High   float64
 2   Adj Low    float64
 3   Adj Close  float64
 4   Volume     int64
dtypes: float64(4), int64(1)
memory usage: 349.0+ MB

In [74]:
import pandas as pd

target_date = pd.Timestamp("2025-09-01")

# Use level=1 for the date level (since level names aren't 'timestamp')
dates_in_index = df_ohlcv.index.get_level_values(1).normalize().unique()
print(f"2025-09-01 in index: {target_date in dates_in_index}")

# Check if date exists (one-liner)
any_match = (df_ohlcv.index.get_level_values(1).normalize() == target_date).any()
print(f"Any match: {any_match}")

# If you want to see which tickers have data on that date:
if any_match:
    mask = df_ohlcv.index.get_level_values(1).normalize() == target_date
    tickers_on_date = df_ohlcv.index.get_level_values(0)[mask].unique()
    print(f"Tickers on 2025-09-01: {tickers_on_date}")
    print(f"Count: {len(tickers_on_date)}")

# Extract all data for that specific date
if any_match:
    # Using boolean mask (works regardless of index sorting)
    mask = df_ohlcv.index.get_level_values(1).normalize() == target_date
    df_target = df_ohlcv[mask]
    print(df_target.head())

2025-09-01 in index: False
Any match: False

In [75]:
df_ohlcv.index

MultiIndex([('091160.KS', '2007-01-29'),
            ('091160.KS', '2007-01-30'),
            ('091160.KS', '2007-01-31'),
            ('091160.KS', '2007-02-01'),
            ('091160.KS', '2007-02-02'),
            ('091160.KS', '2007-02-05'),
            ('091160.KS', '2007-02-06'),
            ('091160.KS', '2007-02-07'),
            ('091160.KS', '2007-02-08'),
            ('091160.KS', '2007-02-09'),
            ...
            (      'ZWS', '2026-07-06'),
            (      'ZWS', '2026-07-07'),
            (      'ZWS', '2026-07-08'),
            (      'ZWS', '2026-07-09'),
            (      'ZWS', '2026-07-10'),
            (      'ZWS', '2026-07-13'),
            (      'ZWS', '2026-07-14'),
            (      'ZWS', '2026-07-15'),
            (      'ZWS', '2026-07-16'),
            (      'ZWS', '2026-07-17')],
           names=['Ticker', 'Date'], length=8308398)

In [76]:
# Configuration for Interactive UI (Stage 1 Setup)
_inputs = EngineInput(
    mode="Ranking",
    decision_date=pd.Timestamp("2026-04-16"),
    lookback_period=189,
    holding_period=5,
    metric="Sharpe (TRP)",
    benchmark_ticker=config.benchmark_ticker,
    rank_start=1,
    rank_end=200,
    debug=False,
)

analyzer1, stage1_pack = create_walk_forward_analyzer(
    engine, _inputs, universe_subset=None
)
analyzer1.show()

VBox(children=(HTML(value='<b>1. Timeline Configuration:</b> (Past <--- Decision ---> Future)'), HBox(children…

In [77]:
# Execute Headless Agent Simulation
print("--- 🤖 RL AGENT HEADLESS VIEW ---")
metrics_df = run_headless_simulation(engine, _inputs)
display(metrics_df.style.format("{:.4f}"))
print(f"\nTarget Reward Signal: {metrics_df.loc['Group Gain', 'Holding']:.6f}")

--- 🤖 RL AGENT HEADLESS VIEW ---
----------------------------------------------------------------------
Timeline: [2025-07-16] -> Decision: 2026-04-16 -> Entry: 2026-04-17 -> End: 2026-04-24
Selected Tickers (200):
SGOV, SHV, BIL, MINT, USFR, BOXX, PULS, JPST, GTLS, SNDK
JAAA, RVMD, CIEN, TER, EA, LITE, ASX, VGSH, WDC, GLW
ROIV, SHY, ROST, EWY, WBD, VALE, MU, FTI, ERIC, RIO
VTEB, BE, KEYS, NOK, STX, FIX, UTHR, VCSH, IGSB, MUB
CHRW, EMXC, LRCX, GOOGL, GOOG, HSBC, INTC, TEVA, JNJ, TD
CAT, EWZ, ALB, MKSI, CMI, BNS, BSV, COPX, RY, SU
PBR, EFV, ASML, GSK, EWT, FDX, ONTO, BP, AA, IAG
CVE, SLV, HL, KGC, ITUB, COHR, BHP, AU, JAZZ, IAUM
AMAT, GLDM, SGOL, IAU, APA, B, AZN, XBI, SCCO, EMB
PSLV, EQX, SOXX, SCHF, GLD, VEA, BG, SPDW, NEM, IEMG
VEU, IONS, GDX, EEM, VXUS, PHYS, LSCC, HAL, IXUS, ETR
EWJ, MTZ, OPEN, SMH, FNDX, USO, SOXL, KLAC, GDXJ, MOD
NBIS, FTAI, SIL, MEDP, VLO, MPWR, SPIB, VRT, SHEL, AEM
MBB, TTMI, JBHT, BKR, CNQ, IDEV, DD, GFI, ATI, WELL
FE, JNK, EQIX, NVS, FNV, MTSI, VTR, NVT, EIX, SPHY
AG, FN, PAAS, GM, AEP, IBB, RGLD, AGI, USHY, TJX
HII, IEFA, VYM, XLE, IUSB, CLS, CASY, EFA, XOM, PEN
ADI, RPRX, IWD, SCHD, MRK, VTV, PR, HYG, AGG, APLD
STLD, MRVL, IGIB, VWO, XPO, SPG, VCIT, BND, DGRO, ARGX
C, CFG, TSM, FLS, VT, CDE, SLB, IWN, WMT, FIVE
----------------------------------------------------------------------

Target Reward Signal: 0.003314

 # Section 5: Stage 2 - Cascade Filter Execution

In [78]:
print("--- CASCADE FILTER, TICKERS PASSED FIRST FILTER ---")
# Get decision date from last run
decision_date_last_run = FilterPack(decision_date=analyzer1.last_run.decision_date)

# LAUNCH STAGE 2 (Cascade on the Stage 1 subset)
analyzer2, stage2_pack = create_walk_forward_analyzer(
    engine,
    universe_subset=analyzer1.last_run.tickers,
    filter_pack=decision_date_last_run,
)

print("🚀 Ready for Stage 2: Run Simulation for 2nd filter.")
analyzer2.show()

--- CASCADE FILTER, TICKERS PASSED FIRST FILTER ---
🚀 Ready for Stage 2: Run Simulation for 2nd filter.

VBox(children=(HTML(value='<b>1. Timeline Configuration:</b> (Past <--- Decision ---> Future)'), HBox(children…

In [79]:
# Parse and map results from Analyzer 2
result = SU.map_analyzer(analyzer2)

====================================================================
[SEARCH] ANALYZER SIMULATION MAP
====================================================================
[  0] [DATA] audit_pack (EngineOutput)
[  1]   [PLOT] portfolio_series (shape=(196,))
[  2]   [PLOT] benchmark_series (shape=(196,))
[  3]   [CALC] normalized_plot_data (shape=(196, 100))
[  4]   [FILE] tickers (len=100)
[  5]     [DOC] index_0 (str)
[  6]     [DOC] index_1 (str)
[  7]     [DOC] index_2 (str)
[  8]     [DOC] index_3 (str)
[  9]     [DOC] index_4 (str)
[ 10]     [DOC] index_5 (str)
[ 11]     [DOC] index_6 (str)
[ 12]     [DOC] index_7 (str)
[ 13]     [DOC] index_8 (str)
[ 14]     [DOC] index_9 (str)
[ 15]     [DOC] index_10 (str)
[ 16]     [DOC] index_11 (str)
[ 17]     [DOC] index_12 (str)
[ 18]     [DOC] index_13 (str)
[ 19]     [DOC] index_14 (str)
[ 20]     [DOC] index_15 (str)
[ 21]     [DOC] index_16 (str)
[ 22]     [DOC] index_17 (str)
[ 23]     [DOC] index_18 (str)
[ 24]     [DOC] index_19 (str)
[ 25]     [DOC] index_20 (str)
[ 26]     [DOC] index_21 (str)
[ 27]     [DOC] index_22 (str)
[ 28]     [DOC] index_23 (str)
[ 29]     [DOC] index_24 (str)
[ 30]     [DOC] index_25 (str)
[ 31]     [DOC] index_26 (str)
[ 32]     [DOC] index_27 (str)
[ 33]     [DOC] index_28 (str)
[ 34]     [DOC] index_29 (str)
[ 35]     [DOC] index_30 (str)
[ 36]     [DOC] index_31 (str)
[ 37]     [DOC] index_32 (str)
[ 38]     [DOC] index_33 (str)
[ 39]     [DOC] index_34 (str)
[ 40]     [DOC] index_35 (str)
[ 41]     [DOC] index_36 (str)
[ 42]     [DOC] index_37 (str)
[ 43]     [DOC] index_38 (str)
[ 44]     [DOC] index_39 (str)
[ 45]     [DOC] index_40 (str)
[ 46]     [DOC] index_41 (str)
[ 47]     [DOC] index_42 (str)
[ 48]     [DOC] index_43 (str)
[ 49]     [DOC] index_44 (str)
[ 50]     [DOC] index_45 (str)
[ 51]     [DOC] index_46 (str)
[ 52]     [DOC] index_47 (str)
[ 53]     [DOC] index_48 (str)
[ 54]     [DOC] index_49 (str)
[ 55]     [DOC] index_50 (str)
[ 56]     [DOC] index_51 (str)
[ 57]     [DOC] index_52 (str)
[ 58]     [DOC] index_53 (str)
[ 59]     [DOC] index_54 (str)
[ 60]     [DOC] index_55 (str)
[ 61]     [DOC] index_56 (str)
[ 62]     [DOC] index_57 (str)
[ 63]     [DOC] index_58 (str)
[ 64]     [DOC] index_59 (str)
[ 65]     [DOC] index_60 (str)
[ 66]     [DOC] index_61 (str)
[ 67]     [DOC] index_62 (str)
[ 68]     [DOC] index_63 (str)
[ 69]     [DOC] index_64 (str)
[ 70]     [DOC] index_65 (str)
[ 71]     [DOC] index_66 (str)
[ 72]     [DOC] index_67 (str)
[ 73]     [DOC] index_68 (str)
[ 74]     [DOC] index_69 (str)
[ 75]     [DOC] index_70 (str)
[ 76]     [DOC] index_71 (str)
[ 77]     [DOC] index_72 (str)
[ 78]     [DOC] index_73 (str)
[ 79]     [DOC] index_74 (str)
[ 80]     [DOC] index_75 (str)
[ 81]     [DOC] index_76 (str)
[ 82]     [DOC] index_77 (str)
[ 83]     [DOC] index_78 (str)
[ 84]     [DOC] index_79 (str)
[ 85]     [DOC] index_80 (str)
[ 86]     [DOC] index_81 (str)
[ 87]     [DOC] index_82 (str)
[ 88]     [DOC] index_83 (str)
[ 89]     [DOC] index_84 (str)
[ 90]     [DOC] index_85 (str)
[ 91]     [DOC] index_86 (str)
[ 92]     [DOC] index_87 (str)
[ 93]     [DOC] index_88 (str)
[ 94]     [DOC] index_89 (str)
[ 95]     [DOC] index_90 (str)
[ 96]     [DOC] index_91 (str)
[ 97]     [DOC] index_92 (str)
[ 98]     [DOC] index_93 (str)
[ 99]     [DOC] index_94 (str)
[100]     [DOC] index_95 (str)
[101]     [DOC] index_96 (str)
[102]     [DOC] index_97 (str)
[103]     [DOC] index_98 (str)
[104]     [DOC] index_99 (str)
[105]   [PLOT] initial_weights (shape=(100,))
[106]   [FILE] perf_metrics (len=24)
[107]     [NUM] full_p_gain (float)
[108]     [NUM] full_p_sharpe (shape=())
[109]     [NUM] full_p_sharpe_atrp (float)
[110]     [NUM] full_p_sharpe_trp (float)
[111]     [NUM] lookback_p_gain (float)
[112]     [NUM] lookback_p_sharpe (shape=())
[113]     [NUM] lookback_p_sharpe_atrp (float)
[114]     [NUM] lookback_p_sharpe_trp (float)
[115]     [NUM] holding_p_gain (float)
[116]     [NUM] holding_p_sharpe (shape=())
[117]     [NUM] holding_p_sharpe_atrp (float)
[118]     [NUM] holding_p_sharpe_trp (float)
[119]     [NUM] full_b_gain (float)
[120]     [NUM] full_b_sharpe (shape=())
[121]     [NUM] full_b_sharpe_atrp (float)
[122]     [NUM] full_b_sharpe_trp (float)
[123]     [NUM] lookback_b_gain (float)
[124]     [NUM] lookback_b_sharpe (shape=())
[125]     [NUM] lookback_b_sharpe_atrp (float)
[126]     [NUM] lookback_b_sharpe_trp (float)
[127]     [NUM] holding_b_gain (float)
[128]     [NUM] holding_b_sharpe (shape=())
[129]     [NUM] holding_b_sharpe_atrp (float)
[130]     [NUM] holding_b_sharpe_trp (float)
[131]   [CALC] results_df (shape=(100, 2))
[132]   [DATE] start_date (Timestamp)
[133]   [DATE] decision_date (Timestamp)
[134]   [DATE] buy_date (Timestamp)
[135]   [DATE] holding_end_date (Timestamp)
[136]   [PLOT] portfolio_atrp_series (shape=(196,))
[137]   [PLOT] benchmark_atrp_series (shape=(196,))
[138]   [PLOT] portfolio_trp_series (shape=(196,))
[139]   [PLOT] benchmark_trp_series (shape=(196,))
[140]   [DOC] error_msg (NoneType)
[141]   [FILE] debug_data (len=8)
[142]     [FILE] audit_liquidity (len=3)
[143]       [DOC] mode (str)
[144]       [NUM] tickers_passed (int)
[145]       [NUM] forced_list (bool)
[146]     [CALC] full_universe_ranking (shape=(200, 16))
[147]     [FILE] meta (len=4)
[148]       [NUM] dropped_count (int)
[149]       [FILE] dropped_tickers (len=0)
[150]       [NUM] clean_count (int)
[151]       [DOC] selection_range (str)
[152]     [DATA] inputs_snapshot (EngineInput)
[153]       [DOC] mode (str)
[154]       [DATE] decision_date (Timestamp)
[155]       [NUM] lookback_period (int)
[156]       [NUM] holding_period (int)
[157]       [DOC] metric (str)
[158]       [DOC] benchmark_ticker (str)
[159]       [NUM] rank_start (int)
[160]       [NUM] rank_end (int)
[161]       [DATA] quality_thresholds (QualityThresholds)
[162]         [NUM] min_median_dollar_volume (int)
[163]         [NUM] min_liquidity_percentile (float)
[164]         [NUM] max_stale_pct (float)
[165]         [NUM] max_same_vol_count (int)
[166]       [FILE] manual_tickers (len=0)
[167]       [NUM] debug (bool)
[168]       [FILE] universe_subset (len=200)
[169]         [DOC] index_0 (str)
[170]         [DOC] index_1 (str)
[171]         [DOC] index_2 (str)
[172]         [DOC] index_3 (str)
[173]         [DOC] index_4 (str)
[174]         [DOC] index_5 (str)
[175]         [DOC] index_6 (str)
[176]         [DOC] index_7 (str)
[177]         [DOC] index_8 (str)
[178]         [DOC] index_9 (str)
[179]         [DOC] index_10 (str)
[180]         [DOC] index_11 (str)
[181]         [DOC] index_12 (str)
[182]         [DOC] index_13 (str)
[183]         [DOC] index_14 (str)
[184]         [DOC] index_15 (str)
[185]         [DOC] index_16 (str)
[186]         [DOC] index_17 (str)
[187]         [DOC] index_18 (str)
[188]         [DOC] index_19 (str)
[189]         [DOC] index_20 (str)
[190]         [DOC] index_21 (str)
[191]         [DOC] index_22 (str)
[192]         [DOC] index_23 (str)
[193]         [DOC] index_24 (str)
[194]         [DOC] index_25 (str)
[195]         [DOC] index_26 (str)
[196]         [DOC] index_27 (str)
[197]         [DOC] index_28 (str)
[198]         [DOC] index_29 (str)
[199]         [DOC] index_30 (str)
[200]         [DOC] index_31 (str)
[201]         [DOC] index_32 (str)
[202]         [DOC] index_33 (str)
[203]         [DOC] index_34 (str)
[204]         [DOC] index_35 (str)
[205]         [DOC] index_36 (str)
[206]         [DOC] index_37 (str)
[207]         [DOC] index_38 (str)
[208]         [DOC] index_39 (str)
[209]         [DOC] index_40 (str)
[210]         [DOC] index_41 (str)
[211]         [DOC] index_42 (str)
[212]         [DOC] index_43 (str)
[213]         [DOC] index_44 (str)
[214]         [DOC] index_45 (str)
[215]         [DOC] index_46 (str)
[216]         [DOC] index_47 (str)
[217]         [DOC] index_48 (str)
[218]         [DOC] index_49 (str)
[219]         [DOC] index_50 (str)
[220]         [DOC] index_51 (str)
[221]         [DOC] index_52 (str)
[222]         [DOC] index_53 (str)
[223]         [DOC] index_54 (str)
[224]         [DOC] index_55 (str)
[225]         [DOC] index_56 (str)
[226]         [DOC] index_57 (str)
[227]         [DOC] index_58 (str)
[228]         [DOC] index_59 (str)
[229]         [DOC] index_60 (str)
[230]         [DOC] index_61 (str)
[231]         [DOC] index_62 (str)
[232]         [DOC] index_63 (str)
[233]         [DOC] index_64 (str)
[234]         [DOC] index_65 (str)
[235]         [DOC] index_66 (str)
[236]         [DOC] index_67 (str)
[237]         [DOC] index_68 (str)
[238]         [DOC] index_69 (str)
[239]         [DOC] index_70 (str)
[240]         [DOC] index_71 (str)
[241]         [DOC] index_72 (str)
[242]         [DOC] index_73 (str)
[243]         [DOC] index_74 (str)
[244]         [DOC] index_75 (str)
[245]         [DOC] index_76 (str)
[246]         [DOC] index_77 (str)
[247]         [DOC] index_78 (str)
[248]         [DOC] index_79 (str)
[249]         [DOC] index_80 (str)
[250]         [DOC] index_81 (str)
[251]         [DOC] index_82 (str)
[252]         [DOC] index_83 (str)
[253]         [DOC] index_84 (str)
[254]         [DOC] index_85 (str)
[255]         [DOC] index_86 (str)
[256]         [DOC] index_87 (str)
[257]         [DOC] index_88 (str)
[258]         [DOC] index_89 (str)
[259]         [DOC] index_90 (str)
[260]         [DOC] index_91 (str)
[261]         [DOC] index_92 (str)
[262]         [DOC] index_93 (str)
[263]         [DOC] index_94 (str)
[264]         [DOC] index_95 (str)
[265]         [DOC] index_96 (str)
[266]         [DOC] index_97 (str)
[267]         [DOC] index_98 (str)
[268]         [DOC] index_99 (str)
[269]         [DOC] index_100 (str)
[270]         [DOC] index_101 (str)
[271]         [DOC] index_102 (str)
[272]         [DOC] index_103 (str)
[273]         [DOC] index_104 (str)
[274]         [DOC] index_105 (str)
[275]         [DOC] index_106 (str)
[276]         [DOC] index_107 (str)
[277]         [DOC] index_108 (str)
[278]         [DOC] index_109 (str)
[279]         [DOC] index_110 (str)
[280]         [DOC] index_111 (str)
[281]         [DOC] index_112 (str)
[282]         [DOC] index_113 (str)
[283]         [DOC] index_114 (str)
[284]         [DOC] index_115 (str)
[285]         [DOC] index_116 (str)
[286]         [DOC] index_117 (str)
[287]         [DOC] index_118 (str)
[288]         [DOC] index_119 (str)
[289]         [DOC] index_120 (str)
[290]         [DOC] index_121 (str)
[291]         [DOC] index_122 (str)
[292]         [DOC] index_123 (str)
[293]         [DOC] index_124 (str)
[294]         [DOC] index_125 (str)
[295]         [DOC] index_126 (str)
[296]         [DOC] index_127 (str)
[297]         [DOC] index_128 (str)
[298]         [DOC] index_129 (str)
[299]         [DOC] index_130 (str)
[300]         [DOC] index_131 (str)
[301]         [DOC] index_132 (str)
[302]         [DOC] index_133 (str)
[303]         [DOC] index_134 (str)
[304]         [DOC] index_135 (str)
[305]         [DOC] index_136 (str)
[306]         [DOC] index_137 (str)
[307]         [DOC] index_138 (str)
[308]         [DOC] index_139 (str)
[309]         [DOC] index_140 (str)
[310]         [DOC] index_141 (str)
[311]         [DOC] index_142 (str)
[312]         [DOC] index_143 (str)
[313]         [DOC] index_144 (str)
[314]         [DOC] index_145 (str)
[315]         [DOC] index_146 (str)
[316]         [DOC] index_147 (str)
[317]         [DOC] index_148 (str)
[318]         [DOC] index_149 (str)
[319]         [DOC] index_150 (str)
[320]         [DOC] index_151 (str)
[321]         [DOC] index_152 (str)
[322]         [DOC] index_153 (str)
[323]         [DOC] index_154 (str)
[324]         [DOC] index_155 (str)
[325]         [DOC] index_156 (str)
[326]         [DOC] index_157 (str)
[327]         [DOC] index_158 (str)
[328]         [DOC] index_159 (str)
[329]         [DOC] index_160 (str)
[330]         [DOC] index_161 (str)
[331]         [DOC] index_162 (str)
[332]         [DOC] index_163 (str)
[333]         [DOC] index_164 (str)
[334]         [DOC] index_165 (str)
[335]         [DOC] index_166 (str)
[336]         [DOC] index_167 (str)
[337]         [DOC] index_168 (str)
[338]         [DOC] index_169 (str)
[339]         [DOC] index_170 (str)
[340]         [DOC] index_171 (str)
[341]         [DOC] index_172 (str)
[342]         [DOC] index_173 (str)
[343]         [DOC] index_174 (str)
[344]         [DOC] index_175 (str)
[345]         [DOC] index_176 (str)
[346]         [DOC] index_177 (str)
[347]         [DOC] index_178 (str)
[348]         [DOC] index_179 (str)
[349]         [DOC] index_180 (str)
[350]         [DOC] index_181 (str)
[351]         [DOC] index_182 (str)
[352]         [DOC] index_183 (str)
[353]         [DOC] index_184 (str)
[354]         [DOC] index_185 (str)
[355]         [DOC] index_186 (str)
[356]         [DOC] index_187 (str)
[357]         [DOC] index_188 (str)
[358]         [DOC] index_189 (str)
[359]         [DOC] index_190 (str)
[360]         [DOC] index_191 (str)
[361]         [DOC] index_192 (str)
[362]         [DOC] index_193 (str)
[363]         [DOC] index_194 (str)
[364]         [DOC] index_195 (str)
[365]         [DOC] index_196 (str)
[366]         [DOC] index_197 (str)
[367]         [DOC] index_198 (str)
[368]         [DOC] index_199 (str)
[369]     [FILE] verification (len=2)
[370]       [FILE] p (len=4)
                  +-- val --> [See ID 1]
[371]         [PLOT] ret (shape=(196,))
                  +-- atrp --> [See ID 136]
                  +-- trp --> [See ID 138]
[372]       [FILE] b (len=4)
                  +-- val --> [See ID 2]
[373]         [PLOT] ret (shape=(196,))
                  +-- atrp --> [See ID 137]
                  +-- trp --> [See ID 139]
[374]     [FILE] portfolio_raw_components (len=4)
[375]       [CALC] prices (shape=(196, 100))
[376]       [CALC] atrp (shape=(196, 100))
[377]       [CALC] trp (shape=(196, 100))
[378]       [CALC] ohlcv_raw (shape=(19600, 5))
[379]     [FILE] benchmark_raw_components (len=4)
[380]       [CALC] prices (shape=(196, 1))
[381]       [CALC] atrp (shape=(196, 1))
[382]       [CALC] trp (shape=(196, 1))
[383]       [CALC] ohlcv_raw (shape=(196, 5))
              +-- selection_audit --> [See ID 146]
[384]   [CALC] macro_df (shape=(7431, 11))
[385]   [DOC] alpha_perception (NoneType)

In [80]:
# Test different methods to extract resulting target tickers
_tickers = SU.fetch(4, result)
print(f"_tickers (by index): {_tickers}\n")

_tickers = SU.fetch("tickers", result)
print(f"_tickers (by key): {_tickers}\n")

print(f'result[4]["obj"]: {result[4]["obj"]}')

 ============================================================
 [INFO] INDEX: [4]
 [LABEL] NAME:  tickers
 [FILE] PATH:  audit_pack -> tickers
 ============================================================

['SGOV',
 'SHV',
 'BIL',
 'MINT',
 'USFR',
 'BOXX',
 'PULS',
 'JPST',
 'GTLS',
 'SNDK',
 'JAAA',
 'RVMD',
 'CIEN',
 'TER',
 'EA',
 'LITE',
 'ASX',
 'VGSH',
 'WDC',
 'GLW',
 'ROIV',
 'SHY',
 'ROST',
 'EWY',
 'WBD',
 'VALE',
 'MU',
 'FTI',
 'ERIC',
 'RIO',
 'VTEB',
 'BE',
 'KEYS',
 'NOK',
 'STX',
 'FIX',
 'UTHR',
 'VCSH',
 'IGSB',
 'MUB',
 'CHRW',
 'EMXC',
 'LRCX',
 'GOOGL',
 'GOOG',
 'HSBC',
 'INTC',
 'TEVA',
 'JNJ',
 'TD',
 'CAT',
 'EWZ',
 'ALB',
 'MKSI',
 'CMI',
 'BNS',
 'BSV',
 'COPX',
 'RY',
 'SU',
 'PBR',
 'EFV',
 'ASML',
 'GSK',
 'EWT',
 'FDX',
 'ONTO',
 'BP',
 'AA',
 'IAG',
 'CVE',
 'SLV',
 'HL',
 'KGC',
 'ITUB',
 'COHR',
 'BHP',
 'AU',
 'JAZZ',
 'IAUM',
 'AMAT',
 'GLDM',
 'SGOL',
 'IAU',
 'APA',
 'B',
 'AZN',
 'XBI',
 'SCCO',
 'EMB',
 'PSLV',
 'EQX',
 'SOXX',
 'SCHF',
 'GLD',
 'VEA',
 'BG',
 'SPDW',
 'NEM',
 'IEMG']

_tickers (by index): ['SGOV', 'SHV', 'BIL', 'MINT', 'USFR', 'BOXX', 'PULS', 'JPST', 'GTLS', 'SNDK', 'JAAA', 'RVMD', 'CIEN', 'TER', 'EA', 'LITE', 'ASX', 'VGSH', 'WDC', 'GLW', 'ROIV', 'SHY', 'ROST', 'EWY', 'WBD', 'VALE', 'MU', 'FTI', 'ERIC', 'RIO', 'VTEB', 'BE', 'KEYS', 'NOK', 'STX', 'FIX', 'UTHR', 'VCSH', 'IGSB', 'MUB', 'CHRW', 'EMXC', 'LRCX', 'GOOGL', 'GOOG', 'HSBC', 'INTC', 'TEVA', 'JNJ', 'TD', 'CAT', 'EWZ', 'ALB', 'MKSI', 'CMI', 'BNS', 'BSV', 'COPX', 'RY', 'SU', 'PBR', 'EFV', 'ASML', 'GSK', 'EWT', 'FDX', 'ONTO', 'BP', 'AA', 'IAG', 'CVE', 'SLV', 'HL', 'KGC', 'ITUB', 'COHR', 'BHP', 'AU', 'JAZZ', 'IAUM', 'AMAT', 'GLDM', 'SGOL', 'IAU', 'APA', 'B', 'AZN', 'XBI', 'SCCO', 'EMB', 'PSLV', 'EQX', 'SOXX', 'SCHF', 'GLD', 'VEA', 'BG', 'SPDW', 'NEM', 'IEMG']

 ============================================================
 [INFO] INDEX: [4]
 [LABEL] NAME:  tickers
 [FILE] PATH:  audit_pack -> tickers
 ============================================================

['SGOV',
 'SHV',
 'BIL',
 'MINT',
 'USFR',
 'BOXX',
 'PULS',
 'JPST',
 'GTLS',
 'SNDK',
 'JAAA',
 'RVMD',
 'CIEN',
 'TER',
 'EA',
 'LITE',
 'ASX',
 'VGSH',
 'WDC',
 'GLW',
 'ROIV',
 'SHY',
 'ROST',
 'EWY',
 'WBD',
 'VALE',
 'MU',
 'FTI',
 'ERIC',
 'RIO',
 'VTEB',
 'BE',
 'KEYS',
 'NOK',
 'STX',
 'FIX',
 'UTHR',
 'VCSH',
 'IGSB',
 'MUB',
 'CHRW',
 'EMXC',
 'LRCX',
 'GOOGL',
 'GOOG',
 'HSBC',
 'INTC',
 'TEVA',
 'JNJ',
 'TD',
 'CAT',
 'EWZ',
 'ALB',
 'MKSI',
 'CMI',
 'BNS',
 'BSV',
 'COPX',
 'RY',
 'SU',
 'PBR',
 'EFV',
 'ASML',
 'GSK',
 'EWT',
 'FDX',
 'ONTO',
 'BP',
 'AA',
 'IAG',
 'CVE',
 'SLV',
 'HL',
 'KGC',
 'ITUB',
 'COHR',
 'BHP',
 'AU',
 'JAZZ',
 'IAUM',
 'AMAT',
 'GLDM',
 'SGOL',
 'IAU',
 'APA',
 'B',
 'AZN',
 'XBI',
 'SCCO',
 'EMB',
 'PSLV',
 'EQX',
 'SOXX',
 'SCHF',
 'GLD',
 'VEA',
 'BG',
 'SPDW',
 'NEM',
 'IEMG']

_tickers (by key): ['SGOV', 'SHV', 'BIL', 'MINT', 'USFR', 'BOXX', 'PULS', 'JPST', 'GTLS', 'SNDK', 'JAAA', 'RVMD', 'CIEN', 'TER', 'EA', 'LITE', 'ASX', 'VGSH', 'WDC', 'GLW', 'ROIV', 'SHY', 'ROST', 'EWY', 'WBD', 'VALE', 'MU', 'FTI', 'ERIC', 'RIO', 'VTEB', 'BE', 'KEYS', 'NOK', 'STX', 'FIX', 'UTHR', 'VCSH', 'IGSB', 'MUB', 'CHRW', 'EMXC', 'LRCX', 'GOOGL', 'GOOG', 'HSBC', 'INTC', 'TEVA', 'JNJ', 'TD', 'CAT', 'EWZ', 'ALB', 'MKSI', 'CMI', 'BNS', 'BSV', 'COPX', 'RY', 'SU', 'PBR', 'EFV', 'ASML', 'GSK', 'EWT', 'FDX', 'ONTO', 'BP', 'AA', 'IAG', 'CVE', 'SLV', 'HL', 'KGC', 'ITUB', 'COHR', 'BHP', 'AU', 'JAZZ', 'IAUM', 'AMAT', 'GLDM', 'SGOL', 'IAU', 'APA', 'B', 'AZN', 'XBI', 'SCCO', 'EMB', 'PSLV', 'EQX', 'SOXX', 'SCHF', 'GLD', 'VEA', 'BG', 'SPDW', 'NEM', 'IEMG']

result[4]["obj"]: ['SGOV', 'SHV', 'BIL', 'MINT', 'USFR', 'BOXX', 'PULS', 'JPST', 'GTLS', 'SNDK', 'JAAA', 'RVMD', 'CIEN', 'TER', 'EA', 'LITE', 'ASX', 'VGSH', 'WDC', 'GLW', 'ROIV', 'SHY', 'ROST', 'EWY', 'WBD', 'VALE', 'MU', 'FTI', 'ERIC', 'RIO', 'VTEB', 'BE', 'KEYS', 'NOK', 'STX', 'FIX', 'UTHR', 'VCSH', 'IGSB', 'MUB', 'CHRW', 'EMXC', 'LRCX', 'GOOGL', 'GOOG', 'HSBC', 'INTC', 'TEVA', 'JNJ', 'TD', 'CAT', 'EWZ', 'ALB', 'MKSI', 'CMI', 'BNS', 'BSV', 'COPX', 'RY', 'SU', 'PBR', 'EFV', 'ASML', 'GSK', 'EWT', 'FDX', 'ONTO', 'BP', 'AA', 'IAG', 'CVE', 'SLV', 'HL', 'KGC', 'ITUB', 'COHR', 'BHP', 'AU', 'JAZZ', 'IAUM', 'AMAT', 'GLDM', 'SGOL', 'IAU', 'APA', 'B', 'AZN', 'XBI', 'SCCO', 'EMB', 'PSLV', 'EQX', 'SOXX', 'SCHF', 'GLD', 'VEA', 'BG', 'SPDW', 'NEM', 'IEMG']

 # Section 6: Verification, Exports & Auditing

In [81]:
# Export analytical trace logs to Excel
SU.export_audit_to_excel(
    audit_pack=analyzer2.last_run, filename="Audit_Verification_Report.xlsx"
)

[FILE] [EXCEL AUDIT] Building full transparency report: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\output\Audit_Verification_Report.xlsx
[DONE] Audit Report Complete: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\output\Audit_Verification_Report.xlsx

WindowsPath('C:/Users/ping/Files_win10/python/py311/stocks/notebooks_RLVR_v2/output/Audit_Verification_Report.xlsx')

In [82]:
# Export last-run stacked OHLCV ticker records
SU.export_last_run_tickers_data_to_csv(
    analyzer=analyzer2,
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    filename="last_run_tickers_stacked.csv",
)

Creating combined dictionary for 101 ticker(s)
Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00
============================================================
Data retrieved for 101 ticker(s) from 2025-07-16 00:00:00 to 2026-04-24 00:00:00
Total rows: 19796
Date range in data: 2025-07-16 00:00:00 to 2026-04-24 00:00:00
  SGOV: 196 rows
  SHV: 196 rows
  BIL: 196 rows
  MINT: 196 rows
  USFR: 196 rows
  BOXX: 196 rows
  PULS: 196 rows
  JPST: 196 rows
  GTLS: 196 rows
  SNDK: 196 rows
  JAAA: 196 rows
  RVMD: 196 rows
  CIEN: 196 rows
  TER: 196 rows
  EA: 196 rows
  LITE: 196 rows
  ASX: 196 rows
  VGSH: 196 rows
  WDC: 196 rows
  GLW: 196 rows
  ROIV: 196 rows
  SHY: 196 rows
  ROST: 196 rows
  EWY: 196 rows
  WBD: 196 rows
  VALE: 196 rows
  MU: 196 rows
  FTI: 196 rows
  ERIC: 196 rows
  RIO: 196 rows
  VTEB: 196 rows
  BE: 196 rows
  KEYS: 196 rows
  NOK: 196 rows
  STX: 196 rows
  FIX: 196 rows
  UTHR: 196 rows
  VCSH: 196 rows
  IGSB: 196 rows
  MUB: 196 rows
  CHRW: 196 rows
  EMXC: 196 rows
  LRCX: 196 rows
  GOOGL: 196 rows
  GOOG: 196 rows
  HSBC: 196 rows
  INTC: 196 rows
  TEVA: 196 rows
  JNJ: 196 rows
  TD: 196 rows
  CAT: 196 rows
  EWZ: 196 rows
  ALB: 196 rows
  MKSI: 196 rows
  CMI: 196 rows
  BNS: 196 rows
  BSV: 196 rows
  COPX: 196 rows
  RY: 196 rows
  SU: 196 rows
  PBR: 196 rows
  EFV: 196 rows
  ASML: 196 rows
  GSK: 196 rows
  EWT: 196 rows
  FDX: 196 rows
  ONTO: 196 rows
  BP: 196 rows
  AA: 196 rows
  IAG: 196 rows
  CVE: 196 rows
  SLV: 196 rows
  HL: 196 rows
  KGC: 196 rows
  ITUB: 196 rows
  COHR: 196 rows
  BHP: 196 rows
  AU: 196 rows
  JAZZ: 196 rows
  IAUM: 196 rows
  AMAT: 196 rows
  GLDM: 196 rows
  SGOL: 196 rows
  IAU: 196 rows
  APA: 196 rows
  B: 196 rows
  AZN: 196 rows
  XBI: 196 rows
  SCCO: 196 rows
  EMB: 196 rows
  PSLV: 196 rows
  EQX: 196 rows
  SOXX: 196 rows
  SCHF: 196 rows
  GLD: 196 rows
  VEA: 196 rows
  BG: 196 rows
  SPDW: 196 rows
  NEM: 196 rows
  IEMG: 196 rows
  SPY: 196 rows
Features data retrieved for 101 ticker(s) from 2025-07-16 00:00:00 to 2026-04-24 00:00:00
Total rows: 19796
Date range in data: 2025-07-16 00:00:00 to 2026-04-24 00:00:00
Available features: ATR, ATRP, TRP, RSI, Mom_21, Consistency, IR_63, Beta_63, DD_21, AutoCorr_15, Ret_1d, Range_Pos_20, Slope_P_5, Slope_V_5, Slope_P_5_Z, Slope_V_5_Z, Convexity, RollingStalePct, RollMedDollarVol, RollingSameVolCount
  SGOV: 196 rows
  SHV: 196 rows
  BIL: 196 rows
  MINT: 196 rows
  USFR: 196 rows
  BOXX: 196 rows
  PULS: 196 rows
  JPST: 196 rows
  GTLS: 196 rows
  SNDK: 196 rows
  JAAA: 196 rows
  RVMD: 196 rows
  CIEN: 196 rows
  TER: 196 rows
  EA: 196 rows
  LITE: 196 rows
  ASX: 196 rows
  VGSH: 196 rows
  WDC: 196 rows
  GLW: 196 rows
  ROIV: 196 rows
  SHY: 196 rows
  ROST: 196 rows
  EWY: 196 rows
  WBD: 196 rows
  VALE: 196 rows
  MU: 196 rows
  FTI: 196 rows
  ERIC: 196 rows
  RIO: 196 rows
  VTEB: 196 rows
  BE: 196 rows
  KEYS: 196 rows
  NOK: 196 rows
  STX: 196 rows
  FIX: 196 rows
  UTHR: 196 rows
  VCSH: 196 rows
  IGSB: 196 rows
  MUB: 196 rows
  CHRW: 196 rows
  EMXC: 196 rows
  LRCX: 196 rows
  GOOGL: 196 rows
  GOOG: 196 rows
  HSBC: 196 rows
  INTC: 196 rows
  TEVA: 196 rows
  JNJ: 196 rows
  TD: 196 rows
  CAT: 196 rows
  EWZ: 196 rows
  ALB: 196 rows
  MKSI: 196 rows
  CMI: 196 rows
  BNS: 196 rows
  BSV: 196 rows
  COPX: 196 rows
  RY: 196 rows
  SU: 196 rows
  PBR: 196 rows
  EFV: 196 rows
  ASML: 196 rows
  GSK: 196 rows
  EWT: 196 rows
  FDX: 196 rows
  ONTO: 196 rows
  BP: 196 rows
  AA: 196 rows
  IAG: 196 rows
  CVE: 196 rows
  SLV: 196 rows
  HL: 196 rows
  KGC: 196 rows
  ITUB: 196 rows
  COHR: 196 rows
  BHP: 196 rows
  AU: 196 rows
  JAZZ: 196 rows
  IAUM: 196 rows
  AMAT: 196 rows
  GLDM: 196 rows
  SGOL: 196 rows
  IAU: 196 rows
  APA: 196 rows
  B: 196 rows
  AZN: 196 rows
  XBI: 196 rows
  SCCO: 196 rows
  EMB: 196 rows
  PSLV: 196 rows
  EQX: 196 rows
  SOXX: 196 rows
  SCHF: 196 rows
  GLD: 196 rows
  VEA: 196 rows
  BG: 196 rows
  SPDW: 196 rows
  NEM: 196 rows
  IEMG: 196 rows
  SPY: 196 rows

Processing SGOV...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing SHV...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing BIL...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing MINT...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing USFR...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing BOXX...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing PULS...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing JPST...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing GTLS...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing SNDK...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing JAAA...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing RVMD...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing CIEN...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing TER...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing EA...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing LITE...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ASX...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing VGSH...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing WDC...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing GLW...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ROIV...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing SHY...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ROST...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing EWY...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing WBD...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing VALE...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing MU...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing FTI...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ERIC...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing RIO...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing VTEB...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing BE...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing KEYS...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing NOK...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing STX...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing FIX...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing UTHR...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing VCSH...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing IGSB...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing MUB...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing CHRW...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing EMXC...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing LRCX...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing GOOGL...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing GOOG...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing HSBC...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing INTC...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing TEVA...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing JNJ...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing TD...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing CAT...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing EWZ...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ALB...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing MKSI...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing CMI...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing BNS...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing BSV...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing COPX...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing RY...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing SU...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing PBR...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing EFV...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ASML...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing GSK...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing EWT...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing FDX...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ONTO...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing BP...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing AA...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing IAG...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing CVE...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing SLV...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing HL...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing KGC...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ITUB...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing COHR...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing BHP...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing AU...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing JAZZ...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing IAUM...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing AMAT...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing GLDM...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing SGOL...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing IAU...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 20)
  Combined shape: (196, 25)

WindowsPath('C:/Users/ping/Files_win10/python/py311/stocks/notebooks_RLVR_v2/output/last_run_tickers_stacked.csv')

 # Section 7: Slicing Tests & Dictionary Parsing

In [83]:
# Verify captured ticker names
_tickers

['SGOV',
 'SHV',
 'BIL',
 'MINT',
 'USFR',
 'BOXX',
 'PULS',
 'JPST',
 'GTLS',
 'SNDK',
 'JAAA',
 'RVMD',
 'CIEN',
 'TER',
 'EA',
 'LITE',
 'ASX',
 'VGSH',
 'WDC',
 'GLW',
 'ROIV',
 'SHY',
 'ROST',
 'EWY',
 'WBD',
 'VALE',
 'MU',
 'FTI',
 'ERIC',
 'RIO',
 'VTEB',
 'BE',
 'KEYS',
 'NOK',
 'STX',
 'FIX',
 'UTHR',
 'VCSH',
 'IGSB',
 'MUB',
 'CHRW',
 'EMXC',
 'LRCX',
 'GOOGL',
 'GOOG',
 'HSBC',
 'INTC',
 'TEVA',
 'JNJ',
 'TD',
 'CAT',
 'EWZ',
 'ALB',
 'MKSI',
 'CMI',
 'BNS',
 'BSV',
 'COPX',
 'RY',
 'SU',
 'PBR',
 'EFV',
 'ASML',
 'GSK',
 'EWT',
 'FDX',
 'ONTO',
 'BP',
 'AA',
 'IAG',
 'CVE',
 'SLV',
 'HL',
 'KGC',
 'ITUB',
 'COHR',
 'BHP',
 'AU',
 'JAZZ',
 'IAUM',
 'AMAT',
 'GLDM',
 'SGOL',
 'IAU',
 'APA',
 'B',
 'AZN',
 'XBI',
 'SCCO',
 'EMB',
 'PSLV',
 'EQX',
 'SOXX',
 'SCHF',
 'GLD',
 'VEA',
 'BG',
 'SPDW',
 'NEM',
 'IEMG']

In [84]:
# Test various pandas multi-index slicing configurations
test_tickers = ["NVDA", "GOOG"]
idx = pd.IndexSlice
columns = ["Adj Close", "Volume"]

# Slice 1: All dates, all columns
display(df_ohlcv.loc[idx[test_tickers]].copy().head(3))

# Slice 2: specific start date, all columns
display(df_ohlcv.loc[idx[test_tickers, pd.Timestamp("2026-04-01") :], :].head(3))

# Slice 3: specific start date, selected columns
display(df_ohlcv.loc[idx[test_tickers, pd.Timestamp("2026-04-01") :], columns].head(3))

# Slice 4: specific start/end range, all columns
display(
    df_ohlcv.loc[
        idx[test_tickers, pd.Timestamp("2026-04-01") : pd.Timestamp("2026-04-10")], :
    ].head(3)
)

                   Adj Open  Adj High   Adj Low  Adj Close      Volume
Ticker Date
NVDA   1999-01-22  0.040063  0.044713  0.035532   0.037559  2964547212
       1999-01-25  0.040540  0.041970  0.037559   0.041494   557464453
       1999-01-26  0.041970  0.042805  0.037678   0.038274   374788019

                   Adj Open  Adj High  Adj Low  Adj Close     Volume
Ticker Date
NVDA   2026-04-01   175.795   177.164  174.547    175.545  168327949
       2026-04-02   171.980   177.283  171.170    177.183  143310037
       2026-04-06   176.954   177.583  175.555    177.433  107689668

                   Adj Close     Volume
Ticker Date
NVDA   2026-04-01    175.545  168327949
       2026-04-02    177.183  143310037
       2026-04-06    177.433  107689668

                   Adj Open  Adj High  Adj Low  Adj Close     Volume
Ticker Date
NVDA   2026-04-01   175.795   177.164  174.547    175.545  168327949
       2026-04-02   171.980   177.283  171.170    177.183  143310037
       2026-04-06   176.954   177.583  175.555    177.433  107689668

In [85]:
# Test custom combined dictionary extraction
SU.create_combined_dict(
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    tickers=_tickers,
    date_start="2026-05-01",
    date_end=None,
    verbose=False,
)

{'SGOV':             Adj Open  Adj High   Adj Low  Adj Close    Volume       ATR      ATRP       TRP       RSI    Mom_21  Consistency     IR_63   Beta_63  DD_21  AutoCorr_15    Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5  Slope_P_5_Z  Slope_V_5_Z     Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount
 Date
 2026-05-01   99.8174   99.8174   99.8075    99.8174  34010416  0.019380  0.000194  0.000379  0.999997  0.003169          0.6 -0.061535 -0.003308    0.0    -0.574082  0.000379      1.000000   0.000145   0.739754     0.083808    -0.303915  6.269530e-06         0.011905      1.368667e+09                  0.0
 2026-05-04   99.8274   99.8274   99.8174    99.8274  20905678  0.018710  0.000187  0.000100  0.999997  0.002869          0.8 -0.047193 -0.003232    0.0    -0.583954  0.000100      1.000000   0.000154   0.914948     0.373513     0.374019  6.419916e-05         0.011905      1.368667e+09                  0.0
 2026-05-05   99.8373   99.8373   99.8274    99.8373  17248897  0.018081  0.000181  0.000099  0.999997  0.002869          0.8 -0.074907 -0.003217    0.0    -0.630975  0.000099      1.000000   0.000164   1.045906     0.714718     0.956022  1.830052e-05         0.011905      1.368667e+09                  0.0
 2026-05-06   99.8472   99.8472   99.8373    99.8472  20673206  0.017496  0.000175  0.000099  0.999997  0.002869          0.8 -0.104858 -0.003284    0.0    -0.610373  0.000099      1.000000   0.000155   1.177021     0.422711     1.579517  1.877910e-06         0.011905      1.371227e+09                  0.0
 2026-05-07   99.8572   99.8572   99.8472    99.8572  17379668  0.016961  0.000170  0.000100  0.999997  0.002969          1.0 -0.121958 -0.003704    0.0    -0.589380  0.000100      1.000000   0.000100   1.003861    -1.526980     0.857613 -6.395360e-05         0.011905      1.373512e+09                  0.0
 2026-05-08   99.8870   99.8870   99.8771    99.8870  20392450  0.017878  0.000179  0.000298  0.999998  0.003169          1.0 -0.106314 -0.004216    0.0    -0.528171  0.000298      1.000000   0.000139   0.999112    -0.143429     0.818479 -1.608627e-05         0.011905      1.374582e+09                  0.0
 2026-05-11   99.8969   99.8969   99.8870    99.8969  21563560  0.017308  0.000173  0.000099  0.999998  0.002869          1.0 -0.102244 -0.004274    0.0    -0.528262  0.000099      1.000000   0.000159   1.041499     0.547240     0.969041  5.964961e-05         0.011905      1.380694e+09                  0.0
 2026-05-12   99.8969   99.9069   99.8969    99.9069  18422322  0.016786  0.000168  0.000100  0.999998  0.002869          1.0 -0.104234 -0.004290    0.0    -0.503706  0.000100      1.000000   0.000159   1.037150     0.557961     0.926228  1.999495e-05         0.011905      1.388046e+09                  0.0
 2026-05-13   99.9168   99.9168   99.9069    99.9168  16870061  0.016294  0.000163  0.000099  0.999998  0.002968          1.0 -0.113849 -0.004350    0.0    -0.483100  0.000099      1.000000   0.000139   1.017738    -0.139654     0.823368 -1.995622e-05         0.011905      1.388046e+09                  0.0
 2026-05-14   99.9268   99.9268   99.9168    99.9268  15817247  0.015845  0.000159  0.000100  0.999998  0.002869          1.0 -0.157559 -0.004425    0.0    -0.482957  0.000100      1.000000   0.000100   0.942305    -1.514540     0.493291 -5.970313e-05         0.011905      1.388046e+09                  0.0
 2026-05-15   99.9566   99.9566   99.9466    99.9566  18350700  0.016842  0.000168  0.000298  0.999998  0.003168          1.0 -0.133047 -0.004637    0.0    -0.482181  0.000298      1.000000   0.000139   0.893176    -0.117234     0.275892  1.487088e-07         0.011905      1.392964e+09                  0.0
 2026-05-18   99.9665   99.9665   99.9566    99.9665  23701076  0.016346  0.000164  0.000099  0.999998  0.002969          1.0 -0.128845 -0.004610    0.0    -0.409115  0.000099      1.000000   0.000159   0.952812     0.587965     0.502406  5.950798e-05         0.011905      1.398331e+09                  0.0
 2026-05-19   99.9765   99.9765   99.9665    99.9765  20575831  0.015892  0.000159  0.000100  0.999999  0.002969          1.0 -0.108418 -0.004547    0.0    -0.368606  0.000100      1.000000   0.000159   1.027590     0.632336     0.788670  1.978084e-05         0.011905      1.402871e+09                  0.0
 2026-05-20   99.9864   99.9864   99.9765    99.9864  17041473  0.015464  0.000155  0.000099  0.999999  0.002870          1.0 -0.129655 -0.004592    0.0    -0.344094  0.000099      1.000000   0.000139   1.046321    -0.085210     0.839741 -1.994230e-05         0.011905      1.402871e+09                  0.0
 2026-05-21   99.9963   99.9963   99.9864    99.9864  17463161  0.015067  0.000151  0.000099  0.999999  0.002769          0.8 -0.121446 -0.004706    0.0    -0.343879  0.000000      0.961373   0.000080   0.820294    -2.150719    -0.134145 -7.966325e-05         0.011905      1.406084e+09                  0.0
 2026-05-22  100.0310  100.0360  100.0260   100.0360  18542834  0.017534  0.000175  0.000496  0.999999  0.003167          0.8 -0.146871 -0.004514    0.0    -0.374746  0.000496      1.000000   0.000149   0.658135     0.301475    -0.817471  9.741687e-06         0.011905      1.407978e+09                  0.0
 2026-05-26  100.0460  100.0460  100.0360   100.0460  21793116  0.016995  0.000170  0.000100  0.999999  0.002968          0.8 -0.145724 -0.004403    0.0    -0.333530  0.000100      1.000000   0.000189   0.673366     1.641483    -0.755837  1.090571e-04         0.011905      1.410831e+09                  0.0
 2026-05-27  100.0460  100.0560  100.0460   100.0560  15575924  0.016496  0.000165  0.000100  0.999999  0.003069          0.8 -0.131438 -0.004367    0.0    -0.333691  0.000100      1.000000   0.000199   0.765140     1.900641    -0.380837  4.986074e-05         0.011905      1.415623e+09                  0.0
 2026-05-28  100.0640  100.0660  100.0560   100.0560  16715651  0.016032  0.000160  0.000100  0.999999  0.002870          0.6 -0.151471 -0.004432    0.0    -0.299961  0.000000      0.965084   0.000159   0.749372     0.542161    -0.465008 -2.941751e-05         0.011905      1.420056e+09                  0.0
 2026-05-29  100.0760  100.0860  100.0760   100.0760  34427578  0.017030  0.000170  0.000300  0.999999  0.002971          0.8 -0.164823 -0.004384    0.0    -0.329843  0.000200      0.964093   0.000090   0.794432    -1.748392    -0.266378 -1.088107e-04         0.011905      1.422333e+09                  0.0
 2026-06-01  100.1050  100.1050  100.0950   100.1050  40015356  0.017885  0.000179  0.000290  0.999999  0.003261          0.8 -0.168299 -0.004358    0.0    -0.267232  0.000290      1.000000   0.000138   1.064324    -0.143438     0.953488 -2.126352e-05         0.011905      1.425396e+09                  0.0
 2026-06-02  100.1140  100.1150  100.1050   100.1050  22281213  0.017321  0.000173  0.000100  0.999999  0.002881          0.6 -0.188528 -0.004322    0.0    -0.316560  0.000000      0.965229   0.000147   1.106190     0.172651     1.256803  5.693163e-05         0.011905      1.425396e+09                  0.0
 2026-06-03  100.1250  100.1250  100.1150   100.1150  20058176  0.017513  0.000175  0.000200  0.999999  0.002881          0.6 -0.162727 -0.004057    0.0    -0.289243  0.000100      0.965242   0.000147   1.132259     0.166347     1.433222  8.975189e-06         0.011905      1.425396e+09                  0.0
 2026-06-04  100.1300  100.1350  100.1250   100.1250  18857145  0.017690  0.000177  0.000200  0.999999  0.002882          0.8 -0.180045 -0.004177    0.0    -0.289361  0.000100      0.965254   0.000108   0.875951    -1.151055     0.177186 -3.899114e-05         0.011905      1.431304e+09                  0.0
 2026-06-05  100.1600  100.1650  100.1450   100.1550  27918989  0.019284  0.000193  0.000399  0.999999  0.003083          0.8 -0.149890 -0.003870    0.0    -0.307523  0.000300      0.965266   0.000120   0.844608    -0.728847     0.016687 -2.702578e-05         0.011905      1.435258e+09                  0.0
 2026-06-08  100.1550  100.1750  100.1550   100.1650  24166756  0.019335  0.000193  0.000200  0.999999  0.003082          0.8 -0.139637 -0.003858    0.0    -0.307651  0.000100      0.965278   0.000160   1.116432     0.621405     1.326554  5.189367e-05         0.011905      1.436794e+09                  0.0
 2026-06-09  100.1750  100.1750  100.1650   100.1750  25823428  0.018668  0.000186  0.000100  0.999999  0.002883          1.0 -0.137099 -0.003897    0.0    -0.289021  0.000100      1.000000   0.000160   1.192397     0.628505     1.639583  3.992114e-05         0.011905      1.438505e+09                  0.0
 2026-06-10  100.1800  100.1850  100.1750   100.1850  20422247  0.018049  0.000180  0.000100  1.000000  0.002884          1.0 -0.109982 -0.003553    0.0    -0.289139  0.000100      1.000000   0.000140   1.190812    -0.043878     1.568796 -2.000295e-05         0.011905      1.440372e+09                  0.0
 2026-06-11  100.1950  100.1950  100.1850   100.1950  25001211  0.017474  0.000174  0.000100  1.000000  0.002884          1.0 -0.163387 -0.003807    0.0    -0.289256  0.000100      1.000000   0.000100   1.136843    -1.399579     1.271631 -5.994303e-05         0.011905      1.446816e+09                  0.0
 2026-06-12  100.2240  100.2240  100.2140   100.2140  23214758  0.018297  0.000183  0.000289  1.000000  0.002974          1.0 -0.182551 -0.003593    0.0    -0.332410  0.000190      0.963951   0.000118   1.116779    -0.770340     1.142218 -2.200363e-05         0.011905      1.452102e+09                  0.0
 2026-06-15  100.2290  100.2340  100.2240   100.2340  25305103  0.018419  0.000184  0.000200  1.000000  0.003074          1.0 -0.191663 -0.003126    0.0    -0.162934  0.000200      1.000000   0.000147   1.118521     0.214066     1.116682  4.687614e-05         0.011905      1.460385e+09                  0.0
 2026-06-16  100.2440  100.2440  100.2340   100.2440  20401787  0.017818  0.000178  0.000100  1.000000  0.002875          1.0 -0.176883 -0.003044    0.0    -0.150637  0.000100      1.000000   0.000157   1.114255     0.546682     1.063091  3.888625e-05         0.011905      1.468433e+09                  0.0
 2026-06-17  100.2540  100.2640  100.2440   100.2540  16022310  0.017974  0.000179  0.000199  1.000000  0.002876          1.0 -0.179932 -0.003078    0.0    -0.150504  0.000100      0.965217   0.000148   1.011902     0.237764     0.576283  9.656977e-07         0.011905      1.475684e+09                  0.0
 2026-06-18  100.2940  100.2940  100.2840   100.2940  18652543  0.019547  0.000195  0.000399  1.000000  0.003176          1.0 -0.199429 -0.002796    0.0    -0.226530  0.000399      1.000000   0.000180   0.922654     1.281806     0.143738  2.288200e-05         0.011905      1.483655e+09                  0.0
 2026-06-22  100.2990  100.3040  100.2940   100.3040  20377214  0.018865  0.000188  0.000100  1.000000  0.003176          1.0 -0.222651 -0.002426    0.0    -0.240324  0.000100      1.000000   0.000189   0.867837     1.559655    -0.123159  4.182313e-05         0.011905      1.484783e+09                  0.0
 2026-06-23  100.3040  100.3140  100.3040   100.3140  18599989  0.018232  0.000182  0.000100  1.000000  0.003276          1.0 -0.177889 -0.002006    0.0    -0.283164  0.000100      1.000000   0.000189   0.874149     1.503700    -0.115991  9.925425e-06         0.011905      1.485183e+09                  0.0
 2026-06-24  100.3240  100.3240  100.3140   100.3240  18064916  0.017644  0.000176  0.000100  1.000000  0.002879          1.0 -0.183298 -0.001857    0.0    -0.145036  0.000100      1.000000   0.000160   0.896804     0.501058    -0.028269 -2.995432e-05         0.011905      1.487309e+09                  0.0
 2026-06-25  100.3240  100.3340  100.3240   100.3340  17924102  0.017098  0.000170  0.000100  1.000000  0.002879          1.0 -0.176616 -0.001768    0.0    -0.195466  0.000100      1.000000   0.000100   0.882168    -1.436377    -0.122569 -8.978440e-05         0.011905      1.493400e+09                  0.0
 2026-06-26  100.3540  100.3640  100.3540   100.3540  14195138  0.018019  0.000180  0.000299  1.000000  0.002978          1.0 -0.199093 -0.002119    0.0    -0.234726  0.000199      0.965278   0.000120   0.822514    -0.795347    -0.450385 -3.992847e-05         0.011905      1.493400e+09                  0.0
 2026-06-29  100.3640  100.3740  100.3640   100.3740  18876502  0.018161  0.000181  0.000199  1.000000  0.003178          1.0 -0.259821 -0.001488    0.0    -0.163907  0.000199      1.000000   0.000149   0.807099     0.185345    -0.532824  4.980028e-05         0.011905      1.498537e+09                  0.0
 2026-06-30  100.3740  100.3840  100.3740   100.3740  29025944  0.017578  0.000175  0.000100  1.000000  0.002978          0.8 -0.279189 -0.001677    0.0    -0.172441  0.000000      0.964158   0.000140   0.640619    -0.142406    -1.334589  1.990363e-05         0.011905      1.502443e+09                  0.0
 2026-07-01  100.3950  100.4000  100.3900   100.4000  38244700  0.018180  0.000181  0.000259  1.000000  0.002947          0.8 -0.243190 -0.001196    0.0    -0.302821  0.000259      1.000000   0.000151   0.763991     0.242860    -0.705957  1.957538e-06         0.011905      1.502443e+09                  0.0
 2026-07-02  100.4300  100.4400  100.4300   100.4400  22627800  0.019738  0.000197  0.000398  1.000000  0.003346          0.8 -0.227005 -0.001485    0.0    -0.076783  0.000398      1.000000   0.000197   0.936120     1.674292     0.157018  5.770852e-05         0.011905      1.502443e+09                  0.0
 2026-07-06  100.4400  100.4500  100.4400   100.4400  20795500  0.019043  0.000190  0.000100  1.000000  0.003246          0.6 -0.240994 -0.001607    0.0    -0.289975  0.000000      0.967213   0.000197   0.864986     1.629963    -0.175146  4.575261e-05         0.011905      1.508403e+09                  0.0
 2026-07-07  100.4500  100.4600  100.4500   100.4600  18518200  0.019111  0.000190  0.000199  1.000000  0.003346          0.6 -0.222511 -0.001651    0.0    -0.293269  0.000199      1.000000   0.000211   0.862744     2.061413    -0.154695  1.389881e-05         0.011905      1.511911e+09                  0.0
 2026-07-08  100.4600  100.4700  100.4600   100.4700  19251300  0.018460  0.000184  0.000100  1.000000  0.003145          0.8 -0.215556 -0.001609    0.0    -0.307140  0.000100      1.000000   0.000159   0.668156     0.479156    -1.188429 -3.789337e-05         0.011905      1.514239e+09                  0.0
 2026-07-09  100.4800  100.4800  100.4700   100.4800  15296600  0.017856  0.000178  0.000100  1.000000  0.003145          0.8 -0.195525 -0.001066    0.0    -0.277621  0.000100      1.000000   0.000109   0.692336    -1.121604    -1.021645 -1.016206e-04         0.011905      1.519096e+09                  0.0
 2026-07-10  100.5000  100.5100  100.5000   100.5000  15612400  0.018723  0.000186  0.000299  1.000000  0.003244          0.8 -0.192763 -0.000991    0.0    -0.306873  0.000199      0.969231   0.000139   0.828682    -0.201611    -0.266484 -1.995896e-05         0.011905      1.527507e+09                  0.0
 2026-07-13  100.5100  100.5200  100.5100   100.5200  15894500  0.018814  0.000187  0.000199  1.000000  0.003344          1.0 -0.177978 -0.000951    0.0    -0.269137  0.000199      1.000000   0.000149   0.788342     0.125339    -0.500611  3.977227e-05         0.011905      1.533948e+09                  0.0
 2026-07-14  100.5300  100.5300  100.5200   100.5200  14999500  0.018185  0.000181  0.000099  1.000000  0.003244          0.8 -0.167550 -0.000948    0.0    -0.264726  0.000000      0.967320   0.000139   0.606601    -0.198987    -1.474797 -3.664596e-08         0.011905      1.533948e+09                  0.0
 2026-07-15  100.5350  100.5400  100.5300   100.5400  15943300  0.018315  0.000182  0.000199  1.000000  0.003253          0.8 -0.153425 -0.000565    0.0    -0.308070  0.000199      1.000000   0.000139   0.540222    -0.184308    -1.767784 -9.980447e-06         0.011905      1.535977e+09                  0.0
 2026-07-16  100.5450  100.5500  100.5400   100.5500  16153800  0.017721  0.000176  0.000099  1.000000  0.003153          0.8 -0.127697 -0.000577    0.0    -0.337795  0.000099      1.000000   0.000119   0.550158    -0.848908    -1.663086 -1.993613e-05         0.011905      1.536968e+09                  0.0
 2026-07-17  100.5800  100.5800  100.5700   100.5800  20738600  0.018598  0.000185  0.000298  1.000000  0.003352          0.8 -0.101591 -0.000906    0.0    -0.379508  0.000298      1.000000   0.000149   0.680213     0.139745    -1.005291  9.894341e-06         0.011905      1.537470e+09                  0.0,
 'SHV':             Adj Open  Adj High  Adj Low  Adj Close   Volume       ATR      ATRP       TRP       RSI    Mom_21  Consistency     IR_63   Beta_63     DD_21  AutoCorr_15    Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5  Slope_P_5_Z  Slope_V_5_Z     Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount
 Date
 2026-05-01   109.453   109.453  109.443    109.443  3457935  0.021441  0.000196  0.000347  0.999981  0.003080          0.8 -0.062512 -0.000043  0.000000    -0.372977  0.000256      0.967320   0.000124   0.635910    -0.354227    -0.850266  1.458325e-05              0.0      2.788740e+08                  0.0
 2026-05-04   109.462   109.462  109.453    109.462  2395688  0.021267  0.000194  0.000174  0.999983  0.002886          0.8 -0.048183 -0.000122  0.000000    -0.286135  0.000174      1.000000   0.000166   0.810528     0.898563    -0.289312  8.405137e-05              0.0      2.776825e+08                  0.0
 2026-05-05   109.462   109.472  109.462    109.462  3081924  0.020462  0.000187  0.000091  0.999983  0.002794          0.6 -0.075952 -0.000370  0.000000    -0.280393  0.000000      0.966102   0.000165   0.777431     0.882544    -0.371851  4.110085e-05              0.0      2.776825e+08                  0.0
 2026-05-06   109.472   109.482  109.472    109.482  2309179  0.020429  0.000187  0.000183  0.999985  0.002885          0.8 -0.105681 -0.000396  0.000000    -0.280174  0.000183      1.000000   0.000140   0.596988     0.111128    -0.919956 -2.653132e-05              0.0      2.761295e+08                  0.0
 2026-05-07   109.492   109.492  109.482    109.492  2283126  0.019684  0.000180  0.000091  0.999985  0.002885          0.8 -0.123412 -0.000027  0.000000    -0.337195  0.000091      1.000000   0.000108   0.523187    -0.842697    -1.121677 -5.760709e-05              0.0      2.755156e+08                  0.0
 2026-05-08   109.522   109.532  109.512    109.532  1749790  0.021135  0.000193  0.000365  0.999988  0.003068          0.8 -0.107480  0.000144  0.000000    -0.360337  0.000365      1.000000   0.000155   0.559620     0.572011    -0.976297  1.546926e-05              0.0      2.753101e+08                  0.0
 2026-05-11   109.532   109.532  109.522    109.532  1914559  0.020340  0.000186  0.000091  0.999988  0.002802          0.6 -0.103538  0.000081  0.000000    -0.333093  0.000000      1.000000   0.000174   0.543243     1.117350    -0.996368  6.572277e-05              0.0      2.749759e+08                  0.0
 2026-05-12   109.542   109.542  109.532    109.542  1525068  0.019601  0.000179  0.000091  0.999989  0.002893          0.8 -0.105376  0.000007  0.000000    -0.332910  0.000091      1.000000   0.000146   0.423408     0.306392    -1.330105 -9.157692e-06              0.0      2.742781e+08                  0.0
 2026-05-13   109.542   109.552  109.542    109.542  3583373  0.018915  0.000173  0.000091  0.999989  0.002709          0.6 -0.115351 -0.000118  0.000000    -0.269171  0.000000      0.966216   0.000100   0.269091    -1.058463    -1.738213 -7.307721e-05              0.0      2.742781e+08                  0.0

 # Section 8: Finviz Ingestion & Filtering

In [86]:
# Load latest updated Finviz dataset dynamically
def load_latest_finviz_parquet(data_dir: Path) -> pd.DataFrame:
    pattern = "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_df_finviz_merged_stocks_etfs.parquet"
    files = list(data_dir.glob(pattern))

    if not files:
        print(f"DEBUG: No files matching pattern found in {data_dir.absolute()}")
        return None

    latest_path = max(files, key=lambda x: x.name)
    print(f"DEBUG: Loading file: {latest_path.name}")

    try:
        return pd.read_parquet(latest_path)
    except Exception as e:
        print(f"DEBUG: Failed to read {latest_path.name}. Error: {e}")
        return None


# Load the file using the unified data_dir path
df_finviz = load_latest_finviz_parquet(GLOBAL_DATA_DIR)
print(
    f"df_finviz raw records shape: {df_finviz.shape if df_finviz is not None else None}"
)

DEBUG: Loading file: 2026-07-17_df_finviz_merged_stocks_etfs.parquet
df_finviz raw records shape: (1426, 139)

In [87]:
display(df_finviz.head())
display(df_finviz.tail())

       No.         Company               Index                  Sector                        Industry Country Exchange                                               Info  MktCap AUM, M  Rank  Market Cap, M    P/E  Fwd P/E   PEG    P/S    P/B    P/C  P/FCF  Book/sh  Cash/sh  Dividend %  Dividend TTM Dividend Ex Date  Payout Ratio %    EPS  EPS next Q  EPS this Y %  EPS next Y %  EPS past 5Y %  EPS next 5Y %  Sales past 5Y %  Sales Q/Q %  EPS Q/Q %  EPS YoY TTM %  Sales YoY TTM %  Sales, M  Income, M  EPS Surprise %  Revenue Surprise %  Outstanding, M  Float, M  Float %  Insider Own %  Insider Trans %  Inst Own %  Inst Trans %  Short Float %  Short Ratio  Short Interest, M  ROA %   ROE %  ROIC %  Curr R  Quick R  LTDebt/Eq  Debt/Eq  Gross M %  Oper M %  Profit M %  Perf 3D %  Perf Week %  Perf Month %  Perf Quart %  Perf Half %  Perf Year %  Perf YTD %  Beta    ATR  ATR/Price %  Volatility W %  Volatility M %  SMA20 %  SMA50 %  SMA200 %  50D High %  50D Low %  52W High %  52W Low %        52W Range  All-Time High %  All-Time Low %    RSI  Earnings    IPO Date Optionable Shortable  Employees  Change from Open %  Gap %  Recom  Avg Volume, M  Rel Volume     Volume  Target Price  Prev Close    Open    High     Low   Price  Change % Single Category Asset Type  Expense %  Holdings  AUM, M  Flows 1M, M  Flows% 1M  Flows 3M, M  Flows% 3M  Flows YTD, M  Flows% YTD  Return% 1Y  Return% 3Y  Return% 5Y Tags   Sharpe 3d   Sortino 3d    Omega 3d  Sharpe 5d  Sortino 5d  Omega 5d  Sharpe 10d  Sortino 10d  Omega 10d  Sharpe 15d  Sortino 15d  Omega 15d  Sharpe 30d  Sortino 30d  Omega 30d  Sharpe 60d  Sortino 60d  Omega 60d  Sharpe 120d  Sortino 120d  Omega 120d  Sharpe 250d  Sortino 250d  Omega 250d
NVDA     1     NVIDIA Corp  DJIA, NDX, S&P 500              Technology                  Semiconductors     USA     NASD                         Technology, Semiconductors      5016420.0     1      5016420.0  31.75      NaN  0.34  19.79  25.69  62.26  42.13     8.07     3.33        0.31          0.28         6/4/2026            0.82   6.53        2.08           NaN           NaN            NaN            NaN              NaN        85.23     213.42         109.57            70.68  253490.0   159610.0            6.52                3.43         24220.0   23270.0    96.07           3.85            -0.33       70.44          0.00           1.33         1.99             310.13  82.97  114.29   77.17    3.44     2.85       0.06     0.07      74.15     64.02       62.97  -4.244570        -2.13         -1.61          2.59        11.31        20.95       11.15  2.22   7.20     3.473395            3.13            3.31     2.78    -1.17      7.64      -12.37       9.21      -12.37      26.34  164.07 - 236.54           -12.37       621769.95  52.24  May 20/a   1/22/1999        Yes       Yes    42000.0               -0.12   2.10   1.23         156.20        0.70  108685563        313.74      203.28  207.54  208.65  204.01  207.29      1.97                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    - -278.986352   -15.861674    0.000000  -0.372315   -0.682930  0.939110    2.321686     4.178263   1.434780    2.460691     4.368984   1.467117   -1.458425    -1.954923   0.796620    0.142354     0.214060   1.022596     0.550344      0.825261    1.092388     0.544999      0.799288    1.092006
AAPL     2       Apple Inc  DJIA, NDX, S&P 500              Technology            Consumer Electronics     USA     NASD                   Technology, Consumer Electronics      4813630.0     2      4813630.0  39.65      NaN  2.62  10.66  45.14  70.26  37.26     7.26     4.66        0.33          1.05        5/11/2026           13.66   8.27        1.89           NaN           NaN            NaN            NaN              NaN        16.60      22.04          28.91            12.76  451440.0   122580.0            3.30                1.58         14690.0   14670.0    99.88           0.12            -2.21       67.21          0.00           0.96         2.55             140.53  34.91  141.47   67.76    1.07     1.02       0.70     0.80      47.86     32.64       27.15   5.996316         4.09          9.98         20.03        28.26        54.25       20.55  1.07   8.21     2.505034            2.64            2.79     6.24     7.73     19.21       -2.16      19.72       -2.16      62.65  201.50 - 334.99            -2.16       515084.78  64.54  Jul 30/a  12/12/1980        Yes       Yes   166000.0                1.43  -1.06   2.04          55.10        0.75   41338917        321.28      326.59  323.13  329.60  322.22  327.74      0.35                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    -   13.006772  9918.843399  884.640802   9.611452   51.186814  7.448932    7.760268    32.155268   4.721830   10.679806    53.271708   7.567258    1.806564     2.680799   1.363610    3.080708     4.852769   1.708333     2.099500      3.195737    1.431509     1.839780      2.947064    1.387544
GOOGL    3    Alphabet Inc  DJIA, NDX, S&P 500  Communication Services  Internet Content & Information     USA     NASD  Communication Services, Internet Content & Inf...      4222970.0     3      4222970.0  26.48      NaN  1.37   9.98   8.79  33.29  65.54    39.51    10.43        0.25          0.85         6/8/2026            7.68  13.11        2.88           NaN           NaN            NaN            NaN              NaN        22.34      81.96          46.22            17.77  423170.0   160210.0           90.47                2.73         12170.0    5830.0    47.91          52.09            -0.04       39.25          0.00           1.47         2.70              85.86  27.17   38.88   28.04    1.92     1.92       0.19     0.20      60.43     33.63       37.86  -3.543712        -3.44         -5.67          2.88         5.20        82.61       10.91  1.24  11.29     3.252196            3.38            3.00    -2.20    -5.83      7.57      -15.04       5.13      -15.04      86.49  186.15 - 408.61           -15.04        14356.60  43.10  Jul 22/a   8/19/2004        Yes       Yes   190820.0               -1.19  -0.19   1.38          31.84        0.73   23369833        437.93      351.99  351.32  351.32  347.00  347.15     -1.38                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    -  -32.855882   -15.022014    0.000000  -1.687403   -2.417728  0.772389   -4.303723    -5.324823   0.491562    1.393907     2.249898   1.259486   -1.778743    -2.354664   0.744765    0.328070     0.544563   1.062915     0.303548      0.492199    1.055062     2.022028      3.626904    1.431936
GOOG     4    Alphabet Inc        NDX, S&P 500  Communication Services  Internet Content & Information     USA     NASD  Communication Services, Internet Content & Inf...      4218720.0     4      4218720.0  26.41      NaN  1.38   9.97   8.76  33.26  65.48    39.51    10.41        0.25          0.85         6/8/2026            7.68  13.11        2.88           NaN           NaN            NaN            NaN              NaN        22.34      81.96          46.22            17.77  423170.0   160210.0           90.39                2.74          5460.0    5090.0    93.37          58.15            -0.03       27.58          0.00           1.15         2.70              58.49  27.17   38.88   28.04    1.92     1.92       0.19     0.20      60.43     33.63       37.86  -3.137156        -3.12         -5.79          3.22         4.80        81.11       10.32  1.23  11.16     3.223663            3.44            2.90    -1.94    -5.44      7.51      -14.41       3.75      -14.41      85.08  187.05 - 404.47           -14.41         1323.99  43.85  Jul 22/a   3/27/2014        Yes       Yes   190820.0               -1.25  -0.23   1.38          21.69        0.80   17419521        437.79      351.37  350.56  350.74  346.01  346.19     -1.47                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    -  -33.007525   -15.029216    0.000000  -1.254107   -1.862989  0.824697   -3.995760    -5.133498   0.512747    1.643225     2.776139   1.315443   -1.552018    -2.097562   0.774903    0.360734     0.608842   1.069003     0.284796      0.466120    1.051524     2.016694      3.636671    1.430210
MSFT     5  Microsoft Corp  DJIA, NDX, S&P 500              Technology       Software - Infrastructure     USA     NASD              Technology, Software - Infrastructure      2954660.0     5      2954660.0  23.69      NaN  1.10   9.28   7.13  37.75  40.52    55.78    10.54        0.93          3.56        8/20/2026           24.34  16.79        4.24           NaN           NaN            NaN            NaN              NaN        18.30      23.32          29.64            17.87  318270.0   125220.0            5.18                1.77          7430.0    7310.0    98.46           1.54            -0.03       75.97         -1.37           1.22         2.26              89.06  19.93   34.01   24.02    1.28     1.27       0.26     0.30      68.31     46.80       39.34   2.309511         3.33          4.84         -4.86       -13.51       -22.02      -17.76  1.11  11.76     2.956631            2.78            3.00     3.63    -0.77     -9.22      -14.70      13.90      -28.39      13.90  349.20 - 555.45           -28.39       499092.76  53.40  Jul 29/a   3/13/1986        Yes       Yes   228000.0               -0.26  -0.87   1.23          39.36        0.61   24126632        555.30      402.29  398.80  401.47  396.32  397.75     -1.13                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    -   -1.629361    -2.845661    0.746488   1.295001    2.418029  1.216070    1.992301     3.345140   1.366930    3.820156     7.153920   1.770666   -2.010087    -2.803024   0.733948   -1.090151    -1.535080   0.839175    -1.001362     -1.312144    0.841918    -0.927819     -1.221604    0.848709

      No.                                            Company Index     Sector              Industry Country Exchange                                               Info  MktCap AUM, M  Rank  Market Cap, M  P/E  Fwd P/E  PEG  P/S  P/B  P/C  P/FCF  Book/sh  Cash/sh  Dividend %  Dividend TTM Dividend Ex Date  Payout Ratio %  EPS  EPS next Q  EPS this Y %  EPS next Y %  EPS past 5Y %  EPS next 5Y %  Sales past 5Y %  Sales Q/Q %  EPS Q/Q %  EPS YoY TTM %  Sales YoY TTM %  Sales, M  Income, M  EPS Surprise %  Revenue Surprise %  Outstanding, M  Float, M  Float %  Insider Own %  Insider Trans %  Inst Own %  Inst Trans %  Short Float %  Short Ratio  Short Interest, M  ROA %  ROE %  ROIC %  Curr R  Quick R  LTDebt/Eq  Debt/Eq  Gross M %  Oper M %  Profit M %  Perf 3D %  Perf Week %  Perf Month %  Perf Quart %  Perf Half %  Perf Year %  Perf YTD %  Beta   ATR  ATR/Price %  Volatility W %  Volatility M %  SMA20 %  SMA50 %  SMA200 %  50D High %  50D Low %  52W High %  52W Low %        52W Range  All-Time High %  All-Time Low %    RSI Earnings    IPO Date Optionable Shortable  Employees  Change from Open %  Gap %  Recom  Avg Volume, M  Rel Volume    Volume  Target Price  Prev Close    Open    High     Low   Price  Change %                Single Category         Asset Type  Expense %  Holdings  AUM, M  Flows 1M, M  Flows% 1M  Flows 3M, M  Flows% 3M  Flows YTD, M  Flows% YTD  Return% 1Y  Return% 3Y  Return% 5Y                                               Tags  Sharpe 3d  Sortino 3d  Omega 3d  Sharpe 5d  Sortino 5d  Omega 5d  Sharpe 10d  Sortino 10d  Omega 10d  Sharpe 15d  Sortino 15d  Omega 15d  Sharpe 30d  Sortino 30d  Omega 30d  Sharpe 60d  Sortino 60d  Omega 60d  Sharpe 120d  Sortino 120d  Omega 120d  Sharpe 250d  Sortino 250d  Omega 250d
SBIL  394               Simplify Government Money Market ETF     -  Financial  Exchange Traded Fund     USA     NYSE  Financial, Exchange Traded Fund, Bonds - Money...         5030.0  1554            NaN  NaN      NaN  NaN  NaN  NaN  NaN    NaN      NaN      NaN        3.55          3.56        6/25/2026             NaN  NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN       NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.07               0.02    NaN    NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN   0.039916         0.07          0.01          0.02         0.01         0.19        0.19 -0.00  0.05     0.049860            0.02            0.03     0.12     0.10      0.10       -0.19       0.27       -0.43       0.27  100.01 - 100.71            -0.43            0.27  66.31        -   7/15/2025         No       Yes        NaN                0.00   0.01    NaN        0.25224        0.32     80043           NaN      100.27  100.28  100.29  100.27  100.28      0.01           Bonds - Money Market              Bonds       0.15     166.0  5030.0          NaN       2.22          NaN       4.78        615.99       13.96        3.87         NaN         NaN  U.S., fixed-income, debt, bonds, government-bonds  -0.679437   -1.281318  0.885851  -6.631362   -8.063849  0.373569    1.090253     1.572784   1.183270   -1.368435    -1.758833   0.808439   -2.277987    -2.840040   0.703918   -1.390021    -1.759697   0.795634    -1.983742     -2.565138    0.731820    -0.913346     -1.278601    0.863335
EAGG  396          iShares ESG Aware U.S. Aggregate Bond ETF     -  Financial  Exchange Traded Fund     USA     NYSE  Financial, Exchange Traded Fund, Bonds - Broad...         4990.0  1556            NaN  NaN      NaN  NaN  NaN  NaN  NaN    NaN      NaN      NaN        4.04          1.89         7/1/2026             NaN  NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN       NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         3.07               1.25    NaN    NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN   0.234442        -0.23         -1.14         -2.11        -2.34        -0.76       -2.17  0.26  0.15     0.320444            0.21            0.20    -0.72    -0.80     -1.95       -1.72       0.22       -3.68       0.22    46.71 - 48.60           -18.15            6.22  37.73        -  10/23/2018        Yes       Yes        NaN               -0.13  -0.09    NaN        0.40631        0.37    151407           NaN       46.91   46.87   46.87   46.79   46.81     -0.21           Bonds - Broad Market              Bonds       0.10    5142.0  4990.0          NaN       3.62          NaN       7.75        688.12       16.00        3.93        3.58       -0.24  U.S., fixed-income, corporate-bonds, debt-secu...  -4.186487   -6.098475  0.456705  11.517052   55.175694  7.951484   -4.142448    -4.823654   0.514101   -5.476661    -5.850667   0.394584   -1.197108    -1.593790   0.823879   -1.432123    -1.874108   0.796103    -1.027892     -1.353351    0.848708    -0.059391     -0.083883    0.990489
SJNK  397  State Street SPDR Bloomberg Short Term High Yi...     -  Financial  Exchange Traded Fund     USA     NYSE  Financial, Exchange Traded Fund, Bonds - Corpo...         4920.0  1557            NaN  NaN      NaN  NaN  NaN  NaN  NaN    NaN      NaN      NaN        7.03          1.75         7/1/2026             NaN  NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN       NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.55               1.35    NaN    NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN   0.040145        -0.08         -0.60         -1.35        -2.20        -2.08       -1.70  0.29  0.05     0.200884            0.13            0.15    -0.24    -0.37     -1.17       -1.03       0.12       -2.96       0.69    24.72 - 25.65           -20.17           16.20  42.00        -   3/15/2012        Yes       Yes        NaN               -0.16   0.04    NaN        2.47000        0.62   1535859           NaN       24.92   24.93   24.93   24.89   24.89     -0.12              Bonds - Corporate              Bonds       0.40    1156.0  4920.0          NaN       1.86          NaN       6.68       -246.65       -4.78        5.32        7.69        4.78  U.S., fixed-income, corporate-bonds, bonds, hi... -15.668636  -12.904716  0.000000   3.928030    7.933977  1.869476   -5.084632    -5.937641   0.478042    0.071192     0.099171   1.010189   -0.218092    -0.329462   0.964946   -0.529269    -0.751357   0.918874    -0.336492     -0.476567    0.944999     0.329720      0.483874    1.057673
SLYV  398   State Street SPDR S&P 600 TM Small Cap Value ETF     -  Financial  Exchange Traded Fund     USA     NYSE  Financial, Exchange Traded Fund, US Equities -...         4890.0  1558            NaN  NaN      NaN  NaN  NaN  NaN  NaN    NaN      NaN      NaN        1.80          1.98        6/22/2026             NaN  NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN       NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.35               0.08    NaN    NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN   1.166667         1.44          2.58          6.98        12.30        33.48       20.44  1.00  1.42     1.296093            1.25            1.15     1.32     3.59     12.60       -0.88      10.11       -0.88      39.46   78.56 - 110.53            -0.88          798.75  59.52        -   9/29/2000        Yes       Yes        NaN                0.73   0.23    NaN        0.22757        0.58    132393           NaN      108.52  108.77  109.58  108.50  109.56      0.96         US Equities - US Style  Equities (Stocks)       0.15     463.0  4890.0          NaN       1.36          NaN       4.92         39.12        0.81       33.91       13.54        7.26              U.S., equity, value, small-cap, SP600   2.716092    7.166175  1.638414   5.485368   12.091090  2.523334    2.057106     3.334690   1.375439   -0.117890    -0.178141   0.981421    1.988684     3.122302   1.352788    1.892572     2.932729   1.327379     1.529053      2.293893    1.273384     1.598342      2.561445    1.301878
KRE   399         State Street SPDR S&P Regional Banking ETF     -  Financial  Exchange Traded Fund     USA     NYSE  Financial, Exchange Traded Fund, US Equities -...         4850.0  1559            NaN  NaN      NaN  NaN  NaN  NaN  NaN    NaN      NaN      NaN        2.10          1.60        6/22/2026             NaN  NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN       NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         3.77              54.97    NaN    NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN   2.253333         1.31          5.94          7.56        11.98        20.47       17.24  0.85  1.34     1.763622            1.91            1.63     1.05     5.56     12.75       -2.71      14.39       -2.71      32.02    57.55 - 78.10            -3.59          426.91  57.98        -   6/22/2006        Yes       Yes        NaN                0.38  -0.26    NaN       14.57000        1.10  15981683           NaN       75.89   75.69   76.02   74.98   75.98      0.12  US Equities - Industry Sector  Equities (Stocks)       0.35     162.0  4850.0          NaN       5.24          NaN      13.58        396.55        8.90       23.06       23.38        6.04            U.S., equity, financial, regional-banks   3.094483    8.544499  1.761205   4.386256   10.204178  2.165055    1.592962     2.638344   1.303896    1.513244     2.438580   1.278776    4.258837     6.754182   1.917797    2.106232     3.211885   1.377805     1.204829      1.688044    1.215289     0.905662      1.316574    1.169795

In [88]:
# Set test target tickers
target_tickers = ["GLW", "NOK", "DELL", "NVDA", "GOOG"]

In [89]:
# Clean index extraction using ast exception parsing if tickers are missing
try:
    result = df_finviz.loc[target_tickers]
except KeyError as e:
    error_msg = str(e)
    missing_str = error_msg.replace(" not in index", "").strip('"').strip("'")
    missing_tickers = ast.literal_eval(missing_str)

    print(f"Missing tickers: {missing_tickers}")

    # Strip out the missing symbols and retry slicing
    target_tickers_in_finviz = [t for t in target_tickers if t not in missing_tickers]
    result = df_finviz.loc[target_tickers_in_finviz].copy()
    result.sort_values(by="MktCap AUM, M", ascending=False, inplace=True)

print(f"result shape: {result.shape}")

result shape: (5, 139)

In [90]:
# Display filtered Finviz information and schema details
result.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, GLW to GOOG
Columns: 139 entries, No. to Omega 250d
dtypes: float64(120), int64(3), object(16)
memory usage: 5.5+ KB

In [91]:
# Check specific target column (Market Capitalization)
result["MktCap AUM, M"]

GLW      139780.0
NOK       59450.0
DELL     262000.0
NVDA    5016420.0
GOOG    4218720.0
Name: MktCap AUM, M, dtype: float64

In [92]:
# Sort records descendingly by Market Capitalization
result.sort_values(by="MktCap AUM, M", ascending=False, inplace=True)

In [93]:
# View final sorted DataFrame
print(result)

      No.                Company               Index                  Sector                        Industry  Country Exchange                                               Info  MktCap AUM, M  Rank  Market Cap, M    P/E  Fwd P/E   PEG    P/S    P/B    P/C  P/FCF  Book/sh  Cash/sh  Dividend %  Dividend TTM Dividend Ex Date  Payout Ratio %    EPS  EPS next Q  EPS this Y %  EPS next Y %  EPS past 5Y %  EPS next 5Y %  Sales past 5Y %  Sales Q/Q %  EPS Q/Q %  EPS YoY TTM %  Sales YoY TTM %  Sales, M  Income, M  EPS Surprise %  Revenue Surprise %  Outstanding, M  Float, M  Float %  Insider Own %  Insider Trans %  Inst Own %  Inst Trans %  Short Float %  Short Ratio  Short Interest, M  ROA %   ROE %  ROIC %  Curr R  Quick R  LTDebt/Eq  Debt/Eq  Gross M %  Oper M %  Profit M %  Perf 3D %  Perf Week %  Perf Month %  Perf Quart %  Perf Half %  Perf Year %  Perf YTD %  Beta    ATR  ATR/Price %  Volatility W %  Volatility M %  SMA20 %  SMA50 %  SMA200 %  50D High %  50D Low %  52W High %  52W Low %        52W Range  All-Time High %  All-Time Low %    RSI  Earnings   IPO Date Optionable Shortable  Employees  Change from Open %  Gap %  Recom  Avg Volume, M  Rel Volume     Volume  Target Price  Prev Close    Open    High     Low   Price  Change % Single Category Asset Type  Expense %  Holdings  AUM, M  Flows 1M, M  Flows% 1M  Flows 3M, M  Flows% 3M  Flows YTD, M  Flows% YTD  Return% 1Y  Return% 3Y  Return% 5Y Tags   Sharpe 3d  Sortino 3d  Omega 3d  Sharpe 5d  Sortino 5d  Omega 5d  Sharpe 10d  Sortino 10d  Omega 10d  Sharpe 15d  Sortino 15d  Omega 15d  Sharpe 30d  Sortino 30d  Omega 30d  Sharpe 60d  Sortino 60d  Omega 60d  Sharpe 120d  Sortino 120d  Omega 120d  Sharpe 250d  Sortino 250d  Omega 250d
NVDA    1            NVIDIA Corp  DJIA, NDX, S&P 500              Technology                  Semiconductors      USA     NASD                         Technology, Semiconductors      5016420.0     1      5016420.0  31.75      NaN  0.34  19.79  25.69  62.26  42.13     8.07     3.33        0.31          0.28         6/4/2026            0.82   6.53        2.08           NaN           NaN            NaN            NaN              NaN        85.23     213.42         109.57            70.68  253490.0  159610.00            6.52                3.43         24220.0  23270.00    96.07           3.85            -0.33       70.44          0.00           1.33         1.99             310.13  82.97  114.29   77.17    3.44     2.85       0.06     0.07      74.15     64.02       62.97  -4.244570        -2.13         -1.61          2.59        11.31        20.95       11.15  2.22   7.20     3.473395            3.13            3.31     2.78    -1.17      7.64      -12.37       9.21      -12.37      26.34  164.07 - 236.54           -12.37       621769.95  52.24  May 20/a  1/22/1999        Yes       Yes    42000.0               -0.12   2.10   1.23         156.20        0.70  108685563        313.74      203.28  207.54  208.65  204.01  207.29      1.97                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    - -278.986352  -15.861674  0.000000  -0.372315   -0.682930  0.939110    2.321686     4.178263   1.434780    2.460691     4.368984   1.467117   -1.458425    -1.954923   0.796620    0.142354     0.214060   1.022596     0.550344      0.825261    1.092388     0.544999      0.799288    1.092006
GOOG    4           Alphabet Inc        NDX, S&P 500  Communication Services  Internet Content & Information      USA     NASD  Communication Services, Internet Content & Inf...      4218720.0     4      4218720.0  26.41      NaN  1.38   9.97   8.76  33.26  65.48    39.51    10.41        0.25          0.85         6/8/2026            7.68  13.11        2.88           NaN           NaN            NaN            NaN              NaN        22.34      81.96          46.22            17.77  423170.0  160210.00           90.39                2.74          5460.0   5090.00    93.37          58.15            -0.03       27.58          0.00           1.15         2.70              58.49  27.17   38.88   28.04    1.92     1.92       0.19     0.20      60.43     33.63       37.86  -3.137156        -3.12         -5.79          3.22         4.80        81.11       10.32  1.23  11.16     3.223663            3.44            2.90    -1.94    -5.44      7.51      -14.41       3.75      -14.41      85.08  187.05 - 404.47           -14.41         1323.99  43.85  Jul 22/a  3/27/2014        Yes       Yes   190820.0               -1.25  -0.23   1.38          21.69        0.80   17419521        437.79      351.37  350.56  350.74  346.01  346.19     -1.47                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    -  -33.007525  -15.029216  0.000000  -1.254107   -1.862989  0.824697   -3.995760    -5.133498   0.512747    1.643225     2.776139   1.315443   -1.552018    -2.097562   0.774903    0.360734     0.608842   1.069003     0.284796      0.466120    1.051524     2.016694      3.636671    1.430210
DELL   57  Dell Technologies Inc             S&P 500              Technology               Computer Hardware      USA     NYSE                      Technology, Computer Hardware       262000.0    62       262000.0  32.12      NaN  0.51   1.95    NaN  22.29  27.75    -2.16    18.13        0.61          2.31        7/21/2026           24.20  12.58        4.88           NaN           NaN            NaN            NaN              NaN        87.49     281.26          99.71            38.87  134190.0    8410.00           64.09               22.66           324.0    301.27    92.98          53.53            -2.84       40.24         -2.04           4.31         1.49              12.98   8.33     NaN   37.04    0.95     0.74        NaN      NaN      19.09      8.57        6.27 -13.375880       -11.67         -1.31         97.88       235.31       213.39      221.06  1.33  31.21     7.722380            8.74            7.43    -3.24     8.73     98.30      -13.91      77.83      -13.91     266.68  110.22 - 469.47           -13.91         3330.03  50.44  May 28/a  8/17/2016        Yes       Yes    97000.0                2.45   3.30   1.73           8.73        0.60    5277357        506.00      381.88  394.50  407.98  393.94  404.15      5.83                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    -   -6.854769   -8.511692  0.241718  -3.559157   -4.745605  0.557430   -0.951271    -1.276389   0.859810    0.147933     0.199711   1.022598   -0.517598    -0.679203   0.925934    3.001379     6.961073   1.810348     3.370270      7.529601    1.911635     1.946728      3.737766    1.454341
GLW   113            Corning Inc             S&P 500              Technology           Electronic Components      USA     NYSE                  Technology, Electronic Components       139780.0   126       139780.0  77.95      NaN  1.18   8.56  12.47  78.57  93.18    13.02     2.07        0.72          1.12        8/31/2026           61.12   2.08        0.76           NaN           NaN            NaN            NaN              NaN        20.05     134.97         298.15            20.05   16320.0    1810.00            1.19                1.09           907.0    788.05    86.89           8.43            -0.75       73.82         -1.80           2.60         1.40              20.52   6.17   16.07    8.88    1.61     1.06       0.73     0.84      35.64     16.13       11.09 -17.602857       -13.45        -16.68         -1.80        72.41       201.32       85.48  1.15  16.17     9.956283            7.69            8.36   -16.68   -15.00     22.09      -40.24      10.53      -40.24     204.77   53.29 - 271.78           -40.24        14664.55  40.96  Jul 28/b  5/21/1945        Yes       Yes    67200.0                0.69   5.36   1.75          14.68        0.69   10182878        218.54      153.10  161.30  164.50  156.60  162.41      6.08                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    -  -19.157835  -13.696616  0.000000 -12.404913  -10.861079  0.131657   -8.920434    -8.699260   0.239452   -5.021239    -6.181099   0.413384   -1.365836    -1.915295   0.808112    0.082849     0.125178   1.013586     1.564922      2.501135    1.292145     1.892300      3.016660    1.410628
NOK   285         Nokia Corp ADR                   -              Technology         Communication Equipment  Finland     NYSE                Technology, Communication Equipment        59450.0   327        59450.0  66.31      NaN  1.35   2.56   2.44   8.85  36.32     4.36     1.20        1.64          0.16        4/28/2026             NaN   0.16        0.06           NaN           NaN            NaN            NaN              NaN        13.95     253.04           9.07            12.83   23200.0     898.25           33.18               -1.18          5590.0   5590.00   100.00           0.00              NaN       16.44         -4.04           1.07         0.53              59.69   2.10    3.84    3.21    1.57     1.32       0.15     0.16      43.47      8.78        3.87 -13.504274        -9.15        -21.20          0.28        62.29       123.79       64.30  1.19   0.79     7.431797            5.63            5.03   -12.61   -22.00     18.10      -39.08       8.14      -39.08     165.75     4.00 - 17.45           -82.24          761.33  36.79  Jul 23/b   7/1/1994        Yes       Yes        NaN                1.43   3.97   2.23         113.36        0.89  101227994         13.44       10.08   10.48   10.77   10.45   10.63      5.46                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    -  -22.048186  -14.146661  0.000000 -17.117722  -12.377368  0.004930   -7.583706    -8.492876   0.304012   -6.187294    -7.004563   0.377900   -5.254454    -5.868166   0.431628    0.485094     0.733552   1.079676     1.481241      2.297884    1.274328     1.564473      2.589130    1.337263

In [94]:
# Export processed dataframe output directly to trash file
result.to_csv(output_dir / "_trash.csv")