 # Section 1: Setup, Unified Paths & Global Settings

 This cell loads essential utilities, configures global Pandas display parameters,

 silences silent-downcasting warnings, and dynamically maps project directories.

In [1]:
%load_ext autoreload
%autoreload 2

import ast

from pathlib import Path
import numpy as np
import pandas as pd

from core.contracts import EngineInput, FilterPack
from core.settings import TradingConfig
from core.utils import SystemUtils as SU
from data_pipeline import generate_features
from walk_forward import AlphaEngine, create_walk_forward_analyzer, run_headless_simulation

# 1. Global Configuration Options
config = TradingConfig()

# 2. Silence downcasting warnings & configure wide DataFrame display options
pd.set_option("future.no_silent_downcasting", True)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", 3000)

# 3. Dynamically resolve all project directories once
try:
    current_dir = Path(__file__).resolve().parent
except NameError:
    current_dir = Path.cwd()

data_dir = current_dir.parent / "data"
processed_dir = data_dir / "processed"
output_dir = current_dir.parent / "output"

print(f"Paths Resolved:\n - Root:      {current_dir}\n - Data:      {data_dir}\n - Processed: {processed_dir}\n - Output:    {output_dir}")

NOTEBOOKS_RLVR_ROOT: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2

OUTPUT_DIR: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\output

Paths Resolved:
 - Root:      c:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2
 - Data:      c:\Users\ping\Files_win10\python\py311\stocks\data
 - Processed: c:\Users\ping\Files_win10\python\py311\stocks\data\processed
 - Output:    c:\Users\ping\Files_win10\python\py311\stocks\output

 # Section 2: Ingest Raw and Processed Datasets

 Safely loads raw inputs and previously stored processed matrices with existence verifications.

In [2]:
# Define Raw File Paths
df_ohlcv_path = data_dir / "df_OHLCV_stocks_etfs.parquet"
df_fed_path = data_dir / "High_Yield_Spread_T10Y2Y_Spread.csv"
df_indices_path = data_dir / "df_indices.parquet"

# Load Raw Files
if df_ohlcv_path.exists():
    df_ohlcv = pd.read_parquet(df_ohlcv_path)
    print("[OK] Successfully loaded df_ohlcv!")
else:
    print(f"[ERROR] File not found: {df_ohlcv_path}")

if df_fed_path.exists():
    df_fed = pd.read_csv(df_fed_path)
    print("[OK] Successfully loaded df_fed!")
else:
    print(f"[ERROR] File not found: {df_fed_path}")

if df_indices_path.exists():
    df_indices = pd.read_parquet(df_indices_path)
    print("[OK] Successfully loaded df_indices!")
else:
    print(f"[ERROR] File not found: {df_indices_path}")

[OK] Successfully loaded df_ohlcv!
[OK] Successfully loaded df_fed!
[OK] Successfully loaded df_indices!

In [3]:
# Define Processed File Paths
features_df_path = processed_dir / "features_df.parquet"
macro_df_path = processed_dir / "macro_df.parquet"
df_close_wide_path = processed_dir / "df_close_wide.parquet"
df_atrp_wide_path = processed_dir / "df_atrp_wide.parquet"
df_trp_wide_path = processed_dir / "df_trp_wide.parquet"

# Load Processed Files
if features_df_path.exists():
    features_df = pd.read_parquet(features_df_path)
    print(f"[OK] Loaded features_df  | Shape: {features_df.shape}")
else:
    print(f"[ERROR] File not found: {features_df_path}")

if macro_df_path.exists():
    macro_df = pd.read_parquet(macro_df_path)
    print(f"[OK] Loaded macro_df     | Shape: {macro_df.shape}")
else:
    print(f"[ERROR] File not found: {macro_df_path}")

if df_close_wide_path.exists():
    df_close_wide = pd.read_parquet(df_close_wide_path)
    print(f"[OK] Loaded df_close_wide| Shape: {df_close_wide.shape}")
else:
    print(f"[ERROR] File not found: {df_close_wide_path}")

if df_atrp_wide_path.exists():
    df_atrp_wide = pd.read_parquet(df_atrp_wide_path)
    print(f"[OK] Loaded df_atrp_wide | Shape: {df_atrp_wide.shape}")
else:
    print(f"[ERROR] File not found: {df_atrp_wide_path}")

if df_trp_wide_path.exists():
    df_trp_wide = pd.read_parquet(df_trp_wide_path)
    print(f"[OK] Loaded df_trp_wide  | Shape: {df_trp_wide.shape}")
else:
    print(f"[ERROR] File not found: {df_trp_wide_path}")

[OK] Loaded features_df  | Shape: (9560692, 18)
[OK] Loaded macro_df     | Shape: (16220, 11)
[OK] Loaded df_close_wide| Shape: (16220, 1577)
[OK] Loaded df_atrp_wide | Shape: (16220, 1577)
[OK] Loaded df_trp_wide  | Shape: (16220, 1577)

 # Section 3: In-Memory Structural Previews

 Outputs head and tail previews of the core dataframes.

In [4]:
print("\n" + "=" * 50)
print("DATAFRAME STRUCTURAL PREVIEWS (HEAD & TAIL)")
print("=" * 50)

# 1. Preview wide matrix prices
if "df_close_wide" in locals():
    print("\n=== df_close_wide (Prices) ===")
    print("--- HEAD (First 3 Rows) ---")
    display(df_close_wide.head(3))
    print("\n--- TAIL (Last 3 Rows) ---")
    display(df_close_wide.tail(3))

# 2. Preview multi-index features
if "features_df" in locals():
    print("\n=== features_df (Multi-Index Features) ===")
    print("--- HEAD (First 3 Rows) ---")
    display(features_df.head(3))
    print("\n--- TAIL (Last 3 Rows) ---")
    display(features_df.tail(3))

# 3. Preview macro data
if "macro_df" in locals():
    print("\n=== macro_df (Macro Data) ===")
    print("--- HEAD (First 3 Rows) ---")
    display(macro_df.head(3))
    print("\n--- TAIL (Last 3 Rows) ---")
    display(macro_df.tail(3))

==================================================
DATAFRAME STRUCTURAL PREVIEWS (HEAD & TAIL)
==================================================

=== df_close_wide (Prices) ===
--- HEAD (First 3 Rows) ---

Ticker,A,AA,AAL,AAON,AAPL,ABBV,ABEV,ABNB,ABT,ABVX,ACGL,ACI,ACM,ACN,ACWI,ACWX,ADBE,ADC,ADI,ADM,ADP,ADSK,ADT,AEE,AEG,AEIS,AEM,AEP,AER,AES,AFG,AFL,AFRM,AG,AGCO,AGG,AGI,AGNC,AHR,AIG,AIQ,AIRR,AIT,AIZ,AJG,AKAM,AKRE,ALAB,ALB,ALC,ALGN,ALL,ALLE,ALLY,ALNY,ALSN,ALV,AM,AMAT,AMCR,AMD,AME,AMG,AMGN,AMH,AMKR,AMLP,AMP,AMRZ,AMT,AMTM,AMX,AMZN,AN,ANET,AON,AOS,APA,APD,APG,APH,APLD,APO,APP,APPF,APTV,AR,ARCC,ARE,ARES,ARGX,ARKK,ARM,ARMK,ARWR,AS,ASML,ASND,ASR,ASTS,ASX,ATI,ATO,ATR,AU,AUR,AVAV,AVB,AVDE,AVDV,AVEM,AVGO,AVLV,AVTR,AVUS,AVUV,AVY,AWI,AWK,AXIA,AXON,AXP,AXS,AXSM,AXTA,AYI,AZN,AZO,B,BA,BABA,BAC,BAH,BAI,BALL,BAM,BAP,BAX,BBAX,BBCA,BBD,BBEU,BBIN,BBIO,BBJP,BBUS,BBVA,BBY,BCE,BCH,BCS,BDX,BE,BEKE,BEN,BEP,BEPC,BETA,BF-A,BF-B,BG,BHP,BIDU,BIIB,BIL,BILI,BINC,BIO,BIP,BIRK,BIV,BJ,BK,BKLC,BKLN,BKNG,BKR,BLD,BLDR,BLK,BLSH,BLV,BMNR,BMO,BMRN,BMY,BN,BND,BNDX,BNO,BNS,BNT,BNTX,BOKF,BOND,BOXX,BP,BPOP,BR,BRK-A,BRK-B,BRKR,BRO,BROS,BRX,BSAC,BSBR,BSCQ,BSCR,BSOL,BSV,BSX,BSY,BTC,BTI,BUD,BUFR,BURL,BVN,BWA,BWXT,BX,BXP,BYD,BZ,C,CACI,CAE,CAG,CAH,CAI,CARR,CART,CASY,CAT,CB,CBOE,CBRE,CBSH,CCEP,CCI,CCJ,CCK,CCL,CDE,CDNS,CDP,CDW,CEF,CEG,CELH,CF,CFG,CFR,CG,CGBL,CGCP,CGDV,CGGO,CGGR,CGMU,CGUS,CGXU,CHD,CHDN,CHKP,CHRW,CHT,CHTR,CHWY,CHYM,CI,CIB,CIBR,CIEN,CIFR,CIGI,CINF,CL,CLF,CLH,CLS,CLX,CM,CMC,CMCSA,CME,CMG,CMI,CMS,CNA,CNC,CNH,CNI,CNM,CNP,CNQ,COF,COHR,COIN,COKE,COLB,COO,COP,COPX,COR,CORT,COST,COWZ,CP,CPAY,CPB,CPNG,CPRT,CPT,CQP,CR,CRBG,CRCL,CRDO,CRH,CRK,CRL,CRM,CRS,CRWD,CRWV,CSCO,CSGP,CSL,CSX,CTAS,CTRE,CTSH,CTVA,CUBE,CVE,CVNA,CVS,CVX,CW,CWB,CWEN,CWEN-A,CX,CYTK,D,DAL,DASH,DB,DBEF,DBX,DCI,DD,DDOG,DDS,DE,DECK,DELL,DEO,DFAC,DFAE,DFAI,DFAS,DFAT,DFAU,DFAX,DFCF,DFEM,DFIC,DFIS,DFIV,DFLV,DFSD,DFSV,DFUS,DFUV,DG,DGRO,DGRW,DGX,DHI,DHR,DIA,DIHP,DINO,DIS,DIVO,DKNG,DKS,DLN,DLR,DLTR,DOC,DOCS,DOCU,DON,DOV,DOW,DOX,DPZ,DRI,DRS,DSGX,DSI,DT,DTE,DTM,DUHP,DUK,DUOL,DVA,DVN,DVY,DXCM,DXJ,DY,DYNF,E,EA,EAGG,EBAY,EC,ECL,ED,EDU,EDV,EEM,EFA,EFAV,EFG,EFV,EFX,EG,EGO,EGP,EHC,EIX,EL,ELAN,ELS,ELV,EMA,EMB,EMBJ,EME,EMLC,EMN,EMR,EMXC,ENB,ENSG,ENTG,EOG,EPAM,EPD,EQH,EQIX,EQNR,EQR,EQT,EQX,ERIC,ERIE,ES,ESAB,ESGD,ESGE,ESGU,ESGV,ESLT,ESS,ESTC,ET,ETHA,ETHB,ETN,ETR,EUFN,EVR,EVRG,EVTR,EW,EWBC,EWJ,EWT,EWY,EWZ,EXC,EXE,EXEL,EXLS,EXP,EXPD,EXPE,EXR,EZU,F,FAF,FANG,FAST,FBCG,FBND,FBTC,FCFS,FCNCA,FCX,FDL,FDN,FDS,FDVV,FDX,FE,FELC,FELG,FENI,FER,FERG,FEZ,FFIV,FHN,FICO,FIG,FIGR,FIS,FISV,FITB,FIVE,FIX,FLEX,FLOT,FLR,FLS,FLUT,FMDE,FMS,FMX,FN,FND,FNDA,FNDE,FNDF,FNDX,FNF,FNV,FOX,FOXA,FPE,FR,FRHC,FRMI,FROG,FRT,FSEC,FSLR,FSS,FSV,FTAI,FTCS,FTEC,FTI,FTNT,FTS,FTSM,FTV,FUTU,FVD,FWONA,FWONK,FXI,G,GAP,GBIL,GBTC,GD,GDDY,GDS,GDX,GDXJ,GE,GEHC,GEN,GEV,GFI,GFL,GFS,GGAL,GGG,GH,GIB,GIL,GILD,GIS,GL,GLBE,GLD,GLDM,GLPI,GLW,GM,GMAB,GME,GMED,GNRC,GOOG,GOOGL,GOVT,GPC,GPN,GRAB,GRID,GRMN,GS,GSAT,GSIE,GSK,GSLC,GTLB,GTLS,GUNR,GWRE,GWW,H,HAL,HALO,HAS,HBAN,HBM,HCA,HD,HDB,HDV,HEFA,HEI,HEI-A,HESM,HIG,HII,HIMS,HL,HLI,HLN,HLNE,HLT,HMC,HMY,HON,HOOD,HPE,HPQ,HQY,HRL,HSBC,HSIC,HST,HSY,HTHT,HUBB,HUBS,HUM,HWM,HYG,IAG,IAGG,IAU,IAUM,IBB,IBIT,IBKR,IBM,IBN,IBP,ICE,ICL,ICLR,ICSH,IDA,IDCC,IDEV,IDV,IDXX,IEF,IEFA,IEI,IEMG,IESC,IEUR,IEX,IFF,IGF,IGIB,IGM,IGSB,IGV,IHG,IHI,IJH,IJJ,IJK,IJR,IJS,IJT,ILMN,IMO,INCY,INDA,INFY,ING,INGR,INSM,INTC,INTU,INVH,IONQ,IONS,IOO,IOT,IP,IQLT,IQV,IR,IREN,IRM,ISRG,ISTB,IT,ITA,ITOT,ITT,ITUB,ITW,IUSB,IUSG,IUSV,IVE,IVV,IVW,IVZ,IWB,IWD,IWF,IWM,IWN,IWO,IWP,IWR,IWS,IWV,IWY,IX,IXJ,IXN,IXUS,IYF,IYR,IYW,J,JAAA,JAVA,JAZZ,JBHT,JBL,JBND,JBS,JBTM,JCI,JCPB,JD,JEF,JEPI,JEPQ,JGLO,JGRO,JHG,JHMM,JHX,JIRE,JKHY,JLL,JMBS,JMST,JMTG,JMUB,JNJ,JNK,JOBY,JPIE,JPM,JPST,JQUA,JXN,KB,KBWB,KDP,KEP,KEY,KEYS,KGC,KHC,KIM,KKR,KLAC,KLAR,KMB,KMI,KNSL,KNX,KO,KR,KRE,KRMN,KRYS,KSPI,KT,KTOS,KVUE,KVYO,KWEB,KYMR,L,LAD,LAMR,LBRDA,LBRDK,LDOS,LECO,LEN,LEVI,LFUS,LH,LHX,LI,LII,LIN,LINE,LITE,LKQ,LLY,LLYVA,LLYVK,LMBS,LMT,LNC,LNG,LNT,LOGI,LOW,LPLA,LQD,LRCX,LSCC,LTM,LULU,LUMN,LUV,LVS,LW,LYB,LYFT,LYG,LYV,MA,MAA,MAGS,MANH,MAR,MAS,MASI,MBB,MBLY,MCD,MCHI,MCHP,MCK,MCO,MDB,MDGL,MDLZ,MDT,MDY,MEDP,MELI,MET,META,MFC,MFG,MGA,MGC,MGK,MGM,MGV,MHK,MICC,MIDD,MINT,MKC,MKL,MKSI,MKTX,MLI,MLM,MMM,MMYT,MNDY,MNST,MO,MOAT,MOD,MOG-A,MOH,MORN,MOS,MP,MPC,MPLX,MPWR,MRK,MRNA,MRVL,MS,MSCI,MSFT,MSI,MSTR,MT,MTB,MTCH,MTD,MTSI,MTUM,MTZ,MU,MUB,MUFG,MUSA,NBIS,NBIX,NCLH,NDAQ,NDSN,NEE,NEM,NET,NEU,NFG,NFLX,NGG,NI,NICE,NIO,NKE,NLY,NMR,NNN,NOBL,NOC,NOK,NOW,NRG,NSC,NTAP,NTES,NTNX,NTR,NTRA,NTRS,NTSK,NU,NUE,NUVL,NVDA,NVDL,NVMI,NVO,NVR,NVS,NVT,NWG,NWS,NWSA,NXPI,NXT,NYT,O,OBDC,OC,ODFL,OEF,OGE,OHI,OKE,OKLO,OKTA,OLLI,OMC,OMF,OMFL,ON,ONB,ONC,ONEQ,ONON,ONTO,OPEN,OR,ORA,ORCL,ORI,ORLY,OSK,OTEX,OTF,OTIS,OVV,OWL,OXY,PAA,PAAA,PAAS,PAC,PAG,PAGP,PANW,PATH,PAVE,PAYC,PAYX,PB,PBA,PBR,PBR-A,PBUS,PCAR,PCG,PCOR,PCTY,PDBC,PDD,PDI,PEG,PEGA,PEN,PEP,PFE,PFF,PFG,PFGC,PFSI,PG,PGR,PH,PHG,PHM,PHYS,PINS,PJT,PKG,PKX,PLD,PLNT,PLTR,PM,PNC,PNFP,PNR,PNW,PODD,POOL,PPA,PPC,PPG,PPL,PR,PRAX,PRF,PRI,PRIM,PRU,PSA,PSKY,PSLV,PSN,PSNY,PSO,PSTG,PSX,PTC,PUK,PULS,PVAL,PWR,PYLD,PYPL,Q,QBTS,QCOM,QGEN,QLD,QQQ,QQQI,QQQM,QRVO,QS,QSR,QUAL,QXO,QYLD,R,RACE,RBA,RBC,RBLX,RBRK,RCI,RCL,RDDT,RDVY,RDY,RECS,REET,REG,REGN,RELX,REXR,RF,RGA,RGC,RGEN,RGLD,RGTI,RIO,RIVN,RJF,RKLB,RKT,RL,RMBS,RMD,RNA,RNR,ROIV,ROK,ROKU,ROL,ROP,ROST,RPM,RPRX,RRC,RRR,RRX,RS,RSG,RSP,RSPT,RTO,RTX,RVMD,RVTY,RWL,RY,RYAAY,RYAN,RYTM,SAIA,SAIL,SAN,SANM,SAP,SARO,SATS,SBAC,SBIL,SBS,SBSW,SBUX,SCCO,SCHA,SCHB,SCHC,SCHD,SCHE,SCHF,SCHG,SCHH,SCHI,SCHK,SCHM,SCHO,SCHP,SCHR,SCHV,SCHW,SCHX,SCHZ,SCI,SCZ,SDVY,SDY,SE,SEIC,SF,SFD,SFM,SGI,SGOL,SGOV,SHEL,SHG,SHLD,SHOP,SHV,SHW,SHY,SHYG,SIL,SIRI,SITM,SIVR,SJM,SJNK,SKM,SLB,SLF,SLV,SLYV,SMBS,SMCI,SMFG,SMH,SMMT,SMTC,SN,SNA,SNAP,SNDK,SNN,SNOW,SNPS,SNX,SNY,SO,SOFI,SOLS,SOLV,SONY,SOXL,SOXX,SPAB,SPDW,SPEM,SPG,SPGI,SPHQ,SPHY,SPIB,SPLV,SPMB,SPMD,SPMO,SPOT,SPSB,SPSM,SPTI,SPTL,SPTM,SPTS,SPXC,SPXL,SPY,SPYD,SPYG,SPYI,SPYM,SPYV,SQM,SRAD,SRE,SRLN,SSB,SSD,SSNC,SSO,STAG,STE,STEP,STIP,STLA,STLD,STM,STN,STRC,STRL,STT,STWD,STX,STZ,SU,SUB,SUI,SUN,SUZ,SW,SWK,SWKS,SYF,SYK,SYM,SYY,T,TAK,TAP,TBIL,TCAF,TCOM,TD,TDG,TDY,TEAM,TECH,TECK,TECL,TEL,TEM,TER,TEVA,TFC,TFII,TFLO,TFPM,TGT,THC,THG,THRO,TIGO,TIMB,TIP,TJX,TKO,TLH,TLK,TLN,TLT,TM,TME,TMF,TMO,TMUS,TOL,TOST,TOTL,TPG,TPL,TPR,TQQQ,TRGP,TRI,TRMB,TROW,TRP,TRU,TRV,TS,TSCO,TSEM,TSLA,TSLL,TSM,TSN,TT,TTAN,TTC,TTD,TTE,TTEK,TTMI,TTWO,TU,TW,TWLO,TX,TXN,TXRH,TXT,TYL,U,UAL,UBER,UBS,UDR,UEC,UGI,UHAL,UHAL-B,UHS,UI,UL,ULS,ULTA,UMBF,UMC,UNH,UNM,UNP,UPRO,UPS,URA,URBN,URI,URTH,USB,USFD,USFR,USHY,USIG,USMV,USO,UTHR,UWMC,V,VALE,VB,VBIL,VBK,VBR,VCIT,VCLT,VCR,VCRB,VCSH,VDC,VDE,VEA,VEEV,VEU,VFC,VFH,VFLO,VFS,VG,VGIT,VGK,VGLT,VGSH,VGT,VHT,VICI,VIG,VIGI,VIK,VIPS,VIS,VIV,VLO,VLTO,VLUE,VLY,VMBS,VMC,VMI,VNO,VNOM,VNQ,VO,VOD,VOE,VONE,VONG,VONV,VOO,VOOG,VOOV,VOT,VOX,VOYA,VPL,VPU,VRSK,VRSN,VRT,VRTX,VSGX,VSS,VST,VT,VTEB,VTI,VTIP,VTR,VTRS,VTV,VTWO,VUG,VUSB,VV,VWO,VWOB,VXF,VXUS,VYM,VYMI,VZ,W,WAB,WAL,WAT,WAY,WBD,WBS,WCC,WCN,WDAY,WDC,WDS,WEC,WELL,WES,WF,WFC,WING,WIT,WLK,WM,WMB,WMG,WMS,WMT,WPC,WPM,WRB,WSM,WSO,WST,WTFC,WTRG,WTS,WTW,WWD,WY,WYNN,XAR,XBI,XEL,XLB,XLC,XLE,XLF,XLG,XLI,XLK,XLP,XLRE,XLU,XLV,XLY,XMHQ,XMMO,XOM,XP,XPEV,XPO,XYL,XYZ,YMM,YPF,YUM,YUMC,Z,ZBH,ZBRA,ZG,ZION,ZM,ZS,ZTO,ZTS,ZWS
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1962-01-02,0.0,1.47105,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.887650,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.190931,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.043295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.462332,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.282569,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.305175,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.057055,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.386574,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.238809,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.168170,0.0,0.0,0.0,0.0,0.617244,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.965136,0.0,0.0,0.038465,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.44474,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.817926,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.059996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.044744,0.031692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.830902,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.552087,0.0,0.0,0.0,0.002384,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.063742,0.0,0.0,0.0,0.0,0.0,0.613480,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.244460,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.088155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

--- TAIL (Last 3 Rows) ---

Ticker,A,AA,AAL,AAON,AAPL,ABBV,ABEV,ABNB,ABT,ABVX,ACGL,ACI,ACM,ACN,ACWI,ACWX,ADBE,ADC,ADI,ADM,ADP,ADSK,ADT,AEE,AEG,AEIS,AEM,AEP,AER,AES,AFG,AFL,AFRM,AG,AGCO,AGG,AGI,AGNC,AHR,AIG,AIQ,AIRR,AIT,AIZ,AJG,AKAM,AKRE,ALAB,ALB,ALC,ALGN,ALL,ALLE,ALLY,ALNY,ALSN,ALV,AM,AMAT,AMCR,AMD,AME,AMG,AMGN,AMH,AMKR,AMLP,AMP,AMRZ,AMT,AMTM,AMX,AMZN,AN,ANET,AON,AOS,APA,APD,APG,APH,APLD,APO,APP,APPF,APTV,AR,ARCC,ARE,ARES,ARGX,ARKK,ARM,ARMK,ARWR,AS,ASML,ASND,ASR,ASTS,ASX,ATI,ATO,ATR,AU,AUR,AVAV,AVB,AVDE,AVDV,AVEM,AVGO,AVLV,AVTR,AVUS,AVUV,AVY,AWI,AWK,AXIA,AXON,AXP,AXS,AXSM,AXTA,AYI,AZN,AZO,B,BA,BABA,BAC,BAH,BAI,BALL,BAM,BAP,BAX,BBAX,BBCA,BBD,BBEU,BBIN,BBIO,BBJP,BBUS,BBVA,BBY,BCE,BCH,BCS,BDX,BE,BEKE,BEN,BEP,BEPC,BETA,BF-A,BF-B,BG,BHP,BIDU,BIIB,BIL,BILI,BINC,BIO,BIP,BIRK,BIV,BJ,BK,BKLC,BKLN,BKNG,BKR,BLD,BLDR,BLK,BLSH,BLV,BMNR,BMO,BMRN,BMY,BN,BND,BNDX,BNO,BNS,BNT,BNTX,BOKF,BOND,BOXX,BP,BPOP,BR,BRK-A,BRK-B,BRKR,BRO,BROS,BRX,BSAC,BSBR,BSCQ,BSCR,BSOL,BSV,BSX,BSY,BTC,BTI,BUD,BUFR,BURL,BVN,BWA,BWXT,BX,BXP,BYD,BZ,C,CACI,CAE,CAG,CAH,CAI,CARR,CART,CASY,CAT,CB,CBOE,CBRE,CBSH,CCEP,CCI,CCJ,CCK,CCL,CDE,CDNS,CDP,CDW,CEF,CEG,CELH,CF,CFG,CFR,CG,CGBL,CGCP,CGDV,CGGO,CGGR,CGMU,CGUS,CGXU,CHD,CHDN,CHKP,CHRW,CHT,CHTR,CHWY,CHYM,CI,CIB,CIBR,CIEN,CIFR,CIGI,CINF,CL,CLF,CLH,CLS,CLX,CM,CMC,CMCSA,CME,CMG,CMI,CMS,CNA,CNC,CNH,CNI,CNM,CNP,CNQ,COF,COHR,COIN,COKE,COLB,COO,COP,COPX,COR,CORT,COST,COWZ,CP,CPAY,CPB,CPNG,CPRT,CPT,CQP,CR,CRBG,CRCL,CRDO,CRH,CRK,CRL,CRM,CRS,CRWD,CRWV,CSCO,CSGP,CSL,CSX,CTAS,CTRE,CTSH,CTVA,CUBE,CVE,CVNA,CVS,CVX,CW,CWB,CWEN,CWEN-A,CX,CYTK,D,DAL,DASH,DB,DBEF,DBX,DCI,DD,DDOG,DDS,DE,DECK,DELL,DEO,DFAC,DFAE,DFAI,DFAS,DFAT,DFAU,DFAX,DFCF,DFEM,DFIC,DFIS,DFIV,DFLV,DFSD,DFSV,DFUS,DFUV,DG,DGRO,DGRW,DGX,DHI,DHR,DIA,DIHP,DINO,DIS,DIVO,DKNG,DKS,DLN,DLR,DLTR,DOC,DOCS,DOCU,DON,DOV,DOW,DOX,DPZ,DRI,DRS,DSGX,DSI,DT,DTE,DTM,DUHP,DUK,DUOL,DVA,DVN,DVY,DXCM,DXJ,DY,DYNF,E,EA,EAGG,EBAY,EC,ECL,ED,EDU,EDV,EEM,EFA,EFAV,EFG,EFV,EFX,EG,EGO,EGP,EHC,EIX,EL,ELAN,ELS,ELV,EMA,EMB,EMBJ,EME,EMLC,EMN,EMR,EMXC,ENB,ENSG,ENTG,EOG,EPAM,EPD,EQH,EQIX,EQNR,EQR,EQT,EQX,ERIC,ERIE,ES,ESAB,ESGD,ESGE,ESGU,ESGV,ESLT,ESS,ESTC,ET,ETHA,ETHB,ETN,ETR,EUFN,EVR,EVRG,EVTR,EW,EWBC,EWJ,EWT,EWY,EWZ,EXC,EXE,EXEL,EXLS,EXP,EXPD,EXPE,EXR,EZU,F,FAF,FANG,FAST,FBCG,FBND,FBTC,FCFS,FCNCA,FCX,FDL,FDN,FDS,FDVV,FDX,FE,FELC,FELG,FENI,FER,FERG,FEZ,FFIV,FHN,FICO,FIG,FIGR,FIS,FISV,FITB,FIVE,FIX,FLEX,FLOT,FLR,FLS,FLUT,FMDE,FMS,FMX,FN,FND,FNDA,FNDE,FNDF,FNDX,FNF,FNV,FOX,FOXA,FPE,FR,FRHC,FRMI,FROG,FRT,FSEC,FSLR,FSS,FSV,FTAI,FTCS,FTEC,FTI,FTNT,FTS,FTSM,FTV,FUTU,FVD,FWONA,FWONK,FXI,G,GAP,GBIL,GBTC,GD,GDDY,GDS,GDX,GDXJ,GE,GEHC,GEN,GEV,GFI,GFL,GFS,GGAL,GGG,GH,GIB,GIL,GILD,GIS,GL,GLBE,GLD,GLDM,GLPI,GLW,GM,GMAB,GME,GMED,GNRC,GOOG,GOOGL,GOVT,GPC,GPN,GRAB,GRID,GRMN,GS,GSAT,GSIE,GSK,GSLC,GTLB,GTLS,GUNR,GWRE,GWW,H,HAL,HALO,HAS,HBAN,HBM,HCA,HD,HDB,HDV,HEFA,HEI,HEI-A,HESM,HIG,HII,HIMS,HL,HLI,HLN,HLNE,HLT,HMC,HMY,HON,HOOD,HPE,HPQ,HQY,HRL,HSBC,HSIC,HST,HSY,HTHT,HUBB,HUBS,HUM,HWM,HYG,IAG,IAGG,IAU,IAUM,IBB,IBIT,IBKR,IBM,IBN,IBP,ICE,ICL,ICLR,ICSH,IDA,IDCC,IDEV,IDV,IDXX,IEF,IEFA,IEI,IEMG,IESC,IEUR,IEX,IFF,IGF,IGIB,IGM,IGSB,IGV,IHG,IHI,IJH,IJJ,IJK,IJR,IJS,IJT,ILMN,IMO,INCY,INDA,INFY,ING,INGR,INSM,INTC,INTU,INVH,IONQ,IONS,IOO,IOT,IP,IQLT,IQV,IR,IREN,IRM,ISRG,ISTB,IT,ITA,ITOT,ITT,ITUB,ITW,IUSB,IUSG,IUSV,IVE,IVV,IVW,IVZ,IWB,IWD,IWF,IWM,IWN,IWO,IWP,IWR,IWS,IWV,IWY,IX,IXJ,IXN,IXUS,IYF,IYR,IYW,J,JAAA,JAVA,JAZZ,JBHT,JBL,JBND,JBS,JBTM,JCI,JCPB,JD,JEF,JEPI,JEPQ,JGLO,JGRO,JHG,JHMM,JHX,JIRE,JKHY,JLL,JMBS,JMST,JMTG,JMUB,JNJ,JNK,JOBY,JPIE,JPM,JPST,JQUA,JXN,KB,KBWB,KDP,KEP,KEY,KEYS,KGC,KHC,KIM,KKR,KLAC,KLAR,KMB,KMI,KNSL,KNX,KO,KR,KRE,KRMN,KRYS,KSPI,KT,KTOS,KVUE,KVYO,KWEB,KYMR,L,LAD,LAMR,LBRDA,LBRDK,LDOS,LECO,LEN,LEVI,LFUS,LH,LHX,LI,LII,LIN,LINE,LITE,LKQ,LLY,LLYVA,LLYVK,LMBS,LMT,LNC,LNG,LNT,LOGI,LOW,LPLA,LQD,LRCX,LSCC,LTM,LULU,LUMN,LUV,LVS,LW,LYB,LYFT,LYG,LYV,MA,MAA,MAGS,MANH,MAR,MAS,MASI,MBB,MBLY,MCD,MCHI,MCHP,MCK,MCO,MDB,MDGL,MDLZ,MDT,MDY,MEDP,MELI,MET,META,MFC,MFG,MGA,MGC,MGK,MGM,MGV,MHK,MICC,MIDD,MINT,MKC,MKL,MKSI,MKTX,MLI,MLM,MMM,MMYT,MNDY,MNST,MO,MOAT,MOD,MOG-A,MOH,MORN,MOS,MP,MPC,MPLX,MPWR,MRK,MRNA,MRVL,MS,MSCI,MSFT,MSI,MSTR,MT,MTB,MTCH,MTD,MTSI,MTUM,MTZ,MU,MUB,MUFG,MUSA,NBIS,NBIX,NCLH,NDAQ,NDSN,NEE,NEM,NET,NEU,NFG,NFLX,NGG,NI,NICE,NIO,NKE,NLY,NMR,NNN,NOBL,NOC,NOK,NOW,NRG,NSC,NTAP,NTES,NTNX,NTR,NTRA,NTRS,NTSK,NU,NUE,NUVL,NVDA,NVDL,NVMI,NVO,NVR,NVS,NVT,NWG,NWS,NWSA,NXPI,NXT,NYT,O,OBDC,OC,ODFL,OEF,OGE,OHI,OKE,OKLO,OKTA,OLLI,OMC,OMF,OMFL,ON,ONB,ONC,ONEQ,ONON,ONTO,OPEN,OR,ORA,ORCL,ORI,ORLY,OSK,OTEX,OTF,OTIS,OVV,OWL,OXY,PAA,PAAA,PAAS,PAC,PAG,PAGP,PANW,PATH,PAVE,PAYC,PAYX,PB,PBA,PBR,PBR-A,PBUS,PCAR,PCG,PCOR,PCTY,PDBC,PDD,PDI,PEG,PEGA,PEN,PEP,PFE,PFF,PFG,PFGC,PFSI,PG,PGR,PH,PHG,PHM,PHYS,PINS,PJT,PKG,PKX,PLD,PLNT,PLTR,PM,PNC,PNFP,PNR,PNW,PODD,POOL,PPA,PPC,PPG,PPL,PR,PRAX,PRF,PRI,PRIM,PRU,PSA,PSKY,PSLV,PSN,PSNY,PSO,PSTG,PSX,PTC,PUK,PULS,PVAL,PWR,PYLD,PYPL,Q,QBTS,QCOM,QGEN,QLD,QQQ,QQQI,QQQM,QRVO,QS,QSR,QUAL,QXO,QYLD,R,RACE,RBA,RBC,RBLX,RBRK,RCI,RCL,RDDT,RDVY,RDY,RECS,REET,REG,REGN,RELX,REXR,RF,RGA,RGC,RGEN,RGLD,RGTI,RIO,RIVN,RJF,RKLB,RKT,RL,RMBS,RMD,RNA,RNR,ROIV,ROK,ROKU,ROL,ROP,ROST,RPM,RPRX,RRC,RRR,RRX,RS,RSG,RSP,RSPT,RTO,RTX,RVMD,RVTY,RWL,RY,RYAAY,RYAN,RYTM,SAIA,SAIL,SAN,SANM,SAP,SARO,SATS,SBAC,SBIL,SBS,SBSW,SBUX,SCCO,SCHA,SCHB,SCHC,SCHD,SCHE,SCHF,SCHG,SCHH,SCHI,SCHK,SCHM,SCHO,SCHP,SCHR,SCHV,SCHW,SCHX,SCHZ,SCI,SCZ,SDVY,SDY,SE,SEIC,SF,SFD,SFM,SGI,SGOL,SGOV,SHEL,SHG,SHLD,SHOP,SHV,SHW,SHY,SHYG,SIL,SIRI,SITM,SIVR,SJM,SJNK,SKM,SLB,SLF,SLV,SLYV,SMBS,SMCI,SMFG,SMH,SMMT,SMTC,SN,SNA,SNAP,SNDK,SNN,SNOW,SNPS,SNX,SNY,SO,SOFI,SOLS,SOLV,SONY,SOXL,SOXX,SPAB,SPDW,SPEM,SPG,SPGI,SPHQ,SPHY,SPIB,SPLV,SPMB,SPMD,SPMO,SPOT,SPSB,SPSM,SPTI,SPTL,SPTM,SPTS,SPXC,SPXL,SPY,SPYD,SPYG,SPYI,SPYM,SPYV,SQM,SRAD,SRE,SRLN,SSB,SSD,SSNC,SSO,STAG,STE,STEP,STIP,STLA,STLD,STM,STN,STRC,STRL,STT,STWD,STX,STZ,SU,SUB,SUI,SUN,SUZ,SW,SWK,SWKS,SYF,SYK,SYM,SYY,T,TAK,TAP,TBIL,TCAF,TCOM,TD,TDG,TDY,TEAM,TECH,TECK,TECL,TEL,TEM,TER,TEVA,TFC,TFII,TFLO,TFPM,TGT,THC,THG,THRO,TIGO,TIMB,TIP,TJX,TKO,TLH,TLK,TLN,TLT,TM,TME,TMF,TMO,TMUS,TOL,TOST,TOTL,TPG,TPL,TPR,TQQQ,TRGP,TRI,TRMB,TROW,TRP,TRU,TRV,TS,TSCO,TSEM,TSLA,TSLL,TSM,TSN,TT,TTAN,TTC,TTD,TTE,TTEK,TTMI,TTWO,TU,TW,TWLO,TX,TXN,TXRH,TXT,TYL,U,UAL,UBER,UBS,UDR,UEC,UGI,UHAL,UHAL-B,UHS,UI,UL,ULS,ULTA,UMBF,UMC,UNH,UNM,UNP,UPRO,UPS,URA,URBN,URI,URTH,USB,USFD,USFR,USHY,USIG,USMV,USO,UTHR,UWMC,V,VALE,VB,VBIL,VBK,VBR,VCIT,VCLT,VCR,VCRB,VCSH,VDC,VDE,VEA,VEEV,VEU,VFC,VFH,VFLO,VFS,VG,VGIT,VGK,VGLT,VGSH,VGT,VHT,VICI,VIG,VIGI,VIK,VIPS,VIS,VIV,VLO,VLTO,VLUE,VLY,VMBS,VMC,VMI,VNO,VNOM,VNQ,VO,VOD,VOE,VONE,VONG,VONV,VOO,VOOG,VOOV,VOT,VOX,VOYA,VPL,VPU,VRSK,VRSN,VRT,VRTX,VSGX,VSS,VST,VT,VTEB,VTI,VTIP,VTR,VTRS,VTV,VTWO,VUG,VUSB,VV,VWO,VWOB,VXF,VXUS,VYM,VYMI,VZ,W,WAB,WAL,WAT,WAY,WBD,WBS,WCC,WCN,WDAY,WDC,WDS,WEC,WELL,WES,WF,WFC,WING,WIT,WLK,WM,WMB,WMG,WMS,WMT,WPC,WPM,WRB,WSM,WSO,WST,WTFC,WTRG,WTS,WTW,WWD,WY,WYNN,XAR,XBI,XEL,XLB,XLC,XLE,XLF,XLG,XLI,XLK,XLP,XLRE,XLU,XLV,XLY,XMHQ,XMMO,XOM,XP,XPEV,XPO,XYL,XYZ,YMM,YPF,YUM,YUMC,Z,ZBH,ZBRA,ZG,ZION,ZM,ZS,ZTO,ZTS,ZWS
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-06-10,131.62,65.55,13.42,121.12,291.58,224.95,3.11,129.10,89.17,98.03,91.31,15.28,68.58,170.50,152.24,73.63,233.38,75.53,392.67,81.28,229.36,221.28,6.645,108.77,8.32,308.17,152.48,128.53,135.07,14.63,132.42,117.11,62.81,15.71,108.71,98.31,32.97,10.18,46.82,74.94,61.36,122.77,314.08,257.34,220.14,129.97,55.45,330.86,146.845,66.11,170.50,223.34,129.35,41.88,291.22,113.82,124.13,21.49,497.01,38.17,452.40,221.78,335.34,337.73,33.22,69.61,52.77,450.62,50.51,190.68,22.00,25.43,238.00,193.21,151.76,336.33,57.22,38.00,276.51,41.36,149.22,38.92,131.14,492.98,168.32,65.20,35.64,19.04,52.31,128.31,862.18,73.01,307.43,53.30,70.73,33.76,1734.19,209.79,276.33,87.32,34.30,183.37,169.27,114.67,78.47,6.05,172.93,186.59,86.94,102.67,91.14,372.10,89.12,9.65,123.45,120.86,156.07,152.19,126.46,9.74,447.59,313.34,99.88,246.34,32.10,280.39,178.96,3110.05,37.19,209.00,114.33,54.54,77.29,45.58,54.72,45.70,351.66,20.31,59.35,99.44,3.30,76.06,76.40,67.405,72.63,130.77,22.02,75.64,24.71,38.65,23.64,147.79,234.23,16.00,31.14,35.27,37.49,15.72,26.85,26.53,128.21,82.95,117.48,194.24,91.47,18.08,52.00,291.01,38.99,43.95,76.10,92.49,139.75,139.02,20.42,160.64,63.02,393.22,74.62,1010.68,26.10,67.94,15.64,164.39,56.17,55.60,44.61,72.91,47.90,51.46,81.56,44.52,86.15,131.60,91.36,116.99,42.95,156.15,145.454,727000.0,483.68,54.92,60.18,60.28,31.86,31.28,5.28,19.555,19.645,8.58,77.66,48.34,32.45,27.38,61.12,81.26,35.88,327.01,30.68,71.29,183.00,118.48,65.48,86.82,13.24,133.38,521.14,25.38,13.34,216.30,17.16,67.97,41.210,915.60,856.16,329.552,301.08,134.06,54.56,97.51,93.38,95.03,95.45,25.99,15.41,385.13,34.19,129.30,41.44,242.30,28.37,109.26,64.96,144.50,44.11,36.69,22.23,47.27,38.86,44.58,27.37,42.66,33.15,98.19,88.66,125.69,185.00,45.59,137.79,19.98,16.44,295.81,75.87,83.25,434.65,21.02,98.85,166.43,89.95,12.41,288.64,362.92,99.32,110.14,73.57,23.97,263.80,30.42,630.52,73.46,44.80,65.34,10.18,119.18,49.44,42.74,45.52,177.63,354.77,153.97,191.08,30.32,67.69,119.92,77.45,281.24,78.12,983.37,63.02,89.60,348.99,22.88,15.12,31.36,115.31,66.14,195.65,27.18,78.93,237.68,99.98,13.37,186.29,170.48,523.05,647.74,95.61,118.80,34.23,327.82,46.41,180.40,37.73,51.81,74.46,41.68,28.37,67.25,98.02,189.80,719.02,103.36,37.40,40.43,11.80,67.07,66.77,76.47,151.00,30.99,52.06,27.65,83.56,45.06,227.63,582.55,560.05,111.18,369.83,79.78,42.94,38.27,40.55,77.85,67.69,50.095,36.09,42.06,38.79,36.93,35.130,54.29,38.92,47.77,37.95,79.17,53.40,109.96,74.74,94.76,203.78,146.71,183.63,500.25,33.403,70.76,98.61,45.57,28.79,213.77,95.11,180.78,110.32,20.47,20.24,45.13,55.27,213.76,34.24,56.97,314.77,203.64,46.11,73.91,137.78,40.58,146.07,140.80,40.20,125.04,121.920,198.54,46.60,156.06,74.77,166.70,445.89,64.92,54.24,203.20,47.07,106.41,16.21,256.99,107.60,46.11,63.28,64.66,101.57,89.47,118.72,76.59,166.06,334.548,27.94,200.87,103.35,71.50,85.39,22.87,64.32,404.56,52.20,95.35,53.82,776.72,25.19,71.34,137.11,94.18,56.44,151.65,128.88,140.28,93.04,37.87,41.91,1038.33,37.49,67.61,52.61,9.73,11.60,231.98,69.18,82.92,100.27,51.99,158.75,127.91,818.97,284.64,60.78,19.04,12.28,20.95,375.46,110.48,37.09,340.78,82.83,50.50,85.98,128.09,89.29,98.00,178.45,33.78,45.61,88.56,52.58,29.02,213.19,164.71,218.94,149.60,67.44,14.30,66.13,196.55,46.03,59.20,45.31,53.88,211.73,2112.87,62.08,50.58,262.84,249.08,60.44,319.25,46.43,40.57,42.25,38.88,64.30,224.56,66.65,390.77,24.5518,1220.15,19.79,28.07,38.53,53.28,52.65,195.85,1719.48,139.49,50.95,46.84,72.86,112.94,38.85,22.28,123.65,580.25,49.34,35.97,39.79,52.11,30.57,47.60,208.02,61.03,68.00,17.89,62.41,139.010,6.89,80.36,123.62,43.71,249.27,110.65,142.93,225.76,93.61,268.43,69.95,138.88,56.48,59.810,60.06,92.93,47.76,81.70,88.61,34.75,32.19,21.10,100.00,48.02,341.07,80.28,33.48,73.81,94.54,318.71,63.76,24.62,867.09,33.53,36.59,74.82,49.62,73.47,130.70,66.85,57.04,121.48,33.82,162.52,32.73,374.58,80.77,47.5807,168.17,79.40,24.49,22.42,80.86,239.11,353.32,356.38,22.61,98.43,62.2313,3.27,181.49,231.72,1001.29,80.31,44.72,51.17,138.14,28.51,206.45,51.54,116.59,1317.63,190.63,39.73,70.50,82.29,16.84,24.68,373.34,318.92,23.20,27.68,44.66,320.88,237.45,38.78,129.26,289.13,27.78,14.05,135.96,9.08,78.09,338.22,26.11,14.42,205.88,86.36,45.49,24.69,89.72,24.29,86.16,78.85,23.95,176.61,44.54,467.59,192.79,364.46,249.49,79.47,14.84,50.08,76.79,40.68,165.93,35.08,85.42,272.36,26.77,195.65,140.34,5.50,144.59,50.47,141.65,253.91,87.56,43.50,556.94,93.69,94.87,116.85,78.62,678.20,73.98,214.50,74.23,66.05,52.72,153.02,52.19,91.58,161.47,49.72,73.65,142.70,110.96,138.90,131.65,162.62,162.47,120.26,105.39,47.30,11.76,28.71,102.54,91.88,107.04,284.22,29.71,56.63,73.32,135.78,32.64,31.85,48.36,182.17,70.48,51.52,123.36,412.02,48.07,154.91,224.87,158.92,184.24,7.62,250.17,45.82,180.04,108.91,224.68,728.92,131.55,27.46,396.80,235.24,119.69,282.05,210.92,365.21,136.91,105.39,158.55,412.58,280.79,38.15,95.29,132.89,92.82,125.06,103.52,235.40,121.76,50.58,76.69,229.63,280.75,352.36,53.08,12.03,119.00,139.36,46.55,28.45,57.90,55.29,57.99,68.82,93.06,51.72,72.14,22.01,78.98,127.59,298.22,44.85,50.93,50.32,50.36,238.49,95.73,8.86,45.87,309.14,50.45,69.17,105.74,100.76,89.35,31.70,11.90,21.98,324.00,23.66,24.05,25.38,95.02,213.564,15.78,101.58,31.84,313.57,79.25,83.59,64.46,71.64,45.87,312.410,78.575,18.43,54.82,18.05,14.51,26.44,78.230,108.05,304.83,150.74,32.09,32.24,121.69,253.22,89.85,22.95,439.44,268.63,303.00,13.69,504.80,509.16,44.33,853.26,25.47,1136.37,96.15,99.53,49.75,525.02,36.21,241.81,73.00,109.13,216.19,289.18,108.16,321.80,132.37,47.42,118.93,8.26,41.22,50.81,44.13,65.15,13.39,5.16,167.50,489.08,139.78,64.22,145.15,386.23,70.87,179.95,93.91,9.14,282.52,54.11,87.91,790.44,450.69,348.28,471.32,64.18,80.25,671.84,465.73,1588.29,86.13,570.98,39.25,9.35,64.02,265.88,85.13,46.91,157.83,101.75,17.76,153.75,100.55,49.69,1820.94,316.07,116.11,132.44,552.87,156.85,39.06,81.70,91.21,73.13,101.29,258.17,382.13,197.89,186.06,19.82,53.45,263.28,56.39,1473.04,119.09,45.99,252.59,206.66,608.52,397.36,411.64,115.35,63.81,223.93,34.35,1133.03,354.40,304.92,335.58,891.88,106.82,19.67,612.16,211.69,160.86,17.92,86.4101,278.57,85.12,92.77,219.67,823.94,77.13,82.00,80.38,46.63,88.36,5.18,43.96,21.41,8.52,46.30,54.92,542.14,13.40,106.06,120.65,308.93,160.66,125.52,49.66,65.03,216.50,166.13,8.47,11.62,250.49,123.35,200.42,91.22,508.35,42.81,6305.04,148.12,156.79,15.56,30.90,26.97,285.56,111.95,73.00,62.11,11.12,115.08,235.95,357.76,47.64,45.86,90.57,54.02,114.92,78.30,73.98,54.52,66.66,110.17,24.37,263.61,99.18,38.00,269.33,4.48,31.47,136.69,201.26,38.40,90.46,126.95,21.68,11.06,69.66,57.94,9.47,57.10,22.73,51.37,44.17,221.74,178.18,24.63,263.22,10.75,55.30,136.72,101.10,71.11,48.84,18.11,16.09,72.640,113.99,16.72,43.54,111.64,17.43,81.82,16.299,78.59,32.91,319.34,144.32,25.60,30.77,109.21,100.74,80.08,149.05,204.20,875.60,25.67,118.49,30.78,21.77,157.25,216.64,58.73,145.77,50.60,130.21,182.95,232.64,93.11,71.40,103.10,150.71,189.89,167.62,29.50,112.97,35.58,19.73,240.66,52.69,276.45,93.88,105.17,323.87,10.31,20.05,56.47,20.24,15.34,66.53,181.72,135.08,25.01,49.60,50.03,650.92,26.25,40.70,139.74,23.25,191.20,37.02,86.51,693.69,54.18,285.92,95.00,7.00,73.20,212.33,15.06,17.64,270.25,346.56,105.64,576.74,41.50,71.32,38.60,268.73,172.21,75.66,13.30,42.46,27.53,79.3505,601.65,33.98,34.58,28.58,205.35,20.45,130.76,197.07,19.445,99.06,14.76,150.59,105.05,12.54,376.43,138.12,193.57,11.67,295.75,28.41,440.07,116.94,47.77,334.10,231.92,104.28,54.52,39.037,62.08,200.45,394.29,212.59,206.53,59.75,30.12,177.41,144.19,101.29,126.36,197.61,55.75,34.67,85.71,463.70,14.71,11.92,231.32,170.30,24.77,115.24,207.33,100.19,5.36,9.08,98.76,167.76,33.30,28.03,47.90,32.26,35.07,26.68,32.87,23.93,22.47,34.97,34.60,24.08,26.44,24.51,33.44,89.27,28.58,22.98,73.84,82.69,41.26,150.18,82.44,88.80,70.46,26.83,86.82,68.45,38.88,100.48,86.05,64.27,62.36,108.20,110.15,303.91,81.94,42.16,74.26,27.59,664.23,60.61,117.05,24.88,37.81,55.51,74.92,57.66,105.12,25.260,29.27,22.99,570.91,13.05,154.28,128.22,378.45,5.38,1643.23,30.90,239.90,460.54,267.81,43.57,94.02,15.87,77.69,80.94,20.76,180.65,541.51,25.34,49.09,50.47,212.82,426.38,84.20,23.28,33.27,73.89,22.15,64.57,143.68,503.1,29.93,54.04,28.21,25.78,88.10,28.95,223.63,249.67,725.43,48.34,113.92,52.00,85.165,60.21,74.24,16.73,91.03,40.23,96.67,186.22,68.25,63.67,37.99,208.10,42.35,102.29,6.57,268.34,70.74,71.34,95.81,770.25,161.80,17.05,815.99,142.27,62.09,106.37,126.64,65.80,8.02,38.95,77.47,70.29,69.56,308.84,41.24,78.54,23.21,15.68,40.90,49.910,39.47,47.97,114.50,1212.36,601.35,91.54,52.50,59.91,188.60,202.00,49.48,347.59,33.58,49.76,153.57,50.54,26.85,127.98,164.77,196.434,41.52,89.25,21.58,109.21,167.66,206.43,98.79,15.33,336.59,84.88,172.03,9.21,34.19,482.04,185.55,138.90,24.30,39.13,41.77,375.18,140.92,69.27,272.54,81.96,50.60,106.43,68.78,67.85,303.36,61.47,30.77,233.54,381.59,12.04,407.795,56.13,449.12,71.39,91.25,19.29,88.41,27.15,172.12,210.46,11.87,100.99,207.09,47.23,282.01,164.24,91.3105,302.81,26.66,102.78,68.61,46.77,39.32,9.42,34.79,61.15,54.53,144.82,557.55,58.64,97.38,470.75,131.96,18.90,407.46,90.68,267.03,130.69,103.26,42.35,72.69,1056.35,197.44,56.81,90.18,50.41,36.79,50.90,95.22,134.30,544.10,2.43,322.96,14.93,287.13,75.54,338.24,234.46,81.97,74.39,381.50,76.695,78.70,231.33,164.08,68.81,163.76,80.77,16.41,128.19,45.03,3.05,13.29,58.59,86.69,54.25,58.10,112.34,284.14,28.41,231.71,92.346,88.48,13.71,331.24,12.82,257.99,82.62,190.61,14.16,46.50,272.67,512.25,38.28,44.78,97.68,77.61,15.05,194.45,328.60,123.23,103.26,667.05,79.08,217.03,287.08,185.88,89.14,108.97,190.57,183.13,288.09,280.98,435.71,78.88,152.33,138.54,151.92,50.26,358.04,50.31,84.35,15.77,211.54,113.95,83.64,49.665,333.92,57.72,66.44,230.49,82.59,157.21,98.02,46.95,68.67,256.52,81.57,363.18,18.80,26.23,71.83,333.705,159.03,137.47,490.09,22.03,114.01,211.36,44.23,58.99,81.97,145.59,2.10,87.12,224.28,71.7303,28.69,129.50,120.59,75.84,107.52,68.15,206.94,375.66,330.92,154.63,37.57,313.36,263.91,367.27,24.16,105.26,266.73,128.85,78.10,49.60,111.01,58.25,52.23,60.68,169.66,176.63,85.49,44.99,44.00,152.85,113.49,108.73,161.17,150.62,14.94,14.86,216.26,107.13,66.63,8.34,54.27,151.08,43.79,33.93,88.17,216.79,34.10,65.82,93.96,124.73,22.44,81.29,47.12

=== features_df (Multi-Index Features) ===
--- HEAD (First 3 Rows) ---

                       ATR      ATRP       TRP        RSI  Mom_21  Consistency  IR_63  Beta_63  DD_21  AutoCorr_15    Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5  Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount
Ticker Date
A      1999-11-18      NaN  0.000000  0.000000  50.000000     NaN          NaN    NaN      1.0    0.0          0.0       NaN           NaN        NaN        NaN        0.0              NaN               NaN                  NaN
       1999-11-19  2.49720  0.103712  0.103712   0.000000     NaN          NaN    NaN      1.0    0.0          0.0 -0.082385           NaN        NaN        NaN        0.0              NaN               NaN                  NaN
       1999-11-22  2.48655  0.094761  0.089485   7.142857     NaN          NaN    NaN      1.0    0.0          0.0  0.089782           NaN        NaN        NaN        0.0              NaN               NaN                  NaN

--- TAIL (Last 3 Rows) ---

                        ATR      ATRP       TRP        RSI    Mom_21  Consistency     IR_63   Beta_63     DD_21  AutoCorr_15    Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5  Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount
Ticker Date
ZWS    2026-06-10  1.241188  0.026341  0.036290  44.143181 -0.074245          0.4 -0.047516  1.207976 -0.050993    -0.427133 -0.024834      0.342616   0.000590  -0.220716   0.001688              0.0      3.885449e+07                  0.0
       2026-06-11  1.263961  0.026261  0.032412  50.205407 -0.030651          0.4 -0.035968  1.198699 -0.028701    -0.335414  0.021435      0.604354   0.002971   0.028204  -0.000261              0.0      3.885449e+07                  0.0
       2026-06-12  1.223678  0.025288  0.014466  51.659863 -0.006655          0.6 -0.038373  1.205290 -0.023454    -0.286505  0.005402      0.671505   0.004501   0.269625   0.003911              0.0      3.885449e+07                  0.0

=== macro_df (Macro Data) ===
--- HEAD (First 3 Rows) ---

            Mkt_Ret  Macro_Trend  High_Yield_Spread  Yield_Curve_10Y2Y  High_Yield_Spread_Z  Yield_Curve_10Y2Y_Z  Macro_Trend_Vel  Macro_Trend_Vel_Z  Macro_Trend_Mom  Macro_Vix_Z  Macro_Vix_Ratio
Date
1962-01-02      0.0          0.0                0.0                0.0                  0.0                  0.0              0.0                0.0              0.0          0.0              1.0
1962-01-03      0.0          0.0                0.0                0.0                  0.0                  0.0              0.0                0.0              0.0          0.0              1.0
1962-01-04      0.0          0.0                0.0                0.0                  0.0                  0.0              0.0                0.0              0.0          0.0              1.0

--- TAIL (Last 3 Rows) ---

             Mkt_Ret  Macro_Trend  High_Yield_Spread  Yield_Curve_10Y2Y  High_Yield_Spread_Z  Yield_Curve_10Y2Y_Z  Macro_Trend_Vel  Macro_Trend_Vel_Z  Macro_Trend_Mom  Macro_Vix_Z  Macro_Vix_Ratio
Date
2026-06-10 -0.015766     0.062031                0.0                0.0                  0.0                  0.0        -0.039580          -0.874239        -0.039580     0.485803         0.970730
2026-06-11  0.016997     0.079287                0.0                0.0                  0.0                  0.0        -0.019784          -0.439408        -0.019784    -0.176384         0.907563
2026-06-12  0.005408     0.084315                0.0                0.0                  0.0                  0.0        -0.019995          -0.447505        -0.019995    -0.599436         0.862019

 # Section 4: Engine Initialization & Stage 1 Analysis

In [5]:
# Instantiate Master Engine
engine = AlphaEngine(
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    macro_df=macro_df,
    df_close_wide=df_close_wide,
    df_atrp_wide=df_atrp_wide,
    df_trp_wide=df_trp_wide,
)
print("Master AlphaEngine Ready.")

Master AlphaEngine Ready.

In [ ]:
# Configuration for Interactive UI (Stage 1 Setup)
_inputs = EngineInput(
    mode="Ranking",
    decision_date=pd.Timestamp("2026-04-16"),
    lookback_period=189,
    holding_period=5,
    metric="Sharpe (TRP)",
    benchmark_ticker=config.benchmark_ticker,
    rank_start=1,
    rank_end=200,
    debug=False,
)

analyzer1, stage1_pack = create_walk_forward_analyzer(
    engine, _inputs, universe_subset=None
)
analyzer1.show()

VBox(children=(HTML(value='<b>1. Timeline Configuration:</b> (Past <--- Decision ---> Future)'), HBox(children…

In [7]:
# Execute Headless Agent Simulation
print("--- 🤖 RL AGENT HEADLESS VIEW ---")
metrics_df = run_headless_simulation(engine, _inputs)
display(metrics_df.style.format("{:.4f}"))
print(f"\nTarget Reward Signal: {metrics_df.loc['Group Gain', 'Holding']:.6f}")

--- 🤖 RL AGENT HEADLESS VIEW ---
----------------------------------------------------------------------
Timeline: [2025-07-16] -> Decision: 2026-04-16 -> Entry: 2026-04-17 -> End: 2026-04-24
Selected Tickers (200):
SGOV, SHV, BIL, MINT, USFR, BOXX, PULS, JPST, GTLS, SNDK
JAAA, RVMD, SATS, CIEN, TER, EA, LITE, ASX, VGSH, WDC
GLW, ROIV, SHY, ROST, EWY, WBD, VALE, MU, FTI, ERIC
RIO, VTEB, BE, KEYS, NOK, STX, FIX, UTHR, VCSH, IGSB
MUB, CHRW, EMXC, LRCX, GOOGL, GOOG, HSBC, INTC, TEVA, JNJ
TD, CAT, EWZ, ALB, MKSI, CMI, BNS, BSV, COPX, RY
SU, PBR, EFV, ASML, GSK, EWT, FDX, ONTO, BP, AA
IAG, CVE, SLV, HL, KGC, ITUB, COHR, BHP, AU, JAZZ
IAUM, AMAT, GLDM, SGOL, IAU, APA, B, AZN, XBI, SCCO
EMB, PSLV, EQX, SOXX, SCHF, GLD, VEA, BG, SPDW, NEM
IEMG, VEU, IONS, GDX, EEM, VXUS, PHYS, LSCC, HAL, IXUS
ETR, EWJ, MTZ, OPEN, SMH, FNDX, USO, SOXL, KLAC, GDXJ
MOD, NBIS, FTAI, SIL, MEDP, VLO, MPWR, BK, SPIB, VRT
SHEL, AEM, MBB, TTMI, JBHT, BKR, CNQ, IDEV, DD, GFI
ATI, WELL, FE, JNK, EQIX, NVS, FNV, MTSI, VTR, NVT
EIX, SPHY, AG, FN, PAAS, GM, AEP, IBB, RGLD, AGI
USHY, TJX, HII, IEFA, VYM, XLE, IUSB, CLS, CASY, EFA
XOM, PEN, ADI, RPRX, IWD, SCHD, MRK, VTV, PR, HYG
AGG, APLD, STLD, MRVL, IGIB, VWO, XPO, SPG, VCIT, BND
DGRO, ARGX, C, CFG, TSM, VT, CDE, SLB, IWN, WMT
----------------------------------------------------------------------

Target Reward Signal: 0.002771

 # Section 5: Stage 2 - Cascade Filter Execution

In [8]:
print("--- CASCADE FILTER, TICKERS PASSED FIRST FILTER ---")
# Get decision date from last run
decision_date_last_run = FilterPack(decision_date=analyzer1.last_run.decision_date)

# LAUNCH STAGE 2 (Cascade on the Stage 1 subset)
analyzer2, stage2_pack = create_walk_forward_analyzer(
    engine,
    universe_subset=analyzer1.last_run.tickers,
    filter_pack=decision_date_last_run,
)

print("🚀 Ready for Stage 2: Run Simulation for 2nd filter.")
analyzer2.show()

--- CASCADE FILTER, TICKERS PASSED FIRST FILTER ---
🚀 Ready for Stage 2: Run Simulation for 2nd filter.

VBox(children=(HTML(value='<b>1. Timeline Configuration:</b> (Past <--- Decision ---> Future)'), HBox(children…

In [9]:
# Parse and map results from Analyzer 2
result = SU.map_analyzer(analyzer2)

====================================================================
[SEARCH] ANALYZER SIMULATION MAP
====================================================================
[  0] [DATA] audit_pack (EngineOutput)
[  1]   [PLOT] portfolio_series (shape=(196,))
[  2]   [PLOT] benchmark_series (shape=(196,))
[  3]   [CALC] normalized_plot_data (shape=(196, 100))
[  4]   [FILE] tickers (len=100)
[  5]     [DOC] index_0 (str)
[  6]     [DOC] index_1 (str)
[  7]     [DOC] index_2 (str)
[  8]     [DOC] index_3 (str)
[  9]     [DOC] index_4 (str)
[ 10]     [DOC] index_5 (str)
[ 11]     [DOC] index_6 (str)
[ 12]     [DOC] index_7 (str)
[ 13]     [DOC] index_8 (str)
[ 14]     [DOC] index_9 (str)
[ 15]     [DOC] index_10 (str)
[ 16]     [DOC] index_11 (str)
[ 17]     [DOC] index_12 (str)
[ 18]     [DOC] index_13 (str)
[ 19]     [DOC] index_14 (str)
[ 20]     [DOC] index_15 (str)
[ 21]     [DOC] index_16 (str)
[ 22]     [DOC] index_17 (str)
[ 23]     [DOC] index_18 (str)
[ 24]     [DOC] index_19 (str)
[ 25]     [DOC] index_20 (str)
[ 26]     [DOC] index_21 (str)
[ 27]     [DOC] index_22 (str)
[ 28]     [DOC] index_23 (str)
[ 29]     [DOC] index_24 (str)
[ 30]     [DOC] index_25 (str)
[ 31]     [DOC] index_26 (str)
[ 32]     [DOC] index_27 (str)
[ 33]     [DOC] index_28 (str)
[ 34]     [DOC] index_29 (str)
[ 35]     [DOC] index_30 (str)
[ 36]     [DOC] index_31 (str)
[ 37]     [DOC] index_32 (str)
[ 38]     [DOC] index_33 (str)
[ 39]     [DOC] index_34 (str)
[ 40]     [DOC] index_35 (str)
[ 41]     [DOC] index_36 (str)
[ 42]     [DOC] index_37 (str)
[ 43]     [DOC] index_38 (str)
[ 44]     [DOC] index_39 (str)
[ 45]     [DOC] index_40 (str)
[ 46]     [DOC] index_41 (str)
[ 47]     [DOC] index_42 (str)
[ 48]     [DOC] index_43 (str)
[ 49]     [DOC] index_44 (str)
[ 50]     [DOC] index_45 (str)
[ 51]     [DOC] index_46 (str)
[ 52]     [DOC] index_47 (str)
[ 53]     [DOC] index_48 (str)
[ 54]     [DOC] index_49 (str)
[ 55]     [DOC] index_50 (str)
[ 56]     [DOC] index_51 (str)
[ 57]     [DOC] index_52 (str)
[ 58]     [DOC] index_53 (str)
[ 59]     [DOC] index_54 (str)
[ 60]     [DOC] index_55 (str)
[ 61]     [DOC] index_56 (str)
[ 62]     [DOC] index_57 (str)
[ 63]     [DOC] index_58 (str)
[ 64]     [DOC] index_59 (str)
[ 65]     [DOC] index_60 (str)
[ 66]     [DOC] index_61 (str)
[ 67]     [DOC] index_62 (str)
[ 68]     [DOC] index_63 (str)
[ 69]     [DOC] index_64 (str)
[ 70]     [DOC] index_65 (str)
[ 71]     [DOC] index_66 (str)
[ 72]     [DOC] index_67 (str)
[ 73]     [DOC] index_68 (str)
[ 74]     [DOC] index_69 (str)
[ 75]     [DOC] index_70 (str)
[ 76]     [DOC] index_71 (str)
[ 77]     [DOC] index_72 (str)
[ 78]     [DOC] index_73 (str)
[ 79]     [DOC] index_74 (str)
[ 80]     [DOC] index_75 (str)
[ 81]     [DOC] index_76 (str)
[ 82]     [DOC] index_77 (str)
[ 83]     [DOC] index_78 (str)
[ 84]     [DOC] index_79 (str)
[ 85]     [DOC] index_80 (str)
[ 86]     [DOC] index_81 (str)
[ 87]     [DOC] index_82 (str)
[ 88]     [DOC] index_83 (str)
[ 89]     [DOC] index_84 (str)
[ 90]     [DOC] index_85 (str)
[ 91]     [DOC] index_86 (str)
[ 92]     [DOC] index_87 (str)
[ 93]     [DOC] index_88 (str)
[ 94]     [DOC] index_89 (str)
[ 95]     [DOC] index_90 (str)
[ 96]     [DOC] index_91 (str)
[ 97]     [DOC] index_92 (str)
[ 98]     [DOC] index_93 (str)
[ 99]     [DOC] index_94 (str)
[100]     [DOC] index_95 (str)
[101]     [DOC] index_96 (str)
[102]     [DOC] index_97 (str)
[103]     [DOC] index_98 (str)
[104]     [DOC] index_99 (str)
[105]   [PLOT] initial_weights (shape=(100,))
[106]   [FILE] perf_metrics (len=24)
[107]     [NUM] full_p_gain (float)
[108]     [NUM] full_p_sharpe (shape=())
[109]     [NUM] full_p_sharpe_atrp (float)
[110]     [NUM] full_p_sharpe_trp (float)
[111]     [NUM] lookback_p_gain (float)
[112]     [NUM] lookback_p_sharpe (shape=())
[113]     [NUM] lookback_p_sharpe_atrp (float)
[114]     [NUM] lookback_p_sharpe_trp (float)
[115]     [NUM] holding_p_gain (float)
[116]     [NUM] holding_p_sharpe (shape=())
[117]     [NUM] holding_p_sharpe_atrp (float)
[118]     [NUM] holding_p_sharpe_trp (float)
[119]     [NUM] full_b_gain (float)
[120]     [NUM] full_b_sharpe (shape=())
[121]     [NUM] full_b_sharpe_atrp (float)
[122]     [NUM] full_b_sharpe_trp (float)
[123]     [NUM] lookback_b_gain (float)
[124]     [NUM] lookback_b_sharpe (shape=())
[125]     [NUM] lookback_b_sharpe_atrp (float)
[126]     [NUM] lookback_b_sharpe_trp (float)
[127]     [NUM] holding_b_gain (float)
[128]     [NUM] holding_b_sharpe (shape=())
[129]     [NUM] holding_b_sharpe_atrp (float)
[130]     [NUM] holding_b_sharpe_trp (float)
[131]   [CALC] results_df (shape=(100, 2))
[132]   [DATE] start_date (Timestamp)
[133]   [DATE] decision_date (Timestamp)
[134]   [DATE] buy_date (Timestamp)
[135]   [DATE] holding_end_date (Timestamp)
[136]   [PLOT] portfolio_atrp_series (shape=(196,))
[137]   [PLOT] benchmark_atrp_series (shape=(196,))
[138]   [PLOT] portfolio_trp_series (shape=(196,))
[139]   [PLOT] benchmark_trp_series (shape=(196,))
[140]   [DOC] error_msg (NoneType)
[141]   [FILE] debug_data (len=8)
[142]     [FILE] audit_liquidity (len=3)
[143]       [DOC] mode (str)
[144]       [NUM] tickers_passed (int)
[145]       [NUM] forced_list (bool)
[146]     [CALC] full_universe_ranking (shape=(200, 16))
[147]     [FILE] meta (len=4)
[148]       [NUM] dropped_count (int)
[149]       [FILE] dropped_tickers (len=0)
[150]       [NUM] clean_count (int)
[151]       [DOC] selection_range (str)
[152]     [DATA] inputs_snapshot (EngineInput)
[153]       [DOC] mode (str)
[154]       [DATE] decision_date (Timestamp)
[155]       [NUM] lookback_period (int)
[156]       [NUM] holding_period (int)
[157]       [DOC] metric (str)
[158]       [DOC] benchmark_ticker (str)
[159]       [NUM] rank_start (int)
[160]       [NUM] rank_end (int)
[161]       [DATA] quality_thresholds (QualityThresholds)
[162]         [NUM] min_median_dollar_volume (int)
[163]         [NUM] min_liquidity_percentile (float)
[164]         [NUM] max_stale_pct (float)
[165]         [NUM] max_same_vol_count (int)
[166]       [FILE] manual_tickers (len=0)
[167]       [NUM] debug (bool)
[168]       [FILE] universe_subset (len=200)
[169]         [DOC] index_0 (str)
[170]         [DOC] index_1 (str)
[171]         [DOC] index_2 (str)
[172]         [DOC] index_3 (str)
[173]         [DOC] index_4 (str)
[174]         [DOC] index_5 (str)
[175]         [DOC] index_6 (str)
[176]         [DOC] index_7 (str)
[177]         [DOC] index_8 (str)
[178]         [DOC] index_9 (str)
[179]         [DOC] index_10 (str)
[180]         [DOC] index_11 (str)
[181]         [DOC] index_12 (str)
[182]         [DOC] index_13 (str)
[183]         [DOC] index_14 (str)
[184]         [DOC] index_15 (str)
[185]         [DOC] index_16 (str)
[186]         [DOC] index_17 (str)
[187]         [DOC] index_18 (str)
[188]         [DOC] index_19 (str)
[189]         [DOC] index_20 (str)
[190]         [DOC] index_21 (str)
[191]         [DOC] index_22 (str)
[192]         [DOC] index_23 (str)
[193]         [DOC] index_24 (str)
[194]         [DOC] index_25 (str)
[195]         [DOC] index_26 (str)
[196]         [DOC] index_27 (str)
[197]         [DOC] index_28 (str)
[198]         [DOC] index_29 (str)
[199]         [DOC] index_30 (str)
[200]         [DOC] index_31 (str)
[201]         [DOC] index_32 (str)
[202]         [DOC] index_33 (str)
[203]         [DOC] index_34 (str)
[204]         [DOC] index_35 (str)
[205]         [DOC] index_36 (str)
[206]         [DOC] index_37 (str)
[207]         [DOC] index_38 (str)
[208]         [DOC] index_39 (str)
[209]         [DOC] index_40 (str)
[210]         [DOC] index_41 (str)
[211]         [DOC] index_42 (str)
[212]         [DOC] index_43 (str)
[213]         [DOC] index_44 (str)
[214]         [DOC] index_45 (str)
[215]         [DOC] index_46 (str)
[216]         [DOC] index_47 (str)
[217]         [DOC] index_48 (str)
[218]         [DOC] index_49 (str)
[219]         [DOC] index_50 (str)
[220]         [DOC] index_51 (str)
[221]         [DOC] index_52 (str)
[222]         [DOC] index_53 (str)
[223]         [DOC] index_54 (str)
[224]         [DOC] index_55 (str)
[225]         [DOC] index_56 (str)
[226]         [DOC] index_57 (str)
[227]         [DOC] index_58 (str)
[228]         [DOC] index_59 (str)
[229]         [DOC] index_60 (str)
[230]         [DOC] index_61 (str)
[231]         [DOC] index_62 (str)
[232]         [DOC] index_63 (str)
[233]         [DOC] index_64 (str)
[234]         [DOC] index_65 (str)
[235]         [DOC] index_66 (str)
[236]         [DOC] index_67 (str)
[237]         [DOC] index_68 (str)
[238]         [DOC] index_69 (str)
[239]         [DOC] index_70 (str)
[240]         [DOC] index_71 (str)
[241]         [DOC] index_72 (str)
[242]         [DOC] index_73 (str)
[243]         [DOC] index_74 (str)
[244]         [DOC] index_75 (str)
[245]         [DOC] index_76 (str)
[246]         [DOC] index_77 (str)
[247]         [DOC] index_78 (str)
[248]         [DOC] index_79 (str)
[249]         [DOC] index_80 (str)
[250]         [DOC] index_81 (str)
[251]         [DOC] index_82 (str)
[252]         [DOC] index_83 (str)
[253]         [DOC] index_84 (str)
[254]         [DOC] index_85 (str)
[255]         [DOC] index_86 (str)
[256]         [DOC] index_87 (str)
[257]         [DOC] index_88 (str)
[258]         [DOC] index_89 (str)
[259]         [DOC] index_90 (str)
[260]         [DOC] index_91 (str)
[261]         [DOC] index_92 (str)
[262]         [DOC] index_93 (str)
[263]         [DOC] index_94 (str)
[264]         [DOC] index_95 (str)
[265]         [DOC] index_96 (str)
[266]         [DOC] index_97 (str)
[267]         [DOC] index_98 (str)
[268]         [DOC] index_99 (str)
[269]         [DOC] index_100 (str)
[270]         [DOC] index_101 (str)
[271]         [DOC] index_102 (str)
[272]         [DOC] index_103 (str)
[273]         [DOC] index_104 (str)
[274]         [DOC] index_105 (str)
[275]         [DOC] index_106 (str)
[276]         [DOC] index_107 (str)
[277]         [DOC] index_108 (str)
[278]         [DOC] index_109 (str)
[279]         [DOC] index_110 (str)
[280]         [DOC] index_111 (str)
[281]         [DOC] index_112 (str)
[282]         [DOC] index_113 (str)
[283]         [DOC] index_114 (str)
[284]         [DOC] index_115 (str)
[285]         [DOC] index_116 (str)
[286]         [DOC] index_117 (str)
[287]         [DOC] index_118 (str)
[288]         [DOC] index_119 (str)
[289]         [DOC] index_120 (str)
[290]         [DOC] index_121 (str)
[291]         [DOC] index_122 (str)
[292]         [DOC] index_123 (str)
[293]         [DOC] index_124 (str)
[294]         [DOC] index_125 (str)
[295]         [DOC] index_126 (str)
[296]         [DOC] index_127 (str)
[297]         [DOC] index_128 (str)
[298]         [DOC] index_129 (str)
[299]         [DOC] index_130 (str)
[300]         [DOC] index_131 (str)
[301]         [DOC] index_132 (str)
[302]         [DOC] index_133 (str)
[303]         [DOC] index_134 (str)
[304]         [DOC] index_135 (str)
[305]         [DOC] index_136 (str)
[306]         [DOC] index_137 (str)
[307]         [DOC] index_138 (str)
[308]         [DOC] index_139 (str)
[309]         [DOC] index_140 (str)
[310]         [DOC] index_141 (str)
[311]         [DOC] index_142 (str)
[312]         [DOC] index_143 (str)
[313]         [DOC] index_144 (str)
[314]         [DOC] index_145 (str)
[315]         [DOC] index_146 (str)
[316]         [DOC] index_147 (str)
[317]         [DOC] index_148 (str)
[318]         [DOC] index_149 (str)
[319]         [DOC] index_150 (str)
[320]         [DOC] index_151 (str)
[321]         [DOC] index_152 (str)
[322]         [DOC] index_153 (str)
[323]         [DOC] index_154 (str)
[324]         [DOC] index_155 (str)
[325]         [DOC] index_156 (str)
[326]         [DOC] index_157 (str)
[327]         [DOC] index_158 (str)
[328]         [DOC] index_159 (str)
[329]         [DOC] index_160 (str)
[330]         [DOC] index_161 (str)
[331]         [DOC] index_162 (str)
[332]         [DOC] index_163 (str)
[333]         [DOC] index_164 (str)
[334]         [DOC] index_165 (str)
[335]         [DOC] index_166 (str)
[336]         [DOC] index_167 (str)
[337]         [DOC] index_168 (str)
[338]         [DOC] index_169 (str)
[339]         [DOC] index_170 (str)
[340]         [DOC] index_171 (str)
[341]         [DOC] index_172 (str)
[342]         [DOC] index_173 (str)
[343]         [DOC] index_174 (str)
[344]         [DOC] index_175 (str)
[345]         [DOC] index_176 (str)
[346]         [DOC] index_177 (str)
[347]         [DOC] index_178 (str)
[348]         [DOC] index_179 (str)
[349]         [DOC] index_180 (str)
[350]         [DOC] index_181 (str)
[351]         [DOC] index_182 (str)
[352]         [DOC] index_183 (str)
[353]         [DOC] index_184 (str)
[354]         [DOC] index_185 (str)
[355]         [DOC] index_186 (str)
[356]         [DOC] index_187 (str)
[357]         [DOC] index_188 (str)
[358]         [DOC] index_189 (str)
[359]         [DOC] index_190 (str)
[360]         [DOC] index_191 (str)
[361]         [DOC] index_192 (str)
[362]         [DOC] index_193 (str)
[363]         [DOC] index_194 (str)
[364]         [DOC] index_195 (str)
[365]         [DOC] index_196 (str)
[366]         [DOC] index_197 (str)
[367]         [DOC] index_198 (str)
[368]         [DOC] index_199 (str)
[369]     [FILE] verification (len=2)
[370]       [FILE] p (len=4)
                  +-- val --> [See ID 1]
[371]         [PLOT] ret (shape=(196,))
                  +-- atrp --> [See ID 136]
                  +-- trp --> [See ID 138]
[372]       [FILE] b (len=4)
                  +-- val --> [See ID 2]
[373]         [PLOT] ret (shape=(196,))
                  +-- atrp --> [See ID 137]
                  +-- trp --> [See ID 139]
[374]     [FILE] portfolio_raw_components (len=4)
[375]       [CALC] prices (shape=(196, 100))
[376]       [CALC] atrp (shape=(196, 100))
[377]       [CALC] trp (shape=(196, 100))
[378]       [CALC] ohlcv_raw (shape=(19600, 5))
[379]     [FILE] benchmark_raw_components (len=4)
[380]       [CALC] prices (shape=(196, 1))
[381]       [CALC] atrp (shape=(196, 1))
[382]       [CALC] trp (shape=(196, 1))
[383]       [CALC] ohlcv_raw (shape=(196, 5))
              +-- selection_audit --> [See ID 146]
[384]   [CALC] macro_df (shape=(16220, 11))
[385]   [DOC] alpha_perception (NoneType)

In [10]:
# Test different methods to extract resulting target tickers
_tickers = SU.fetch(4, result)
print(f"_tickers (by index): {_tickers}\n")

_tickers = SU.fetch("tickers", result)
print(f"_tickers (by key): {_tickers}\n")

print(f'result[4]["obj"]: {result[4]["obj"]}')

 ============================================================
 [INFO] INDEX: [4]
 [LABEL] NAME:  tickers
 [FILE] PATH:  audit_pack -> tickers
 ============================================================

['SGOV',
 'SHV',
 'BIL',
 'MINT',
 'USFR',
 'BOXX',
 'PULS',
 'JPST',
 'GTLS',
 'SNDK',
 'JAAA',
 'RVMD',
 'SATS',
 'CIEN',
 'TER',
 'EA',
 'LITE',
 'ASX',
 'VGSH',
 'WDC',
 'GLW',
 'ROIV',
 'SHY',
 'ROST',
 'EWY',
 'WBD',
 'VALE',
 'MU',
 'FTI',
 'ERIC',
 'RIO',
 'VTEB',
 'BE',
 'KEYS',
 'NOK',
 'STX',
 'FIX',
 'UTHR',
 'VCSH',
 'IGSB',
 'MUB',
 'CHRW',
 'EMXC',
 'LRCX',
 'GOOGL',
 'GOOG',
 'HSBC',
 'INTC',
 'TEVA',
 'JNJ',
 'TD',
 'CAT',
 'EWZ',
 'ALB',
 'MKSI',
 'CMI',
 'BNS',
 'BSV',
 'COPX',
 'RY',
 'SU',
 'PBR',
 'EFV',
 'ASML',
 'GSK',
 'EWT',
 'FDX',
 'ONTO',
 'BP',
 'AA',
 'IAG',
 'CVE',
 'SLV',
 'HL',
 'KGC',
 'ITUB',
 'COHR',
 'BHP',
 'AU',
 'JAZZ',
 'IAUM',
 'AMAT',
 'GLDM',
 'SGOL',
 'IAU',
 'APA',
 'B',
 'AZN',
 'XBI',
 'SCCO',
 'EMB',
 'PSLV',
 'EQX',
 'SOXX',
 'SCHF',
 'GLD',
 'VEA',
 'BG',
 'SPDW',
 'NEM']

_tickers (by index): ['SGOV', 'SHV', 'BIL', 'MINT', 'USFR', 'BOXX', 'PULS', 'JPST', 'GTLS', 'SNDK', 'JAAA', 'RVMD', 'SATS', 'CIEN', 'TER', 'EA', 'LITE', 'ASX', 'VGSH', 'WDC', 'GLW', 'ROIV', 'SHY', 'ROST', 'EWY', 'WBD', 'VALE', 'MU', 'FTI', 'ERIC', 'RIO', 'VTEB', 'BE', 'KEYS', 'NOK', 'STX', 'FIX', 'UTHR', 'VCSH', 'IGSB', 'MUB', 'CHRW', 'EMXC', 'LRCX', 'GOOGL', 'GOOG', 'HSBC', 'INTC', 'TEVA', 'JNJ', 'TD', 'CAT', 'EWZ', 'ALB', 'MKSI', 'CMI', 'BNS', 'BSV', 'COPX', 'RY', 'SU', 'PBR', 'EFV', 'ASML', 'GSK', 'EWT', 'FDX', 'ONTO', 'BP', 'AA', 'IAG', 'CVE', 'SLV', 'HL', 'KGC', 'ITUB', 'COHR', 'BHP', 'AU', 'JAZZ', 'IAUM', 'AMAT', 'GLDM', 'SGOL', 'IAU', 'APA', 'B', 'AZN', 'XBI', 'SCCO', 'EMB', 'PSLV', 'EQX', 'SOXX', 'SCHF', 'GLD', 'VEA', 'BG', 'SPDW', 'NEM']

 ============================================================
 [INFO] INDEX: [4]
 [LABEL] NAME:  tickers
 [FILE] PATH:  audit_pack -> tickers
 ============================================================

['SGOV',
 'SHV',
 'BIL',
 'MINT',
 'USFR',
 'BOXX',
 'PULS',
 'JPST',
 'GTLS',
 'SNDK',
 'JAAA',
 'RVMD',
 'SATS',
 'CIEN',
 'TER',
 'EA',
 'LITE',
 'ASX',
 'VGSH',
 'WDC',
 'GLW',
 'ROIV',
 'SHY',
 'ROST',
 'EWY',
 'WBD',
 'VALE',
 'MU',
 'FTI',
 'ERIC',
 'RIO',
 'VTEB',
 'BE',
 'KEYS',
 'NOK',
 'STX',
 'FIX',
 'UTHR',
 'VCSH',
 'IGSB',
 'MUB',
 'CHRW',
 'EMXC',
 'LRCX',
 'GOOGL',
 'GOOG',
 'HSBC',
 'INTC',
 'TEVA',
 'JNJ',
 'TD',
 'CAT',
 'EWZ',
 'ALB',
 'MKSI',
 'CMI',
 'BNS',
 'BSV',
 'COPX',
 'RY',
 'SU',
 'PBR',
 'EFV',
 'ASML',
 'GSK',
 'EWT',
 'FDX',
 'ONTO',
 'BP',
 'AA',
 'IAG',
 'CVE',
 'SLV',
 'HL',
 'KGC',
 'ITUB',
 'COHR',
 'BHP',
 'AU',
 'JAZZ',
 'IAUM',
 'AMAT',
 'GLDM',
 'SGOL',
 'IAU',
 'APA',
 'B',
 'AZN',
 'XBI',
 'SCCO',
 'EMB',
 'PSLV',
 'EQX',
 'SOXX',
 'SCHF',
 'GLD',
 'VEA',
 'BG',
 'SPDW',
 'NEM']

_tickers (by key): ['SGOV', 'SHV', 'BIL', 'MINT', 'USFR', 'BOXX', 'PULS', 'JPST', 'GTLS', 'SNDK', 'JAAA', 'RVMD', 'SATS', 'CIEN', 'TER', 'EA', 'LITE', 'ASX', 'VGSH', 'WDC', 'GLW', 'ROIV', 'SHY', 'ROST', 'EWY', 'WBD', 'VALE', 'MU', 'FTI', 'ERIC', 'RIO', 'VTEB', 'BE', 'KEYS', 'NOK', 'STX', 'FIX', 'UTHR', 'VCSH', 'IGSB', 'MUB', 'CHRW', 'EMXC', 'LRCX', 'GOOGL', 'GOOG', 'HSBC', 'INTC', 'TEVA', 'JNJ', 'TD', 'CAT', 'EWZ', 'ALB', 'MKSI', 'CMI', 'BNS', 'BSV', 'COPX', 'RY', 'SU', 'PBR', 'EFV', 'ASML', 'GSK', 'EWT', 'FDX', 'ONTO', 'BP', 'AA', 'IAG', 'CVE', 'SLV', 'HL', 'KGC', 'ITUB', 'COHR', 'BHP', 'AU', 'JAZZ', 'IAUM', 'AMAT', 'GLDM', 'SGOL', 'IAU', 'APA', 'B', 'AZN', 'XBI', 'SCCO', 'EMB', 'PSLV', 'EQX', 'SOXX', 'SCHF', 'GLD', 'VEA', 'BG', 'SPDW', 'NEM']

result[4]["obj"]: ['SGOV', 'SHV', 'BIL', 'MINT', 'USFR', 'BOXX', 'PULS', 'JPST', 'GTLS', 'SNDK', 'JAAA', 'RVMD', 'SATS', 'CIEN', 'TER', 'EA', 'LITE', 'ASX', 'VGSH', 'WDC', 'GLW', 'ROIV', 'SHY', 'ROST', 'EWY', 'WBD', 'VALE', 'MU', 'FTI', 'ERIC', 'RIO', 'VTEB', 'BE', 'KEYS', 'NOK', 'STX', 'FIX', 'UTHR', 'VCSH', 'IGSB', 'MUB', 'CHRW', 'EMXC', 'LRCX', 'GOOGL', 'GOOG', 'HSBC', 'INTC', 'TEVA', 'JNJ', 'TD', 'CAT', 'EWZ', 'ALB', 'MKSI', 'CMI', 'BNS', 'BSV', 'COPX', 'RY', 'SU', 'PBR', 'EFV', 'ASML', 'GSK', 'EWT', 'FDX', 'ONTO', 'BP', 'AA', 'IAG', 'CVE', 'SLV', 'HL', 'KGC', 'ITUB', 'COHR', 'BHP', 'AU', 'JAZZ', 'IAUM', 'AMAT', 'GLDM', 'SGOL', 'IAU', 'APA', 'B', 'AZN', 'XBI', 'SCCO', 'EMB', 'PSLV', 'EQX', 'SOXX', 'SCHF', 'GLD', 'VEA', 'BG', 'SPDW', 'NEM']

 # Section 6: Verification, Exports & Auditing

In [11]:
# Export analytical trace logs to Excel
SU.export_audit_to_excel(
    audit_pack=analyzer2.last_run, filename="Audit_Verification_Report.xlsx"
)

[FILE] [EXCEL AUDIT] Building full transparency report: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\output\Audit_Verification_Report.xlsx
[DONE] Audit Report Complete: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\output\Audit_Verification_Report.xlsx

WindowsPath('C:/Users/ping/Files_win10/python/py311/stocks/notebooks_RLVR_v2/output/Audit_Verification_Report.xlsx')

In [12]:
# Export last-run stacked OHLCV ticker records
SU.export_last_run_tickers_data_to_csv(
    analyzer=analyzer2,
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    filename="last_run_tickers_stacked.csv",
)

Creating combined dictionary for 101 ticker(s)
Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00
============================================================
Data retrieved for 101 ticker(s) from 2025-07-16 00:00:00 to 2026-04-24 00:00:00
Total rows: 19796
Date range in data: 2025-07-16 00:00:00 to 2026-04-24 00:00:00
  SGOV: 196 rows
  SHV: 196 rows
  BIL: 196 rows
  MINT: 196 rows
  USFR: 196 rows
  BOXX: 196 rows
  PULS: 196 rows
  JPST: 196 rows
  GTLS: 196 rows
  SNDK: 196 rows
  JAAA: 196 rows
  RVMD: 196 rows
  SATS: 196 rows
  CIEN: 196 rows
  TER: 196 rows
  EA: 196 rows
  LITE: 196 rows
  ASX: 196 rows
  VGSH: 196 rows
  WDC: 196 rows
  GLW: 196 rows
  ROIV: 196 rows
  SHY: 196 rows
  ROST: 196 rows
  EWY: 196 rows
  WBD: 196 rows
  VALE: 196 rows
  MU: 196 rows
  FTI: 196 rows
  ERIC: 196 rows
  RIO: 196 rows
  VTEB: 196 rows
  BE: 196 rows
  KEYS: 196 rows
  NOK: 196 rows
  STX: 196 rows
  FIX: 196 rows
  UTHR: 196 rows
  VCSH: 196 rows
  IGSB: 196 rows
  MUB: 196 rows
  CHRW: 196 rows
  EMXC: 196 rows
  LRCX: 196 rows
  GOOGL: 196 rows
  GOOG: 196 rows
  HSBC: 196 rows
  INTC: 196 rows
  TEVA: 196 rows
  JNJ: 196 rows
  TD: 196 rows
  CAT: 196 rows
  EWZ: 196 rows
  ALB: 196 rows
  MKSI: 196 rows
  CMI: 196 rows
  BNS: 196 rows
  BSV: 196 rows
  COPX: 196 rows
  RY: 196 rows
  SU: 196 rows
  PBR: 196 rows
  EFV: 196 rows
  ASML: 196 rows
  GSK: 196 rows
  EWT: 196 rows
  FDX: 196 rows
  ONTO: 196 rows
  BP: 196 rows
  AA: 196 rows
  IAG: 196 rows
  CVE: 196 rows
  SLV: 196 rows
  HL: 196 rows
  KGC: 196 rows
  ITUB: 196 rows
  COHR: 196 rows
  BHP: 196 rows
  AU: 196 rows
  JAZZ: 196 rows
  IAUM: 196 rows
  AMAT: 196 rows
  GLDM: 196 rows
  SGOL: 196 rows
  IAU: 196 rows
  APA: 196 rows
  B: 196 rows
  AZN: 196 rows
  XBI: 196 rows
  SCCO: 196 rows
  EMB: 196 rows
  PSLV: 196 rows
  EQX: 196 rows
  SOXX: 196 rows
  SCHF: 196 rows
  GLD: 196 rows
  VEA: 196 rows
  BG: 196 rows
  SPDW: 196 rows
  NEM: 196 rows
  SPY: 196 rows
Features data retrieved for 101 ticker(s) from 2025-07-16 00:00:00 to 2026-04-24 00:00:00
Total rows: 19796
Date range in data: 2025-07-16 00:00:00 to 2026-04-24 00:00:00
Available features: ATR, ATRP, TRP, RSI, Mom_21, Consistency, IR_63, Beta_63, DD_21, AutoCorr_15, Ret_1d, Range_Pos_20, Slope_P_5, Slope_V_5, Convexity, RollingStalePct, RollMedDollarVol, RollingSameVolCount
  SGOV: 196 rows
  SHV: 196 rows
  BIL: 196 rows
  MINT: 196 rows
  USFR: 196 rows
  BOXX: 196 rows
  PULS: 196 rows
  JPST: 196 rows
  GTLS: 196 rows
  SNDK: 196 rows
  JAAA: 196 rows
  RVMD: 196 rows
  SATS: 196 rows
  CIEN: 196 rows
  TER: 196 rows
  EA: 196 rows
  LITE: 196 rows
  ASX: 196 rows
  VGSH: 196 rows
  WDC: 196 rows
  GLW: 196 rows
  ROIV: 196 rows
  SHY: 196 rows
  ROST: 196 rows
  EWY: 196 rows
  WBD: 196 rows
  VALE: 196 rows
  MU: 196 rows
  FTI: 196 rows
  ERIC: 196 rows
  RIO: 196 rows
  VTEB: 196 rows
  BE: 196 rows
  KEYS: 196 rows
  NOK: 196 rows
  STX: 196 rows
  FIX: 196 rows
  UTHR: 196 rows
  VCSH: 196 rows
  IGSB: 196 rows
  MUB: 196 rows
  CHRW: 196 rows
  EMXC: 196 rows
  LRCX: 196 rows
  GOOGL: 196 rows
  GOOG: 196 rows
  HSBC: 196 rows
  INTC: 196 rows
  TEVA: 196 rows
  JNJ: 196 rows
  TD: 196 rows
  CAT: 196 rows
  EWZ: 196 rows
  ALB: 196 rows
  MKSI: 196 rows
  CMI: 196 rows
  BNS: 196 rows
  BSV: 196 rows
  COPX: 196 rows
  RY: 196 rows
  SU: 196 rows
  PBR: 196 rows
  EFV: 196 rows
  ASML: 196 rows
  GSK: 196 rows
  EWT: 196 rows
  FDX: 196 rows
  ONTO: 196 rows
  BP: 196 rows
  AA: 196 rows
  IAG: 196 rows
  CVE: 196 rows
  SLV: 196 rows
  HL: 196 rows
  KGC: 196 rows
  ITUB: 196 rows
  COHR: 196 rows
  BHP: 196 rows
  AU: 196 rows
  JAZZ: 196 rows
  IAUM: 196 rows
  AMAT: 196 rows
  GLDM: 196 rows
  SGOL: 196 rows
  IAU: 196 rows
  APA: 196 rows
  B: 196 rows
  AZN: 196 rows
  XBI: 196 rows
  SCCO: 196 rows
  EMB: 196 rows
  PSLV: 196 rows
  EQX: 196 rows
  SOXX: 196 rows
  SCHF: 196 rows
  GLD: 196 rows
  VEA: 196 rows
  BG: 196 rows
  SPDW: 196 rows
  NEM: 196 rows
  SPY: 196 rows

Processing SGOV...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing SHV...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing BIL...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing MINT...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing USFR...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing BOXX...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing PULS...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing JPST...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing GTLS...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing SNDK...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing JAAA...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing RVMD...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing SATS...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing CIEN...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing TER...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing EA...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing LITE...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ASX...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing VGSH...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing WDC...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing GLW...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ROIV...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing SHY...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ROST...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing EWY...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing WBD...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing VALE...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing MU...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing FTI...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ERIC...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing RIO...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing VTEB...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing BE...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing KEYS...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing NOK...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing STX...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing FIX...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing UTHR...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing VCSH...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing IGSB...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing MUB...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing CHRW...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing EMXC...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing LRCX...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing GOOGL...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing GOOG...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing HSBC...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing INTC...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing TEVA...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing JNJ...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing TD...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing CAT...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing EWZ...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ALB...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing MKSI...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing CMI...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing BNS...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing BSV...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing COPX...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing RY...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing SU...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing PBR...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing EFV...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ASML...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing GSK...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing EWT...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing FDX...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ONTO...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing BP...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing AA...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing IAG...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing CVE...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing SLV...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing HL...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing KGC...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing ITUB...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing COHR...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing BHP...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing AU...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing JAZZ...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing IAUM...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing AMAT...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing GLDM...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00

Processing SGOL...
  [OK] Successfully combined data
  OHLCV shape: (196, 5)
  Features shape: (196, 18)
  Combined shape: (196, 23)
  Date range: 2025-07-16 00:00:00 to 2026-04-24 00:00:00


WindowsPath('C:/Users/ping/Files_win10/python/py311/stocks/notebooks_RLVR_v2/output/last_run_tickers_stacked.csv')

 # Section 7: Slicing Tests & Dictionary Parsing

In [13]:
# Verify captured ticker names
_tickers

['SGOV',
 'SHV',
 'BIL',
 'MINT',
 'USFR',
 'BOXX',
 'PULS',
 'JPST',
 'GTLS',
 'SNDK',
 'JAAA',
 'RVMD',
 'SATS',
 'CIEN',
 'TER',
 'EA',
 'LITE',
 'ASX',
 'VGSH',
 'WDC',
 'GLW',
 'ROIV',
 'SHY',
 'ROST',
 'EWY',
 'WBD',
 'VALE',
 'MU',
 'FTI',
 'ERIC',
 'RIO',
 'VTEB',
 'BE',
 'KEYS',
 'NOK',
 'STX',
 'FIX',
 'UTHR',
 'VCSH',
 'IGSB',
 'MUB',
 'CHRW',
 'EMXC',
 'LRCX',
 'GOOGL',
 'GOOG',
 'HSBC',
 'INTC',
 'TEVA',
 'JNJ',
 'TD',
 'CAT',
 'EWZ',
 'ALB',
 'MKSI',
 'CMI',
 'BNS',
 'BSV',
 'COPX',
 'RY',
 'SU',
 'PBR',
 'EFV',
 'ASML',
 'GSK',
 'EWT',
 'FDX',
 'ONTO',
 'BP',
 'AA',
 'IAG',
 'CVE',
 'SLV',
 'HL',
 'KGC',
 'ITUB',
 'COHR',
 'BHP',
 'AU',
 'JAZZ',
 'IAUM',
 'AMAT',
 'GLDM',
 'SGOL',
 'IAU',
 'APA',
 'B',
 'AZN',
 'XBI',
 'SCCO',
 'EMB',
 'PSLV',
 'EQX',
 'SOXX',
 'SCHF',
 'GLD',
 'VEA',
 'BG',
 'SPDW',
 'NEM']

In [14]:
# Test various pandas multi-index slicing configurations
test_tickers = ["NVDA", "GOOG"]
idx = pd.IndexSlice
columns = ["Adj Close", "Volume"]

# Slice 1: All dates, all columns
display(df_ohlcv.loc[idx[test_tickers]].copy().head(3))

# Slice 2: specific start date, all columns
display(df_ohlcv.loc[idx[test_tickers, pd.Timestamp("2026-04-01") :], :].head(3))

# Slice 3: specific start date, selected columns
display(df_ohlcv.loc[idx[test_tickers, pd.Timestamp("2026-04-01") :], columns].head(3))

# Slice 4: specific start/end range, all columns
display(
    df_ohlcv.loc[
        idx[test_tickers, pd.Timestamp("2026-04-01") : pd.Timestamp("2026-04-10")], :
    ].head(3)
)

                   Adj Open  Adj High   Adj Low  Adj Close      Volume
Ticker Date
NVDA   1999-01-22  0.040063  0.044713  0.035532   0.037559  2964546624
       1999-01-25  0.040540  0.041970  0.037559   0.041494   557464553
       1999-01-26  0.041970  0.042805  0.037678   0.038274   374788019

                   Adj Open  Adj High  Adj Low  Adj Close     Volume
Ticker Date
NVDA   2026-04-01   175.795   177.164  174.547    175.545  168327949
       2026-04-02   171.980   177.283  171.170    177.183  143310037
       2026-04-06   176.954   177.583  175.555    177.433  107689668

                   Adj Close     Volume
Ticker Date
NVDA   2026-04-01    175.545  168327949
       2026-04-02    177.183  143310037
       2026-04-06    177.433  107689668

                   Adj Open  Adj High  Adj Low  Adj Close     Volume
Ticker Date
NVDA   2026-04-01   175.795   177.164  174.547    175.545  168327949
       2026-04-02   171.980   177.283  171.170    177.183  143310037
       2026-04-06   176.954   177.583  175.555    177.433  107689668

In [15]:
# Test custom combined dictionary extraction
SU.create_combined_dict(
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    tickers=_tickers,
    date_start="2026-05-01",
    date_end=None,
    verbose=False,
)

{'SGOV':             Adj Open  Adj High  Adj Low  Adj Close    Volume       ATR      ATRP       TRP        RSI    Mom_21  Consistency     IR_63   Beta_63  DD_21  AutoCorr_15    Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5  Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount
 Date
 2026-05-01   100.112   100.112  100.102    100.112  33910416  0.019468  0.000194  0.000380  99.999829  0.003171          0.6 -0.061531 -0.003311    0.0    -0.574265  0.000380      1.000000   0.000146   0.739754   0.000006         0.011905      1.368668e+09                  0.0
 2026-05-04   100.122   100.122  100.112    100.122  20844209  0.018792  0.000188  0.000100  99.999837  0.002872          0.8 -0.047191 -0.003235    0.0    -0.582875  0.000100      1.000000   0.000154   0.914948   0.000064         0.011905      1.368668e+09                  0.0
 2026-05-05   100.132   100.132  100.122    100.132  17198180  0.018164  0.000181  0.000100  99.999845  0.002871          0.8 -0.074902 -0.003220    0.0    -0.630826  0.000100      1.000000   0.000164   1.045906   0.000018         0.011905      1.368668e+09                  0.0
 2026-05-06   100.142   100.142  100.132    100.142  20612420  0.017581  0.000176  0.000100  99.999853  0.002872          0.8 -0.104853 -0.003286    0.0    -0.610670  0.000100      1.000000   0.000156   1.177021   0.000002         0.011905      1.371227e+09                  0.0
 2026-05-07   100.152   100.152  100.142    100.152  17328567  0.017039  0.000170  0.000100  99.999861  0.002972          1.0 -0.121953 -0.003706    0.0    -0.589768  0.000100      1.000000   0.000100   1.003861  -0.000064         0.011905      1.373512e+09                  0.0
 2026-05-08   100.182   100.182  100.172    100.182  20332490  0.017965  0.000179  0.000299  99.999881  0.003173          1.0 -0.106304 -0.004216    0.0    -0.529281  0.000300      1.000000   0.000140   0.999112  -0.000016         0.011905      1.374583e+09                  0.0
 2026-05-11   100.192   100.192  100.182    100.192  21500156  0.017396  0.000174  0.000100  99.999887  0.002874          1.0 -0.102236 -0.004275    0.0    -0.529155  0.000100      1.000000   0.000160   1.041499   0.000060         0.011905      1.380694e+09                  0.0
 2026-05-12   100.192   100.202  100.192    100.202  18368154  0.016868  0.000168  0.000100  99.999893  0.002874          1.0 -0.104225 -0.004290    0.0    -0.504855  0.000100      1.000000   0.000160   1.037150   0.000020         0.011905      1.388046e+09                  0.0
 2026-05-13   100.211   100.211  100.202    100.211  16820458  0.016306  0.000163  0.000090  99.999898  0.002965          1.0 -0.113855 -0.004358    0.0    -0.479712  0.000090      1.000000   0.000138   1.017738  -0.000022         0.011905      1.388046e+09                  0.0
 2026-05-14   100.221   100.221  100.211    100.221  15770740  0.015855  0.000158  0.000100  99.999903  0.002865          1.0 -0.157564 -0.004435    0.0    -0.477419  0.000100      1.000000   0.000097   0.942305  -0.000063         0.011905      1.388046e+09                  0.0
 2026-05-15   100.251   100.251  100.241    100.251  18296743  0.016866  0.000168  0.000299  99.999917  0.003165          1.0 -0.133049 -0.004650    0.0    -0.477743  0.000299      1.000000   0.000137   0.893176  -0.000001         0.011905      1.392964e+09                  0.0
 2026-05-18   100.261   100.261  100.251    100.261  23631388  0.016375  0.000163  0.000100  99.999921  0.002966          1.0 -0.128846 -0.004623    0.0    -0.403415  0.000100      1.000000   0.000158   0.952812   0.000061         0.011905      1.398332e+09                  0.0
 2026-05-19   100.271   100.271  100.261    100.271  20515333  0.015920  0.000159  0.000100  99.999925  0.002966          1.0 -0.108419 -0.004559    0.0    -0.362078  0.000100      1.000000   0.000160   1.027590   0.000023         0.011905      1.402871e+09                  0.0
 2026-05-20   100.281   100.281  100.271    100.281  16991365  0.015497  0.000155  0.000100  99.999929  0.002866          1.0 -0.129658 -0.004602    0.0    -0.338274  0.000100      1.000000   0.000140   1.046321  -0.000018         0.011905      1.402871e+09                  0.0
 2026-05-21   100.291   100.291  100.281    100.281  17411814  0.015104  0.000151  0.000100  99.999929  0.002770          0.8 -0.121452 -0.004717    0.0    -0.338062  0.000000      0.961089   0.000080   0.820294  -0.000080         0.011905      1.406083e+09                  0.0
 2026-05-22   100.326   100.331  100.321    100.331  18488312  0.017597  0.000175  0.000498  99.999946  0.003170          0.8 -0.146868 -0.004527    0.0    -0.369443  0.000499      1.000000   0.000150   0.658135   0.000010         0.011905      1.407979e+09                  0.0
 2026-05-26   100.341   100.341  100.331    100.341  21729037  0.017054  0.000170  0.000100  99.999948  0.002969          0.8 -0.145719 -0.004417    0.0    -0.328812  0.000100      1.000000   0.000189   0.673366   0.000110         0.011905      1.410832e+09                  0.0
 2026-05-27   100.341   100.351  100.341    100.351  15530126  0.016550  0.000165  0.000100  99.999951  0.003069          0.8 -0.131435 -0.004382    0.0    -0.328690  0.000100      1.000000   0.000199   0.765140   0.000050         0.011905      1.415622e+09                  0.0
 2026-05-28   100.359   100.361  100.351    100.351  16666501  0.016083  0.000160  0.000100  99.999951  0.002868          0.6 -0.151467 -0.004446    0.0    -0.295198  0.000000      0.965157   0.000159   0.749372  -0.000030         0.011905      1.420056e+09                  0.0
 2026-05-29   100.371   100.381  100.371    100.371  34326353  0.017077  0.000170  0.000299  99.999956  0.002968          0.8 -0.164820 -0.004399    0.0    -0.324471  0.000199      0.964158   0.000090   0.794432  -0.000110         0.011905      1.422333e+09                  0.0
 2026-06-01   100.400   100.400  100.390    100.400  39897700  0.017928  0.000179  0.000289  99.999962  0.003258          0.8 -0.168296 -0.004373    0.0    -0.263110  0.000289      1.000000   0.000137   1.064324  -0.000022         0.011905      1.425396e+09                  0.0
 2026-06-02   100.409   100.410  100.400    100.400  22215700  0.017362  0.000173  0.000100  99.999962  0.002877          0.6 -0.188528 -0.004337    0.0    -0.312278  0.000000      0.965278   0.000146   1.106190   0.000057         0.011905      1.425396e+09                  0.0
 2026-06-03   100.420   100.420  100.410    100.410  19999200  0.017550  0.000175  0.000199  99.999964  0.002876          0.6 -0.162726 -0.004072    0.0    -0.285395  0.000100      0.965278   0.000146   1.132259   0.000009         0.011905      1.425396e+09                  0.0
 2026-06-04   100.425   100.430  100.420    100.420  18801700  0.017725  0.000177  0.000199  99.999966  0.002876          0.8 -0.180043 -0.004192    0.0    -0.287332  0.000100      0.965278   0.000108   0.875951  -0.000039         0.011905      1.431304e+09                  0.0
 2026-06-05   100.455   100.460  100.440    100.450  27836900  0.019316  0.000192  0.000398  99.999971  0.003076          0.8 -0.149892 -0.003880    0.0    -0.307644  0.000299      0.965278   0.000119   0.844608  -0.000027         0.011905      1.435258e+09                  0.0
 2026-06-08   100.450   100.470  100.450    100.460  24095700  0.019365  0.000193  0.000199  99.999972  0.003075          0.8 -0.139641 -0.003868    0.0    -0.307763  0.000100      0.965278   0.000159   1.116432   0.000052         0.011905      1.436794e+09                  0.0
 2026-06-09   100.470   100.470  100.460    100.470  25747500  0.018696  0.000186  0.000100  99.999974  0.002875          1.0 -0.137100 -0.003906    0.0    -0.289553  0.000100      1.000000   0.000159   1.192397   0.000040         0.011905      1.438504e+09                  0.0
 2026-06-10   100.475   100.480  100.470    100.480  20362200  0.018075  0.000180  0.000100  99.999975  0.002874          1.0 -0.109988 -0.003561    0.0    -0.289469  0.000100      1.000000   0.000139   1.190812  -0.000020         0.011905      1.440372e+09                  0.0
 2026-06-11   100.490   100.490  100.480    100.490  24927700  0.017498  0.000174  0.000100  99.999976  0.002874          1.0 -0.163392 -0.003815    0.0    -0.289386  0.000100      1.000000   0.000100   1.136843  -0.000060         0.011905      1.446816e+09                  0.0
 2026-06-12   100.520   100.520  100.510    100.510  23026100  0.018391  0.000183  0.000298  99.999979  0.002984          1.0 -0.182540 -0.003597    0.0    -0.332709  0.000199      0.964158   0.000119   1.115656  -0.000020         0.011905      1.452101e+09                  0.0,
 'SHV':             Adj Open  Adj High  Adj Low  Adj Close   Volume       ATR      ATRP       TRP        RSI    Mom_21  Consistency     IR_63   Beta_63  DD_21  AutoCorr_15    Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5     Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount
 Date
 2026-05-01   109.770   109.770  109.760    109.760  3447939  0.021412  0.000195  0.000346  99.999114  0.003071          0.8 -0.062527  0.000008    0.0    -0.376245  0.000255      0.967320   0.000124   0.635910  1.454123e-05              0.0      2.788755e+08                  0.0
 2026-05-04   109.780   109.780  109.770    109.780  2388763  0.021311  0.000194  0.000182  99.999194  0.002887          0.8 -0.048181 -0.000078    0.0    -0.280524  0.000182      1.000000   0.000168   0.810528  8.563048e-05              0.0      2.776843e+08                  0.0
 2026-05-05   109.780   109.790  109.780    109.780  3073014  0.020503  0.000187  0.000091  99.999194  0.002795          0.6 -0.075951 -0.000326    0.0    -0.280306  0.000000      0.966330   0.000168   0.777431  4.371494e-05              0.0      2.776843e+08                  0.0
 2026-05-06   109.790   109.800  109.790    109.800  2302504  0.020467  0.000186  0.000182  99.999271  0.002895          0.8 -0.105683 -0.000354    0.0    -0.280087  0.000182      1.000000   0.000142   0.596988 -2.554401e-05              0.0      2.761304e+08                  0.0
 2026-05-07   109.810   109.810  109.800    109.810  2276526  0.019720  0.000180  0.000091  99.999306  0.002895          0.8 -0.123395 -0.000009    0.0    -0.337610  0.000091      1.000000   0.000109   0.523187 -5.835217e-05              0.0      2.755160e+08                  0.0
 2026-05-08   109.840   109.850  109.830    109.850  1744731  0.021168  0.000193  0.000364  99.999426  0.003077          0.8 -0.107473  0.000132    0.0    -0.360286  0.000364      1.000000   0.000155   0.559620  1.269094e-05              0.0      2.753104e+08                  0.0
 2026-05-11   109.850   109.850  109.840    109.850  1909024  0.020370  0.000185  0.000091  99.999426  0.002803          0.6 -0.103533  0.000069    0.0    -0.332712  0.000000      1.000000   0.000173   0.543243  6.371040e-05              0.0      2.749768e+08                  0.0
 2026-05-12   109.860   109.860  109.850    109.860  1520660  0.019630  0.000179  0.000091  99.999453  0.002894          0.8 -0.105369 -0.000005    0.0    -0.332529  0.000091      1.000000   0.000146   0.423408 -9.131101e-06              0.0      2.742791e+08                  0.0
 2026-05-13   109.860   109.870  109.860    109.860  3573014  0.018942  0.000172  0.000091  99.999453  0.002711          0.6 -0.115344 -0.000130    0.0    -0.268289  0.000000      0.966330   0.000100   0.269091 -7.286555e-05              0.0      2.742791e+08                  0.0
 2026-05-14   109.870   109.880  109.870    109.870  2390167  0.019017  0.000173  0.000182  99.999482  0.002802          0.6 -0.159067 -0.000336    0.0    -0.220780  0.000091      0.962547   0.000046   0.313566 -1.001668e-04              0.0      2.737795e+08                  0.0
 2026-05-15   109.899   109.909  109.899    109.909  2050950  0.020445  0.000186  0.000355  99.999576  0.003066          0.6 -0.134390 -0.000848    0.0    -0.219208  0.000355      1.000000   0.000116   0.479874  1.634388e-05              0.0      2.736841e+08                  0.0
 2026-05-18   109.909   109.919  109.909    109.919  2741922  0.019699  0.000179  0.000091  99.999596  0.002700          0.8 -0.130343 -0.000828    0.0    -0.218754  0.000091      1.000000   0.000152   0.629226  1.064600e-04              0.0      2.736841e+08                  0.0
 2026-05-19   109.929   109.939  109.919    109.929  2797889  0.019720  0.000179  0.000182  99.999615  0.002791          0.8 -0.109519 -0.000660    0.0    -0.218667  0.000091      0.966330   0.000170   0.826677  5.367076e-05              0.0      2.736841e+08                  0.0
 2026-05-20   109.939   109.949  109.939    109.949  2390869  0.019740  0.000180  0.000182  99.999652  0.002882          1.0 -0.130861 -0.000537    0.0    -0.266149  0.000182      1.000000   0.000162   0.849655  9.976981e-06              0.0      2.733430e+08                  0.0
 2026-05-21   109.949   109.959  109.949    109.959  1960779  0.019045  0.000173  0.000091  99.999669  0.002800          1.0 -0.122433 -0.000591    0.0    -0.258713  0.000091      1.000000   0.000118   0.831316 -5.191044e-05              0.0      2.729425e+08                  0.0
 2026-05-22   109.999   109.999  109.979    109.979  1786457  0.020541  0.000187  0.000364  99.999700  0.002891          1.0 -0.148284 -0.000677    0.0    -0.307027  0.000182      0.934853   0.000136   0.741174 -2.552172e-05              0.0      2.724956e+08                  0.0
 2026-05-26   109.989   109.999  109.989    109.989  1892174  0.020503  0.000186  0.000182  99.999715  0.002708          1.0 -0.147291 -0.000673    0.0    -0.364689  0.000091      0.966330   0.000136   0.663481  1.816047e-05              0.0      2.721120e+08                  0.0
 2026-05-27   110.009   110.019  109.999    110.009  1482144  0.021181  0.000193  0.000273  99.999742  0.002798          1.0 -0.132801 -0.000634    0.0    -0.352820  0.000182      0.967427   0.000136   0.602967 -3.721512e-08              0.0      2.721120e+08                  0.0
 2026-05-28   110.009   110.029  110.009    110.019  2291672  0.021097  0.000192  0.000182  99.999754  0.002798          1.0 -0.152559 -0.000735    0.0    -0.344690  0.000091      0.967427   0.000136   0.616073 -3.720700e-08              0.0      2.719973e+08                  0.0
 2026-05-29   110.039   110.049  110.039    110.049  3235703  0.021733  0.000197  0.000273  99.999787  0.003072          1.0 -0.165995 -0.000541    0.0    -0.351862  0.000273      1.000000   0.000155   0.729587  1.813735e-05              0.0      2.719973e+08                  0.0
 2026-06-01   110.070   110.070  110.050    110.060  3124500  0.021680  0.000197  0.000191  99.999798  0.002989          1.0 -0.169809 -0.000552    0.0    -0.357333  0.000100      0.966667   0.000165   0.875387  2.904018e-05              0.0      2.721120e+08                  0.0
 2026-06-02   110.070   110.080  110.060    110.080  2389900  0.021560  0.000196  0.000182  99.999817  0.002915          1.0 -0.189585 -0.000664    0.0    -0.206562  0.000182      1.000000   0.000166   0.968856  1.176979e-05              0.0      2.719973e+08                  0.0
 2026-06-03   110.080   110.090  110.080    110.080  2075000  0.020735  0.000188  0.000091  99.999817  0.002733          0.8 -0.163884 -0.000271    0.0    -0.313910  0.000000      0.966667   0.000139   0.786359 -2.639171e-05              0.0      2.717571e+08                  0.0
 2026-06-04   110.100   110.100  110.090    110.090  2055400  0.020682  0.000188  0.000182  99.999826  0.002824          0.8 -0.181464 -0.000225    0.0    -0.313666  0.000091      0.966667   0.000093   0.600802 -7.362942e-05              0.0      2.715657e+08                  0.0
 2026-06-05   110.130   110.130  110.110    110.120  3581400  0.022062  0.000200  0.000363  99.999850  0.002914          0.8 -0.150903 -0.000513    0.0    -0.432637  0.000273      0.966667   0.000118   0.625597 -2.093889e-05              0.0      2.717571e+08                  0.0
 2026-06-08   110.120   110.130  110.120    110.130  2264000  0.021200  0.000193  0.000091  99.999857  0.002914          0.8 -0.140627 -0.000465    0.0    -0.455346  0.000091      1.000000   0.000127   0.745665  3.448437e-05              0.0      2.715657e+08                  0.0
 2026-06-09   110.130   110.140  110.130    110.140  3323600  0.020400  0.000185  0.000091  99.999864  0.002640          0.8 -0.138253 -0.000453    0.0    -0.420997  0.000091      1.000000   0.000145   0.988849  2.722362e-05              0.0      2.715657e+08                  0.0
 2026-06-10   110.140   110.150  110.140    110.150  2934900  0.019657  0.000178  0.000091  99.999871  0.002731          1.0 -0.110844 -0.000316    0.0    -0.420717  0.000091      1.000000   0.000127   1.045501 -2.061810e-08              0.0      2.717571e+08                  0.0
 2026-06-11   110.160   110.170  110.150    110.170  3584200  0.019682  0.000179  0.000182  99.999883  0.002822          1.0 -0.164117 -0.000598    0.0    -0.420681  0.000182      1.000000   0.000109   1.069873 -3.636112e-05              0.0      2.720249e+08                  0.0
 2026-06-12   110.190   110.200  110.190    110.200  2001200  0.020419  0.000185  0.000272  99.999899  0.003095          1.0 -0.183332 -0.000228    0.0    -0.286052  0.000272      1.000000   0.000154   1.062427  2.718407e-05              0.0      2.720249e+08                  0.0,
 'BIL':             Adj Open  Adj High  Adj Low  Adj Close    Volume       ATR      ATRP       TRP        RSI    Mom_21  Consistency     IR_63   Beta_63     DD_21  AutoCorr_15    Ret_1d  Range_Pos_20  Slope_P_5  Slope_V_5     Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount
 Date
 2026-05-01   91.1417   91.1417  91.1318    91.1318  14167678  0.020567  0.000226  0.000438  99.213762  0.002955          0.8 -0.062161 -0.001765  0.000000    -0.209912  0.000329      0.960177   0.000120   0.741498  1.093785e-05         0.019841      7.786871e+08                  0.0
 2026-05-04   91.1417   91.1517  91.1417    91.1517  10328010  0.020520  0.000225  0.000218  99.295959  0.002955          0.8 -0.047700 -0.001835  0.000000     0.084535  0.000218      1.000000   0.000175   0.929173  9.874447e-05         0.019841      7.786871e+08                  0.0
 2026-05-05   91.1617   91.1617  91.1517    91.1617   9812096  0.019768  0.000217  0.000110  99.333658  0.002846          0.8 -0.075081 -0.002117  0.000000     0.030679  0.000110      1.000000   0.000208   1.061125  8.776235e-05         0.019841      7.786871e+08                  0.0
 2026-05-06   91.1517   91.1617  91.1517    91.1517   8317911  0.019070  0.000209  0.000110  93.917827  0.002626          0.8 -0.105567 -0.002546 -0.000110     0.073772 -0.000110      0.958124   0.000142   0.622819 -3.272320e-05         0.019841      7.765752e+08                  0.0
 2026-05-07   91.1716   91.1716  91.1617    91.1716   8064467  0.019130  0.000210  0.000218  94.554143  0.002844          0.8 -0.122484 -0.003026  0.000000    -0.047309  0.000218      1.000000   0.000087   0.359178 -1.206251e-04         0.019841      7.765752e+08                  0.0
 2026-05-08   91.1916   91.2016  91.1916    91.1916   8067074  0.019906  0.000218  0.000329  95.108074  0.002955          0.8 -0.107004 -0.003719  0.000000     0.012949  0.000219      0.959823   0.000098   0.306681 -4.393559e-05         0.019841      7.765752e+08                  0.0
 2026-05-11   91.2115   91.2115  91.2016    91.2115   6168503  0.019906  0.000218  0.000218  95.588856  0.002845          0.8 -0.102408 -0.003612  0.000000     0.082488  0.000218      1.000000   0.000153   0.388230  6.566323e-05         0.019841      7.738748e+08                  0.0
 2026-05-12   91.2215   91.2215  91.2115    91.2215   7353681  0.019198  0.000210  0.000110  95.811620  0.002955          0.8 -0.104398 -0.003624  0.000000     0.063438  0.000110      1.000000   0.000197   0.647268  9.846029e-05         0.019841      7.693766e+08                  0.0

 # Section 8: Finviz Ingestion & Filtering

In [16]:
# Load latest updated Finviz dataset dynamically
def load_latest_finviz_parquet(data_dir: Path) -> pd.DataFrame:
    pattern = "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_df_finviz_merged_stocks_etfs.parquet"
    files = list(data_dir.glob(pattern))

    if not files:
        print(f"DEBUG: No files matching pattern found in {data_dir.absolute()}")
        return None

    latest_path = max(files, key=lambda x: x.name)
    print(f"DEBUG: Loading file: {latest_path.name}")

    try:
        return pd.read_parquet(latest_path)
    except Exception as e:
        print(f"DEBUG: Failed to read {latest_path.name}. Error: {e}")
        return None


# Load the file using the unified data_dir path
df_finviz = load_latest_finviz_parquet(data_dir)
print(
    f"df_finviz raw records shape: {df_finviz.shape if df_finviz is not None else None}"
)

DEBUG: Loading file: 2026-06-12_df_finviz_merged_stocks_etfs.parquet
df_finviz raw records shape: (1434, 139)

In [17]:
# Set test target tickers
target_tickers = ["GLW", "NOK", "DELL", "NVDA", "GOOG"]

In [18]:
# Clean index extraction using ast exception parsing if tickers are missing
try:
    result = df_finviz.loc[target_tickers]
except KeyError as e:
    error_msg = str(e)
    missing_str = error_msg.replace(" not in index", "").strip('"').strip("'")
    missing_tickers = ast.literal_eval(missing_str)

    print(f"Missing tickers: {missing_tickers}")

    # Strip out the missing symbols and retry slicing
    target_tickers_in_finviz = [t for t in target_tickers if t not in missing_tickers]
    result = df_finviz.loc[target_tickers_in_finviz].copy()
    result.sort_values(by="MktCap AUM, M", ascending=False, inplace=True)

print(f"result shape: {result.shape}")

result shape: (5, 139)

In [19]:
# Display filtered Finviz information and schema details
result.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, GLW to GOOG
Columns: 139 entries, No. to Omega 250d
dtypes: float64(120), int64(3), object(16)
memory usage: 5.5+ KB

In [20]:
# Check specific target column (Market Capitalization)
result["MktCap AUM, M"]

GLW      154230.0
NOK       82770.0
DELL     256370.0
NVDA    4965600.0
GOOG    4349630.0
Name: MktCap AUM, M, dtype: float64

In [21]:
# Sort records descendingly by Market Capitalization
result.sort_values(by="MktCap AUM, M", ascending=False, inplace=True)

In [22]:
# View final sorted DataFrame
print(result)

      No.                Company               Index                  Sector                        Industry  Country Exchange                                               Info  MktCap AUM, M  Rank  Market Cap, M    P/E  Fwd P/E   PEG    P/S    P/B    P/C   P/FCF  Book/sh  Cash/sh  Dividend %  Dividend TTM Dividend Ex Date  Payout Ratio %    EPS  EPS next Q  EPS this Y %  EPS next Y %  EPS past 5Y %  EPS next 5Y %  Sales past 5Y %  Sales Q/Q %  EPS Q/Q %  EPS YoY TTM %  Sales YoY TTM %  Sales, M  Income, M  EPS Surprise %  Revenue Surprise %  Outstanding, M  Float, M  Float %  Insider Own %  Insider Trans %  Inst Own %  Inst Trans %  Short Float %  Short Ratio  Short Interest, M  ROA %   ROE %  ROIC %  Curr R  Quick R  LTDebt/Eq  Debt/Eq  Gross M %  Oper M %  Profit M %  Perf 3D %  Perf Week %  Perf Month %  Perf Quart %  Perf Half %  Perf Year %  Perf YTD %  Beta    ATR  ATR/Price %  Volatility W %  Volatility M %  SMA20 %  SMA50 %  SMA200 %  50D High %  50D Low %  52W High %  52W Low %        52W Range  All-Time High %  All-Time Low %    RSI  Earnings   IPO Date Optionable Shortable  Employees  Change from Open %  Gap %  Recom  Avg Volume, M  Rel Volume     Volume  Target Price  Prev Close    Open    High     Low   Price  Change % Single Category Asset Type  Expense %  Holdings  AUM, M  Flows 1M, M  Flows% 1M  Flows 3M, M  Flows% 3M  Flows YTD, M  Flows% YTD  Return% 1Y  Return% 3Y  Return% 5Y Tags    Sharpe 3d    Sortino 3d     Omega 3d  Sharpe 5d  Sortino 5d  Omega 5d  Sharpe 10d  Sortino 10d  Omega 10d  Sharpe 15d  Sortino 15d  Omega 15d  Sharpe 30d  Sortino 30d  Omega 30d  Sharpe 60d  Sortino 60d  Omega 60d  Sharpe 120d  Sortino 120d  Omega 120d  Sharpe 250d  Sortino 250d  Omega 250d
NVDA    1            NVIDIA Corp  DJIA, NDX, S&P 500              Technology                  Semiconductors      USA     NASD                         Technology, Semiconductors      4965600.0     1      4965600.0  31.42      NaN  0.36  19.59  25.42  61.63   46.81     8.07     3.33        0.30          0.28         6/4/2026            0.82   6.53        2.07           NaN           NaN            NaN            NaN              NaN        85.23     213.42         109.57            70.68  253490.0  159610.00            6.52                3.43         24220.0  23210.00    95.83           4.09            -0.30       69.19          0.00           1.23         1.72             284.72  82.97  114.29   77.17    3.44     2.85       0.06     0.07      74.15     64.02       62.97  -1.440991         0.04         -9.14         13.84        11.65        41.51       10.02  2.20   8.03     3.913446            3.34            3.58    -4.39    -0.83      8.42      -13.25      19.74      -13.25      45.67  140.85 - 236.54           -13.25       615469.98  45.24  May 20/a  1/22/1999        Yes       Yes    42000.0                0.16   0.00   1.25         165.96        0.67  110617988        309.93      204.87  204.87  207.07  203.44  205.19      0.16                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    -    12.751155  21108.814573  1881.522666  -2.625986   -3.455458  0.589202   -5.108816    -5.554168   0.411260   -1.615763    -2.194244   0.750267    0.800342     1.207868   1.143178    1.562125     2.410530   1.292462     0.794159      1.182428    1.140991     1.073072      1.596357    1.192306
GOOG    3           Alphabet Inc        NDX, S&P 500  Communication Services  Internet Content & Information      USA     NASD  Communication Services, Internet Content & Inf...      4349630.0     2      4349630.0  27.32      NaN  1.45  10.28   9.06  34.29   67.51    39.51    10.44        0.24          0.85         6/8/2026            7.68  13.11        2.88           NaN           NaN            NaN            NaN              NaN        22.34      81.96          46.22            17.77  423170.0  160210.00           90.44                2.74          5460.0   5070.00    92.88          58.18            -0.03       27.26          0.00           0.89         2.21              45.22  27.17   38.88   28.04    1.92     1.92       0.19     0.20      60.43     33.63       37.86  -1.139971        -2.08        -10.24         18.81        11.58       102.38       14.14  1.24  10.69     2.984700            3.40            2.64    -4.04    -0.37     16.47      -11.45      24.55      -11.45     119.29  163.33 - 404.47           -11.45         1373.23  43.44  Apr 29/a  3/27/2014        Yes       Yes   190820.0               -0.78   1.24   1.39          20.42        0.84   17217333        434.23      356.56  360.98  364.77  353.34  358.16      0.45                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    -    31.976652  21108.814573  1881.522666  -2.226388   -2.750744  0.653439   -3.111539    -4.154357   0.586358   -3.394329    -4.302530   0.558494   -2.076404    -2.902654   0.698898    1.945148     3.740423   1.436132     1.092105      1.927787    1.218772     2.468660      4.642997    1.550911
DELL   54  Dell Technologies Inc             S&P 500              Technology               Computer Hardware      USA     NYSE                      Technology, Computer Hardware       256370.0    59       256370.0  31.43      NaN  0.52   1.91    NaN  21.81   27.15    -2.16    18.13        0.63          2.21        4/21/2026           24.20  12.58        4.70           NaN           NaN            NaN            NaN              NaN        87.49     281.26          99.71            38.87  134190.0    8410.00           64.09               22.66           324.0    301.12    92.94          53.54            -2.61       39.86         -2.26           6.30         2.09              18.96   8.33     NaN   37.04    0.95     0.74        NaN      NaN      19.09      8.57        6.27   3.612028         0.30         62.21        160.90       181.28       248.83      214.24  1.32  27.83     7.035417            8.43            7.05    14.12    50.00    135.53      -15.74     140.09      -15.74     262.34  109.17 - 469.47           -15.74         3257.21  64.53  May 28/a  8/17/2016        Yes       Yes    97000.0                2.77  -1.67   1.73           9.06        0.67    6038044        496.76      391.45  384.91  408.38  381.11  395.57      1.05                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    -    16.079981  21108.814573  1881.522666  -0.866007   -1.438957  0.869178   -6.597181    -7.272265   0.356616    3.979158    13.022684   2.436958    4.819647    15.341999   2.724416    4.433529    12.513033   2.457306     3.259323      7.893770    1.971200     2.184498      4.460445    1.548005
GLW    98            Corning Inc             S&P 500              Technology           Electronic Components      USA     NYSE                  Technology, Electronic Components       154230.0   109       154230.0  86.01      NaN  1.37   9.45  13.76  86.69  102.82    13.02     2.07        0.66          1.12        5/29/2026           61.12   2.08        0.75           NaN           NaN            NaN            NaN              NaN        20.05     134.97         298.15            20.05   16320.0    1810.00            1.19                1.09           907.0    788.07    86.89           8.43            -0.75       72.85         -1.66           2.71         1.67              21.39   6.17   16.07    8.88    1.61     1.06       0.73     0.84      35.64     16.13       11.09   3.024031         0.91        -13.22         38.79        90.23       252.62      104.66  1.16  13.55     7.561384            7.14            6.52    -3.20     1.45     51.54      -15.39      31.43      -15.39     262.24   49.47 - 211.79           -15.39        16190.91  48.83  Apr 28/b  5/21/1945        Yes       Yes    67200.0                0.67   0.82   1.90          12.80        0.70    8918702        205.00      176.55  178.00  180.77  173.41  179.20      1.50                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    -    20.799995  21108.814573  1881.522666  -3.065982   -4.118234  0.608663    0.809433     1.327089   1.146499   -1.143596    -1.748877   0.820056    1.599392     2.671706   1.310670    1.910240     3.108962   1.372537     2.378506      4.013454    1.501481     2.488573      4.146600    1.586085
NOK   192         Nokia Corp ADR                   -              Technology         Communication Equipment  Finland     NYSE                Technology, Communication Equipment        82770.0   220        82770.0  92.33      NaN  2.02   3.57   3.39  12.32   50.57     4.36     1.20        1.19          0.16        4/28/2026             NaN   0.16        0.06           NaN           NaN            NaN            NaN              NaN        13.95     253.04           9.07            12.83   23200.0     898.25           33.18               -1.18          5590.0   5590.00   100.00           0.00              NaN       16.43          2.28           1.19         0.65              66.37   2.10    3.84    3.21    1.57     1.32       0.15     0.16      43.47      8.78        3.87   6.859206         2.92          0.61         79.61       137.94       178.20      128.75  1.16   1.02     6.891892            6.43            6.37    -0.82    15.93     84.85      -15.19      83.40      -15.19     270.00     4.00 - 17.45           -75.27         1099.21  53.54  Apr 23/b   7/1/1994        Yes       Yes        NaN                3.64   1.35   2.35         102.88        1.12  114798400         12.33       14.09   14.28   15.07   14.23   14.80      5.04                                   NaN       NaN     NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN    -  1034.367515  21108.814573  1881.522666   1.326859    2.368217  1.215943   -2.377430    -2.845996   0.657156   -0.444466    -0.613304   0.930725    1.433481     2.298185   1.260921    3.634267     6.374776   1.820623     3.139349      5.344355    1.712557     2.156037      3.824189    1.519565

In [23]:
# Export processed dataframe output directly to trash file
result.to_csv(output_dir / "_trash.csv")