# I. Initialization & Environment Setup

In [1]:
import time

_nb_start_time = time.perf_counter()

In [2]:
# 1. Setup & Path
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
from pathlib import Path

from core.settings import TradingConfig
from core.contracts import EngineInput, FilterPack
from core.utils import SystemUtils as SU

# Vertical slice imports
from data_pipeline import generate_features
from walk_forward import AlphaEngine, create_walk_forward_analyzer, run_headless_simulation

config = TradingConfig()

NOTEBOOKS_RLVR_ROOT: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2

OUTPUT_DIR: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\output

In [3]:
# 2. Path Settings
PROCESSED_DATA_DIR = Path(
    r"C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\data\processed"
)
OUTPUT_DIR = Path(
    r"C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\output"
)
DATA_DIR = Path(r"C:\Users\ping\Files_win10\python\py311\stocks\data")
DATA_PATH_OHLCV = DATA_DIR / "df_OHLCV_stocks_etfs.parquet"
DATA_PATH_INDICES = DATA_DIR / "df_indices.parquet"

print(f"PROCESSED_DATA_DIR: {PROCESSED_DATA_DIR}")
print(f"OUTPUT_DIR: {OUTPUT_DIR}")
print(f"DATA_DIR: {DATA_DIR}")
print(f"DATA_PATH_OHLCV: {DATA_PATH_OHLCV}")
print(f"DATA_PATH_INDICES: {DATA_PATH_INDICES}")

PROCESSED_DATA_DIR: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\data\processed
OUTPUT_DIR: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\output
DATA_DIR: C:\Users\ping\Files_win10\python\py311\stocks\data
DATA_PATH_OHLCV: C:\Users\ping\Files_win10\python\py311\stocks\data\df_OHLCV_stocks_etfs.parquet
DATA_PATH_INDICES: C:\Users\ping\Files_win10\python\py311\stocks\data\df_indices.parquet

# II. Data Pipeline
Choose to either reload features quickly from Parquet cache or run the ~6-minute feature generation process.

### Option A: Reload Existing Features from Parquet (Quick)

In [4]:
features_df = pd.read_parquet(PROCESSED_DATA_DIR / "features_df.parquet")
macro_df = pd.read_parquet(PROCESSED_DATA_DIR / "macro_df.parquet")
df_close_wide = pd.read_parquet(PROCESSED_DATA_DIR / "df_close_wide.parquet")
df_atrp_wide = pd.read_parquet(PROCESSED_DATA_DIR / "df_atrp_wide.parquet")
df_trp_wide = pd.read_parquet(PROCESSED_DATA_DIR / "df_trp_wide.parquet")

df_indices = pd.read_parquet(DATA_PATH_INDICES, engine="pyarrow")
df_ohlcv = pd.read_parquet(DATA_PATH_OHLCV, engine="pyarrow")
df_fed = pd.read_parquet(
    DATA_DIR / "High_Yield_Spread_T10Y2Y_Spread.parquet",
    engine="pyarrow",
)
print("✅ Cached Data Reloaded.")

✅ Cached Data Reloaded.

### Option B: Re-generate All Features (Slow)

In [5]:
# print("⏳ Loading DataFrames... takes ~6 minutes")
# df_indices = pd.read_parquet(DATA_PATH_INDICES, engine="pyarrow")
# df_ohlcv = pd.read_parquet(DATA_PATH_OHLCV, engine="pyarrow")
# df_fed = pd.read_parquet(
#     DATA_DIR / "High_Yield_Spread_T10Y2Y_Spread.parquet", engine="pyarrow"
# )

# print("⚡ Generating Features... takes about 6 minutes")
# features_df, macro_df = generate_features(
#     df_ohlcv=df_ohlcv,
#     df_indices=df_indices,
#     df_fed=df_fed,
#     config=config,
# )

# print("🚀 Unstacking Wide Matrices...")
# df_close_wide = df_ohlcv["Adj Close"].unstack(level=0)
# df_atrp_wide = features_df["ATRP"].unstack(level=0).reindex_like(df_close_wide)
# df_trp_wide = features_df["TRP"].unstack(level=0).reindex_like(df_close_wide)

# if config.handle_zeros_as_nan:
#     df_close_wide = df_close_wide.replace(0, np.nan)

# df_close_wide = df_close_wide.ffill(limit=config.max_data_gap_ffill)
# df_close_wide = df_close_wide.fillna(config.nan_price_replacement)

# print(
#     f"✅ Pipeline Complete. Tickers: {len(df_close_wide.columns)}, Days: {len(df_close_wide)}"
# )

In [6]:
# # Optional: Save the freshly generated datasets to the correct processed directory
# PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

# features_df.to_parquet(PROCESSED_DATA_DIR / "features_df.parquet")
# macro_df.to_parquet(PROCESSED_DATA_DIR / "macro_df.parquet")
# df_close_wide.to_parquet(PROCESSED_DATA_DIR / "df_close_wide.parquet")
# df_atrp_wide.to_parquet(PROCESSED_DATA_DIR / "df_atrp_wide.parquet")
# df_trp_wide.to_parquet(PROCESSED_DATA_DIR / "df_trp_wide.parquet")

# print("💾 Processed Data Cached Successfully.")

# III. Walk-Forward Performance Engine

In [7]:
engine = AlphaEngine(
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    macro_df=macro_df,
    df_close_wide=df_close_wide,
    df_atrp_wide=df_atrp_wide,
    df_trp_wide=df_trp_wide,
)
print("🎯 Master AlphaEngine Ready.")

🎯 Master AlphaEngine Ready.

In [ ]:
_inputs = EngineInput(
    mode="Ranking",
    decision_date=pd.Timestamp("2026-05-01"),
    lookback_period=10,
    holding_period=5,
    metric="Sharpe (TRP)",
    benchmark_ticker=config.benchmark_ticker,
    rank_start=1,
    rank_end=200,
    debug=False,
)

analyzer1, stage1_pack = create_walk_forward_analyzer(
    engine, _inputs, universe_subset=None
)
analyzer1.show()

VBox(children=(HTML(value='<b>1. Timeline Configuration:</b> (Past <--- Decision ---> Future)'), HBox(children…

In [9]:
result = SU.map_analyzer(analyzer=analyzer1)
SU.list_analyzer_paths(result)

====================================================================
[SEARCH] ANALYZER SIMULATION MAP
====================================================================
[  0] [DATA] audit_pack (EngineOutput)
[  1]   [PLOT] portfolio_series (shape=(17,))
[  2]   [PLOT] benchmark_series (shape=(17,))
[  3]   [CALC] normalized_plot_data (shape=(17, 200))
[  4]   [FILE] tickers (len=200)
[  5]     [DOC] index_0 (str)
[  6]     [DOC] index_1 (str)
[  7]     [DOC] index_2 (str)
[  8]     [DOC] index_3 (str)
[  9]     [DOC] index_4 (str)
[ 10]     [DOC] index_5 (str)
[ 11]     [DOC] index_6 (str)
[ 12]     [DOC] index_7 (str)
[ 13]     [DOC] index_8 (str)
[ 14]     [DOC] index_9 (str)
[ 15]     [DOC] index_10 (str)
[ 16]     [DOC] index_11 (str)
[ 17]     [DOC] index_12 (str)
[ 18]     [DOC] index_13 (str)
[ 19]     [DOC] index_14 (str)
[ 20]     [DOC] index_15 (str)
[ 21]     [DOC] index_16 (str)
[ 22]     [DOC] index_17 (str)
[ 23]     [DOC] index_18 (str)
[ 24]     [DOC] index_19 (str)
[ 25]     [DOC] index_20 (str)
[ 26]     [DOC] index_21 (str)
[ 27]     [DOC] index_22 (str)
[ 28]     [DOC] index_23 (str)
[ 29]     [DOC] index_24 (str)
[ 30]     [DOC] index_25 (str)
[ 31]     [DOC] index_26 (str)
[ 32]     [DOC] index_27 (str)
[ 33]     [DOC] index_28 (str)
[ 34]     [DOC] index_29 (str)
[ 35]     [DOC] index_30 (str)
[ 36]     [DOC] index_31 (str)
[ 37]     [DOC] index_32 (str)
[ 38]     [DOC] index_33 (str)
[ 39]     [DOC] index_34 (str)
[ 40]     [DOC] index_35 (str)
[ 41]     [DOC] index_36 (str)
[ 42]     [DOC] index_37 (str)
[ 43]     [DOC] index_38 (str)
[ 44]     [DOC] index_39 (str)
[ 45]     [DOC] index_40 (str)
[ 46]     [DOC] index_41 (str)
[ 47]     [DOC] index_42 (str)
[ 48]     [DOC] index_43 (str)
[ 49]     [DOC] index_44 (str)
[ 50]     [DOC] index_45 (str)
[ 51]     [DOC] index_46 (str)
[ 52]     [DOC] index_47 (str)
[ 53]     [DOC] index_48 (str)
[ 54]     [DOC] index_49 (str)
[ 55]     [DOC] index_50 (str)
[ 56]     [DOC] index_51 (str)
[ 57]     [DOC] index_52 (str)
[ 58]     [DOC] index_53 (str)
[ 59]     [DOC] index_54 (str)
[ 60]     [DOC] index_55 (str)
[ 61]     [DOC] index_56 (str)
[ 62]     [DOC] index_57 (str)
[ 63]     [DOC] index_58 (str)
[ 64]     [DOC] index_59 (str)
[ 65]     [DOC] index_60 (str)
[ 66]     [DOC] index_61 (str)
[ 67]     [DOC] index_62 (str)
[ 68]     [DOC] index_63 (str)
[ 69]     [DOC] index_64 (str)
[ 70]     [DOC] index_65 (str)
[ 71]     [DOC] index_66 (str)
[ 72]     [DOC] index_67 (str)
[ 73]     [DOC] index_68 (str)
[ 74]     [DOC] index_69 (str)
[ 75]     [DOC] index_70 (str)
[ 76]     [DOC] index_71 (str)
[ 77]     [DOC] index_72 (str)
[ 78]     [DOC] index_73 (str)
[ 79]     [DOC] index_74 (str)
[ 80]     [DOC] index_75 (str)
[ 81]     [DOC] index_76 (str)
[ 82]     [DOC] index_77 (str)
[ 83]     [DOC] index_78 (str)
[ 84]     [DOC] index_79 (str)
[ 85]     [DOC] index_80 (str)
[ 86]     [DOC] index_81 (str)
[ 87]     [DOC] index_82 (str)
[ 88]     [DOC] index_83 (str)
[ 89]     [DOC] index_84 (str)
[ 90]     [DOC] index_85 (str)
[ 91]     [DOC] index_86 (str)
[ 92]     [DOC] index_87 (str)
[ 93]     [DOC] index_88 (str)
[ 94]     [DOC] index_89 (str)
[ 95]     [DOC] index_90 (str)
[ 96]     [DOC] index_91 (str)
[ 97]     [DOC] index_92 (str)
[ 98]     [DOC] index_93 (str)
[ 99]     [DOC] index_94 (str)
[100]     [DOC] index_95 (str)
[101]     [DOC] index_96 (str)
[102]     [DOC] index_97 (str)
[103]     [DOC] index_98 (str)
[104]     [DOC] index_99 (str)
[105]     [DOC] index_100 (str)
[106]     [DOC] index_101 (str)
[107]     [DOC] index_102 (str)
[108]     [DOC] index_103 (str)
[109]     [DOC] index_104 (str)
[110]     [DOC] index_105 (str)
[111]     [DOC] index_106 (str)
[112]     [DOC] index_107 (str)
[113]     [DOC] index_108 (str)
[114]     [DOC] index_109 (str)
[115]     [DOC] index_110 (str)
[116]     [DOC] index_111 (str)
[117]     [DOC] index_112 (str)
[118]     [DOC] index_113 (str)
[119]     [DOC] index_114 (str)
[120]     [DOC] index_115 (str)
[121]     [DOC] index_116 (str)
[122]     [DOC] index_117 (str)
[123]     [DOC] index_118 (str)
[124]     [DOC] index_119 (str)
[125]     [DOC] index_120 (str)
[126]     [DOC] index_121 (str)
[127]     [DOC] index_122 (str)
[128]     [DOC] index_123 (str)
[129]     [DOC] index_124 (str)
[130]     [DOC] index_125 (str)
[131]     [DOC] index_126 (str)
[132]     [DOC] index_127 (str)
[133]     [DOC] index_128 (str)
[134]     [DOC] index_129 (str)
[135]     [DOC] index_130 (str)
[136]     [DOC] index_131 (str)
[137]     [DOC] index_132 (str)
[138]     [DOC] index_133 (str)
[139]     [DOC] index_134 (str)
[140]     [DOC] index_135 (str)
[141]     [DOC] index_136 (str)
[142]     [DOC] index_137 (str)
[143]     [DOC] index_138 (str)
[144]     [DOC] index_139 (str)
[145]     [DOC] index_140 (str)
[146]     [DOC] index_141 (str)
[147]     [DOC] index_142 (str)
[148]     [DOC] index_143 (str)
[149]     [DOC] index_144 (str)
[150]     [DOC] index_145 (str)
[151]     [DOC] index_146 (str)
[152]     [DOC] index_147 (str)
[153]     [DOC] index_148 (str)
[154]     [DOC] index_149 (str)
[155]     [DOC] index_150 (str)
[156]     [DOC] index_151 (str)
[157]     [DOC] index_152 (str)
[158]     [DOC] index_153 (str)
[159]     [DOC] index_154 (str)
[160]     [DOC] index_155 (str)
[161]     [DOC] index_156 (str)
[162]     [DOC] index_157 (str)
[163]     [DOC] index_158 (str)
[164]     [DOC] index_159 (str)
[165]     [DOC] index_160 (str)
[166]     [DOC] index_161 (str)
[167]     [DOC] index_162 (str)
[168]     [DOC] index_163 (str)
[169]     [DOC] index_164 (str)
[170]     [DOC] index_165 (str)
[171]     [DOC] index_166 (str)
[172]     [DOC] index_167 (str)
[173]     [DOC] index_168 (str)
[174]     [DOC] index_169 (str)
[175]     [DOC] index_170 (str)
[176]     [DOC] index_171 (str)
[177]     [DOC] index_172 (str)
[178]     [DOC] index_173 (str)
[179]     [DOC] index_174 (str)
[180]     [DOC] index_175 (str)
[181]     [DOC] index_176 (str)
[182]     [DOC] index_177 (str)
[183]     [DOC] index_178 (str)
[184]     [DOC] index_179 (str)
[185]     [DOC] index_180 (str)
[186]     [DOC] index_181 (str)
[187]     [DOC] index_182 (str)
[188]     [DOC] index_183 (str)
[189]     [DOC] index_184 (str)
[190]     [DOC] index_185 (str)
[191]     [DOC] index_186 (str)
[192]     [DOC] index_187 (str)
[193]     [DOC] index_188 (str)
[194]     [DOC] index_189 (str)
[195]     [DOC] index_190 (str)
[196]     [DOC] index_191 (str)
[197]     [DOC] index_192 (str)
[198]     [DOC] index_193 (str)
[199]     [DOC] index_194 (str)
[200]     [DOC] index_195 (str)
[201]     [DOC] index_196 (str)
[202]     [DOC] index_197 (str)
[203]     [DOC] index_198 (str)
[204]     [DOC] index_199 (str)
[205]   [PLOT] initial_weights (shape=(200,))
[206]   [FILE] perf_metrics (len=24)
[207]     [NUM] full_p_gain (float)
[208]     [NUM] full_p_sharpe (shape=())
[209]     [NUM] full_p_sharpe_atrp (float)
[210]     [NUM] full_p_sharpe_trp (float)
[211]     [NUM] lookback_p_gain (float)
[212]     [NUM] lookback_p_sharpe (shape=())
[213]     [NUM] lookback_p_sharpe_atrp (float)
[214]     [NUM] lookback_p_sharpe_trp (float)
[215]     [NUM] holding_p_gain (float)
[216]     [NUM] holding_p_sharpe (shape=())
[217]     [NUM] holding_p_sharpe_atrp (float)
[218]     [NUM] holding_p_sharpe_trp (float)
[219]     [NUM] full_b_gain (float)
[220]     [NUM] full_b_sharpe (shape=())
[221]     [NUM] full_b_sharpe_atrp (float)
[222]     [NUM] full_b_sharpe_trp (float)
[223]     [NUM] lookback_b_gain (float)
[224]     [NUM] lookback_b_sharpe (shape=())
[225]     [NUM] lookback_b_sharpe_atrp (float)
[226]     [NUM] lookback_b_sharpe_trp (float)
[227]     [NUM] holding_b_gain (float)
[228]     [NUM] holding_b_sharpe (shape=())
[229]     [NUM] holding_b_sharpe_atrp (float)
[230]     [NUM] holding_b_sharpe_trp (float)
[231]   [CALC] results_df (shape=(200, 2))
[232]   [DATE] start_date (Timestamp)
[233]   [DATE] decision_date (Timestamp)
[234]   [DATE] buy_date (Timestamp)
[235]   [DATE] holding_end_date (Timestamp)
[236]   [PLOT] portfolio_atrp_series (shape=(17,))
[237]   [PLOT] benchmark_atrp_series (shape=(17,))
[238]   [PLOT] portfolio_trp_series (shape=(17,))
[239]   [PLOT] benchmark_trp_series (shape=(17,))
[240]   [DOC] error_msg (NoneType)
[241]   [FILE] debug_data (len=8)
[242]     [FILE] audit_liquidity (len=6)
                +-- date --> [See ID 233]
[243]       [NUM] total_tickers_available (int)
[244]       [NUM] percentile_setting (float)
[245]       [NUM] final_cutoff_usd (shape=())
[246]       [DOC] tickers_passed (shape=())
[247]       [CALC] universe_snapshot (shape=(1577, 19))
[248]     [CALC] full_universe_ranking (shape=(943, 16))
[249]     [FILE] meta (len=4)
[250]       [NUM] dropped_count (int)
[251]       [FILE] dropped_tickers (len=0)
[252]       [NUM] clean_count (int)
[253]       [DOC] selection_range (str)
[254]     [DATA] inputs_snapshot (EngineInput)
[255]       [DOC] mode (str)
[256]       [DATE] decision_date (Timestamp)
[257]       [NUM] lookback_period (int)
[258]       [NUM] holding_period (int)
[259]       [DOC] metric (str)
[260]       [DOC] benchmark_ticker (str)
[261]       [NUM] rank_start (int)
[262]       [NUM] rank_end (int)
[263]       [DATA] quality_thresholds (QualityThresholds)
[264]         [NUM] min_median_dollar_volume (int)
[265]         [NUM] min_liquidity_percentile (float)
[266]         [NUM] max_stale_pct (float)
[267]         [NUM] max_same_vol_count (int)
[268]       [FILE] manual_tickers (len=0)
[269]       [NUM] debug (bool)
[270]       [DOC] universe_subset (NoneType)
[271]     [FILE] verification (len=2)
[272]       [FILE] p (len=4)
                  +-- val --> [See ID 1]
[273]         [PLOT] ret (shape=(17,))
                  +-- atrp --> [See ID 236]
                  +-- trp --> [See ID 238]
[274]       [FILE] b (len=4)
                  +-- val --> [See ID 2]
[275]         [PLOT] ret (shape=(17,))
                  +-- atrp --> [See ID 237]
                  +-- trp --> [See ID 239]
[276]     [FILE] portfolio_raw_components (len=4)
[277]       [CALC] prices (shape=(17, 200))
[278]       [CALC] atrp (shape=(17, 200))
[279]       [CALC] trp (shape=(17, 200))
[280]       [CALC] ohlcv_raw (shape=(3400, 5))
[281]     [FILE] benchmark_raw_components (len=4)
[282]       [CALC] prices (shape=(17, 1))
[283]       [CALC] atrp (shape=(17, 1))
[284]       [CALC] trp (shape=(17, 1))
[285]       [CALC] ohlcv_raw (shape=(17, 5))
              +-- selection_audit --> [See ID 248]
[286]   [CALC] macro_df (shape=(16214, 11))
[287]   [DOC] alpha_perception (NoneType)
NAME                      | PATH
--------------------------------------------------------------------------------
audit_pack                | audit_pack
portfolio_series          | audit_pack -> portfolio_series
benchmark_series          | audit_pack -> benchmark_series
normalized_plot_data      | audit_pack -> normalized_plot_data
tickers                   | audit_pack -> tickers
index_0                   | audit_pack -> tickers -> index_0
index_1                   | audit_pack -> tickers -> index_1
index_2                   | audit_pack -> tickers -> index_2
index_3                   | audit_pack -> tickers -> index_3
index_4                   | audit_pack -> tickers -> index_4
index_5                   | audit_pack -> tickers -> index_5
index_6                   | audit_pack -> tickers -> index_6
index_7                   | audit_pack -> tickers -> index_7
index_8                   | audit_pack -> tickers -> index_8
index_9                   | audit_pack -> tickers -> index_9
index_10                  | audit_pack -> tickers -> index_10
index_11                  | audit_pack -> tickers -> index_11
index_12                  | audit_pack -> tickers -> index_12
index_13                  | audit_pack -> tickers -> index_13
index_14                  | audit_pack -> tickers -> index_14
index_15                  | audit_pack -> tickers -> index_15
index_16                  | audit_pack -> tickers -> index_16
index_17                  | audit_pack -> tickers -> index_17
index_18                  | audit_pack -> tickers -> index_18
index_19                  | audit_pack -> tickers -> index_19
index_20                  | audit_pack -> tickers -> index_20
index_21                  | audit_pack -> tickers -> index_21
index_22                  | audit_pack -> tickers -> index_22
index_23                  | audit_pack -> tickers -> index_23
index_24                  | audit_pack -> tickers -> index_24
index_25                  | audit_pack -> tickers -> index_25
index_26                  | audit_pack -> tickers -> index_26
index_27                  | audit_pack -> tickers -> index_27
index_28                  | audit_pack -> tickers -> index_28
index_29                  | audit_pack -> tickers -> index_29
index_30                  | audit_pack -> tickers -> index_30
index_31                  | audit_pack -> tickers -> index_31
index_32                  | audit_pack -> tickers -> index_32
index_33                  | audit_pack -> tickers -> index_33
index_34                  | audit_pack -> tickers -> index_34
index_35                  | audit_pack -> tickers -> index_35
index_36                  | audit_pack -> tickers -> index_36
index_37                  | audit_pack -> tickers -> index_37
index_38                  | audit_pack -> tickers -> index_38
index_39                  | audit_pack -> tickers -> index_39
index_40                  | audit_pack -> tickers -> index_40
index_41                  | audit_pack -> tickers -> index_41
index_42                  | audit_pack -> tickers -> index_42
index_43                  | audit_pack -> tickers -> index_43
index_44                  | audit_pack -> tickers -> index_44
index_45                  | audit_pack -> tickers -> index_45
index_46                  | audit_pack -> tickers -> index_46
index_47                  | audit_pack -> tickers -> index_47
index_48                  | audit_pack -> tickers -> index_48
index_49                  | audit_pack -> tickers -> index_49
index_50                  | audit_pack -> tickers -> index_50
index_51                  | audit_pack -> tickers -> index_51
index_52                  | audit_pack -> tickers -> index_52
index_53                  | audit_pack -> tickers -> index_53
index_54                  | audit_pack -> tickers -> index_54
index_55                  | audit_pack -> tickers -> index_55
index_56                  | audit_pack -> tickers -> index_56
index_57                  | audit_pack -> tickers -> index_57
index_58                  | audit_pack -> tickers -> index_58
index_59                  | audit_pack -> tickers -> index_59
index_60                  | audit_pack -> tickers -> index_60
index_61                  | audit_pack -> tickers -> index_61
index_62                  | audit_pack -> tickers -> index_62
index_63                  | audit_pack -> tickers -> index_63
index_64                  | audit_pack -> tickers -> index_64
index_65                  | audit_pack -> tickers -> index_65
index_66                  | audit_pack -> tickers -> index_66
index_67                  | audit_pack -> tickers -> index_67
index_68                  | audit_pack -> tickers -> index_68
index_69                  | audit_pack -> tickers -> index_69
index_70                  | audit_pack -> tickers -> index_70
index_71                  | audit_pack -> tickers -> index_71
index_72                  | audit_pack -> tickers -> index_72
index_73                  | audit_pack -> tickers -> index_73
index_74                  | audit_pack -> tickers -> index_74
index_75                  | audit_pack -> tickers -> index_75
index_76                  | audit_pack -> tickers -> index_76
index_77                  | audit_pack -> tickers -> index_77
index_78                  | audit_pack -> tickers -> index_78
index_79                  | audit_pack -> tickers -> index_79
index_80                  | audit_pack -> tickers -> index_80
index_81                  | audit_pack -> tickers -> index_81
index_82                  | audit_pack -> tickers -> index_82
index_83                  | audit_pack -> tickers -> index_83
index_84                  | audit_pack -> tickers -> index_84
index_85                  | audit_pack -> tickers -> index_85
index_86                  | audit_pack -> tickers -> index_86
index_87                  | audit_pack -> tickers -> index_87
index_88                  | audit_pack -> tickers -> index_88
index_89                  | audit_pack -> tickers -> index_89
index_90                  | audit_pack -> tickers -> index_90
index_91                  | audit_pack -> tickers -> index_91
index_92                  | audit_pack -> tickers -> index_92
index_93                  | audit_pack -> tickers -> index_93
index_94                  | audit_pack -> tickers -> index_94
index_95                  | audit_pack -> tickers -> index_95
index_96                  | audit_pack -> tickers -> index_96
index_97                  | audit_pack -> tickers -> index_97
index_98                  | audit_pack -> tickers -> index_98
index_99                  | audit_pack -> tickers -> index_99
index_100                 | audit_pack -> tickers -> index_100
index_101                 | audit_pack -> tickers -> index_101
index_102                 | audit_pack -> tickers -> index_102
index_103                 | audit_pack -> tickers -> index_103
index_104                 | audit_pack -> tickers -> index_104
index_105                 | audit_pack -> tickers -> index_105
index_106                 | audit_pack -> tickers -> index_106
index_107                 | audit_pack -> tickers -> index_107
index_108                 | audit_pack -> tickers -> index_108
index_109                 | audit_pack -> tickers -> index_109
index_110                 | audit_pack -> tickers -> index_110
index_111                 | audit_pack -> tickers -> index_111
index_112                 | audit_pack -> tickers -> index_112
index_113                 | audit_pack -> tickers -> index_113
index_114                 | audit_pack -> tickers -> index_114
index_115                 | audit_pack -> tickers -> index_115
index_116                 | audit_pack -> tickers -> index_116
index_117                 | audit_pack -> tickers -> index_117
index_118                 | audit_pack -> tickers -> index_118
index_119                 | audit_pack -> tickers -> index_119
index_120                 | audit_pack -> tickers -> index_120
index_121                 | audit_pack -> tickers -> index_121
index_122                 | audit_pack -> tickers -> index_122
index_123                 | audit_pack -> tickers -> index_123
index_124                 | audit_pack -> tickers -> index_124
index_125                 | audit_pack -> tickers -> index_125
index_126                 | audit_pack -> tickers -> index_126
index_127                 | audit_pack -> tickers -> index_127
index_128                 | audit_pack -> tickers -> index_128
index_129                 | audit_pack -> tickers -> index_129
index_130                 | audit_pack -> tickers -> index_130
index_131                 | audit_pack -> tickers -> index_131
index_132                 | audit_pack -> tickers -> index_132
index_133                 | audit_pack -> tickers -> index_133
index_134                 | audit_pack -> tickers -> index_134
index_135                 | audit_pack -> tickers -> index_135
index_136                 | audit_pack -> tickers -> index_136
index_137                 | audit_pack -> tickers -> index_137
index_138                 | audit_pack -> tickers -> index_138
index_139                 | audit_pack -> tickers -> index_139
index_140                 | audit_pack -> tickers -> index_140
index_141                 | audit_pack -> tickers -> index_141
index_142                 | audit_pack -> tickers -> index_142
index_143                 | audit_pack -> tickers -> index_143
index_144                 | audit_pack -> tickers -> index_144

In [10]:
# fetch by id
print(f"fetch by id=1:\not{SU.fetch(1, result)}\n")

# fetch by name
print(f'fetch by name = "portfolio_series":\n{SU.fetch("portfolio_series", result)}')

 ============================================================
 [INFO] INDEX: [1]
 [LABEL] NAME:  portfolio_series
 [FILE] PATH:  audit_pack -> portfolio_series
 ============================================================

Date
2026-04-17    1.000000
2026-04-20    1.010604
2026-04-21    1.016630
2026-04-22    1.030356
2026-04-23    1.039983
2026-04-24    1.052968
2026-04-27    1.053197
2026-04-28    1.048946
2026-04-29    1.069061
2026-04-30    1.092390
2026-05-01    1.103319
2026-05-04    1.105369
2026-05-05    1.125884
2026-05-06    1.133777
2026-05-07    1.119758
2026-05-08    1.137621
2026-05-11    1.154806
dtype: float64

fetch by id=1:
otDate
2026-04-17    1.000000
2026-04-20    1.010604
2026-04-21    1.016630
2026-04-22    1.030356
2026-04-23    1.039983
2026-04-24    1.052968
2026-04-27    1.053197
2026-04-28    1.048946
2026-04-29    1.069061
2026-04-30    1.092390
2026-05-01    1.103319
2026-05-04    1.105369
2026-05-05    1.125884
2026-05-06    1.133777
2026-05-07    1.119758
2026-05-08    1.137621
2026-05-11    1.154806
dtype: float64

 ============================================================
 [INFO] INDEX: [1]
 [LABEL] NAME:  portfolio_series
 [FILE] PATH:  audit_pack -> portfolio_series
 ============================================================

Date
2026-04-17    1.000000
2026-04-20    1.010604
2026-04-21    1.016630
2026-04-22    1.030356
2026-04-23    1.039983
2026-04-24    1.052968
2026-04-27    1.053197
2026-04-28    1.048946
2026-04-29    1.069061
2026-04-30    1.092390
2026-05-01    1.103319
2026-05-04    1.105369
2026-05-05    1.125884
2026-05-06    1.133777
2026-05-07    1.119758
2026-05-08    1.137621
2026-05-11    1.154806
dtype: float64

fetch by name = "portfolio_series":
Date
2026-04-17    1.000000
2026-04-20    1.010604
2026-04-21    1.016630
2026-04-22    1.030356
2026-04-23    1.039983
2026-04-24    1.052968
2026-04-27    1.053197
2026-04-28    1.048946
2026-04-29    1.069061
2026-04-30    1.092390
2026-05-01    1.103319
2026-05-04    1.105369
2026-05-05    1.125884
2026-05-06    1.133777
2026-05-07    1.119758
2026-05-08    1.137621
2026-05-11    1.154806
dtype: float64

# IV. Audit: Walk-Forward Analyzer Verification
Checking execution dates and verifying calculated drift weight statistics against baseline simulation audit packs.

In [11]:
start_date = SU.fetch("start_date", result)
decision_date = SU.fetch("decision_date", result)
buy_date = SU.fetch("buy_date", result)
holding_end_date = SU.fetch("holding_end_date", result)

print(f"Start Date:       {start_date}")
print(f"Decision Date:    {decision_date}")
print(f"Buy Date:         {buy_date}")
print(f"Holding End Date: {holding_end_date}")

target_tickers = SU.fetch("tickers", result)
print(f"target_tickers: {target_tickers}")

 ============================================================
 [INFO] INDEX: [232]
 [LABEL] NAME:  start_date
 [FILE] PATH:  audit_pack -> start_date
 ============================================================

Timestamp('2026-04-17 00:00:00')

 ============================================================
 [INFO] INDEX: [233]
 [LABEL] NAME:  decision_date
 [FILE] PATH:  audit_pack -> decision_date
 ============================================================

Timestamp('2026-05-01 00:00:00')

 ============================================================
 [INFO] INDEX: [234]
 [LABEL] NAME:  buy_date
 [FILE] PATH:  audit_pack -> buy_date
 ============================================================

Timestamp('2026-05-04 00:00:00')

 ============================================================
 [INFO] INDEX: [235]
 [LABEL] NAME:  holding_end_date
 [FILE] PATH:  audit_pack -> holding_end_date
 ============================================================

Timestamp('2026-05-11 00:00:00')

Start Date:       2026-04-17 00:00:00
Decision Date:    2026-05-01 00:00:00
Buy Date:         2026-05-04 00:00:00
Holding End Date: 2026-05-11 00:00:00
 ============================================================
 [INFO] INDEX: [4]
 [LABEL] NAME:  tickers
 [FILE] PATH:  audit_pack -> tickers
 ============================================================

['SGOV',
 'SHV',
 'CNC',
 'CVE',
 'BIL',
 'MINT',
 'NXPI',
 'VBIL',
 'PWR',
 'MO',
 'USFR',
 'OVV',
 'INTC',
 'FANG',
 'STM',
 'BOXX',
 'MOH',
 'MUSA',
 'PR',
 'DINO',
 'TWLO',
 'TXN',
 'ADM',
 'DVN',
 'GNRC',
 'NUE',
 'SU',
 'MPC',
 'ON',
 'QCOM',
 'URI',
 'USO',
 'GOOG',
 'AMD',
 'BKR',
 'CASY',
 'STX',
 'UNH',
 'ELV',
 'GOOGL',
 'MCHP',
 'BE',
 'TRP',
 'TEAM',
 'PULS',
 'SWKS',
 'PSX',
 'QRVO',
 'NOK',
 'ZM',
 'NVT',
 'SOXL',
 'STLD',
 'SOXX',
 'CAT',
 'HAL',
 'CNQ',
 'SNDK',
 'APA',
 'SMH',
 'TRGP',
 'EOG',
 'EWT',
 'XLE',
 'VLO',
 'LYB',
 'OKE',
 'ET',
 'JEPQ',
 'MTCH',
 'OXY',
 'TROW',
 'ARM',
 'MTZ',
 'EME',
 'CBOE',
 'QQQI',
 'KDP',
 'MDLZ',
 'PBR',
 'MU',
 'FLEX',
 'EPD',
 'FNDX',
 'MRVL',
 'LNG',
 'QQQM',
 'HUM',
 'QQQ',
 'IYW',
 'QLD',
 'TQQQ',
 'STRL',
 'WMB',
 'JPST',
 'TTMI',
 'SPMO',
 'NTR',
 'DOW',
 'CARR',
 'CVS',
 'CSCO',
 'XLK',
 'ASX',
 'FIX',
 'TECL',
 'FTI',
 'WCC',
 'SWK',
 'ADP',
 'FLR',
 'CP',
 'AVB',
 'WST',
 'SLB',
 'JAAA',
 'NTAP',
 'UNP',
 'IRM',
 'INVH',
 'NVO',
 'ENB',
 'WDC',
 'AMZN',
 'SCHD',
 'FSLR',
 'TEVA',
 'AKAM',
 'CF',
 'SNPS',
 'SBUX',
 'MTUM',
 'CDNS',
 'VGT',
 'LII',
 'COP',
 'ADI',
 'HPE',
 'GTLB',
 'DDOG',
 'BP',
 'ALAB',
 'TSM',
 'CRDO',
 'NSC',
 'JBL',
 'DUOL',
 'PANW',
 'SFM',
 'GME',
 'MNDY',
 'MAS',
 'BLD',
 'IWD',
 'OEF',
 'KO',
 'NEE',
 'CRWD',
 'XOM',
 'STT',
 'EQR',
 'KEYS',
 'CSX',
 'EWY',
 'NET',
 'SRLN',
 'MPWR',
 'AR',
 'PM',
 'MOD',
 'CMI',
 'XLG',
 'DELL',
 'LIN',
 'PSTG',
 'SPYI',
 'BTI',
 'FTNT',
 'SPYM',
 'NTNX',
 'IVV',
 'VOO',
 'SPY',
 'WMT',
 'XLP',
 'TTD',
 'ETN',
 'EXE',
 'CVX',
 'EMN',
 'APD',
 'BIIB',
 'SCHB',
 'IEX',
 'SCHX',
 'ITOT',
 'SPXL',
 'SSO',
 'AAPL',
 'IVE']

target_tickers: ['SGOV', 'SHV', 'CNC', 'CVE', 'BIL', 'MINT', 'NXPI', 'VBIL', 'PWR', 'MO', 'USFR', 'OVV', 'INTC', 'FANG', 'STM', 'BOXX', 'MOH', 'MUSA', 'PR', 'DINO', 'TWLO', 'TXN', 'ADM', 'DVN', 'GNRC', 'NUE', 'SU', 'MPC', 'ON', 'QCOM', 'URI', 'USO', 'GOOG', 'AMD', 'BKR', 'CASY', 'STX', 'UNH', 'ELV', 'GOOGL', 'MCHP', 'BE', 'TRP', 'TEAM', 'PULS', 'SWKS', 'PSX', 'QRVO', 'NOK', 'ZM', 'NVT', 'SOXL', 'STLD', 'SOXX', 'CAT', 'HAL', 'CNQ', 'SNDK', 'APA', 'SMH', 'TRGP', 'EOG', 'EWT', 'XLE', 'VLO', 'LYB', 'OKE', 'ET', 'JEPQ', 'MTCH', 'OXY', 'TROW', 'ARM', 'MTZ', 'EME', 'CBOE', 'QQQI', 'KDP', 'MDLZ', 'PBR', 'MU', 'FLEX', 'EPD', 'FNDX', 'MRVL', 'LNG', 'QQQM', 'HUM', 'QQQ', 'IYW', 'QLD', 'TQQQ', 'STRL', 'WMB', 'JPST', 'TTMI', 'SPMO', 'NTR', 'DOW', 'CARR', 'CVS', 'CSCO', 'XLK', 'ASX', 'FIX', 'TECL', 'FTI', 'WCC', 'SWK', 'ADP', 'FLR', 'CP', 'AVB', 'WST', 'SLB', 'JAAA', 'NTAP', 'UNP', 'IRM', 'INVH', 'NVO', 'ENB', 'WDC', 'AMZN', 'SCHD', 'FSLR', 'TEVA', 'AKAM', 'CF', 'SNPS', 'SBUX', 'MTUM', 'CDNS', 'VGT', 'LII', 'COP', 'ADI', 'HPE', 'GTLB', 'DDOG', 'BP', 'ALAB', 'TSM', 'CRDO', 'NSC', 'JBL', 'DUOL', 'PANW', 'SFM', 'GME', 'MNDY', 'MAS', 'BLD', 'IWD', 'OEF', 'KO', 'NEE', 'CRWD', 'XOM', 'STT', 'EQR', 'KEYS', 'CSX', 'EWY', 'NET', 'SRLN', 'MPWR', 'AR', 'PM', 'MOD', 'CMI', 'XLG', 'DELL', 'LIN', 'PSTG', 'SPYI', 'BTI', 'FTNT', 'SPYM', 'NTNX', 'IVV', 'VOO', 'SPY', 'WMT', 'XLP', 'TTD', 'ETN', 'EXE', 'CVX', 'EMN', 'APD', 'BIIB', 'SCHB', 'IEX', 'SCHX', 'ITOT', 'SPXL', 'SSO', 'AAPL', 'IVE']

In [12]:
def get_value_by_key(search_term, data):
    """
    Search for a value by its name or its full path string.
    """
    for item in data:
        # Check if the search term matches the name OR the full path
        if item.get("name") == search_term or item.get("path") == search_term:
            return item.get("obj")

    return f"Error: Key '{search_term}' not found in the dataset."

In [13]:
raw_prices = get_value_by_key(
    "audit_pack -> debug_data -> portfolio_raw_components -> prices", result
)
raw_prices

Ticker,SGOV,SHV,CNC,CVE,BIL,MINT,NXPI,VBIL,PWR,MO,...,APD,BIIB,SCHB,IEX,SCHX,ITOT,SPXL,SSO,AAPL,IVE
Date,,,,,,,,,,,,,,,,,,,,,
2026-04-17,99.9645,109.623,38.17,24.51,91.0124,99.8871,216.03,75.1372,601.88,64.17,...,291.81,177.35,27.43,205.189,27.99,155.59,238.73,61.62,269.981,220.89
2026-04-20,99.9745,109.623,38.31,24.91,91.0223,99.8971,221.34,75.1471,604.97,64.61,...,296.15,183.34,27.40,205.627,27.96,155.49,237.33,61.37,272.799,221.12
2026-04-21,99.9944,109.633,39.14,25.60,91.0323,99.9070,224.50,75.1571,605.89,64.65,...,294.78,185.95,27.23,204.063,27.78,154.45,232.68,60.58,265.925,219.76
2026-04-22,100.0040,109.652,38.93,25.92,91.0323,99.9169,225.75,75.1670,613.78,65.18,...,296.76,190.07,27.48,202.907,28.04,155.91,239.69,61.78,272.919,220.16
2026-04-23,100.0140,109.662,41.09,26.45,91.0521,99.9666,241.16,75.1769,633.44,67.15,...,303.65,187.88,27.38,205.906,27.94,155.24,236.62,61.31,273.178,220.85
2026-04-24,100.0440,109.692,41.82,26.29,91.0720,99.9865,244.04,75.1968,624.84,66.88,...,301.76,184.38,27.56,204.013,28.14,156.34,242.14,62.21,270.810,220.63
2026-04-27,100.0440,109.702,43.50,26.78,91.0820,100.0060,236.87,75.1968,637.28,66.00,...,302.38,180.67,27.61,206.654,28.17,156.55,243.30,62.42,267.364,220.06
2026-04-28,100.0640,109.712,49.57,27.42,91.0919,100.0260,230.39,75.2068,630.94,67.80,...,303.35,183.38,27.46,204.631,28.03,155.72,239.71,61.80,270.461,220.20
2026-04-29,100.0740,109.712,53.98,28.75,91.0919,100.0560,289.25,75.2167,628.60,68.20,...,302.50,194.38,27.44,216.568,28.02,155.62,239.60,61.79,269.921,220.91
2026-04-30,100.0740,109.732,53.69,29.24,91.1018,100.0360,293.59,75.2267,727.77,72.65,...,300.05,189.28,27.73,217.077,28.29,157.29,246.37,62.96,271.100,223.67
2026-05-01,100.1120,109.760,53.34,29.27,91.1318,100.0960,295.24,75.2526,742.21,74.55,...,301.07,187.06,27.82,214.167,28.38,157.76,248.48,63.31,279.882,223.51
2026-05-04,100.1220,109.780,53.56,29.98,91.1517,100.1060,290.76,75.2626,757.34,73.41,...,298.35,187.21,27.72,213.569,28.28,157.17,245.73,62.86,276.575,222.08
2026-05-05,100.1320,109.780,52.98,30.45,91.1617,100.1260,292.35,75.2626,771.61,72.79,...,303.93,189.13,27.94,214.994,28.50,158.49,251.45,63.83,283.918,223.80
2026-05-06,100.1420,109.800,55.33,29.02,91.1517,100.1160,303.55,75.2626,785.24,70.17,...,300.21,190.68,28.34,217.415,28.89,160.74,261.94,65.61,287.245,224.77
2026-05-07,100.1520,109.810,54.98,28.46,91.1716,100.1360,290.22,75.2725,750.73,69.04,...,294.99,191.38,28.21,214.107,28.79,159.99,259.38,65.18,287.175,223.58
2026-05-08,100.1820,109.850,55.96,28.40,91.1916,100.1660,294.75,75.3124,745.00,68.12,...,295.41,193.45,28.42,216.150,29.00,161.18,265.56,66.22,293.050,224.26
2026-05-11,100.1920,109.850,56.36,29.13,91.2115,100.1760,305.99,75.3124,781.38,68.61,...,304.50,197.95,28.48,213.250,29.07,161.50,267.27,66.51,292.680,224.58

In [14]:
# raw_prices = SU.fetch("full_universe_ranking", result)
raw_prices = SU.fetch(277, result)
# raw_prices = SU.fetch("prices", result)

 ============================================================
 [INFO] INDEX: [277]
 [LABEL] NAME:  prices
 [FILE] PATH:  audit_pack -> debug_data -> portfolio_raw_components -> prices
 ============================================================

Ticker,SGOV,SHV,CNC,CVE,BIL,MINT,NXPI,VBIL,PWR,MO,...,APD,BIIB,SCHB,IEX,SCHX,ITOT,SPXL,SSO,AAPL,IVE
Date,,,,,,,,,,,,,,,,,,,,,
2026-04-17,99.9645,109.623,38.17,24.51,91.0124,99.8871,216.03,75.1372,601.88,64.17,...,291.81,177.35,27.43,205.189,27.99,155.59,238.73,61.62,269.981,220.89
2026-04-20,99.9745,109.623,38.31,24.91,91.0223,99.8971,221.34,75.1471,604.97,64.61,...,296.15,183.34,27.40,205.627,27.96,155.49,237.33,61.37,272.799,221.12
2026-04-21,99.9944,109.633,39.14,25.60,91.0323,99.9070,224.50,75.1571,605.89,64.65,...,294.78,185.95,27.23,204.063,27.78,154.45,232.68,60.58,265.925,219.76
2026-04-22,100.0040,109.652,38.93,25.92,91.0323,99.9169,225.75,75.1670,613.78,65.18,...,296.76,190.07,27.48,202.907,28.04,155.91,239.69,61.78,272.919,220.16
2026-04-23,100.0140,109.662,41.09,26.45,91.0521,99.9666,241.16,75.1769,633.44,67.15,...,303.65,187.88,27.38,205.906,27.94,155.24,236.62,61.31,273.178,220.85
2026-04-24,100.0440,109.692,41.82,26.29,91.0720,99.9865,244.04,75.1968,624.84,66.88,...,301.76,184.38,27.56,204.013,28.14,156.34,242.14,62.21,270.810,220.63
2026-04-27,100.0440,109.702,43.50,26.78,91.0820,100.0060,236.87,75.1968,637.28,66.00,...,302.38,180.67,27.61,206.654,28.17,156.55,243.30,62.42,267.364,220.06
2026-04-28,100.0640,109.712,49.57,27.42,91.0919,100.0260,230.39,75.2068,630.94,67.80,...,303.35,183.38,27.46,204.631,28.03,155.72,239.71,61.80,270.461,220.20
2026-04-29,100.0740,109.712,53.98,28.75,91.0919,100.0560,289.25,75.2167,628.60,68.20,...,302.50,194.38,27.44,216.568,28.02,155.62,239.60,61.79,269.921,220.91
2026-04-30,100.0740,109.732,53.69,29.24,91.1018,100.0360,293.59,75.2267,727.77,72.65,...,300.05,189.28,27.73,217.077,28.29,157.29,246.37,62.96,271.100,223.67
2026-05-01,100.1120,109.760,53.34,29.27,91.1318,100.0960,295.24,75.2526,742.21,74.55,...,301.07,187.06,27.82,214.167,28.38,157.76,248.48,63.31,279.882,223.51
2026-05-04,100.1220,109.780,53.56,29.98,91.1517,100.1060,290.76,75.2626,757.34,73.41,...,298.35,187.21,27.72,213.569,28.28,157.17,245.73,62.86,276.575,222.08
2026-05-05,100.1320,109.780,52.98,30.45,91.1617,100.1260,292.35,75.2626,771.61,72.79,...,303.93,189.13,27.94,214.994,28.50,158.49,251.45,63.83,283.918,223.80
2026-05-06,100.1420,109.800,55.33,29.02,91.1517,100.1160,303.55,75.2626,785.24,70.17,...,300.21,190.68,28.34,217.415,28.89,160.74,261.94,65.61,287.245,224.77
2026-05-07,100.1520,109.810,54.98,28.46,91.1716,100.1360,290.22,75.2725,750.73,69.04,...,294.99,191.38,28.21,214.107,28.79,159.99,259.38,65.18,287.175,223.58
2026-05-08,100.1820,109.850,55.96,28.40,91.1916,100.1660,294.75,75.3124,745.00,68.12,...,295.41,193.45,28.42,216.150,29.00,161.18,265.56,66.22,293.050,224.26
2026-05-11,100.1920,109.850,56.36,29.13,91.2115,100.1760,305.99,75.3124,781.38,68.61,...,304.50,197.95,28.48,213.250,29.07,161.50,267.27,66.51,292.680,224.58

In [15]:
from typing import cast

# --- 1. Extract Drift Data ---
raw_prices = get_value_by_key(
    "audit_pack -> debug_data -> portfolio_raw_components -> prices", result
)
raw_atrp = get_value_by_key(
    "audit_pack -> debug_data -> portfolio_raw_components -> atrp", result
)
raw_trp = get_value_by_key(
    "audit_pack -> debug_data -> portfolio_raw_components -> trp", result
)

metric_suffixes = ["gain", "sharpe", "sharpe_atrp", "sharpe_trp"]
period_prefixes = ["full", "lookback", "holding"]
audit_data = {
    f"{p}_p_{s}": get_value_by_key(f"{p}_p_{s}", result)
    for s in metric_suffixes
    for p in period_prefixes
}

metric_types = ["Log Gain", "Sharpe", "Sharpe (ATRP)", "Sharpe (TRP)"]
period_names = ["Full", "Lookback", "Holding"]
period_slices = {
    "Full": (start_date, holding_end_date),
    "Lookback": (start_date, decision_date),
    "Holding": (buy_date, holding_end_date),
}

portfolio_results = {}

# --- 2. Calculate Drift Weights & Expected Returns ---
for name, (s_date, e_date) in period_slices.items():

    raw_prices = cast(pd.DataFrame, raw_prices)
    raw_atrp = cast(pd.DataFrame, raw_atrp)
    raw_trp = cast(pd.DataFrame, raw_trp)

    p_slice = raw_prices.loc[s_date:e_date]
    a_slice = raw_atrp.loc[s_date:e_date]
    t_slice = raw_trp.loc[s_date:e_date]

    norm_prices = p_slice / p_slice.iloc[0]
    weights = norm_prices.div(norm_prices.sum(axis=1), axis=0)

    equity_curve = norm_prices.mean(axis=1)
    returns = equity_curve.pct_change().dropna()

    port_atrp = (weights * a_slice).sum(axis=1).loc[returns.index]
    port_trp = (weights * t_slice).sum(axis=1).loc[returns.index]

    portfolio_results[f"{name} Log Gain"] = np.log(equity_curve.iloc[-1])
    portfolio_results[f"{name} Sharpe"] = (returns.mean() / returns.std()) * np.sqrt(
        252
    )
    portfolio_results[f"{name} Sharpe (ATRP)"] = returns.mean() / port_atrp.mean()
    portfolio_results[f"{name} Sharpe (TRP)"] = returns.mean() / port_trp.mean()

# --- 3. Evaluate Discrepancy ---
print(f"{'METRIC':<25} | {'CALCULATED':<12} | {'AUDIT PACK':<12} | {'MATCH?'}")
for m_type in metric_types:
    print("-" * 75)
    for p_name in period_names:
        key = f"{p_name} {m_type}"
        sfx = m_type.lower().replace(" ", "_").replace("(", "").replace(")", "")
        audit_key = f"{p_name.lower()}_p_{'gain' if sfx == 'log_gain' else sfx}"

        calc_val, audit_val = portfolio_results[key], audit_data[audit_key]
        is_match = np.isclose(float(calc_val), float(audit_val or 0), rtol=1e-05)
        print(
            f"{key:<25} | {calc_val:<12.6f} | {audit_val:<12.6f} | {'✅ YES' if is_match else '❌ NO'}"
        )

for key, val in portfolio_results.items():
    p, m = key.split(" ", 1)
    sfx = m.lower().replace(" ", "_").replace("(", "").replace(")", "")
    audit_key = f"{p.lower()}_p_{'gain' if sfx == 'log_gain' else sfx}"
    assert np.isclose(
        float(val or 0.0), float(audit_data[audit_key] or 0.0), rtol=1e-05
    )

print("Verification complete. Drift weights match the holding period metrics.")

METRIC                    | CALCULATED   | AUDIT PACK   | MATCH?
---------------------------------------------------------------------------
Full Log Gain             | 0.143932     | 0.143932     | ✅ YES
Lookback Log Gain         | 0.098323     | 0.098323     | ✅ YES
Holding Log Gain          | 0.041702     | 0.041702     | ✅ YES
---------------------------------------------------------------------------
Full Sharpe               | 15.789618    | 15.789618    | ✅ YES
Lookback Sharpe           | 20.081569    | 20.081569    | ✅ YES
Holding Sharpe            | 11.107559    | 11.107559    | ✅ YES
---------------------------------------------------------------------------
Full Sharpe (ATRP)        | 0.290284     | 0.290284     | ✅ YES
Lookback Sharpe (ATRP)    | 0.320815     | 0.320815     | ✅ YES
Holding Sharpe (ATRP)     | 0.270137     | 0.270137     | ✅ YES
---------------------------------------------------------------------------
Full Sharpe (TRP)         | 0.258178     | 0.258178     | ✅ YES
Lookback Sharpe (TRP)     | 0.297537     | 0.297537     | ✅ YES
Holding Sharpe (TRP)      | 0.218721     | 0.218721     | ✅ YES
Verification complete. Drift weights match the holding period metrics.

# V. Audit: Individual Feature Math
Step-by-step verification comparing pipeline features against manual formulations for a chosen target ticker.

### Group A: Basic Features (Returns, Momentum, Drawdown, Consistency, TRP)

In [26]:
# verification_ticker = "NVDA"
# target_date = pd.Timestamp("2026-04-24")
# lookback_days = 120

verification_ticker = "A"
target_date = pd.Timestamp("2026-05-01")
lookback_days = 10


ticker_prices = df_ohlcv.xs(verification_ticker, level="Ticker")
ticker_features = features_df.xs(verification_ticker, level="Ticker")

if target_date not in ticker_prices.index:
    new_target = ticker_prices.index[ticker_prices.index <= target_date][-1]
    print(f"Adjusting target date from {target_date.date()} to {new_target.date()}")
    target_date = new_target

raw_slice = ticker_prices.loc[:target_date].tail(90).copy()
feat_row = ticker_features.loc[target_date]

manual_ret_1d = raw_slice["Adj Close"].pct_change().iloc[-1]
manual_mom_21 = raw_slice["Adj Close"].pct_change(21).iloc[-1]

rolling_max_21 = raw_slice["Adj Close"].rolling(window=21).max()
manual_dd_21 = (raw_slice["Adj Close"] / rolling_max_21 - 1).iloc[-1]

daily_rets = raw_slice["Adj Close"].pct_change()
manual_consist = (daily_rets > 0).rolling(window=5).mean().iloc[-1]

prev_close = raw_slice["Adj Close"].shift(1)
tr_val = pd.concat(
    [
        (raw_slice["Adj High"] - raw_slice["Adj Low"]),
        (raw_slice["Adj High"] - prev_close).abs(),
        (raw_slice["Adj Low"] - prev_close).abs(),
    ],
    axis=1,
).max(axis=1)
manual_trp = (tr_val / raw_slice["Adj Close"]).iloc[-1]

easy_verification = pd.DataFrame(
    {
        "Feature": ["Ret_1d", "Mom_21", "DD_21", "Consistency", "TRP"],
        "Manual_Value": [
            manual_ret_1d,
            manual_mom_21,
            manual_dd_21,
            manual_consist,
            manual_trp,
        ],
        "Feature_DF_Value": [
            feat_row["Ret_1d"],
            feat_row["Mom_21"],
            feat_row["DD_21"],
            feat_row["Consistency"],
            feat_row["TRP"],
        ],
    }
)
easy_verification["Abs_Error"] = (
    easy_verification["Manual_Value"] - easy_verification["Feature_DF_Value"]
).abs()

print(f"\nVerification for {verification_ticker} on {target_date.date()}")
print(
    easy_verification.to_string(
        index=False,
        formatters={
            "Manual_Value": "{:.6f}".format,
            "Feature_DF_Value": "{:.6f}".format,
            "Abs_Error": "{:.2e}".format,
        },
    )
)

if easy_verification["Abs_Error"].max() < 1e-10:
    print("\n✅ Easy Group Verified.")
else:
    print("\n❌ Discrepancy detected.")

Verification for A on 2026-05-01
    Feature Manual_Value Feature_DF_Value Abs_Error
     Ret_1d    -0.008914        -0.008914  0.00e+00
     Mom_21    -0.000175        -0.000175  0.00e+00
      DD_21    -0.062003        -0.062003  0.00e+00
Consistency     0.400000         0.400000  0.00e+00
        TRP     0.021306         0.021306  0.00e+00

✅ Easy Group Verified.

### Group B: Smoothed Indicators (RSI, ATRP, Autocorrelation)

In [27]:
ticker_prices = df_ohlcv.xs(verification_ticker, level="Ticker")
ticker_features = features_df.xs(verification_ticker, level="Ticker")
feat_row = ticker_features.loc[target_date]

adj_close = ticker_prices["Adj Close"]
adj_high = ticker_prices["Adj High"]
adj_low = ticker_prices["Adj Low"]
rsi_period = config.rsi_period
atr_period = config.atr_period

# 1. Wilder's RSI
delta = adj_close.diff()
gain = delta.where(delta > 0, 0)
loss = -delta.where(delta < 0, 0)
avg_gain = gain.ewm(alpha=1 / rsi_period, adjust=False).mean()
avg_loss = loss.ewm(alpha=1 / rsi_period, adjust=False).mean()
rs = avg_gain / avg_loss
manual_rsi = (100 - (100 / (1 + rs))).loc[target_date]

# 2. ATRP
prev_close = adj_close.shift(1)
tr = pd.concat(
    [(adj_high - adj_low), (adj_high - prev_close).abs(), (adj_low - prev_close).abs()],
    axis=1,
).max(axis=1)
manual_atr = tr.ewm(alpha=1 / atr_period, adjust=False).mean()
manual_atrp = (manual_atr / adj_close).loc[target_date]

# 3. Lag-1 Correlation
rets = adj_close.pct_change()
manual_autocorr = rets.rolling(window=15).corr(rets.shift(1)).loc[target_date]

group2_verification = pd.DataFrame(
    {
        "Feature": ["RSI", "ATRP", "AutoCorr_15"],
        "Manual_Value": [manual_rsi, manual_atrp, manual_autocorr],
        "Feature_DF_Value": [
            feat_row["RSI"],
            feat_row["ATRP"],
            feat_row["AutoCorr_15"],
        ],
    }
)
group2_verification["Abs_Error"] = (
    group2_verification["Manual_Value"] - group2_verification["Feature_DF_Value"]
).abs()

print(f"Verification for {verification_ticker} on {target_date.date()}")
print(
    group2_verification.to_string(
        index=False,
        formatters={
            "Manual_Value": "{:.6f}".format,
            "Feature_DF_Value": "{:.6f}".format,
            "Abs_Error": "{:.2e}".format,
        },
    )
)

if group2_verification["Abs_Error"].max() < 1e-8:
    print("\n✅ Smoothed Group Verified.")
else:
    print("\n❌ Discrepancy detected.")

Verification for A on 2026-05-01
    Feature Manual_Value Feature_DF_Value Abs_Error
        RSI    46.042348        46.042348  0.00e+00
       ATRP     0.030175         0.030175  0.00e+00
AutoCorr_15    -0.205047        -0.205047  0.00e+00

✅ Smoothed Group Verified.

### Group C: Quality & Acceleration Features (Staleness, Dollar Volume, Convexity)

In [28]:
q_window = config.quality_window
q_min = config.quality_min_periods

ticker_prices = df_ohlcv.xs(verification_ticker, level="Ticker")
ticker_features = features_df.xs(verification_ticker, level="Ticker")
feat_row = ticker_features.loc[target_date]

is_stale = (
    (ticker_prices["Volume"] == 0)
    | (ticker_prices["Adj High"] == ticker_prices["Adj Low"])
).astype(int)
manual_stale_pct = (
    is_stale.rolling(window=q_window, min_periods=q_min).mean().loc[target_date]
)

has_same_vol = (ticker_prices["Volume"].diff() == 0).astype(int)
manual_same_vol = (
    has_same_vol.rolling(window=q_window, min_periods=q_min).sum().loc[target_date]
)

dollar_vol = ticker_prices["Adj Close"] * ticker_prices["Volume"]
manual_med_dvol = (
    dollar_vol.rolling(window=q_window, min_periods=q_min).median().loc[target_date]
)
s_idx = ticker_features.index.get_indexer_for(pd.Index([target_date]))[0]
slope_t = ticker_features["Slope_P_5"].iloc[s_idx]
slope_t_minus_2 = ticker_features["Slope_P_5"].iloc[s_idx - 2]
manual_convexity = slope_t - slope_t_minus_2

final_verification = pd.DataFrame(
    {
        "Feature": [
            "RollingStalePct",
            "RollingSameVolCount",
            "RollMedDollarVol",
            "Convexity",
        ],
        "Manual_Value": [
            manual_stale_pct,
            manual_same_vol,
            manual_med_dvol,
            manual_convexity,
        ],
        "Feature_DF_Value": [
            feat_row["RollingStalePct"],
            feat_row["RollingSameVolCount"],
            feat_row["RollMedDollarVol"],
            feat_row["Convexity"],
        ],
    }
)
final_verification["Abs_Error"] = (
    final_verification["Manual_Value"] - final_verification["Feature_DF_Value"]
).abs()

print(f"--- Final Group Verification: {verification_ticker} ({target_date.date()}) ---")
print(
    final_verification.to_string(
        index=False,
        formatters={
            "Manual_Value": "{:,.4f}".format,
            "Feature_DF_Value": "{:,.4f}".format,
            "Abs_Error": "{:.2e}".format,
        },
    )
)

if final_verification["Abs_Error"].max() < 1e-7:
    print("\n✅ Final Group Verified: All quality and acceleration metrics match.")
else:
    print("\n❌ Discrepancy detected in final group.")

--- Final Group Verification: A (2026-05-01) ---
            Feature     Manual_Value Feature_DF_Value Abs_Error
    RollingStalePct           0.0000           0.0000  0.00e+00
RollingSameVolCount           0.0000           0.0000  0.00e+00
   RollMedDollarVol 227,620,611.9000 227,620,611.9000  0.00e+00
          Convexity           0.0048           0.0048  0.00e+00

✅ Final Group Verified: All quality and acceleration metrics match.

### Group D: Complex & Relative Indicators (ATR, IR, Beta, Price Position, Slope)

In [29]:
ticker_prices = df_ohlcv.xs(verification_ticker, level="Ticker")
ticker_features = features_df.xs(verification_ticker, level="Ticker")
feat_row = ticker_features.loc[target_date]

atr_period = config.atr_period
win_63 = config.win_63d
win_20 = 20

s_idx = ticker_prices.index.get_loc(target_date)
adj_close = ticker_prices["Adj Close"]
adj_high = ticker_prices["Adj High"]
adj_low = ticker_prices["Adj Low"]
volume = ticker_prices["Volume"]


def apply_5d_slope_kernel(series, idx):
    y = series.iloc[idx - 4 : idx + 1].values
    weights = np.array([-2, -1, 0, 1, 2])
    return np.sum(y * weights) / 10


# 1. Raw ATR
prev_close = adj_close.shift(1)
tr = pd.concat(
    [(adj_high - adj_low), (adj_high - prev_close).abs(), (adj_low - prev_close).abs()],
    axis=1,
).max(axis=1)
manual_atr = tr.ewm(alpha=1 / atr_period, adjust=False).mean().loc[target_date]

# 2. Price Channel Position
h_20 = adj_high.rolling(window=win_20).max().loc[target_date]
l_20 = adj_low.rolling(window=win_20).min().loc[target_date]
manual_range_pos = (adj_close.loc[target_date] - l_20) / (h_20 - l_20)

# 3. Beta & Information Ratio (IR)
stock_rets = adj_close.pct_change()
common_idx = stock_rets.index.intersection(macro_df.index)
mkt_rets = macro_df.loc[common_idx, "Mkt_Ret"]
stock_rets_aligned = stock_rets.loc[common_idx]


s_idx_aligned = stock_rets_aligned.index.get_indexer_for(pd.Index([target_date]))[0]
y = stock_rets_aligned.iloc[s_idx_aligned - 62 : s_idx_aligned + 1]
x_mkt = mkt_rets.iloc[s_idx_aligned - 62 : s_idx_aligned + 1]

manual_beta_63 = np.cov(y, x_mkt)[0, 1] / np.var(x_mkt, ddof=1)

excess = y - x_mkt
manual_ir_63 = excess.mean() / excess.std()

# 4. Trend Slopes
manual_slope_p = apply_5d_slope_kernel(np.log(adj_close), s_idx)
v_baseline = volume.rolling(window=win_63, min_periods=1).mean().replace(0, 1e-8)
v_rel = volume / v_baseline

obv_rel = (adj_close.diff().fillna(0).pipe(np.sign) * v_rel).cumsum()
manual_slope_v = apply_5d_slope_kernel(obv_rel, s_idx)

audit_results = pd.DataFrame(
    {
        "Feature": [
            "ATR",
            "IR_63",
            "Beta_63",
            "Range_Pos_20",
            "Slope_P_5",
            "Slope_V_5",
        ],
        "Manual_Value": [
            manual_atr,
            manual_ir_63,
            manual_beta_63,
            manual_range_pos,
            manual_slope_p,
            manual_slope_v,
        ],
        "Feature_DF_Value": [
            feat_row["ATR"],
            feat_row["IR_63"],
            feat_row["Beta_63"],
            feat_row["Range_Pos_20"],
            feat_row["Slope_P_5"],
            feat_row["Slope_V_5"],
        ],
    }
)
audit_results["Abs_Error"] = (
    audit_results["Manual_Value"] - audit_results["Feature_DF_Value"]
).abs()

print(f"--- Completion Audit: {verification_ticker} ({target_date.date()}) ---")
print(
    audit_results.to_string(
        index=False,
        formatters={
            "Manual_Value": "{:,.6f}".format,
            "Feature_DF_Value": "{:,.6f}".format,
            "Abs_Error": "{:.2e}".format,
        },
    )
)

if audit_results["Abs_Error"].max() < 1e-7:
    print("\n✅ All remaining columns verified. Audit Complete.")
else:
    print("\n❌ Audit mismatch detected in remaining columns.")

--- Completion Audit: A (2026-05-01) ---
     Feature Manual_Value Feature_DF_Value Abs_Error
         ATR     3.455650         3.455650  0.00e+00
       IR_63    -0.195027        -0.195027  1.42e-15
     Beta_63     0.914108         0.914108  1.54e-14
Range_Pos_20     0.288752         0.288752  0.00e+00
   Slope_P_5    -0.001322        -0.001322  0.00e+00
   Slope_V_5    -0.285536        -0.285536  1.14e-14

✅ All remaining columns verified. Audit Complete.

# VI. Audit: Cross-Sectional Blueprints
Analyzing Z-Scores and double-scoring architectures across the universe for Pillar 5 (OBV Divergence) and Pillar 6 (Convexity).

In [30]:
target_date = pd.Timestamp("2026-04-24")
verification_ticker = "NVDA"
universe_convexity = features_df.xs(target_date, level="Date")["Convexity"]

# Manual Engine Logic
clean_universe = universe_convexity.replace([np.inf, -np.inf], np.nan).dropna()
u_mean = clean_universe.mean()
u_std = clean_universe.std()
manual_z_scores = (clean_universe - u_mean) / u_std
clip_val = config.feature_zscore_clip
final_agent_values = manual_z_scores.fillna(0).clip(-clip_val, clip_val)

raw_val = clean_universe.loc[verification_ticker]
agent_val = final_agent_values.loc[verification_ticker]

print(f"--- Pillar 6 (Convexity) Cross-Sectional Audit ---")
print(f"Date: {target_date.date()} | Universe Size: {len(clean_universe)}")
print(f"NVDA Raw Convexity    : {raw_val:.6f}")
print(f"NVDA Agent View (Z)   : {agent_val:.6f}")

--- Pillar 6 (Convexity) Cross-Sectional Audit ---
Date: 2026-04-24 | Universe Size: 1577
NVDA Raw Convexity    : 0.002689
NVDA Agent View (Z)   : 0.509011

In [31]:
from core.contracts import MetricBlueprint
from types import SimpleNamespace
from strategy.registry import get_strategy_registry

registry = get_strategy_registry(config)
daily_snapshot = features_df.xs(target_date, level="Date")
obs = SimpleNamespace(
    convexity=daily_snapshot["Convexity"],
    slope_p_5=daily_snapshot["Slope_P_5"],
    slope_v_5=daily_snapshot["Slope_V_5"],
)

convexity_blueprint = registry["Convexity"]
system_output_series = convexity_blueprint.get_agent_view(obs, config=config)
system_val = system_output_series.loc[verification_ticker]

print(f"--- Final System Verification: Pillar 6 ---")
print(f"Manual Audit Value (Z):  {agent_val:.5f}")
print(f"System Output Value (Z): {system_val:.5f}")

error = abs(agent_val - system_val)
if error < 1e-5:
    print(
        f"\n✅ VERIFIED: The System Logic matches the Manual Audit (Error: {error:.2e})"
    )
else:
    print(f"\n❌ DISCREPANCY: System output differs from manual calculation!")

--- Final System Verification: Pillar 6 ---
Manual Audit Value (Z):  0.50901
System Output Value (Z): 0.50901

✅ VERIFIED: The System Logic matches the Manual Audit (Error: 0.00e+00)

In [32]:
class QuantUtils:
    @staticmethod
    def zscore(series: pd.Series) -> pd.Series:
        clean = series.replace([np.inf, -np.inf], np.nan)
        return (clean - clean.mean()) / clean.std()


obs_p5 = SimpleNamespace(
    slope_v_5=daily_snapshot["Slope_V_5"], slope_p_5=daily_snapshot["Slope_P_5"]
)

divergence_blueprint = registry["OBV Divergence (5d)"]

# Step-by-Step Manual Double Z-Score Verification
z_vol = QuantUtils.zscore(obs_p5.slope_v_5)
z_price = QuantUtils.zscore(obs_p5.slope_p_5)
raw_divergence = z_vol - z_price

final_manual_z = QuantUtils.zscore(raw_divergence)
clip_val = config.feature_zscore_clip
manual_final_val = (
    final_manual_z.fillna(0).clip(-clip_val, clip_val).loc[verification_ticker]
)

system_output_series = divergence_blueprint.get_agent_view(obs_p5, config=config)
system_final_val = system_output_series.loc[verification_ticker]

print(f"--- Pillar 5 (OBV Divergence) Completion Audit ---")
print(f"NVDA Z-Volume (Internal): {z_vol.loc[verification_ticker]:10.5f}")
print(f"NVDA Z-Price  (Internal): {z_price.loc[verification_ticker]:10.5f}")
print(f"Manual Final Z-Score    : {manual_final_val:10.5f}")
print(f"System Final Z-Score    : {system_final_val:10.5f}")

error = abs(manual_final_val - system_final_val)
if error < 1e-5:
    print(
        f"\n✅ VERIFIED: Pillar 5 logic is mathematically consistent (Error: {error:.2e})"
    )
else:
    print(f"\n❌ DISCREPANCY: Check QuantUtils.zscore implementation details.")

--- Pillar 5 (OBV Divergence) Completion Audit ---
NVDA Z-Volume (Internal):    0.48394
NVDA Z-Price  (Internal):    0.71172
Manual Final Z-Score    :   -0.31402
System Final Z-Score    :   -0.31402

✅ VERIFIED: Pillar 5 logic is mathematically consistent (Error: 0.00e+00)

# VII. Data Exports & Sheets

In [33]:
filename = "verify_UI_n_features_calc.xlsx"
SU.export_audit_to_excel(
    audit_pack=analyzer1.last_run,
    filename=filename,
)
print(f"\n{filename} written to {OUTPUT_DIR}\\")

[FILE] [EXCEL AUDIT] Building full transparency report: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\output\verify_UI_n_features_calc.xlsx
[DONE] Audit Report Complete: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\output\verify_UI_n_features_calc.xlsx

verify_UI_n_features_calc.xlsx written to C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR_v2\output\

In [34]:
features_df.loc["TSLA"].to_excel("features_df_out.xlsx")
print("Wrote TSLA data from features_df to features_df_out.xlsx")

Wrote TSLA data from features_df to features_df_out.xlsx

In [35]:
_nb_elapsed = time.perf_counter() - _nb_start_time
print(f"\n⏱️ Total Execution Time: {_nb_elapsed:.2f}s ({_nb_elapsed/60:.2f} min)")

⏱️ Total Execution Time: 195.49s (3.26 min)