### Finviz Data Cleaning and Transformation Pipeline

This notebook processes the raw data downloaded from Finviz, cleans it, and transforms it into an analysis-ready format.

**Workflow:**

1.  **Load Data:** Reads a raw Finviz `.parquet` file for a specific date.
2.  **Feature Engineering:** Creates new composite columns (`Info`, `MktCap AUM`).
3.  **Data Type Conversion:**
    *   Converts currency strings (e.g., `1.5B`, `250K`) into numeric values in millions.
    *   Converts percentage strings (e.g., `12.5%`) into numeric values.
    *   Converts other object columns to their proper numeric types.
4.  **Final Processing:** Sorts the data by market capitalization, sets the `Ticker` as the index, and adds a `Rank` column.
5.  **Save & Verify:** Saves the cleaned DataFrame to a new `.parquet` file and verifies the saved file.

### Setup and Configuration

**This is the only cell you need to modify.** It contains all imports, paths, and lists of columns for processing.

In [1]:
import sys
from pathlib import Path
import pandas as pd
import numpy as np

# --- Project Path Setup ---
NOTEBOOK_DIR = Path.cwd()
ROOT_DIR = NOTEBOOK_DIR.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))

SRC_DIR = ROOT_DIR / 'src'
if str(SRC_DIR) not in sys.path:
    sys.path.append(str(SRC_DIR))

# Import config and custom utils now that path is set
from config import DATE_STR, DOWNLOAD_DIR, DEST_DIR
import utils

# --- File Path Configuration ---
# Build paths using pathlib for cross-platform compatibility
SOURCE_PATH = Path(DOWNLOAD_DIR) / f'df_finviz_{DATE_STR}_stocks_etfs.parquet'
DEST_PATH = Path(DEST_DIR) / f'{DATE_STR}_df_finviz_stocks_etfs.parquet'

# --- Column Processing Configuration ---
# Define which columns need specific cleaning operations.

# Columns to combine into the 'Info' column
INFO_COLS = ["Sector", "Industry", "Single Category", "Asset Type"]

# Columns with abbreviated currency values (B, M, K) to be converted to millions
CURRENCY_COLS = [
    'Market Cap', 'AUM', 'Sales', 'Income', 'Outstanding', 'Float', 
    'Short Interest', 'Avg Volume', 'Flows 1M', 'Flows 3M', 'Flows YTD',
    'MktCap AUM' # This is the new column we create
]

# Other columns that are numeric but stored as strings (objects)
# Note: Percentage columns are detected automatically in Step 3.
OTHER_NUMERIC_COLS = [
    "No.", "P/E", "Fwd P/E", "PEG", "P/S", "P/B", "P/C", "P/FCF",
    "Book/sh", "Cash/sh", "Dividend TTM", "EPS", "EPS next Q", "Short Ratio",
    "Curr R", "Quick R", "LTDebt/Eq", "Debt/Eq", "Beta", "ATR", "RSI",
    "Employees", "Recom", "Rel Volume", "Volume", "Target Price",
    "Prev Close", "Open", "High", "Low", "Price", "Holdings"
]

# --- Notebook Setup ---
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 200)
pd.set_option('display.width', 2500)
%load_ext autoreload
%autoreload 2

# --- Verification ---
print(f"Source file: {SOURCE_PATH}")
print(f"Destination file: {DEST_PATH}")
print(f"Processing for date: {DATE_STR}")

Source file: C:\Users\ping\Downloads\df_finviz_2026-07-17_stocks_etfs.parquet
Destination file: c:\Users\ping\Files_win10\python\py311\stocks\data\2026-07-17_df_finviz_stocks_etfs.parquet
Processing for date: 2026-07-17

### Step 1: Load Raw Data

Load the source Parquet file into a pandas DataFrame.

In [2]:
print(f"--- Step 1: Loading data from {SOURCE_PATH.name} ---")

try:
    df = pd.read_parquet(SOURCE_PATH, engine="pyarrow")
    print("Data loaded successfully.")
    df.info()
    display(df.head(3))
except FileNotFoundError:
    print(f"ERROR: Source file not found at {SOURCE_PATH}")
    df = None  # Ensure df is None if loading fails
except Exception as e:
    print(f"An error occurred during file loading: {e}")
    df = None

--- Step 1: Loading data from df_finviz_2026-07-17_stocks_etfs.parquet ---
Data loaded successfully.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Columns: 111 entries, No. to Tags
dtypes: float64(32), int64(2), object(77)
memory usage: 1.3+ MB

   No. Ticker                               Company    Index             Sector                        Industry Country Exchange Market Cap    P/E  Forward P/E   PEG   P/S    P/B     P/C  P/FCF  Book/sh  Cash/sh Dividend  Dividend TTM Dividend Ex Date Payout Ratio   EPS  EPS next Q EPS This Y EPS Next Y EPS Past 5Y EPS Next 5Y Sales Past 5Y Sales Q/Q EPS Q/Q EPS YoY TTM Sales YoY TTM   Sales Income EPS Surprise Revenue Surprise Outstanding    Float Float % Insider Own Insider Trans Inst Own Inst Trans Short Float  Short Ratio Short Interest    ROA     ROE    ROIC  Curr R  Quick R  LTDebt/Eq  Debt/Eq Gross M  Oper M Profit M Perf Week Perf Month Perf Quart Perf Half Perf Year Perf YTD  Beta   ATR Volatility W Volatility M    SMA20    SMA50   SMA200 50D High 50D Low 52W High 52W Low      52W Range All-Time High All-Time Low    RSI  Earnings    IPO Date Optionable Shortable  Employees Change from Open     Gap  Recom Avg Volume  Rel Volume    Volume  Target Price  Prev Close   Open   High    Low  Price  Change Single Category Asset Type Expense  Holdings AUM  Flows 1M Flows% 1M  Flows 3M Flows% 3M Flows YTD Flows% YTD Return% 1Y Return% 3Y Return% 5Y Tags
0  461   LLVS                  Las Vegas Sands Corp  S&P 500  Consumer Cyclical               Resorts & Casinos     USA     NYSE     30.06B  16.79        12.66  1.69  2.19  25.10    9.03  13.61     1.81     5.03    2.48%          1.10         5/5/2026       42.59%  2.70        0.76      9.52%      8.73%           -       7.51%        34.66%    25.26%  71.16%      50.79%        22.67%  13.74B  1.84B       20.31%            6.64%     663.00M  274.72M  41.44%      58.54%        -0.02%   42.23%     -0.86%       6.57%         3.90         18.05M  8.68%  94.53%  12.20%    0.92     0.91      11.60    13.13  38.37%  24.64%   13.41%    -2.85%     -7.32%    -20.01%   -24.27%    -7.30%  -30.31%  0.85  1.21        2.32%        2.47%   -2.42%   -7.64%  -19.10%  -16.95%   2.58%  -35.62%   2.58%  44.22 - 70.45       -67.54%     3399.34%  37.02  Jul 22/a  12/15/2004        Yes       Yes    41500.0           -0.50%  -0.24%   1.57      4.63M        0.93   4296079         66.73       45.70  45.59  45.70  45.02  45.36  -0.74%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
1  462   FFTS                            Fortis Inc        -          Utilities  Utilities - Regulated Electric  Canada     NYSE     29.92B  23.94        21.09  5.13  3.39   1.83  116.33    NaN    32.03     0.51    3.17%          1.83        5/15/2026       73.03%  2.46        0.55      0.19%      7.15%       4.66%       4.11%         5.51%     5.95%   3.40%       3.49%         5.00%   8.84B  1.24B       -0.32%           -3.73%     509.10M  507.93M  99.77%       0.23%         0.05%   56.50%     -1.68%       2.07%        14.76         10.49M  2.44%   7.62%   3.28%    0.49     0.41       1.28     1.45  28.43%  28.43%   14.05%     2.40%      2.91%      3.45%    13.19%    25.06%   13.17%  0.41  0.84        1.34%        1.39%    2.38%    3.95%    8.14%    0.19%   8.45%    0.00%  25.98%  46.66 - 58.78         0.00%      451.28%  62.10  Jul 31/b  11/19/2003        Yes       Yes     9900.0           -0.02%   0.20%   3.00    711.24K        1.93   1371159         57.26       58.67  58.79  59.08  58.24  58.78   0.19%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
2  463  EERIC  Telefonaktiebolaget L M Ericsson ADR        -         Technology         Communication Equipment  Sweden     NASD     29.90B  12.56        14.80   NaN  1.23   3.02    5.35   9.16     3.25     1.84    3.28%          0.31         4/2/2026            -  0.78        0.15    -40.63%     18.28%       8.75%      -8.29%        -0.90%    -3.10%  -7.93%      56.42%         2.72%  24.30B  2.61B        4.54%           -3.24%       3.05B    3.04B  99.99%       0.00%             -   10.63%     -1.51%       2.14%         5.54         65.23M  8.98%  26.30%  19.10%    1.12     0.89       0.27     0.38  48.13%  13.75%   10.75%   -13.48%    -16.43%    -19.24%     4.69%    33.06%    1.76%  0.96  0.42        3.29%        2.69%  -10.30%  -17.74%   -8.70%  -28.69%  -0.23%  -28.69%  37.25%   7.16 - 13.77       -92.54%     1251.57%  32.71  Jul 14/b   8/24/1981        Yes        No    88826.0           -0.05%  -0.66%   3.04     11.78M        1.49  17534015         10.32        9.89   9.82   9.95   9.78   9.82  -0.71%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -

In [8]:
sorted(df["Ticker"].dropna().astype(str).tolist())

['AA',
 'AAA',
 'AAAL',
 'AAAOI',
 'AAAON',
 'AAAPL',
 'AABBV',
 'AABEV',
 'AABNB',
 'AABT',
 'AABVX',
 'AACA',
 'AACGL',
 'AACI',
 'AACM',
 'AACN',
 'AACWI',
 'AACWX',
 'AADBE',
 'AADC',
 'AADI',
 'AADM',
 'AADP',
 'AADSK',
 'AAEE',
 'AAEG',
 'AAEIS',
 'AAEM',
 'AAEP',
 'AAER',
 'AAES',
 'AAFG',
 'AAFL',
 'AAFRM',
 'AAG',
 'AAGCO',
 'AAGG',
 'AAGI',
 'AAGNC',
 'AAGX',
 'AAHR',
 'AAIG',
 'AAIQ',
 'AAIRR',
 'AAIT',
 'AAIZ',
 'AAJG',
 'AAKAM',
 'AAKRE',
 'AALAB',
 'AALB',
 'AALC',
 'AALGM',
 'AALGN',
 'AALKS',
 'AALL',
 'AALLE',
 'AALLY',
 'AALNY',
 'AALSN',
 'AALV',
 'AAM',
 'AAMAT',
 'AAMCR',
 'AAMD',
 'AAME',
 'AAMG',
 'AAMGN',
 'AAMH',
 'AAMKR',
 'AAMLP',
 'AAMP',
 'AAMRZ',
 'AAMT',
 'AAMX',
 'AAMZN',
 'AANET',
 'AAON',
 'AAOS',
 'AAPA',
 'AAPD',
 'AAPG',
 'AAPGE',
 'AAPH',
 'AAPLD',
 'AAPO',
 'AAPP',
 'AAPTV',
 'AAR',
 'AARCC',
 'AARE',
 'AARES',
 'AARGX',
 'AARKK',
 'AARM',
 'AARMK',
 'AARW',
 'AARWR',
 'AARXS',
 'AAS',
 'AASML',
 'AASND',
 'AASR',
 'AASTS',
 'AASX',
 'AATI',
 'AATO',
 'AATR',
 'AAU',
 'AAUR',
 'AAVAV',
 'AAVB',
 'AAVDE',
 'AAVDV',
 'AAVEM',
 'AAVGO',
 'AAVLV',
 'AAVT',
 'AAVTR',
 'AAVUS',
 'AAVUV',
 'AAVY',
 'AAWK',
 'AAXIA',
 'AAXON',
 'AAXP',
 'AAXS',
 'AAXSM',
 'AAYI',
 'AAZN',
 'AAZO',
 'BB',
 'BBA',
 'BBABA',
 'BBAC',
 'BBAH',
 'BBAI',
 'BBALL',
 'BBAM',
 'BBAP',
 'BBAX',
 'BBBAX',
 'BBBCA',
 'BBBD',
 'BBBEU',
 'BBBIN',
 'BBBIO',
 'BBBJP',
 'BBBUS',
 'BBBVA',
 'BBBY',
 'BBCE',
 'BBCH',
 'BBCS',
 'BBDX',
 'BBE',
 'BBEKE',
 'BBEN',
 'BBEP',
 'BBF-A',
 'BBF-B',
 'BBG',
 'BBHP',
 'BBIDU',
 'BBIIB',
 'BBIL',
 'BBINC',
 'BBIO',
 'BBIP',
 'BBIRK',
 'BBIV',
 'BBJ',
 'BBKLC',
 'BBKLN',
 'BBKNG',
 'BBKR',
 'BBLCR',
 'BBLDR',
 'BBLK',
 'BBLV',
 'BBMNR',
 'BBMO',
 'BBMRN',
 'BBMY',
 'BBN',
 'BBND',
 'BBNDX',
 'BBNS',
 'BBNT',
 'BBNTX',
 'BBNY',
 'BBOKF',
 'BBOND',
 'BBOXX',
 'BBP',
 'BBPOP',
 'BBR',
 'BBRK-A',
 'BBRK-B',
 'BBRKR',
 'BBRO',
 'BBROS',
 'BBRX',
 'BBSAC',
 'BBSBR',
 'BBSP',
 'BBSV',
 'BBSX',
 'BBSY',
 'BBTI',
 'BBTSG',
 'BBUD',
 'BBUFR',
 'BBURL',
 'BBVN',
 'BBWA',
 'BBWXT',
 'BBX',
 'BBXP',
 'CC',
 'CCACI',
 'CCAE',
 'CCAH',
 'CCARR',
 'CCART',
 'CCASY',
 'CCAT',
 'CCAVA',
 'CCB',
 'CCBC',
 'CCBOE',
 'CCBRE',
 'CCBRS',
 'CCBSH',
 'CCCEP',
 'CCCI',
 'CCCJ',
 'CCCK',
 'CCCL',
 'CCDE',
 'CCDNS',
 'CCDP',
 'CCDW',
 'CCEF',
 'CCEG',
 'CCELH',
 'CCF',
 'CCFG',
 'CCFR',
 'CCG',
 'CCGBL',
 'CCGCB',
 'CCGCP',
 'CCGDG',
 'CCGDV',
 'CCGGO',
 'CCGGR',
 'CCGMS',
 'CCGMU',
 'CCGNX',
 'CCGUS',
 'CCGXU',
 'CCHD',
 'CCHKP',
 'CCHRD',
 'CCHRW',
 'CCHT',
 'CCHTR',
 'CCHWY',
 'CCHYM',
 'CCI',
 'CCIB',
 'CCIBR',
 'CCIEN',
 'CCIFR',
 'CCINF',
 'CCL',
 'CCLH',
 'CCLS',
 'CCLX',
 'CCM',
 'CCMC',
 'CCMCSA',
 'CCME',
 'CCMG',
 'CCMI',
 'CCMS',
 'CCNA',
 'CCNC',
 'CCNH',
 'CCNI',
 'CCNM',
 'CCNP',
 'CCNQ',
 'CCOF',
 'CCOHR',
 'CCOIN',
 'CCOKE',
 'CCOLB',
 'CCOMP',
 'CCOO',
 'CCOP',
 'CCOPX',
 'CCOR',
 'CCORO',
 'CCORT',
 'CCOST',
 'CCOWZ',
 'CCP',
 'CCPAY',
 'CCPNG',
 'CCPRT',
 'CCPT',
 'CCQP',
 'CCR',
 'CCRBG',
 'CCRCL',
 'CCRDO',
 'CCRH',
 'CCRL',
 'CCRM',
 'CCRNX',
 'CCRS',
 'CCRWD',
 'CCRWV',
 'CCSCO',
 'CCSGP',
 'CCSL',
 'CCSX',
 'CCTAS',
 'CCTRE',
 'CCTSH',
 'CCTVA',
 'CCUBE',
 'CCVE',
 'CCVNA',
 'CCVS',
 'CCVX',
 'CCW',
 'CCWB',
 'CCX',
 'CCYTK',
 'DD',
 'DDAL',
 'DDAR',
 'DDASH',
 'DDB',
 'DDBEF',
 'DDCI',
 'DDD',
 'DDDOG',
 'DDDS',
 'DDE',
 'DDECK',
 'DDELL',
 'DDEO',
 'DDFAC',
 'DDFAE',
 'DDFAI',
 'DDFAS',
 'DDFAT',
 'DDFAU',
 'DDFAX',
 'DDFCF',
 'DDFEM',
 'DDFIC',
 'DDFIS',
 'DDFIV',
 'DDFLV',
 'DDFSD',
 'DDFSV',
 'DDFUS',
 'DDFUV',
 'DDG',
 'DDGRO',
 'DDGRW',
 'DDGX',
 'DDHI',
 'DDHR',
 'DDIA',
 'DDIHP',
 'DDINO',
 'DDIS',
 'DDIVO',
 'DDKNG',
 'DDKS',
 'DDLN',
 'DDLR',
 'DDLTR',
 'DDOC',
 'DDOCN',
 'DDOCU',
 'DDOV',
 'DDOW',
 'DDPZ',
 'DDRAM',
 'DDRI',
 'DDRS',
 'DDSI',
 'DDT',
 'DDTE',
 'DDTM',
 'DDUHP',
 'DDUK',
 'DDVA',
 'DDVN',
 'DDVY',
 'DDXCM',
 'DDXJ',
 'DDY',
 'DDYNF',
 'EE',
 'EEA',
 'EEAGG',
 'EEAT',
 'EEBAY',
 'EEC',
 'EECHO',
 'EECL',
 'EED',
 'EEDU',
 'EEEM',
 'EEFA',
 'EEFAV',
 'EEFG',
 'EEFV',
 'EEFX',
 'EEG',
 'EEGO',
 'EEGP',
 'EEHC',
 'EEIX',
 'EEL',
 'EELAN',
 'EELPC',
 'EELS',
 'EELV',
 'EEMA',
 'EEMB',
 'EEMBJ',
 'EEME',
 'EEMN',
 'EEMR',
 'EEMXC',
 'EENB',
 'EENLT',
 'EENS',
 'EENSG',
 'EENTG',
 'EEOG',
 'EEPD',
 'EEPRT',
 'EEQH',
 'EEQIX',
 'EEQNR',
 'EEQR',
 'EEQT',
 'EERIC',
 'EERIE',
 'EES',
 'EESE',
 'EESGD',
 'EESGE',
 'EESGU',
 'EESGV',
 'EESI',
 'EESLT',
 'EESS',
 'EET',
 'EETHA',
 'EETN',
 'EETR',
 'EETSY',
 'EEVR',
 'EEVRG',
 'EEVTR',
 'EEW',
 'EEWBC',
 'EEWC',
 'EEWJ',
 'EEWT',
 'EEWY',
 'EEWZ',
 'EEXC',
 'EEXE',
 'EEXEL',
 'EEXPD',
 'EEXPE',
 'EEXR',
 'EEZU',
 'FF',
 'FFAF',
 'FFANG',
 'FFAST',
 'FFBCG',
 'FFBND',
 'FFBTC',
 'FFCFS',
 'FFCNCA',
 'FFCX',
 'FFDL',
 'FFDN',
 'FFDS',
 'FFDVV',
 'FFDX',
 'FFDXF',
 'FFE',
 'FFELC',
 'FFELG',
 'FFENI',
 'FFER',
 'FFERG',
 'FFESM',
 'FFFIV',
 'FFHN',
 'FFICO',
 'FFIG',
 'FFIS',
 'FFISV',
 'FFITB',
 'FFIVE',
 'FFIX',
 'FFLEX',
 'FFLOT',
 'FFLS',
 'FFLUT',
 'FFMDE',
 'FFMS',
 'FFMX',
 'FFN',
 'FFNDA',
 'FFNDE',
 'FFNDF',
 'FFNDX',
 'FFNF',
 'FFNV',
 'FFORM',
 'FFOX',
 'FFOXA',
 'FFPE',
 'FFPS',
 'FFR',
 'FFRHC',
 'FFRO',
 'FFROG',
 'FFRT',
 'FFRVO',
 'FFSLR',
 'FFSS',
 'FFTAI',
 'FFTCS',
 'FFTEC',
 'FFTI',
 'FFTNT',
 'FFTS',
 'FFTSM',
 'FFTV',
 'FFUTU',
 'FFVD',
 'FFWONA',
 'FFWONK',
 'GGAP',
 'GGBIL',
 'GGBTC',
 'GGD',
 'GGDDY',
 'GGDX',
 'GGDXJ',
 'GGE',
 'GGEHC',
 'GGEN',
 'GGEV',
 'GGFI',
 'GGFL',
 'GGFS',
 'GGGG',
 'GGH',
 'GGIB',
 'GGIL',
 'GGILD',
 'GGIS',
 'GGKOS',
 'GGL',
 'GGLD',
 'GGLDM',
 'GGLPI',
 'GGLW',
 'GGLXY',
 'GGM',
 'GGMAB',
 'GGME',
 'GGMED',
 'GGNRC',
 'GGOOG',
 'GGOOGL',
 'GGOVT',
 'GGPC',
 'GGPIQ',
 'GGPIX',
 'GGPN',
 'GGRAB',
 'GGRID',
 'GGRMN',
 'GGS',
 'GGSAT',
 'GGSIE',
 'GGSK',
 'GGSLC',
 'GGTLS',
 'GGUNR',
 'GGWRE',
 'GGWW',
 'HH',
 'HHAL',
 'HHALO',
 'HHAS',
 'HHBAN',
 'HHBM',
 'HHCA',
 'HHD',
 'HHDB',
 'HHDV',
 'HHEFA',
 'HHEI',
 'HHEI-A',
 'HHESM',
 'HHIG',
 'HHII',
 'HHIMS',
 'HHL',
 'HHLI',
 'HHLN',
 'HHLT',
 'HHMC',
 'HHMY',
 'HHON',
 'HHONA',
 'HHOOD',
 'HHPE',
 'HHPQ',
 'HHQY',
 'HHR',
 'HHRL',
 'HHSAI',
 'HHSBC',
 'HHSIC',
 'HHST',
 'HHSY',
 'HHTHT',
 'HHUBB',
 'HHUBS',
 'HHUM',
 'HHUT',
 'HHWM',
 'HHXL',
 'HHYG',
 'IIAG',
 'IIAGG',
 'IIALT',
 'IIAU',
 'IIAUM',
 'IIBB',
 'IIBIT',
 'IIBKR',
 'IIBM',
 'IIBN',
 'IIBRX',
 'IICE',
 'IICLR',
 'IICSH',
 'IICVT',
 'IIDA',
 'IIDEV',
 'IIDV',
 'IIDXX',
 'IIEF',
 'IIEFA',
 'IIEI',
 'IIEMG',
 'IIESC',
 'IIEUR',
 'IIEX',
 'IIFF',
 'IIGF',
 'IIGIB',
 'IIGM',
 'IIGSB',
 'IIGV',
 'IIHG',
 'IIJH',
 'IIJJ',
 'IIJK',
 'IIJR',
 'IIJS',
 'IIJT',
 'IILMN',
 'IIMO',
 'IIMVT',
 'IINCY',
 'IINDA',
 'IINFY',
 'IING',
 'IINIO',
 'IINSM',
 'IINTC',
 'IINTU',
 'IINVH',
 'IIONQ',
 'IIONS',
 'IIOO',
 'IIOT',
 'IIP',
 'IIQLT',
 'IIQMM',
 'IIQV',
 'IIR',
 'IIREN',
 'IIRM',
 'IISRG',
 'IISTB',
 'IIT',
 'IITA',
 'IITOT',
 'IITT',
 'IITUB',
 'IITW',
 'IIUSB',
 'IIUSG',
 'IIUSV',
 'IIVE',
 'IIVV',
 'IIVW',
 'IIVZ',
 'IIWB',
 'IIWD',
 'IIWF',
 'IIWM',
 'IIWN',
 'IIWO',
 'IIWP',
 'IIWR',
 'IIWS',
 'IIWV',
 'IIWY',
 'IIX',
 'IIXN',
 'IIXUS',
 'IIYW',
 'JJ',
 'JJAAA',
 'JJAN',
 'JJAVA',
 'JJAZZ',
 'JJBHT',
 'JJBL',
 'JJBND',
 'JJBS',
 'JJBTM',
 'JJCI',
 'JJCPB',
 'JJD',
 'JJEF',
 'JJEPI',
 'JJEPQ',
 'JJGLO',
 'JJGRO',
 'JJHMM',
 'JJHX',
 'JJIRE',
 'JJKHY',
 'JJLL',
 'JJMBS',
 'JJMST',
 'JJMTG',
 'JJMUB',
 'JJNJ',
 'JJNK',
 'JJOBY',
 'JJPIE',
 'JJPM',
 'JJPST',
 'JJQUA',
 'JJXN',
 'KKB',
 'KKBWB',
 'KKDP',
 'KKEP',
 'KKEX',
 'KKEY',
 'KKEYS',
 'KKGC',
 'KKHC',
 'KKIM',
 'KKKR',
 'KKLAC',
 'KKLAR',
 'KKMB',
 'KKMI',
 'KKMX',
 'KKNSL',
 'KKNTK',
 'KKNX',
 'KKO',
 'KKR',
 'KKRE',
 'KKRYS',
 'KKSPI',
 'KKT',
 'KKTOS',
 'KKVUE',
 'KKWEB',
 'KKYMR',
 'LL',
 'LLAD',
 'LLAMR',
 'LLDOS',
 'LLEA',
 'LLECO',
 'LLEN',
 'LLEVI',
 'LLFUS',
 'LLGN',
 'LLH',
 'LLHX',
 'LLI',
 'LLII',
 'LLIN',
 'LLINE',
 'LLITE',
 'LLLY',
 'LLLYVA',
 'LLLYVK',
 'LLMBS',
 'LLMT',
 'LLNC',
 'LLNG',
 'LLNT',
 'LLNTH',
 'LLOGI',
 'LLOW',
 'LLPLA',
 'LLQD',
 'LLQDA',
 'LLRCX',
 'LLSCC',
 'LLSTR',
 'LLTH',
 'LLTM',
 'LLULU',
 'LLUV',
 'LLVHI',
 'LLVS',
 'LLYB',
 'LLYG',
 'LLYV',
 'MMA',
 'MMAA',
 'MMAAS',
 'MMAC',
 'MMAIR',
 'MMANH',
 'MMAR',
 'MMAS',
 'MMBB',
 'MMBLY',
 'MMCD',
 'MMCHI',
 'MMCHP',
 'MMCK',
 'MMCO',
 'MMDB',
 'MMDGL',
 'MMDLN',
 'MMDLZ',
 'MMDT',
 'MMDY',
 'MMEDP',
 'MMELI',
 'MMET',
 'MMETA',
 'MMFC',
 'MMFG',
 'MMGA',
 'MMGC',
 'MMGK',
 'MMGM',
 'MMGV',
 'MMICC',
 'MMINT',
 'MMIRM',
 'MMKC',
 'MMKL',
 'MMKSI',
 'MMLI',
 'MMLM',
 'MMMM',
 'MMNST',
 'MMO',
 'MMOAT',
 'MMOD',
 'MMOG-A',
 'MMOH',
 'MMOS',
 'MMP',
 'MMPC',
 'MMPLX',
 'MMPWR',
 'MMRK',
 'MMRNA',
 'MMRSH',
 'MMRVL',
 'MMS',
 'MMSCI',
 'MMSFT',
 'MMSGS',
 'MMSI',
 'MMSTR',
 'MMT',
 'MMTB',
 'MMTCH',
 'MMTD',
 'MMTSI',
 'MMTUM',
 'MMTZ',
 'MMU',
 'MMUB',
 'MMUFG',
 'MMUSA',
 'NNBIS',
 'NNBIX',
 'NNCLH',
 'NNDAQ',
 'NNDSN',
 'NNEE',
 'NNEM',
 'NNET',
 'NNEU',
 'NNFG',
 'NNFLX',
 'NNGG',
 'NNI',
 'NNIO',
 'NNKE',
 'NNLY',
 'NNMR',
 'NNNN',
 'NNOBL',
 'NNOC',
 'NNOK',
 'NNOV',
 'NNOW',
 'NNRG',
 'NNSC',
 'NNTAP',
 'NNTES',
 'NNTNX',
 'NNTR',
 'NNTRA',
 'NNTRS',
 'NNU',
 'NNUE',
 'NNUVL',
 'NNVDA',
 'NNVMI',
 'NNVO',
 'NNVR',
 'NNVS',
 'NNVT',
 'NNWG',
 'NNWS',
 'NNWSA',
 'NNXPI',
 'NNXT',
 'NNYT',
 'OO',
 'OOC',
 'OODFL',
 'OOEF',
 'OOGE',
 'OOHI',
 'OOKE',
 'OOKLO',
 'OOKTA',
 'OOMC',
 'OON',
 'OONB',
 'OONC',
 'OONEQ',
 'OONON',
 'OONTO',
 'OORCL',
 'OORI',
 'OORLY',
 'OOSCR',
 'OOSK',
 'OOTIS',
 'OOVV',
 'OOWL',
 'OOXY',
 'PP',
 ...]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Columns: 111 entries, No. to Tags
dtypes: float64(32), int64(2), object(77)
memory usage: 1.3+ MB

In [ ]:
# Sort df by 'Market Cap' from largest to smallest
if df is not None:
  sort_col_m = "Market Cap, M"
  if sort_col_m in df.columns:
    df.sort_values(by=sort_col_m, ascending=False, inplace=True, na_position="last")
  else:
    tmp_sort = "_market_cap_sort_m"
    if "convert_to_millions" in globals():
      df[tmp_sort] = df["Market Cap"].apply(convert_to_millions)
    else:
      def _to_millions(val):
        if pd.isna(val):
          return np.nan
        s = str(val).strip().upper()
        if not s:
          return np.nan
        mul = {"T": 1_000_000, "B": 1_000, "M": 1, "K": 0.001}
        suf = s[-1]
        if suf in mul:
          try:
            return float(s[:-1]) * mul[suf]
          except Exception:
            return np.nan
        return np.nan
      df[tmp_sort] = df["Market Cap"].apply(_to_millions)

    df.sort_values(by=tmp_sort, ascending=False, inplace=True, na_position="last")
    df.drop(columns=[tmp_sort], inplace=True)

  print("Sorted by Market Cap (largest -> smallest).")
  display(df[["Market Cap"]].head(10))

In [9]:
df.head(20)

    No. Ticker                               Company         Index                  Sector                            Industry     Country Exchange Market Cap    P/E  Forward P/E   PEG    P/S    P/B     P/C   P/FCF  Book/sh  Cash/sh Dividend  Dividend TTM Dividend Ex Date Payout Ratio    EPS  EPS next Q EPS This Y EPS Next Y EPS Past 5Y EPS Next 5Y Sales Past 5Y Sales Q/Q   EPS Q/Q EPS YoY TTM Sales YoY TTM   Sales    Income EPS Surprise Revenue Surprise Outstanding    Float Float % Insider Own Insider Trans Inst Own Inst Trans Short Float  Short Ratio Short Interest     ROA     ROE    ROIC  Curr R  Quick R  LTDebt/Eq  Debt/Eq Gross M  Oper M Profit M Perf Week Perf Month Perf Quart Perf Half Perf Year Perf YTD  Beta    ATR Volatility W Volatility M    SMA20    SMA50   SMA200 50D High 50D Low 52W High  52W Low         52W Range All-Time High All-Time Low    RSI  Earnings    IPO Date Optionable Shortable  Employees Change from Open     Gap  Recom Avg Volume  Rel Volume    Volume  Target Price  Prev Close     Open     High      Low    Price  Change Single Category Asset Type Expense  Holdings AUM  Flows 1M Flows% 1M  Flows 3M Flows% 3M Flows YTD Flows% YTD Return% 1Y Return% 3Y Return% 5Y Tags
0   461   LLVS                  Las Vegas Sands Corp       S&P 500       Consumer Cyclical                   Resorts & Casinos         USA     NYSE     30.06B  16.79        12.66  1.69   2.19  25.10    9.03   13.61     1.81     5.03    2.48%          1.10         5/5/2026       42.59%   2.70        0.76      9.52%      8.73%           -       7.51%        34.66%    25.26%    71.16%      50.79%        22.67%  13.74B     1.84B       20.31%            6.64%     663.00M  274.72M  41.44%      58.54%        -0.02%   42.23%     -0.86%       6.57%         3.90         18.05M   8.68%  94.53%  12.20%    0.92     0.91      11.60    13.13  38.37%  24.64%   13.41%    -2.85%     -7.32%    -20.01%   -24.27%    -7.30%  -30.31%  0.85   1.21        2.32%        2.47%   -2.42%   -7.64%  -19.10%  -16.95%   2.58%  -35.62%    2.58%     44.22 - 70.45       -67.54%     3399.34%  37.02  Jul 22/a  12/15/2004        Yes       Yes    41500.0           -0.50%  -0.24%   1.57      4.63M        0.93   4296079         66.73       45.70    45.59    45.70    45.02    45.36  -0.74%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
1   462   FFTS                            Fortis Inc             -               Utilities      Utilities - Regulated Electric      Canada     NYSE     29.92B  23.94        21.09  5.13   3.39   1.83  116.33     NaN    32.03     0.51    3.17%          1.83        5/15/2026       73.03%   2.46        0.55      0.19%      7.15%       4.66%       4.11%         5.51%     5.95%     3.40%       3.49%         5.00%   8.84B     1.24B       -0.32%           -3.73%     509.10M  507.93M  99.77%       0.23%         0.05%   56.50%     -1.68%       2.07%        14.76         10.49M   2.44%   7.62%   3.28%    0.49     0.41       1.28     1.45  28.43%  28.43%   14.05%     2.40%      2.91%      3.45%    13.19%    25.06%   13.17%  0.41   0.84        1.34%        1.39%    2.38%    3.95%    8.14%    0.19%   8.45%    0.00%   25.98%     46.66 - 58.78         0.00%      451.28%  62.10  Jul 31/b  11/19/2003        Yes       Yes     9900.0           -0.02%   0.20%   3.00    711.24K        1.93   1371159         57.26       58.67    58.79    59.08    58.24    58.78   0.19%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
2   463  EERIC  Telefonaktiebolaget L M Ericsson ADR             -              Technology             Communication Equipment      Sweden     NASD     29.90B  12.56        14.80   NaN   1.23   3.02    5.35    9.16     3.25     1.84    3.28%          0.31         4/2/2026            -   0.78        0.15    -40.63%     18.28%       8.75%      -8.29%        -0.90%    -3.10%    -7.93%      56.42%         2.72%  24.30B     2.61B        4.54%           -3.24%       3.05B    3.04B  99.99%       0.00%             -   10.63%     -1.51%       2.14%         5.54         65.23M   8.98%  26.30%  19.10%    1.12     0.89       0.27     0.38  48.13%  13.75%   10.75%   -13.48%    -16.43%    -19.24%     4.69%    33.06%    1.76%  0.96   0.42        3.29%        2.69%  -10.30%  -17.74%   -8.70%  -28.69%  -0.23%  -28.69%   37.25%      7.16 - 13.77       -92.54%     1251.57%  32.71  Jul 14/b   8/24/1981        Yes        No    88826.0           -0.05%  -0.66%   3.04     11.78M        1.49  17534015         10.32        9.89     9.82     9.95     9.78     9.82  -0.71%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
3   464   EEIX                  Edison International       S&P 500               Utilities      Utilities - Regulated Electric         USA     NYSE     29.87B   8.42        11.91  6.58   1.52   1.73  177.81     NaN    44.80     0.44    4.51%          3.46         7/7/2026       29.09%   9.22        1.20     -6.49%      6.42%      42.36%       1.81%         7.31%     7.66%   -63.09%      30.35%        13.14%  19.61B     3.55B        7.58%           -1.21%     384.79M  384.11M  99.82%       0.17%        -1.46%   95.60%     -0.95%       3.56%         5.35         13.66M   4.05%  21.80%   6.65%    0.74     0.68       2.21     2.47  32.09%  27.90%   18.12%     3.23%      7.73%      8.42%    25.98%    51.24%   29.34%  0.65   1.65        2.55%        2.08%    3.45%    7.13%   17.87%   -0.83%  19.39%   -0.83%   53.48%     50.58 - 78.28       -12.55%     1142.08%  65.20  Jul 30/a   5/27/1926        Yes       Yes    13725.0           -1.99%   1.49%   2.67      2.55M        0.97   2483774         76.50       78.05    79.21    79.88    77.19    77.63  -0.54%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
4   465  BBIDU                         Baidu Inc ADR             -  Communication Services      Internet Content & Information       China     NASD     29.84B    NaN        12.74  1.49   1.65   0.94    1.75     NaN   114.39    61.12    1.66%           NaN                -        0.00%  -0.02        1.61     -8.82%     17.05%     -29.62%       8.54%         2.97%     3.87%   -51.49%     -98.39%        -2.40%  18.13B    61.25M        4.23%            2.11%     278.23M  278.09M  99.95%       0.05%       -46.84%   19.84%     -5.86%       4.22%         4.58         11.72M   0.10%   0.16%   0.13%    1.85     1.85       0.24     0.35  42.06%   7.04%    0.34%    -8.76%     -4.86%    -14.23%   -28.74%    22.55%  -17.92%  0.58   5.01        3.35%        3.24%   -4.30%  -12.96%  -15.53%  -29.62%   6.90%  -35.12%   26.70%    84.64 - 165.30       -69.78%     2313.14%  39.36  May 18/b    8/5/2005        Yes       Yes    33500.0           -0.71%  -4.26%   1.53      2.56M        0.95   2429542        172.38      112.82   108.01   108.99   106.98   107.24  -4.95%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
5   466  CCPNG                           Coupang Inc             -       Consumer Cyclical                     Internet Retail         USA     NYSE     29.83B    NaN        47.06  0.52   0.85   7.65    4.67  104.54     2.17     3.56        -           NaN                -        0.00%  -0.09       -0.25   -347.53%    229.70%           -      89.91%        23.61%     7.54%  -350.77%    -163.64%        13.10%  35.13B  -165.00M      -60.60%            0.32%       1.65B    1.24B  74.82%      31.19%         1.33%   57.52%     -3.81%       6.47%         3.33         79.87M  -0.99%  -3.97%  -2.32%    0.97     0.76       0.81     1.37  28.81%   0.33%   -0.47%   -11.60%     -7.82%    -22.66%   -20.06%   -46.65%  -29.55%  1.12   0.79        4.20%        4.55%   -7.17%   -2.20%  -24.18%  -20.59%  11.39%  -51.23%   11.39%     14.92 - 34.08       -75.91%       85.08%  41.42  May 05/a   3/11/2021        Yes       Yes   108000.0           -0.12%  -1.30%   1.74     23.99M        0.68  16334899         25.26       16.86    16.64    16.90    16.41    16.62  -1.42%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
6   467   PPBA                 Pembina Pipeline Corp             -                  Energy                 Oil & Gas Midstream      Canada     NYSE     29.82B  26.59        22.52  3.28   5.50   2.74  240.55   20.90    18.71     0.21    4.06%          2.08        6/15/2026      105.70%   1.93        0.52     11.61%      4.22%           -       6.86%         4.37%    -4.04%     5.06%     -12.24%        -5.12%   5.42B     1.12B       11.22%            4.90%     581.00M  580.72M  99.95%       0.12%         0.00%   58.04%     -4.55%       1.50%         7.18          8.69M   4.82%  10.06%   5.66%    0.83     0.68       0.78     0.82  36.76%  31.05%   20.70%     7.87%      8.87%     18.62%    33.78%    37.91%   34.76%  0.58   0.92        1.38%        1.75%    7.28%    7.18%   20.09%    0.31%  15.99%    0.31%   44.68%     35.45 - 51.13         0.31%      384.78%  70.51  Jul 30/a   10/6/2010        Yes       Yes     2974.0           -0.45%   1.10%   1.83      1.21M        0.78    945155         50.13       50.96    51.52    51.56    50.97    51.29   0.65%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
7   468    EEL                 Estee Lauder Cos. Inc       S&P 500      Consumer Defensive       Household & Personal Products         USA     NYSE     29.71B    NaN        25.83  0.71   2.00   7.44    9.51   23.12    11.04     8.64    1.75%          1.40        5/29/2026            -  -0.70        0.32     61.23%     30.60%           -      36.48%         0.04%     5.00%   -44.64%      71.47%         0.71%  14.85B  -248.00M       40.41%            0.62%     247.29M  246.48M  99.67%      31.87%         0.00%   66.28%      0.33%       3.22%         2.23          7.93M  -1.25%  -5.95%  -2.00%    1.27     0.94       2.10     2.33  74.73%  10.38%   -1.67%    -0.64%     -6.22%      9.01%   -29.75%    -5.12%  -21.57%  1.25   2.96        3.45%        3.60%   -0.33%   -1.95%  -11.36%  -11.07%   9.12%  -32.48%   24.03%    66.22 - 121.64       -78.05%      934.71%  47.89  May 01/b  11/17/1995        Yes       Yes    57000.0            0.61%  -1.46%   2.26      3.55M        0.69   2448180         94.16       82.84    81.63    83.57    80.92    82.13  -0.86%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
8   469   AATO                     Atmos Energy Corp       S&P 500               Utilities           Utilities - Regulated Gas         USA     NYSE     29.66B  21.87        19.71  2.08   6.08   1.99  233.33     NaN    89.32     0.76    2.25%          3.87        5/26/2026       46.63%   8.12        1.33     13.08%      6.88%       8.82%       9.48%        10.76%     0.61%    14.58%      13.54%         8.81%   4.88B     1.35B        1.82%            1.12%     166.92M  166.16M  99.54%       0.46%         0.00%   99.35%     -0.33%       2.18%         2.61          3.62M   4.69%   9.60%   5.49%    1.00     0.89       0.65     0.65  45.38%  35.87%   27.57%     0.84%      4.75%     -5.48%     5.31%    14.43%    6.00%  0.60   3.23        2.02%        1.64%    1.61%    1.83%    0.85%   -6.58%   6.82%   -7.70%   15.42%   153.94 - 192.51        -7.70%     3395.34%  55.34  Aug 05/a  12/28/1983        Yes       Yes     5487.0            0.93%  -1.12%   2.59      1.39M        1.07   1483153        190.09      178.04   176.04   181.47   176.04   177.68  -0.20%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
9   470  DDXCM                            Dexcom Inc  NDX, S&P 500              Healthcare                     Medical Devices         USA     NASD     29.58B  32.78        24.81  1.19   6.14  10.00   12.25   20.69     7.66     6.26        -           NaN                -        0.00%   2.34        0.61     24.09%     19.14%      10.55%      20.88%        19.33%    15.05%    92.21%      76.15%        16.15%   4.82B   930.40M       20.27%            1.47%     385.90M  379.12M  98.24%       1.75%        -1.14%   98.52%      0.99%       4.78%         3.16         18.11M  13.90%  35.62%  21.53%    1.95     1.64       0.46     0.47  62.64%  21.45%   19.31%     2.25%      4.77%     25.18%     9.97%    -8.86%   15.49%  1.43   2.81        4.15%        3.59%    6.29%    8.76%   13.81%   -3.16%  32.95%  -14.81%   41.66%     54.11 - 89.98       -53.51%    22444.12%  59.08  Jul 30/a   4/14/2005        Yes       Yes    11100.0           -1.55%  -0.15%   1.40      5.73M        0.89   5069951         86.04       77.98    77.86    78.01    75.95    76.65  -1.71%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
10  471   TTDY             Teledyne Technologies Inc       S&P 500              Technology  Scientific & Technical Instruments         USA     NYSE     29.44B  32.16        24.41  2.85   4.73   2.75   56.47   27.94   231.05    11.25        -           NaN                -        0.00%  19.76        5.79      9.88%      7.76%      12.23%       8.57%        14.84%     7.50%    21.54%      12.76%         7.74%   6.22B   933.00M        5.96%            2.96%      46.33M   45.93M  99.14%       0.87%        -2.77%   99.14%      1.10%       3.45%         4.67          1.59M   6.11%   9.05%   7.33%    1.76     1.16       0.19     0.23  39.29%  19.01%   14.99%     0.14%      0.86%     -0.04%    12.97%    13.69%   24.43%  0.92  18.98        3.01%        3.07%    0.29%    1.49%    6.72%   -5.80%   6.00%   -8.34%   31.57%   483.02 - 693.38        -8.34%     8034.66%  52.23  Jul 22/b  11/23/1999        Yes       Yes    15800.0            3.47%  -2.64%   1.67    339.35K        0.92    312732        740.58      630.86   614.22   637.83   610.00   635.52   0.74%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
11  472   HHAL                        Halliburton Co       S&P 500                  Energy      Oil & Gas Equipment & Services         USA     NYSE     29.42B  19.32        12.03  0.99   1.33   2.73   14.69   17.53    12.91     2.40    1.98%          0.68         6/3/2026       45.21%   1.82        0.54     -2.25%     23.75%           -      12.10%         8.96%    -0.28%   133.23%     -23.60%        -1.72%  22.17B     1.54B       10.33%            1.80%     835.00M  831.59M  99.59%       0.46%       -14.92%   83.87%      1.10%       3.81%         2.66         31.71M   6.12%  14.56%   8.31%    2.08     1.54       0.72     0.75  15.28%  13.46%    6.95%     2.41%     -5.32%     -7.68%     6.60%    63.51%   24.63%  0.74   1.03        2.71%        2.73%    2.32%   -7.11%    5.77%  -19.20%   8.07%  -19.20%   74.62%     20.17 - 43.59       -52.62%      750.07%  46.58  Jul 21/b   9/15/1948        Yes       Yes    46000.0           -0.20%   0.71%   1.91     11.92M        0.72   8618035         44.46       35.04    35.29    35.36    34.78    35.22   0.51%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
12  473  TTCOM                Trip.com Group Ltd ADR             -       Consumer Cyclical                     Travel Services   Singapore     NASD     29.27B   6.68        10.12   NaN   3.21   1.23    2.50     NaN    34.64    17.01    0.17%           NaN        3/17/2025        0.00%   6.35        0.89    -46.69%     16.84%           -     -11.48%        26.75%    23.16%   -36.76%      87.04%        19.28%   9.13B     4.41B       -5.69%            1.70%     689.45M  640.21M  92.86%           -             -   22.48%     -3.91%       2.06%         4.17         13.19M  12.21%  20.05%  17.28%    1.53     1.53       0.07     0.19  80.31%  24.91%   48.36%    -0.82%     -8.18%    -22.38%   -32.38%   -31.88%  -40.97% -0.01   1.39        2.09%        2.86%    0.14%   -8.22%  -27.95%  -22.11%  11.59%  -46.26%   11.59%     38.04 - 78.99       -46.26%     2898.68%  43.93  Jun 24/a   12/9/2003        Yes       Yes    43574.0           -1.10%  -1.90%   1.47      3.17M        1.25   3965240         60.79       43.75    42.92    43.54    42.12    42.45  -2.97%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
13  474   XXYL                             Xylem Inc       S&P 500             Industrials      Specialty Industrial Machinery         USA     NYSE     29.18B  30.50        20.15  2.01   3.21   2.68   36.12   31.41    45.89     3.40    1.28%          1.66        5/28/2026       40.79%   4.03        1.34      9.11%      9.96%      22.83%      10.01%        13.14%     2.71%    14.41%       8.05%         5.64%   9.08B   981.00M        3.24%            0.72%     239.10M  236.85M  99.06%       0.35%        -0.37%   96.14%     -2.52%       3.33%         3.75          7.88M   5.85%   9.00%   7.92%    1.46     1.10       0.13     0.19  38.48%  14.68%   10.80%     1.29%      9.60%     -1.94%   -12.36%    -7.31%   -9.84%  1.02   2.84        2.53%        2.33%    4.03%    8.29%   -5.39%   -2.33%  16.61%  -20.41%   16.61%   105.29 - 154.27       -20.41%      447.39%  64.10  Jul 28/b  10/13/2011        Yes       Yes    22000.0           -1.78%  -0.23%   1.77      2.10M        1.30   2736736        152.44      125.30   125.01   126.76   122.66   122.78  -2.01%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -
14  475  FFICO                       Fair Isaac Corp       S&P 500              Technology              Software - Application         USA     NYSE     29.15B  39.83        23.16  0.80  12.92    NaN  132.87   34.17   -90.22     9.46        -           NaN         3/1/2017        0.00%  31.56       11.71     43.97%     26.16%      27.43%      29.12%         8.99%    38.69%    69.04%      34.99%        22.57%   2.26B   759.63M       14.76%            9.75%      23.30M   22.47M  96.44%       3.10%        -0.12%   94.97%      0.75%       9.70%         6.37          2.18M  39.12%       -  48.85%    2.22     2.22        NaN      NaN  84.16%  50.85%   33.67%     0.50%      5.97%     17.49%   -22.22%   -17.58%  -25.64%  1.29  52.78        4.17%        4.12%    3.98%    5.47%  -10.15%   -5.88%  20.90%  -37.08%   44.49%  870.01 - 1998.01       -47.68%   226179.79%  56.22  Jul 29/a   7/22/1987        Yes       Yes     3811.0            1.96%  -0.67%   1.96    342.03K        0.74    251465       1507.50     1241.22  1232.89  1260.21  1219.97  1257.11   1.28%               -          -       -       NaN   -       NaN         -       NaN         -         -          -          -          -          -    -

### Step 2: Feature Engineering - Create Composite Columns

Combine existing columns to create more meaningful features: `Info` and `MktCap AUM`.

In [ ]:
if df is not None:
    print("\n--- Step 2: Engineering new features ---")

    # 1. Create 'Info' column by concatenating category columns.
    for col in INFO_COLS:
        if col in df.columns:
            df[col] = df[col].replace("-", "")
    df["Info"] = df[INFO_COLS].apply(
        lambda row: ", ".join(filter(None, row.astype(str))), axis=1
    )
    print("Created 'Info' column.")

    # 2. Create 'MktCap AUM' by concatenating 'Market Cap' and 'AUM'.
    # This combines stock and ETF liquidity metrics into a single string column for now.
    # It will be converted to numeric in the next step.
    df["MktCap AUM"] = df["Market Cap"].replace("-", "") + df["AUM"].replace("-", "")
    print("Created 'MktCap AUM' column.")

    # Display the new columns for verification
    display(df[["Ticker", "Info", "MktCap AUM"]].head(3))

### Step 3: Data Type Conversion

This multi-part step cleans and converts all string-based numeric and percentage columns into proper numeric types.

#### Part A: Convert Abbreviated Currency Columns to Millions

In [ ]:
def convert_to_millions(value: str) -> float:
    """Converts a string with a T/B/M/K suffix to a numeric value in millions."""
    if pd.isna(value):
        return np.nan

    value_str = str(value).strip().upper()
    if not value_str:
        return np.nan

    multipliers = {"T": 1_000_000, "B": 1_000, "M": 1, "K": 0.001}
    suffix = value_str[-1]

    if suffix in multipliers:
        number_part = value_str[:-1]
        try:
            return float(number_part) * multipliers[suffix]
        except (ValueError, TypeError):
            return np.nan
    return np.nan


if df is not None:
    print("\n--- Step 3a: Converting currency columns to millions ---")
    new_names = {}
    for col in CURRENCY_COLS:
        if col in df.columns:
            df[col] = df[col].apply(convert_to_millions)
            new_names[col] = f"{col}, M"

    df.rename(columns=new_names, inplace=True)
    print(f"Converted and renamed {len(new_names)} columns.")
    display(df[[name for name in new_names.values() if name in df.columns]].head(3))

#### Part B: Convert Percentage Columns to Numeric

In [ ]:
if df is not None:
    print("\n--- Step 3b: Converting percentage columns ---")
    percent_cols = [
        col
        for col in df.columns
        if df[col].dtype == "object" and df[col].str.endswith("%", na=False).any()
    ]

    if not percent_cols:
        print("No new percentage columns found to modify.")
    else:
        print("Processing the following percentage columns:")
        for col in percent_cols:
            df[col] = pd.to_numeric(df[col].str.replace("%", ""), errors="coerce")
            new_name = f"{col} %" if "%" not in col else col
            df.rename(columns={col: new_name}, inplace=True)
            print(f"  - Converted '{col}' to numeric and renamed to '{new_name}'")

#### Part C: Convert Other String-Based Numeric Columns

In [ ]:
if df is not None:
    print("\n--- Step 3c: Converting other numeric string columns ---")
    converted_count = 0
    for col in OTHER_NUMERIC_COLS:
        if col in df.columns and df[col].dtype == "object":
            df[col] = pd.to_numeric(
                df[col].str.replace(",", "", regex=False), errors="coerce"
            )
            converted_count += 1

    print(f"Converted {converted_count} additional columns to numeric type.")
    print("\nData types after all conversions:")
    df.info()

### Step 4: Final Processing - Sort, Index, and Rank

Sort the DataFrame by the unified liquidity metric, set the `Ticker` as the index, and add a final `Rank`.

In [ ]:
if df is not None:
    print("\n--- Step 4: Finalizing DataFrame ---")

    # 1. Sort by the primary metric in descending order
    df.sort_values(
        by="MktCap AUM, M", ascending=False, inplace=True, na_position="last"
    )
    print("Sorted DataFrame by 'MktCap AUM, M'.")

    # 2. Add a 'Rank' column based on the new sort order
    df["Rank"] = range(1, len(df) + 1)
    print("Added 'Rank' column.")

    # 3. Set 'Ticker' as the index
    if "Ticker" in df.columns:
        df.set_index("Ticker", inplace=True)
        print("Set 'Ticker' as the index.")

    print("\nFinal DataFrame structure:")
    display(df[["Rank", "Info", "MktCap AUM, M"]].head())

### Step 5: Save and Verify Cleaned Data

Save the final, cleaned DataFrame to a new Parquet file and read it back to verify integrity.

In [ ]:
if df is not None:
    print("\n--- Step 5: Saving and verifying data ---")
    try:
        # Ensure destination directory exists
        DEST_PATH.parent.mkdir(parents=True, exist_ok=True)

        # Save the file
        df.to_parquet(DEST_PATH, engine="pyarrow", compression="zstd")
        print(f"Successfully saved cleaned data to: {DEST_PATH}")

        # Verify by loading it back
        loaded_df = pd.read_parquet(DEST_PATH, engine="pyarrow")
        print("\nVerification successful. First 20 rows of the saved file:")
        display(loaded_df.head(20))

    except Exception as e:
        print(f"An error occurred during save or verification: {e}")